// Expanded Symptoms Database - Cardiovascular, Respiratory, and GI Systems
// Contains additional symptoms not in the main symptom-database.ts

// Re-declaring SymptomEntry interface for standalone use
export interface SymptomEntry {
  symptomId: string;
  name: string;
  spanishName: string;
  description: string;
  spanishDescription: string;
  bodyRegions: string[];
  bodySystems: string[];
  severity: number; // 1-10 scale
  possibleCauses: string[];
  redFlags: string[];
  associatedSymptoms: string[];
  commonAge: string;
  prevalence: string;
}

export const EXPANDED_SYMPTOMS_CV_RESP_GI: SymptomEntry[] = [
  // ========== CARDIOVASCULAR SYMPTOMS ==========
  {
    symptomId: 'SX-EXP-001',
    name: 'Cyanosis',
    spanishName: 'Cianosis',
    description: 'Bluish or purplish discoloration of the skin and mucous membranes due to insufficient oxygen in the blood.',
    spanishDescription: 'Decoloracion azulada o purpura de la piel y las mucosas debido a oxigeno insuficiente en la sangre.',
    bodyRegions: ['lips', 'fingers', 'toes', 'face'],
    bodySystems: ['cardiovascular', 'respiratory'],
    severity: 8,
    possibleCauses: [
      'Congenital heart disease',
      'Severe pneumonia',
      'Pulmonary embolism',
      'COPD exacerbation',
      'Methemoglobinemia',
      'Peripheral vascular disease',
      'Hypothermia',
      'High altitude',
    ],
    redFlags: [
      'Central cyanosis involving lips and tongue',
      'Sudden onset with chest pain or dyspnea',
      'Cyanosis in a newborn',
      'Associated with altered consciousness',
      'Progressive worsening despite oxygen therapy',
    ],
    associatedSymptoms: [
      'Shortness of breath',
      'Chest pain',
      'Rapid breathing',
      'Confusion',
      'Fatigue',
      'Palpitations',
    ],
    commonAge: 'All ages, more serious in neonates and elderly',
    prevalence: 'Uncommon; seen in 2-5% of cardiac and severe respiratory conditions',
  },
  {
    symptomId: 'SX-EXP-002',
    name: 'Jugular venous distension',
    spanishName: 'Distension venosa yugular',
    description: 'Visible bulging of the jugular veins in the neck, indicating elevated central venous pressure.',
    spanishDescription: 'Abultamiento visible de las venas yugulares en el cuello, indicando presion venosa central elevada.',
    bodyRegions: ['neck'],
    bodySystems: ['cardiovascular'],
    severity: 7,
    possibleCauses: [
      'Congestive heart failure',
      'Tricuspid regurgitation',
      'Pulmonary hypertension',
      'Cardiac tamponade',
      'Constrictive pericarditis',
      'Superior vena cava syndrome',
      'Tension pneumothorax',
      'Fluid overload',
    ],
    redFlags: [
      'JVD with hypotension (possible tamponade)',
      'Acute onset with chest pain',
      'Associated with severe dyspnea',
      'Muffled heart sounds',
      'Paradoxical pulse',
    ],
    associatedSymptoms: [
      'Leg swelling',
      'Shortness of breath',
      'Fatigue',
      'Abdominal distension',
      'Hepatomegaly',
      'Orthopnea',
    ],
    commonAge: 'Adults over 50, but can occur at any age with cardiac disease',
    prevalence: 'Common in heart failure patients (30-40%); indicates advanced disease',
  },

  // ========== RESPIRATORY SYMPTOMS ==========
  {
    symptomId: 'SX-EXP-003',
    name: 'Stridor',
    spanishName: 'Estridor',
    description: 'High-pitched, wheezing sound heard during breathing, typically indicating upper airway obstruction.',
    spanishDescription: 'Sonido agudo y sibilante que se escucha durante la respiracion, que generalmente indica obstruccion de las vias respiratorias superiores.',
    bodyRegions: ['throat', 'chest'],
    bodySystems: ['respiratory'],
    severity: 9,
    possibleCauses: [
      'Croup (laryngotracheobronchitis)',
      'Epiglottitis',
      'Foreign body aspiration',
      'Anaphylaxis with laryngeal edema',
      'Vocal cord dysfunction',
      'Tracheal stenosis',
      'Retropharyngeal abscess',
      'Laryngeal tumor',
    ],
    redFlags: [
      'Sudden onset with drooling and inability to swallow',
      'Stridor at rest (not just with activity)',
      'Cyanosis or severe respiratory distress',
      'Decreased level of consciousness',
      'Complete inability to speak',
      'Stridor in infant under 6 months',
    ],
    associatedSymptoms: [
      'Difficulty breathing',
      'Hoarseness',
      'Cough',
      'Drooling',
      'Fever',
      'Anxiety',
    ],
    commonAge: 'Most common in children 6 months to 3 years; adults with specific pathology',
    prevalence: 'Croup affects 3-5% of children annually; other causes less common',
  },
  {
    symptomId: 'SX-EXP-004',
    name: 'Pleuritic chest pain',
    spanishName: 'Dolor toracico pleuritico',
    description: 'Sharp, stabbing chest pain that worsens with deep breathing, coughing, or movement, indicating pleural irritation.',
    spanishDescription: 'Dolor toracico agudo y punzante que empeora con la respiracion profunda, la tos o el movimiento, indicando irritacion pleural.',
    bodyRegions: ['chest'],
    bodySystems: ['respiratory', 'cardiovascular'],
    severity: 7,
    possibleCauses: [
      'Pleuritis (pleurisy)',
      'Pneumonia',
      'Pulmonary embolism',
      'Pneumothorax',
      'Costochondritis',
      'Rib fracture',
      'Pericarditis',
      'Autoimmune conditions (lupus, rheumatoid arthritis)',
    ],
    redFlags: [
      'Sudden onset with severe dyspnea',
      'Hemoptysis',
      'Syncope or presyncope',
      'Unilateral leg swelling (DVT)',
      'Fever with productive cough',
      'History of recent surgery or prolonged immobility',
    ],
    associatedSymptoms: [
      'Shortness of breath',
      'Cough',
      'Fever',
      'Rapid breathing',
      'Anxiety',
      'Shoulder pain',
    ],
    commonAge: 'Adults, increasing with age; rare in children',
    prevalence: 'Accounts for 5-10% of chest pain presentations in emergency departments',
  },
  {
    symptomId: 'SX-EXP-005',
    name: 'Sputum production',
    spanishName: 'Produccion de esputo',
    description: 'Expulsion of mucus or phlegm from the respiratory tract, often during coughing.',
    spanishDescription: 'Expulsion de moco o flema del tracto respiratorio, frecuentemente durante la tos.',
    bodyRegions: ['chest', 'throat'],
    bodySystems: ['respiratory'],
    severity: 4,
    possibleCauses: [
      'Acute bronchitis',
      'Chronic bronchitis',
      'Pneumonia',
      'COPD',
      'Asthma',
      'Bronchiectasis',
      'Cystic fibrosis',
      'Tuberculosis',
    ],
    redFlags: [
      'Blood-tinged or hemoptysis',
      'Foul-smelling sputum (possible abscess)',
      'Large volume production (>30 mL/day)',
      'Green or rust-colored sputum with fever',
      'Progressive dyspnea',
      'Weight loss and night sweats',
    ],
    associatedSymptoms: [
      'Cough',
      'Shortness of breath',
      'Chest congestion',
      'Wheezing',
      'Fever',
      'Fatigue',
    ],
    commonAge: 'All ages; chronic production more common in adults over 40',
    prevalence: 'Very common; affects 10-20% of adults with respiratory complaints',
  },
  {
    symptomId: 'SX-EXP-006',
    name: 'Apneic episodes',
    spanishName: 'Episodios apneicos',
    description: 'Temporary cessation of breathing during sleep or wakefulness, lasting more than 10 seconds.',
    spanishDescription: 'Cese temporal de la respiracion durante el sueno o la vigilia, que dura mas de 10 segundos.',
    bodyRegions: ['chest', 'whole-body'],
    bodySystems: ['respiratory', 'neurological'],
    severity: 8,
    possibleCauses: [
      'Obstructive sleep apnea',
      'Central sleep apnea',
      'Prematurity in infants',
      'Neurological disorders',
      'Brainstem lesions',
      'Severe obesity',
      'Congestive heart failure',
      'Opioid use',
    ],
    redFlags: [
      'Apnea in infant (risk of SIDS)',
      'Cyanosis during episodes',
      'Loss of consciousness',
      'Severe daytime sleepiness with accidents',
      'Associated with cardiac arrhythmias',
      'Morning headaches and confusion',
    ],
    associatedSymptoms: [
      'Loud snoring',
      'Gasping for air',
      'Daytime fatigue',
      'Morning headaches',
      'Difficulty concentrating',
      'Irritability',
    ],
    commonAge: 'Adults 30-60 years (OSA); infants born premature',
    prevalence: 'Affects 10-30% of adults; OSA prevalence increasing with obesity epidemic',
  },

  // ========== GASTROINTESTINAL SYMPTOMS ==========
  {
    symptomId: 'SX-EXP-007',
    name: 'Odynophagia',
    spanishName: 'Odinofagia',
    description: 'Painful swallowing, with discomfort or pain when food or liquid passes through the esophagus.',
    spanishDescription: 'Deglucion dolorosa, con malestar o dolor cuando la comida o el liquido pasa por el esofago.',
    bodyRegions: ['throat', 'chest'],
    bodySystems: ['gastrointestinal'],
    severity: 6,
    possibleCauses: [
      'Esophagitis (reflux, infectious, eosinophilic)',
      'Esophageal ulceration',
      'Candida esophagitis (immunocompromised)',
      'Pill esophagitis',
      'Esophageal cancer',
      'Radiation esophagitis',
      'Chemical injury',
      'Severe pharyngitis',
    ],
    redFlags: [
      'Progressive dysphagia with weight loss',
      'Hematemesis',
      'Persistent symptoms despite treatment',
      'Odynophagia in immunocompromised patient',
      'History of caustic ingestion',
      'New onset in patient over 50',
    ],
    associatedSymptoms: [
      'Dysphagia',
      'Chest pain',
      'Heartburn',
      'Regurgitation',
      'Weight loss',
      'Sore throat',
    ],
    commonAge: 'All ages; malignancy more common over 50',
    prevalence: 'Less common than dysphagia; seen in 5-10% of patients with esophageal complaints',
  },
  {
    symptomId: 'SX-EXP-008',
    name: 'Hematemesis',
    spanishName: 'Hematemesis',
    description: 'Vomiting of blood, which may appear bright red or dark like coffee grounds, indicating upper GI bleeding.',
    spanishDescription: 'Vomito de sangre, que puede aparecer de color rojo brillante o oscuro como posos de cafe, indicando sangrado del tracto GI superior.',
    bodyRegions: ['abdomen', 'chest'],
    bodySystems: ['gastrointestinal', 'cardiovascular'],
    severity: 9,
    possibleCauses: [
      'Peptic ulcer disease',
      'Esophageal varices',
      'Mallory-Weiss tear',
      'Gastritis or esophagitis',
      'Esophageal or gastric cancer',
      'Arteriovenous malformation',
      'Dieulafoy lesion',
      'NSAIDs or anticoagulant use',
    ],
    redFlags: [
      'Large volume hematemesis',
      'Hypotension or tachycardia',
      'Altered mental status',
      'Melena or hematochezia',
      'History of liver disease or cirrhosis',
      'Persistent vomiting prior to bleeding',
    ],
    associatedSymptoms: [
      'Abdominal pain',
      'Nausea',
      'Dizziness',
      'Weakness',
      'Black tarry stools',
      'Pallor',
    ],
    commonAge: 'Adults over 40, but can occur at any age',
    prevalence: 'Upper GI bleeding incidence 50-150 per 100,000; hematemesis in 40-50% of cases',
  },
  {
    symptomId: 'SX-EXP-009',
    name: 'Melena',
    spanishName: 'Melena',
    description: 'Black, tarry, foul-smelling stools resulting from digested blood, indicating upper gastrointestinal bleeding.',
    spanishDescription: 'Heces negras, alquitranadas y de mal olor que resultan de sangre digerida, indicando sangrado del tracto gastrointestinal superior.',
    bodyRegions: ['abdomen'],
    bodySystems: ['gastrointestinal'],
    severity: 8,
    possibleCauses: [
      'Peptic ulcer disease',
      'Esophageal varices',
      'Gastritis or duodenitis',
      'Upper GI malignancy',
      'Angiodysplasia',
      'Aortoenteric fistula',
      'NSAIDs or anticoagulant use',
      'Meckel diverticulum (children)',
    ],
    redFlags: [
      'Hemodynamic instability',
      'Associated hematemesis',
      'Severe abdominal pain',
      'Syncope or presyncope',
      'History of liver disease',
      'Recent vascular graft surgery',
    ],
    associatedSymptoms: [
      'Abdominal pain',
      'Nausea or vomiting',
      'Weakness',
      'Dizziness',
      'Pallor',
      'Fatigue',
    ],
    commonAge: 'Adults, more common over 60',
    prevalence: 'Melena occurs in 30-40% of upper GI bleeding cases',
  },
  {
    symptomId: 'SX-EXP-010',
    name: 'Tenesmus',
    spanishName: 'Tenesmo',
    description: 'Persistent sensation of incomplete bowel evacuation with cramping rectal pain and frequent urge to defecate.',
    spanishDescription: 'Sensacion persistente de evacuacion intestinal incompleta con dolor rectal tipo calambre y urgencia frecuente de defecar.',
    bodyRegions: ['abdomen', 'pelvis'],
    bodySystems: ['gastrointestinal'],
    severity: 5,
    possibleCauses: [
      'Inflammatory bowel disease (ulcerative colitis, Crohn\'s)',
      'Infectious colitis',
      'Irritable bowel syndrome',
      'Rectal or colon cancer',
      'Proctitis',
      'Rectal prolapse',
      'Hemorrhoids',
      'Anal fissure',
    ],
    redFlags: [
      'Blood in stool',
      'Unintentional weight loss',
      'Severe abdominal pain',
      'Fever with diarrhea',
      'New onset in patient over 50',
      'Progressive symptoms despite treatment',
    ],
    associatedSymptoms: [
      'Rectal pain',
      'Diarrhea',
      'Abdominal cramping',
      'Mucus in stool',
      'Urgency',
      'Bleeding',
    ],
    commonAge: 'Adults 20-40 (IBD); over 50 (malignancy)',
    prevalence: 'Common in IBD (60-80% of active disease); less common in other conditions',
  },
];
