// =============================================================================
// SOMA Medical Education App - Expanded Symptoms Database
// General & Neurological Symptoms
// =============================================================================

export interface SymptomEntry {
  symptomId: string;
  name: string;
  spanishName: string;
  description: string;
  spanishDescription: string;
  bodyRegions: string[];
  bodySystems: string[];
  possibleCauses: {
    conditionId: string;
    conditionName: string;
    likelihood: 'common' | 'less-common' | 'rare' | 'do-not-miss';
  }[];
  redFlags: string[];
  associatedSymptoms: string[];
  characterQuestions: string[];
  homeManagement: string[];
  whenToSeeDoctor: string;
  diagnosticWorkup: string[];
  explanations: {
    level1: string;
    level2: string;
    level3: string;
    level4: string;
    level5: string;
  };
}

export const EXPANDED_SYMPTOMS_GENERAL_NEURO: SymptomEntry[] = [
  // =========================================================================
  // GENERAL / CONSTITUTIONAL
  // =========================================================================

  {
    symptomId: 'SX-EXP-001',
    name: 'Malaise',
    spanishName: 'Malestar general',
    description: 'A general feeling of discomfort, illness, or lack of well-being that may appear suddenly or develop gradually.',
    spanishDescription: 'Sensación general de malestar, enfermedad o falta de bienestar que puede aparecer repentinamente o desarrollarse gradualmente.',
    bodyRegions: ['whole-body'],
    bodySystems: ['general'],
    possibleCauses: [
      { conditionId: 'C-URI', conditionName: 'Viral infection', likelihood: 'common' },
      { conditionId: 'C-ANEMIA', conditionName: 'Anemia', likelihood: 'common' },
      { conditionId: 'C-HYPOTHYROID', conditionName: 'Hypothyroidism', likelihood: 'less-common' },
      { conditionId: 'C-HEPATITIS', conditionName: 'Hepatitis', likelihood: 'less-common' },
      { conditionId: 'C-CANCER', conditionName: 'Malignancy', likelihood: 'rare' },
      { conditionId: 'C-HIV', conditionName: 'HIV/AIDS', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Weight loss greater than 10 pounds without trying',
      'Night sweats',
      'Persistent fever',
      'Progressive worsening over weeks',
      'New lumps or masses',
    ],
    associatedSymptoms: ['fatigue', 'weakness', 'loss of appetite', 'body aches', 'low-grade fever'],
    characterQuestions: [
      'When did the malaise begin?',
      'Is it constant or does it come and go?',
      'Have you noticed any weight changes?',
      'Do you have any other symptoms?',
      'Have you traveled recently?',
    ],
    homeManagement: [
      'Get adequate rest and sleep',
      'Stay well-hydrated',
      'Eat nutritious, balanced meals',
      'Engage in light physical activity if tolerated',
      'Monitor for new or worsening symptoms',
    ],
    whenToSeeDoctor: 'Seek medical evaluation if malaise persists beyond 2 weeks, is accompanied by fever, weight loss, or other concerning symptoms, or significantly interferes with daily activities.',
    diagnosticWorkup: ['Complete blood count', 'Comprehensive metabolic panel', 'Thyroid function tests', 'ESR/CRP', 'HIV screening'],
    explanations: {
      level1: 'Your body feels sick and tired all over.',
      level2: 'Malaise is when your whole body feels unwell, like something is wrong but you cannot point to exactly what.',
      level3: 'Malaise is a non-specific symptom where the body signals that something is off, often due to infection, inflammation, or metabolic disturbance.',
      level4: 'Malaise represents a systemic response to various pathophysiologic processes, mediated by cytokines and inflammatory mediators that affect multiple organ systems and produce generalized feelings of unwellness.',
      level5: 'Malaise results from complex interactions between pro-inflammatory cytokines (IL-1β, IL-6, TNF-α) acting on the central nervous system, disrupting normal neurotransmitter balance and affecting the hypothalamic-pituitary-adrenal axis, leading to behavioral and somatic manifestations of sickness behavior.',
    },
  },

  {
    symptomId: 'SX-EXP-002',
    name: 'Cachexia',
    spanishName: 'Caquexia',
    description: 'Severe weight loss and muscle wasting that occurs with chronic diseases, characterized by loss of muscle mass that cannot be reversed with nutritional supplementation alone.',
    spanishDescription: 'Pérdida severa de peso y desgaste muscular que ocurre con enfermedades crónicas, caracterizada por pérdida de masa muscular que no se puede revertir solo con suplementación nutricional.',
    bodyRegions: ['whole-body'],
    bodySystems: ['general', 'musculoskeletal', 'endocrine'],
    possibleCauses: [
      { conditionId: 'C-CANCER', conditionName: 'Advanced cancer', likelihood: 'common' },
      { conditionId: 'C-CHF', conditionName: 'Congestive heart failure', likelihood: 'common' },
      { conditionId: 'C-COPD', conditionName: 'COPD', likelihood: 'less-common' },
      { conditionId: 'C-HIV', conditionName: 'Advanced HIV/AIDS', likelihood: 'less-common' },
      { conditionId: 'C-CKD', conditionName: 'Chronic kidney disease', likelihood: 'less-common' },
    ],
    redFlags: [
      'Weight loss greater than 5% in 12 months',
      'Severe muscle wasting',
      'Progressive weakness',
      'Difficulty eating or swallowing',
      'Signs of underlying malignancy',
    ],
    associatedSymptoms: ['severe fatigue', 'loss of appetite', 'weakness', 'depression', 'decreased functional capacity'],
    characterQuestions: [
      'How much weight have you lost and over what time period?',
      'Are you able to eat normally?',
      'Have you noticed muscle loss?',
      'What underlying medical conditions do you have?',
      'How has this affected your daily activities?',
    ],
    homeManagement: [
      'High-protein, nutrient-dense meals',
      'Small, frequent meals throughout the day',
      'Nutritional supplements as recommended',
      'Gentle resistance exercises if able',
      'Work with registered dietitian',
    ],
    whenToSeeDoctor: 'Immediate medical evaluation is warranted for unexplained weight loss and muscle wasting. This requires comprehensive workup and treatment of underlying cause.',
    diagnosticWorkup: ['Complete metabolic panel', 'Albumin and prealbumin', 'C-reactive protein', 'Cancer screening', 'CT imaging', 'Assessment of underlying disease'],
    explanations: {
      level1: 'Your body is losing weight and muscle even when you try to eat.',
      level2: 'Cachexia is when serious illnesses make your body break down muscle and lose weight, even if you eat well.',
      level3: 'Cachexia is a complex metabolic syndrome where the body breaks down muscle and fat tissue due to underlying disease, despite adequate caloric intake.',
      level4: 'Cachexia involves dysregulation of protein and energy metabolism driven by inflammatory mediators, resulting in increased protein catabolism, decreased protein synthesis, and resistance to nutritional intervention.',
      level5: 'Cachexia is characterized by elevated pro-inflammatory cytokines (TNF-α, IL-1, IL-6) that activate the ubiquitin-proteasome pathway and autophagy-lysosome system, leading to accelerated skeletal muscle proteolysis. Concurrent activation of lipolysis, insulin resistance, and central appetite suppression via leptin and melanocortin pathways perpetuates the catabolic state.',
    },
  },

  {
    symptomId: 'SX-EXP-003',
    name: 'Failure to Thrive',
    spanishName: 'Falta de crecimiento',
    description: 'Inadequate physical growth and development in children, defined as weight below the 3rd percentile or crossing two major percentile lines on growth charts.',
    spanishDescription: 'Crecimiento físico y desarrollo inadecuado en niños, definido como peso por debajo del percentil 3 o cruzando dos líneas principales de percentil en las gráficas de crecimiento.',
    bodyRegions: ['whole-body'],
    bodySystems: ['general', 'gastrointestinal', 'endocrine'],
    possibleCauses: [
      { conditionId: 'C-INADEQUATE-INTAKE', conditionName: 'Inadequate caloric intake', likelihood: 'common' },
      { conditionId: 'C-GERD', conditionName: 'Gastroesophageal reflux', likelihood: 'common' },
      { conditionId: 'C-MALABSORPTION', conditionName: 'Malabsorption syndrome', likelihood: 'less-common' },
      { conditionId: 'C-CELIAC', conditionName: 'Celiac disease', likelihood: 'less-common' },
      { conditionId: 'C-CF', conditionName: 'Cystic fibrosis', likelihood: 'rare' },
      { conditionId: 'C-NEGLECT', conditionName: 'Child neglect or abuse', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Weight below 3rd percentile',
      'Crossing two major growth percentiles downward',
      'Developmental delays',
      'Signs of neglect or abuse',
      'Severe feeding difficulties',
    ],
    associatedSymptoms: ['poor appetite', 'vomiting', 'diarrhea', 'developmental delay', 'decreased activity'],
    characterQuestions: [
      'What is the child\'s typical diet and feeding pattern?',
      'Has the child had any vomiting or diarrhea?',
      'What is the family and social situation?',
      'Are developmental milestones being met?',
      'Any concerns about the home environment?',
    ],
    homeManagement: [
      'Work with pediatrician on feeding plan',
      'High-calorie, nutrient-dense foods',
      'Regular meal and snack schedule',
      'Monitor weight regularly',
      'Address any feeding difficulties',
    ],
    whenToSeeDoctor: 'Immediate pediatric evaluation is required for any child with poor growth. This may represent serious underlying disease or social concerns requiring intervention.',
    diagnosticWorkup: ['Growth chart review', 'Complete blood count', 'Metabolic panel', 'Celiac screening', 'Stool studies', 'Social work evaluation'],
    explanations: {
      level1: 'A baby or child is not growing like they should.',
      level2: 'Failure to thrive means a child is not gaining weight and growing as expected for their age.',
      level3: 'Failure to thrive occurs when a child does not receive or cannot use the calories needed for normal growth, leading to poor weight gain and development.',
      level4: 'Failure to thrive represents inadequate physical growth due to insufficient caloric intake, malabsorption, increased metabolic demands, or defective utilization of nutrients, often requiring multidisciplinary evaluation.',
      level5: 'Failure to thrive results from imbalance between caloric intake and energy expenditure, involving complex interactions of nutritional, gastrointestinal, metabolic, neurologic, and psychosocial factors. Chronic undernutrition leads to adaptive metabolic changes, growth hormone resistance, and can cause lasting neurodevelopmental consequences if not addressed.',
    },
  },

  {
    symptomId: 'SX-EXP-004',
    name: 'Dehydration',
    spanishName: 'Deshidratación',
    description: 'Excessive loss of body water and electrolytes, occurring when fluid output exceeds fluid intake.',
    spanishDescription: 'Pérdida excesiva de agua corporal y electrolitos, que ocurre cuando la salida de líquidos excede la ingesta de líquidos.',
    bodyRegions: ['whole-body'],
    bodySystems: ['general', 'genitourinary'],
    possibleCauses: [
      { conditionId: 'C-GASTROENTERITIS', conditionName: 'Gastroenteritis', likelihood: 'common' },
      { conditionId: 'C-HEAT-ILLNESS', conditionName: 'Heat exposure', likelihood: 'common' },
      { conditionId: 'C-DM', conditionName: 'Diabetes mellitus', likelihood: 'less-common' },
      { conditionId: 'C-DI', conditionName: 'Diabetes insipidus', likelihood: 'rare' },
      { conditionId: 'C-ADDISON', conditionName: 'Adrenal insufficiency', likelihood: 'rare' },
    ],
    redFlags: [
      'Decreased urine output or dark urine',
      'Altered mental status or lethargy',
      'Rapid heart rate',
      'Sunken eyes or fontanelle in infants',
      'Severe thirst',
      'Dry mucous membranes',
    ],
    associatedSymptoms: ['thirst', 'dry mouth', 'decreased urination', 'dizziness', 'weakness', 'headache'],
    characterQuestions: [
      'How much fluid have you been drinking?',
      'Have you had vomiting or diarrhea?',
      'When did you last urinate and what color was it?',
      'Do you feel dizzy when standing?',
      'Have you been in hot weather or exercising?',
    ],
    homeManagement: [
      'Increase fluid intake with water and oral rehydration solutions',
      'Sip fluids slowly if nauseated',
      'Avoid alcohol and caffeine',
      'Rest in a cool environment',
      'Monitor urine color and output',
    ],
    whenToSeeDoctor: 'Seek immediate care for severe dehydration signs including confusion, very dry mouth, little to no urination, rapid heart rate, or inability to keep fluids down.',
    diagnosticWorkup: ['Basic metabolic panel', 'Urinalysis', 'Urine specific gravity', 'BUN/creatinine ratio'],
    explanations: {
      level1: 'Your body does not have enough water.',
      level2: 'Dehydration happens when you lose more water than you drink, making it hard for your body to work properly.',
      level3: 'Dehydration occurs when fluid losses from vomiting, diarrhea, sweating, or inadequate intake exceed the body\'s ability to maintain proper fluid balance.',
      level4: 'Dehydration represents a deficit in total body water causing decreased intravascular volume, increased plasma osmolality, and compensatory physiologic responses including increased antidiuretic hormone secretion and activation of the renin-angiotensin-aldosterone system.',
      level5: 'Dehydration triggers baroreceptor and osmoreceptor-mediated responses: hyperosmolality stimulates hypothalamic osmoreceptors causing ADH release from the posterior pituitary, promoting water reabsorption in collecting ducts via aquaporin-2 channels. Hypovolemia activates the RAAS, increasing sodium and water retention. Severe dehydration impairs perfusion, leading to prerenal azotemia and potential progression to acute tubular necrosis.',
    },
  },

  {
    symptomId: 'SX-EXP-005',
    name: 'Anorexia',
    spanishName: 'Anorexia',
    description: 'Loss of appetite or decreased desire to eat, often accompanying various medical conditions.',
    spanishDescription: 'Pérdida de apetito o disminución del deseo de comer, que a menudo acompaña a varias condiciones médicas.',
    bodyRegions: ['whole-body'],
    bodySystems: ['general', 'gastrointestinal', 'psychiatric'],
    possibleCauses: [
      { conditionId: 'C-INFECTION', conditionName: 'Acute infection', likelihood: 'common' },
      { conditionId: 'C-DEPRESSION', conditionName: 'Depression', likelihood: 'common' },
      { conditionId: 'C-MEDICATION', conditionName: 'Medication side effect', likelihood: 'common' },
      { conditionId: 'C-CANCER', conditionName: 'Malignancy', likelihood: 'less-common' },
      { conditionId: 'C-HEPATITIS', conditionName: 'Liver disease', likelihood: 'less-common' },
      { conditionId: 'C-THYROTOXICOSIS', conditionName: 'Hyperthyroidism', likelihood: 'less-common' },
    ],
    redFlags: [
      'Unintentional weight loss',
      'Persistent loss of appetite for more than 2 weeks',
      'Signs of malnutrition',
      'Jaundice',
      'Severe abdominal pain',
    ],
    associatedSymptoms: ['weight loss', 'nausea', 'fatigue', 'weakness', 'early satiety'],
    characterQuestions: [
      'When did you notice the loss of appetite?',
      'Have you lost weight?',
      'Do you feel full quickly when eating?',
      'Are you able to eat or is there nausea?',
      'What medications are you taking?',
    ],
    homeManagement: [
      'Eat small, frequent meals',
      'Choose nutrient-dense, appealing foods',
      'Stay hydrated',
      'Light physical activity to stimulate appetite',
      'Keep a food diary',
    ],
    whenToSeeDoctor: 'Medical evaluation is needed if loss of appetite persists more than 2 weeks, causes significant weight loss, or is accompanied by other concerning symptoms.',
    diagnosticWorkup: ['Complete blood count', 'Comprehensive metabolic panel', 'Thyroid function tests', 'Evaluation for depression', 'Medication review'],
    explanations: {
      level1: 'You do not feel hungry or want to eat.',
      level2: 'Loss of appetite means you do not feel like eating, which can happen when you are sick or stressed.',
      level3: 'Anorexia is decreased desire to eat that can result from illness, medications, psychological factors, or metabolic disturbances affecting appetite regulation.',
      level4: 'Anorexia involves disruption of appetite regulation centers in the hypothalamus, influenced by peripheral signals including ghrelin, leptin, and inflammatory cytokines, as well as psychological and metabolic factors.',
      level5: 'Appetite regulation involves the arcuate nucleus of the hypothalamus, where orexigenic neurons (NPY/AgRP) and anorexigenic neurons (POMC/CART) integrate peripheral signals. Anorexia results from increased pro-inflammatory cytokines (IL-1, TNF-α) activating POMC neurons, decreased ghrelin signaling, elevated leptin in chronic disease states, and disruption of reward pathways in the nucleus accumbens and ventral tegmental area.',
    },
  },

  // =========================================================================
  // NEUROLOGICAL
  // =========================================================================

  {
    symptomId: 'SX-EXP-006',
    name: 'Vertigo',
    spanishName: 'Vértigo',
    description: 'False sensation of spinning or movement, either of oneself or the environment, often accompanied by nausea and balance problems.',
    spanishDescription: 'Sensación falsa de giro o movimiento, ya sea de uno mismo o del entorno, a menudo acompañada de náuseas y problemas de equilibrio.',
    bodyRegions: ['head'],
    bodySystems: ['neurological', 'otologic'],
    possibleCauses: [
      { conditionId: 'C-BPPV', conditionName: 'Benign paroxysmal positional vertigo', likelihood: 'common' },
      { conditionId: 'C-VESTIBULAR-NEURITIS', conditionName: 'Vestibular neuritis', likelihood: 'common' },
      { conditionId: 'C-MENIERES', conditionName: 'Meniere\'s disease', likelihood: 'less-common' },
      { conditionId: 'C-MIGRAINE', conditionName: 'Vestibular migraine', likelihood: 'less-common' },
      { conditionId: 'C-STROKE', conditionName: 'Posterior circulation stroke', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Sudden onset with severe headache',
      'Focal neurologic deficits',
      'Inability to walk',
      'Diplopia or visual changes',
      'New or different headache pattern',
    ],
    associatedSymptoms: ['nausea', 'vomiting', 'imbalance', 'nystagmus', 'hearing loss', 'tinnitus'],
    characterQuestions: [
      'Does the room spin or do you feel lightheaded?',
      'What triggers the vertigo?',
      'How long do episodes last?',
      'Do you have hearing changes?',
      'Any recent head trauma or ear infection?',
    ],
    homeManagement: [
      'Avoid sudden head movements',
      'Move slowly when changing positions',
      'Epley maneuver for BPPV (if diagnosed)',
      'Stay hydrated',
      'Avoid driving during episodes',
    ],
    whenToSeeDoctor: 'Seek immediate care for vertigo with neurologic symptoms, severe headache, inability to walk, or new hearing loss. Persistent vertigo requires evaluation.',
    diagnosticWorkup: ['Dix-Hallpike maneuver', 'Head impulse test', 'Audiometry', 'Brain MRI', 'Vestibular function testing'],
    explanations: {
      level1: 'The room feels like it is spinning around you.',
      level2: 'Vertigo makes you feel like everything is spinning or moving when you are actually still.',
      level3: 'Vertigo is a false sensation of motion caused by problems in the inner ear balance system or the brain areas that process balance information.',
      level4: 'Vertigo results from asymmetry in vestibular input between the two ears or central processing abnormalities, creating a mismatch between visual, vestibular, and proprioceptive sensory information.',
      level5: 'Vertigo arises from imbalanced tonic firing rates between paired vestibular nuclei. In peripheral vertigo, damage to the labyrinth or vestibular nerve causes unilateral hypofunction; the intact side generates unopposed neural signals interpreted as rotation. Central vertigo involves brainstem or cerebellar lesions disrupting integration of vestibular, visual, and proprioceptive inputs in the vestibular nuclei, inferior olivary complex, or vestibulocerebellar pathways.',
    },
  },

  {
    symptomId: 'SX-EXP-007',
    name: 'Ataxia',
    spanishName: 'Ataxia',
    description: 'Lack of voluntary coordination of muscle movements, affecting gait, balance, speech, and limb movements.',
    spanishDescription: 'Falta de coordinación voluntaria de los movimientos musculares, que afecta la marcha, el equilibrio, el habla y los movimientos de las extremidades.',
    bodyRegions: ['whole-body', 'upper-extremities', 'lower-extremities'],
    bodySystems: ['neurological'],
    possibleCauses: [
      { conditionId: 'C-ALCOHOL', conditionName: 'Alcohol intoxication', likelihood: 'common' },
      { conditionId: 'C-MEDICATION', conditionName: 'Medication effect', likelihood: 'common' },
      { conditionId: 'C-STROKE', conditionName: 'Cerebellar stroke', likelihood: 'less-common' },
      { conditionId: 'C-MS', conditionName: 'Multiple sclerosis', likelihood: 'less-common' },
      { conditionId: 'C-BRAIN-TUMOR', conditionName: 'Posterior fossa tumor', likelihood: 'rare' },
      { conditionId: 'C-WERNICKE', conditionName: 'Wernicke encephalopathy', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Acute onset with headache',
      'Progressive worsening',
      'Associated weakness or sensory loss',
      'Altered mental status',
      'Signs of increased intracranial pressure',
    ],
    associatedSymptoms: ['imbalance', 'tremor', 'dysarthria', 'nystagmus', 'difficulty with fine motor tasks'],
    characterQuestions: [
      'When did the coordination problems start?',
      'Is it getting worse?',
      'Does it affect walking, speech, or hand movements?',
      'Any recent alcohol use or new medications?',
      'Family history of neurologic disease?',
    ],
    homeManagement: [
      'Use assistive devices for walking if needed',
      'Remove fall hazards from home',
      'Physical therapy exercises',
      'Avoid alcohol and review medications',
      'Ensure adequate nutrition including B vitamins',
    ],
    whenToSeeDoctor: 'Immediate evaluation required for acute ataxia, especially with headache, altered mental status, or focal neurologic signs. Progressive ataxia needs thorough neurologic workup.',
    diagnosticWorkup: ['Brain MRI', 'Cerebellar function tests', 'B12 and thiamine levels', 'Genetic testing', 'Toxicology screen'],
    explanations: {
      level1: 'Your body movements are clumsy and hard to control.',
      level2: 'Ataxia means your muscles do not work together smoothly, making you uncoordinated and wobbly.',
      level3: 'Ataxia is impaired coordination resulting from dysfunction of the cerebellum or its connections, affecting the timing and precision of movements.',
      level4: 'Ataxia reflects disruption of cerebellar function or its afferent/efferent pathways, impairing the cerebellum\'s role in motor planning, timing, force modulation, and error correction during movement execution.',
      level5: 'Ataxia results from cerebellar or proprioceptive pathway dysfunction. The cerebellum compares intended movements with actual performance via climbing fiber (from inferior olive) and mossy fiber (from pontine nuclei and spinal cord) inputs to Purkinje cells. Purkinje cell output modulates deep cerebellar nuclei, which project to motor cortex via thalamus and to brainstem motor centers. Disruption causes dysmetria, dysdiadochokinesia, intention tremor, and impaired motor learning.',
    },
  },

  {
    symptomId: 'SX-EXP-008',
    name: 'Delirium and Confusion',
    spanishName: 'Delirio y confusión',
    description: 'Acute disturbance in attention, awareness, and cognition that develops over hours to days and fluctuates in severity.',
    spanishDescription: 'Alteración aguda de la atención, conciencia y cognición que se desarrolla en horas o días y fluctúa en severidad.',
    bodyRegions: ['head'],
    bodySystems: ['neurological', 'psychiatric'],
    possibleCauses: [
      { conditionId: 'C-INFECTION', conditionName: 'Infection (UTI, pneumonia)', likelihood: 'common' },
      { conditionId: 'C-MEDICATION', conditionName: 'Medication effect', likelihood: 'common' },
      { conditionId: 'C-METABOLIC', conditionName: 'Metabolic disturbance', likelihood: 'common' },
      { conditionId: 'C-STROKE', conditionName: 'Stroke', likelihood: 'less-common' },
      { conditionId: 'C-MENINGITIS', conditionName: 'Meningitis or encephalitis', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Acute onset',
      'Fever',
      'Focal neurologic signs',
      'Severe headache',
      'Signs of trauma',
      'Unable to care for self',
    ],
    associatedSymptoms: ['disorientation', 'agitation', 'hallucinations', 'sleep-wake cycle disturbance', 'inattention'],
    characterQuestions: [
      'When did the confusion start?',
      'Does it fluctuate during the day?',
      'What medications is the patient taking?',
      'Any recent illness or infection?',
      'What is the patient\'s baseline mental status?',
    ],
    homeManagement: [
      'Ensure safe environment',
      'Reorient frequently',
      'Maintain normal sleep-wake cycle',
      'Adequate hydration and nutrition',
      'Minimize unnecessary medications',
    ],
    whenToSeeDoctor: 'Delirium requires immediate medical evaluation to identify and treat underlying cause. This is a medical emergency, especially in elderly patients.',
    diagnosticWorkup: ['Complete metabolic panel', 'Urinalysis', 'Chest X-ray', 'Head CT', 'Medication review', 'Lumbar puncture if indicated'],
    explanations: {
      level1: 'Your brain is very confused and you cannot think clearly.',
      level2: 'Delirium is sudden confusion where you cannot focus, think straight, or know where you are.',
      level3: 'Delirium is an acute brain dysfunction caused by illness, medications, or metabolic problems that disrupt normal brain activity and awareness.',
      level4: 'Delirium represents widespread cerebral dysfunction due to systemic illness, neurotransmitter imbalances (particularly acetylcholine deficiency and dopamine excess), inflammatory mediators, and disruption of normal neuronal activity patterns.',
      level5: 'Delirium pathophysiology involves multiple mechanisms: cholinergic deficiency impairing attention networks in prefrontal cortex and basal forebrain; dopaminergic excess causing perceptual disturbances; inflammatory cytokines (IL-1, IL-6, TNF-α) crossing blood-brain barrier and activating microglia; impaired oxidative metabolism; neurotransmitter imbalances affecting ascending reticular activating system; and disruption of thalamic gating and cortical-subcortical network connectivity.',
    },
  },

  {
    symptomId: 'SX-EXP-009',
    name: 'Altered Level of Consciousness',
    spanishName: 'Nivel alterado de conciencia',
    description: 'Decreased awareness of self and environment, ranging from mild lethargy to coma.',
    spanishDescription: 'Disminución de la conciencia de sí mismo y del entorno, que va desde letargo leve hasta coma.',
    bodyRegions: ['head'],
    bodySystems: ['neurological'],
    possibleCauses: [
      { conditionId: 'C-STROKE', conditionName: 'Stroke', likelihood: 'common' },
      { conditionId: 'C-TRAUMA', conditionName: 'Head trauma', likelihood: 'common' },
      { conditionId: 'C-METABOLIC', conditionName: 'Metabolic encephalopathy', likelihood: 'common' },
      { conditionId: 'C-OVERDOSE', conditionName: 'Drug overdose', likelihood: 'less-common' },
      { conditionId: 'C-MENINGITIS', conditionName: 'Meningitis or encephalitis', likelihood: 'do-not-miss' },
      { conditionId: 'C-HERNIATION', conditionName: 'Brain herniation', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Rapidly declining consciousness',
      'Posturing movements',
      'Unequal pupils',
      'Absent brainstem reflexes',
      'Respiratory pattern changes',
    ],
    associatedSymptoms: ['confusion', 'focal weakness', 'seizures', 'abnormal breathing', 'abnormal posturing'],
    characterQuestions: [
      'How quickly did this develop?',
      'Any recent trauma?',
      'What medications or substances could be involved?',
      'Any medical conditions like diabetes?',
      'Was there a seizure?',
    ],
    homeManagement: [
      'Call 911 immediately - this is a medical emergency',
      'Position patient safely',
      'Do not give anything by mouth',
      'Protect airway',
      'Monitor breathing',
    ],
    whenToSeeDoctor: 'Any alteration in consciousness is a medical emergency requiring immediate emergency department evaluation and stabilization.',
    diagnosticWorkup: ['Head CT', 'Basic metabolic panel', 'Glucose', 'Toxicology screen', 'Arterial blood gas', 'Lumbar puncture if indicated'],
    explanations: {
      level1: 'Someone is very sleepy and hard to wake up.',
      level2: 'Altered consciousness means a person is less awake and aware than normal, which can be very dangerous.',
      level3: 'Altered consciousness represents dysfunction of the brain\'s arousal systems, caused by structural damage, metabolic disturbances, toxins, or inadequate blood flow.',
      level4: 'Consciousness depends on intact cerebral cortex and ascending reticular activating system in the brainstem. Altered consciousness reflects dysfunction of these systems due to structural lesions, metabolic derangements, or diffuse brain injury.',
      level5: 'Consciousness requires bilateral cortical function and intact reticular activating system projecting from brainstem through thalamus to cortex. Decreased consciousness results from: bilateral hemispheric dysfunction, disruption of ascending arousal pathways (cholinergic pedunculopontine/laterodorsal tegmental nuclei, noradrenergic locus coeruleus, serotonergic raphe, dopaminergic ventral tegmental area), thalamic gating dysfunction, or direct brainstem injury. Metabolic encephalopathy impairs neuronal membrane potentials and neurotransmission globally.',
    },
  },

  {
    symptomId: 'SX-EXP-010',
    name: 'Dysarthria',
    spanishName: 'Disartria',
    description: 'Difficulty speaking due to weakness or incoordination of the muscles used for speech.',
    spanishDescription: 'Dificultad para hablar debido a debilidad o incoordinación de los músculos utilizados para el habla.',
    bodyRegions: ['face', 'mouth', 'throat'],
    bodySystems: ['neurological'],
    possibleCauses: [
      { conditionId: 'C-STROKE', conditionName: 'Stroke', likelihood: 'common' },
      { conditionId: 'C-BELLS-PALSY', conditionName: 'Bell\'s palsy', likelihood: 'common' },
      { conditionId: 'C-MS', conditionName: 'Multiple sclerosis', likelihood: 'less-common' },
      { conditionId: 'C-PARKINSONS', conditionName: 'Parkinson\'s disease', likelihood: 'less-common' },
      { conditionId: 'C-MG', conditionName: 'Myasthenia gravis', likelihood: 'rare' },
      { conditionId: 'C-BRAINSTEM-STROKE', conditionName: 'Brainstem stroke', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Acute onset with other stroke symptoms',
      'Progressive worsening',
      'Difficulty swallowing',
      'Breathing difficulty',
      'Bilateral facial weakness',
    ],
    associatedSymptoms: ['facial weakness', 'dysphagia', 'drooling', 'nasal speech', 'slurred speech'],
    characterQuestions: [
      'When did the speech difficulty start?',
      'Is it getting worse?',
      'Any trouble swallowing?',
      'Do you have weakness elsewhere?',
      'Any other neurologic symptoms?',
    ],
    homeManagement: [
      'Speak slowly and clearly',
      'Use short phrases',
      'Speech therapy exercises if prescribed',
      'Ensure safe swallowing',
      'Use written communication if needed',
    ],
    whenToSeeDoctor: 'Sudden onset dysarthria requires immediate stroke evaluation. Progressive dysarthria needs neurologic assessment to determine cause.',
    diagnosticWorkup: ['Brain MRI', 'Speech and swallow evaluation', 'EMG/NCS', 'Assessment for myasthenia gravis'],
    explanations: {
      level1: 'Your mouth muscles are weak and you cannot speak clearly.',
      level2: 'Dysarthria makes your words sound slurred because the muscles you use to talk are not working right.',
      level3: 'Dysarthria is difficulty articulating speech due to weakness, slowness, or incoordination of the muscles controlling the lips, tongue, palate, and vocal cords.',
      level4: 'Dysarthria results from upper or lower motor neuron lesions, cerebellar dysfunction, basal ganglia disease, or neuromuscular junction abnormalities affecting the motor control of speech musculature.',
      level5: 'Speech articulation requires coordinated activity of corticobulbar pathways to cranial nerve nuclei (V, VII, IX, X, XII), modulated by basal ganglia and cerebellum. Dysarthria patterns localize lesions: flaccid (lower motor neuron), spastic (bilateral upper motor neuron), ataxic (cerebellar), hypokinetic (parkinsonism), hyperkinetic (chorea, dystonia), or mixed. Neuromuscular junction disorders cause fatigable dysarthria with normal muscle bulk and reflexes.',
    },
  },

  {
    symptomId: 'SX-EXP-011',
    name: 'Photophobia',
    spanishName: 'Fotofobia',
    description: 'Abnormal sensitivity to light, causing discomfort or pain in the eyes.',
    spanishDescription: 'Sensibilidad anormal a la luz, causando incomodidad o dolor en los ojos.',
    bodyRegions: ['eyes', 'head'],
    bodySystems: ['neurological', 'ophthalmologic'],
    possibleCauses: [
      { conditionId: 'C-MIGRAINE', conditionName: 'Migraine', likelihood: 'common' },
      { conditionId: 'C-CORNEAL-ABRASION', conditionName: 'Corneal abrasion', likelihood: 'common' },
      { conditionId: 'C-UVEITIS', conditionName: 'Uveitis', likelihood: 'less-common' },
      { conditionId: 'C-MENINGITIS', conditionName: 'Meningitis', likelihood: 'do-not-miss' },
      { conditionId: 'C-SAH', conditionName: 'Subarachnoid hemorrhage', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Severe headache',
      'Neck stiffness',
      'Fever',
      'Altered mental status',
      'Eye redness with decreased vision',
    ],
    associatedSymptoms: ['headache', 'eye pain', 'tearing', 'blurred vision', 'nausea'],
    characterQuestions: [
      'When did light sensitivity start?',
      'Is there associated headache?',
      'Any eye redness or discharge?',
      'Recent eye injury?',
      'Any fever or neck stiffness?',
    ],
    homeManagement: [
      'Wear sunglasses indoors and outdoors',
      'Dim lights or use blackout curtains',
      'Rest in dark, quiet room',
      'Use lubricating eye drops if dry eyes',
      'Avoid bright screens',
    ],
    whenToSeeDoctor: 'Seek immediate care for photophobia with severe headache, fever, neck stiffness, or vision changes. Persistent photophobia requires evaluation.',
    diagnosticWorkup: ['Ophthalmologic examination', 'Slit lamp exam', 'Lumbar puncture if meningeal signs', 'Head CT or MRI'],
    explanations: {
      level1: 'Light hurts your eyes.',
      level2: 'Photophobia means bright light bothers your eyes and makes them hurt.',
      level3: 'Photophobia is sensitivity to light that occurs when the eyes or brain are irritated, making normal light levels uncomfortable or painful.',
      level4: 'Photophobia results from activation of pain-sensitive trigeminal nerve fibers innervating the eye and meninges, amplified by central sensitization in migraineurs or increased by ocular or meningeal inflammation.',
      level5: 'Photophobia involves intrinsically photosensitive retinal ganglion cells containing melanopsin that project to the trigeminal nucleus and thalamus. Light-induced activation of trigeminal pain pathways occurs through: direct ocular inflammation activating trigeminal nerve endings; meningeal inflammation sensitizing trigeminal afferents; or in migraine, central sensitization of thalamic and cortical neurons processing light and pain signals, with abnormal activation of the trigeminovascular system.',
    },
  },

  {
    symptomId: 'SX-EXP-012',
    name: 'Neck Stiffness and Meningismus',
    spanishName: 'Rigidez de cuello y meningismo',
    description: 'Inability to flex the neck forward due to rigidity of neck muscles, often indicating meningeal irritation.',
    spanishDescription: 'Incapacidad para flexionar el cuello hacia adelante debido a rigidez de los músculos del cuello, a menudo indicando irritación meníngea.',
    bodyRegions: ['neck'],
    bodySystems: ['neurological', 'musculoskeletal'],
    possibleCauses: [
      { conditionId: 'C-MENINGITIS', conditionName: 'Meningitis', likelihood: 'common' },
      { conditionId: 'C-SAH', conditionName: 'Subarachnoid hemorrhage', likelihood: 'do-not-miss' },
      { conditionId: 'C-MUSCLE-STRAIN', conditionName: 'Neck muscle strain', likelihood: 'common' },
      { conditionId: 'C-RETROPHARYNGEAL-ABSCESS', conditionName: 'Retropharyngeal abscess', likelihood: 'rare' },
    ],
    redFlags: [
      'Fever with neck stiffness',
      'Severe headache',
      'Altered mental status',
      'Petechial rash',
      'Positive Kernig or Brudzinski signs',
    ],
    associatedSymptoms: ['fever', 'headache', 'photophobia', 'altered mental status', 'nausea and vomiting'],
    characterQuestions: [
      'Can you touch your chin to your chest?',
      'Do you have fever or headache?',
      'When did the stiffness start?',
      'Any recent trauma?',
      'Have you been exposed to anyone who is sick?',
    ],
    homeManagement: [
      'If fever or severe headache: call 911 immediately',
      'For simple muscle strain: rest, heat, gentle stretching',
      'Avoid driving if neck mobility limited',
    ],
    whenToSeeDoctor: 'Neck stiffness with fever, severe headache, altered mental status, or rash requires immediate emergency evaluation for possible meningitis.',
    diagnosticWorkup: ['Lumbar puncture with CSF analysis', 'Blood cultures', 'Head CT before LP if increased ICP suspected', 'Complete blood count'],
    explanations: {
      level1: 'Your neck is stiff and it hurts to bend it forward.',
      level2: 'Neck stiffness with fever can mean the coverings of your brain are irritated or infected.',
      level3: 'Meningismus is neck stiffness caused by inflammation of the meninges, the protective layers covering the brain and spinal cord.',
      level4: 'Neck stiffness results from reflex spasm of cervical muscles in response to meningeal inflammation, detected by stretch receptors and mediated by trigeminal and upper cervical nerve afferents.',
      level5: 'Meningeal irritation from infection, hemorrhage, or inflammation activates meningeal nociceptors innervated by trigeminal nerve and upper cervical roots (C1-C3). Inflammatory mediators and blood products cause meningeal chemoreceptor and mechanoreceptor activation. Reflexive nuchal muscle contraction via upper cervical motor neurons prevents painful meningeal stretch during neck flexion. Kernig and Brudzinski signs reflect similar protective responses to meningeal tension.',
    },
  },

  {
    symptomId: 'SX-EXP-013',
    name: 'Gait Abnormality',
    spanishName: 'Anormalidad de la marcha',
    description: 'Deviation from normal walking pattern, which may involve balance, coordination, strength, or sensory issues.',
    spanishDescription: 'Desviación del patrón normal de caminar, que puede involucrar problemas de equilibrio, coordinación, fuerza o sensoriales.',
    bodyRegions: ['lower-extremities', 'whole-body'],
    bodySystems: ['neurological', 'musculoskeletal'],
    possibleCauses: [
      { conditionId: 'C-PARKINSONS', conditionName: 'Parkinson\'s disease', likelihood: 'common' },
      { conditionId: 'C-STROKE', conditionName: 'Stroke', likelihood: 'common' },
      { conditionId: 'C-PERIPHERAL-NEUROPATHY', conditionName: 'Peripheral neuropathy', likelihood: 'common' },
      { conditionId: 'C-NPH', conditionName: 'Normal pressure hydrocephalus', likelihood: 'less-common' },
      { conditionId: 'C-SPINAL-CORD-COMPRESSION', conditionName: 'Spinal cord compression', likelihood: 'do-not-miss' },
    ],
    redFlags: [
      'Rapidly progressive',
      'Associated with bowel or bladder dysfunction',
      'Severe back pain',
      'Bilateral leg weakness',
      'Falls',
    ],
    associatedSymptoms: ['imbalance', 'weakness', 'numbness', 'tremor', 'pain'],
    characterQuestions: [
      'How long have you had difficulty walking?',
      'Is it getting worse?',
      'Do you have pain, weakness, or numbness?',
      'Have you fallen?',
      'What makes it better or worse?',
    ],
    homeManagement: [
      'Use assistive device if recommended',
      'Physical therapy exercises',
      'Remove tripping hazards at home',
      'Wear proper footwear',
      'Consider home safety evaluation',
    ],
    whenToSeeDoctor: 'Acute gait changes or progressive worsening requires neurologic evaluation. Gait disturbance with falls needs urgent assessment.',
    diagnosticWorkup: ['Neurologic examination', 'Spine MRI', 'Brain MRI', 'EMG/NCS', 'B12 level', 'Gait analysis'],
    explanations: {
      level1: 'You walk in an unusual way.',
      level2: 'Gait problems mean you have trouble walking normally, which can be from many causes affecting your legs or brain.',
      level3: 'Abnormal gait results from problems with strength, sensation, balance, or coordination affecting the complex process of walking.',
      level4: 'Normal gait requires integration of motor control, proprioception, vestibular input, and cerebellar coordination. Gait abnormalities reflect dysfunction in one or more of these systems.',
      level5: 'Gait involves sequential activation of motor cortex, corticospinal tracts, spinal motor neurons, and muscles, modulated by basal ganglia (movement initiation/scaling), cerebellum (coordination/timing), and sensory feedback (proprioceptive and vestibular). Distinct gait patterns localize lesions: hemiplegic (contralateral corticospinal), parkinsonian (basal ganglia dopamine depletion), ataxic (cerebellar), steppage (peroneal nerve/L5 radiculopathy), antalgic (pain), sensory ataxic (dorsal columns), waddling (proximal myopathy).',
    },
  },

  {
    symptomId: 'SX-EXP-014',
    name: 'Involuntary Movements',
    spanishName: 'Movimientos involuntarios',
    description: 'Unintentional movements including chorea (dance-like), dystonia (sustained muscle contractions), or other abnormal movements.',
    spanishDescription: 'Movimientos no intencionales que incluyen corea (como bailar), distonía (contracciones musculares sostenidas) u otros movimientos anormales.',
    bodyRegions: ['upper-extremities', 'lower-extremities', 'face', 'whole-body'],
    bodySystems: ['neurological'],
    possibleCauses: [
      { conditionId: 'C-MEDICATION', conditionName: 'Medication-induced (antipsychotics)', likelihood: 'common' },
      { conditionId: 'C-HUNTINGTONS', conditionName: 'Huntington\'s disease', likelihood: 'less-common' },
      { conditionId: 'C-PARKINSONS', conditionName: 'Parkinson\'s disease', likelihood: 'common' },
      { conditionId: 'C-WILSON', conditionName: 'Wilson\'s disease', likelihood: 'rare' },
      { conditionId: 'C-STROKE', conditionName: 'Basal ganglia stroke', likelihood: 'less-common' },
    ],
    redFlags: [
      'Rapidly progressive',
      'Cognitive decline',
      'Psychiatric symptoms',
      'Acute onset',
      'Medication changes',
    ],
    associatedSymptoms: ['tremor', 'rigidity', 'cognitive changes', 'behavioral changes', 'speech difficulties'],
    characterQuestions: [
      'What type of movements are occurring?',
      'When did they start?',
      'What medications are you taking?',
      'Any family history of movement disorders?',
      'Can you control or suppress the movements?',
    ],
    homeManagement: [
      'Ensure safety to prevent injury',
      'Medication compliance if prescribed',
      'Stress reduction techniques',
      'Occupational therapy adaptations',
      'Avoid triggering factors if identified',
    ],
    whenToSeeDoctor: 'New onset involuntary movements require neurologic evaluation. Acute onset may indicate stroke or medication reaction requiring urgent assessment.',
    diagnosticWorkup: ['Brain MRI', 'Medication review', 'Ceruloplasmin for Wilson\'s', 'Genetic testing', 'Metabolic workup'],
    explanations: {
      level1: 'Your body makes movements that you do not control.',
      level2: 'Involuntary movements are when parts of your body move on their own without you wanting them to.',
      level3: 'Involuntary movements result from dysfunction of brain circuits controlling movement, particularly the basal ganglia and their connections.',
      level4: 'Movement disorders reflect imbalances in basal ganglia circuits regulating motor control. Hyperkinetic disorders (chorea, dystonia) involve excessive or abnormal movements from disrupted inhibitory control.',
      level5: 'Basal ganglia circuits process cortical input through direct (facilitating movement) and indirect (suppressing unwanted movement) pathways, modulated by dopamine. Chorea results from striatal neuron loss reducing indirect pathway activity (as in Huntington\'s disease). Dystonia involves abnormal sensorimotor integration and loss of inhibition in basal ganglia-thalamo-cortical loops. Dopamine receptor blockade or depletion causes parkinsonism. Disorders involve specific neurotransmitter imbalances affecting striatal medium spiny neurons and their projections.',
    },
  },

  {
    symptomId: 'SX-EXP-015',
    name: 'Facial Droop',
    spanishName: 'Caída facial',
    description: 'Weakness or paralysis of facial muscles on one or both sides, causing asymmetry of the face.',
    spanishDescription: 'Debilidad o parálisis de los músculos faciales en uno o ambos lados, causando asimetría de la cara.',
    bodyRegions: ['face'],
    bodySystems: ['neurological'],
    possibleCauses: [
      { conditionId: 'C-BELLS-PALSY', conditionName: 'Bell\'s palsy', likelihood: 'common' },
      { conditionId: 'C-STROKE', conditionName: 'Stroke', likelihood: 'do-not-miss' },
      { conditionId: 'C-RAMSEY-HUNT', conditionName: 'Ramsay Hunt syndrome', likelihood: 'less-common' },
      { conditionId: 'C-LYME', conditionName: 'Lyme disease', likelihood: 'less-common' },
      { conditionId: 'C-BRAIN-TUMOR', conditionName: 'Brain tumor', likelihood: 'rare' },
    ],
    redFlags: [
      'Sudden onset with arm or leg weakness',
      'Speech difficulty',
      'Severe headache',
      'Bilateral facial weakness',
      'Progressive worsening',
    ],
    associatedSymptoms: ['dysarthria', 'difficulty closing eye', 'drooling', 'loss of taste', 'hyperacusis'],
    characterQuestions: [
      'When did the facial weakness start?',
      'Can you wrinkle your forehead on the affected side?',
      'Any other weakness or numbness?',
      'Recent viral illness or ear pain?',
      'Any difficulty with speech or swallowing?',
    ],
    homeManagement: [
      'Protect the eye with artificial tears and eye patch at night',
      'Gentle facial massage',
      'Practice facial exercises as directed',
      'Eat soft foods',
      'Maintain good oral hygiene',
    ],
    whenToSeeDoctor: 'Sudden facial droop with other stroke symptoms (arm weakness, speech difficulty) requires immediate emergency evaluation. Isolated facial droop needs prompt assessment within 24-72 hours.',
    diagnosticWorkup: ['Neurologic examination', 'Brain MRI', 'Lyme serology', 'Varicella zoster testing', 'EMG if indicated'],
    explanations: {
      level1: 'One side of your face does not move like the other side.',
      level2: 'Facial droop happens when nerves or muscles on one side of your face stop working, making that side sag.',
      level3: 'Facial weakness results from damage to the facial nerve or the brain areas controlling facial movement, causing asymmetry and loss of facial expression.',
      level4: 'Facial weakness localizes to either peripheral (facial nerve) or central (corticobulbar tract) lesions. Peripheral lesions affect all facial muscles; central lesions spare forehead due to bilateral cortical innervation of upper facial muscles.',
      level5: 'Facial motor control originates in motor cortex with upper motor neurons traveling via corticobulbar tracts to facial nuclei in pons. Upper face receives bilateral cortical input; lower face receives predominantly contralateral input. Bell\'s palsy involves inflammatory demyelination of the facial nerve in the facial canal. Stroke affecting motor cortex or internal capsule causes contralateral lower facial weakness sparing forehead. Pontine lesions affecting facial nucleus cause ipsilateral complete facial paralysis, often with abducens palsy (lateral rectus weakness).',
    },
  },
];
