// =============================================================================
// SOMA Medical Education App - Expanded Symptoms Database
// GU, MSK, DERM, PSYCH Systems
// New symptoms not in main symptom-database.ts
// =============================================================================

// Re-declare interface locally for standalone use
export interface SymptomEntry {
  symptomId: string;
  name: string;
  spanishName: string;
  description: string;
  spanishDescription: string;
  bodyRegions: string[];
  bodySystems: string[];
  severity: number; // 1-10 range
  possibleCauses: string[];
  redFlags: string[];
  associatedSymptoms: string[];
  commonAge: string;
  prevalence: string;
}

export const EXPANDED_SYMPTOMS_GU_MSK_DERM_PSYCH: SymptomEntry[] = [
  // GENITOURINARY SYMPTOMS
  {
    symptomId: 'SX-EXP-001',
    name: 'Urinary retention',
    spanishName: 'Retención urinaria',
    description: 'Inability to empty the bladder completely or at all, despite the urge to urinate.',
    spanishDescription: 'Incapacidad para vaciar la vejiga completamente o en absoluto, a pesar de la urgencia de orinar.',
    bodyRegions: ['abdomen', 'pelvis'],
    bodySystems: ['genitourinary'],
    severity: 8,
    possibleCauses: ['Benign prostatic hyperplasia', 'Urethral stricture', 'Neurogenic bladder', 'Medications (anticholinergics)', 'Bladder outlet obstruction', 'Urinary tract infection'],
    redFlags: ['Complete inability to urinate', 'Severe lower abdominal pain and distention', 'Fever with retention', 'Recent back injury or trauma', 'Saddle anesthesia'],
    associatedSymptoms: ['Lower abdominal pain', 'Bladder fullness', 'Overflow incontinence', 'Weak urinary stream', 'Dysuria'],
    commonAge: 'Adults over 50, especially men',
    prevalence: 'Common in older men (10% over age 70)',
  },
  {
    symptomId: 'SX-EXP-002',
    name: 'Flank pain',
    spanishName: 'Dolor en el flanco',
    description: 'Pain in the side of the body between the ribs and pelvis, often indicating kidney or ureter problems.',
    spanishDescription: 'Dolor en el costado del cuerpo entre las costillas y la pelvis, que a menudo indica problemas renales o ureterales.',
    bodyRegions: ['back', 'abdomen'],
    bodySystems: ['genitourinary'],
    severity: 7,
    possibleCauses: ['Kidney stones', 'Pyelonephritis', 'Renal infarction', 'Renal abscess', 'Musculoskeletal strain', 'Herpes zoster'],
    redFlags: ['Severe colicky pain radiating to groin', 'Fever with flank pain', 'Hematuria', 'Nausea and vomiting', 'Anuria'],
    associatedSymptoms: ['Hematuria', 'Dysuria', 'Nausea', 'Vomiting', 'Fever', 'Urinary frequency'],
    commonAge: 'Adults 30-60 years',
    prevalence: 'Common (kidney stones affect 10% of population)',
  },

  // MUSCULOSKELETAL SYMPTOMS
  {
    symptomId: 'SX-EXP-003',
    name: 'Myalgia',
    spanishName: 'Mialgia',
    description: 'Muscle pain or aching that can be localized or widespread throughout the body.',
    spanishDescription: 'Dolor o molestia muscular que puede ser localizado o generalizado en todo el cuerpo.',
    bodyRegions: ['whole-body', 'extremities', 'back'],
    bodySystems: ['musculoskeletal'],
    severity: 4,
    possibleCauses: ['Viral infection', 'Fibromyalgia', 'Polymyalgia rheumatica', 'Statin medications', 'Overexertion', 'Autoimmune myositis', 'Hypothyroidism'],
    redFlags: ['Muscle weakness with pain', 'Dark urine (rhabdomyolysis)', 'Fever and severe muscle pain', 'Progressive weakness', 'Difficulty swallowing or breathing'],
    associatedSymptoms: ['Fatigue', 'Fever', 'Muscle weakness', 'Joint pain', 'Headache'],
    commonAge: 'All ages',
    prevalence: 'Very common (affects majority during viral illnesses)',
  },
  {
    symptomId: 'SX-EXP-004',
    name: 'Morning stiffness',
    spanishName: 'Rigidez matutina',
    description: 'Joint or muscle stiffness that is most severe upon waking and improves with movement.',
    spanishDescription: 'Rigidez articular o muscular más grave al despertar que mejora con el movimiento.',
    bodyRegions: ['joints', 'hands', 'spine'],
    bodySystems: ['musculoskeletal'],
    severity: 5,
    possibleCauses: ['Rheumatoid arthritis', 'Osteoarthritis', 'Ankylosing spondylitis', 'Polymyalgia rheumatica', 'Fibromyalgia'],
    redFlags: ['Morning stiffness lasting more than 1 hour', 'Progressive joint deformity', 'Systemic symptoms with stiffness', 'Young adult with back stiffness'],
    associatedSymptoms: ['Joint pain', 'Joint swelling', 'Fatigue', 'Limited range of motion'],
    commonAge: 'Adults over 40',
    prevalence: 'Common in inflammatory arthritis (>90% RA patients)',
  },
  {
    symptomId: 'SX-EXP-005',
    name: 'Muscle cramps',
    spanishName: 'Calambres musculares',
    description: 'Sudden, involuntary, and painful muscle contractions that typically resolve spontaneously.',
    spanishDescription: 'Contracciones musculares súbitas, involuntarias y dolorosas que generalmente se resuelven espontáneamente.',
    bodyRegions: ['legs', 'arms', 'abdomen'],
    bodySystems: ['musculoskeletal', 'neurological'],
    severity: 5,
    possibleCauses: ['Dehydration', 'Electrolyte imbalance', 'Overexertion', 'Peripheral artery disease', 'Nerve compression', 'Medication side effects'],
    redFlags: ['Frequent severe cramps', 'Cramps with muscle weakness', 'Cramps with dark urine', 'Associated with numbness or tingling'],
    associatedSymptoms: ['Muscle fatigue', 'Dehydration', 'Weakness', 'Fasciculations'],
    commonAge: 'All ages, more common in adults',
    prevalence: 'Very common (60% experience nocturnal leg cramps)',
  },
  {
    symptomId: 'SX-EXP-006',
    name: 'Bone pain',
    spanishName: 'Dolor óseo',
    description: 'Deep, aching pain originating from bone tissue, distinct from muscle or joint pain.',
    spanishDescription: 'Dolor profundo y persistente que se origina en el tejido óseo, distinto del dolor muscular o articular.',
    bodyRegions: ['bones', 'spine', 'extremities'],
    bodySystems: ['musculoskeletal'],
    severity: 7,
    possibleCauses: ['Bone metastases', 'Multiple myeloma', 'Osteoporosis with fracture', 'Osteomyelitis', 'Paget disease', 'Bone infarction'],
    redFlags: ['Severe night pain', 'Unexplained weight loss with bone pain', 'Pain at rest', 'History of cancer', 'Pathologic fracture'],
    associatedSymptoms: ['Fatigue', 'Weight loss', 'Fever (if infection)', 'Weakness', 'Anemia symptoms'],
    commonAge: 'Adults over 50',
    prevalence: 'Uncommon in general population, common in malignancy',
  },

  // DERMATOLOGIC SYMPTOMS
  {
    symptomId: 'SX-EXP-007',
    name: 'Petechiae',
    spanishName: 'Petequias',
    description: 'Small, pinpoint red or purple spots on the skin caused by bleeding under the skin.',
    spanishDescription: 'Manchas rojas o púrpuras pequeñas y puntiformes en la piel causadas por sangrado debajo de la piel.',
    bodyRegions: ['skin', 'extremities', 'trunk'],
    bodySystems: ['dermatological', 'hematologic'],
    severity: 8,
    possibleCauses: ['Thrombocytopenia', 'Meningococcemia', 'Vasculitis', 'Endocarditis', 'Viral infections', 'Medication reactions', 'Leukemia'],
    redFlags: ['Fever with petechiae', 'Rapidly spreading petechiae', 'Mucosal bleeding', 'Altered mental status', 'Severe headache with petechiae'],
    associatedSymptoms: ['Easy bruising', 'Bleeding gums', 'Nosebleeds', 'Fever', 'Fatigue'],
    commonAge: 'All ages',
    prevalence: 'Uncommon, indicates serious pathology when present',
  },
  {
    symptomId: 'SX-EXP-008',
    name: 'Purpura',
    spanishName: 'Púrpura',
    description: 'Purple or red discoloration of skin due to bleeding underneath, larger than petechiae (>3mm).',
    spanishDescription: 'Decoloración púrpura o roja de la piel debido a sangrado subyacente, más grande que las petequias (>3mm).',
    bodyRegions: ['skin', 'extremities'],
    bodySystems: ['dermatological', 'hematologic'],
    severity: 7,
    possibleCauses: ['Thrombocytopenia', 'Platelet dysfunction', 'Vasculitis', 'Coagulation disorders', 'Henoch-Schonlein purpura', 'Scurvy', 'Amyloidosis'],
    redFlags: ['Purpura with fever', 'Rapidly progressive purpura', 'Associated abdominal pain', 'Joint pain with purpura', 'Renal symptoms'],
    associatedSymptoms: ['Petechiae', 'Easy bruising', 'Joint pain', 'Abdominal pain', 'Hematuria'],
    commonAge: 'All ages, varies by cause',
    prevalence: 'Uncommon',
  },
  {
    symptomId: 'SX-EXP-009',
    name: 'Hyperpigmentation',
    spanishName: 'Hiperpigmentación',
    description: 'Darkening of the skin due to increased melanin production or deposition.',
    spanishDescription: 'Oscurecimiento de la piel debido al aumento de la producción o deposición de melanina.',
    bodyRegions: ['skin', 'face', 'exposed areas'],
    bodySystems: ['dermatological', 'endocrine'],
    severity: 3,
    possibleCauses: ['Sun exposure', 'Post-inflammatory hyperpigmentation', 'Melasma', 'Addison disease', 'Hemochromatosis', 'Medications', 'Vitamin deficiencies'],
    redFlags: ['Generalized hyperpigmentation with weight loss', 'Hyperpigmentation with fatigue and hypotension', 'Rapid onset with systemic symptoms'],
    associatedSymptoms: ['Fatigue', 'Weight loss', 'Dizziness', 'Salt craving (if Addison)'],
    commonAge: 'All ages',
    prevalence: 'Very common',
  },

  // PSYCHIATRIC SYMPTOMS
  {
    symptomId: 'SX-EXP-010',
    name: 'Anhedonia',
    spanishName: 'Anhedonia',
    description: 'Loss of interest or pleasure in activities that were previously enjoyable.',
    spanishDescription: 'Pérdida de interés o placer en actividades que anteriormente eran agradables.',
    bodyRegions: ['brain'],
    bodySystems: ['psychiatric', 'neurological'],
    severity: 6,
    possibleCauses: ['Major depressive disorder', 'Schizophrenia', 'Parkinson disease', 'Substance use disorder', 'Post-traumatic stress disorder'],
    redFlags: ['Anhedonia with suicidal ideation', 'Severe functional impairment', 'Psychotic symptoms', 'Recent significant weight loss'],
    associatedSymptoms: ['Depressed mood', 'Fatigue', 'Sleep disturbance', 'Poor concentration', 'Social withdrawal'],
    commonAge: 'Adults, any age',
    prevalence: 'Common in depression (present in 70% of MDD)',
  },
  {
    symptomId: 'SX-EXP-011',
    name: 'Psychomotor agitation',
    spanishName: 'Agitación psicomotora',
    description: 'Excessive motor activity associated with mental tension, such as restlessness, pacing, or hand-wringing.',
    spanishDescription: 'Actividad motora excesiva asociada con tensión mental, como inquietud, caminar de un lado a otro o retorcerse las manos.',
    bodyRegions: ['whole-body'],
    bodySystems: ['psychiatric', 'neurological'],
    severity: 6,
    possibleCauses: ['Anxiety disorders', 'Manic episode', 'Agitated depression', 'Delirium', 'Substance intoxication', 'Akathisia from medications'],
    redFlags: ['Severe agitation with aggression', 'Agitation with confusion', 'Risk of self-harm', 'Inability to remain still'],
    associatedSymptoms: ['Anxiety', 'Insomnia', 'Irritability', 'Racing thoughts', 'Pressured speech'],
    commonAge: 'Adults',
    prevalence: 'Common in acute psychiatric states',
  },
  {
    symptomId: 'SX-EXP-012',
    name: 'Hallucinations',
    spanishName: 'Alucinaciones',
    description: 'Perception of something that is not present, involving any sensory modality (visual, auditory, tactile, olfactory, gustatory).',
    spanishDescription: 'Percepción de algo que no está presente, involucrando cualquier modalidad sensorial (visual, auditiva, táctil, olfativa, gustativa).',
    bodyRegions: ['brain'],
    bodySystems: ['psychiatric', 'neurological'],
    severity: 9,
    possibleCauses: ['Schizophrenia', 'Delirium', 'Substance intoxication/withdrawal', 'Dementia with Lewy bodies', 'Brain tumor', 'Seizure disorder', 'Severe depression'],
    redFlags: ['New-onset hallucinations', 'Command hallucinations', 'Associated with altered consciousness', 'Focal neurological signs', 'Fever with hallucinations'],
    associatedSymptoms: ['Delusions', 'Confusion', 'Agitation', 'Sleep disturbance', 'Paranoia'],
    commonAge: 'Young adults for schizophrenia, elderly for delirium',
    prevalence: 'Uncommon in general population',
  },
  {
    symptomId: 'SX-EXP-013',
    name: 'Paranoia',
    spanishName: 'Paranoia',
    description: 'Irrational and persistent feeling that others are trying to harm or deceive you, despite lack of evidence.',
    spanishDescription: 'Sensación irracional y persistente de que otros intentan dañarte o engañarte, a pesar de la falta de evidencia.',
    bodyRegions: ['brain'],
    bodySystems: ['psychiatric'],
    severity: 7,
    possibleCauses: ['Paranoid personality disorder', 'Schizophrenia', 'Delusional disorder', 'Substance use (stimulants)', 'Dementia', 'Delirium'],
    redFlags: ['Paranoia with violent thoughts', 'Rapid onset with confusion', 'Inability to function', 'Associated psychotic symptoms'],
    associatedSymptoms: ['Anxiety', 'Social withdrawal', 'Hypervigilance', 'Sleep disturbance', 'Hallucinations', 'Delusions'],
    commonAge: 'Young to middle-aged adults',
    prevalence: 'Uncommon as primary symptom',
  },
  {
    symptomId: 'SX-EXP-014',
    name: 'Depersonalization',
    spanishName: 'Despersonalización',
    description: 'Feeling detached from oneself, as if observing oneself from outside the body or feeling unreal.',
    spanishDescription: 'Sensación de estar separado de uno mismo, como si se observara desde fuera del cuerpo o sintiéndose irreal.',
    bodyRegions: ['brain'],
    bodySystems: ['psychiatric', 'neurological'],
    severity: 5,
    possibleCauses: ['Panic disorder', 'Post-traumatic stress disorder', 'Depersonalization-derealization disorder', 'Severe stress', 'Substance use', 'Temporal lobe epilepsy'],
    redFlags: ['Persistent depersonalization interfering with function', 'Associated with suicidal ideation', 'New onset with neurological symptoms'],
    associatedSymptoms: ['Derealization', 'Anxiety', 'Panic attacks', 'Dissociation', 'Depression'],
    commonAge: 'Young adults',
    prevalence: 'Fairly common transiently (50%), chronic form rare',
  },
];
