import { EducationalContent } from '../../types';

export const DATA_SECURITY: EducationalContent = {
  id: 'wearables-data-security',
  type: 'concept',
  name: 'Health Data Security',
  alternateNames: ['Healthcare Cybersecurity', 'Medical Data Security', 'Health Information Security', 'Protected Health Information Security'],
  levels: {
    1: {
      level: 1,
      summary: 'Health data security means protecting medical information and health data from hackers, theft, and accidents using special technology and careful practices.',
      explanation: 'Just like you might lock your front door to keep your home safe, health data security is about protecting your health information from people who should not see it. Hospitals, doctors, and health apps use different tools to keep your information safe. Passwords and special codes (encryption) scramble your data so only the right people can read it. Secure networks protect information as it travels through the internet. Access controls make sure only people who need to see your health information can access it. Unfortunately, hackers sometimes try to steal health data because it is valuable. That is why healthcare organizations work hard to build strong defenses and train their staff to be careful with patient information. When you use health apps or fitness trackers, using strong passwords and keeping your apps updated helps protect your information too.',
      keyTerms: [
        { term: 'security', definition: 'Measures taken to protect health information from unauthorized access' },
        { term: 'hackers', definition: 'People who try to illegally access computer systems and data' },
        { term: 'passwords', definition: 'Secret codes used to verify identity and protect accounts' },
        { term: 'encryption', definition: 'Scrambling data so only authorized people can read it' },
        { term: 'protection', definition: 'Safeguards that keep health information safe from threats' },
      ],
    },
    2: {
      level: 2,
      summary: 'Health data security encompasses technical safeguards, organizational policies, and best practices protecting health information from unauthorized access, breaches, and cyber threats.',
      explanation: 'Healthcare organizations face significant cybersecurity challenges because health data is valuable and healthcare systems can be vulnerable. Technical security measures include encryption (scrambling data so only authorized parties can read it), access controls (limiting who can view or modify data), firewalls (blocking unauthorized network access), and intrusion detection systems (alerting when suspicious activity occurs). The HIPAA Security Rule requires covered entities to implement administrative, physical, and technical safeguards protecting electronic protected health information (ePHI). Administrative safeguards include security policies, workforce training, and risk assessments. Physical safeguards protect facilities and equipment. Technical safeguards address access controls, audit controls, integrity controls, and transmission security. Healthcare cyber threats include ransomware (malware that locks systems until payment), phishing (deceptive emails tricking users into revealing credentials), and data breaches exposing patient information. Incidents can disrupt care delivery, compromise patient privacy, and result in significant financial and reputational damage. Individual security practices matter too: using strong unique passwords, enabling two-factor authentication, keeping software updated, and being cautious with email links.',
      keyTerms: [
        { term: 'encryption', definition: 'Converting data into code to prevent unauthorized access' },
        { term: 'access controls', definition: 'Systems limiting who can view or modify data' },
        { term: 'HIPAA Security Rule', definition: 'Federal requirements for protecting electronic health information' },
        { term: 'ePHI', definition: 'Electronic protected health information subject to HIPAA' },
        { term: 'ransomware', definition: 'Malware that locks systems until payment is made' },
        { term: 'phishing', definition: 'Deceptive messages tricking users into revealing credentials' },
        { term: 'two-factor authentication', definition: 'Security requiring two forms of verification to access accounts' },
      ],
    },
    3: {
      level: 3,
      summary: 'Health data security requires comprehensive cybersecurity programs implementing defense-in-depth strategies, regulatory compliance frameworks, incident response capabilities, and continuous risk management for healthcare environments.',
      explanation: 'Healthcare cybersecurity operates within a complex threat landscape requiring sophisticated defense strategies. Defense-in-depth architectures layer multiple security controls: network segmentation isolating sensitive systems, endpoint protection on workstations and medical devices, email security filtering malicious content, and data loss prevention monitoring information flows. Encryption standards protect data at rest (stored) and in transit (transmitted), with key management practices ensuring encryption effectiveness. Identity and access management systems implement authentication (verifying identity), authorization (granting appropriate access), and accountability (logging activities). The HIPAA Security Rule mandates risk analysis, security management processes, workforce security, information access management, security awareness training, security incident procedures, contingency planning, and evaluation processes. Healthcare-specific challenges include legacy medical devices with limited security capabilities, clinical workflow requirements affecting security implementation, and third-party vendor access for system support. Incident response programs establish preparation, detection, analysis, containment, eradication, and recovery procedures for security events. Threat intelligence sharing through organizations like Health-ISAC helps healthcare entities understand and respond to emerging threats. Security frameworks including NIST Cybersecurity Framework and HITRUST CSF provide structured approaches to healthcare security program development.',
      keyTerms: [
        { term: 'defense-in-depth', definition: 'Layered security controls providing multiple protective barriers' },
        { term: 'network segmentation', definition: 'Isolating sensitive systems into separate network zones' },
        { term: 'data loss prevention', definition: 'Tools monitoring and controlling information flows to prevent leaks' },
        { term: 'key management', definition: 'Practices for securely generating, storing, and using encryption keys' },
        { term: 'identity and access management', definition: 'Systems for authentication, authorization, and accountability' },
        { term: 'incident response', definition: 'Procedures for detecting, analyzing, and recovering from security events' },
        { term: 'NIST Cybersecurity Framework', definition: 'Federal framework for managing cybersecurity risk' },
        { term: 'HITRUST', definition: 'Healthcare information trust alliance certification framework' },
      ],
    },
    4: {
      level: 4,
      summary: 'Scholarly analysis of health data security examines threat evolution, attack methodologies, healthcare-specific vulnerabilities, security economics, and the intersection of cybersecurity with patient safety and clinical operations.',
      explanation: 'Academic examination of healthcare cybersecurity spans technical, organizational, economic, and policy dimensions. Threat landscape analysis documents the evolution from opportunistic attacks to sophisticated campaigns by organized criminal groups and nation-state actors targeting healthcare for financial gain, intelligence collection, or disruption. Healthcare-specific vulnerabilities include legacy medical devices with unpatched operating systems, interoperability requirements exposing integration points, 24/7 operational requirements limiting maintenance windows, and workforce composition challenges for security awareness. Attack methodology research examines healthcare-targeted ransomware families, supply chain compromises affecting healthcare software, and social engineering techniques exploiting healthcare workflows. Security economics analyzes investment decisions, cyber insurance markets, and the financial impact of breaches including regulatory penalties, legal costs, remediation expenses, and reputation damage. Patient safety implications of cybersecurity incidents include delayed care during system outages, altered medical records, and compromised medical device function. Regulatory effectiveness studies examine whether compliance-focused approaches adequately address evolving threats or create checkbox mentality limiting actual security improvement. Research-based security improvements include machine learning for anomaly detection, formal methods for medical device security, and human factors research improving security usability. Policy debates address information sharing barriers, liability frameworks, and minimum security standards for healthcare.',
      keyTerms: [
        { term: 'threat landscape', definition: 'Evolving array of cyber threats targeting healthcare organizations' },
        { term: 'nation-state actors', definition: 'Government-sponsored groups conducting cyber attacks' },
        { term: 'legacy medical devices', definition: 'Older equipment with outdated software and security vulnerabilities' },
        { term: 'supply chain security', definition: 'Protecting against compromises in software and hardware vendors' },
        { term: 'security economics', definition: 'Analysis of cybersecurity investment decisions and breach costs' },
        { term: 'patient safety', definition: 'Implications of cyber incidents for care delivery and outcomes' },
        { term: 'regulatory effectiveness', definition: 'Assessment of whether compliance approaches adequately address threats' },
        { term: 'machine learning detection', definition: 'AI-based systems identifying anomalous activity and threats' },
      ],
    },
    5: {
      level: 5,
      summary: 'Healthcare security leadership requires strategic program development, risk-based resource allocation, incident readiness, clinical operations integration, and organizational culture development supporting cybersecurity resilience.',
      explanation: 'Building effective healthcare cybersecurity programs demands strategic leadership across technical, operational, and organizational dimensions. Governance structures establish security accountability through CISO roles, security committees, and board-level oversight, with clear policies addressing acceptable use, access management, incident response, and vendor security. Risk management programs conduct regular assessments identifying threats, vulnerabilities, and potential impacts, enabling risk-based prioritization of security investments. Technical security architecture implements defense-in-depth with network segmentation, endpoint detection and response, privileged access management, and security monitoring capabilities. Medical device security programs address inventory management, vulnerability assessment, network isolation, and procurement requirements for new devices. Vendor risk management ensures appropriate security requirements in contracts, assesses third-party security practices, and manages access to systems and data. Incident response and business continuity planning prepares for security events through documented procedures, regular exercises, and maintained backup and recovery capabilities. Workforce security programs develop security awareness through training, simulation exercises, and cultural reinforcement. Clinical operations integration ensures security controls accommodate care delivery needs while maintaining protection. Metrics and reporting demonstrate security program effectiveness to leadership and support continuous improvement. Regulatory compliance management ensures HIPAA Security Rule adherence with documentation supporting audit readiness.',
      keyTerms: [
        { term: 'security governance', definition: 'Accountability structures and policies for cybersecurity oversight' },
        { term: 'risk-based prioritization', definition: 'Allocating security resources based on threat and impact assessment' },
        { term: 'endpoint detection and response', definition: 'Tools monitoring workstations and devices for security threats' },
        { term: 'medical device security', definition: 'Programs addressing vulnerabilities in connected healthcare equipment' },
        { term: 'vendor risk management', definition: 'Assessing and managing security risks from third-party partners' },
        { term: 'business continuity', definition: 'Planning for backup and recovery during security incidents' },
        { term: 'security awareness', definition: 'Workforce training on recognizing and preventing cyber threats' },
        { term: 'metrics and reporting', definition: 'Measuring and communicating security program effectiveness' },
      ],
      clinicalNotes: 'Protect patient information by using strong passwords, locking workstations when stepping away, being cautious with email attachments and links, and reporting suspicious activities. Understand that security measures protect both patients and the organization. Follow policies regarding personal devices, removable media, and remote access. Participate in security training and recognize that clinical staff are often targeted by social engineering attacks. Report lost or stolen devices containing patient information immediately.',
    },
  },
  media: [],
  citations: [
    {
      id: 'ocr-hipaa-security-2022',
      type: 'website',
      title: 'Summary of the HIPAA Security Rule',
      authors: ['Office for Civil Rights'],
      source: 'U.S. Department of Health and Human Services',
    },
    {
      id: 'hcic-2017',
      type: 'article',
      title: 'Report on Improving Cybersecurity in the Health Care Industry',
      authors: ['Health Care Industry Cybersecurity Task Force'],
      source: 'HHS',
    },
    {
      id: 'nist-2018',
      type: 'website',
      title: 'Framework for Improving Critical Infrastructure Cybersecurity',
      authors: ['NIST'],
      source: 'National Institute of Standards and Technology',
    },
    {
      id: 'kruse-2017',
      type: 'article',
      title: 'Cybersecurity in healthcare: A systematic review of modern threats and trends',
      authors: ['Kruse CS', 'et al.'],
      source: 'Technol Health Care',
      page: '25(1):1-10',
    },
  ],
  crossReferences: [
    { targetId: 'health-data-privacy', targetType: 'concept', relationship: 'related', label: 'Health Data Privacy' },
    { targetId: 'telehealth-regulations', targetType: 'concept', relationship: 'related', label: 'Telehealth Regulations' },
    { targetId: 'ai-ethics-healthcare', targetType: 'concept', relationship: 'related', label: 'AI Ethics in Healthcare' },
    { targetId: 'remote-patient-monitoring', targetType: 'concept', relationship: 'related', label: 'Remote Patient Monitoring' },
  ],
  tags: {
    systems: ['digital-health'],
    topics: ['cybersecurity', 'data-protection', 'HIPAA', 'security', 'healthcare-IT'],
    keywords: ['health data security', 'cybersecurity', 'encryption', 'ransomware', 'HIPAA Security Rule', 'breach prevention'],
  },
  createdAt: '2025-01-28T00:00:00.000Z',
  updatedAt: '2025-01-28T00:00:00.000Z',
  version: 1,
  status: 'published',
  contributors: ['Biological Self Content Team'],
};
