import { EducationalContent } from '../../types';

export const HEALTH_DATA_PRIVACY: EducationalContent = {
  id: 'wearables-health-data-privacy',
  type: 'concept',
  name: 'Health Data Privacy',
  alternateNames: ['Medical Data Privacy', 'Patient Data Protection', 'Healthcare Privacy', 'Personal Health Information Protection'],
  levels: {
    1: {
      level: 1,
      summary: 'Health data privacy means keeping your medical information and health data safe and controlling who can see it.',
      explanation: 'Your health information is very personal, including things like what medicines you take, what conditions you have, and data from your fitness tracker or health apps. Health data privacy is about making sure this information stays safe and private. Laws like HIPAA protect your medical records at doctor\'s offices and hospitals, meaning they cannot share your information without your permission except in certain situations. But when you use health apps and fitness trackers, the rules can be different - many apps can collect and share your data in ways you might not expect. It is important to read privacy policies (even though they can be long and confusing) and think about what information you are comfortable sharing. You have rights to see your own health information and to know how it is being used. Good health data privacy means you get to decide who sees your personal health information.',
      keyTerms: [
        { term: 'privacy', definition: 'The right to control who can see your personal health information' },
        { term: 'personal information', definition: 'Data that identifies you and your health conditions' },
        { term: 'HIPAA', definition: 'A law that protects your medical information at doctors and hospitals' },
        { term: 'permission', definition: 'Consent you give for others to see your health information' },
        { term: 'medical records', definition: 'Documents containing your health history and treatments' },
      ],
    },
    2: {
      level: 2,
      summary: 'Health data privacy encompasses legal frameworks, organizational practices, and individual rights governing the collection, use, storage, and sharing of personal health information.',
      explanation: 'Health data privacy involves multiple layers of protection for sensitive medical and health-related information. In the United States, HIPAA (Health Insurance Portability and Accountability Act) establishes privacy protections for health information held by covered entities (healthcare providers, health plans, and clearinghouses) and their business associates. HIPAA gives patients rights including access to their records, the ability to request corrections, and knowledge of how their information is used. However, HIPAA does not cover many consumer health technologies like fitness trackers, health apps, and direct-to-consumer genetic testing services. For these, the FTC (Federal Trade Commission) provides some oversight under general consumer protection laws, but protections are weaker than HIPAA. Data privacy practices vary widely among health technology companies: some collect extensive data and share it with third parties for advertising or research, while others take a privacy-first approach. Individuals should review privacy policies, understand what data is collected, and use available privacy settings. International frameworks like GDPR in Europe provide stronger consumer protections including explicit consent requirements and data deletion rights.',
      keyTerms: [
        { term: 'HIPAA', definition: 'Health Insurance Portability and Accountability Act protecting health information' },
        { term: 'covered entities', definition: 'Healthcare providers, plans, and clearinghouses subject to HIPAA' },
        { term: 'business associates', definition: 'Vendors handling protected health information for covered entities' },
        { term: 'FTC', definition: 'Federal Trade Commission providing consumer protection oversight' },
        { term: 'GDPR', definition: 'European regulation providing strong data protection rights' },
        { term: 'consent', definition: 'Permission given by patients for use of their health information' },
        { term: 'patient rights', definition: 'Legal entitlements to access and control health information' },
      ],
    },
    3: {
      level: 3,
      summary: 'Health data privacy frameworks establish legal requirements and ethical principles for protecting personal health information, with distinct regulatory regimes governing clinical data, consumer health technology, and research applications.',
      explanation: 'The health data privacy landscape encompasses multiple regulatory frameworks with different scopes and requirements. HIPAA\'s Privacy and Security Rules apply to protected health information (PHI) held by covered entities, requiring administrative, physical, and technical safeguards, limiting disclosures without authorization, and establishing individual rights. Business associate agreements extend HIPAA requirements to vendors handling PHI. The HIPAA Breach Notification Rule mandates reporting of unauthorized PHI disclosures. Consumer health data falls largely outside HIPAA when not connected to covered entities, creating a regulatory gap addressed partially by FTC enforcement against deceptive privacy practices and emerging state laws (Washington\'s My Health My Data Act, California\'s CCPA/CPRA). Research use of health data involves additional frameworks including the Common Rule governing federally funded research, IRB oversight, and de-identification standards under HIPAA Safe Harbor or Expert Determination methods. International frameworks vary: GDPR provides comprehensive protections including explicit consent requirements, data minimization principles, and significant penalties for violations. Technical privacy measures include encryption, access controls, audit logging, and de-identification techniques, though re-identification risks persist with detailed health data. Ethical frameworks emphasize respect for persons, beneficence, and justice in health data stewardship.',
      keyTerms: [
        { term: 'Protected Health Information', definition: 'Individually identifiable health information subject to HIPAA' },
        { term: 'Security Rule', definition: 'HIPAA requirements for technical safeguards protecting ePHI' },
        { term: 'Breach Notification', definition: 'Requirements to report unauthorized disclosures of health information' },
        { term: 'Common Rule', definition: 'Federal regulations governing federally funded human subjects research' },
        { term: 'IRB', definition: 'Institutional Review Board overseeing research involving human subjects' },
        { term: 'de-identification', definition: 'Removing identifying information from health data' },
        { term: 'Safe Harbor', definition: 'HIPAA method for de-identification by removing specified identifiers' },
        { term: 'data minimization', definition: 'Principle of collecting only necessary information' },
      ],
    },
    4: {
      level: 4,
      summary: 'Scholarly analysis of health data privacy examines regulatory adequacy, privacy-utility tensions, re-identification risks, consent frameworks, and evolving challenges from big data, AI, and consumer health technologies.',
      explanation: 'Academic examination of health data privacy engages legal, ethical, technical, and policy perspectives. Regulatory analysis critiques gaps between HIPAA\'s scope and the expanding universe of health data, including consumer wearables, health apps, social media health disclosures, and environmental health monitoring. Privacy-utility tensions arise in research contexts where data sharing advances medical knowledge but risks individual privacy; frameworks for data governance attempt to balance these interests through controlled access, data enclaves, synthetic data, and differential privacy approaches. Re-identification research demonstrates that de-identified health data can often be re-identified through linkage with other datasets, challenging assumptions underlying Safe Harbor and similar standards. Consent frameworks face criticism for placing excessive burden on individuals through lengthy, complex privacy policies while providing limited meaningful choice; alternative models include opt-out consent, dynamic consent, and broad consent with governance oversight. Discrimination concerns arise when health data enables insurance, employment, or other decisions disadvantaging individuals based on health status, with laws like GINA providing partial protection. Emerging challenges include AI systems trained on health data raising questions about derived data ownership and algorithmic fairness, cross-border data flows complicating jurisdictional enforcement, and the proliferation of health data through social media, genomics, and IoT devices. Surveillance concerns examine how health data collection may enable governmental or commercial monitoring of individuals.',
      keyTerms: [
        { term: 'regulatory gaps', definition: 'Areas where health data lacks adequate legal protection' },
        { term: 'privacy-utility balance', definition: 'Tension between protecting data and enabling beneficial research' },
        { term: 're-identification', definition: 'Process of linking de-identified data back to individuals' },
        { term: 'consent frameworks', definition: 'Models for obtaining permission to use health data' },
        { term: 'differential privacy', definition: 'Mathematical approach adding noise to protect individual privacy' },
        { term: 'GINA', definition: 'Genetic Information Nondiscrimination Act protecting against genetic discrimination' },
        { term: 'algorithmic fairness', definition: 'Ensuring AI systems do not discriminate based on health data' },
        { term: 'data governance', definition: 'Policies and processes for responsible health data management' },
      ],
    },
    5: {
      level: 5,
      summary: 'Healthcare leaders must implement comprehensive privacy programs addressing regulatory compliance, organizational policies, technical safeguards, workforce training, and patient engagement while navigating evolving data practices and emerging technologies.',
      explanation: 'Organizational health data privacy requires systematic approaches across governance, technical, operational, and cultural dimensions. Governance frameworks establish privacy officers, oversight committees, and accountability structures with clear policies addressing data classification, access authorization, disclosure procedures, and breach response. Technical safeguards implement encryption at rest and in transit, role-based access controls, audit logging, and monitoring for anomalous access patterns. Business associate management ensures appropriate agreements and oversight of vendors handling PHI. Workforce training develops privacy awareness and compliance skills across all staff roles, with specialized training for those handling sensitive data. Breach prevention and response capabilities include vulnerability assessment, incident detection, and established procedures for investigation, notification, and remediation. Patient engagement approaches provide clear communication about privacy practices, meaningful consent processes, and accessible mechanisms for exercising privacy rights. Research data governance balances scientific advancement with privacy protection through IRB oversight, data use agreements, and appropriate de-identification or security controls. Consumer health technology integration requires assessment of privacy practices for apps and devices patients may use alongside clinical care. Regulatory monitoring tracks evolving requirements at federal and state levels, with processes for policy updates and compliance assessment. Privacy-by-design principles embed privacy considerations into new initiatives from inception. Quality metrics assess compliance, breach rates, and patient satisfaction with privacy practices.',
      keyTerms: [
        { term: 'privacy governance', definition: 'Organizational structures and policies for privacy oversight' },
        { term: 'technical safeguards', definition: 'Technology controls protecting health information' },
        { term: 'business associate management', definition: 'Oversight of vendors handling protected health information' },
        { term: 'breach response', definition: 'Procedures for investigating and reporting privacy incidents' },
        { term: 'workforce training', definition: 'Education on privacy practices and compliance requirements' },
        { term: 'patient engagement', definition: 'Communication and processes supporting patient privacy rights' },
        { term: 'research data governance', definition: 'Oversight balancing scientific advancement with privacy protection' },
        { term: 'privacy-by-design', definition: 'Embedding privacy considerations into systems from inception' },
      ],
      clinicalNotes: 'Protect patient health information through minimum necessary access, appropriate disclosures, and secure communication practices. Be aware that patient-generated health data from apps and wearables may not have the same protections as clinical data. Counsel patients about privacy implications of health technologies they use. Ensure informed consent processes address data practices. Report suspected privacy incidents through established channels. Stay current with organizational privacy policies and regulatory requirements.',
    },
  },
  media: [],
  citations: [
    {
      id: 'ocr-hipaa-privacy-2022',
      type: 'website',
      title: 'Summary of the HIPAA Privacy Rule',
      authors: ['Office for Civil Rights'],
      source: 'U.S. Department of Health and Human Services',
    },
    {
      id: 'mcgraw-2021',
      type: 'article',
      title: 'Privacy protections to encourage use of health-relevant digital data in a learning health system',
      authors: ['McGraw D', 'Mandl KD'],
      source: 'NPJ Digit Med',
      page: '4:2',
    },
    {
      id: 'rothstein-2010',
      type: 'article',
      title: 'Is Deidentification Sufficient to Protect Health Privacy in Research?',
      authors: ['Rothstein MA'],
      source: 'Am J Bioeth',
      page: '10(9):3-11',
    },
    {
      id: 'cohen-2018',
      type: 'article',
      title: 'HIPAA and Protecting Health Information in the 21st Century',
      authors: ['Cohen IG', 'Mello MM'],
      source: 'JAMA',
      page: '320(3):231-232',
    },
  ],
  crossReferences: [
    { targetId: 'data-security', targetType: 'concept', relationship: 'related', label: 'Data Security' },
    { targetId: 'telehealth-regulations', targetType: 'concept', relationship: 'related', label: 'Telehealth Regulations' },
    { targetId: 'ai-ethics-healthcare', targetType: 'concept', relationship: 'related', label: 'AI Ethics in Healthcare' },
    { targetId: 'fitness-tracker-basics', targetType: 'concept', relationship: 'related', label: 'Fitness Tracker Basics' },
  ],
  tags: {
    systems: ['digital-health'],
    topics: ['privacy', 'data-protection', 'HIPAA', 'health-information', 'patient-rights'],
    keywords: ['health data privacy', 'HIPAA', 'PHI', 'data protection', 'consent', 'patient privacy'],
  },
  createdAt: '2025-01-28T00:00:00.000Z',
  updatedAt: '2025-01-28T00:00:00.000Z',
  version: 1,
  status: 'published',
  contributors: ['Biological Self Content Team'],
};
