/**
 * Histology and Tissue Types Encyclopedia Entries
 * 
 * Transcribed from OpenStax Anatomy & Physiology Chapter 4 (CC BY 4.0)
 * The Tissue Level of Organization
 */

import type { EncyclopediaEntry } from '../types';

/**
 * Tissue Types and Histology Entry
 */
export const tissueTypesEntry: EncyclopediaEntry = {
  entryId: 'tissue-types',
  name: 'Tissue Types and Histology',
  entryType: 'anatomy',
  category: 'general',
  summary: 'The four primary tissue types—epithelial, connective, muscle, and nervous—form the structural and functional foundation of the human body, each with distinct cellular organization and physiological roles.',
  overview: {
    patient: 'Your body is made up of four main types of tissues that work together to keep you alive and functioning. Think of tissues as specialized teams of cells. Epithelial tissue forms protective coverings and linings, like your skin and the lining of your digestive tract. Connective tissue supports and connects everything together—this includes fat, cartilage, bone, and blood. Muscle tissue allows you to move, with three types: skeletal (voluntary movement), cardiac (heart beats), and smooth (internal organ movement). Nervous tissue forms your brain, spinal cord, and nerves, carrying electrical messages throughout your body. Together, these tissues form organs and organ systems that maintain your health.',
    intermediate: 'Tissues are groups of similar cells and extracellular material that perform specialized functions. The four primary tissue types are: (1) Epithelial tissue—covers body surfaces, lines cavities and hollow organs, and forms glands; characterized by polarity, avascularity, extensive innervation, and high regeneration capacity. (2) Connective tissue—protects and supports the body and its organs, binds organs together, stores energy, and provides immunity; characterized by diverse cell types suspended in abundant extracellular matrix. (3) Muscle tissue—generates force for movement; three types: skeletal (striated, voluntary, multinucleated), cardiac (striated, involuntary, single nucleus, intercalated discs), and smooth (non-striated, involuntary, single nucleus). (4) Nervous tissue—detects stimuli and transmits electrical signals; consists of neurons (conducting cells) and neuroglia (supporting cells). Understanding tissue structure (histology) is essential for comprehending organ function and disease pathology.',
    professional: 'Histology (microscopic anatomy) examines tissue architecture at the cellular level. The four fundamental tissue types exhibit distinct organizational principles: Epithelial tissue demonstrates apical-basal polarity with specialized junctional complexes (tight junctions, adherens junctions, desmosomes, gap junctions); classified by cell layers (simple, stratified, pseudostratified) and cell shape (squamous, cuboidal, columnar). Connective tissue exhibits the most diverse morphology: cells (fibroblasts, chondrocytes, osteocytes, hematopoietic cells) embedded in extracellular matrix comprising ground substance (hyaluronic acid, proteoglycans, glycoproteins) and fibers (collagen, elastic, reticular). Muscle tissue demonstrates contractile specialization: skeletal (somatic motor innervation, sarcomeres with A/I bands, H-zone, Z-discs, T-tubules at A-I junction), cardiac (autonomic innervation, branching fibers, intercalated discs with fascia adherens, desmosomes, gap junctions), and smooth (dense bodies, calmodulin-based regulation, autonomic control). Nervous tissue: neurons (soma, dendrites, axon with initial segment, axon hillock, terminal boutons) and glial cells (astrocytes, oligodendrocytes, microglia, ependymal cells in CNS; Schwann cells, satellite cells in PNS). Tissue membranes (mucous, serous, cutaneous, synovial) and glandular epithelium (exocrine with merocrine/apocrine/holocrine secretion, endocrine) complete the organizational hierarchy from cells to organ systems.',
  },
  content: [
    {
      title: 'Epithelial Tissue: Structure and Classification',
      content: {
        patient: `Epithelial tissue covers your body like protective wrapping and lines the inside of organs and cavities. You can think of it as your body's inside and outside lining. This tissue has several important characteristics: cells are packed tightly together like bricks in a wall, leaving almost no space between them. The tissue has polarity—one side faces outward or into a space (apical surface), while the other attaches to underlying tissue (basal surface). Epithelial tissue doesn't have blood vessels (it's avascular), so it gets nutrients from blood vessels in the connective tissue underneath. It's also highly regenerative—skin constantly replaces itself, and the lining of your intestines renews every few days.

Epithelial tissue is classified in two ways: by the number of cell layers and by the shape of the cells. Simple epithelium has one layer; stratified has multiple layers for extra protection. Pseudostratified looks layered but is actually one cell layer where cells are different heights. Cell shapes include squamous (flat like floor tiles), cuboidal (cube-shaped), and columnar (tall and rectangular like columns). These classifications combine to describe each type: simple squamous, stratified squamous, simple cuboidal, and so on.`,
        intermediate: `Epithelial tissue covers body surfaces, lines cavities and hollow organs, and forms glands. Key characteristics: (1) Polarity—apical surface (free, often with microvilli or cilia) and basal surface (attached to basement membrane); (2) Specialized contacts—cells connected by tight junctions, desmosomes, and gap junctions; (3) Supported by connective tissue—basement membrane (basal lamina + reticular lamina) anchors epithelium; (4) Avascular but innervated—no blood vessels but rich nerve supply; (5) Regeneration—high mitotic rate due to environmental exposure and damage.

Classification by layers: Simple epithelium (single layer, thin barrier for diffusion/filtration/ absorption/ secretion), stratified epithelium (two+ layers, protection), pseudostratified epithelium (single layer of cells at different heights, appears stratified, all cells contact basement membrane).

Classification by cell shape: Squamous (flat, scale-like), cuboidal (cube-shaped, spherical central nucleus), columnar (tall, column-like, oval nucleus near base). In stratified epithelium, named by shape of apical layer cells.

Common types: Simple squamous (endothelium lining vessels, mesothelium lining body cavities—allows diffusion), simple cuboidal (kidney tubules, ducts—secretion/absorption), simple columnar (digestive tract lining—absorption/secretion, often with goblet cells), pseudostratified ciliated columnar (respiratory tract—mucus movement), stratified squamous keratinized (epidermis—protection), stratified squamous non-keratinized (mouth, esophagus, vagina—moist protection), stratified cuboidal/columnar (rare, ducts), transitional (urinary tract—stretching ability).`,
        professional: `Epithelial tissue histology and classification:

Structural characteristics: Polarity maintained by distinct apical and basolateral membrane domains with different lipid and protein composition. Apical specializations: microvilli (actin-based, 1 μm long, increase surface area 20-fold for absorption, striated border in intestine, brush border in kidney), stereocilia (long microvilli, epididymis), cilia (9+2 microtubule axoneme, motile for mucus/cell movement, respiratory epithelium, oviducts), flagellum (sperm only). Junctional complexes: tight junctions (zonula occludens, occludin/claudin proteins, seal intercellular space), adherens junctions (zonula adherens, cadherins, actin-linked), desmosomes (macula adherens, cadherins, intermediate filament-linked), gap junctions (connexons/connexins, intercellular communication). Basement membrane: basal lamina (lamina lucida—laminin, lamina densa—type IV collagen) synthesized by epithelium; reticular lamina (type III collagen) from connective tissue; hemidesmosomes anchor cells to basement membrane.

Classification systems: By cell layers—simple (single layer, all cells contact basement membrane; thin for diffusion, absorption, secretion), stratified (two or more layers; basal cells regenerate, superficial cells slough; protection against abrasion), pseudostratified (single layer with varying cell heights, all contact basement membrane but not all reach apical surface; often ciliated with goblet cells). By cell morphology—squamous (flattened, disc-shaped nuclei, minimal cytoplasm), cuboidal (roughly equal dimensions, spherical central nuclei), columnar (tall, rectangular, basal oval nuclei, apical cytoplasm with organelles).

Specific epithelial types and locations: Simple squamous (endothelium—heart, blood/lymphatic vessels; mesothelium—pleura, pericardium, peritoneum; kidney glomerulus; air sacs of lungs). Simple cuboidal (kidney tubules; thyroid follicles; surface of ovary; ducts of glands). Simple columnar (gastrointestinal tract from stomach to anus; gallbladder; excretory ducts of glands; uterus; oviducts—often ciliated). Pseudostratified ciliated columnar (trachea, bronchi; nasal cavity; epididymis). Stratified squamous keratinized (epidermis; palms/soles thick, other areas thin). Stratified squamous non-keratinized (mouth, esophagus, vagina, anus; moist surfaces). Stratified cuboidal (sweat gland ducts; ovarian follicular cells; rare). Stratified columnar (conjunctiva; pharynx; anus; mammary glands; rare). Transitional (urothelium—renal pelvis, ureters, bladder, urethra; allows stretching; dome-shaped superficial cells when relaxed, squamous when distended).`,
      },
    },
    {
      title: 'Connective Tissue: The Body\'s Support Network',
      content: {
        patient: `Connective tissue is the most abundant and diverse tissue type in your body. Unlike epithelial tissue where cells are packed tight, connective tissue has cells scattered within a lot of extracellular material called matrix. This matrix consists of ground substance (a gel-like material) and protein fibers. Think of it like fruit suspended in Jell-O—the fruit are the cells, and the Jell-O is the matrix.

All connective tissues share three common components: cells, fibers, and ground substance. However, the proportions vary enormously. Blood has lots of fluid matrix with scattered cells; bone has abundant matrix with trapped cells; fat is mostly cells with minimal matrix. This diversity allows connective tissue to perform many functions: binding and supporting (tendons, ligaments, cartilage), protecting (bone, fat cushioning), insulating (fat), storing fuel (fat), and transporting substances (blood). Connective tissue proper has two subclasses: loose connective tissue (areolar, adipose, reticular) and dense connective tissue (regular, irregular, elastic).`,
        intermediate: `Connective tissue is characterized by: (1) Common embryonic origin—all arise from mesenchyme (embryonic tissue); (2) Variable vascularity—cartilage avascular, bone highly vascular, others intermediate; (3) Extracellular matrix—abundant matrix with cells suspended; (4) Major functions—binding/support, protection, insulation, storage, transportation.

Common components: Cells—blast cells (immature, mitotic, matrix-secreting: fibroblasts, chondroblasts, osteoblasts), cyte cells (mature, maintain matrix: chrocytes, osteocytes), clast cells (break down matrix: osteoclasts). Ground substance—unstructured material filling space between cells and fibers; composed of interstitial fluid, cell adhesion proteins (fibronectin, laminin), and proteoglycans (hyaluronic acid core + protein + GAGs like chondroitin/keratan sulfate). Fibers—collagen (white, strong, flexible, type I most common, types II-IV others), elastic (yellow, stretch and recoil, elastin + fibrillin), reticular (fine collagen type III, branching network).

Classification: Connective tissue proper (loose: areolar, adipose, reticular; dense: regular, irregular, elastic), Supporting connective tissue (cartilage: hyaline, elastic, fibrocartilage; bone: compact, spongy), Fluid connective tissue (blood, lymph).`,
        professional: `Connective tissue histology and classification:

Embryonic connective tissue: Mesenchyme (embryonic origin of all CT; star-shaped mesenchymal cells in gel-like ground substance with fibers; differentiates into all CT types). Mucous connective tissue (Wharton\'s jelly; umbilical cord only; gelatinous ground substance with collagen and fibroblasts).

Cell types by function: Resident cells (native to tissue, involved in production/maintenance): fibroblasts (synthesize collagen, elastin, reticular fibers, ground substance), chondroblasts/chondrocytes (cartilage matrix—type II collagen, proteoglycans), osteoblasts/osteocytes (bone matrix—type I collagen, hydroxyapatite), adipocytes (lipid storage—white/brown types). Wandering cells (immune/inflammatory): macrophages (phagocytosis, antigen presentation), mast cells (histamine, heparin, inflammatory mediators), plasma cells (antibody production from B cells), leukocytes (neutrophils, eosinophils, lymphocytes—in inflammation/immunity). Structural support cells: reticular cells (stroma for lymphoid organs).

Extracellular matrix composition: Ground substance—viscous, gel-like; components: interstitial fluid, glycosaminoglycans (GAGs: hyaluronic acid, chondroitin sulfate, dermatan sulfate, keratan sulfate, heparan sulfate), proteoglycans (core protein + GAGs), glycoproteins (fibronectin, laminin, chondronectin, osteonectin—cell adhesion, matrix organization). Fibers—collagen (type I—skin, bone, tendons, 90% body collagen; type II—cartilage; type III—reticular; type IV—basement membrane; type V—interstitial with type I); elastic (elastin core with fibrillin microfibrils; recoil property; skin, lungs, arteries); reticular (type III collagen, glycosylated, fine branching network; lymphoid organs, liver, basement membrane).

Classification scheme: Connective tissue proper (loose CT—areolar, adipose, reticular; dense CT—regular, irregular, elastic), Supporting CT (cartilage—hyaline, elastic, fibrocartilage; bone—compact, spongy), Fluid CT (blood, lymph).`,
      },
    },
    {
      title: 'Connective Tissue Types: Proper, Cartilage, and Bone',
      content: {
        patient: `Connective tissue proper comes in loose and dense varieties. Loose connective tissue (areolar) is like the body's "packing material"—it wraps and cushions organs and contains all fiber types along with various cells. Adipose tissue is body fat—cells filled with fat droplets that insulate, store energy, and protect organs. Reticular tissue forms a soft internal skeleton (stroma) supporting cells in lymph organs like the spleen and lymph nodes.

Dense connective tissue has more fibers and less ground substance. Dense regular (tendons and ligaments) has collagen fibers arranged in parallel for strength in one direction—tendons connect muscle to bone, ligaments connect bone to bone. Dense irregular (dermis, organ capsules) has fibers going in all directions for strength from any angle. Elastic tissue (artery walls, vocal cords) can stretch and return to shape.

Supporting connective tissue provides strong structural support. Cartilage is firm but flexible—hyaline covers bone ends and forms the nose/trachea; elastic cartilage (ears, epiglottis) is more flexible; fibrocartilage (knee meniscus, intervertebral discs) resists compression and shear. Bone (osseous tissue) is calcified connective tissue—compact bone forms the hard outer layer, while spongy bone inside has a honeycomb structure.`,
        intermediate: `Connective tissue proper subclasses:

Loose connective tissue: Areolar CT—most widely distributed; gel-like ground substance with all three fiber types (collagen, elastic, reticular); fibroblasts, macrophages, mast cells, some WBCs; wraps and cushions organs; macrophages phagocytize bacteria; important for inflammation. Adipose CT—adipocytes dominant; white adipose (unilocular—single large lipid droplet, nucleus pushed to side; energy storage, insulation, cushioning; highly vascularized; leptin production), brown adipose (multilocular—multiple small lipid droplets, abundant mitochondria; thermogenesis in newborns); subcutaneous layer, around kidneys/eyes, breasts, bone marrow. Reticular CT—reticular fibers form delicate network (stroma); supports functional cells in lymphoid organs (lymph nodes, spleen, bone marrow); fibroblasts + leukocytes.

Dense connective tissue: Dense regular—parallel collagen fibers with fibroblasts between; poorly vascularized; withstands tension in ONE direction; tendons (muscle-to-bone), ligaments (bone-to-bone), aponeuroses (sheet-like tendons). Dense irregular—irregularly arranged collagen fibers with some elastic; withstands tension from MANY directions; dermis, fibrous joint capsules, organ coverings. Elastic—high proportion of elastic fibers; allows stretching and recoil; walls of large arteries (aorta), certain ligaments (ligamentum flavum), bronchial tubes.

Supporting connective tissue: Cartilage—firm, gel-like matrix with chondrocytes in lacunae (small spaces); avascular, slow to heal; perichondrium (dense irregular CT sheath) provides nutrients; hyaline (glassy matrix, most abundant, covers bone ends, costal cartilage, nose, trachea, larynx, fetal skeleton), elastic (more elastic fibers, flexible, external ear, epiglottis), fibrocartilage (thick collagen fibers, rows of chondrocytes, resists compression/shear, intervertebral discs, pubic symphysis, menisci). Bone (osseous tissue)—calcified matrix with osteocytes in lacunae; highly vascularized; compact bone (dense outer layer, osteons/Haversian systems), spongy bone (trabecular/cancellous, honeycomb, red marrow sites).`,
        professional: `Connective tissue types—detailed histology:

Loose connective tissue proper: Areolar CT—ground substance: abundant, viscous; fibers: collagen (thick, type I), elastic (thin, branching), reticular (fine, type III); cells: fibroblasts (spindle-shaped, produce matrix), macrophages (kidney-shaped, phagocytic), mast cells (round, granulated), plasma cells (eccentric nucleus, clock-face chromatin), adipocytes, WBCs. Location: under epithelia, packages organs, surrounds capillaries. Functions: wraps/cushions, holds tissue fluid, macrophage phagocytosis, inflammation site.

Adipose CT—White adipose tissue (WAT): unilocular adipocytes (80-90% lipid by volume); large central lipid droplet pushes nucleus and thin cytoplasm rim to periphery (signet ring appearance); highly vascularized; innervated; leptin, adiponectin, cytokine secretion; metabolic/endocrine functions. Brown adipose tissue (BAT): multilocular adipocytes with many small lipid droplets; abundant mitochondria with uncoupling protein-1 (UCP-1/thermogenin); non-shivering thermogenesis; prominent in newborns (interscapular, neck), less in adults (supraclavicular, paravertebral). Beige/brite adipocytes (inducible brown-like in WAT depots).

Reticular CT—Meshwork of reticular fibers (type III collagen + glycoprotein coating); argyrophilic (stain with silver); reticular cells (fibroblast-like); forms stroma supporting parenchymal cells in bone marrow, spleen, lymph nodes; allows free cell movement for immune function.

Dense connective tissue proper: Dense regular—tightly packed parallel collagen fibers (type I) with rows of fibroblasts between; minimal ground substance; low metabolic activity; poor healing due to avascularity; tensile strength: 50-100 MPa parallel, weak perpendicular. Tendons (muscle-to-bone transmission), ligaments (bone-to-bone stabilization), aponeuroses (broad flat tendons). Dense irregular—interwoven meshwork of collagen bundles (type I) in all planes; resists multidirectional tension; dermis, organ capsules, periosteum, perichondrium, heart valves. Elastic—predominantly elastic fibers with collagen; fibroblasts; fenestrated sheets or ligaments; elastic laminae in large arteries, vocal ligaments, suspensory ligaments of penis, ligamentum flavum, ligamentum nuchae.

Cartilage: Hyaline—matrix appears glassy/homogeneous (fine type II collagen not visible by light microscopy); territorial matrix (around lacunae) vs interterritorial matrix; chondrocytes in lacunae, often in isogenous groups (cell nests from division); perichondrium except articular cartilage; locations: articular surfaces, costal cartilages, nose, larynx, trachea, bronchial tree, fetal skeleton. Elastic—perichondrium present; abundant elastic fibers in matrix (visible with special stains); chondrocytes in lacunae; highly flexible; external ear, epiglottis, larynx apex, eustachian tube. Fibrocartilage—intermediate between dense regular CT and hyaline cartilage; thick type I collagen bundles (like tendon); rows of chondrocytes in lacunae; no perichondrium; resists compression AND shear; intervertebral discs, pubic symphysis, menisci, TMJ discs.

Bone (osseous tissue): Matrix—organic (35%—type I collagen, osteocalcin, osteonectin) and inorganic (65%—hydroxyapatite Ca₁₀(PO₄)₆(OH)₂ crystals); hardness from mineral, flexibility from collagen. Cells—osteoprogenitor cells (stem cells), osteoblasts (matrix secretion, cuboidal on surface), osteocytes (mature, in lacunae, mechanosensors), osteoclasts (multinucleated, bone resorption, ruffled border). Compact bone—osteons/Haversian systems (concentric lamellae around central canal), osteocytes in lacunae connected by canaliculi, circumferential lamellae, interstitial lamellae, perforating/Volkmann's canals. Spongy/cancellous bone—trabeculae forming lattice; spaces contain red bone marrow; oriented along stress lines; no osteons; covers by endosteum.`,
      },
    },
    {
      title: 'Muscle Tissue: Contraction and Movement',
      content: {
        patient: `Muscle tissue is specialized for contraction—generating force to produce movement. Your body has three types of muscle tissue, each with distinct characteristics. Skeletal muscle attaches to bones and enables voluntary movements like walking, talking, and facial expressions. These muscle cells are long, cylindrical, and have multiple nuclei. Under a microscope, they show alternating light and dark stripes called striations. You control skeletal muscle consciously.

Cardiac muscle forms your heart wall. Like skeletal muscle, it's striated, but the cells are shorter, branched, and have only one nucleus each. Most importantly, cardiac muscle cells connect end-to-end through special junctions called intercalated discs that allow electrical signals to spread quickly, coordinating heartbeats. Cardiac muscle contracts automatically without conscious control.

Smooth muscle is found in the walls of hollow organs like your stomach, intestines, bladder, and blood vessels. These cells are spindle-shaped with one central nucleus and lack striations. Smooth muscle contracts slowly but can sustain contractions for long periods. It controls involuntary movements like digestion and blood vessel diameter.`,
        intermediate: `Muscle tissue comparison:

Skeletal muscle: Striated, voluntary (somatic nervous system control), multinucleated (peripheral nuclei), long cylindrical fibers. Function: locomotion, manipulation of environment, facial expression, voluntary control. Structure: muscle → fascicles → fibers → myofibrils → sarcomeres (contractile units). Sarcomere organization: Z-discs at ends, I-band (thin actin filaments only), A-band (thick myosin + actin overlap), H-zone (myosin only, disappears in contraction), M-line (middle). T-tubules at A-I junction; triad with terminal cisternae of sarcoplasmic reticulum; sarcolemma (muscle cell membrane).

Cardiac muscle: Striated, involuntary (autonomic nervous system plus intrinsic conduction), single central nucleus (occasionally binucleate), short branched cells. Intercalated discs at cell junctions contain fascia adherens (anchoring), desmosomes (strength), and gap junctions (electrical coupling for coordinated contraction). Intercalated discs allow rapid spread of action potentials as functional syncytium. Myocardium contraction is autorhythmic (SA node, AV node, Purkinje fibers) with neural and hormonal modulation. High mitochondria density (30% cell volume) for aerobic metabolism.

Smooth muscle: Non-striated, involuntary (autonomic nervous system), single central nucleus, spindle-shaped (fusiform) cells tapered at ends. Lack organized sarcomeres; instead have dense bodies (analogous to Z-discs) and intermediate filaments with smooth muscle myosin and actin arranged obliquely. Slow, sustained contractions with low energy cost (latch mechanism); can maintain tone without continuous ATP use. Location: walls of hollow visceral organs (GI tract, uterus, urinary bladder, blood vessels), respiratory tract, iris/ciliary body of eye, arrector pili of skin.

Regeneration capacity: Skeletal—limited, satellite cells can regenerate; Cardiac—minimal, scar formation; Smooth—good, hyperplasia and hypertrophy.`,
        professional: `Muscle tissue histology and physiology:

Skeletal muscle histology: Muscle fiber (cell) is long cylindrical syncytium formed by fusion of myoblasts; sarcolemma with invaginations forming T-tubules (transverse tubules) at A-I junctions in mammalian muscle; sarcoplasm (cytoplasm) contains myofibrils, glycogen, myoglobin, mitochondria; multinucleated with peripheral subsarcolemmal nuclei. Myofibrils—longitudinal bundles of thick (myosin, 15 nm diameter, bipolar with ATPase heads) and thin (actin, troponin, tropomyosin, 8 nm diameter) filaments organized into sarcomeres (2-3 μm length). Sarcomere structure: Z-discs (Z-lines, zwichenscheibe)—protein boundary anchoring thin filaments (α-actinin); M-line (mittelscheibe)—proteins connecting thick filaments (myomesin, C-protein); I-band—light, thin filaments only, bisected by Z-disc; A-band—dark, thick filaments, length constant; H-zone—lighter center of A-band with thick filaments only; A-bands contain both thick and thin filaments in overlap zone. Sarcoplasmic reticulum (SR)—specialized smooth ER surrounding myofibrils; terminal cisternae (enlarged portions) form triads with T-tubules; stores and releases Ca²⁺. Motor neuron axons form neuromuscular junctions; action potential → T-tubule → SR Ca²⁺ release → contraction.

Cardiac muscle histology: Cardiac myocytes (cardiac muscle cells)—short (50-100 μm), branched, 1-2 central nuclei; contain myofibrils with sarcomeres and striations (less organized than skeletal); abundant mitochondria (25-30% cell volume); numerous large mitochondria between myofibrils for aerobic metabolism; intercalated discs—specialized cell junctions at Z-disc level containing three junction types: fascia adherens (anchoring site for actin filaments, analogous to Z-disc), macula adherens (desmosomes with desmoglein/desmocollin for mechanical coupling), gap junctions (nexus with connexin-43 for electrical coupling, low resistance pathways allowing rapid AP spread). Functional syncytium—electrical continuity allows coordinated wave of contraction from pacemaker through myocardium. Granular sarcoplasmic reticulum and T-tubules at Z-disc level (vs A-I junction in skeletal); diads rather than triads.

Smooth muscle histology: Smooth muscle cells (smooth muscle fibers)—spindle-shaped, 20-500 μm long, 5-10 μm diameter, single elongated central nucleus; lack striations due to absence of organized sarcomeres; thick (myosin) and thin (actin) filaments present with ratio 1:12-30 (vs 1:2 in skeletal); 10-15 nm intermediate filaments (desmin, vimentin). Dense bodies—electron-dense structures in cytoplasm (analogous to Z-discs) containing α-actinin; dense plaques on cell membrane anchor thin filaments. Filament arrangement oblique rather than longitudinal—allows cell shortening and twisting. Intermediate filaments form cytoskeletal network with dense bodies. Caveolae (invaginations of sarcolemma) function as T-tubule equivalents for Ca²⁺ entry. Sarcoplasmic reticulum less developed than striated muscle. Gap junctions present in visceral smooth muscle for coordinated contraction (single-unit/smooth muscle); multi-unit smooth muscle (vascular, respiratory) has few gap junctions with individual innervation.

Regeneration: Skeletal—satellite cells (quiescent myogenic stem cells between sarcolemma and basal lamina) activated by injury; proliferate, differentiate, fuse to repair damage; limited capacity, excessive damage leads to fibrosis. Cardiac—minimal regenerative capacity in adults (debated 0.5-1% annual turnover); injury → fibroblast activation → collagen scar; non-contractile scar alters mechanical/electrical properties. Smooth—good regenerative capacity via hypertrophy (cell enlargement) and hyperplasia (cell division); uterus hypertrophy during pregnancy; arterial smooth muscle proliferation in atherosclerosis.`,
      },
    },
    {
      title: 'Nervous Tissue: Communication and Control',
      content: {
        patient: `Nervous tissue forms your body's communication network—the brain, spinal cord, and nerves. It has two main cell types. Neurons are the signaling cells that transmit electrical and chemical messages. They have three main parts: the cell body (containing the nucleus), dendrites (branching extensions that receive signals), and an axon (a long fiber that transmits signals away). Neurons can be very long—some stretch from your spine to your toes!

Neuroglia (glial cells) are the support cells that outnumber neurons and provide many essential functions. In the brain and spinal cord (central nervous system), astrocytes support and nourish neurons, oligodendrocytes form insulation around axons, microglia act as immune defenders, and ependymal cells line fluid-filled spaces. In the nerves outside the brain (peripheral nervous system), Schwann cells form insulation, and satellite cells support neuron cell bodies. Glial cells don't transmit signals but are essential for nervous system function.

The nervous system works by generating electrical signals (action potentials) in neurons. These signals travel along axons to communicate with other neurons, muscles, or glands. Communication between cells occurs at synapses through chemical messengers called neurotransmitters.`,
        intermediate: `Nervous tissue comprises neurons (excitable cells generating/conducting nerve impulses) and neuroglia (supporting cells). Neurons: Highly specialized for electrical/chemical signaling; high metabolic demand; generally amitotic (limited regeneration in CNS, some in PNS). Structure: Cell body/soma/perikaryon—contains nucleus, abundant rough ER (Nissl bodies), Golgi, mitochondria; maintains cell. Dendrites—short, highly branched processes receiving signals; contain Nissl bodies; conduct graded potentials toward soma. Axon—single long process (can be 1+ meters) transmitting action potentials away; axon hillock (trigger zone) contains voltage-gated channels initiating APs; telodendria/axon terminals branch at end for synaptic transmission; axolemma (axon membrane), axoplasm (cytoplasm); cytoskeletal elements (neurofilaments, microtubules) for transport. Myelination—Schwann cells (PNS) or oligodendrocytes (CNS) wrap axons with myelin (lipid-rich) for insulation and saltatory conduction; nodes of Ranvier (unmyelinated gaps) contain voltage-gated channels.

Neuroglia (glial cells)—support, protect, nourish neurons; smaller, more numerous; capable of mitosis: CNS glia—astrocytes (star-shaped, blood-brain barrier component, regulate ion/water balance, glutamate reuptake, glycogen storage), oligodendrocytes (form myelin sheaths around CNS axons, one cell myelinates multiple axon segments), microglia (small, phagocytic, CNS immune defense, originate from monocytes), ependymal cells (line ventricles and central canal, ciliated for CSF movement, some produce CSF). PNS glia—Schwann cells (myelinate single PNS axon segment or envelope unmyelinated axons, neurolemmocytes), satellite cells (surround ganglia neuron cell bodies, regulate microenvironment).

Functional classification: Sensory (afferent)—transmit impulses TO CNS from receptors. Motor (efferent)—transmit impulses FROM CNS to effectors (muscles/glands). Interneurons (association)—within CNS, integrate/processing, 99% of neurons. Structural classification: Multipolar (multiple dendrites, one axon; most common, motor neurons), bipolar (one dendrite, one axon; retina, olfactory epithelium, vestibulocochlear), pseudounipolar (single process splits; sensory ganglia).`,
        professional: `Nervous tissue histology and cell biology:

Neuron structure and classification: Cell body/soma—5-100+ μm diameter; nucleus large, pale, euchromatic with prominent nucleolus; cytoplasm rich in rough ER (Nissl bodies, tigroid bodies visible with light microscopy—protein synthesis for neuron), free ribosomes, Golgi, mitochondria, neurofilaments (intermediate filaments, 10 nm), microtubules (25 nm), neuromelanin/lipofuscin (aging pigment). Cytoskeleton—neurofilaments provide structural support; microtubules for axonal transport (kinesin toward + end/anterograde, dynein toward - end/retrograde); actin in growth cones and synapses. Dendrites—receive synaptic input; highly branched (dendritic tree); dendritic spines (small protrusions increasing surface area, postsynaptic sites); contain Nissl bodies and organelles; conduct graded potentials (electrotonic conduction) decrementally. Axon—arises from axon hillock (no Nissl bodies, high density voltage-gated Na⁺ channels—trigger zone); initial segment most excitable; uniform diameter (0.2-20 μm); axon proper uniform structure; collateral branches; terminal arborization/telodendria ending in synaptic boutons/knobs/terminals; presynaptic terminals contain synaptic vesicles (neurotransmitters), mitochondria, active zones.

Axonal transport: Anterograde (soma to terminal)—fast (100-400 mm/day, organelles, vesicles, membranous components via kinesin), slow component a (SCa, 0.1-1 mm/day, cytoskeletal elements), slow component b (SCb, 2-8 mm/day, soluble proteins). Retrograde (terminal to soma)—fast (200 mm/day, endosomes, multivesicular bodies, signaling complexes via dynein); important for trophic factor signaling, pathogen transport (tetanus, rabies).

Myelination and conduction: Myelin—compact spiral wrapping of glial cell membrane (75-80% lipid, 20-25% protein); major dense lines (apposed cytoplasmic surfaces), intraperiod lines (apposed extracellular surfaces); myelin basic protein (cytoplasmic), proteolipid protein (transmembrane) in CNS; P0, PMP22 in PNS. Nodes of Ranvier—1-2 μm gaps between myelin segments with high density Na⁺ channels; paranodal loops (glial cytoplasmic collars); juxtaparanodal K⁺ channels. Saltatory conduction—AP jumps between nodes; speeds conduction, saves energy. Schwann cell—one per internode (PNS); neurofascin/neurofascin adhesion; basal lamina surrounds; can guide regeneration. Oligodendrocyte—up to 50 internodes from one cell (CNS); inhibitory molecules (Nogo, MAG, OMgp) limit regeneration.

Glial cells—CNS: Astrocytes—protoplasmic (gray matter, complex processes enveloping synapses) and fibrous (white matter, fewer processes); express GFAP; foot processes on vessels (blood-brain barrier), pia (glia limitans); regulate extracellular K⁺ (spatial buffering), pH, transmitters (glutamate transporters GLT-1/GLAST, GABA uptake); glycogen storage; release gliotransmitters (ATP, D-serine, glutamate); respond to injury (reactive astrogliosis). Oligodendrocytes—myelinate CNS axons; precursors (NG2 cells) persist in adult; inhibitory to axon regeneration; vulnerable to hypoxia, demyelinating diseases. Microglia—CNS macrophages/mononuclear phagocytes; ramified/resting (surveillance) or activated/amoeboid (phagocytic); CX3CR1/fractalkine signaling; neuroinflammation, synaptic pruning, debris clearance. Ependymal cells—cuboidal/columnar epithelium lining ventricles; ciliated (CSF flow), microvilli (absorption); specialized ependyma: choroid plexus epithelium (produces CSF with tight junctions).

PNS glia: Schwann cells—myelinating (form internodes, one per axon segment) or non-myelinating (Remak cells, envelope multiple unmyelinated axons in cytoplasmic grooves); neurotrophic support; basal lamina (laminin, collagen IV) surrounds; essential for regeneration (bands of Büngner guide axons); express NGF, BDNF, GDNF. Satellite cells—caps of flattened glial cells surrounding neuron somata in sensory/motor ganglia; regulate microenvironment (ion balance, neurotransmitter uptake); gap junctions between satellite cells. Enteric glia—in gut wall, similar to astrocytes.

Neuroglial functions: Structural support, ion/water homeostasis, neurotransmitter recycling, myelination, immune defense, blood-brain barrier, metabolic/nutritional support, synaptic modulation, developmental guidance. Glial cells outnumber neurons 10-50:1 depending on region; constitute ~50% brain volume but 90% brain cells; essential for all nervous system function.`,
      },
    },
    {
      title: 'Tissue Membranes and Glands',
      content: {
        patient: `Tissue membranes are thin protective layers that line cavities and cover surfaces. Your body has four main types. Mucous membranes (mucosae) line body cavities that open to the outside—like your digestive tract, respiratory tract, and urinary tract. They secrete mucus that lubricates and traps particles. Serous membranes (serosae) line closed body cavities and cover organs within them—the pleura covers your lungs, pericardium covers your heart, and peritoneum covers your abdominal organs. They secrete a thin, watery fluid that reduces friction. The cutaneous membrane is your skin—the largest membrane. Synovial membranes line joint cavities and secrete lubricating synovial fluid for smooth movement.

Glands are epithelial cell structures that produce and secrete substances. Exocrine glands have ducts that carry their secretions to epithelial surfaces—sweat glands, oil glands, salivary glands, and digestive glands. Endocrine glands are ductless and secrete hormones directly into the bloodstream to act on distant target organs—thyroid, adrenal, and pituitary glands. Exocrine glands use different secretion methods: merocrine (cells release products by exocytosis, like sweat glands), apocrine (part of cell pinches off with secretion, like mammary glands), and holocrine (whole cells rupture to release product, like oil glands).`,
        intermediate: `Tissue membranes:

Mucous membranes (mucosae): Line body cavities opening to exterior (digestive, respiratory, urinary, reproductive tracts). Structure: epithelium (varies by location—non-keratinized stratified squamous in mouth/esophagus/vagina; simple columnar in intestines; pseudostratified ciliated columnar in respiratory) overlying areolar connective tissue (lamina propria). Functions: absorption, secretion, protection; mucus from goblet cells and glands traps particles, lubricates, protects epithelium; sometimes called mucosa.

Serous membranes (serosae): Line closed ventral body cavities and cover organs; simple squamous epithelium (mesothelium) overlying areolar connective tissue. Produce serous fluid (watery, lubricating) between parietal (cavity wall) and visceral (organ) layers. Types: pleura (lungs—parietal pleura lines thoracic cavity, visceral pleura covers lungs; pleural cavity with serous fluid), pericardium (heart—fibrous pericardium outer, parietal serous pericardium, visceral serous pericardium/epicardium; pericardial cavity), peritoneum (abdominopelvic cavity—parietal peritoneum lines cavity, visceral peritoneum covers organs; peritoneal cavity with minimal fluid). Functions: reduce friction between organs and cavity walls.

Cutaneous membrane: Skin; keratinized stratified squamous epithelium (epidermis) over dense irregular connective tissue (dermis); dry membrane unlike mucous/serous.

Synovial membranes: Line joint cavities (synovial joints), tendon sheaths, bursae. Structure: modified connective tissue—no epithelium! Intima (cell layer: synoviocytes type A—macrophage-like, type B—fibroblast-like) over subintima (connective tissue, varies in density). Secrete synovial fluid (filtrate of blood plasma + hyaluronic acid secreted by type B synoviocytes); viscous, lubricating, nutrient supply for avascular cartilage. Functions: lubrication, nutrient delivery to cartilage.

Glandular epithelium: Glands—one or more cells making and secreting aqueous fluid. Classification: By site—endocrine (ductless, secrete hormones into blood/interstitial fluid, target distant cells) vs exocrine (have ducts carrying secretion to epithelial surface). By number of cells—unicellular (goblet cells in epithelia secrete mucus) vs multicellular (glands with duct and secretory unit). By duct structure—simple (unbranched duct) vs compound (branched duct). By secretory unit shape—tubular (tube-like), alveolar/acinar (flask-like sac), tubuloalveolar (both). By secretion type—serous (thin, watery, enzyme-rich), mucous (thick mucus), mixed (both cell types).`,
        professional: `Tissue membranes and glandular epithelium:

Mucous membranes—detailed structure: Epithelial component varies by functional demands: stratified squamous non-keratinized (mouth, oropharynx, esophagus, anal canal, vagina—abrasion resistance), simple columnar (stomach, intestines, gallbladder—absorption/secretion), pseudostratified ciliated columnar with goblet cells (respiratory tract—mucociliary clearance), transitional (urinary tract—distension). Lamina propria—areolar connective tissue with vessels, lymphoid tissue (MALT), glands; can have muscularis mucosae (smooth muscle) in digestive tract. Specialized mucosae: olfactory (pseudostratified with olfactory receptors), gastric (simple columnar with gastric pits/glands), intestinal (simple columnar with villi/crypts). Functions: barrier protection (mechanical, chemical, microbial), selective absorption, secretion (digestive enzymes, mucus, antibodies), immune surveillance (MALT with lymphocytes, plasma cells, macrophages).

Serous membranes—ultrastructure: Mesothelium—simple squamous epithelium with microvilli; tight junctions; glycocalyx; secrete glycosaminoglycans/hyaluronan for lubrication; phagocytic capability. Serous fluid—ultrafiltrate of plasma; hyaluronic acid; phospholipids (surfactant apoproteins in pleura); 5-15 mL in peritoneal cavity, 10-20 mL in pleural cavities, 10-50 mL in pericardium. Clinical significance: inflammation (pleuritis, pericarditis, peritonitis) causes pain (somatosensory innervation of parietal layer) and fluid accumulation (effusion); mesothelioma (malignancy of mesothelium associated with asbestos).

Synovial membrane histology: Intimal lining—1-4 cells deep, not true epithelium (no basement membrane, derived from mesenchyme); type A synoviocytes (macrophage-like, CD68+, phagocytic, debris removal), type B synoviocytes (fibroblast-like, fibroblast markers, secrete hyaluronan, lubricin/PRG4 for boundary lubrication). Subintima—loose to dense connective tissue; adipose, areolar, or fibrous types; contains vessels, lymphatics, nerves. Synovial fluid—dialysate of plasma (small molecules) + hyaluronic acid (type B secretion); viscosity 50-200× water; boundary lubrication by lubricin, fluid film lubrication; nourishes avascular cartilage; removes waste. Clinical: synovitis (inflammation in rheumatoid arthritis), osteoarthritis (synovial changes), joint effusion.

Glandular epithelium—classification and structure: Endocrine glands—no ducts; secrete hormones into fenestrated capillaries; structural types: cords/clusters (adrenal cortex, liver), follicles (thyroid), cords with vessels (parathyroid, pancreatic islets); regulated by humoral, neural, hormonal stimuli; major glands: pituitary, thyroid, parathyroid, adrenal, pineal, pancreatic islets, gonads.

Exocrine glands—classification schema: By duct structure—simple (single unbranched duct: simple tubular—intestinal glands, simple branched tubular—stomach glands, simple coiled tubular—sweat glands, simple acinar/alveolar—sebaceous glands, simple branched acinar—sebaceous glands); compound (branched duct: compound tubular—bulbourethral glands, compound acinar/alveolar—mammary glands, compound tubuloacinar—salivary glands). By secretion mechanism—merocrine (eccrine): secretory product released by exocytosis (exocytosis), cell intact (salivary glands, pancreas, sweat glands); apocrine: apical cytoplasm pinches off with secretory product, cell repairs itself (mammary glands, ceruminous glands, some sweat glands—controversial if true apocrine in humans); holocrine: entire cell becomes secretory product, cell ruptures and dies, replaced by stem cells (sebaceous glands).

By secretion type—Serous cells: pyramidal; basal round nucleus; basal rough ER; apical secretory granules (zymogen granules); secrete watery protein-rich fluid with enzymes; serous demilunes (crescents) in mixed glands. Mucous cells: columnar/cuboidal; basal flattened nucleus (pushed down by mucinogen granules); pale-staining cytoplasm; secrete mucins (glycoproteins) that hydrate to form mucus; protective/lubricating. Mixed (seromucous) glands: both cell types (submandibular salivary glands).

Secretory unit structure: Acinus/alveolus—secretory epithelium; myoepithelial cells (contractile, smooth muscle-like, squeeze secretion); basement membrane. Duct system: intercalated duct (short, connects acinus to striated duct, simple cuboidal), striated duct (columnar with basal striations—infoldings with mitochondria for ion transport, modifies secretion), interlobular/excretory duct (stratified/pseudostratified, larger, conveys secretion).

Major exocrine glands: Salivary (parotid—serous only, submandibular—mixed, sublingual—mucous predominantly); pancreas (exocrine—serous acini, endocrine—islets); liver (hepatocytes, bile canaliculi); sweat (eccrine—merocrine, apocrine—modified apocrine); sebaceous (holocrine); mammary (modified apocrine sweat glands).`,
      },
    },
  ],
  anatomyLinks: [
    { structureId: 'epidermis', structureName: 'Epidermis', linkText: 'Epidermis', relevance: 'Epithelial tissue example' },
    { structureId: 'dermis', structureName: 'Dermis', linkText: 'Dermis', relevance: 'Connective tissue example' },
    { structureId: 'bone-tissue', structureName: 'Bone Tissue', linkText: 'Bone Tissue', relevance: 'Supporting connective tissue' },
    { structureId: 'cartilage', structureName: 'Cartilage', linkText: 'Cartilage', relevance: 'Supporting connective tissue' },
    { structureId: 'skeletal-muscle', structureName: 'Skeletal Muscle', linkText: 'Skeletal Muscle', relevance: 'Striated muscle tissue' },
    { structureId: 'cardiac-muscle', structureName: 'Cardiac Muscle', linkText: 'Cardiac Muscle', relevance: 'Striated muscle tissue' },
    { structureId: 'smooth-muscle', structureName: 'Smooth Muscle', linkText: 'Smooth Muscle', relevance: 'Non-striated muscle tissue' },
    { structureId: 'neurons', structureName: 'Neurons', linkText: 'Neurons', relevance: 'Nervous tissue cells' },
    { structureId: 'blood-vessels', structureName: 'Blood Vessels', linkText: 'Blood Vessels', relevance: 'Endothelium lining' },
    { structureId: 'joint-capsule', structureName: 'Joint Capsule', linkText: 'Joint Capsule', relevance: 'Dense irregular connective tissue' },
  ],
  references: [
    {
      referenceId: 'openstax-ap-4',
      type: 'textbook',
      title: 'Anatomy and Physiology - Chapter 4: The Tissue Level of Organization',
      authors: 'Betts JG, Young KA, Wise JA, Johnson E, Poe B, Kruse DH, Korol O, Johnson JE, Womble M, DeSaix P.',
      source: 'OpenStax',
      year: 2021,
      url: 'https://openstax.org/books/anatomy-and-physiology/pages/4-introduction',
      citation: 'Betts JG, et al. Anatomy and Physiology. Chapter 4: The Tissue Level of Organization. OpenStax; 2021.',
    },
  ],
  relatedEntries: [
    { entryId: 'integumentary-system', entryType: 'anatomy', name: 'Integumentary System', relationship: 'see-also', description: 'Contains epithelial and connective tissues' },
    { entryId: 'skeletal-system', entryType: 'anatomy', name: 'Skeletal System', relationship: 'see-also', description: 'Bones are supporting connective tissue' },
    { entryId: 'muscular-system', entryType: 'anatomy', name: 'Muscular System', relationship: 'see-also', description: 'Contains all three muscle types' },
    { entryId: 'nervous-system-anatomy', entryType: 'anatomy', name: 'Nervous System Anatomy', relationship: 'see-also', description: 'Contains nervous tissue' },
    { entryId: 'immune-system', entryType: 'physiology', name: 'Immune System', relationship: 'see-also', description: 'Connective tissue contains immune cells' },
    { entryId: 'cardiovascular-system', entryType: 'anatomy', name: 'Cardiovascular System', relationship: 'see-also', description: 'Blood is fluid connective tissue' },
    { entryId: 'respiratory-system', entryType: 'anatomy', name: 'Respiratory System', relationship: 'see-also', description: 'Lined by respiratory epithelium' },
    { entryId: 'digestive-system', entryType: 'anatomy', name: 'Digestive System', relationship: 'see-also', description: 'Lined by mucous membranes' },
  ],
  searchMetadata: {
    primaryKeywords: ['histology', 'tissue types', 'epithelial tissue', 'connective tissue', 'muscle tissue', 'nervous tissue', 'tissue membrane', 'gland'],
    secondaryKeywords: ['squamous epithelium', 'cuboidal epithelium', 'columnar epithelium', 'stratified epithelium', 'simple epithelium', 'ciliated epithelium', 'keratinized epithelium', 'areolar tissue', 'adipose tissue', 'dense connective tissue', 'cartilage', 'bone tissue', 'blood', 'skeletal muscle', 'cardiac muscle', 'smooth muscle', 'neuron', 'neuroglia', 'synovial membrane', 'serous membrane', 'mucous membrane', 'exocrine gland', 'endocrine gland'],
    tags: ['histology', 'anatomy', 'tissue biology', 'cell biology', 'pathology foundation'],
    synonyms: ['microscopic anatomy', 'tissue biology', 'tissue histology', 'body tissues', 'tissue organization', 'cellular organization'],
    abbreviations: ['ECM', 'CNS', 'PNS', 'CT', 'WAT', 'BAT'],
    meshTerms: ['Tissues', 'Epithelial Cells', 'Connective Tissue', 'Muscle, Skeletal', 'Muscle, Smooth', 'Myocardium', 'Nervous System', 'Neurons', 'Neuroglia', 'Membranes', 'Glands'],
  },
  clinicalImportance: 'essential',
  version: '1.0.0',
  lastUpdated: '2026-02-02',
  author: 'SOMA Medical Education',
  reviewStatus: 'approved',
};

// Export all entries
export const tissueTypesEntries: EncyclopediaEntry[] = [
  tissueTypesEntry,
];
