/**
 * Exercise Benefits for Mental Health - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const exerciseBenefitsContent: EducationalContent = {
  id: 'mental-health-exercise-benefits',
  type: 'topic',
  name: 'Exercise Benefits for Mental Health',
  alternateNames: ['Physical Activity and Mental Health', 'Exercise for Depression'],

  levels: {
    1: { level: 1, summary: 'Regular exercise is one of the most effective things you can do for your mental health. It reduces depression and anxiety, improves mood, and boosts overall well-being.', explanation: '**Exercise and Mental Health**\n\nExercise is not just good for your body - it is powerful medicine for your mind.\n\n**Benefits:**\n- Reduces symptoms of depression\n- Decreases anxiety\n- Improves mood\n- Increases energy\n- Helps with sleep\n- Boosts self-esteem\n- Reduces stress\n\n**How Much Exercise?**\n- 150 minutes of moderate activity per week (30 min, 5 days)\n- Or 75 minutes of vigorous activity\n- Any amount helps - start where you are\n\n**Types of Exercise:**\n- Walking, jogging, running\n- Swimming, cycling\n- Dancing, sports\n- Strength training\n- Yoga, tai chi\n\n**Tips for Getting Started:**\n- Start small (even 10 minutes helps)\n- Choose activities you enjoy\n- Exercise with others for motivation\n- Build into your routine\n- Be patient - benefits build over time\n\nThe best exercise is the one you will actually do consistently.', keyTerms: [{ term: 'aerobic exercise', definition: 'Activity that increases heart rate and breathing' }], analogies: ['Exercise is like a natural antidepressant with no prescription needed.'], examples: ['A 30-minute walk most days has been shown to be as effective as antidepressant medication for mild-moderate depression.'] },
    2: { level: 2, summary: 'Exercise has antidepressant and anxiolytic effects comparable to medication for mild-moderate symptoms. Mechanisms include endorphins, neuroplasticity, and stress system regulation. Both aerobic and resistance training are effective.', explanation: '**Evidence for Exercise:**\n\n*Depression:*\n- Meta-analyses show medium-large effect size\n- Comparable to medication for mild-moderate\n- Augments medication effects\n- Prevents recurrence\n\n*Anxiety:*\n- Reduces symptoms across anxiety disorders\n- Acute and chronic benefits\n\n**Mechanisms:**\n- Endorphin release\n- BDNF increase\n- Monoamine effects (serotonin, dopamine)\n- HPA axis regulation\n- Reduced inflammation\n- Self-efficacy improvement\n\n**Exercise Prescription:**\n\n*Type:*\n- Aerobic (most studied)\n- Resistance training (also effective)\n- Yoga (anxiety, stress)\n\n*Dose:*\n- 150 min/week moderate or 75 min vigorous\n- 3-5 sessions per week\n- Benefits seen with less\n\n*Intensity:*\n- Moderate intensity effective\n- Some evidence higher intensity may be better for depression\n\n**Barriers and Solutions:**\n- Low motivation: Start very small, habit stacking\n- Physical limitations: Adapt activity\n- Time: Break into shorter bouts\n- Environment: Find enjoyable activities', keyTerms: [{ term: 'BDNF', definition: 'Brain-derived neurotrophic factor, increased by exercise' }, { term: 'anxiolytic', definition: 'Anxiety-reducing' }], analogies: [] },
    3: { level: 3, summary: 'Exercise effects on mental health involve neuroplasticity (BDNF, neurogenesis), monoamine regulation, HPA axis effects, and anti-inflammatory mechanisms. Prescription should specify type, frequency, intensity, and duration.', explanation: '**Neurobiological Mechanisms:**\n\n*Neuroplasticity:*\n- BDNF upregulation\n- Hippocampal neurogenesis\n- Synaptic plasticity\n- Similar to antidepressant effects\n\n*Neurotransmitters:*\n- Serotonin enhancement\n- Dopamine release\n- Norepinephrine effects\n- Endorphin/endocannabinoid release\n\n*Stress Systems:*\n- HPA axis regulation\n- Cortisol normalization\n- Autonomic balance\n\n*Inflammation:*\n- Anti-inflammatory effects\n- IL-6 acute increase, chronic reduction\n- May address inflammatory depression subtype\n\n**Clinical Application:**\n\n*Assessment:*\n- Current activity level\n- Physical limitations\n- Preferences\n- Barriers\n\n*Prescription Elements:*\n- Type: Aerobic, resistance, combined\n- Frequency: 3-5x/week\n- Intensity: Moderate to vigorous\n- Duration: 30-45 min sessions\n- Progression: Gradual increase\n\n*Integration with Treatment:*\n- Adjunct to therapy and medication\n- May be first-line for mild symptoms\n- Relapse prevention\n- Part of comprehensive care', keyTerms: [{ term: 'neurogenesis', definition: 'Formation of new neurons, occurs in hippocampus with exercise' }, { term: 'endocannabinoid', definition: 'Internal cannabis-like compounds increased by exercise' }], clinicalNotes: 'Exercise is underutilized intervention. Prescribe with specificity. Address barriers. Effective as adjunct or monotherapy for mild-moderate symptoms. Consider exercise physiology referral for complex patients.' },
    4: { level: 4, summary: 'Exercise prescription for mental health requires attention to dose-response, individual factors, and adherence. Mechanisms involve multiple pathways including neuroplasticity, inflammation, and psychological factors. Integration into psychiatric care remains suboptimal.', explanation: '**Dose-Response:**\n\n*Depression:*\n- Some evidence for dose-response\n- Higher volume may have greater effect\n- Intensity may matter (vigorous > moderate for some)\n- Even low doses have benefit\n\n*Individual Factors:*\n- Age considerations\n- Comorbid medical conditions\n- Medication effects\n- Baseline fitness\n\n**Implementation:**\n\n*Behavioral Strategies:*\n- Motivational interviewing\n- Goal setting\n- Self-monitoring\n- Social support\n- Habit formation\n\n*Program Design:*\n- Supervised initially may increase adherence\n- Progression planning\n- Enjoyment focus\n- Flexibility\n\n**Special Populations:**\n\n*Severe Mental Illness:*\n- Physical health disparities\n- Medication effects on motivation\n- Adapted programs\n- Strong evidence for benefit\n\n*Older Adults:*\n- Cognitive benefits\n- Social benefits\n- Fall prevention\n- Adapted intensity\n\n**Research Gaps:**\n- Optimal dose\n- Long-term maintenance\n- Combination with other treatments\n- Individual matching', keyTerms: [{ term: 'dose-response', definition: 'Relationship between amount of exercise and mental health benefit' }, { term: 'motivational interviewing', definition: 'Counseling approach to enhance motivation for change' }], clinicalNotes: 'Prescribe exercise like a medication with specific parameters. Address motivational barriers. Supervised programs may improve adherence. Integrate into treatment planning. Monitor and adjust.' },
    5: { level: 5, summary: 'Contemporary exercise-mental health research explores precision approaches, mechanistic pathways, and implementation strategies. Digital tools and telehealth expand reach. Exercise as medicine requires system-level integration.', explanation: '**Precision Approaches:**\n\n*Individual Matching:*\n- Exercise preferences\n- Response prediction\n- Optimal type/dose\n- Biomarker-guided\n\n*Mechanisms Research:*\n- Inflammatory subtypes\n- BDNF response\n- Gut-brain axis\n- Genetic factors\n\n**Technology:**\n- Wearables for monitoring\n- Apps for adherence\n- Telehealth exercise programs\n- Gamification\n\n**Implementation:**\n\n*Healthcare Integration:*\n- Exercise as vital sign\n- Referral pathways\n- Reimbursement models\n- Training clinicians\n\n*Community:*\n- Programs in mental health settings\n- Community partnerships\n- Accessibility\n\n**Emerging Questions:**\n- Acute vs chronic effects\n- Timing relative to other treatments\n- High-intensity interval training\n- Mind-body practices mechanisms', keyTerms: [{ term: 'exercise vital sign', definition: 'Assessing physical activity as routine part of clinical care' }, { term: 'HIIT', definition: 'High-intensity interval training' }], clinicalNotes: 'Exercise prescription remains underutilized. System-level changes needed for integration. Technology can support adherence. Precision approaches emerging. Evidence strong for recommending to all psychiatric patients.' },
  },

  media: [],
  citations: [{ id: 'exercise-depression', type: 'article', title: 'Exercise for Depression', authors: ['Schuch FB', 'et al'], source: 'Journal of Psychiatric Research' }],
  crossReferences: [{ targetId: 'mental-health-depression', targetType: 'condition', relationship: 'see-also', label: 'Depression' }],
  tags: { systems: ['nervous', 'musculoskeletal'], topics: ['mental-health', 'wellness'], keywords: ['exercise', 'physical activity', 'depression', 'anxiety'], clinicalRelevance: 'high', examRelevance: { usmle: false, nbme: false, shelf: [] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default exerciseBenefitsContent;
