/**
 * Mindfulness Meditation - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const mindfulnessMeditationContent: EducationalContent = {
  id: 'mental-health-mindfulness-meditation',
  type: 'topic',
  name: 'Mindfulness Meditation',
  alternateNames: ['Mindfulness', 'Meditation', 'MBSR', 'MBCT'],

  levels: {
    1: { level: 1, summary: 'Mindfulness means paying attention to the present moment without judgment. Regular practice can reduce stress, anxiety, and depression while improving overall well-being.', explanation: '**What Is Mindfulness?**\n\nMindfulness is paying attention to the present moment - your thoughts, feelings, and sensations - without judging them as good or bad.\n\n**Benefits:**\n- Reduces stress and anxiety\n- Helps with depression\n- Improves focus\n- Better emotional regulation\n- Greater sense of calm\n- Better sleep\n\n**How to Practice:**\n\n*Simple Breathing Meditation:*\n1. Sit comfortably\n2. Close your eyes\n3. Focus on your breath\n4. When your mind wanders (it will), gently return to breath\n5. Start with 5 minutes, build up\n\n*Throughout Your Day:*\n- Eat one meal mindfully\n- Take mindful walks\n- Notice when you are on autopilot\n- Pause and take three deep breaths\n\n**Getting Started:**\n- Apps: Headspace, Calm, Insight Timer\n- Classes in your community\n- Online programs\n- Books and videos\n\nRemember: Mindfulness is a skill that improves with practice. Be patient with yourself.', keyTerms: [{ term: 'mindfulness', definition: 'Paying attention to the present moment without judgment' }, { term: 'meditation', definition: 'Practice of training attention and awareness' }], analogies: ['Mindfulness is like training a puppy - when your mind wanders, gently bring it back.'], examples: [] },
    2: { level: 2, summary: 'Mindfulness-based interventions (MBSR, MBCT) have strong evidence for stress, anxiety, depression relapse prevention, and chronic pain. Practice involves formal meditation and informal present-moment awareness.', explanation: '**Evidence-Based Programs:**\n\n*MBSR (Mindfulness-Based Stress Reduction):*\n- 8-week program\n- Developed by Jon Kabat-Zinn\n- Weekly classes + home practice\n- Evidence for stress, anxiety, chronic pain\n\n*MBCT (Mindfulness-Based Cognitive Therapy):*\n- Combines mindfulness with cognitive therapy\n- Designed for depression relapse prevention\n- 8-week program\n- Strong evidence for recurrent depression\n\n**Core Practices:**\n\n*Formal:*\n- Body scan\n- Sitting meditation\n- Mindful movement (yoga, walking)\n- Loving-kindness meditation\n\n*Informal:*\n- Mindful eating\n- Mindful daily activities\n- Pausing throughout the day\n\n**Mechanisms:**\n- Decentering (observing thoughts)\n- Reduced rumination\n- Improved emotion regulation\n- Present-moment focus\n- Acceptance\n\n**Research Findings:**\n- Reduces anxiety symptoms\n- Prevents depression relapse (comparable to medication)\n- Helps chronic pain\n- Improves well-being\n- Changes brain structure and function', keyTerms: [{ term: 'MBSR', definition: 'Mindfulness-Based Stress Reduction - foundational 8-week program' }, { term: 'MBCT', definition: 'Mindfulness-Based Cognitive Therapy - for depression relapse prevention' }, { term: 'decentering', definition: 'Ability to observe thoughts as mental events rather than facts' }], analogies: [] },
    3: { level: 3, summary: 'MBSR and MBCT are manualized interventions with structured curricula. Mechanisms include attention regulation, body awareness, emotion regulation, and change in self-perspective. Neural correlates include prefrontal and insula changes.', explanation: '**Program Structure:**\n\n*MBSR:*\n- 8 weekly 2.5-hour sessions\n- Day-long retreat\n- Daily home practice (45 min)\n- Body scan, sitting, yoga, walking meditation\n\n*MBCT:*\n- Similar structure to MBSR\n- Cognitive therapy elements added\n- Focus on depression patterns\n- "Thoughts are not facts"\n\n**Mechanisms:**\n\n*Attention Regulation:*\n- Improved sustained attention\n- Reduced mind-wandering\n- Executive function enhancement\n\n*Body Awareness:*\n- Interoceptive awareness\n- Early detection of emotional states\n- Insula activation\n\n*Emotion Regulation:*\n- Decreased reactivity\n- Increased tolerance of difficult emotions\n- Amygdala changes\n\n*Self-Perspective:*\n- Decentering from thoughts\n- Reduced self-referential processing\n- Default mode network changes\n\n**Neural Correlates:**\n- Prefrontal cortex: Increased activation\n- Amygdala: Decreased reactivity\n- Insula: Enhanced interoception\n- Default mode network: Altered connectivity\n\n**Clinical Applications:**\n- Anxiety disorders\n- Depression (especially relapse prevention)\n- Chronic pain\n- Stress-related conditions\n- Adjunct to other treatments', keyTerms: [{ term: 'interoception', definition: 'Awareness of internal body states' }, { term: 'default mode network', definition: 'Brain network active during mind-wandering, altered by meditation' }, { term: 'rumination', definition: 'Repetitive negative thinking, reduced by mindfulness' }], clinicalNotes: 'MBCT has strongest evidence for depression relapse prevention. MBSR for stress and pain. Ensure qualified teacher for programs. Can be adjunct to other treatments. Not appropriate during acute crisis for some.' },
    4: { level: 4, summary: 'Mindfulness mechanisms involve attention, interoception, emotion regulation, and self-referential processing. Brain changes include prefrontal, insula, and amygdala effects. Research addresses optimal dosing, active ingredients, and personalization.', explanation: '**Detailed Mechanisms:**\n\n*Attention Networks:*\n- Executive attention improvement\n- Alerting network changes\n- Orienting effects\n- Conflict monitoring\n\n*Interoception:*\n- Insula activation\n- Body awareness\n- Emotional awareness\n- Altered pain processing\n\n*Self-Referential Processing:*\n- Reduced DMN activity during meditation\n- Decentering capacity\n- Changed narrative self\n\n**Research Questions:**\n\n*Dose:*\n- How much practice needed?\n- Brief vs intensive programs\n- Maintenance practice\n\n*Active Ingredients:*\n- Which components essential?\n- Dismantling studies\n- Attention vs acceptance\n\n*Individual Differences:*\n- Who benefits most?\n- Personality factors\n- Baseline characteristics\n\n**Clinical Integration:**\n- Third-wave CBT context\n- Part of treatment packages\n- Skill that generalizes\n- Ongoing practice needed\n\n**Cautions:**\n- Not for everyone\n- Can increase distress initially\n- Trauma-sensitive adaptations needed\n- Qualified instruction important', keyTerms: [{ term: 'dismantling study', definition: 'Research separating intervention components to identify active ingredients' }, { term: 'third-wave CBT', definition: 'CBT approaches incorporating mindfulness and acceptance' }], clinicalNotes: 'Mindfulness is not a panacea. Consider trauma history. Brief interventions may have limited effects. Ongoing practice needed for maintenance. Quality of instruction matters. Integration with other treatments.' },
    5: { level: 5, summary: 'Contemporary mindfulness research explores mechanisms, optimal delivery, digital platforms, and integration with other treatments. Precision approaches aim to match interventions to individuals. Implementation science addresses scaling evidence-based programs.', explanation: '**Research Frontiers:**\n\n*Mechanism Studies:*\n- Real-time neural correlates\n- Micro-phenomenology\n- Computational modeling\n- Biomarkers of response\n\n*Precision Approaches:*\n- Who benefits from which practice?\n- Personalized recommendations\n- Adaptive interventions\n\n**Technology:**\n\n*Digital Mindfulness:*\n- Apps (Headspace, Calm, etc.)\n- Online MBSR/MBCT\n- VR meditation\n- Biofeedback integration\n\n*Research Questions:*\n- Digital vs in-person equivalence\n- Optimal app features\n- Engagement and adherence\n\n**Integration:**\n\n*With Other Treatments:*\n- Mindfulness + medication\n- Mindfulness in psychotherapy\n- Trauma-sensitive mindfulness\n\n*Healthcare Settings:*\n- Primary care integration\n- Psychiatry integration\n- Chronic disease management\n\n**Implementation:**\n- Teacher training standards\n- Quality assurance\n- Access and equity\n- Scaling evidence-based programs\n\n**Emerging Areas:**\n- Psychedelic-assisted mindfulness\n- Compassion-based practices\n- Interoceptive training\n- Network neuroscience approaches', keyTerms: [{ term: 'micro-phenomenology', definition: 'Detailed first-person investigation of conscious experience' }, { term: 'trauma-sensitive mindfulness', definition: 'Adaptations for practicing safely with trauma history' }], clinicalNotes: 'Digital apps can expand access but may not equal intensive programs. Quality matters - look for evidence-based programs. Trauma-informed approaches important. Integration with other treatments promising. Ongoing research refining understanding.' },
  },

  media: [],
  citations: [{ id: 'mbct-evidence', type: 'article', title: 'MBCT for Depression Relapse Prevention', authors: ['Segal ZV', 'Williams JMG', 'Teasdale JD'], source: 'Various publications' }],
  crossReferences: [{ targetId: 'mental-health-stress-management', targetType: 'topic', relationship: 'related', label: 'Stress Management' }],
  tags: { systems: ['nervous'], topics: ['mental-health', 'wellness'], keywords: ['mindfulness', 'meditation', 'MBSR', 'MBCT'], clinicalRelevance: 'high', examRelevance: { usmle: false, nbme: false, shelf: [] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default mindfulnessMeditationContent;
