/**
 * Sleep and Mental Health - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const sleepMentalHealthContent: EducationalContent = {
  id: 'mental-health-sleep-mental-health',
  type: 'topic',
  name: 'Sleep and Mental Health',
  alternateNames: ['Sleep Hygiene', 'Sleep and Mood', 'Insomnia'],

  levels: {
    1: { level: 1, summary: 'Sleep and mental health are deeply connected. Poor sleep can worsen depression and anxiety, while mental health conditions often disrupt sleep. Good sleep habits can significantly improve mental health.', explanation: '**Sleep and Mental Health Connection**\n\nSleep and mental health affect each other:\n- Poor sleep can worsen depression and anxiety\n- Depression and anxiety can cause sleep problems\n- Improving sleep can improve mental health\n\n**How Much Sleep Do You Need?**\n- Adults: 7-9 hours\n- Teens: 8-10 hours\n- Quality matters as much as quantity\n\n**Signs of Sleep Problems:**\n- Trouble falling asleep\n- Waking up during the night\n- Waking up too early\n- Feeling tired despite sleeping\n- Daytime sleepiness\n\n**Sleep Hygiene Tips:**\n- Keep a regular sleep schedule\n- Make your bedroom dark, quiet, and cool\n- Avoid screens before bed\n- Limit caffeine, especially afternoon/evening\n- Avoid alcohol close to bedtime\n- Get regular exercise (but not too close to bedtime)\n- Use bed only for sleep and intimacy\n- If you cannot sleep, get up and do something relaxing\n\n**When to Get Help:**\nIf sleep problems persist or significantly affect your life, talk to your doctor.', keyTerms: [{ term: 'sleep hygiene', definition: 'Habits and practices that promote good sleep' }, { term: 'insomnia', definition: 'Difficulty falling or staying asleep' }], analogies: ['Sleep is like charging your phone - you need enough charge to function well.'], examples: [] },
    2: { level: 2, summary: 'Sleep disturbances are common in psychiatric disorders and bidirectionally related to mental health. CBT-I is first-line treatment for insomnia. Sleep architecture changes occur in depression. Improving sleep often improves psychiatric symptoms.', explanation: '**Bidirectional Relationship:**\n\n*Sleep → Mental Health:*\n- Sleep deprivation worsens mood\n- Increases anxiety\n- Impairs cognitive function\n- Risk factor for depression\n\n*Mental Health → Sleep:*\n- Depression: Early morning awakening, hypersomnia\n- Anxiety: Difficulty falling asleep\n- PTSD: Nightmares\n- Bipolar: Reduced sleep need in mania\n\n**Sleep in Psychiatric Disorders:**\n\n*Depression:*\n- Insomnia or hypersomnia\n- Reduced REM latency\n- Sleep fragmentation\n\n*Anxiety:*\n- Initial insomnia\n- Hyperarousal\n\n*PTSD:*\n- Nightmares\n- Sleep avoidance\n\n**Treatment:**\n\n*CBT-I (Cognitive Behavioral Therapy for Insomnia):*\n- First-line treatment\n- Sleep restriction\n- Stimulus control\n- Cognitive restructuring\n- Relaxation\n- 6-8 sessions typically\n\n*Medications:*\n- Short-term use when needed\n- Options: Trazodone, melatonin, others\n- Avoid benzodiazepines long-term\n\n**Sleep Hygiene Education:**\n- Consistent schedule\n- Bedroom environment\n- Pre-sleep routine\n- Avoid stimulants\n- Manage light exposure', keyTerms: [{ term: 'CBT-I', definition: 'Cognitive Behavioral Therapy for Insomnia - evidence-based treatment' }, { term: 'sleep restriction', definition: 'Limiting time in bed to increase sleep efficiency' }, { term: 'REM latency', definition: 'Time to first REM sleep, shortened in depression' }], analogies: [] },
    3: { level: 3, summary: 'Sleep disorders and psychiatric conditions share neurobiological substrates. CBT-I shows efficacy equal to medications with more durable effects. Sleep disturbance is increasingly recognized as transdiagnostic treatment target.', explanation: '**Neurobiology:**\n\n*Sleep Regulation:*\n- Circadian system (SCN, melatonin)\n- Homeostatic drive (adenosine)\n- Arousal systems (NE, 5-HT, DA, histamine, orexin)\n\n*Shared Mechanisms with Psychiatry:*\n- Monoamine systems\n- HPA axis\n- Inflammation\n- Circadian genes\n\n**CBT-I Components:**\n\n*Sleep Restriction:*\n- Calculate sleep efficiency\n- Restrict TIB to match actual sleep\n- Gradually increase as efficiency improves\n\n*Stimulus Control:*\n- Bed for sleep only\n- Leave bed if not sleeping\n- Consistent wake time\n\n*Cognitive:*\n- Address catastrophic thoughts about sleep\n- Realistic expectations\n\n*Relaxation:*\n- PMR, breathing exercises\n- Reducing arousal\n\n**Medications:**\n\n*Options:*\n- Trazodone (sedating antidepressant)\n- Mirtazapine (if depression comorbid)\n- Melatonin/ramelteon (circadian)\n- Doxepin low-dose\n- Z-drugs short-term (zolpidem, eszopiclone)\n- Orexin antagonists (suvorexant, lemborexant)\n\n*Avoid:*\n- Benzodiazepines long-term\n- Antihistamines (tolerance)\n\n**Transdiagnostic Target:**\n- Sleep as treatment target across disorders\n- Improving sleep improves psychiatric symptoms\n- Sleep intervention as prevention', keyTerms: [{ term: 'sleep efficiency', definition: 'Ratio of time asleep to time in bed' }, { term: 'orexin', definition: 'Neuropeptide regulating wakefulness, target of new sleep medications' }, { term: 'transdiagnostic', definition: 'Addressing factor common across multiple disorders' }], clinicalNotes: 'CBT-I is first-line for chronic insomnia. Sleep restriction is most potent component. Avoid benzodiazepines long-term. Address sleep as transdiagnostic target. Screen for sleep apnea if indicated.' },
    4: { level: 4, summary: 'Sleep neurobiology involves complex circadian and homeostatic regulation. Sleep deprivation affects emotional regulation circuits. CBT-I mechanisms include extinction learning and homeostatic pressure. Chronotherapy emerging for mood disorders.', explanation: '**Advanced Neurobiology:**\n\n*Two-Process Model:*\n- Process S (homeostatic): Adenosine accumulation\n- Process C (circadian): SCN rhythm\n\n*Emotional Regulation:*\n- Sleep deprivation increases amygdala reactivity\n- Decreases prefrontal regulation\n- Impairs emotion processing\n\n**CBT-I Mechanisms:**\n\n*Sleep Restriction:*\n- Builds homeostatic pressure\n- Consolidates sleep\n- Resets expectations\n\n*Stimulus Control:*\n- Extinction of arousal to bed/bedroom\n- Re-association with sleep\n\n**Chronotherapy:**\n\n*For Depression:*\n- Wake therapy (sleep deprivation)\n- Light therapy\n- Sleep phase advance\n- Triple chronotherapy\n\n*For Bipolar:*\n- Dark therapy for mania\n- Rhythm stabilization\n- IPSRT principles\n\n**Special Populations:**\n\n*PTSD:*\n- Prazosin for nightmares\n- Imagery rehearsal therapy\n- CBT-I adapted\n\n*Schizophrenia:*\n- Circadian disruption common\n- CBT-I can be adapted\n- Medication effects on sleep', keyTerms: [{ term: 'chronotherapy', definition: 'Using timing of light, sleep, activity to treat mood disorders' }, { term: 'wake therapy', definition: 'Therapeutic sleep deprivation for depression' }, { term: 'imagery rehearsal', definition: 'Treatment for nightmares involving rewriting dream content' }], clinicalNotes: 'Chronotherapy has rapid effects in depression. Consider circadian factors in treatment planning. PTSD nightmares respond to prazosin and imagery rehearsal. Address medication effects on sleep.' },
    5: { level: 5, summary: 'Contemporary sleep research explores digital CBT-I, circadian interventions, and biomarker-guided treatment. Sleep is recognized as modifiable risk factor for mental illness. Precision approaches match intervention to sleep phenotype.', explanation: '**Digital Interventions:**\n\n*Digital CBT-I:*\n- Apps and online programs\n- Comparable efficacy to in-person\n- Scalable\n- Examples: Sleepio, CBT-I Coach\n\n**Precision Sleep Medicine:**\n\n*Sleep Phenotyping:*\n- Insomnia subtypes\n- Circadian preferences\n- Matching treatment to phenotype\n\n*Biomarkers:*\n- Actigraphy\n- Sleep EEG markers\n- Genetic factors\n\n**Prevention:**\n\n*Sleep as Prevention Target:*\n- Sleep problems precede depression\n- Intervention may prevent episodes\n- Youth focus\n\n**Emerging Treatments:**\n\n*Orexin Antagonists:*\n- Suvorexant, lemborexant\n- Different mechanism than traditional hypnotics\n- May have psychiatric applications\n\n*Circadian Interventions:*\n- Light therapy timing optimization\n- Melatonin timing\n- Chronotherapy protocols\n\n**Implementation:**\n- Training in CBT-I\n- Digital tools to expand access\n- Integration with psychiatric care\n- Stepped care models', keyTerms: [{ term: 'digital CBT-I', definition: 'App or online-delivered CBT for insomnia' }, { term: 'sleep phenotype', definition: 'Individual pattern of sleep characteristics' }, { term: 'stepped care', definition: 'Starting with less intensive treatment, stepping up as needed' }], clinicalNotes: 'Digital CBT-I effective and scalable. Sleep as prevention target emerging. Precision approaches matching treatment to phenotype. Address sleep as core component of psychiatric care.' },
  },

  media: [],
  citations: [{ id: 'cbti-evidence', type: 'article', title: 'CBT-I as First-Line Treatment for Insomnia', authors: ['Various'], source: 'AASM Guidelines' }],
  crossReferences: [{ targetId: 'mental-health-depression', targetType: 'condition', relationship: 'related', label: 'Depression' }],
  tags: { systems: ['nervous'], topics: ['mental-health', 'wellness', 'sleep'], keywords: ['sleep', 'insomnia', 'CBT-I', 'sleep hygiene'], clinicalRelevance: 'high', examRelevance: { usmle: true, nbme: true, shelf: ['psychiatry'] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default sleepMentalHealthContent;
