/**
 * Social Connection - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const socialConnectionContent: EducationalContent = {
  id: 'mental-health-social-connection',
  type: 'topic',
  name: 'Social Connection',
  alternateNames: ['Social Support', 'Relationships and Mental Health', 'Loneliness'],

  levels: {
    1: { level: 1, summary: 'Human connection is essential for mental health. Strong relationships protect against depression and anxiety, while loneliness is a significant risk factor for mental and physical health problems.', explanation: '**Why Connection Matters**\n\nHumans are social beings. Strong connections with others:\n- Reduce stress\n- Protect against depression and anxiety\n- Improve physical health\n- Increase sense of purpose\n- Help us cope with challenges\n\n**Effects of Loneliness:**\n- Increased depression and anxiety\n- Higher stress levels\n- Worse physical health\n- Cognitive decline\n\n**Building Connection:**\n\n*Strengthen Existing Relationships:*\n- Reach out to friends and family\n- Be present when with others\n- Express appreciation\n- Be willing to be vulnerable\n\n*Make New Connections:*\n- Join groups based on interests\n- Volunteer\n- Take classes\n- Be open to conversation\n\n*Quality Over Quantity:*\n- A few close relationships more valuable than many acquaintances\n- Depth matters\n\n**If You Are Struggling:**\n- It is okay to start small\n- Online communities can help\n- Therapy can address social anxiety\n- Support groups connect you with others who understand\n\nConnection is a skill that can be built and strengthened.', keyTerms: [{ term: 'social support', definition: 'Emotional and practical help from relationships' }, { term: 'loneliness', definition: 'Subjective feeling of being alone or disconnected' }], analogies: ['Social connection is like a vitamin for mental health - we need regular doses to thrive.'], examples: [] },
    2: { level: 2, summary: 'Social support buffers stress and protects mental health through multiple mechanisms. Loneliness is associated with depression, anxiety, and physical health problems. Interventions include addressing maladaptive cognitions, enhancing social skills, and increasing opportunity for connection.', explanation: '**Social Support and Mental Health:**\n\n*Protective Effects:*\n- Buffers against stress\n- Reduces depression and anxiety\n- Aids recovery from mental illness\n- Prevents relapse\n\n*Types of Support:*\n- Emotional: Empathy, caring, love\n- Instrumental: Practical help\n- Informational: Advice, guidance\n- Companionship: Shared activities\n\n**Loneliness:**\n\n*Distinguished From Social Isolation:*\n- Loneliness: Subjective distress about connection\n- Social isolation: Objective lack of contacts\n- Both matter for health\n\n*Health Effects:*\n- Depression and anxiety\n- Increased inflammation\n- Cardiovascular effects\n- Cognitive decline\n- Mortality risk comparable to smoking\n\n**Intervention Approaches:**\n\n*Addressing Cognitions:*\n- Maladaptive social cognitions\n- Negative expectations\n- Hypervigilance to rejection\n\n*Social Skills:*\n- Communication training\n- Assertiveness\n- Conversation skills\n\n*Increasing Opportunity:*\n- Group activities\n- Community involvement\n- Support groups\n\n*Technology:*\n- Can supplement connection\n- Not full replacement\n- Quality matters', keyTerms: [{ term: 'stress buffering', definition: 'Protective effect of social support against stress' }, { term: 'social isolation', definition: 'Objective lack of social contacts' }, { term: 'maladaptive social cognition', definition: 'Unhelpful thinking patterns about social situations' }], analogies: [] },
    3: { level: 3, summary: 'Social connection operates through psychological and biological mechanisms including stress buffering, behavioral regulation, and oxytocin. Loneliness involves specific neural patterns. Interventions target cognitive, behavioral, and opportunity-related factors.', explanation: '**Mechanisms:**\n\n*Psychological:*\n- Stress buffering\n- Sense of belonging\n- Self-esteem support\n- Coping resources\n- Behavioral regulation\n\n*Biological:*\n- Oxytocin effects\n- HPA axis regulation\n- Immune function\n- Inflammation reduction\n- Cardiovascular protection\n\n**Neuroscience of Loneliness:**\n\n*Neural Correlates:*\n- Hypervigilance to social threat\n- Altered reward processing\n- Default mode network changes\n- Social pain overlaps with physical pain\n\n**Clinical Implications:**\n\n*Assessment:*\n- UCLA Loneliness Scale\n- Social network assessment\n- Quality vs quantity\n- Barriers to connection\n\n*Treatment:*\n- Address in psychotherapy\n- Social skills training\n- Cognitive restructuring (social cognitions)\n- Behavioral experiments\n- Group therapy\n- Support groups\n\n**Special Populations:**\n\n*Older Adults:*\n- Higher loneliness prevalence\n- Physical barriers\n- Loss of social network\n- Technology barriers\n\n*Severe Mental Illness:*\n- Social network erosion\n- Skills deficits\n- Stigma barriers\n- Supported socialization', keyTerms: [{ term: 'oxytocin', definition: 'Hormone involved in social bonding and trust' }, { term: 'social pain', definition: 'Distress from social rejection or exclusion, shares neural pathways with physical pain' }], clinicalNotes: 'Assess social connection in all patients. Address cognitions about relationships. Consider group therapy for social skill building. Loneliness is modifiable. Technology can supplement but not replace in-person connection.' },
    4: { level: 4, summary: 'Social connection involves complex neurobiological systems including oxytocin, opioid, and dopamine pathways. Loneliness produces chronic stress physiology. Meta-analyses show cognitive interventions most effective. Social prescribing emerging as healthcare approach.', explanation: '**Neurobiology:**\n\n*Social Reward:*\n- Dopamine system activation\n- Opioid system involvement\n- Similar to other rewards\n\n*Oxytocin System:*\n- Released during positive social interaction\n- Trust and bonding\n- Stress buffering\n- Modulates threat response\n\n*Social Pain:*\n- Anterior cingulate cortex\n- Anterior insula\n- Overlaps with physical pain\n- Acetaminophen studies\n\n**Loneliness Pathophysiology:**\n\n*Chronic Stress:*\n- HPA axis activation\n- Elevated cortisol\n- Inflammation (IL-6, CRP)\n- Immunosuppression\n\n*Hypervigilance:*\n- Increased threat detection\n- Sleep disruption\n- Self-protective behaviors that worsen isolation\n\n**Intervention Evidence:**\n\n*Meta-Analysis Findings:*\n- Cognitive interventions most effective\n- Addressing maladaptive cognitions\n- Social skills training modest effect\n- Increasing opportunities alone less effective\n\n**Social Prescribing:**\n- Healthcare referral to community activities\n- Link workers\n- Non-medical interventions\n- Growing evidence base\n- UK and global models', keyTerms: [{ term: 'social prescribing', definition: 'Healthcare referral to community-based activities for health benefit' }, { term: 'link worker', definition: 'Person who connects patients to community resources' }, { term: 'anterior cingulate', definition: 'Brain region involved in social pain processing' }], clinicalNotes: 'Cognitive interventions most effective for loneliness. Addressing maladaptive social cognitions key. Social prescribing expanding. Consider biological mechanisms. Group interventions can be efficient.' },
    5: { level: 5, summary: 'Contemporary research explores loneliness as public health crisis, neurobiological mechanisms, digital connections, and social prescribing implementation. Precision approaches match intervention to individual profile. Policy implications emerging.', explanation: '**Public Health Perspective:**\n\n*Loneliness Epidemic:*\n- Prevalence increasing\n- Health system impact\n- Economic costs\n- Policy attention\n\n*Policy Responses:*\n- Government initiatives (UK loneliness minister)\n- Healthcare integration\n- Community investment\n- Awareness campaigns\n\n**Research Directions:**\n\n*Mechanisms:*\n- Neural circuitry\n- Inflammatory pathways\n- Genetic factors\n- Developmental aspects\n\n*Interventions:*\n- Digital approaches\n- Social prescribing effectiveness\n- Scalable interventions\n- Prevention\n\n**Technology:**\n\n*Digital Connection:*\n- Video contact\n- Social media effects (mixed)\n- Virtual communities\n- Telehealth for isolated\n\n*Questions:*\n- Can digital replace in-person?\n- Quality of digital connection\n- Optimal use of technology\n\n**Implementation:**\n\n*Healthcare Integration:*\n- Screening for loneliness\n- Social prescribing systems\n- Training clinicians\n- Community partnerships\n\n*Scaling:*\n- Group-based interventions\n- Peer support models\n- Community development\n- Cross-sector collaboration', keyTerms: [{ term: 'loneliness epidemic', definition: 'Framing of widespread loneliness as public health crisis' }, { term: 'social determinants', definition: 'Social factors affecting health outcomes' }], clinicalNotes: 'Loneliness recognized as public health issue. Social prescribing models expanding. Digital can supplement but not replace in-person. Policy-level changes needed. Healthcare has role in addressing social connection.' },
  },

  media: [],
  citations: [{ id: 'loneliness-health', type: 'article', title: 'Loneliness and Social Isolation as Risk Factors', authors: ['Holt-Lunstad J'], source: 'Various publications' }],
  crossReferences: [{ targetId: 'mental-health-depression', targetType: 'condition', relationship: 'related', label: 'Depression' }],
  tags: { systems: ['nervous'], topics: ['mental-health', 'wellness'], keywords: ['social connection', 'loneliness', 'relationships', 'social support'], clinicalRelevance: 'high', examRelevance: { usmle: false, nbme: false, shelf: [] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default socialConnectionContent;
