/**
 * Work-Life Balance - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const workLifeBalanceContent: EducationalContent = {
  id: 'mental-health-work-life-balance',
  type: 'topic',
  name: 'Work-Life Balance',
  alternateNames: ['Work Stress', 'Burnout', 'Occupational Mental Health'],

  levels: {
    1: { level: 1, summary: 'Work-life balance is essential for mental health. Chronic work stress can lead to burnout, anxiety, and depression. Setting boundaries and prioritizing self-care protects your well-being.', explanation: '**Work and Mental Health**\n\nWhile work can provide purpose and meaning, too much work stress without balance can harm your mental health.\n\n**Signs of Poor Balance:**\n- Always exhausted\n- No time for relationships or hobbies\n- Work constantly on your mind\n- Physical symptoms (headaches, sleep problems)\n- Feeling irritable or anxious\n- Dreading work\n\n**Burnout Warning Signs:**\n- Emotional exhaustion\n- Feeling detached or cynical\n- Sense that nothing you do matters\n- Decreased effectiveness\n\n**Tips for Better Balance:**\n\n*Set Boundaries:*\n- Define work hours and stick to them\n- Turn off notifications after hours\n- Learn to say no\n- Take your breaks and vacation time\n\n*Prioritize Self-Care:*\n- Protect sleep\n- Make time for exercise\n- Maintain relationships\n- Do activities you enjoy\n\n*At Work:*\n- Take regular breaks\n- Focus on priorities\n- Delegate when possible\n- Communicate with supervisor about concerns\n\n**When to Get Help:**\nIf work stress is overwhelming or you have burnout symptoms, talk to a healthcare provider or mental health professional.', keyTerms: [{ term: 'burnout', definition: 'A state of chronic stress leading to exhaustion, cynicism, and ineffectiveness' }, { term: 'work-life balance', definition: 'Equilibrium between professional work and personal life' }], analogies: ['Balance is like a bank account - you cannot keep withdrawing without making deposits.'], examples: [] },
    2: { level: 2, summary: 'Occupational stress contributes to depression, anxiety, and physical health problems. Burnout is characterized by exhaustion, cynicism, and reduced efficacy. Interventions include individual strategies, workplace changes, and professional support when needed.', explanation: '**Work Stress Effects:**\n\n*Mental Health:*\n- Depression\n- Anxiety\n- Burnout\n- Substance use\n\n*Physical Health:*\n- Cardiovascular disease\n- Immune dysfunction\n- Musculoskeletal problems\n- Sleep disorders\n\n**Burnout:**\n\n*Three Dimensions (Maslach):*\n- Emotional exhaustion: Depleted, drained\n- Depersonalization: Cynicism, detachment\n- Reduced personal accomplishment: Ineffective, failing\n\n*Risk Factors:*\n- High demand, low control\n- Poor supervisor support\n- Unfair treatment\n- Values conflict\n- Lack of recognition\n\n**Intervention Levels:**\n\n*Individual:*\n- Stress management skills\n- Boundary setting\n- Self-care prioritization\n- Career decisions\n\n*Interpersonal:*\n- Social support at work\n- Communication skills\n- Conflict resolution\n\n*Organizational:*\n- Workload management\n- Supervisor training\n- Policy changes\n- Culture shifts\n\n**When Professional Help Needed:**\n- Burnout affecting daily function\n- Depression or anxiety symptoms\n- Substance use to cope\n- Physical health problems', keyTerms: [{ term: 'Maslach Burnout Inventory', definition: 'Standard measure of burnout across three dimensions' }, { term: 'job demands-resources model', definition: 'Framework for understanding work stress' }, { term: 'depersonalization', definition: 'Cynical, detached attitude toward work' }], analogies: [] },
    3: { level: 3, summary: 'Occupational stress involves demand-control-support dynamics. Burnout is recognized as an occupational phenomenon (ICD-11). Evidence supports both individual and organizational interventions. Healthcare worker burnout is particular concern.', explanation: '**Theoretical Models:**\n\n*Demand-Control-Support:*\n- High demands + low control = strain\n- Social support moderates\n- Job redesign implications\n\n*Effort-Reward Imbalance:*\n- High effort + low reward = distress\n- Includes recognition, security, promotion\n\n*Job Demands-Resources:*\n- Demands deplete\n- Resources buffer and motivate\n- Balance matters\n\n**Burnout (ICD-11):**\n\n*Definition:*\n- Occupational phenomenon\n- Chronic workplace stress not successfully managed\n- Three dimensions\n\n*Not Same As:*\n- Depression (though overlaps)\n- Adjustment to non-work stress\n- Other mental disorders\n\n**Intervention Evidence:**\n\n*Individual Level:*\n- Mindfulness programs\n- CBT-based stress management\n- Resilience training\n- Modest effects alone\n\n*Organizational Level:*\n- Workload reduction\n- Increasing autonomy\n- Improving fairness\n- Leadership development\n- More sustained effects\n\n*Combined Approaches:*\n- Most effective\n- Individual + organizational\n\n**Healthcare Worker Burnout:**\n- High prevalence\n- System factors predominant\n- Patient safety implications\n- Requires organizational response', keyTerms: [{ term: 'demand-control model', definition: 'Work stress model: high demands + low control = strain' }, { term: 'effort-reward imbalance', definition: 'Stress from mismatch between work effort and rewards' }, { term: 'occupational phenomenon', definition: 'ICD-11 classification of burnout as work-related, not medical diagnosis' }], clinicalNotes: 'Burnout overlaps with but is distinct from depression. Assess occupational factors in mental health presentations. Individual interventions alone insufficient. Consider workplace advocacy. Healthcare workers at high risk.' },
    4: { level: 4, summary: 'Burnout pathophysiology involves HPA axis dysregulation, inflammation, and neural changes overlapping with depression. Differentiation from depression important for intervention. Organizational interventions have stronger evidence than individual alone.', explanation: '**Pathophysiology:**\n\n*Stress Response:*\n- Chronic HPA activation\n- Cortisol dysregulation (varied patterns)\n- Sympathetic activation\n\n*Inflammation:*\n- Elevated inflammatory markers\n- Similar to depression\n\n*Neural:*\n- Prefrontal changes\n- Overlaps with depression neuroscience\n- Distinct features unclear\n\n**Burnout vs Depression:**\n\n*Overlaps:*\n- Exhaustion\n- Cognitive impairment\n- Sleep problems\n- Anhedonia\n\n*Distinctions:*\n- Burnout: Work-specific, less pervasive (in theory)\n- Depression: Broader, self-critical, suicidality\n- Considerable overlap in practice\n\n*Clinical Implications:*\n- Screen for depression in burnout\n- Address workplace factors\n- Treatment may overlap\n\n**Organizational Interventions:**\n\n*Evidence-Based:*\n- Workload adjustment\n- Schedule flexibility\n- Autonomy enhancement\n- Leadership development\n- Peer support programs\n- Process improvement involving workers\n\n*Healthcare Specific:*\n- EHR optimization\n- Team-based care\n- Scribes and support staff\n- Reducing administrative burden\n\n**Measurement:**\n- Maslach Burnout Inventory\n- Copenhagen Burnout Inventory\n- Single-item measures\n- Organizational climate assessments', keyTerms: [{ term: 'work-specific', definition: 'Theoretical distinction that burnout is tied to work context' }, { term: 'administrative burden', definition: 'Non-clinical tasks contributing to healthcare burnout' }], clinicalNotes: 'Burnout and depression frequently co-occur. Individual resilience training insufficient alone. Organizational changes needed. Healthcare burnout is patient safety issue. Advocacy role for clinicians.' },
    5: { level: 5, summary: 'Contemporary burnout research addresses measurement debates, organizational science integration, policy implications, and system redesign. Post-pandemic workforce changes accelerated attention. Prevention and system-level approaches emphasized.', explanation: '**Current Debates:**\n\n*Measurement:*\n- Is burnout distinct from depression?\n- Diagnostic criteria debates\n- Cultural variations\n- Screening vs diagnosis\n\n*Construct:*\n- Individual vs organizational problem\n- Framing affects intervention\n- Political dimensions\n\n**Organizational Science:**\n\n*Implementation:*\n- Evidence-based organizational interventions\n- Leadership engagement\n- Sustainability\n- ROI for employers\n\n*Workplace Redesign:*\n- Human-centered design\n- Worker involvement\n- Iterative improvement\n- Culture change\n\n**Healthcare Specific:**\n\n*Quadruple Aim:*\n- Patient experience\n- Population health\n- Cost\n- Provider well-being (added fourth aim)\n\n*System Changes:*\n- EHR reform\n- Team-based care\n- Payment reform\n- Regulatory relief\n\n**Post-Pandemic:**\n\n*Workforce Changes:*\n- "Great Resignation"\n- Remote work impacts\n- Boundary blurring\n- Reassessment of priorities\n\n*Policy Attention:*\n- Surgeon General advisory (healthcare)\n- WHO recognition\n- Corporate responses\n\n**Future Directions:**\n- Prevention focus\n- Policy-level changes\n- Healthy organizational cultures\n- Work redesign\n- AI and automation implications', keyTerms: [{ term: 'Quadruple Aim', definition: 'Adding provider well-being to healthcare Triple Aim' }, { term: 'Great Resignation', definition: 'Post-pandemic workforce exodus and reassessment' }], clinicalNotes: 'Burnout increasingly recognized at policy level. Prevention and organizational change emphasized. Healthcare systems addressing as quality and safety issue. Individual clinicians can advocate for system changes. Work redesign needed.' },
  },

  media: [],
  citations: [{ id: 'maslach-burnout', type: 'article', title: 'Burnout Research', authors: ['Maslach C', 'Leiter MP'], source: 'Various publications' }],
  crossReferences: [{ targetId: 'mental-health-stress-management', targetType: 'topic', relationship: 'related', label: 'Stress Management' }],
  tags: { systems: ['nervous'], topics: ['mental-health', 'wellness', 'occupational'], keywords: ['burnout', 'work-life balance', 'work stress', 'occupational health'], clinicalRelevance: 'high', examRelevance: { usmle: false, nbme: false, shelf: [] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default workLifeBalanceContent;
