// medicina-deportiva-enciclopedia.ts
// Sports Medicine Bilingual Encyclopedia — Spanish-first
// Pattern: JSON.parse() to avoid TS2590 on large literal arrays

export interface MedicinaDeportivaEntry {
  id: string;
  nombreEs: string;
  nombreEn: string;
  descripcionEs: string;
  descripcionEn: string;
  categoriaEs: string;
  categoriaEn: string;
  sintomasEs: string[];
  sintomasEn: string[];
  causasEs: string;
  causasEn: string;
  diagnosticoEs: string;
  diagnosticoEn: string;
  tratamientoEs: string;
  tratamientoEn: string;
  rehabilitacionEs: string;
  rehabilitacionEn: string;
  prevencionEs: string;
  prevencionEn: string;
  tiempoRecuperacionEs: string;
  tiempoRecuperacionEn: string;
}

export const MEDICINA_DEPORTIVA_ENTRIES: MedicinaDeportivaEntry[] = JSON.parse(`[
  {
    "id": "esguince-tobillo",
    "nombreEs": "Esguince de Tobillo",
    "nombreEn": "Ankle Sprain",
    "descripcionEs": "El esguince de tobillo es una de las lesiones deportivas más frecuentes y ocurre cuando los ligamentos que sostienen la articulación del tobillo se estiran o desgarran más allá de su rango normal de movimiento. Generalmente se produce por una inversión forzada del pie, donde el tobillo gira hacia adentro de manera abrupta, afectando los ligamentos laterales, especialmente el ligamento talofibular anterior. Según su gravedad, se clasifica en tres grados: grado I (estiramiento leve con microrroturas), grado II (desgarro parcial con inestabilidad moderada) y grado III (rotura completa del ligamento con inestabilidad severa). Esta lesión es particularmente común en deportes que involucran saltos, cambios de dirección rápidos y contacto físico, como el baloncesto, el fútbol, el voleibol y el atletismo. La recurrencia es alta si no se realiza una rehabilitación adecuada, ya que la propiocepción y la fuerza muscular peronea pueden quedar comprometidas tras el primer episodio.",
    "nombreEn": "Ankle Sprain",
    "descripcionEn": "An ankle sprain is one of the most common sports injuries and occurs when the ligaments that support the ankle joint are stretched or torn beyond their normal range of motion. It typically results from a forced inversion of the foot, where the ankle rolls inward abruptly, affecting the lateral ligaments, especially the anterior talofibular ligament. Based on severity, it is classified into three grades: grade I (mild stretching with micro-tears), grade II (partial tear with moderate instability), and grade III (complete ligament rupture with severe instability). This injury is particularly common in sports involving jumping, rapid direction changes, and physical contact, such as basketball, soccer, volleyball, and track and field. Recurrence is high if proper rehabilitation is not performed, as proprioception and peroneal muscle strength may remain compromised after the first episode.",
    "categoriaEs": "Lesión ligamentosa",
    "categoriaEn": "Ligament injury",
    "sintomasEs": [
      "Dolor agudo e inmediato en la cara lateral del tobillo tras la torsión",
      "Hinchazón difusa que aparece en minutos y puede extenderse al pie",
      "Equimosis (moretones) que se desarrollan en las primeras 24-48 horas",
      "Dificultad o incapacidad para soportar peso sobre el pie afectado",
      "Sensación de inestabilidad articular al caminar o estar de pie",
      "Rigidez articular y disminución del rango de movimiento",
      "Sensibilidad a la palpación sobre los ligamentos laterales",
      "Chasquido o sonido audible en el momento de la lesión en casos severos"
    ],
    "sintomasEn": [
      "Acute and immediate pain on the lateral side of the ankle after twisting",
      "Diffuse swelling appearing within minutes that may extend to the foot",
      "Ecchymosis (bruising) developing within the first 24-48 hours",
      "Difficulty or inability to bear weight on the affected foot",
      "Sensation of joint instability when walking or standing",
      "Joint stiffness and decreased range of motion",
      "Tenderness on palpation over the lateral ligaments",
      "Pop or audible sound at the moment of injury in severe cases"
    ],
    "causasEs": "El esguince de tobillo se produce principalmente por una inversión forzada del pie durante actividades deportivas, aterrizajes incorrectos tras un salto, pisar sobre superficies irregulares o sobre el pie de otro jugador. Los factores de riesgo incluyen antecedentes previos de esguinces, debilidad muscular peronea, déficit propioceptivo, calzado inadecuado, superficies de juego irregulares y fatiga muscular que reduce la capacidad de estabilización refleja. La laxitud ligamentosa congénita y la alineación en varo del retropié también predisponen a esta lesión.",
    "causasEn": "Ankle sprains occur primarily from forced inversion of the foot during sports activities, incorrect landings after a jump, stepping on irregular surfaces, or landing on another player's foot. Risk factors include a history of previous sprains, peroneal muscle weakness, proprioceptive deficit, inadequate footwear, uneven playing surfaces, and muscular fatigue that reduces the capacity for reflex stabilization. Congenital ligament laxity and hindfoot varus alignment also predispose to this injury.",
    "diagnosticoEs": "El diagnóstico se basa en la historia clínica y el examen físico, incluyendo las pruebas del cajón anterior (para evaluar el ligamento talofibular anterior) y la prueba de inversión forzada (para el ligamento calcaneofibular). Se aplican las Reglas de Ottawa para determinar la necesidad de radiografías y descartar fracturas asociadas. La resonancia magnética (RM) se reserva para casos con sospecha de lesión grado III, lesiones osteocondrales o cuando los síntomas persisten más de 6 semanas a pesar del tratamiento conservador. La ecografía musculoesquelética es una alternativa accesible para evaluar la integridad ligamentosa en tiempo real.",
    "diagnosticoEn": "Diagnosis is based on clinical history and physical examination, including the anterior drawer test (to assess the anterior talofibular ligament) and the forced inversion test (for the calcaneofibular ligament). The Ottawa Ankle Rules are applied to determine the need for X-rays and to rule out associated fractures. MRI is reserved for cases with suspected grade III injury, osteochondral lesions, or when symptoms persist beyond 6 weeks despite conservative treatment. Musculoskeletal ultrasound is an accessible alternative for evaluating ligament integrity in real time.",
    "tratamientoEs": "El tratamiento inicial sigue el protocolo POLICE (Protección, Carga Óptima, Hielo, Compresión y Elevación). Para grado I-II se indica reposo relativo con movilización temprana, uso de tobillera funcional o vendaje neuromuscular, analgésicos (paracetamol o AINEs) y crioterapia en las primeras 48-72 horas. La carga de peso progresiva se inicia según tolerancia. Para grado III, se puede considerar inmovilización con bota ortopédica durante 2-3 semanas seguida de rehabilitación intensiva. La cirugía reconstructiva (reparación o reconstrucción de Broström) se reserva para casos de inestabilidad crónica que no responden al tratamiento conservador tras 3-6 meses de rehabilitación supervisada.",
    "tratamientoEn": "Initial treatment follows the POLICE protocol (Protection, Optimal Loading, Ice, Compression, and Elevation). For grade I-II, relative rest with early mobilization is indicated, using a functional ankle brace or neuromuscular taping, analgesics (acetaminophen or NSAIDs), and cryotherapy for the first 48-72 hours. Progressive weight-bearing is initiated as tolerated. For grade III, immobilization with an orthopedic boot for 2-3 weeks may be considered, followed by intensive rehabilitation. Reconstructive surgery (Broström repair or reconstruction) is reserved for cases of chronic instability that do not respond to conservative treatment after 3-6 months of supervised rehabilitation.",
    "rehabilitacionEs": "La rehabilitación se divide en fases progresivas. Fase 1 (0-2 semanas): control del dolor e inflamación, ejercicios de rango de movimiento activo (alfabeto con el pie, dorsiflexión y plantiflexión). Fase 2 (2-4 semanas): fortalecimiento isométrico e isotónico de los músculos peroneos, tibial posterior y tríceps sural, con bandas elásticas. Fase 3 (4-8 semanas): entrenamiento propioceptivo con tabla de equilibrio, superficies inestables (BOSU), ejercicios de cadena cinética cerrada y fortalecimiento excéntrico. Fase 4 (8-12 semanas): reintegración deportiva con ejercicios pliométricos, agilidad, cambios de dirección y simulación de actividades específicas del deporte. Se recomienda uso de tobillera funcional durante los primeros 6-12 meses tras la lesión.",
    "rehabilitacionEn": "Rehabilitation is divided into progressive phases. Phase 1 (0-2 weeks): pain and inflammation control, active range of motion exercises (foot alphabet, dorsiflexion, and plantarflexion). Phase 2 (2-4 weeks): isometric and isotonic strengthening of peroneal muscles, tibialis posterior, and triceps surae with resistance bands. Phase 3 (4-8 weeks): proprioceptive training with balance board, unstable surfaces (BOSU), closed kinetic chain exercises, and eccentric strengthening. Phase 4 (8-12 weeks): sports reintegration with plyometric exercises, agility drills, direction changes, and simulation of sport-specific activities. The use of a functional ankle brace is recommended during the first 6-12 months after injury.",
    "prevencionEs": "La prevención incluye programas de entrenamiento propioceptivo y de equilibrio realizados de forma regular, fortalecimiento de los músculos peroneos y estabilizadores del tobillo, uso de calzado deportivo apropiado con soporte lateral adecuado, calentamiento dinámico antes de la actividad deportiva, uso profiláctico de tobilleras en atletas con antecedentes de esguinces previos, y evaluación y corrección de alteraciones biomecánicas del pie y tobillo. Los programas de prevención neuromuscular han demostrado reducir la incidencia de esguinces hasta en un 50%.",
    "prevencionEn": "Prevention includes regular proprioceptive and balance training programs, strengthening of peroneal muscles and ankle stabilizers, use of appropriate sports footwear with adequate lateral support, dynamic warm-up before sports activity, prophylactic use of ankle braces in athletes with a history of previous sprains, and evaluation and correction of biomechanical alterations of the foot and ankle. Neuromuscular prevention programs have been shown to reduce the incidence of sprains by up to 50%.",
    "tiempoRecuperacionEs": "Grado I: 1-3 semanas. Grado II: 3-6 semanas. Grado III: 6-12 semanas o más. La reconstrucción quirúrgica requiere 4-6 meses para el retorno deportivo completo. La recuperación funcional completa con restauración de la propiocepción puede tomar hasta 6 meses independientemente del grado.",
    "tiempoRecuperacionEn": "Grade I: 1-3 weeks. Grade II: 3-6 weeks. Grade III: 6-12 weeks or more. Surgical reconstruction requires 4-6 months for full return to sport. Complete functional recovery with proprioception restoration may take up to 6 months regardless of grade."
  },
  {
    "id": "rotura-ligamento-cruzado",
    "nombreEs": "Rotura del Ligamento Cruzado Anterior",
    "nombreEn": "Anterior Cruciate Ligament (ACL) Tear",
    "descripcionEs": "La rotura del ligamento cruzado anterior (LCA) es una de las lesiones de rodilla más devastadoras en el ámbito deportivo, afectando la estructura intraarticular que conecta el fémur con la tibia y que es fundamental para la estabilidad rotacional y anteroposterior de la rodilla. El LCA se compone de dos fascículos (anteromedial y posterolateral) que trabajan sinérgicamente para prevenir la traslación anterior de la tibia y la rotación interna excesiva. Esta lesión predomina en deportes de pivote como fútbol, baloncesto, esquí y balonmano, con una incidencia significativamente mayor en mujeres atletas (2-8 veces más que en hombres) debido a factores anatómicos, hormonales y neuromusculares. La rotura del LCA frecuentemente se asocia con lesiones concomitantes del menisco medial, el ligamento colateral medial y el cartílago articular, lo que constituye la denominada tríada infeliz o tríada de O'Donoghue cuando se combinan las tres estructuras.",
    "descripcionEn": "An anterior cruciate ligament (ACL) tear is one of the most devastating knee injuries in sports, affecting the intra-articular structure connecting the femur to the tibia that is essential for rotational and anteroposterior stability of the knee. The ACL is composed of two bundles (anteromedial and posterolateral) that work synergistically to prevent anterior tibial translation and excessive internal rotation. This injury predominates in pivoting sports such as soccer, basketball, skiing, and handball, with significantly higher incidence in female athletes (2-8 times more than males) due to anatomical, hormonal, and neuromuscular factors. ACL tears frequently occur with concomitant injuries to the medial meniscus, medial collateral ligament, and articular cartilage, constituting the so-called unhappy triad or O'Donoghue triad when all three structures are involved.",
    "categoriaEs": "Lesión ligamentosa",
    "categoriaEn": "Ligament injury",
    "sintomasEs": [
      "Chasquido audible o sensación de 'pop' en el momento de la lesión",
      "Derrame articular rápido (hemartrosis) en las primeras 2-4 horas",
      "Sensación de inestabilidad o que la rodilla 'cede' o 'se sale'",
      "Dolor intenso que impide continuar la actividad deportiva",
      "Incapacidad para soportar peso completo sobre la pierna afectada",
      "Pérdida del rango de movimiento completo, especialmente la extensión",
      "Inflamación generalizada de la rodilla que aumenta progresivamente",
      "Sensibilidad en la línea articular y a lo largo del ligamento"
    ],
    "sintomasEn": [
      "Audible pop or popping sensation at the time of injury",
      "Rapid joint effusion (hemarthrosis) within the first 2-4 hours",
      "Sensation of instability or the knee 'giving way' or 'buckling'",
      "Severe pain preventing continuation of sports activity",
      "Inability to bear full weight on the affected leg",
      "Loss of full range of motion, especially extension",
      "Generalized knee swelling that progressively increases",
      "Tenderness along the joint line and along the ligament"
    ],
    "causasEs": "La rotura del LCA se produce por mecanismos de no contacto en aproximadamente el 70% de los casos, incluyendo desaceleración brusca con cambio de dirección, aterrizaje con la rodilla en hiperextensión o valgo dinámico, y pivoteo sobre el pie fijo. Los mecanismos de contacto incluyen traumatismos directos laterales sobre la rodilla. Los factores de riesgo incluyen: sexo femenino, índice de masa corporal elevado, déficit neuromuscular (dominancia del cuádriceps sobre los isquiotibiales), fatiga muscular, ángulo Q aumentado, pendiente tibial posterior pronunciada, escotadura intercondílea estrecha, fase folicular del ciclo menstrual y antecedentes familiares de lesión del LCA.",
    "causasEn": "ACL tears occur through non-contact mechanisms in approximately 70% of cases, including sudden deceleration with direction change, landing with the knee in hyperextension or dynamic valgus, and pivoting on a planted foot. Contact mechanisms include direct lateral blows to the knee. Risk factors include: female sex, elevated body mass index, neuromuscular deficits (quadriceps dominance over hamstrings), muscle fatigue, increased Q-angle, steep posterior tibial slope, narrow intercondylar notch, follicular phase of the menstrual cycle, and family history of ACL injury.",
    "diagnosticoEs": "El diagnóstico clínico se realiza mediante la prueba de Lachman (la más sensible, >85%), la prueba del cajón anterior y la prueba de desplazamiento del pivote (pivot shift). La resonancia magnética es el estándar de oro para confirmar el diagnóstico, con una sensibilidad y especificidad superiores al 95%, y permite evaluar lesiones asociadas de meniscos, cartílago y otros ligamentos. Las radiografías convencionales se realizan para descartar fracturas asociadas, incluyendo la fractura por avulsión de Segond (patognomónica de lesión del LCA). La artroscopia diagnóstica raramente es necesaria dado el alto rendimiento de la RM.",
    "diagnosticoEn": "Clinical diagnosis is performed using the Lachman test (the most sensitive, >85%), the anterior drawer test, and the pivot shift test. MRI is the gold standard for confirming the diagnosis, with sensitivity and specificity greater than 95%, and allows evaluation of associated meniscal, cartilage, and other ligament injuries. Conventional X-rays are performed to rule out associated fractures, including the Segond avulsion fracture (pathognomonic of ACL injury). Diagnostic arthroscopy is rarely necessary given the high performance of MRI.",
    "tratamientoEs": "El tratamiento se divide en conservador y quirúrgico según el nivel de actividad del paciente, la presencia de lesiones asociadas y el grado de inestabilidad. El tratamiento conservador (rehabilitación intensiva, ortesis funcional y modificación de actividades) puede ser apropiado para pacientes sedentarios o de mayor edad sin inestabilidad funcional significativa. La reconstrucción quirúrgica artroscópica es el estándar para atletas y personas activas, utilizando autoinjertos (tendón rotuliano, isquiotibiales o cuadricipital) o aloinjertos. La técnica anatómica de doble fascículo busca restaurar la biomecánica original del ligamento. La rehabilitación prequirúrgica ('prehab') de 2-6 semanas para restaurar el rango de movimiento y la fuerza muscular mejora significativamente los resultados postoperatorios.",
    "tratamientoEn": "Treatment is divided into conservative and surgical approaches based on the patient's activity level, presence of associated injuries, and degree of instability. Conservative treatment (intensive rehabilitation, functional bracing, and activity modification) may be appropriate for sedentary or older patients without significant functional instability. Arthroscopic surgical reconstruction is the standard for athletes and active individuals, using autografts (patellar tendon, hamstring, or quadriceps tendon) or allografts. The anatomic double-bundle technique aims to restore the original biomechanics of the ligament. Pre-surgical rehabilitation ('prehab') for 2-6 weeks to restore range of motion and muscle strength significantly improves postoperative outcomes.",
    "rehabilitacionEs": "La rehabilitación post-reconstrucción del LCA es un proceso prolongado y estructurado en fases. Fase 1 (0-2 semanas): control de dolor e inflamación, extensión pasiva completa, flexión progresiva hasta 90 grados, activación del cuádriceps. Fase 2 (2-6 semanas): carga de peso progresiva, bicicleta estática, ejercicios de cadena cinética cerrada. Fase 3 (6-12 semanas): fortalecimiento muscular progresivo, entrenamiento propioceptivo, natación y ejercicios acuáticos. Fase 4 (3-6 meses): carrera progresiva, ejercicios de agilidad en línea recta, fortalecimiento avanzado. Fase 5 (6-9 meses): ejercicios pliométricos, agilidad multidireccional, simulación deportiva específica. Fase 6 (9-12 meses): retorno deportivo gradual basado en criterios funcionales objetivos (fuerza >90% del lado contralateral, pruebas de salto >90%, confianza psicológica).",
    "rehabilitacionEn": "Post-ACL reconstruction rehabilitation is a prolonged and phase-structured process. Phase 1 (0-2 weeks): pain and inflammation control, full passive extension, progressive flexion to 90 degrees, quadriceps activation. Phase 2 (2-6 weeks): progressive weight-bearing, stationary cycling, closed kinetic chain exercises. Phase 3 (6-12 weeks): progressive muscle strengthening, proprioceptive training, swimming and aquatic exercises. Phase 4 (3-6 months): progressive running, straight-line agility exercises, advanced strengthening. Phase 5 (6-9 months): plyometric exercises, multidirectional agility, sport-specific simulation. Phase 6 (9-12 months): gradual return to sport based on objective functional criteria (strength >90% of contralateral side, hop tests >90%, psychological readiness).",
    "prevencionEs": "Los programas de prevención neuromuscular como el FIFA 11+, PEP y Sportsmetrics han demostrado reducir la incidencia de lesiones del LCA en un 50-70%. Estos programas incluyen ejercicios de calentamiento dinámico, fortalecimiento de isquiotibiales y glúteos, entrenamiento pliométrico con técnica de aterrizaje correcta (rodillas flexionadas, alineación rodilla-pie), ejercicios de agilidad y equilibrio, y educación sobre mecánicas de movimiento de riesgo. Es fundamental abordar el desequilibrio cuádriceps/isquiotibiales y el patrón de dominancia ligamentosa. La implementación debe ser regular (2-3 veces por semana durante toda la temporada) y supervisada inicialmente.",
    "prevencionEn": "Neuromuscular prevention programs such as FIFA 11+, PEP, and Sportsmetrics have been shown to reduce the incidence of ACL injuries by 50-70%. These programs include dynamic warm-up exercises, hamstring and gluteal strengthening, plyometric training with correct landing technique (knees bent, knee-foot alignment), agility and balance exercises, and education on risky movement mechanics. It is essential to address quadriceps/hamstring imbalance and ligament dominance patterns. Implementation must be regular (2-3 times per week throughout the season) and initially supervised.",
    "tiempoRecuperacionEs": "Tratamiento conservador: 3-6 meses para actividades de la vida diaria. Reconstrucción quirúrgica: 9-12 meses para el retorno deportivo competitivo. Algunos atletas de élite pueden requerir hasta 24 meses para alcanzar el nivel de rendimiento previo a la lesión. La tasa de re-rotura es del 6-25% en los primeros 2 años post-reconstrucción, siendo mayor en atletas jóvenes menores de 20 años.",
    "tiempoRecuperacionEn": "Conservative treatment: 3-6 months for daily living activities. Surgical reconstruction: 9-12 months for competitive return to sport. Some elite athletes may require up to 24 months to reach pre-injury performance levels. The re-tear rate is 6-25% in the first 2 years post-reconstruction, being higher in young athletes under 20 years of age."
  },
  {
    "id": "tendinitis-aquiles",
    "nombreEs": "Tendinitis de Aquiles",
    "nombreEn": "Achilles Tendinitis",
    "descripcionEs": "La tendinitis de Aquiles, más correctamente denominada tendinopatía aquílea, es una condición degenerativa y dolorosa del tendón de Aquiles, la estructura tendinosa más grande y fuerte del cuerpo humano que conecta los músculos gastrocnemio y sóleo con el calcáneo. Se distinguen dos formas principales: la tendinopatía insercional (en la unión con el calcáneo, asociada frecuentemente con la deformidad de Haglund) y la tendinopatía de la porción media (2-6 cm proximal a la inserción, la más común en corredores). La patología subyacente es predominantemente degenerativa (tendinosis) más que inflamatoria, con desorganización de las fibras de colágeno, neovascularización y aumento de sustancia fundamental. Es una de las lesiones por sobreuso más frecuentes en corredores y deportistas que realizan actividades con impacto repetitivo, representando hasta el 11% de todas las lesiones por carrera.",
    "descripcionEn": "Achilles tendinitis, more correctly termed Achilles tendinopathy, is a degenerative and painful condition of the Achilles tendon, the largest and strongest tendinous structure in the human body connecting the gastrocnemius and soleus muscles to the calcaneus. Two main forms are distinguished: insertional tendinopathy (at the calcaneal junction, frequently associated with Haglund's deformity) and midportion tendinopathy (2-6 cm proximal to the insertion, the most common in runners). The underlying pathology is predominantly degenerative (tendinosis) rather than inflammatory, with disorganization of collagen fibers, neovascularization, and increased ground substance. It is one of the most frequent overuse injuries in runners and athletes performing activities with repetitive impact, accounting for up to 11% of all running injuries.",
    "categoriaEs": "Lesión de tendón",
    "categoriaEn": "Tendon injury",
    "sintomasEs": [
      "Dolor gradual en la parte posterior del tobillo que empeora con la actividad",
      "Rigidez matutina en el tendón de Aquiles que mejora con el movimiento",
      "Engrosamiento fusiforme palpable del tendón en la porción media",
      "Dolor que se intensifica al inicio del ejercicio, mejora durante la actividad y reaparece después",
      "Sensibilidad a la palpación directa sobre el tendón afectado",
      "Crepitación peritendinosa durante la dorsiflexión y plantiflexión activas",
      "Debilidad en la flexión plantar y dificultad para ponerse de puntillas",
      "Dolor al subir escaleras, correr o saltar"
    ],
    "sintomasEn": [
      "Gradual pain in the posterior ankle that worsens with activity",
      "Morning stiffness in the Achilles tendon that improves with movement",
      "Palpable fusiform thickening of the tendon in the midportion",
      "Pain that intensifies at the start of exercise, improves during activity, and returns afterward",
      "Tenderness on direct palpation over the affected tendon",
      "Peritendinous crepitation during active dorsiflexion and plantarflexion",
      "Weakness in plantar flexion and difficulty rising on tiptoes",
      "Pain when climbing stairs, running, or jumping"
    ],
    "causasEs": "La tendinopatía aquílea es causada principalmente por sobrecarga mecánica repetitiva que excede la capacidad de reparación del tendón. Los factores de riesgo extrínsecos incluyen: aumento brusco del volumen o intensidad del entrenamiento (error de entrenamiento), cambio de superficie de carrera, calzado inadecuado o desgastado, y correr en pendientes. Los factores intrínsecos incluyen: pronación excesiva del pie, desalineación biomecánica de la cadena posterior, rigidez del complejo gastrocnemio-sóleo, edad avanzada (la vascularización del tendón disminuye con la edad), obesidad, uso de fluoroquinolonas, hipercolesterolemia, diabetes mellitus y enfermedades reumatológicas.",
    "causasEn": "Achilles tendinopathy is primarily caused by repetitive mechanical overload that exceeds the tendon's repair capacity. Extrinsic risk factors include: abrupt increase in training volume or intensity (training error), change in running surface, inadequate or worn-out footwear, and running on inclines. Intrinsic risk factors include: excessive foot pronation, biomechanical misalignment of the posterior chain, gastrocnemius-soleus complex tightness, advancing age (tendon vascularization decreases with age), obesity, fluoroquinolone use, hypercholesterolemia, diabetes mellitus, and rheumatological diseases.",
    "diagnosticoEs": "El diagnóstico es fundamentalmente clínico. La prueba de Royal London Hospital (dolor a la palpación que disminuye con la dorsiflexión del tobillo) y la prueba del arco doloroso ayudan a localizar la lesión. La ecografía musculoesquelética es la primera línea de imagen, mostrando engrosamiento tendinoso, hipoecogenicidad focal, neovascularización en Doppler de potencia y posibles calcificaciones insercionales. La resonancia magnética se reserva para casos atípicos o para planificación prequirúrgica, mostrando señal intratendinosa aumentada en T2 y engrosamiento tendinoso. La prueba de Thompson debe realizarse para descartar rotura completa del tendón.",
    "diagnosticoEn": "Diagnosis is fundamentally clinical. The Royal London Hospital test (tenderness on palpation that decreases with ankle dorsiflexion) and the painful arc test help localize the lesion. Musculoskeletal ultrasound is the first-line imaging, showing tendon thickening, focal hypoechogenicity, neovascularization on power Doppler, and possible insertional calcifications. MRI is reserved for atypical cases or pre-surgical planning, showing increased intratendinous signal on T2 and tendon thickening. The Thompson test must be performed to rule out complete tendon rupture.",
    "tratamientoEs": "El pilar del tratamiento conservador es el programa de ejercicios excéntricos de Alfredson, que consiste en descensos excéntricos del talón realizados 2 veces al día, 3 series de 15 repeticiones, durante un mínimo de 12 semanas. Se complementa con: modificación de la carga de entrenamiento (reducción del 50% inicial con incremento progresivo), crioterapia post-actividad, taloneras de gel para reducir la tensión sobre el tendón, terapia de ondas de choque extracorpóreas (ESWT) para casos refractarios, inyecciones de plasma rico en plaquetas (PRP) en casos seleccionados, y nitroglicerina tópica. Los AINEs se usan con precaución ya que pueden interferir con la reparación tendinosa. Las inyecciones de corticosteroides están contraindicadas por el riesgo de rotura tendinosa. La cirugía (desbridamiento, transferencia del flexor largo del hallux) se reserva para fracasos del tratamiento conservador tras 6 meses.",
    "tratamientoEn": "The cornerstone of conservative treatment is the Alfredson eccentric exercise program, consisting of eccentric heel drops performed twice daily, 3 sets of 15 repetitions, for a minimum of 12 weeks. This is supplemented with: training load modification (initial 50% reduction with progressive increase), post-activity cryotherapy, gel heel lifts to reduce tendon tension, extracorporeal shockwave therapy (ESWT) for refractory cases, platelet-rich plasma (PRP) injections in selected cases, and topical nitroglycerin. NSAIDs are used cautiously as they may interfere with tendon repair. Corticosteroid injections are contraindicated due to the risk of tendon rupture. Surgery (debridement, flexor hallucis longus transfer) is reserved for failures of conservative treatment after 6 months.",
    "rehabilitacionEs": "La rehabilitación se centra en el programa de carga progresiva del tendón. Fase 1 (0-4 semanas): ejercicios isométricos de la pantorrilla (5 series de 45 segundos), movilidad activa del tobillo, masaje transverso profundo. Fase 2 (4-8 semanas): ejercicios excéntricos de Alfredson (protocolo completo), fortalecimiento isotónico progresivo, estiramientos del sóleo y gastrocnemio. Fase 3 (8-12 semanas): ejercicios de almacenamiento de energía (saltar la cuerda, pliometría suave), incremento gradual de la carga de carrera (programa couch-to-5K modificado). Fase 4 (12-16 semanas): reintegración deportiva completa con monitorización de síntomas. Es fundamental la regla del dolor: la actividad puede realizarse si el dolor es menor de 5/10 y no aumenta más de 2 puntos al día siguiente.",
    "rehabilitacionEn": "Rehabilitation focuses on progressive tendon loading. Phase 1 (0-4 weeks): calf isometric exercises (5 sets of 45 seconds), active ankle mobility, deep transverse massage. Phase 2 (4-8 weeks): Alfredson eccentric exercises (full protocol), progressive isotonic strengthening, soleus and gastrocnemius stretching. Phase 3 (8-12 weeks): energy storage exercises (jump rope, gentle plyometrics), gradual increase in running load (modified couch-to-5K program). Phase 4 (12-16 weeks): full sports reintegration with symptom monitoring. The pain rule is essential: activity can be performed if pain is less than 5/10 and does not increase by more than 2 points the following day.",
    "prevencionEs": "La prevención incluye incremento gradual de la carga de entrenamiento (regla del 10%: no aumentar más del 10% semanal en volumen o intensidad), programa regular de fortalecimiento excéntrico de la pantorrilla, estiramientos adecuados del complejo gastrocnemio-sóleo, uso de calzado con amortiguación apropiada y reemplazo regular, análisis biomecánico de la carrera para corregir deficiencias, variación de superficies de entrenamiento, períodos adecuados de recuperación entre sesiones intensas, y corrección de factores de riesgo modificables como la hiperpronación mediante ortesis plantares.",
    "prevencionEn": "Prevention includes gradual training load increase (the 10% rule: do not increase more than 10% weekly in volume or intensity), regular eccentric calf strengthening program, adequate stretching of the gastrocnemius-soleus complex, use of footwear with appropriate cushioning and regular replacement, running biomechanics analysis to correct deficiencies, variation of training surfaces, adequate recovery periods between intense sessions, and correction of modifiable risk factors such as hyperpronation through plantar orthotics.",
    "tiempoRecuperacionEs": "Tendinopatía leve: 6-8 semanas con tratamiento conservador adecuado. Tendinopatía moderada: 3-6 meses. Tendinopatía crónica severa: 6-12 meses. Recuperación post-quirúrgica: 4-6 meses para actividades deportivas. El 75-90% de los pacientes responden al tratamiento conservador si se realiza de forma consistente y prolongada.",
    "tiempoRecuperacionEn": "Mild tendinopathy: 6-8 weeks with adequate conservative treatment. Moderate tendinopathy: 3-6 months. Severe chronic tendinopathy: 6-12 months. Post-surgical recovery: 4-6 months for sports activities. 75-90% of patients respond to conservative treatment if performed consistently and for a prolonged period."
  },
  {
    "id": "fractura-estres",
    "nombreEs": "Fractura por Estrés",
    "nombreEn": "Stress Fracture",
    "descripcionEs": "Las fracturas por estrés son lesiones óseas por sobreuso que resultan de la acumulación de microtraumatismos repetitivos que superan la capacidad de remodelación ósea normal. A diferencia de las fracturas agudas traumáticas, las fracturas por estrés se desarrollan gradualmente cuando el hueso es sometido a cargas cíclicas repetidas sin tiempo suficiente de recuperación. Representan entre el 10-20% de todas las lesiones deportivas y son especialmente prevalentes en corredores de fondo, militares en entrenamiento básico, bailarines y gimnastas. Los sitios más comúnmente afectados incluyen la tibia (más del 50% de los casos), los metatarsianos (especialmente el segundo y tercero), el peroné, el navicular del tarso, el fémur y la pelvis. Se clasifican en fracturas de bajo riesgo (tibia medial, peroné, metatarsianos 2-4) y alto riesgo (navicular del tarso, base del quinto metatarsiano, cuello femoral, tibia anterior) según su potencial de progresión a fractura completa o complicaciones.",
    "descripcionEn": "Stress fractures are overuse bone injuries resulting from the accumulation of repetitive microtrauma that exceeds normal bone remodeling capacity. Unlike acute traumatic fractures, stress fractures develop gradually when bone is subjected to repeated cyclic loading without sufficient recovery time. They represent 10-20% of all sports injuries and are especially prevalent in distance runners, military recruits in basic training, dancers, and gymnasts. The most commonly affected sites include the tibia (more than 50% of cases), metatarsals (especially the second and third), fibula, tarsal navicular, femur, and pelvis. They are classified into low-risk fractures (medial tibia, fibula, metatarsals 2-4) and high-risk fractures (tarsal navicular, base of fifth metatarsal, femoral neck, anterior tibia) based on their potential for progression to complete fracture or complications.",
    "categoriaEs": "Lesión ósea",
    "categoriaEn": "Bone injury",
    "sintomasEs": [
      "Dolor localizado e insidioso que aparece durante la actividad y se alivia con el reposo",
      "Progresión del dolor que eventualmente se presenta incluso en reposo o con actividades cotidianas",
      "Sensibilidad puntual a la palpación directa sobre el sitio de fractura",
      "Hinchazón localizada sobre el área ósea afectada",
      "Dolor que aumenta con la carga de peso y al final del día",
      "Prueba de vibración positiva (dolor al aplicar un diapasón sobre el hueso)",
      "Dolor nocturno en casos avanzados o fracturas de alto riesgo",
      "Cojera protectora durante la marcha"
    ],
    "sintomasEn": [
      "Localized and insidious pain that appears during activity and resolves with rest",
      "Pain progression that eventually presents even at rest or with daily activities",
      "Point tenderness on direct palpation over the fracture site",
      "Localized swelling over the affected bony area",
      "Pain that increases with weight-bearing and at the end of the day",
      "Positive vibration test (pain when applying a tuning fork over the bone)",
      "Night pain in advanced cases or high-risk fractures",
      "Protective limping during gait"
    ],
    "causasEs": "Las fracturas por estrés resultan de un desequilibrio entre la formación y la resorción ósea causado por carga mecánica excesiva. Los factores de riesgo incluyen: aumento rápido del volumen o intensidad del entrenamiento, cambio abrupto de calzado o superficie de entrenamiento, biomecánica alterada (pie cavo, discrepancia de longitud de miembros inferiores), déficit nutricional (deficiencia de vitamina D, calcio insuficiente, baja disponibilidad energética relativa o RED-S), tríada de la atleta femenina (baja disponibilidad energética, disfunción menstrual y baja densidad mineral ósea), uso de corticosteroides crónicos, tabaquismo y factores genéticos que afectan el metabolismo óseo.",
    "causasEn": "Stress fractures result from an imbalance between bone formation and resorption caused by excessive mechanical loading. Risk factors include: rapid increase in training volume or intensity, abrupt change in footwear or training surface, altered biomechanics (cavus foot, lower limb length discrepancy), nutritional deficits (vitamin D deficiency, insufficient calcium, relative energy deficiency in sport or RED-S), female athlete triad (low energy availability, menstrual dysfunction, and low bone mineral density), chronic corticosteroid use, smoking, and genetic factors affecting bone metabolism.",
    "diagnosticoEs": "El diagnóstico puede ser desafiante en fases tempranas. Las radiografías iniciales son normales en el 50-70% de los casos y pueden mostrar cambios (línea de fractura, reacción perióstica, formación de callo) solo después de 2-4 semanas. La resonancia magnética es el estándar de oro, con sensibilidad cercana al 100%, mostrando edema óseo medular en secuencias STIR/T2 antes de que aparezca la línea de fractura. La gammagrafía ósea con tecnecio-99m es altamente sensible pero poco específica. La tomografía computarizada es útil para fracturas del navicular y la base del quinto metatarsiano. El sistema de clasificación de Fredericson por RM (grados 1-4) permite estratificar la severidad y guiar el tratamiento.",
    "diagnosticoEn": "Diagnosis can be challenging in early phases. Initial X-rays are normal in 50-70% of cases and may show changes (fracture line, periosteal reaction, callus formation) only after 2-4 weeks. MRI is the gold standard, with sensitivity approaching 100%, showing bone marrow edema on STIR/T2 sequences before the fracture line appears. Technetium-99m bone scintigraphy is highly sensitive but poorly specific. CT is useful for navicular and fifth metatarsal base fractures. The Fredericson MRI classification system (grades 1-4) allows severity stratification and guides treatment.",
    "tratamientoEs": "El tratamiento depende de la clasificación de riesgo de la fractura. Fracturas de bajo riesgo: reposo relativo con reducción de la actividad causante, carga de peso tolerada con calzado rígido o bota neumática durante 4-8 semanas, actividad física alternativa de bajo impacto (natación, ciclismo). Fracturas de alto riesgo: inmovilización sin carga de peso (navicular, base del quinto metatarsiano) o intervención quirúrgica (fijación con tornillo para navicular o quinto metatarsiano, fijación intramedular para tibia anterior). Se debe optimizar el estado nutricional: vitamina D (mantener niveles >30 ng/mL), ingesta de calcio de 1500 mg/día y asegurar disponibilidad energética adecuada (>45 kcal/kg de masa libre de grasa/día). Los estimuladores óseos por ultrasonido pulsado de baja intensidad (LIPUS) pueden considerarse como terapia adyuvante.",
    "tratamientoEn": "Treatment depends on the fracture's risk classification. Low-risk fractures: relative rest with reduction of the causative activity, weight-bearing as tolerated with rigid footwear or pneumatic boot for 4-8 weeks, alternative low-impact physical activity (swimming, cycling). High-risk fractures: non-weight-bearing immobilization (navicular, fifth metatarsal base) or surgical intervention (screw fixation for navicular or fifth metatarsal, intramedullary fixation for anterior tibia). Nutritional status should be optimized: vitamin D (maintain levels >30 ng/mL), calcium intake of 1500 mg/day, and ensuring adequate energy availability (>45 kcal/kg fat-free mass/day). Low-intensity pulsed ultrasound (LIPUS) bone stimulators may be considered as adjunctive therapy.",
    "rehabilitacionEs": "La rehabilitación sigue un protocolo de reintegración gradual a la actividad. Fase 1 (0-4 semanas): reposo activo, mantenimiento de la condición cardiovascular con actividades sin impacto (piscina, bicicleta), fortalecimiento muscular del tronco y extremidades superiores. Fase 2 (4-8 semanas): inicio de carga progresiva según resolución del dolor, caminata en superficie plana, fortalecimiento de la musculatura de soporte. Fase 3 (8-12 semanas): programa de carrera progresiva comenzando con intervalos de caminata/trote (programa de retorno a la carrera), corrección biomecánica si se identificaron factores contribuyentes. Fase 4 (12-16 semanas): reintegración deportiva completa con monitorización continua de síntomas. El criterio clave de progresión es la ausencia de dolor durante y después de cada etapa.",
    "rehabilitacionEn": "Rehabilitation follows a gradual activity reintegration protocol. Phase 1 (0-4 weeks): active rest, maintenance of cardiovascular fitness with non-impact activities (pool, cycling), core and upper extremity muscle strengthening. Phase 2 (4-8 weeks): initiation of progressive loading as pain resolves, flat surface walking, support musculature strengthening. Phase 3 (8-12 weeks): progressive running program beginning with walk/jog intervals (return-to-run program), biomechanical correction if contributing factors were identified. Phase 4 (12-16 weeks): complete sports reintegration with continuous symptom monitoring. The key progression criterion is the absence of pain during and after each stage.",
    "prevencionEs": "La prevención se basa en el manejo adecuado de la carga de entrenamiento (regla del 10%), uso de calzado con amortiguación adecuada y renovación regular, evaluación y corrección de deficiencias biomecánicas, optimización nutricional con ingesta adecuada de calcio (1000-1500 mg/día) y vitamina D (800-2000 UI/día), mantenimiento de una disponibilidad energética adecuada evitando la restricción calórica excesiva, inclusión de entrenamiento de fuerza para mejorar la densidad mineral ósea, variación de superficies e intensidades de entrenamiento, y evaluación periódica de la salud ósea en atletas de riesgo (mujeres con amenorrea, atletas con restricción energética).",
    "prevencionEn": "Prevention is based on adequate training load management (10% rule), use of footwear with adequate cushioning and regular renewal, evaluation and correction of biomechanical deficiencies, nutritional optimization with adequate calcium intake (1000-1500 mg/day) and vitamin D (800-2000 IU/day), maintenance of adequate energy availability while avoiding excessive caloric restriction, inclusion of strength training to improve bone mineral density, variation of training surfaces and intensities, and periodic evaluation of bone health in at-risk athletes (women with amenorrhea, athletes with energy restriction).",
    "tiempoRecuperacionEs": "Fracturas de bajo riesgo: 4-8 semanas para curación, 8-12 semanas para retorno deportivo. Fracturas de alto riesgo: 8-16 semanas para curación, 3-6 meses para retorno deportivo. Fracturas del navicular y quinto metatarsiano pueden requerir 4-6 meses. El retorno prematuro a la actividad aumenta significativamente el riesgo de re-fractura y progresión a fractura completa desplazada.",
    "tiempoRecuperacionEn": "Low-risk fractures: 4-8 weeks for healing, 8-12 weeks for return to sport. High-risk fractures: 8-16 weeks for healing, 3-6 months for return to sport. Navicular and fifth metatarsal fractures may require 4-6 months. Premature return to activity significantly increases the risk of re-fracture and progression to complete displaced fracture."
  },
  {
    "id": "conmocion-cerebral-deportiva",
    "nombreEs": "Conmoción Cerebral Deportiva",
    "nombreEn": "Sports Concussion",
    "descripcionEs": "La conmoción cerebral deportiva es una lesión cerebral traumática leve (LCTl) inducida por fuerzas biomecánicas transmitidas directa o indirectamente al cerebro durante la práctica deportiva. Representa un proceso fisiopatológico complejo que afecta la función cerebral sin causar lesiones estructurales macroscópicas detectables en la neuroimagen convencional. A nivel celular, se produce una cascada neurometabólica que incluye despolarización iónica generalizada, liberación masiva de neurotransmisores excitatorios (glutamato), flujo descontrolado de calcio intracelular, crisis energética mitocondrial e inflamación neuronal. Es la lesión deportiva más infradiagnosticada, con una estimación de 1.6 a 3.8 millones de casos anuales solo en Estados Unidos. El Consenso de Berlín (2016) y su actualización de Ámsterdam (2022) proporcionan las directrices internacionales actuales para su manejo. La preocupación creciente sobre la encefalopatía traumática crónica (ETC) asociada a impactos repetitivos ha revolucionado los protocolos de seguridad deportiva.",
    "descripcionEn": "Sports concussion is a mild traumatic brain injury (mTBI) induced by biomechanical forces transmitted directly or indirectly to the brain during sports practice. It represents a complex pathophysiological process that affects brain function without causing macroscopic structural lesions detectable on conventional neuroimaging. At the cellular level, a neurometabolic cascade occurs that includes generalized ionic depolarization, massive release of excitatory neurotransmitters (glutamate), uncontrolled intracellular calcium flux, mitochondrial energy crisis, and neuronal inflammation. It is the most underdiagnosed sports injury, with an estimated 1.6 to 3.8 million cases annually in the United States alone. The Berlin Consensus (2016) and its Amsterdam update (2022) provide the current international guidelines for management. Growing concern about chronic traumatic encephalopathy (CTE) associated with repetitive impacts has revolutionized sports safety protocols.",
    "categoriaEs": "Lesión traumática",
    "categoriaEn": "Traumatic injury",
    "sintomasEs": [
      "Cefalea persistente o presión intracraneal, el síntoma más frecuente (>90%)",
      "Mareo, vértigo y alteraciones del equilibrio",
      "Confusión, desorientación y sensación de 'niebla mental'",
      "Pérdida de consciencia transitoria (presente solo en el 10% de los casos)",
      "Amnesia anterógrada o retrógrada del evento",
      "Náuseas o vómitos en las primeras horas",
      "Sensibilidad a la luz (fotofobia) y al ruido (fonofobia)",
      "Alteraciones del sueño (insomnio o hipersomnia)",
      "Dificultad de concentración, lentitud de procesamiento cognitivo",
      "Irritabilidad, labilidad emocional, ansiedad o depresión"
    ],
    "sintomasEn": [
      "Persistent headache or intracranial pressure, the most frequent symptom (>90%)",
      "Dizziness, vertigo, and balance disturbances",
      "Confusion, disorientation, and sensation of 'brain fog'",
      "Transient loss of consciousness (present in only 10% of cases)",
      "Anterograde or retrograde amnesia of the event",
      "Nausea or vomiting in the first hours",
      "Sensitivity to light (photophobia) and noise (phonophobia)",
      "Sleep disturbances (insomnia or hypersomnia)",
      "Difficulty concentrating, slowed cognitive processing",
      "Irritability, emotional lability, anxiety, or depression"
    ],
    "causasEs": "La conmoción cerebral se produce por fuerzas de aceleración-desaceleración lineal o rotacional aplicadas al cerebro, ya sea por impacto directo en la cabeza (golpe, choque contra otro jugador u objeto) o por transmisión de fuerzas desde otra parte del cuerpo (latigazo cervical). Los deportes de mayor riesgo incluyen fútbol americano, rugby, hockey sobre hielo, fútbol (cabeceo), boxeo, artes marciales mixtas, lacrosse y ciclismo. Los factores de riesgo para sufrir una conmoción incluyen: antecedentes de conmociones previas (el principal factor de riesgo), sexo femenino (mayor incidencia reportada y recuperación más lenta), edad joven, historial de migrañas, trastornos del aprendizaje o déficit de atención, y depresión preexistente.",
    "causasEn": "Concussion is caused by linear or rotational acceleration-deceleration forces applied to the brain, either by direct impact to the head (blow, collision with another player or object) or by force transmission from another body part (whiplash). The highest-risk sports include American football, rugby, ice hockey, soccer (heading), boxing, mixed martial arts, lacrosse, and cycling. Risk factors for sustaining a concussion include: history of previous concussions (the primary risk factor), female sex (higher reported incidence and slower recovery), young age, history of migraines, learning disorders or attention deficits, and pre-existing depression.",
    "diagnosticoEs": "El diagnóstico es fundamentalmente clínico, ya que la neuroimagen convencional (TC y RM estándar) es normal por definición. Se utilizan herramientas estandarizadas como el SCAT6 (Sport Concussion Assessment Tool 6), que incluye evaluación de síntomas, orientación, memoria inmediata, concentración, memoria diferida y evaluación del equilibrio. La evaluación en la línea lateral debe realizarse por personal sanitario entrenado. La tomografía computarizada craneal se indica para descartar hemorragia intracraneal cuando hay signos de alarma (vómitos repetidos, convulsiones, deterioro progresivo de consciencia, cefalea severa creciente, signos neurológicos focales). Las pruebas neuropsicológicas computarizadas (ImPACT, CogSport) son valiosas cuando se dispone de valores de referencia pre-temporada. La investigación actual explora biomarcadores sanguíneos (GFAP, UCH-L1, NfL, tau) como herramientas diagnósticas objetivas.",
    "diagnosticoEn": "Diagnosis is fundamentally clinical, as conventional neuroimaging (CT and standard MRI) is normal by definition. Standardized tools such as the SCAT6 (Sport Concussion Assessment Tool 6) are used, which includes symptom evaluation, orientation, immediate memory, concentration, delayed memory, and balance assessment. Sideline assessment should be performed by trained medical personnel. Cranial CT is indicated to rule out intracranial hemorrhage when red-flag signs are present (repeated vomiting, seizures, progressive deterioration of consciousness, severe increasing headache, focal neurological signs). Computerized neuropsychological tests (ImPACT, CogSport) are valuable when pre-season baseline values are available. Current research is exploring blood biomarkers (GFAP, UCH-L1, NfL, tau) as objective diagnostic tools.",
    "tratamientoEs": "El tratamiento ha evolucionado del reposo absoluto prolongado a un enfoque de reposo relativo activo. El manejo agudo incluye: retiro inmediato de la actividad deportiva ('ante la duda, fuera'), evaluación médica en las primeras horas, reposo cognitivo y físico relativo durante las primeras 24-48 horas (evitar actividad extenuante pero no oscuridad absoluta ni aislamiento social). Después de 24-48 horas, se inicia actividad física aeróbica subsintomática (caminar, bicicleta estática a intensidad que no provoque síntomas). El retorno a la actividad académica/laboral es gradual con acomodaciones si es necesario. No existe medicación específica, pero los síntomas individuales pueden tratarse: melatonina para insomnio, amitriptilina para cefalea crónica post-conmoción, y terapia vestibular para mareo persistente. El seguimiento debe incluir evaluación de síntomas persistentes más allá de 2-4 semanas (síndrome post-conmoción).",
    "tratamientoEn": "Treatment has evolved from prolonged absolute rest to an active relative rest approach. Acute management includes: immediate removal from sports activity ('when in doubt, sit them out'), medical evaluation within the first hours, relative cognitive and physical rest during the first 24-48 hours (avoid strenuous activity but not absolute darkness or social isolation). After 24-48 hours, sub-symptom threshold aerobic physical activity is initiated (walking, stationary cycling at an intensity that does not provoke symptoms). Return to academic/work activities is gradual with accommodations if necessary. No specific medication exists, but individual symptoms can be treated: melatonin for insomnia, amitriptyline for chronic post-concussion headache, and vestibular therapy for persistent dizziness. Follow-up should include evaluation of persistent symptoms beyond 2-4 weeks (post-concussion syndrome).",
    "rehabilitacionEs": "El protocolo de retorno al deporte sigue 6 etapas graduales (cada etapa requiere mínimo 24 horas sin síntomas antes de avanzar): Etapa 1: Actividad limitada a síntomas (actividades cotidianas normales). Etapa 2: Actividad aeróbica ligera (caminar, nadar, bicicleta estática a 70% de frecuencia cardíaca máxima, 15-20 minutos). Etapa 3: Ejercicio específico del deporte (técnica, movimientos sin contacto). Etapa 4: Entrenamiento sin contacto (práctica con aumento progresivo de complejidad y carga cognitiva). Etapa 5: Práctica con contacto completo (tras autorización médica). Etapa 6: Retorno a la competición. Si los síntomas reaparecen en cualquier etapa, se retrocede a la etapa anterior y se espera 24 horas antes de reintentar. Para atletas pediátricos y adolescentes, cada etapa se extiende a 48 horas mínimo.",
    "rehabilitacionEn": "The return-to-sport protocol follows 6 gradual stages (each stage requires a minimum of 24 hours without symptoms before advancing): Stage 1: Symptom-limited activity (normal daily activities). Stage 2: Light aerobic activity (walking, swimming, stationary cycling at 70% maximum heart rate, 15-20 minutes). Stage 3: Sport-specific exercise (technique, non-contact drills). Stage 4: Non-contact training (practice with progressive increase in complexity and cognitive load). Stage 5: Full contact practice (after medical clearance). Stage 6: Return to competition. If symptoms recur at any stage, the athlete returns to the previous stage and waits 24 hours before retrying. For pediatric and adolescent athletes, each stage is extended to a minimum of 48 hours.",
    "prevencionEs": "La prevención abarca múltiples niveles: uso obligatorio de equipamiento protector apropiado (cascos certificados según el deporte, protectores bucales), aplicación y cumplimiento de reglas deportivas que penalicen el contacto peligroso con la cabeza, implementación de programas de entrenamiento neuromuscular del cuello para mejorar la estabilización de la cabeza ante impactos, limitación de la exposición a contacto en entrenamientos (especialmente en jóvenes), educación a atletas, entrenadores, padres y árbitros sobre el reconocimiento de síntomas y la importancia de reportarlos, evaluaciones de referencia pre-temporada (SCAT6, pruebas neuropsicológicas, equilibrio) y cultura deportiva que priorice la seguridad sobre el rendimiento competitivo.",
    "prevencionEn": "Prevention encompasses multiple levels: mandatory use of appropriate protective equipment (sport-specific certified helmets, mouthguards), application and enforcement of sporting rules that penalize dangerous head contact, implementation of neck neuromuscular training programs to improve head stabilization against impacts, limitation of contact exposure in training (especially in youth), education for athletes, coaches, parents, and referees on symptom recognition and the importance of reporting them, pre-season baseline assessments (SCAT6, neuropsychological tests, balance), and a sporting culture that prioritizes safety over competitive performance.",
    "tiempoRecuperacionEs": "La mayoría de los adultos (80-90%) se recuperan completamente en 10-14 días. Los niños y adolescentes pueden requerir 4 semanas o más. El síndrome post-conmoción (síntomas persistentes >4 semanas) afecta al 10-30% de los pacientes. Los factores de mal pronóstico incluyen: edad joven, sexo femenino, antecedentes de conmociones múltiples, historial de migrañas, trastornos psiquiátricos preexistentes y carga elevada de síntomas iniciales. La segunda conmoción antes de la recuperación completa de la primera (síndrome de segundo impacto) es extremadamente rara pero potencialmente fatal.",
    "tiempoRecuperacionEn": "Most adults (80-90%) fully recover within 10-14 days. Children and adolescents may require 4 weeks or more. Post-concussion syndrome (persistent symptoms >4 weeks) affects 10-30% of patients. Poor prognostic factors include: young age, female sex, history of multiple concussions, history of migraines, pre-existing psychiatric disorders, and high initial symptom burden. A second concussion before complete recovery from the first (second impact syndrome) is extremely rare but potentially fatal."
  },
  {
    "id": "epicondilitis-lateral",
    "nombreEs": "Epicondilitis Lateral (Codo de Tenista)",
    "nombreEn": "Lateral Epicondylitis (Tennis Elbow)",
    "descripcionEs": "La epicondilitis lateral, comúnmente conocida como codo de tenista, es una tendinopatía degenerativa que afecta los tendones extensores del antebrazo en su origen en el epicóndilo lateral del húmero, particularmente el tendón del extensor radial corto del carpo (ECRB). A pesar de su nombre coloquial, solo el 5-10% de los pacientes diagnosticados practican tenis; la condición es mucho más prevalente en trabajadores manuales y deportistas de raqueta en general. La fisiopatología actual comprende un proceso de tendinosis angiofibroblástica (degeneración del colágeno con hiperplasia fibroblástica y neovascularización) más que una verdadera tendinitis inflamatoria. Afecta predominantemente a personas de 35-55 años, con una incidencia del 1-3% en la población general y hasta el 50% en jugadores de tenis mayores de 30 años. La condición es bilateral en el 20% de los casos y es más frecuente en el brazo dominante.",
    "descripcionEn": "Lateral epicondylitis, commonly known as tennis elbow, is a degenerative tendinopathy affecting the forearm extensor tendons at their origin on the lateral epicondyle of the humerus, particularly the extensor carpi radialis brevis (ECRB) tendon. Despite its colloquial name, only 5-10% of diagnosed patients play tennis; the condition is much more prevalent in manual workers and racquet sport athletes in general. Current pathophysiology describes a process of angiofibroblastic tendinosis (collagen degeneration with fibroblastic hyperplasia and neovascularization) rather than true inflammatory tendinitis. It predominantly affects people aged 35-55, with an incidence of 1-3% in the general population and up to 50% in tennis players over 30 years old. The condition is bilateral in 20% of cases and is more common in the dominant arm.",
    "categoriaEs": "Lesión de tendón",
    "categoriaEn": "Tendon injury",
    "sintomasEs": [
      "Dolor en la cara lateral del codo que se irradia hacia el antebrazo",
      "Dolor que se agrava al agarrar objetos, girar pomos o dar la mano",
      "Debilidad progresiva en la fuerza de prensión",
      "Sensibilidad puntual a la palpación sobre el epicóndilo lateral",
      "Dolor al extensión resistida de la muñeca y del dedo medio (prueba de Cozen y prueba de Maudsley)",
      "Rigidez matutina en el codo que mejora con la actividad suave",
      "Dolor al levantar objetos con el brazo extendido y la palma hacia abajo",
      "Dificultad para realizar actividades cotidianas como verter líquidos o usar herramientas"
    ],
    "sintomasEn": [
      "Pain on the lateral aspect of the elbow radiating to the forearm",
      "Pain aggravated by gripping objects, turning doorknobs, or shaking hands",
      "Progressive weakness in grip strength",
      "Point tenderness on palpation over the lateral epicondyle",
      "Pain with resisted wrist extension and middle finger extension (Cozen's test and Maudsley's test)",
      "Morning stiffness in the elbow that improves with gentle activity",
      "Pain when lifting objects with the arm extended and palm facing down",
      "Difficulty performing daily activities such as pouring liquids or using tools"
    ],
    "causasEs": "La epicondilitis lateral se debe a microtraumatismos acumulativos por contracciones excéntricas repetitivas de los extensores de la muñeca. En el tenis, se asocia con técnica incorrecta del revés (golpear con el codo adelantado), raqueta con grip inadecuado, tensión excesiva del encordado y vibración transmitida. En el ámbito laboral, se asocia con movimientos repetitivos de prensión, torsión y extensión de la muñeca (uso de destornilladores, ratón de computadora, líneas de ensamblaje). Los factores de riesgo incluyen: edad 35-55 años, ocupaciones con movimientos repetitivos del antebrazo, tabaquismo (compromete la vascularización tendinosa), obesidad, diabetes mellitus y uso de fluoroquinolonas.",
    "causasEn": "Lateral epicondylitis results from cumulative microtrauma due to repetitive eccentric contractions of the wrist extensors. In tennis, it is associated with incorrect backhand technique (hitting with the elbow forward), racquet with inadequate grip size, excessive string tension, and transmitted vibration. In occupational settings, it is associated with repetitive gripping, twisting, and wrist extension movements (screwdriver use, computer mouse, assembly lines). Risk factors include: age 35-55 years, occupations with repetitive forearm movements, smoking (compromises tendon vascularization), obesity, diabetes mellitus, and fluoroquinolone use.",
    "diagnosticoEs": "El diagnóstico es primariamente clínico basado en la localización del dolor y pruebas provocativas. La prueba de Cozen (extensión resistida de la muñeca con el codo extendido) y la prueba de Mill (estiramiento pasivo de los extensores con el puño cerrado) son las más utilizadas. La prueba de Maudsley (extensión resistida del dedo medio) aísla el ECRB. La ecografía musculoesquelética muestra engrosamiento del tendón, hipoecogenicidad, desgarros parciales y neovascularización en Doppler. La resonancia magnética se reserva para casos refractarios o atípicos, mostrando señal aumentada en T2 en el origen del ECRB. Es esencial realizar diagnóstico diferencial con síndrome del túnel radial, plica sinovial, inestabilidad del codo, radiculopatía cervical C6-C7 y artrosis radiocapitelar.",
    "diagnosticoEn": "Diagnosis is primarily clinical based on pain location and provocative tests. Cozen's test (resisted wrist extension with the elbow extended) and Mill's test (passive stretching of extensors with a clenched fist) are the most commonly used. Maudsley's test (resisted middle finger extension) isolates the ECRB. Musculoskeletal ultrasound shows tendon thickening, hypoechogenicity, partial tears, and neovascularization on Doppler. MRI is reserved for refractory or atypical cases, showing increased T2 signal at the ECRB origin. It is essential to perform differential diagnosis with radial tunnel syndrome, synovial plica, elbow instability, C6-C7 cervical radiculopathy, and radiocapitellar osteoarthritis.",
    "tratamientoEs": "El tratamiento de primera línea es conservador y tiene éxito en el 85-90% de los casos en un plazo de 6-12 meses. Incluye: modificación de actividades y ergonomía laboral/deportiva, uso de una órtesis contrafuerza (banda epicondílea) colocada 2-3 cm distal al epicóndilo, programa de ejercicios excéntricos de Tyler (flexbar) realizados diariamente durante 6-8 semanas, crioterapia post-actividad, AINEs tópicos (diclofenaco gel) como primera opción farmacológica. Las inyecciones de corticosteroides proporcionan alivio a corto plazo (4-6 semanas) pero tienen peores resultados a largo plazo y mayor tasa de recurrencia comparado con fisioterapia sola. Las terapias de segunda línea incluyen: inyecciones de PRP, proloterapia, terapia de ondas de choque y aguja seca o punción percutánea tenotómica con ecografía (TENEX). La cirugía (desbridamiento artroscópico o abierto del ECRB, procedimiento de Nirschl) se considera tras 6-12 meses de fracaso conservador.",
    "tratamientoEn": "First-line treatment is conservative and is successful in 85-90% of cases within 6-12 months. It includes: activity modification and workplace/sports ergonomics, use of a counterforce brace (epicondylar band) placed 2-3 cm distal to the epicondyle, Tyler twist eccentric exercise program (flexbar) performed daily for 6-8 weeks, post-activity cryotherapy, topical NSAIDs (diclofenac gel) as first-line pharmacological option. Corticosteroid injections provide short-term relief (4-6 weeks) but have worse long-term outcomes and higher recurrence rates compared to physical therapy alone. Second-line therapies include: PRP injections, prolotherapy, shockwave therapy, and dry needling or percutaneous ultrasonic tenotomy (TENEX). Surgery (arthroscopic or open ECRB debridement, Nirschl procedure) is considered after 6-12 months of conservative failure.",
    "rehabilitacionEs": "La rehabilitación se basa en la progresión de cargas tendinosas. Fase 1 (0-2 semanas): reposo relativo, crioterapia, ejercicios isométricos de extensión de muñeca (5 series de 45 segundos al 70% de contracción máxima), movilidad suave del codo y muñeca. Fase 2 (2-6 semanas): ejercicios excéntricos con flexbar de Tyler (3 series de 15 repeticiones, 1-2 veces al día), fortalecimiento isotónico progresivo de extensores y flexores de muñeca y pronadores/supinadores. Fase 3 (6-10 semanas): ejercicios de fuerza progresiva con pesas ligeras, fortalecimiento de la cadena cinética (hombro, escápula, core), inicio de actividades funcionales simuladas. Fase 4 (10-16 semanas): retorno progresivo al deporte o actividad laboral con técnica corregida, programa de mantenimiento excéntrico 2-3 veces por semana. La ergonomía correcta y la técnica deportiva adecuada son componentes esenciales de la rehabilitación.",
    "rehabilitacionEn": "Rehabilitation is based on progressive tendon loading. Phase 1 (0-2 weeks): relative rest, cryotherapy, isometric wrist extension exercises (5 sets of 45 seconds at 70% maximum contraction), gentle elbow and wrist mobility. Phase 2 (2-6 weeks): Tyler twist eccentric exercises with flexbar (3 sets of 15 repetitions, 1-2 times daily), progressive isotonic strengthening of wrist extensors and flexors, and pronators/supinators. Phase 3 (6-10 weeks): progressive strength exercises with light weights, kinetic chain strengthening (shoulder, scapula, core), initiation of simulated functional activities. Phase 4 (10-16 weeks): progressive return to sport or occupational activity with corrected technique, eccentric maintenance program 2-3 times per week. Correct ergonomics and proper sports technique are essential components of rehabilitation.",
    "prevencionEs": "La prevención en deportistas de raqueta incluye: técnica correcta del revés (uso de revés a dos manos o golpear con la muñeca firme), selección apropiada de raqueta (tamaño de grip correcto, raqueta con buena absorción de vibraciones), tensión de encordado moderada, acondicionamiento muscular pretemporada de los extensores del antebrazo, calentamiento adecuado y estiramientos antes y después de jugar. En el ámbito laboral: diseño ergonómico del puesto de trabajo, herramientas con empuñaduras acolchadas y de tamaño adecuado, rotación de tareas para evitar movimientos repetitivos prolongados, pausas activas regulares y fortalecimiento preventivo de la musculatura del antebrazo.",
    "prevencionEn": "Prevention in racquet sport athletes includes: correct backhand technique (use of two-handed backhand or hitting with a firm wrist), appropriate racquet selection (correct grip size, racquet with good vibration absorption), moderate string tension, pre-season muscular conditioning of forearm extensors, adequate warm-up and stretching before and after playing. In the occupational setting: ergonomic workstation design, tools with cushioned and appropriately sized grips, task rotation to avoid prolonged repetitive movements, regular active breaks, and preventive forearm musculature strengthening.",
    "tiempoRecuperacionEs": "El 85-90% de los pacientes mejoran con tratamiento conservador en 6-12 meses. Los casos leves pueden resolver en 6-8 semanas con ejercicios excéntricos y modificación de actividades. La recuperación post-quirúrgica requiere 3-6 meses para retorno a actividades deportivas completas. La tasa de recurrencia es del 8-15%, siendo mayor si no se corrigen los factores biomecánicos y ergonómicos contribuyentes.",
    "tiempoRecuperacionEn": "85-90% of patients improve with conservative treatment within 6-12 months. Mild cases may resolve in 6-8 weeks with eccentric exercises and activity modification. Post-surgical recovery requires 3-6 months for return to full sports activities. The recurrence rate is 8-15%, being higher if contributing biomechanical and ergonomic factors are not corrected."
  },
  {
    "id": "lesion-manguito-rotador",
    "nombreEs": "Lesión del Manguito Rotador",
    "nombreEn": "Rotator Cuff Injury",
    "descripcionEs": "La lesión del manguito rotador abarca un espectro de patologías que afectan al grupo de cuatro músculos y sus tendones (supraespinoso, infraespinoso, redondo menor y subescapular) que estabilizan dinámicamente la articulación glenohumeral y permiten los movimientos de rotación y elevación del hombro. El supraespinoso es el más frecuentemente afectado debido a su posición anatómica vulnerable en el espacio subacromial y su zona crítica de hipovascularización. Las lesiones varían desde la tendinopatía (tendinosis sin desgarro) y los desgarros parciales (superficie bursal, articular o intratendinosa) hasta los desgarros completos de espesor total que pueden involucrar uno o varios tendones. Esta patología es extraordinariamente prevalente: los estudios de RM en personas asintomáticas mayores de 60 años muestran desgarros del manguito en el 30-50% de los casos, lo que subraya la importancia de correlacionar los hallazgos de imagen con la clínica. En el contexto deportivo, es especialmente frecuente en atletas que realizan movimientos por encima de la cabeza (overhead athletes) como nadadores, tenistas, jugadores de voleibol, béisbol y lanzadores de jabalina.",
    "descripcionEn": "Rotator cuff injury encompasses a spectrum of pathologies affecting the group of four muscles and their tendons (supraspinatus, infraspinatus, teres minor, and subscapularis) that dynamically stabilize the glenohumeral joint and allow rotation and elevation movements of the shoulder. The supraspinatus is most frequently affected due to its vulnerable anatomical position in the subacromial space and its critical zone of hypovascularization. Injuries range from tendinopathy (tendinosis without tear) and partial tears (bursal surface, articular, or intratendinous) to full-thickness complete tears that may involve one or multiple tendons. This pathology is extraordinarily prevalent: MRI studies in asymptomatic individuals over 60 years show rotator cuff tears in 30-50% of cases, underscoring the importance of correlating imaging findings with clinical presentation. In the sports context, it is especially frequent in overhead athletes such as swimmers, tennis players, volleyball players, baseball players, and javelin throwers.",
    "categoriaEs": "Lesión articular",
    "categoriaEn": "Joint injury",
    "sintomasEs": [
      "Dolor en la cara lateral y anterior del hombro que se irradia hacia el deltoides",
      "Dolor nocturno que impide dormir sobre el hombro afectado",
      "Dolor al elevar el brazo por encima de la cabeza o en arco doloroso (60-120 grados de abducción)",
      "Debilidad progresiva para rotación externa y abducción del hombro",
      "Crepitación subacromial durante los movimientos del hombro",
      "Incapacidad para mantener el brazo elevado contra gravedad en desgarros completos",
      "Atrofia muscular visible de la fosa supraespinosa o infraespinosa en casos crónicos",
      "Dolor al alcanzar objetos a la espalda o al ponerse un abrigo"
    ],
    "sintomasEn": [
      "Pain on the lateral and anterior aspect of the shoulder radiating toward the deltoid",
      "Night pain preventing sleep on the affected shoulder",
      "Pain when raising the arm overhead or in a painful arc (60-120 degrees of abduction)",
      "Progressive weakness in external rotation and shoulder abduction",
      "Subacromial crepitation during shoulder movements",
      "Inability to maintain the arm elevated against gravity in complete tears",
      "Visible muscle atrophy of the supraspinous or infraspinous fossa in chronic cases",
      "Pain when reaching behind the back or putting on a coat"
    ],
    "causasEs": "Las lesiones del manguito rotador tienen una etiología multifactorial. Los factores extrínsecos incluyen: pinzamiento subacromial (compresión mecánica por el arco coracoacromial), sobrecarga repetitiva overhead (natación, tenis, béisbol), y traumatismos agudos (caídas sobre el brazo extendido o sobre el hombro, tracción brusca). Los factores intrínsecos incluyen: degeneración tendinosa relacionada con la edad, hipovascularización de la zona crítica del supraespinoso (1 cm proximal a la inserción), predisposición genética, tabaquismo, diabetes mellitus, hipercolesterolemia, morfología acromion tipo III (gancho) y laxitud capsular. En atletas jóvenes, predomina la inestabilidad glenohumeral subyacente como causa (pinzamiento interno).",
    "causasEn": "Rotator cuff injuries have a multifactorial etiology. Extrinsic factors include: subacromial impingement (mechanical compression by the coracoacromial arch), repetitive overhead loading (swimming, tennis, baseball), and acute trauma (falls on an outstretched arm or onto the shoulder, sudden traction). Intrinsic factors include: age-related tendon degeneration, hypovascularization of the supraspinatus critical zone (1 cm proximal to insertion), genetic predisposition, smoking, diabetes mellitus, hypercholesterolemia, type III acromion morphology (hook), and capsular laxity. In young athletes, underlying glenohumeral instability predominates as the cause (internal impingement).",
    "diagnosticoEs": "El examen físico incluye pruebas específicas para cada tendón: prueba de Jobe/Empty Can (supraespinoso), prueba de rotación externa resistida (infraespinoso), prueba de Belly Press y Lift-off de Gerber (subescapular), y prueba de Horn Blower (redondo menor). Las pruebas de pinzamiento de Neer y Hawkins-Kennedy evalúan la compresión subacromial. Las radiografías pueden mostrar ascenso de la cabeza humeral, esclerosis del troquíter y osteofitos acromiales en casos crónicos. La ecografía musculoesquelética dinámica tiene una sensibilidad del 90-95% para desgarros completos y es la primera línea de imagen en muchos centros. La resonancia magnética es el estándar de oro para evaluación completa, permitiendo clasificar el desgarro según tamaño (pequeño <1 cm, mediano 1-3 cm, grande 3-5 cm, masivo >5 cm), localización, retracción tendinosa y degeneración grasa muscular (clasificación de Goutallier), factores determinantes para la planificación quirúrgica.",
    "diagnosticoEn": "Physical examination includes tests specific to each tendon: Jobe/Empty Can test (supraspinatus), resisted external rotation test (infraspinatus), Belly Press and Gerber Lift-off test (subscapularis), and Horn Blower test (teres minor). Neer and Hawkins-Kennedy impingement tests assess subacromial compression. X-rays may show humeral head ascent, greater tuberosity sclerosis, and acromial osteophytes in chronic cases. Dynamic musculoskeletal ultrasound has 90-95% sensitivity for complete tears and is the first-line imaging in many centers. MRI is the gold standard for comprehensive evaluation, allowing tear classification by size (small <1 cm, medium 1-3 cm, large 3-5 cm, massive >5 cm), location, tendon retraction, and muscle fatty degeneration (Goutallier classification), factors that are determinant for surgical planning.",
    "tratamientoEs": "El tratamiento depende del tipo de lesión, la edad y el nivel de actividad del paciente. Tratamiento conservador (indicado para tendinopatía, desgarros parciales y desgarros completos en pacientes mayores de baja demanda): fisioterapia enfocada en fortalecimiento del manguito rotador y estabilizadores escapulares, AINEs orales o tópicos, inyección subacromial de corticosteroides (máximo 3 por año), modificación de actividades overhead. Tratamiento quirúrgico (indicado para desgarros agudos traumáticos en pacientes jóvenes/activos, desgarros completos con debilidad funcional, fracaso del tratamiento conservador tras 3-6 meses): reparación artroscópica del manguito rotador (técnica de fila simple o doble), con o sin acromioplastia descompresiva. Para desgarros masivos irreparables: transferencias tendinosas (dorsal ancho, pectoral mayor), reconstrucción capsular superior con injerto dérmico, o artroplastia inversa de hombro en pacientes mayores con artropatía del manguito.",
    "tratamientoEn": "Treatment depends on the type of injury, age, and activity level of the patient. Conservative treatment (indicated for tendinopathy, partial tears, and complete tears in older, low-demand patients): physical therapy focused on rotator cuff and scapular stabilizer strengthening, oral or topical NSAIDs, subacromial corticosteroid injection (maximum 3 per year), modification of overhead activities. Surgical treatment (indicated for acute traumatic tears in young/active patients, complete tears with functional weakness, failure of conservative treatment after 3-6 months): arthroscopic rotator cuff repair (single-row or double-row technique), with or without decompressive acromioplasty. For massive irreparable tears: tendon transfers (latissimus dorsi, pectoralis major), superior capsular reconstruction with dermal graft, or reverse shoulder arthroplasty in older patients with cuff tear arthropathy.",
    "rehabilitacionEs": "La rehabilitación post-reparación artroscópica es prolongada y cautelosa. Fase 1 (0-6 semanas): inmovilización con cabestrillo con almohada de abducción, movimientos pendulares de Codman, ejercicios de movilidad pasiva asistida del hombro (flexión hasta 120 grados, rotación externa hasta 30 grados), fortalecimiento de mano, muñeca y codo. Fase 2 (6-12 semanas): retiro gradual del cabestrillo, movilidad activa asistida progresiva, inicio de rotación externa activa y elevación activa, isométricos suaves del manguito rotador. Fase 3 (12-16 semanas): fortalecimiento activo resistido del manguito rotador con bandas elásticas, ejercicios de estabilización escapular, rango de movimiento completo activo. Fase 4 (4-6 meses): fortalecimiento avanzado, ejercicios pliométricos del hombro, ejercicios de cadena cinética. Fase 5 (6-9 meses): programa de retorno al deporte específico con progresión gradual de intensidad y volumen overhead. La recuperación completa para deportes overhead competitivos puede requerir 9-12 meses.",
    "rehabilitacionEn": "Post-arthroscopic repair rehabilitation is prolonged and cautious. Phase 1 (0-6 weeks): immobilization with sling and abduction pillow, Codman pendulum exercises, passive assisted shoulder mobility exercises (flexion to 120 degrees, external rotation to 30 degrees), hand, wrist, and elbow strengthening. Phase 2 (6-12 weeks): gradual sling removal, progressive active-assisted mobility, initiation of active external rotation and elevation, gentle rotator cuff isometrics. Phase 3 (12-16 weeks): active resisted rotator cuff strengthening with resistance bands, scapular stabilization exercises, full active range of motion. Phase 4 (4-6 months): advanced strengthening, shoulder plyometric exercises, kinetic chain exercises. Phase 5 (6-9 months): sport-specific return-to-sport program with gradual progression of overhead intensity and volume. Complete recovery for competitive overhead sports may require 9-12 months.",
    "prevencionEs": "La prevención en atletas overhead incluye: programa de fortalecimiento preventivo del manguito rotador y estabilizadores escapulares (ejercicios de Thrower's Ten o programa de fortalecimiento del hombro de ASMI), calentamiento dinámico específico del hombro antes de la actividad, control del volumen de lanzamientos/servicios (conteo de lanzamientos en béisbol, reglas de pitch count para jóvenes), técnica deportiva correcta con participación adecuada de la cadena cinética (uso de piernas, tronco y escápula para generar potencia), mantenimiento de la flexibilidad capsular posterior (estiramiento del durmiente), monitorización de la fatiga (la mecánica alterada por fatiga predispone a lesiones), y períodos adecuados de descanso entre temporadas (evitar la especialización temprana y la práctica durante todo el año del mismo deporte overhead).",
    "prevencionEn": "Prevention in overhead athletes includes: preventive rotator cuff and scapular stabilizer strengthening program (Thrower's Ten exercises or ASMI shoulder strengthening program), specific dynamic shoulder warm-up before activity, control of throwing/serving volume (pitch counting in baseball, youth pitch count rules), correct sports technique with adequate kinetic chain participation (use of legs, trunk, and scapula to generate power), maintenance of posterior capsular flexibility (sleeper stretch), fatigue monitoring (fatigue-altered mechanics predispose to injuries), and adequate rest periods between seasons (avoiding early specialization and year-round practice of the same overhead sport).",
    "tiempoRecuperacionEs": "Tendinopatía y pinzamiento: 4-8 semanas con fisioterapia. Desgarro parcial: 3-6 meses con tratamiento conservador. Reparación artroscópica de desgarro pequeño-mediano: 4-6 meses para actividades de la vida diaria, 9-12 meses para retorno deportivo overhead competitivo. Desgarros masivos reparados: 6-9 meses para actividades funcionales, retorno deportivo competitivo incierto. La tasa de re-rotura tras reparación artroscópica varía del 10-40% dependiendo del tamaño del desgarro, la calidad del tejido y la edad del paciente.",
    "tiempoRecuperacionEn": "Tendinopathy and impingement: 4-8 weeks with physical therapy. Partial tear: 3-6 months with conservative treatment. Arthroscopic repair of small-medium tear: 4-6 months for daily living activities, 9-12 months for competitive overhead return to sport. Repaired massive tears: 6-9 months for functional activities, competitive return to sport uncertain. Re-tear rate after arthroscopic repair varies from 10-40% depending on tear size, tissue quality, and patient age."
  }
]`);

export function buscarMedicinaDeportiva(termino: string): MedicinaDeportivaEntry[] {
  const t = termino.toLowerCase();
  return MEDICINA_DEPORTIVA_ENTRIES.filter(e =>
    e.nombreEs.toLowerCase().includes(t) ||
    e.nombreEn.toLowerCase().includes(t) ||
    e.descripcionEs.toLowerCase().includes(t) ||
    e.descripcionEn.toLowerCase().includes(t)
  );
}

export function getMedicinaDeportivaById(id: string): MedicinaDeportivaEntry | undefined {
  return MEDICINA_DEPORTIVA_ENTRIES.find(e => e.id === id);
}

export function getMedicinaDeportivaPorCategoria(categoria: string): MedicinaDeportivaEntry[] {
  const c = categoria.toLowerCase();
  return MEDICINA_DEPORTIVA_ENTRIES.filter(e =>
    e.categoriaEs.toLowerCase().includes(c) ||
    e.categoriaEn.toLowerCase().includes(c)
  );
}
