/**
 * Family Education - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const familyEducationContent: EducationalContent = {
  id: 'mental-health-family-education',
  type: 'topic',
  name: 'Family Education',
  alternateNames: ['Family Psychoeducation', 'Supporting a Family Member', 'Caregiver Education'],

  levels: {
    1: { level: 1, summary: 'Families play a crucial role in supporting loved ones with mental health conditions. Understanding the condition, learning communication skills, and practicing self-care helps both the family member and the person with the condition.', explanation: '**Supporting a Family Member with Mental Health Challenges**\n\n**Understanding Helps:**\n- Mental health conditions are medical conditions\n- They are not anyone\'s fault\n- They are treatable\n- Recovery is possible\n\n**How You Can Help:**\n\n*Learn About the Condition:*\n- Understand symptoms and treatment\n- Know warning signs of relapse\n- Learn about medications and their effects\n\n*Communicate Effectively:*\n- Listen without judgment\n- Express concern with "I" statements\n- Avoid criticism and blame\n- Be patient\n\n*Support Treatment:*\n- Encourage professional help\n- Help with appointments if needed\n- Support medication adherence\n- Participate in family therapy if offered\n\n*Set Appropriate Boundaries:*\n- You cannot control their recovery\n- It is okay to have limits\n- Balance support with your own needs\n\n**Take Care of Yourself:**\n- Your well-being matters too\n- Seek support (support groups, therapy)\n- Maintain your own health\n- Accept help from others\n\n**Crisis Planning:**\n- Know warning signs\n- Have emergency numbers ready\n- Create a plan together when possible', keyTerms: [{ term: 'psychoeducation', definition: 'Education about mental health conditions and treatment' }, { term: 'caregiver', definition: 'Person providing support to someone with a health condition' }], analogies: ['Supporting someone with mental illness is like helping someone climb a mountain - you can encourage and assist, but they must do the climbing.'], examples: [] },
    2: { level: 2, summary: 'Family psychoeducation is an evidence-based intervention that reduces relapse in schizophrenia and improves outcomes in mood disorders. Components include education about illness, communication training, problem-solving, and crisis management.', explanation: '**Family Psychoeducation:**\n\n*Evidence:*\n- Reduces relapse in schizophrenia by ~50%\n- Improves outcomes in bipolar disorder\n- Benefits in depression, eating disorders\n- Recommended in treatment guidelines\n\n*Core Components:*\n- Education about the illness\n- Communication skills training\n- Problem-solving training\n- Crisis planning\n- Stress management\n\n**Educational Content:**\n\n*About the Condition:*\n- Symptoms and course\n- Treatment options\n- Role of medication\n- Warning signs of relapse\n\n*About Recovery:*\n- Realistic expectations\n- Timeline for improvement\n- Importance of ongoing treatment\n- Hope and resilience\n\n**Communication Training:**\n\n*Express Positive Feelings:*\n- Appreciation and praise\n- Specific positive feedback\n\n*Active Listening:*\n- Reflective listening\n- Asking clarifying questions\n\n*Making Requests:*\n- Specific, positive requests\n- Avoid criticism and demands\n\n*Expressing Negative Feelings:*\n- "I" statements\n- Focusing on behavior, not character\n\n**Expressed Emotion:**\n\n*High EE Environment:*\n- Criticism\n- Hostility\n- Emotional over-involvement\n\n*Associated with Higher Relapse:*\n- Family intervention reduces EE\n- Improves family climate\n\n**Self-Care for Families:**\n- Caregiver burden is real\n- Support groups (NAMI Family-to-Family)\n- Individual therapy if needed\n- Respite when possible', keyTerms: [{ term: 'expressed emotion', definition: 'Level of criticism, hostility, and over-involvement in family environment' }, { term: 'high EE', definition: 'High expressed emotion environment associated with increased relapse' }, { term: 'NAMI', definition: 'National Alliance on Mental Illness - provides family support and education' }], analogies: [] },
    3: { level: 3, summary: 'Family psychoeducation programs (McFarlane, Miklowitz, Falloon models) are evidence-based interventions. Mechanisms include reduced expressed emotion, improved communication, enhanced problem-solving, and medication adherence. Implementation requires trained clinicians and appropriate format selection.', explanation: '**Evidence-Based Models:**\n\n*McFarlane Multi-Family Groups (Schizophrenia):*\n- Multiple families together\n- Psychoeducation + problem-solving\n- 2+ years recommended\n- Reduces relapse ~50%\n\n*Falloon Behavioral Family Therapy:*\n- Single-family format\n- Communication training emphasis\n- Home-based options\n\n*Miklowitz Family-Focused Therapy (Bipolar):*\n- 21 sessions over 9 months\n- Psychoeducation + communication + problem-solving\n- Reduces relapse, improves medication adherence\n\n**Mechanisms:**\n\n*Expressed Emotion Reduction:*\n- Reframe symptoms as illness\n- Reduce blame and criticism\n- Appropriate expectations\n- Emotional distance (healthy)\n\n*Communication:*\n- Clarity\n- Reduced conflict\n- Better problem resolution\n\n*Problem-Solving:*\n- Structured approach\n- Family collaboration\n- Practical solutions\n\n*Medication Adherence:*\n- Family support for treatment\n- Understanding medication role\n- Side effect management\n\n**Implementation:**\n\n*Formats:*\n- Single-family\n- Multi-family groups\n- Brief vs extended\n- In-clinic vs home-based\n\n*Training:*\n- Specific training needed\n- Fidelity matters\n- Ongoing supervision\n\n**Specific Conditions:**\n\n*Schizophrenia:*\n- Strongest evidence\n- Multi-family groups effective\n- Long-term engagement\n\n*Bipolar Disorder:*\n- FFT evidence-based\n- Adjunct to medication\n\n*Eating Disorders:*\n- FBT for adolescents\n- Family involvement essential', keyTerms: [{ term: 'McFarlane model', definition: 'Multi-family group psychoeducation for schizophrenia' }, { term: 'FFT', definition: 'Family-Focused Therapy for bipolar disorder' }, { term: 'FBT', definition: 'Family-Based Treatment for eating disorders' }], clinicalNotes: 'Family psychoeducation is guideline-recommended for schizophrenia and bipolar. Multi-family groups are cost-effective. Single-family appropriate for some. Reduce expressed emotion. Address caregiver burden.' },
    4: { level: 4, summary: 'Family intervention mechanisms involve stress-vulnerability interaction, communication pattern modification, and social network strengthening. Implementation requires attention to cultural adaptation, diverse family structures, and scalability. Caregiver interventions address burden and improve family outcomes.', explanation: '**Theoretical Framework:**\n\n*Stress-Vulnerability Model:*\n- Biological vulnerability\n- Environmental stress triggers\n- Family can reduce stress\n- Protective factors enhanced\n\n*Communication Patterns:*\n- Affective style assessment\n- Behavioral change targets\n- Skill generalization\n\n**Research Evidence:**\n\n*Meta-Analyses:*\n- Schizophrenia: NNT ~7 for relapse prevention\n- Effect maintained at follow-up\n- Multi-family groups cost-effective\n- Benefits across cultures\n\n*Mediators:*\n- Expressed emotion reduction\n- Communication improvement\n- Problem-solving\n- Knowledge increase\n\n**Cultural Adaptation:**\n\n*Considerations:*\n- Family structure varies\n- Stigma varies culturally\n- Communication norms differ\n- Language access\n\n*Approaches:*\n- Cultural consultation\n- Adapted materials\n- Diverse facilitators\n- Community partnership\n\n**Caregiver Interventions:**\n\n*Caregiver Burden:*\n- Emotional, physical, financial\n- Own mental health effects\n- Reduced quality of life\n\n*Interventions:*\n- Support groups\n- Individual therapy\n- Respite services\n- Care coordination\n\n**Implementation Challenges:**\n\n*Barriers:*\n- Family engagement\n- Clinician training\n- Time and resources\n- System support\n\n*Solutions:*\n- Flexible scheduling\n- Telehealth options\n- Peer-led components\n- Integration with clinical care', keyTerms: [{ term: 'stress-vulnerability model', definition: 'Framework where stress interacts with biological vulnerability to trigger episodes' }, { term: 'caregiver burden', definition: 'Physical, emotional, and financial strain on caregivers' }, { term: 'NNT', definition: 'Number needed to treat - here, families needed to prevent one relapse' }], clinicalNotes: 'Family intervention is evidence-based and underutilized. Address cultural factors. Caregiver well-being affects patient outcomes. Multiple formats can work. Training and fidelity important.' },
    5: { level: 5, summary: 'Contemporary family intervention research explores digital delivery, integration with coordinated specialty care, and precision approaches. Peer family support models expand reach. Implementation science addresses dissemination gaps.', explanation: '**Research Directions:**\n\n*Digital Delivery:*\n- Online psychoeducation\n- Video-based family sessions\n- App-supported skills practice\n- Accessibility improvement\n\n*First-Episode Integration:*\n- Part of coordinated specialty care\n- Early family engagement\n- Better long-term outcomes\n\n**Precision Approaches:**\n\n*Matching:*\n- Which families need most intensive?\n- Stepped care models\n- Cultural matching\n\n*Personalization:*\n- Family-specific targets\n- Adaptive interventions\n\n**Peer Family Support:**\n\n*NAMI Programs:*\n- Family-to-Family\n- Peer-led education\n- Support groups\n- Expanding reach\n\n*Integration:*\n- Peer + professional\n- Community-based\n- Sustainable models\n\n**Implementation Science:**\n\n*Dissemination:*\n- Training programs\n- Fidelity measurement\n- Sustainability\n- System integration\n\n*Barriers:*\n- Reimbursement\n- Time constraints\n- Family engagement\n- Workforce capacity\n\n**Global Perspectives:**\n\n*LMIC Applications:*\n- Task-sharing models\n- Community health workers\n- Adapted content\n- Demonstrated effectiveness\n\n**Emerging Areas:**\n- Digital phenotyping of family environment\n- Genetic counseling integration\n- Trauma-informed family approaches\n- Lifespan considerations', keyTerms: [{ term: 'coordinated specialty care', definition: 'Team-based first-episode psychosis treatment including family' }, { term: 'Family-to-Family', definition: 'NAMI peer-led family education program' }, { term: 'task-sharing', definition: 'Using non-specialists to deliver interventions' }], clinicalNotes: 'Family intervention remains underutilized despite evidence. Digital options expanding access. Peer programs complement professional services. Early engagement in first episode important. Implementation requires system support.' },
  },

  media: [],
  citations: [{ id: 'family-intervention', type: 'article', title: 'Family Intervention for Schizophrenia', authors: ['McFarlane WR'], source: 'Various publications' }],
  crossReferences: [{ targetId: 'mental-health-schizophrenia', targetType: 'condition', relationship: 'see-also', label: 'Schizophrenia' }],
  tags: { systems: ['nervous'], topics: ['mental-health', 'family', 'support'], keywords: ['family education', 'psychoeducation', 'caregiver', 'family therapy'], clinicalRelevance: 'high', examRelevance: { usmle: true, nbme: true, shelf: ['psychiatry'] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default familyEducationContent;
