/**
 * Peer Support - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const peerSupportContent: EducationalContent = {
  id: 'mental-health-peer-support',
  type: 'topic',
  name: 'Peer Support',
  alternateNames: ['Peer Specialists', 'Peer Counselors', 'Lived Experience Support'],

  levels: {
    1: { level: 1, summary: 'Peer support is help provided by someone who has experienced similar mental health challenges. Peer supporters offer unique understanding, hope, and practical guidance based on their own recovery journey.', explanation: '**What Is Peer Support?**\n\nPeer support is help from someone who has lived experience with mental health challenges. They have been through similar struggles and can offer unique understanding.\n\n**What Peer Supporters Offer:**\n- Lived experience and understanding\n- Hope through example\n- Practical recovery strategies\n- Emotional support\n- Navigation help\n- Reduced sense of isolation\n\n**Types of Peer Support:**\n\n*Informal:*\n- Friends with shared experiences\n- Online communities\n- Support groups\n\n*Formal:*\n- Trained peer specialists\n- Certified peer counselors\n- Part of treatment teams\n\n**Why It Helps:**\n- "Someone who truly gets it"\n- Shows recovery is possible\n- Less power imbalance than with professionals\n- Different perspective\n- Practical tips from experience\n\n**Where to Find:**\n- Mental health treatment programs\n- Community mental health centers\n- Peer-run organizations\n- Warm lines\n- Online platforms\n\nPeer support complements professional treatment with the unique perspective of lived experience.', keyTerms: [{ term: 'peer support', definition: 'Help from someone with similar lived experience' }, { term: 'peer specialist', definition: 'Trained person with lived experience who provides support' }, { term: 'lived experience', definition: 'Personal history with mental health challenges' }], analogies: ['Peer support is like having a guide who has walked the same difficult path before you.'], examples: [] },
    2: { level: 2, summary: 'Peer support services utilize the expertise of people with lived experience. Peer specialists are trained and often certified professionals working alongside clinical staff. Evidence shows benefits including engagement, hope, and reduced hospitalization.', explanation: '**Peer Support Services:**\n\n*Peer Specialists:*\n- Trained individuals with lived experience\n- Certified in most states\n- Work in treatment settings\n- Multiple roles\n\n*Services Provided:*\n- One-on-one support\n- Group facilitation\n- System navigation\n- Advocacy\n- Crisis support\n- Wellness planning\n\n**Evidence Base:**\n\n*Benefits:*\n- Improved engagement in treatment\n- Increased hope and empowerment\n- Reduced hospitalizations\n- Better symptom outcomes\n- Improved social support\n- Cost-effective\n\n*For Peer Specialists:*\n- Meaningful employment\n- Supports own recovery\n- Career pathway\n\n**Core Values:**\n\n*SAMHSA Core Competencies:*\n- Recovery-oriented\n- Person-centered\n- Voluntary\n- Relationship-focused\n- Trauma-informed\n\n**Settings:**\n- Community mental health centers\n- Hospitals\n- Crisis services\n- Outpatient clinics\n- Peer-run organizations\n- Primary care (emerging)\n\n**Training and Certification:**\n- State certification programs\n- Competency-based training\n- Continuing education\n- Supervision requirements', keyTerms: [{ term: 'peer specialist certification', definition: 'State credential for trained peer supporters' }, { term: 'warm line', definition: 'Peer-staffed support line for non-crisis support' }, { term: 'peer-run organization', definition: 'Service organization operated by people with lived experience' }], analogies: [] },
    3: { level: 3, summary: 'Peer support is an evidence-based service with defined competencies and certification. Mechanisms include hope, role modeling, social support, and experiential knowledge. Integration into clinical teams requires attention to role clarity and organizational support.', explanation: '**Competencies (SAMHSA):**\n\n1. Engages peers in collaborative relationships\n2. Provides support\n3. Shares lived experience\n4. Personalizes peer support\n5. Supports recovery planning\n6. Links to resources\n7. Provides information\n8. Develops leadership\n9. Supports crisis prevention\n10. Addresses trauma\n11. Values communication\n12. Promotes wellness\n\n**Mechanisms:**\n\n*Hope:*\n- Role modeling recovery\n- Tangible evidence of possibility\n- Reduced hopelessness\n\n*Experiential Knowledge:*\n- Insider understanding\n- Practical strategies\n- System navigation\n\n*Social Support:*\n- Mutual relationship\n- Reduced isolation\n- Belonging\n\n*Empowerment:*\n- Self-determination support\n- Advocacy modeling\n- Strength-based approach\n\n**Integration Challenges:**\n\n*Role Clarity:*\n- Distinguishing from clinical roles\n- Scope of practice\n- Boundaries\n\n*Organizational:*\n- Staff attitudes\n- Supervision structures\n- Compensation parity\n- Career pathways\n\n*Personal:*\n- Managing own recovery\n- Avoiding overidentification\n- Self-care\n\n**Quality Assurance:**\n- Supervision models\n- Fidelity measures\n- Outcome tracking\n- Continuing education', keyTerms: [{ term: 'experiential knowledge', definition: 'Knowledge gained through personal experience with mental health challenges' }, { term: 'recovery capital', definition: 'Resources supporting recovery including social, physical, human, cultural' }, { term: 'scope of practice', definition: 'Defined boundaries of peer specialist role' }], clinicalNotes: 'Peer specialists are part of evidence-based care. Role clarity important for integration. Supervision structures needed. Peer perspective complements clinical perspective. Address organizational culture.' },
    4: { level: 4, summary: 'Peer support services demonstrate effectiveness through multiple mechanisms including experiential sharing and hope. Implementation requires workforce development, organizational readiness, and sustainable financing. Research addresses optimization and diverse applications.', explanation: '**Evidence Synthesis:**\n\n*Systematic Reviews:*\n- Reduced hospitalizations\n- Improved engagement\n- Enhanced recovery outcomes\n- Cost-effectiveness\n\n*Limitations:*\n- Heterogeneous studies\n- Difficulty blinding\n- Various service models\n- Outcome measure variation\n\n**Mechanism Research:**\n\n*Unique Elements:*\n- Experiential knowledge\n- Mutual relationship (vs hierarchical)\n- Hope through modeling\n- Social identity\n\n*Overlap with Professional:*\n- Support and listening\n- Information provision\n- System navigation\n- Distinct but complementary\n\n**Implementation Factors:**\n\n*Workforce:*\n- Recruitment and retention\n- Training quality\n- Supervision\n- Career development\n- Compensation equity\n\n*Organizational:*\n- Leadership buy-in\n- Culture change\n- Integration structures\n- Clear protocols\n\n*Financing:*\n- Medicaid reimbursement (most states)\n- Grant funding\n- Sustainable models\n\n**Specialized Applications:**\n\n*Crisis Services:*\n- Peer respite\n- Mobile crisis teams\n- Warm lines\n\n*Specific Populations:*\n- Veterans\n- Young adults\n- Criminal justice involved\n- Cultural populations\n\n*Specific Conditions:*\n- Substance use (long history)\n- Serious mental illness\n- Eating disorders\n- Trauma survivors', keyTerms: [{ term: 'peer respite', definition: 'Peer-run short-term crisis alternative to hospitalization' }, { term: 'organizational readiness', definition: 'Preparedness of organization to integrate peer services' }, { term: 'Medicaid reimbursement', definition: 'State Medicaid payment for peer support services' }], clinicalNotes: 'Peer services reimbursable in most states via Medicaid. Organizational culture affects success. Specialized applications expanding. Research demonstrates value. Implementation support needed.' },
    5: { level: 5, summary: 'Contemporary peer support research addresses optimization, diverse applications, workforce development, and global scaling. Digital platforms and telehealth expand reach. Movement toward integrated care and policy recognition continues.', explanation: '**Research Directions:**\n\n*Optimization:*\n- What works best for whom?\n- Dosing and intensity\n- Comparative effectiveness\n- Active ingredients\n\n*New Applications:*\n- Primary care integration\n- Emergency departments\n- Forensic settings\n- Schools\n\n**Digital Peer Support:**\n\n*Platforms:*\n- Telehealth delivery\n- Online communities\n- App-based support\n- Text-based peer support\n\n*Research:*\n- Effectiveness comparison\n- Safety considerations\n- Optimal moderation\n- Reaching underserved\n\n**Workforce Development:**\n\n*Professionalization:*\n- National certification discussions\n- Competency standards\n- Educational pathways\n- Career ladders\n\n*Challenges:*\n- Compensation equity\n- Burnout prevention\n- Maintaining peer identity\n- Integration tensions\n\n**Global Perspectives:**\n\n*International:*\n- LMIC applications\n- WHO endorsement\n- Cultural adaptations\n- Task-sharing models\n\n*User/Survivor Movement:*\n- Advocacy influence\n- Policy change\n- Self-determination emphasis\n\n**Policy:**\n\n*Recognition:*\n- Federal endorsement\n- State Medicaid coverage\n- Accreditation standards\n- Workforce investment\n\n*Challenges:*\n- Sustainability\n- Quality assurance\n- Integration\n- Equity in access', keyTerms: [{ term: 'task-sharing', definition: 'Using non-specialists including peers to extend mental health workforce' }, { term: 'national certification', definition: 'Emerging national peer specialist credential' }, { term: 'WHO endorsement', definition: 'World Health Organization recognition of peer support value' }], clinicalNotes: 'Peer support is globally recognized. Digital options expanding. Workforce development ongoing. Policy support growing. Integration into healthcare systems continues.' },
  },

  media: [],
  citations: [{ id: 'peer-support-evidence', type: 'article', title: 'Peer Support in Mental Health Services', authors: ['Various'], source: 'Various publications' }],
  crossReferences: [{ targetId: 'mental-health-support-groups', targetType: 'topic', relationship: 'related', label: 'Support Groups' }],
  tags: { systems: ['nervous'], topics: ['mental-health', 'support'], keywords: ['peer support', 'peer specialist', 'lived experience', 'recovery'], clinicalRelevance: 'medium', examRelevance: { usmle: false, nbme: false, shelf: [] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default peerSupportContent;
