/**
 * Support Groups - Patient Education Content
 */

import { EducationalContent } from '../../types';

export const supportGroupsContent: EducationalContent = {
  id: 'mental-health-support-groups',
  type: 'topic',
  name: 'Support Groups',
  alternateNames: ['Peer Support', 'Self-Help Groups', 'Mutual Support'],

  levels: {
    1: { level: 1, summary: 'Support groups bring together people facing similar challenges to share experiences and provide mutual support. They can be powerful complements to professional treatment.', explanation: '**What Are Support Groups?**\n\nSupport groups are gatherings of people who share similar experiences or challenges. Members support each other through sharing, listening, and understanding.\n\n**Benefits:**\n- You are not alone\n- Learn from others\' experiences\n- Give and receive support\n- Practical tips and resources\n- Reduced stigma\n- Hope from seeing others\' recovery\n\n**Types of Groups:**\n\n*Condition-Specific:*\n- Depression, anxiety, bipolar\n- PTSD, OCD\n- Addiction recovery (AA, NA)\n- Grief support\n\n*Population-Specific:*\n- Veterans\n- LGBTQ+\n- Specific age groups\n- Family members/caregivers\n\n**Formats:**\n- In-person meetings\n- Online/virtual groups\n- Phone-based support\n\n**Finding Groups:**\n- Ask your therapist or doctor\n- NAMI (National Alliance on Mental Illness)\n- DBSA (Depression and Bipolar Support Alliance)\n- Hospitals and community centers\n- Online searches\n\n**What to Expect:**\n- Shared experiences and feelings\n- Confidentiality\n- No pressure to share\n- Peer-led or professionally facilitated\n- Supportive environment\n\nSupport groups complement but do not replace professional treatment.', keyTerms: [{ term: 'support group', definition: 'Gathering of people with shared experiences for mutual support' }, { term: 'peer support', definition: 'Support from others with similar lived experience' }], analogies: ['A support group is like finding your tribe - people who truly understand.'], examples: [] },
    2: { level: 2, summary: 'Support groups provide mutual aid through shared experience. Types include condition-specific, 12-step, and peer-led programs. Evidence supports their role as treatment adjuncts. Key therapeutic factors include universality, hope, and experiential learning.', explanation: '**Types of Support Groups:**\n\n*Mental Health Specific:*\n- DBSA (Depression and Bipolar Support Alliance)\n- NAMI Support Groups\n- Anxiety and Depression Association groups\n- Condition-specific groups\n\n*12-Step Programs:*\n- Alcoholics Anonymous (AA)\n- Narcotics Anonymous (NA)\n- Other addiction programs\n- Structured approach with steps\n\n*Peer-Run Organizations:*\n- Consumer-run drop-in centers\n- Peer support programs\n- Warm lines\n\n**Therapeutic Factors (Yalom):**\n\n*Universality:*\n- "I\'m not alone"\n- Shared experience reduces isolation\n\n*Hope:*\n- Seeing others\' recovery\n- "If they can, I can"\n\n*Experiential Learning:*\n- Learning from others\' experiences\n- Practical strategies\n\n*Altruism:*\n- Helping others helps self\n- Purpose and meaning\n\n*Cohesion:*\n- Belonging\n- Acceptance\n\n**Evidence:**\n- Adjunctive benefit to treatment\n- Improved outcomes in addiction (AA)\n- Enhanced recovery in mental illness\n- Reduced hospitalizations\n- Improved quality of life\n\n**Facilitation:**\n\n*Peer-Led:*\n- Lived experience\n- More accessible\n- Empowerment model\n\n*Professionally Facilitated:*\n- Structured content\n- Crisis management\n- Clinical oversight\n\n**Considerations:**\n- Finding right fit\n- Confidentiality\n- Boundaries\n- When professional help needed', keyTerms: [{ term: 'therapeutic factors', definition: 'Elements of group experience that promote healing' }, { term: 'universality', definition: 'Realization that others share similar experiences' }, { term: '12-step', definition: 'Structured recovery program originated with AA' }], analogies: [] },
    3: { level: 3, summary: 'Support groups utilize specific therapeutic factors including universality, instillation of hope, and interpersonal learning. 12-step programs have substantial evidence for addiction. Peer support integration into mental health care is expanding.', explanation: '**Therapeutic Mechanisms:**\n\n*Yalom\'s Therapeutic Factors in Groups:*\n- Universality\n- Installation of hope\n- Imparting information\n- Altruism\n- Corrective recapitulation of family\n- Development of socializing techniques\n- Imitative behavior\n- Interpersonal learning\n- Group cohesiveness\n- Catharsis\n- Existential factors\n\n*Applied to Support Groups:*\n- Universality prominent\n- Hope from peer recovery\n- Information sharing\n- Altruism through helping others\n\n**12-Step Evidence:**\n\n*Research:*\n- AA: Large evidence base\n- Cochrane review: Comparable or better than other treatments\n- Mechanisms: Social support, behavior change, spirituality\n- Cost-effective\n\n*Key Elements:*\n- Admitting powerlessness\n- Higher power concept (flexible)\n- Moral inventory\n- Making amends\n- Ongoing meetings\n- Sponsorship\n\n**Mental Health Support Groups:**\n\n*Evidence:*\n- Less robust than 12-step literature\n- Positive effects on symptoms, function\n- Complements professional treatment\n- Reduces hospitalization\n\n*Programs:*\n- WRAP (Wellness Recovery Action Plan)\n- IMR (Illness Management and Recovery)\n- Peer-led education\n\n**Professional Integration:**\n\n*Referral:*\n- Appropriate matching\n- Timing in treatment\n- Ongoing assessment\n\n*Collaboration:*\n- Communication with group leaders\n- Complementary roles\n- Crisis protocols', keyTerms: [{ term: 'WRAP', definition: 'Wellness Recovery Action Plan - peer-developed self-management' }, { term: 'IMR', definition: 'Illness Management and Recovery - structured curriculum' }, { term: 'sponsorship', definition: '12-step mentorship relationship' }], clinicalNotes: 'Support groups complement professional treatment. Match group to patient needs. 12-step has strong evidence for addiction. Address any negative group experiences. Peer support expanding in mental health care.' },
    4: { level: 4, summary: 'Support group mechanisms involve social learning, identity transformation, and therapeutic factors. Implementation considerations include matching, safety, and integration with clinical care. Peer support roles increasingly formalized in healthcare.', explanation: '**Mechanisms Research:**\n\n*Social Learning:*\n- Modeling recovery\n- Skill observation\n- Vicarious learning\n\n*Identity Transformation:*\n- From patient to person in recovery\n- Recovery identity\n- Peer role models\n\n*Social Network:*\n- Recovery-supportive network\n- Replace substance-using networks\n- Community belonging\n\n**Formalized Peer Support:**\n\n*Peer Specialists:*\n- Trained individuals with lived experience\n- Certified in many states\n- Part of treatment teams\n- Multiple roles (support, navigation, modeling)\n\n*Evidence:*\n- Reduced hospitalizations\n- Improved engagement\n- Patient satisfaction\n- Cost-effective\n\n**Implementation:**\n\n*Matching:*\n- Condition-specific\n- Cultural considerations\n- Stage of recovery\n- Personality factors\n\n*Safety:*\n- Confidentiality structures\n- Crisis protocols\n- Appropriate boundaries\n- Monitoring for harm\n\n*Integration:*\n- Communication with clinical team\n- Complementary not competing\n- Clear roles\n- Referral pathways\n\n**Special Considerations:**\n\n*Online Groups:*\n- Accessibility\n- Anonymity options\n- Geographic reach\n- Moderation challenges\n\n*Specific Populations:*\n- Cultural adaptations\n- Age-specific\n- Condition-specific\n- Dual diagnosis', keyTerms: [{ term: 'peer specialist', definition: 'Trained individual with lived experience providing support' }, { term: 'recovery identity', definition: 'Self-concept organized around recovery rather than illness' }, { term: 'dual diagnosis', definition: 'Co-occurring mental health and substance use disorders' }], clinicalNotes: 'Peer support is increasingly evidence-based. Integration with clinical care important. Peer specialists are formalized roles. Address matching and safety. Support groups work best as complements to treatment.' },
    5: { level: 5, summary: 'Contemporary research explores peer support implementation science, digital platforms, and integration into healthcare systems. Peer workforce development expanding. Evidence synthesis informs best practices.', explanation: '**Implementation Science:**\n\n*Dissemination:*\n- Peer specialist training programs\n- State certification standards\n- Reimbursement mechanisms\n- Supervision models\n\n*Sustainability:*\n- Funding streams\n- Organizational integration\n- Career pathways\n- Quality assurance\n\n**Digital Platforms:**\n\n*Online Communities:*\n- Moderated forums\n- Video-based groups\n- Apps with peer components\n- Social media groups\n\n*Research:*\n- Effectiveness of online support\n- Optimal moderation\n- Safety considerations\n- Reaching underserved\n\n**Workforce Development:**\n\n*Peer Specialists:*\n- Training curricula\n- Competency frameworks\n- Supervision approaches\n- Career advancement\n\n*Integration:*\n- Team-based care inclusion\n- Role clarity\n- Organizational culture\n- Professional collaboration\n\n**Research Priorities:**\n\n*Mechanism Studies:*\n- What works for whom?\n- Active ingredients\n- Moderators of effect\n\n*Comparative Effectiveness:*\n- Types of groups\n- Formats (online vs in-person)\n- Duration and intensity\n\n**Global Perspectives:**\n- User/survivor movement\n- LMIC applications\n- Cultural adaptations\n- Policy integration', keyTerms: [{ term: 'peer workforce', definition: 'Employed individuals with lived experience in mental health roles' }, { term: 'user/survivor movement', definition: 'Advocacy movement of mental health service users' }, { term: 'competency framework', definition: 'Standards defining peer specialist skills and knowledge' }], clinicalNotes: 'Peer support workforce growing. Certification standards exist in most states. Digital options expanding access. Integration into healthcare systems ongoing. Research base developing.' },
  },

  media: [],
  citations: [{ id: 'support-groups', type: 'article', title: 'Support Groups and Peer Support', authors: ['Various'], source: 'Various publications' }],
  crossReferences: [{ targetId: 'mental-health-peer-support', targetType: 'topic', relationship: 'related', label: 'Peer Support' }],
  tags: { systems: ['nervous'], topics: ['mental-health', 'support'], keywords: ['support groups', 'peer support', '12-step', 'mutual aid'], clinicalRelevance: 'medium', examRelevance: { usmle: false, nbme: false, shelf: [] } },
  createdAt: '2025-01-24T00:00:00.000Z',
  updatedAt: '2025-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default supportGroupsContent;
