/**
 * Return to Work Planning - Educational Content
 */

import { EducationalContent } from '../../types';

export const returnToWorkPlanning: EducationalContent = {
  id: 'rehab-return-to-work-planning',
  type: 'concept',
  name: 'Return to Work Planning',
  alternateNames: ['RTW Planning', 'Occupational Rehabilitation'],

  levels: {
    1: { level: 1, summary: 'Return to work planning helps people safely get back to their jobs after injury, illness, or disability.', explanation: 'When health problems affect your ability to work, a plan helps you return safely and successfully.', keyTerms: [{ term: 'return to work', definition: 'Process of going back to employment after time off for health reasons' }, { term: 'work restrictions', definition: 'Limits on work activities based on health status' }, { term: 'accommodations', definition: 'Changes to work that help someone with a disability do their job' }], analogies: ['Return to work planning is like having a roadmap to get back to your job safely.'], examples: ['After back surgery, a worker gradually returns to full duties over several weeks.'] },
    2: { level: 2, summary: 'Return to work involves medical clearance, job analysis, accommodations, and graduated return strategies to facilitate successful reentry into employment.', explanation: '**RTW Process:**\n1. Medical evaluation and clearance\n2. Functional capacity assessment\n3. Job demands analysis\n4. Gap identification\n5. Accommodation planning\n6. Graduated return schedule\n7. Monitoring and adjustment\n\n**Key Components:**\n- Healthcare provider communication\n- Employer engagement\n- Case management\n- Vocational services if needed\n\n**Factors Affecting RTW:**\n- Injury/illness severity\n- Job physical demands\n- Workplace support\n- Psychosocial factors\n- Financial considerations', keyTerms: [{ term: 'job demands analysis', definition: 'Detailed assessment of physical and cognitive job requirements' }, { term: 'transitional duty', definition: 'Modified work during return-to-work transition' }, { term: 'case management', definition: 'Coordination of medical, vocational, and employer services' }], analogies: ['RTW planning bridges the gap between medical recovery and job demands.'] },
    3: { level: 3, summary: 'Evidence-based RTW programs integrate medical, functional, and workplace factors with psychosocial interventions to optimize sustainable return to meaningful work.', explanation: '## Evidence Base\n\n**Predictors of RTW:**\n- Recovery expectations\n- RTW self-efficacy\n- Workplace factors\n- Fear-avoidance beliefs\n- Pain intensity (modest predictor)\n\n**Effective Interventions:**\n- Early contact and communication\n- Workplace-based interventions\n- Cognitive-behavioral approaches\n- Graduated return schedules\n- Supervisor training\n\n## Models\n\n**Sherbrooke Model:**\n- Occupational physician role\n- Workplace intervention focus\n- Participatory ergonomics\n- Reduced disability duration\n\n**Flags System:**\n- Red flags: Medical concerns\n- Yellow flags: Psychosocial risks\n- Blue flags: Workplace perceptions\n- Black flags: System/context barriers\n\n## Accommodations\n\n| Type | Examples |\n|------|----------|\n| Physical | Ergonomic equipment, lifting limits |\n| Schedule | Modified hours, breaks |\n| Duties | Task modification, job restructuring |\n| Support | Supervision, assistance |', keyTerms: [{ term: 'participatory ergonomics', definition: 'Involving workers in workplace design and problem-solving' }, { term: 'flags system', definition: 'Classification of RTW barriers into medical, psychosocial, and system categories' }, { term: 'RTW self-efficacy', definition: 'Confidence in ability to return to work' }], clinicalNotes: 'Psychosocial factors (yellow flags) are often stronger predictors of prolonged disability than medical factors. Addressing these early improves RTW outcomes.' },
    4: { level: 4, summary: 'Advanced RTW rehabilitation addresses complex cases through multidisciplinary intervention, workplace integration, and navigation of insurance and legal systems.', explanation: '## Complex Cases\n\n**Chronic Conditions:**\n- Longer intervention duration\n- Multidisciplinary approaches\n- Cognitive-behavioral components\n- Vocational counseling\n\n**Mental Health:**\n- Depression/anxiety common\n- Integrated treatment\n- Workplace mental health support\n- Stigma challenges\n\n## Stakeholder Coordination\n\n**Healthcare:**\n- Clear communication\n- Functional focus\n- Timely documentation\n\n**Employer:**\n- Accommodation provision\n- Supervisor support\n- Culture of return\n\n**Insurance/Legal:**\n- Workers compensation navigation\n- ADA compliance\n- Disability determination\n\n## Outcomes Measurement\n\n- Sustainable RTW\n- Time to RTW\n- Productivity\n- Recurrence rates\n- Quality of life', keyTerms: [{ term: 'sustainable RTW', definition: 'Return to work that is maintained over time without recurrence' }, { term: 'ADA', definition: 'Americans with Disabilities Act - law requiring reasonable accommodations' }], clinicalNotes: 'Multidisciplinary programs including physical, psychological, and vocational components are most effective for complex cases and chronic conditions.' },
    5: { level: 5, summary: 'Contemporary RTW research explores precision approaches, workplace health integration, and policy innovations to improve outcomes across populations.', explanation: '## Research Directions\n\n**Precision RTW:**\n- Risk stratification\n- Targeted intervention\n- Individual trajectories\n- Predictive models\n\n**Workplace Integration:**\n- Health promotion\n- Disability prevention\n- Accommodation culture\n- Manager training\n\n## Policy\n\n**Systems:**\n- Compensation reform\n- Employer incentives\n- Healthcare-workplace linkage\n- International models\n\n**Equity:**\n- Access to services\n- Disparities\n- Gig economy challenges\n- Aging workforce', keyTerms: [{ term: 'risk stratification', definition: 'Identifying patients at high risk for prolonged disability' }], clinicalNotes: 'Early identification of high-risk cases allows targeted intervention to prevent prolonged disability, which is more effective than treating established chronicity.' },
  },

  media: [],
  citations: [],
  crossReferences: [{ targetId: 'rehab-functional-capacity-evaluation', targetType: 'topic', relationship: 'related', label: 'Functional Capacity Evaluation' }],
  tags: { systems: ['functional'], topics: ['rehabilitation', 'work', 'disability', 'vocational'], clinicalRelevance: 'high', examRelevance: { usmle: true, nbme: true, shelf: ['medicine'] } },
  createdAt: '2026-01-24T00:00:00.000Z',
  updatedAt: '2026-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default returnToWorkPlanning;
