/**
 * Vocational Rehabilitation - Educational Content
 */

import { EducationalContent } from '../../types';

export const vocationalRehabilitation: EducationalContent = {
  id: 'rehab-vocational-rehabilitation',
  type: 'concept',
  name: 'Vocational Rehabilitation',
  alternateNames: ['VR Services', 'Vocational Counseling', 'Career Rehabilitation'],

  levels: {
    1: { level: 1, summary: 'Vocational rehabilitation helps people with disabilities find and keep jobs by providing training, support, and job placement services.', explanation: 'If a disability affects your ability to work, vocational rehabilitation can help you find suitable employment.', keyTerms: [{ term: 'vocational rehabilitation', definition: 'Services helping people with disabilities prepare for and find work' }, { term: 'vocational counselor', definition: 'Professional who helps with career planning and job placement' }], analogies: ['Vocational rehabilitation is like having a career coach who specializes in helping people with disabilities succeed at work.'], examples: ['Learning new computer skills to change careers after a disability prevents physical work.'] },
    2: { level: 2, summary: 'Vocational rehabilitation services include assessment, counseling, training, job placement, and support to help individuals with disabilities achieve competitive integrated employment.', explanation: '**Services:**\n- Vocational assessment\n- Career counseling\n- Training and education\n- Job placement\n- Assistive technology\n- Support services\n\n**Service Providers:**\n- State VR agencies (every state)\n- Private rehabilitation providers\n- Workers compensation VR\n- VA vocational services\n\n**Process:**\n1. Application and eligibility\n2. Assessment\n3. Individualized plan\n4. Services provision\n5. Job placement\n6. Follow-up', keyTerms: [{ term: 'state VR agency', definition: 'Government agency providing vocational rehabilitation in each state' }, { term: 'individualized plan for employment', definition: 'Written plan of VR services and employment goal' }, { term: 'competitive integrated employment', definition: 'Regular jobs in community settings with fair wages' }], analogies: ['The VR process is like a career planning journey with professional guidance.'] },
    3: { level: 3, summary: 'Vocational rehabilitation integrates functional assessment, labor market analysis, and evidence-based interventions to facilitate competitive employment for individuals with disabilities.', explanation: '## Assessment\n\n**Vocational Evaluation:**\n- Interests (Strong, O*NET)\n- Aptitudes\n- Transferable skills\n- Work values\n- Labor market factors\n\n**Functional Assessment:**\n- Physical capacities\n- Cognitive abilities\n- Psychosocial factors\n- Environmental needs\n\n## Service Categories\n\n| Category | Services |\n|----------|----------|\n| Assessment | Vocational evaluation, FCE |\n| Training | Education, OJT, apprenticeship |\n| Placement | Job development, supported employment |\n| Support | Assistive tech, counseling |\n\n## Evidence-Based Practices\n\n**Supported Employment:**\n- Place-then-train model\n- Job coaching\n- Ongoing support\n- Effective for serious mental illness\n\n**Customized Employment:**\n- Individual job carving\n- Negotiated positions\n- Complex disabilities', keyTerms: [{ term: 'supported employment', definition: 'Model providing job coaching and ongoing support in competitive work' }, { term: 'transferable skills', definition: 'Skills from past work applicable to new employment' }, { term: 'labor market analysis', definition: 'Assessment of job opportunities in a geographic area' }], clinicalNotes: 'Supported employment (Individual Placement and Support model) is an evidence-based practice for serious mental illness with strong randomized trial support.' },
    4: { level: 4, summary: 'Advanced vocational rehabilitation addresses complex cases through specialized assessment, customized interventions, and coordination with healthcare and employer systems.', explanation: '## Complex Populations\n\n**Brain Injury:**\n- Cognitive accommodations\n- Neuropsychological input\n- Structured job matching\n- Long-term support\n\n**Spinal Cord Injury:**\n- Physical demand matching\n- Assistive technology\n- Workplace accessibility\n- Transportation needs\n\n**Mental Health:**\n- IPS model\n- Psychiatric collaboration\n- Disclosure decisions\n- Stigma management\n\n## Employer Relations\n\n- Business development\n- Disability awareness training\n- Accommodation consulting\n- Tax incentive information\n\n## Outcome Measurement\n\n- Employment rate\n- Wage level\n- Hours worked\n- Job retention\n- Career advancement', keyTerms: [{ term: 'IPS', definition: 'Individual Placement and Support - evidence-based supported employment model' }, { term: 'job carving', definition: 'Creating a position by combining tasks from multiple jobs' }], clinicalNotes: 'For individuals with significant disabilities, customized employment approaches may be necessary when traditional competitive job placement is not feasible.' },
    5: { level: 5, summary: 'Contemporary vocational rehabilitation research explores technology applications, inclusive employment practices, and systems reform to improve employment outcomes for people with disabilities.', explanation: '## Technology\n\n**Assistive Technology:**\n- Rapid advancement\n- Workplace integration\n- Remote work enablement\n\n**Service Delivery:**\n- Telehealth VR services\n- Online training\n- Virtual job exploration\n\n## Policy Directions\n\n**WIOA Implementation:**\n- Pre-employment transition services\n- Competitive integrated employment focus\n- Systems coordination\n\n**Employment First:**\n- Policy shift to employment\n- Subminimum wage phase-out\n- Community integration\n\n## Research Needs\n\n- Effectiveness by disability type\n- Technology impact\n- Employer practices\n- Long-term outcomes', keyTerms: [{ term: 'WIOA', definition: 'Workforce Innovation and Opportunity Act - federal employment and training legislation' }, { term: 'Employment First', definition: 'Policy prioritizing competitive employment for people with disabilities' }], clinicalNotes: 'WIOA (2014) emphasizes competitive integrated employment and pre-employment transition services for students, shifting VR focus toward competitive work outcomes.' },
  },

  media: [],
  citations: [],
  crossReferences: [{ targetId: 'rehab-return-to-work-planning', targetType: 'topic', relationship: 'related', label: 'Return to Work Planning' }],
  tags: { systems: ['functional'], topics: ['rehabilitation', 'vocational', 'employment', 'disability'], clinicalRelevance: 'high', examRelevance: { usmle: true, nbme: true, shelf: ['medicine'] } },
  createdAt: '2026-01-24T00:00:00.000Z',
  updatedAt: '2026-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default vocationalRehabilitation;
