// =============================================================================
// SOMA Toxicologia Enciclopedia — Spanish-First Bilingual
// Toxicology Patient Education Content
// =============================================================================
// ARCHITECTURE: JSON.parse() wrapper prevents TS2590 "expression too complex"
// =============================================================================

export interface ToxicologiaEntry {
  id: string;
  nombreEs: string;
  nombreEn: string;
  descripcionEs: string;
  descripcionEn: string;
  categoriaEs: string;
  categoriaEn: string;
  sintomasEs: string[];
  sintomasEn: string[];
  agenteToxicoEs: string;
  agenteToxicoEn: string;
  mecanismoEs: string;
  mecanismoEn: string;
  tratamientoEs: string;
  tratamientoEn: string;
  antidotoEs: string;
  antidotoEn: string;
  primerosAuxiliosEs: string;
  primerosAuxiliosEn: string;
  prevencionEs: string;
  prevencionEn: string;
}

export const TOXICOLOGIA_ENTRIES: ToxicologiaEntry[] = JSON.parse(`[
  {
    "id": "intoxicacion-paracetamol",
    "nombreEs": "Intoxicacion por Paracetamol (Acetaminofen)",
    "nombreEn": "Acetaminophen (Paracetamol) Overdose",
    "categoriaEs": "Medicamentosa",
    "categoriaEn": "Medication-related",
    "descripcionEs": "La intoxicacion por paracetamol es una de las causas mas frecuentes de insuficiencia hepatica aguda en todo el mundo. Ocurre cuando se ingiere una cantidad excesiva del farmaco, generalmente superior a 150 mg/kg en una sola toma o en dosis supraterapeuticas repetidas en un periodo de 24 horas. El metabolismo hepatico del paracetamol genera un metabolito toxico llamado N-acetil-p-benzoquinoneimina (NAPQI), que normalmente es neutralizado por el glutation hepatico; sin embargo, en sobredosis, las reservas de glutation se agotan y el NAPQI se acumula, provocando necrosis hepatocelular masiva. La presentacion clinica sigue un patron de cuatro fases que puede evolucionar desde sintomas inespecificos hasta falla hepatica fulminante y muerte si no se trata a tiempo. Es fundamental reconocer que los sintomas iniciales pueden ser leves o estar ausentes, lo que retrasa el diagnostico y empeora el pronostico.",
    "descripcionEn": "Acetaminophen overdose is one of the most common causes of acute liver failure worldwide. It occurs when an excessive amount of the drug is ingested, typically greater than 150 mg/kg in a single dose or in repeated supratherapeutic doses over a 24-hour period. Hepatic metabolism of acetaminophen generates a toxic metabolite called N-acetyl-p-benzoquinoneimine (NAPQI), which is normally neutralized by hepatic glutathione; however, in overdose, glutathione stores are depleted and NAPQI accumulates, causing massive hepatocellular necrosis. The clinical presentation follows a four-phase pattern that can evolve from nonspecific symptoms to fulminant hepatic failure and death if not treated promptly. It is critical to recognize that initial symptoms may be mild or absent, delaying diagnosis and worsening prognosis.",
    "sintomasEs": [
      "Nauseas, vomitos y dolor abdominal en las primeras 24 horas (Fase I)",
      "Mejoria aparente con dolor en hipocondrio derecho entre las 24-72 horas (Fase II)",
      "Ictericia, coagulopatia y elevacion marcada de transaminasas (Fase III, 72-96 horas)",
      "Encefalopatia hepatica con confusion, somnolencia y coma",
      "Oliguria o anuria por insuficiencia renal concomitante",
      "Hipoglucemia severa por falla hepatica",
      "Acidosis metabolica con lactato elevado",
      "Sangrado espontaneo por coagulopatia"
    ],
    "sintomasEn": [
      "Nausea, vomiting, and abdominal pain in the first 24 hours (Phase I)",
      "Apparent improvement with right upper quadrant pain between 24-72 hours (Phase II)",
      "Jaundice, coagulopathy, and markedly elevated transaminases (Phase III, 72-96 hours)",
      "Hepatic encephalopathy with confusion, drowsiness, and coma",
      "Oliguria or anuria from concomitant renal failure",
      "Severe hypoglycemia from hepatic failure",
      "Metabolic acidosis with elevated lactate",
      "Spontaneous bleeding from coagulopathy"
    ],
    "agenteToxicoEs": "Paracetamol (acetaminofen). La dosis toxica es generalmente superior a 150 mg/kg en adultos o mas de 200 mg/kg en ninos. El riesgo aumenta con el consumo cronico de alcohol, desnutricion, uso concomitante de farmacos inductores del citocromo P450 (como isoniazida, rifampicina o anticonvulsivantes), y en pacientes con enfermedad hepatica preexistente. Multiples presentaciones comerciales contienen paracetamol, lo que puede llevar a sobredosis inadvertida.",
    "agenteToxicoEn": "Acetaminophen (paracetamol). The toxic dose is generally greater than 150 mg/kg in adults or more than 200 mg/kg in children. Risk increases with chronic alcohol use, malnutrition, concomitant use of cytochrome P450-inducing drugs (such as isoniazid, rifampin, or anticonvulsants), and in patients with pre-existing liver disease. Multiple commercial products contain acetaminophen, which can lead to inadvertent overdose.",
    "mecanismoEs": "El paracetamol se metaboliza principalmente en el higado por glucuronidacion y sulfatacion (90%). Un pequeno porcentaje (5-10%) es oxidado por el citocromo P450 (CYP2E1) produciendo NAPQI, un metabolito altamente reactivo. En dosis terapeuticas, el NAPQI se conjuga rapidamente con glutation y se elimina como acido mercapturico. En sobredosis, las vias de conjugacion se saturan, aumenta la produccion de NAPQI y las reservas de glutation se agotan (por debajo del 30% de lo normal), permitiendo que el NAPQI se una covalentemente a proteinas hepatocelulares, causando estres oxidativo, disfuncion mitocondrial y necrosis centrolobulillar.",
    "mecanismoEn": "Acetaminophen is primarily metabolized in the liver by glucuronidation and sulfation (90%). A small percentage (5-10%) is oxidized by cytochrome P450 (CYP2E1) producing NAPQI, a highly reactive metabolite. At therapeutic doses, NAPQI is rapidly conjugated with glutathione and eliminated as mercapturic acid. In overdose, conjugation pathways become saturated, NAPQI production increases, and glutathione stores are depleted (below 30% of normal), allowing NAPQI to covalently bind to hepatocellular proteins, causing oxidative stress, mitochondrial dysfunction, and centrilobular necrosis.",
    "tratamientoEs": "El tratamiento de primera linea es la N-acetilcisteina (NAC), que actua como precursor del glutation, reponiendo las reservas hepaticas y neutralizando el NAPQI. El protocolo intravenoso estandar consiste en tres fases: 150 mg/kg en 60 minutos, seguido de 50 mg/kg en 4 horas, y finalmente 100 mg/kg en 16 horas (total 300 mg/kg en 21 horas). La NAC es mas efectiva cuando se administra dentro de las primeras 8 horas postingesta, pero sigue siendo beneficiosa incluso en etapas tardias. Se debe determinar el nivel serico de paracetamol a las 4 horas postingesta y utilizar el nomograma de Rumack-Matthew para evaluar la necesidad de tratamiento. El carbon activado (1 g/kg, maximo 50 g) se puede administrar si la ingesta fue hace menos de 2-4 horas. En casos de falla hepatica fulminante, el trasplante hepatico puede ser necesario. Los criterios del Kings College ayudan a determinar la necesidad de trasplante.",
    "tratamientoEn": "The first-line treatment is N-acetylcysteine (NAC), which acts as a glutathione precursor, replenishing hepatic stores and neutralizing NAPQI. The standard intravenous protocol consists of three phases: 150 mg/kg over 60 minutes, followed by 50 mg/kg over 4 hours, and finally 100 mg/kg over 16 hours (total 300 mg/kg over 21 hours). NAC is most effective when administered within the first 8 hours post-ingestion but remains beneficial even in late stages. Serum acetaminophen level should be obtained at 4 hours post-ingestion and the Rumack-Matthew nomogram used to assess the need for treatment. Activated charcoal (1 g/kg, maximum 50 g) can be given if ingestion occurred less than 2-4 hours prior. In cases of fulminant hepatic failure, liver transplantation may be required. The Kings College Criteria help determine transplant necessity.",
    "antidotoEs": "N-acetilcisteina (NAC). Es el antidoto especifico y debe administrarse lo antes posible. Via intravenosa: protocolo de 21 horas (150 mg/kg + 50 mg/kg + 100 mg/kg). Via oral: 140 mg/kg dosis de carga, seguida de 70 mg/kg cada 4 horas por 17 dosis adicionales (72 horas total). La via intravenosa es preferida en pacientes con vomitos, falla hepatica o embarazo. Las reacciones anafilactoides son posibles con la via IV pero generalmente son leves y manejables.",
    "antidotoEn": "N-acetylcysteine (NAC). It is the specific antidote and should be administered as soon as possible. Intravenous route: 21-hour protocol (150 mg/kg + 50 mg/kg + 100 mg/kg). Oral route: 140 mg/kg loading dose followed by 70 mg/kg every 4 hours for 17 additional doses (72 hours total). The intravenous route is preferred in patients with vomiting, hepatic failure, or pregnancy. Anaphylactoid reactions are possible with the IV route but are generally mild and manageable.",
    "primerosAuxiliosEs": "Si se sospecha sobredosis de paracetamol, acudir a urgencias inmediatamente incluso si no hay sintomas, ya que la fase inicial puede ser asintomatica. Llevar el envase del medicamento para identificar la cantidad ingerida. No inducir el vomito a menos que lo indique un profesional de salud o un centro de control de intoxicaciones. Si la persona esta inconsciente, colocarla en posicion lateral de seguridad y asegurar la via aerea. Llamar al centro de control de intoxicaciones (en EE.UU.: 1-800-222-1222; en Mexico: 800-00-92-400) para recibir orientacion inmediata.",
    "primerosAuxiliosEn": "If acetaminophen overdose is suspected, go to the emergency department immediately even if there are no symptoms, as the initial phase may be asymptomatic. Bring the medication container to identify the quantity ingested. Do not induce vomiting unless instructed by a healthcare professional or poison control center. If the person is unconscious, place them in the recovery position and secure the airway. Call poison control (in the US: 1-800-222-1222) for immediate guidance.",
    "prevencionEs": "No exceder la dosis maxima diaria recomendada de 4 gramos en adultos sanos (2 gramos en pacientes con enfermedad hepatica o consumo cronico de alcohol). Leer las etiquetas de todos los medicamentos para identificar la presencia de paracetamol, ya que se encuentra en mas de 600 productos comerciales incluyendo antigripales, analgesicos combinados y medicamentos para el resfriado. Almacenar los medicamentos fuera del alcance de los ninos con tapas de seguridad. Evitar el consumo de alcohol mientras se toma paracetamol. Consultar al medico antes de usar paracetamol si se tienen problemas hepaticos o se toman otros medicamentos.",
    "prevencionEn": "Do not exceed the maximum recommended daily dose of 4 grams in healthy adults (2 grams in patients with liver disease or chronic alcohol consumption). Read the labels of all medications to identify the presence of acetaminophen, as it is found in more than 600 commercial products including cold medicines, combination analgesics, and flu medications. Store medications out of reach of children with safety caps. Avoid alcohol consumption while taking acetaminophen. Consult your doctor before using acetaminophen if you have liver problems or are taking other medications."
  },
  {
    "id": "intoxicacion-organofosforados",
    "nombreEs": "Intoxicacion por Organofosforados",
    "nombreEn": "Organophosphate Poisoning",
    "categoriaEs": "Plaguicidas",
    "categoriaEn": "Pesticides",
    "descripcionEs": "La intoxicacion por organofosforados es una emergencia toxicologica grave y potencialmente mortal causada por la exposicion a insecticidas organofosforados o agentes nerviosos. Estos compuestos inhiben de forma irreversible la enzima acetilcolinesterasa, provocando una acumulacion masiva de acetilcolina en las sinapsis colinergicas muscaranicas, nicotinicas y del sistema nervioso central. Es una causa importante de morbimortalidad en paises agricolas, donde la exposicion puede ser ocupacional o intencional (autolesion). El cuadro clinico se caracteriza por una crisis colinergica aguda que puede progresar rapidamente a insuficiencia respiratoria y muerte si no se trata con urgencia. La via de exposicion puede ser dermica, inhalatoria u oral, siendo esta ultima la mas grave.",
    "descripcionEn": "Organophosphate poisoning is a severe and potentially fatal toxicological emergency caused by exposure to organophosphate insecticides or nerve agents. These compounds irreversibly inhibit the enzyme acetylcholinesterase, causing massive accumulation of acetylcholine at muscarinic, nicotinic, and central nervous system cholinergic synapses. It is a major cause of morbidity and mortality in agricultural countries, where exposure may be occupational or intentional (self-harm). The clinical presentation is characterized by an acute cholinergic crisis that can rapidly progress to respiratory failure and death if not treated urgently. The route of exposure may be dermal, inhalational, or oral, with oral being the most severe.",
    "sintomasEs": [
      "Sialorrea (salivacion excesiva), lagrimeo y rinorrea",
      "Miosis (pupilas puntiformes) con vision borrosa",
      "Broncorrea, broncoespasmo y dificultad respiratoria severa",
      "Bradicardia e hipotension",
      "Nauseas, vomitos, dolor abdominal y diarrea profusa",
      "Fasciculaciones musculares, debilidad y paralisis",
      "Incontinencia urinaria y fecal",
      "Convulsiones, agitacion, confusion y coma",
      "Diaforesis profusa (sudoracion excesiva)",
      "Sindrome intermedio: debilidad de musculos proximales y respiratorios 24-96 horas despues"
    ],
    "sintomasEn": [
      "Sialorrhea (excessive salivation), lacrimation, and rhinorrhea",
      "Miosis (pinpoint pupils) with blurred vision",
      "Bronchorrhea, bronchospasm, and severe respiratory distress",
      "Bradycardia and hypotension",
      "Nausea, vomiting, abdominal pain, and profuse diarrhea",
      "Muscle fasciculations, weakness, and paralysis",
      "Urinary and fecal incontinence",
      "Seizures, agitation, confusion, and coma",
      "Profuse diaphoresis (excessive sweating)",
      "Intermediate syndrome: proximal and respiratory muscle weakness 24-96 hours later"
    ],
    "agenteToxicoEs": "Compuestos organofosforados incluyendo insecticidas agricolas (paration, malation, clorpirifos, diazinon, dimetoato) y agentes nerviosos de uso belico (sarin, soman, tabun, VX). Se absorben eficientemente por via oral, dermica e inhalatoria. Los compuestos lipofialicos como el fention pueden causar toxicidad retardada por almacenamiento en tejido graso. La dosis letal varia segun el compuesto: malation tiene relativamente baja toxicidad (DL50 oral >1000 mg/kg), mientras que el paration es altamente toxico (DL50 oral 3-8 mg/kg).",
    "agenteToxicoEn": "Organophosphate compounds including agricultural insecticides (parathion, malathion, chlorpyrifos, diazinon, dimethoate) and chemical warfare nerve agents (sarin, soman, tabun, VX). They are efficiently absorbed via oral, dermal, and inhalational routes. Lipophilic compounds like fenthion can cause delayed toxicity due to fat tissue storage. The lethal dose varies by compound: malathion has relatively low toxicity (oral LD50 >1000 mg/kg), while parathion is highly toxic (oral LD50 3-8 mg/kg).",
    "mecanismoEs": "Los organofosforados fosforilan el sitio activo de la acetilcolinesterasa (AChE), inactivandola de forma progresivamente irreversible. Inicialmente se forma un complejo enzima-fosforato que puede ser revertido con oximas (pralidoxima). Sin embargo, con el tiempo ocurre un proceso llamado envejecimiento (aging), en el cual se pierde un grupo alquilo del complejo, haciendo la inhibicion permanente e irreversible. El tiempo de envejecimiento varia: para soman es de 2-6 minutos, para sarin 5 horas, y para otros compuestos puede ser de 24-48 horas. La acumulacion resultante de acetilcolina produce sobreestimulacion de receptores muscarinicos (en glandulas y musculo liso), nicotinicos (en placa neuromuscular y ganglios autonomicos) y centrales, generando la crisis colinergica.",
    "mecanismoEn": "Organophosphates phosphorylate the active site of acetylcholinesterase (AChE), progressively and irreversibly inactivating it. Initially, an enzyme-phosphorate complex forms that can be reversed with oximes (pralidoxime). However, over time a process called aging occurs, in which an alkyl group is lost from the complex, making the inhibition permanent and irreversible. Aging time varies: for soman it is 2-6 minutes, for sarin 5 hours, and for other compounds it may be 24-48 hours. The resulting accumulation of acetylcholine produces overstimulation of muscarinic receptors (in glands and smooth muscle), nicotinic receptors (at the neuromuscular junction and autonomic ganglia), and central receptors, generating the cholinergic crisis.",
    "tratamientoEs": "El tratamiento requiere accion inmediata y se basa en tres pilares. Primero, la estabilizacion con especial atencion a la via aerea y respiracion, ya que la insuficiencia respiratoria es la principal causa de muerte. Se debe intubar si es necesario y aspirar secreciones bronquiales frecuentemente. Segundo, la atropina es el farmaco fundamental: se administra 2-4 mg IV en adultos (0.05 mg/kg en ninos), repitiendo cada 5-10 minutos hasta lograr la atropinizacion (secreciones secas, frecuencia cardiaca >80). Las dosis requeridas pueden ser enormes (hasta cientos de miligramos en casos graves). Tercero, la pralidoxima (2-PAM) se administra para reactivar la AChE antes del envejecimiento: 1-2 g IV en adultos en 15-30 minutos, seguido de infusion continua de 500 mg/hora. Las benzodiacepinas (diazepam 5-10 mg IV) se usan para controlar convulsiones. La descontaminacion es critica: retirar toda la ropa, lavar la piel con abundante agua y jabon, y el personal debe usar equipo de proteccion para evitar contaminacion secundaria.",
    "tratamientoEn": "Treatment requires immediate action and is based on three pillars. First, stabilization with special attention to airway and breathing, as respiratory failure is the main cause of death. Intubation should be performed if necessary and bronchial secretions aspirated frequently. Second, atropine is the fundamental drug: 2-4 mg IV in adults (0.05 mg/kg in children) is administered, repeating every 5-10 minutes until atropinization is achieved (dry secretions, heart rate >80). Required doses can be enormous (up to hundreds of milligrams in severe cases). Third, pralidoxime (2-PAM) is administered to reactivate AChE before aging: 1-2 g IV in adults over 15-30 minutes, followed by continuous infusion of 500 mg/hour. Benzodiazepines (diazepam 5-10 mg IV) are used to control seizures. Decontamination is critical: remove all clothing, wash skin with copious water and soap, and personnel must use protective equipment to avoid secondary contamination.",
    "antidotoEs": "Atropina: antagonista competitivo de los receptores muscarinicos que contrarresta la broncorrea, broncoespasmo, bradicardia y secreciones excesivas. No tiene efecto sobre los sintomas nicotinicos. Dosis inicial de 2-4 mg IV, duplicando la dosis cada 5 minutos hasta atropinizacion. Pralidoxima (2-PAM): reactivador de la acetilcolinesterasa que revierte los efectos nicotinicos (fasciculaciones, debilidad). Debe administrarse lo antes posible antes del envejecimiento de la enzima. Dosis: 1-2 g IV en 15-30 minutos. Diazepam: 5-10 mg IV para convulsiones.",
    "antidotoEn": "Atropine: competitive muscarinic receptor antagonist that counteracts bronchorrhea, bronchospasm, bradycardia, and excessive secretions. It has no effect on nicotinic symptoms. Initial dose of 2-4 mg IV, doubling the dose every 5 minutes until atropinization. Pralidoxime (2-PAM): acetylcholinesterase reactivator that reverses nicotinic effects (fasciculations, weakness). Must be administered as soon as possible before enzyme aging. Dose: 1-2 g IV over 15-30 minutes. Diazepam: 5-10 mg IV for seizures.",
    "primerosAuxiliosEs": "Sacar a la persona del area de exposicion inmediatamente, protegiendo al rescatista con guantes y mascarilla. Retirar toda la ropa contaminada y colocarla en bolsas de plastico selladas. Lavar toda la piel expuesta con abundante agua y jabon durante al menos 15 minutos, prestando especial atencion a pliegues cutaneos, unas y cabello. Si hubo ingestion, no inducir el vomito. Llamar al servicio de emergencias y al centro de control de intoxicaciones. Si la persona tiene dificultad respiratoria, mantener la via aerea permeable y administrar oxigeno si esta disponible. Si la persona convulsiona, proteger de lesiones sin introducir nada en la boca.",
    "primerosAuxiliosEn": "Remove the person from the exposure area immediately, protecting the rescuer with gloves and a mask. Remove all contaminated clothing and place in sealed plastic bags. Wash all exposed skin with copious water and soap for at least 15 minutes, paying special attention to skin folds, nails, and hair. If ingestion occurred, do not induce vomiting. Call emergency services and poison control. If the person has difficulty breathing, maintain a patent airway and administer oxygen if available. If the person is seizing, protect from injury without placing anything in the mouth.",
    "prevencionEs": "Utilizar equipo de proteccion personal completo (guantes, mascarilla, overol, botas) al manejar plaguicidas. Respetar los periodos de reingreso a campos tratados. Almacenar los plaguicidas en recipientes originales etiquetados, lejos de alimentos y fuera del alcance de ninos. Nunca transferir plaguicidas a envases de bebidas o alimentos. Lavarse las manos y la cara antes de comer, beber o fumar despues de trabajar con plaguicidas. Implementar el manejo integrado de plagas para reducir la dependencia de pesticidas quimicos. Capacitar a trabajadores agricolas en el manejo seguro de estos productos.",
    "prevencionEn": "Use complete personal protective equipment (gloves, mask, coveralls, boots) when handling pesticides. Respect re-entry intervals for treated fields. Store pesticides in original labeled containers, away from food and out of reach of children. Never transfer pesticides to beverage or food containers. Wash hands and face before eating, drinking, or smoking after working with pesticides. Implement integrated pest management to reduce dependence on chemical pesticides. Train agricultural workers in the safe handling of these products."
  },
  {
    "id": "intoxicacion-monoxido-carbono",
    "nombreEs": "Intoxicacion por Monoxido de Carbono",
    "nombreEn": "Carbon Monoxide Poisoning",
    "categoriaEs": "Gases",
    "categoriaEn": "Gases",
    "descripcionEs": "La intoxicacion por monoxido de carbono (CO) es una causa frecuente de muerte por envenenamiento en todo el mundo. El CO es un gas incoloro, inodoro e insipido producido por la combustion incompleta de materiales organicos. Sus fuentes incluyen calentadores defectuosos, motores de combustion interna, incendios, generadores electricos y estufas de gas mal ventiladas. El CO tiene una afinidad por la hemoglobina 200-250 veces mayor que el oxigeno, formando carboxihemoglobina (COHb) que reduce drasticamente la capacidad de transporte de oxigeno a los tejidos. Ademas, desplaza la curva de disociacion de la hemoglobina hacia la izquierda, dificulta la liberacion de oxigeno a nivel tisular, e inhibe la citocromo c oxidasa mitocondrial, causando hipoxia celular directa. La intoxicacion puede ser aguda o cronica, y sus sintomas inespecificos frecuentemente llevan a diagnosticos erroneos.",
    "descripcionEn": "Carbon monoxide (CO) poisoning is a frequent cause of poisoning death worldwide. CO is a colorless, odorless, and tasteless gas produced by incomplete combustion of organic materials. Its sources include faulty heaters, internal combustion engines, fires, electric generators, and poorly ventilated gas stoves. CO has an affinity for hemoglobin 200-250 times greater than oxygen, forming carboxyhemoglobin (COHb) which drastically reduces the oxygen-carrying capacity to tissues. Additionally, it shifts the hemoglobin dissociation curve to the left, impairs oxygen release at the tissue level, and inhibits mitochondrial cytochrome c oxidase, causing direct cellular hypoxia. Poisoning can be acute or chronic, and its nonspecific symptoms frequently lead to misdiagnosis.",
    "sintomasEs": [
      "Cefalea intensa y persistente (sintoma mas comun)",
      "Mareo, vertigo y confusion",
      "Nauseas, vomitos y debilidad general",
      "Taquicardia y dolor toracico (especialmente en pacientes con enfermedad coronaria)",
      "Vision borrosa y dificultad para concentrarse",
      "Piel clasicamente rojo cereza (signo tardio, infrecuente en vivos)",
      "Sincope, convulsiones y coma en intoxicacion severa",
      "Edema pulmonar no cardiogenico",
      "Sindrome neurologico tardio: deterioro cognitivo, cambios de personalidad, trastornos del movimiento semanas despues de la exposicion"
    ],
    "sintomasEn": [
      "Severe and persistent headache (most common symptom)",
      "Dizziness, vertigo, and confusion",
      "Nausea, vomiting, and general weakness",
      "Tachycardia and chest pain (especially in patients with coronary artery disease)",
      "Blurred vision and difficulty concentrating",
      "Classically cherry-red skin (late sign, infrequent in living patients)",
      "Syncope, seizures, and coma in severe poisoning",
      "Non-cardiogenic pulmonary edema",
      "Delayed neurological syndrome: cognitive impairment, personality changes, movement disorders weeks after exposure"
    ],
    "agenteToxicoEs": "Monoxido de carbono (CO), gas producido por combustion incompleta. Fuentes principales: calentadores de agua y calefactores defectuosos o mal ventilados, motores de automoviles en espacios cerrados, incendios estructurales, generadores portatiles de gasolina, estufas de lena o carbon en espacios cerrados, parrillas de carbon usadas en interiores, y humo de tabaco (causa de exposicion cronica de bajo nivel). La intoxicacion es mas comun en invierno por el uso de calefaccion y en desastres naturales por el uso de generadores.",
    "agenteToxicoEn": "Carbon monoxide (CO), a gas produced by incomplete combustion. Main sources: faulty or poorly ventilated water heaters and furnaces, car engines in enclosed spaces, structural fires, portable gasoline generators, wood or charcoal stoves in enclosed spaces, charcoal grills used indoors, and cigarette smoke (cause of chronic low-level exposure). Poisoning is more common in winter due to heating use and during natural disasters due to generator use.",
    "mecanismoEs": "El CO se une a la hemoglobina con una afinidad 200-250 veces mayor que el oxigeno, formando carboxihemoglobina (COHb) que no puede transportar oxigeno. Esto reduce la capacidad de transporte de oxigeno de la sangre de forma proporcional al nivel de COHb. Ademas, el CO desplaza la curva de disociacion de oxihemoglobina hacia la izquierda, lo que significa que la hemoglobina restante no oxigenada libera el oxigeno con mayor dificultad a los tejidos. A nivel celular, el CO se une a la citocromo c oxidasa mitocondrial inhibiendo la cadena de transporte de electrones y la fosforilacion oxidativa, causando produccion de radicales libres y estres oxidativo. Tambien se une a la mioglobina cardiaca, contribuyendo a la disfuncion miocardica. El dano neurologico tardio se debe a peroxidacion lipidica, desmielinizacion y apoptosis neuronal mediada por mecanismos inflamatorios.",
    "mecanismoEn": "CO binds to hemoglobin with 200-250 times greater affinity than oxygen, forming carboxyhemoglobin (COHb) that cannot transport oxygen. This reduces the blood's oxygen-carrying capacity proportionally to the COHb level. Additionally, CO shifts the oxyhemoglobin dissociation curve to the left, meaning that remaining non-oxygenated hemoglobin releases oxygen with greater difficulty to tissues. At the cellular level, CO binds to mitochondrial cytochrome c oxidase, inhibiting the electron transport chain and oxidative phosphorylation, causing free radical production and oxidative stress. It also binds to cardiac myoglobin, contributing to myocardial dysfunction. Delayed neurological damage is due to lipid peroxidation, demyelination, and neuronal apoptosis mediated by inflammatory mechanisms.",
    "tratamientoEs": "La base del tratamiento es la administracion de oxigeno al 100% con mascarilla de no reinhalacion, que reduce la vida media de la COHb de 4-6 horas (respirando aire ambiente) a 60-90 minutos. El oxigeno hiperbarico (OHB) a 2.5-3 atmosferas reduce la vida media a 15-23 minutos y esta indicado en intoxicaciones severas: perdida de conciencia, COHb >25%, sintomas neurologicos, isquemia cardiaca, embarazo con COHb >15%, y sintomas persistentes tras 4-6 horas de oxigeno normbarico. Se debe monitorizar continuamente la funcion cardiaca con ECG y troponinas, ya que la toxicidad miocardica es comun. Las convulsiones se tratan con benzodiacepinas. Los pacientes deben ser observados durante al menos 6 horas y se debe realizar seguimiento neurologico a las 2-4 semanas para detectar el sindrome neurologico tardio.",
    "tratamientoEn": "The cornerstone of treatment is administration of 100% oxygen via non-rebreather mask, which reduces COHb half-life from 4-6 hours (breathing room air) to 60-90 minutes. Hyperbaric oxygen (HBO) at 2.5-3 atmospheres reduces the half-life to 15-23 minutes and is indicated in severe poisoning: loss of consciousness, COHb >25%, neurological symptoms, cardiac ischemia, pregnancy with COHb >15%, and persistent symptoms after 4-6 hours of normobaric oxygen. Cardiac function should be continuously monitored with ECG and troponins, as myocardial toxicity is common. Seizures are treated with benzodiazepines. Patients should be observed for at least 6 hours and neurological follow-up at 2-4 weeks should be performed to detect delayed neurological syndrome.",
    "antidotoEs": "No existe un antidoto farmacologico especifico. El oxigeno al 100% es el tratamiento principal, ya que compite con el CO por los sitios de union en la hemoglobina, acelerando la disociacion de la COHb. El oxigeno hiperbarico (OHB) potencia este efecto y ademas aumenta el oxigeno disuelto en plasma, proporciona oxigenacion tisular independiente de la hemoglobina, reduce el edema cerebral, y puede disminuir la incidencia del sindrome neurologico tardio. La decision de usar OHB debe tomarse en consulta con un centro de medicina hiperbarica.",
    "antidotoEn": "There is no specific pharmacological antidote. 100% oxygen is the primary treatment, as it competes with CO for binding sites on hemoglobin, accelerating COHb dissociation. Hyperbaric oxygen (HBO) enhances this effect and additionally increases plasma dissolved oxygen, provides tissue oxygenation independent of hemoglobin, reduces cerebral edema, and may decrease the incidence of delayed neurological syndrome. The decision to use HBO should be made in consultation with a hyperbaric medicine center.",
    "primerosAuxiliosEs": "Sacar a la persona del ambiente contaminado inmediatamente y llevarla al aire libre. El rescatista no debe entrar a espacios cerrados sospechosos sin proteccion respiratoria adecuada, ya que puede convertirse en otra victima. Llamar al servicio de emergencias (911). Si la persona esta inconsciente pero respira, colocarla en posicion lateral de seguridad. Si no respira, iniciar RCP. Administrar oxigeno al 100% si esta disponible. No encender cerillas ni aparatos electricos en el area si se sospecha fuga de gas. Abrir puertas y ventanas para ventilar el area. Toda persona expuesta debe ser evaluada en urgencias, incluso si los sintomas parecen leves.",
    "primerosAuxiliosEn": "Remove the person from the contaminated environment immediately and take them to fresh air. The rescuer should not enter suspicious enclosed spaces without adequate respiratory protection, as they can become another victim. Call emergency services (911). If the person is unconscious but breathing, place them in the recovery position. If not breathing, begin CPR. Administer 100% oxygen if available. Do not light matches or turn on electrical devices in the area if a gas leak is suspected. Open doors and windows to ventilate the area. Every exposed person should be evaluated in the emergency department, even if symptoms seem mild.",
    "prevencionEs": "Instalar detectores de monoxido de carbono en todos los niveles de la vivienda, especialmente cerca de dormitorios, y cambiar las baterias regularmente. Realizar mantenimiento anual de calentadores, calderas, chimeneas y sistemas de calefaccion. Nunca usar generadores electricos, parrillas de carbon, estufas de campamento o vehiculos en marcha dentro de la casa, garaje o cualquier espacio cerrado. No calentar la casa con la estufa del horno. Asegurar ventilacion adecuada en areas donde se usen aparatos de combustion. En caso de corte de electricidad, usar generadores solo en exteriores a mas de 6 metros de puertas y ventanas.",
    "prevencionEn": "Install carbon monoxide detectors on every level of the home, especially near bedrooms, and replace batteries regularly. Perform annual maintenance on water heaters, furnaces, chimneys, and heating systems. Never use electric generators, charcoal grills, camping stoves, or running vehicles inside the house, garage, or any enclosed space. Do not heat the house with the oven stove. Ensure adequate ventilation in areas where combustion appliances are used. In case of power outage, use generators only outdoors more than 20 feet from doors and windows."
  },
  {
    "id": "intoxicacion-etanol",
    "nombreEs": "Intoxicacion por Etanol (Alcohol)",
    "nombreEn": "Alcohol (Ethanol) Intoxication",
    "categoriaEs": "Sustancias",
    "categoriaEn": "Substances",
    "descripcionEs": "La intoxicacion aguda por etanol es la causa mas comun de intoxicacion atendida en servicios de urgencias a nivel mundial. El etanol es un depresor del sistema nervioso central que afecta multiples sistemas de neurotransmisores, principalmente potenciando la accion del acido gamma-aminobutirico (GABA) e inhibiendo los receptores de N-metil-D-aspartato (NMDA) del glutamato. La gravedad de la intoxicacion depende de la concentracion sanguinea de alcohol, la tolerancia individual, la velocidad de ingestion y la presencia de coingestiones. La intoxicacion severa puede causar depresion respiratoria, aspiracion, hipotermia y muerte. El alcoholismo cronico conlleva riesgos adicionales incluyendo hepatopatia, pancreatitis, neuropatia, encefalopatia de Wernicke-Korsakoff y sindrome de abstinencia potencialmente mortal.",
    "descripcionEn": "Acute ethanol intoxication is the most common cause of poisoning treated in emergency departments worldwide. Ethanol is a central nervous system depressant that affects multiple neurotransmitter systems, primarily potentiating gamma-aminobutyric acid (GABA) action and inhibiting N-methyl-D-aspartate (NMDA) glutamate receptors. The severity of intoxication depends on blood alcohol concentration, individual tolerance, speed of ingestion, and the presence of co-ingestions. Severe intoxication can cause respiratory depression, aspiration, hypothermia, and death. Chronic alcoholism carries additional risks including liver disease, pancreatitis, neuropathy, Wernicke-Korsakoff encephalopathy, and potentially fatal withdrawal syndrome.",
    "sintomasEs": [
      "Euforia, desinhibicion y deterioro del juicio (alcoholemia 50-100 mg/dL)",
      "Disartria (habla arrastrada) y ataxia (incoordinacion motora)",
      "Nauseas, vomitos y dolor abdominal",
      "Nistagmo (movimientos involuntarios de los ojos)",
      "Vision doble (diplopia) y vision borrosa",
      "Hipotermia por vasodilatacion periferica",
      "Hipoglucemia, especialmente en ninos y bebedores cronicos desnutridos",
      "Depresion respiratoria con alcoholemia >300-400 mg/dL",
      "Estupor, coma y arreflexia en intoxicacion severa",
      "Riesgo de aspiracion de vomito con obstruccion de via aerea"
    ],
    "sintomasEn": [
      "Euphoria, disinhibition, and impaired judgment (BAC 50-100 mg/dL)",
      "Dysarthria (slurred speech) and ataxia (motor incoordination)",
      "Nausea, vomiting, and abdominal pain",
      "Nystagmus (involuntary eye movements)",
      "Double vision (diplopia) and blurred vision",
      "Hypothermia from peripheral vasodilation",
      "Hypoglycemia, especially in children and malnourished chronic drinkers",
      "Respiratory depression with BAC >300-400 mg/dL",
      "Stupor, coma, and areflexia in severe intoxication",
      "Risk of vomit aspiration with airway obstruction"
    ],
    "agenteToxicoEs": "Etanol (alcohol etilico, C2H5OH), presente en bebidas alcoholicas, productos de limpieza, enjuagues bucales y perfumes. Las bebidas alcoholicas varian en concentracion: cerveza (3-12%), vino (9-16%), licores destilados (20-50%). Un trago estandar contiene aproximadamente 14 gramos de etanol puro. La dosis letal se estima en 5-8 g/kg, correspondiente a una alcoholemia de 400-500 mg/dL en personas sin tolerancia, aunque bebedores cronicos pueden tolerar niveles mucho mas altos. Los ninos son especialmente vulnerables por su menor masa corporal y menor actividad de alcohol deshidrogenasa.",
    "agenteToxicoEn": "Ethanol (ethyl alcohol, C2H5OH), found in alcoholic beverages, cleaning products, mouthwashes, and perfumes. Alcoholic beverages vary in concentration: beer (3-12%), wine (9-16%), distilled spirits (20-50%). A standard drink contains approximately 14 grams of pure ethanol. The lethal dose is estimated at 5-8 g/kg, corresponding to a BAC of 400-500 mg/dL in non-tolerant individuals, although chronic drinkers may tolerate much higher levels. Children are especially vulnerable due to their lower body mass and lower alcohol dehydrogenase activity.",
    "mecanismoEs": "El etanol potencia la neurotransmision inhibitoria GABAergica al actuar como modulador alosterico positivo del receptor GABA-A, aumentando la frecuencia de apertura del canal de cloro y produciendo sedacion, ansiolisis y depresion del SNC. Simultaneamente, inhibe los receptores NMDA del glutamato, reduciendo la neurotransmision excitatoria. A nivel del sistema de recompensa, estimula la liberacion de dopamina en el nucleo accumbens, mediando los efectos de refuerzo positivo. El etanol se metaboliza principalmente en el higado: la alcohol deshidrogenasa (ADH) lo convierte en acetaldehido (toxico), y la aldehido deshidrogenasa (ALDH) lo convierte en acetato. El metabolismo sigue una cinetica de orden cero a concentraciones elevadas, eliminando aproximadamente 15-20 mg/dL por hora. El acetaldehido contribuye a los efectos toxicos agudos y cronicos, incluyendo el rubor facial, nauseas y dano hepatico.",
    "mecanismoEn": "Ethanol potentiates inhibitory GABAergic neurotransmission by acting as a positive allosteric modulator of the GABA-A receptor, increasing chloride channel opening frequency and producing sedation, anxiolysis, and CNS depression. Simultaneously, it inhibits NMDA glutamate receptors, reducing excitatory neurotransmission. At the reward system level, it stimulates dopamine release in the nucleus accumbens, mediating positive reinforcement effects. Ethanol is primarily metabolized in the liver: alcohol dehydrogenase (ADH) converts it to acetaldehyde (toxic), and aldehyde dehydrogenase (ALDH) converts it to acetate. Metabolism follows zero-order kinetics at elevated concentrations, eliminating approximately 15-20 mg/dL per hour. Acetaldehyde contributes to acute and chronic toxic effects, including facial flushing, nausea, and liver damage.",
    "tratamientoEs": "El manejo de la intoxicacion aguda es fundamentalmente de soporte. La prioridad es proteger la via aerea, especialmente en pacientes con depresion del nivel de conciencia y riesgo de aspiracion: posicion lateral de seguridad si no se requiere intubacion, succion orofaringea, e intubacion endotraqueal si hay compromiso ventilatorio o GCS menor de 8. Monitorizar la glucemia y corregir la hipoglucemia con dextrosa IV (50 mL de dextrosa al 50% en adultos). Administrar tiamina 100 mg IV antes de la dextrosa en bebedores cronicos para prevenir la encefalopatia de Wernicke. Corregir la deshidratacion con fluidos intravenosos. Monitorizar electrolitos, especialmente magnesio y potasio. No existe indicacion para el lavado gastrico o carbon activado en la intoxicacion por etanol puro. En intoxicacion severa (alcoholemia >400 mg/dL), considerar hemodialisis. Es fundamental descartar coingestiones, traumatismos craneoencefalicos y otras causas de alteracion del nivel de conciencia.",
    "tratamientoEn": "Management of acute intoxication is fundamentally supportive. The priority is airway protection, especially in patients with depressed level of consciousness and aspiration risk: recovery position if intubation is not required, oropharyngeal suctioning, and endotracheal intubation if ventilatory compromise or GCS less than 8. Monitor blood glucose and correct hypoglycemia with IV dextrose (50 mL of 50% dextrose in adults). Administer thiamine 100 mg IV before dextrose in chronic drinkers to prevent Wernicke encephalopathy. Correct dehydration with intravenous fluids. Monitor electrolytes, especially magnesium and potassium. There is no indication for gastric lavage or activated charcoal in pure ethanol intoxication. In severe intoxication (BAC >400 mg/dL), consider hemodialysis. It is fundamental to rule out co-ingestions, head trauma, and other causes of altered level of consciousness.",
    "antidotoEs": "No existe un antidoto especifico para la intoxicacion por etanol. El tratamiento es exclusivamente de soporte. Nota importante: en la intoxicacion por alcoholes toxicos (metanol, etilenglicol), el etanol paradojicamente se usa como antidoto competitivo de la alcohol deshidrogenasa, aunque el fomepizol (4-metilpirazol) es el antidoto preferido actualmente. El flumazenil (antagonista de benzodiacepinas) NO esta indicado y puede precipitar convulsiones en coingestiones. La naloxona solo es util si hay coingesion de opioides.",
    "antidotoEn": "There is no specific antidote for ethanol intoxication. Treatment is exclusively supportive. Important note: in toxic alcohol poisoning (methanol, ethylene glycol), ethanol is paradoxically used as a competitive antidote for alcohol dehydrogenase, although fomepizole (4-methylpyrazole) is the currently preferred antidote. Flumazenil (benzodiazepine antagonist) is NOT indicated and may precipitate seizures in co-ingestions. Naloxone is only useful if opioid co-ingestion is suspected.",
    "primerosAuxiliosEs": "Si la persona esta consciente y alerta, mantenerla en un ambiente seguro, calido y supervisado. No dejarla sola. Si esta vomitando, colocarla en posicion lateral de seguridad para prevenir aspiracion. No inducir el vomito. No administrar cafe, duchas frias ni intentar hacer caminar a la persona (estos remedios populares no ayudan y pueden causar dano). Si la persona esta inconsciente, no responde a estimulos, tiene respiracion lenta (menos de 8 por minuto), pausas respiratorias, piel fria y humeda, o convulsiones, llamar al 911 inmediatamente. Monitorizar la respiracion continuamente mientras se espera la ayuda. Si la respiracion se detiene, iniciar RCP.",
    "primerosAuxiliosEn": "If the person is conscious and alert, keep them in a safe, warm, and supervised environment. Do not leave them alone. If vomiting, place in the recovery position to prevent aspiration. Do not induce vomiting. Do not administer coffee, cold showers, or try to make the person walk (these folk remedies do not help and may cause harm). If the person is unconscious, unresponsive to stimuli, has slow breathing (less than 8 per minute), respiratory pauses, cold and clammy skin, or seizures, call 911 immediately. Monitor breathing continuously while waiting for help. If breathing stops, begin CPR.",
    "prevencionEs": "Beber con moderacion: no mas de 2 tragos estandar al dia para hombres y 1 para mujeres. No beber con el estomago vacio. Alternar bebidas alcoholicas con agua. No mezclar alcohol con medicamentos, especialmente sedantes, opioides y antihistaminicos. Nunca conducir despues de beber. Designar un conductor sobrio. Supervisar a adolescentes y jovenes en eventos sociales. Buscar ayuda profesional si se tiene dificultad para controlar el consumo de alcohol. Conocer los signos de intoxicacion severa y actuar rapidamente.",
    "prevencionEn": "Drink in moderation: no more than 2 standard drinks per day for men and 1 for women. Do not drink on an empty stomach. Alternate alcoholic beverages with water. Do not mix alcohol with medications, especially sedatives, opioids, and antihistamines. Never drive after drinking. Designate a sober driver. Supervise adolescents and young adults at social events. Seek professional help if you have difficulty controlling alcohol consumption. Know the signs of severe intoxication and act quickly."
  },
  {
    "id": "mordedura-serpiente",
    "nombreEs": "Mordedura de Serpiente (Envenenamiento Ofidico)",
    "nombreEn": "Snakebite Envenomation",
    "categoriaEs": "Animal",
    "categoriaEn": "Animal",
    "descripcionEs": "El envenenamiento ofidico es una emergencia medica causada por la inyeccion de veneno a traves de la mordedura de serpientes venenosas. La Organizacion Mundial de la Salud lo clasifica como una enfermedad tropical desatendida que afecta a entre 1.8 y 2.7 millones de personas anualmente, causando hasta 138,000 muertes al ano, principalmente en regiones rurales de Asia, Africa y America Latina. Los venenos de serpiente son mezclas complejas de proteinas y peptidos que incluyen enzimas proteoliticas, fosfolipasas, metaloproteinas y neurotoxinas, cuya composicion varia segun la especie. Los efectos principales incluyen toxicidad local (necrosis tisular), coagulopatia, neurotoxicidad y nefrotoxicidad. El diagnostico se basa en la historia clinica, identificacion de la serpiente cuando es posible, y evaluacion clinica y de laboratorio. El tratamiento oportuno con antiveneno especifico es fundamental para reducir la mortalidad y morbilidad.",
    "descripcionEn": "Snakebite envenomation is a medical emergency caused by the injection of venom through the bite of venomous snakes. The World Health Organization classifies it as a neglected tropical disease affecting between 1.8 and 2.7 million people annually, causing up to 138,000 deaths per year, mainly in rural regions of Asia, Africa, and Latin America. Snake venoms are complex mixtures of proteins and peptides including proteolytic enzymes, phospholipases, metalloproteases, and neurotoxins, whose composition varies by species. The main effects include local toxicity (tissue necrosis), coagulopathy, neurotoxicity, and nephrotoxicity. Diagnosis is based on clinical history, identification of the snake when possible, and clinical and laboratory evaluation. Timely treatment with specific antivenom is fundamental to reducing mortality and morbidity.",
    "sintomasEs": [
      "Dolor intenso, edema y eritema progresivo en el sitio de la mordedura",
      "Marcas de colmillos visibles (uno o dos puntos de entrada)",
      "Equimosis, ampollas hemorragicas y necrosis tisular local",
      "Sangrado espontaneo de encias, nariz, sitios de venopuncion (coagulopatia)",
      "Ptosis palpebral, diplopia y disfagia (envenenamiento neurotoxico — elapidos)",
      "Paralisis muscular descendente que puede afectar la respiracion",
      "Orina oscura o rojiza por rabdomiolisis o hemolisis",
      "Hipotension, taquicardia y shock",
      "Insuficiencia renal aguda",
      "Sindrome compartimental en extremidades severamente inflamadas"
    ],
    "sintomasEn": [
      "Intense pain, progressive edema, and erythema at the bite site",
      "Visible fang marks (one or two puncture points)",
      "Ecchymosis, hemorrhagic blisters, and local tissue necrosis",
      "Spontaneous bleeding from gums, nose, venipuncture sites (coagulopathy)",
      "Palpebral ptosis, diplopia, and dysphagia (neurotoxic envenomation — elapids)",
      "Descending muscular paralysis that may affect breathing",
      "Dark or reddish urine from rhabdomyolysis or hemolysis",
      "Hypotension, tachycardia, and shock",
      "Acute renal failure",
      "Compartment syndrome in severely swollen extremities"
    ],
    "agenteToxicoEs": "Veneno de serpiente. Las principales familias de serpientes venenosas incluyen: Viperidae (viboras y crotalaidos — cascabel, nauyaca/terciopelo/barba amarilla, moccasin), cuyos venenos son predominantemente hemotoxicos y citotoxicos; Elapidae (corales, cobras, mambas, taipanes), con venenos predominantemente neurotoxicos; y Hydrophiidae (serpientes marinas), con venenos miotoxicos y neurotoxicos. En America Latina, las mordeduras mas frecuentes son por crotalaidos del genero Bothrops (nauyaca, jararaca), Crotalus (cascabel) y Micrurus (coral). La cantidad de veneno inyectado varia: hasta el 25% de las mordeduras son secas (sin inyeccion de veneno).",
    "agenteToxicoEn": "Snake venom. The main families of venomous snakes include: Viperidae (vipers and crotalids — rattlesnakes, fer-de-lance/terciopelo, water moccasins), whose venoms are predominantly hemotoxic and cytotoxic; Elapidae (coral snakes, cobras, mambas, taipans), with predominantly neurotoxic venoms; and Hydrophiidae (sea snakes), with myotoxic and neurotoxic venoms. In Latin America, the most frequent bites are from crotalids of the genus Bothrops (fer-de-lance, jararaca), Crotalus (rattlesnake), and Micrurus (coral snake). The amount of venom injected varies: up to 25% of bites are dry (no venom injection).",
    "mecanismoEs": "Los venenos de serpiente contienen multiples componentes bioactivos. Las metaloproteinas de zinc (como las hemorraginas) degradan componentes de la membrana basal vascular y la matriz extracelular, causando hemorragia y necrosis tisular. Las fosfolipasas A2 destruyen membranas celulares, causan hemolisis y mionecrosis, y tienen actividad neurotoxica presinaptica (beta-bungarotoxina, notexina). Las serinoproteasas tipo trombina activan la cascada de coagulacion consumiendo fibrinogeno y factores de coagulacion, produciendo coagulopatia de consumo. Las neurotoxinas alfa (postsinapticas) bloquean competitivamente los receptores nicotinicos de acetilcolina en la placa neuromuscular, causando paralisis flacida. Las miotoxinas causan rabdomiolisis. Las citotoxinas y fosfolipasas causan dano tisular local directo. Muchos venenos tienen accion sinergica entre sus componentes.",
    "mecanismoEn": "Snake venoms contain multiple bioactive components. Zinc metalloproteases (such as hemorrhagins) degrade components of the vascular basement membrane and extracellular matrix, causing hemorrhage and tissue necrosis. Phospholipases A2 destroy cell membranes, cause hemolysis and myonecrosis, and have presynaptic neurotoxic activity (beta-bungarotoxin, notexin). Thrombin-like serine proteases activate the coagulation cascade by consuming fibrinogen and clotting factors, producing consumption coagulopathy. Alpha neurotoxins (postsynaptic) competitively block nicotinic acetylcholine receptors at the neuromuscular junction, causing flaccid paralysis. Myotoxins cause rhabdomyolysis. Cytotoxins and phospholipases cause direct local tissue damage. Many venoms have synergistic action between their components.",
    "tratamientoEs": "El tratamiento principal es la administracion de antiveneno especifico, que debe ser el apropiado para la especie de serpiente involucrada o un antiveneno polivalente regional. Se administra por via intravenosa diluido en solucion salina en infusion lenta, con disponibilidad de epinefrina para tratar posibles reacciones anafilacticas. La dosis depende de la severidad del envenenamiento y no del peso del paciente (el antiveneno neutraliza el veneno, no depende del tamano corporal). Se debe inmovilizar la extremidad afectada a nivel del corazon y proporcionar analgesia. Monitorizar la coagulacion con tiempo de protrombina, fibrinogeno, plaquetas y dimero D cada 6 horas. Administrar fluidos IV para mantener la perfusion renal y prevenir la nefrotoxicidad. La fasciotomia solo esta indicada si se documenta presion compartimental elevada. Actualizar la vacunacion antitetanica. Los antibioticos profilacticos son controvertidos pero pueden considerarse en mordeduras con necrosis extensa. La rehabilitacion puede ser prolongada en casos con necrosis tisular significativa.",
    "tratamientoEn": "The primary treatment is administration of specific antivenom, which should be appropriate for the snake species involved or a regional polyvalent antivenom. It is administered intravenously diluted in normal saline as a slow infusion, with epinephrine available to treat possible anaphylactic reactions. The dose depends on the severity of envenomation and not on the patient's weight (antivenom neutralizes the venom, not dependent on body size). The affected extremity should be immobilized at heart level and analgesia provided. Monitor coagulation with prothrombin time, fibrinogen, platelets, and D-dimer every 6 hours. Administer IV fluids to maintain renal perfusion and prevent nephrotoxicity. Fasciotomy is only indicated if elevated compartmental pressure is documented. Update tetanus vaccination. Prophylactic antibiotics are controversial but may be considered in bites with extensive necrosis. Rehabilitation may be prolonged in cases with significant tissue necrosis.",
    "antidotoEs": "Antiveneno (suero antiofidico) especifico para la especie de serpiente o polivalente regional. En Mexico se utiliza el Antivipmyn (polivalente para viperidos) y Coralmyn (para corales). En EE.UU. se dispone de CroFab (polivalente para crotalidos) y Anavip. La dosis inicial tipica es de 4-6 viales para envenenamiento moderado y 8-12 viales para envenenamiento severo, con dosis adicionales segun la progresion clinica. El antiveneno es mas efectivo cuando se administra en las primeras 4-6 horas, pero puede ser beneficioso hasta 24 horas o mas despues de la mordedura, especialmente para coagulopatia. Siempre administrar en un entorno hospitalario preparado para manejar anafilaxia.",
    "antidotoEn": "Antivenom (antiophidic serum) specific to the snake species or regional polyvalent. In Mexico, Antivipmyn (polyvalent for viperids) and Coralmyn (for coral snakes) are used. In the US, CroFab (polyvalent for crotalids) and Anavip are available. The typical initial dose is 4-6 vials for moderate envenomation and 8-12 vials for severe envenomation, with additional doses based on clinical progression. Antivenom is most effective when administered within the first 4-6 hours but may be beneficial up to 24 hours or more after the bite, especially for coagulopathy. Always administer in a hospital setting prepared to manage anaphylaxis.",
    "primerosAuxiliosEs": "Mantener la calma y alejarse de la serpiente. Inmovilizar la extremidad afectada en posicion neutra a nivel del corazon, como si fuera una fractura, para reducir la diseminacion del veneno por via linfatica. Retirar anillos, relojes y ropa ajustada antes de que aparezca la inflamacion. Tomar una fotografia de la serpiente si es posible hacerlo de forma segura, para facilitar la identificacion. Transportar al paciente al hospital mas cercano que disponga de antiveneno lo antes posible. NO aplicar torniquetes, NO hacer incisiones ni succionar el veneno, NO aplicar hielo, NO dar bebidas alcoholicas, y NO usar dispositivos de succion comerciales. Estas practicas son ineficaces y pueden empeorar el dano tisular. Marcar el borde del edema con un marcador y la hora para monitorizar la progresion.",
    "primerosAuxiliosEn": "Stay calm and move away from the snake. Immobilize the affected extremity in a neutral position at heart level, as if it were a fracture, to reduce venom spread via the lymphatic system. Remove rings, watches, and tight clothing before swelling develops. Take a photograph of the snake if it can be done safely, to facilitate identification. Transport the patient to the nearest hospital with antivenom as quickly as possible. Do NOT apply tourniquets, do NOT make incisions or suck the venom, do NOT apply ice, do NOT give alcoholic beverages, and do NOT use commercial suction devices. These practices are ineffective and may worsen tissue damage. Mark the edge of edema with a marker and the time to monitor progression.",
    "prevencionEs": "Usar botas altas y pantalones largos al caminar en areas con vegetacion, especialmente en zonas rurales tropicales y subtropicales. Usar una linterna al caminar de noche. Mirar antes de poner las manos o los pies en lugares oscuros, entre rocas, troncos o vegetacion densa. Sacudir la ropa y el calzado antes de ponerselos cuando se esta en el campo. No molestar, atrapar ni intentar matar serpientes. Mantener los alrededores de las viviendas limpios de maleza, basura y escombros que sirvan de refugio para roedores y serpientes. Sellar grietas y aberturas en paredes y pisos de las viviendas. Conocer las serpientes venenosas de la region y saber donde se encuentra el centro de salud mas cercano con antiveneno.",
    "prevencionEn": "Wear tall boots and long pants when walking in vegetated areas, especially in rural tropical and subtropical zones. Use a flashlight when walking at night. Look before placing hands or feet in dark places, among rocks, logs, or dense vegetation. Shake out clothing and footwear before putting them on when in the field. Do not disturb, capture, or attempt to kill snakes. Keep the surroundings of dwellings clear of brush, trash, and debris that serve as shelter for rodents and snakes. Seal cracks and openings in walls and floors of dwellings. Know the venomous snakes of the region and know where the nearest health center with antivenom is located."
  },
  {
    "id": "intoxicacion-plomo",
    "nombreEs": "Intoxicacion por Plomo (Saturnismo)",
    "nombreEn": "Lead Poisoning (Plumbism)",
    "categoriaEs": "Metales pesados",
    "categoriaEn": "Heavy metals",
    "descripcionEs": "La intoxicacion por plomo es una enfermedad sistemica causada por la acumulacion de plomo en el organismo. Es un problema de salud publica importante que afecta principalmente a ninos menores de 6 anos, en quienes incluso niveles bajos de exposicion causan dano neurologico irreversible. El plomo no tiene funcion biologica conocida y es toxico a cualquier nivel de exposicion; actualmente se reconoce que no existe un umbral seguro de plomo en sangre. Las fuentes de exposicion incluyen pinturas a base de plomo en viviendas antiguas (principal fuente en ninos), agua contaminada por tuberias de plomo, suelo contaminado, exposicion ocupacional (fundiciones, fabricas de baterias, mineria), ceramica vidriada artesanal, cosmeticos tradicionales y remedios herbales de ciertas culturas. La intoxicacion puede ser aguda o cronica, siendo la cronica la forma mas comun y peligrosa por su naturaleza insidiosa.",
    "descripcionEn": "Lead poisoning is a systemic disease caused by the accumulation of lead in the body. It is a major public health problem primarily affecting children under 6 years of age, in whom even low levels of exposure cause irreversible neurological damage. Lead has no known biological function and is toxic at any level of exposure; it is currently recognized that there is no safe blood lead level. Sources of exposure include lead-based paint in older homes (primary source in children), contaminated water from lead pipes, contaminated soil, occupational exposure (smelters, battery factories, mining), artisanal glazed ceramics, traditional cosmetics, and herbal remedies from certain cultures. Poisoning can be acute or chronic, with chronic being the most common and dangerous form due to its insidious nature.",
    "sintomasEs": [
      "En ninos: retraso del desarrollo neurologico, dificultades de aprendizaje y problemas de conducta",
      "Irritabilidad, letargia y disminucion del nivel de actividad",
      "Dolor abdominal colico recurrente (colico saturnino)",
      "Anorexia, nauseas, vomitos y estrenimiento",
      "Cefalea cronica y dificultad de concentracion",
      "Linea de Burton (linea gris-azulada en las encias) en exposicion cronica",
      "Anemia microcitica e hipocromica con punteado basofilo en eritrocitos",
      "Neuropatia periferica con debilidad de extensores (mano caida)",
      "Nefropatia cronica con dano tubular renal",
      "Encefalopatia plumbica en intoxicacion severa: convulsiones, edema cerebral y coma (emergencia medica)"
    ],
    "sintomasEn": [
      "In children: neurodevelopmental delay, learning difficulties, and behavioral problems",
      "Irritability, lethargy, and decreased activity level",
      "Recurrent colicky abdominal pain (saturnine colic)",
      "Anorexia, nausea, vomiting, and constipation",
      "Chronic headache and difficulty concentrating",
      "Burton line (gray-blue line on the gums) in chronic exposure",
      "Microcytic hypochromic anemia with basophilic stippling in erythrocytes",
      "Peripheral neuropathy with extensor weakness (wrist drop)",
      "Chronic nephropathy with renal tubular damage",
      "Lead encephalopathy in severe poisoning: seizures, cerebral edema, and coma (medical emergency)"
    ],
    "agenteToxicoEs": "Plomo (Pb), metal pesado ubicuo en el medio ambiente por siglos de uso industrial. Fuentes de exposicion: pintura con plomo en casas construidas antes de 1978 (principal fuente en ninos por ingestion de escamas y polvo de pintura), tuberias y soldaduras de plomo que contaminan el agua potable, suelo contaminado cerca de carreteras y zonas industriales, ceramica vidriada artesanal (ollas de barro), dulces importados con envoltorios de plomo, cosmeticos tradicionales (kohl, surma), remedios herbales (azarcon, greta), municiones y pesas de pesca, exposicion ocupacional en fundiciones, fabricas de baterias, reciclaje informal de metales y soldadura. En ninos, la pica (ingestion de sustancias no alimentarias) aumenta significativamente el riesgo.",
    "agenteToxicoEn": "Lead (Pb), a heavy metal ubiquitous in the environment from centuries of industrial use. Exposure sources: lead-based paint in homes built before 1978 (primary source in children from ingestion of paint chips and dust), lead pipes and solder contaminating drinking water, contaminated soil near highways and industrial areas, artisanal glazed ceramics (clay pots), imported candies with lead wrappers, traditional cosmetics (kohl, surma), herbal remedies (azarcon, greta), ammunition and fishing weights, occupational exposure in smelters, battery factories, informal metal recycling, and soldering. In children, pica (ingestion of non-food substances) significantly increases risk.",
    "mecanismoEs": "El plomo ejerce su toxicidad a traves de multiples mecanismos. Mimetiza al calcio y al zinc, interfiriendo con procesos dependientes de estos iones: inhibe la liberacion de neurotransmisores (alterando los canales de calcio presinapticos), afecta la sinaptogenesis y la poda sinaptica durante el desarrollo cerebral, e interfiere con enzimas dependientes de zinc como la acido delta-aminolevulinico deshidratasa (ALAD) y la ferroquelatasa, inhibiendo la sintesis del grupo hemo y causando anemia. A nivel del SNC, el plomo dana la barrera hematoencefalica (especialmente inmadura en ninos), produce estres oxidativo, activa la apoptosis neuronal y altera la mielinizacion. A nivel renal, causa dano tubular proximal y nefritis intersticial cronica. Inhibe la Na-K-ATPasa causando hipertension. El plomo se almacena predominantemente en hueso (95% en adultos), desde donde puede ser liberado durante el embarazo, lactancia, menopausia o fracturas.",
    "mecanismoEn": "Lead exerts its toxicity through multiple mechanisms. It mimics calcium and zinc, interfering with processes dependent on these ions: it inhibits neurotransmitter release (altering presynaptic calcium channels), affects synaptogenesis and synaptic pruning during brain development, and interferes with zinc-dependent enzymes such as delta-aminolevulinic acid dehydratase (ALAD) and ferrochelatase, inhibiting heme group synthesis and causing anemia. At the CNS level, lead damages the blood-brain barrier (especially immature in children), produces oxidative stress, activates neuronal apoptosis, and alters myelination. At the renal level, it causes proximal tubular damage and chronic interstitial nephritis. It inhibits Na-K-ATPase causing hypertension. Lead is stored predominantly in bone (95% in adults), from where it can be released during pregnancy, lactation, menopause, or fractures.",
    "tratamientoEs": "El pilar fundamental del tratamiento es la identificacion y eliminacion de la fuente de exposicion. La terapia de quelacion se indica segun los niveles de plomo en sangre: para niveles de 45-69 mcg/dL se utiliza succimero (acido dimercaptosuccinico, DMSA) por via oral, 10 mg/kg cada 8 horas por 5 dias, luego cada 12 horas por 14 dias. Para niveles mayores o igual a 70 mcg/dL o encefalopatia, se requiere quelacion parenteral con dimercaprol (BAL) 75 mg/m2 IM cada 4 horas por 5 dias, iniciando 4 horas antes de agregar edetato calcico disodico (CaNa2EDTA) 1500 mg/m2/dia IV en infusion continua por 5 dias. La encefalopatia plumbica requiere manejo en UCI con control de convulsiones (benzodiacepinas), reduccion de la presion intracraneal (manitol, dexametasona), y prevencion de la insuficiencia renal con hidratacion adecuada. Asegurar una ingesta adecuada de calcio, hierro y vitamina C, ya que las deficiencias de estos nutrientes aumentan la absorcion de plomo.",
    "tratamientoEn": "The fundamental pillar of treatment is identification and removal of the exposure source. Chelation therapy is indicated based on blood lead levels: for levels of 45-69 mcg/dL, succimer (dimercaptosuccinic acid, DMSA) is used orally, 10 mg/kg every 8 hours for 5 days, then every 12 hours for 14 days. For levels greater than or equal to 70 mcg/dL or encephalopathy, parenteral chelation with dimercaprol (BAL) 75 mg/m2 IM every 4 hours for 5 days is required, starting 4 hours before adding calcium disodium edetate (CaNa2EDTA) 1500 mg/m2/day IV continuous infusion for 5 days. Lead encephalopathy requires ICU management with seizure control (benzodiazepines), intracranial pressure reduction (mannitol, dexamethasone), and prevention of renal failure with adequate hydration. Ensure adequate intake of calcium, iron, and vitamin C, as deficiencies of these nutrients increase lead absorption.",
    "antidotoEs": "Los agentes quelantes son el tratamiento especifico: Succimero (DMSA): quelante oral de primera linea para intoxicacion moderada (plomo 45-69 mcg/dL). Es efectivo, bien tolerado y puede usarse ambulatoriamente. Dimercaprol (BAL): quelante parenteral para intoxicacion severa o encefalopatia. Se administra IM, es doloroso y tiene efectos adversos significativos (hipertension, taquicardia, nauseas). Contraindicado en alergia al cacahuate (vehiculo es aceite de cacahuate) y en insuficiencia hepatica. Edetato calcico disodico (CaNa2EDTA): quelante IV que se usa en combinacion con BAL en casos severos. Nunca usar EDTA sin calcio, ya que puede causar hipocalcemia fatal. La penicilamina es una alternativa oral de segunda linea pero tiene mas efectos adversos.",
    "antidotoEn": "Chelating agents are the specific treatment: Succimer (DMSA): first-line oral chelator for moderate poisoning (lead 45-69 mcg/dL). It is effective, well-tolerated, and can be used on an outpatient basis. Dimercaprol (BAL): parenteral chelator for severe poisoning or encephalopathy. Administered IM, it is painful and has significant adverse effects (hypertension, tachycardia, nausea). Contraindicated in peanut allergy (vehicle is peanut oil) and hepatic insufficiency. Calcium disodium edetate (CaNa2EDTA): IV chelator used in combination with BAL in severe cases. Never use EDTA without calcium, as it can cause fatal hypocalcemia. Penicillamine is a second-line oral alternative but has more adverse effects.",
    "primerosAuxiliosEs": "La intoxicacion por plomo generalmente es cronica y no requiere primeros auxilios agudos. Sin embargo, si se sospecha ingestion aguda de un objeto con plomo (como una pieza de joyeria, peso de pesca o fragmento de pintura): llevar al nino a urgencias inmediatamente. No inducir el vomito. Se debe realizar una radiografia abdominal para localizar el objeto. Si hay signos de encefalopatia aguda (convulsiones, letargia extrema, vomitos persistentes en un nino con exposicion conocida al plomo), es una emergencia medica que requiere atencion inmediata. Llamar al centro de control de intoxicaciones. Si se descubre exposicion ambiental al plomo (pintura descascarada, agua contaminada), contactar al departamento de salud local para evaluacion del hogar.",
    "primerosAuxiliosEn": "Lead poisoning is generally chronic and does not require acute first aid. However, if acute ingestion of a lead-containing object is suspected (such as a piece of jewelry, fishing weight, or paint chip): take the child to the emergency department immediately. Do not induce vomiting. An abdominal X-ray should be performed to locate the object. If there are signs of acute encephalopathy (seizures, extreme lethargy, persistent vomiting in a child with known lead exposure), it is a medical emergency requiring immediate attention. Call poison control. If environmental lead exposure is discovered (peeling paint, contaminated water), contact the local health department for home evaluation.",
    "prevencionEs": "Realizar pruebas de deteccion de plomo en sangre a todos los ninos a los 12 y 24 meses de edad, especialmente en viviendas construidas antes de 1978. Inspeccionar y remediar profesionalmente la pintura con plomo en viviendas antiguas; nunca lijar o raspar pintura con plomo sin proteccion. Dejar correr el agua fria durante 30-60 segundos antes de usarla para cocinar o beber si las tuberias son antiguas. Usar agua fria (no caliente) para cocinar, ya que el agua caliente disuelve mas plomo. Lavar frecuentemente las manos y juguetes de los ninos. Asegurar una dieta rica en calcio, hierro y vitamina C. Usar equipo de proteccion personal en trabajos con plomo y no llevar ropa de trabajo a casa. Evitar el uso de ceramica vidriada artesanal para cocinar o almacenar alimentos acidos.",
    "prevencionEn": "Perform blood lead screening tests on all children at 12 and 24 months of age, especially in homes built before 1978. Professionally inspect and remediate lead paint in older homes; never sand or scrape lead paint without protection. Run cold water for 30-60 seconds before using it for cooking or drinking if pipes are old. Use cold water (not hot) for cooking, as hot water dissolves more lead. Frequently wash children's hands and toys. Ensure a diet rich in calcium, iron, and vitamin C. Use personal protective equipment in lead-related work and do not bring work clothes home. Avoid using artisanal glazed ceramics for cooking or storing acidic foods."
  },
  {
    "id": "intoxicacion-benzodiacepinas",
    "nombreEs": "Intoxicacion por Benzodiacepinas",
    "nombreEn": "Benzodiazepine Overdose",
    "categoriaEs": "Medicamentosa",
    "categoriaEn": "Medication-related",
    "descripcionEs": "La intoxicacion por benzodiacepinas es una causa frecuente de consulta en urgencias toxicologicas. Las benzodiacepinas son farmacos depresores del sistema nervioso central ampliamente prescritos como ansioliticos, hipnoticos, anticonvulsivantes y relajantes musculares. Aunque son relativamente seguras en monoterapia (amplio margen terapeutico), la coingesion con otros depresores del SNC como alcohol, opioides o barbituricos potencia dramaticamente su toxicidad y puede ser letal. Los compuestos mas frecuentemente involucrados en sobredosis incluyen diazepam, alprazolam, clonazepam, lorazepam y midazolam. La intoxicacion pura por benzodiacepinas rara vez causa la muerte en adultos sanos, pero puede ser fatal en ancianos, pacientes con enfermedad pulmonar cronica, o cuando hay coingestiones. Un problema creciente es la adulteracion de drogas ilicitas con benzodiacepinas potentes como el flualprazolam o el clonazolam, que no se detectan en pruebas convencionales.",
    "descripcionEn": "Benzodiazepine overdose is a frequent cause of emergency toxicology consultation. Benzodiazepines are central nervous system depressant drugs widely prescribed as anxiolytics, hypnotics, anticonvulsants, and muscle relaxants. Although relatively safe in monotherapy (wide therapeutic margin), co-ingestion with other CNS depressants such as alcohol, opioids, or barbiturates dramatically potentiates their toxicity and can be lethal. The compounds most frequently involved in overdose include diazepam, alprazolam, clonazepam, lorazepam, and midazolam. Pure benzodiazepine intoxication rarely causes death in healthy adults but can be fatal in elderly patients, those with chronic pulmonary disease, or when there are co-ingestions. A growing problem is the adulteration of illicit drugs with potent benzodiazepines such as flualprazolam or clonazolam, which are not detected by conventional tests.",
    "sintomasEs": [
      "Somnolencia excesiva y letargia progresiva",
      "Disartria (habla arrastrada) y confusion",
      "Ataxia (incoordinacion motora) y debilidad muscular",
      "Hiporreflexia o arreflexia",
      "Vision borrosa y nistagmo",
      "Amnesia anterograda",
      "Hipotension leve a moderada",
      "Depresion respiratoria (especialmente con coingestiones)",
      "Coma con respuesta preservada a estimulos dolorosos (en intoxicacion pura)",
      "Hipotermia por depresion del centro termorregulador"
    ],
    "sintomasEn": [
      "Excessive drowsiness and progressive lethargy",
      "Dysarthria (slurred speech) and confusion",
      "Ataxia (motor incoordination) and muscle weakness",
      "Hyporeflexia or areflexia",
      "Blurred vision and nystagmus",
      "Anterograde amnesia",
      "Mild to moderate hypotension",
      "Respiratory depression (especially with co-ingestions)",
      "Coma with preserved response to painful stimuli (in pure intoxication)",
      "Hypothermia from thermoregulatory center depression"
    ],
    "agenteToxicoEs": "Benzodiacepinas, una clase de farmacos que incluye compuestos de accion corta (midazolam, triazolam), intermedia (alprazolam, lorazepam, oxazepam) y prolongada (diazepam, clonazepam, clordiazepoxido). El alprazolam y el diazepam son los mas frecuentemente involucrados en sobredosis. Las benzodiacepinas de accion corta y alta potencia (alprazolam, triazolam) tienen mayor potencial de abuso y riesgo de abstinencia severa. Las benzodiacepinas de diseno (flualprazolam, clonazolam, etizolam) son particularmente peligrosas por su potencia extrema y falta de deteccion en pruebas de drogas estandar. La combinacion con opioides es la causa mas comun de muerte por sobredosis de benzodiacepinas.",
    "agenteToxicoEn": "Benzodiazepines, a drug class that includes short-acting (midazolam, triazolam), intermediate-acting (alprazolam, lorazepam, oxazepam), and long-acting (diazepam, clonazepam, chlordiazepoxide) compounds. Alprazolam and diazepam are the most frequently involved in overdose. Short-acting, high-potency benzodiazepines (alprazolam, triazolam) have greater abuse potential and risk of severe withdrawal. Designer benzodiazepines (flualprazolam, clonazolam, etizolam) are particularly dangerous due to their extreme potency and lack of detection on standard drug tests. The combination with opioids is the most common cause of benzodiazepine overdose death.",
    "mecanismoEs": "Las benzodiacepinas actuan como moduladores alostericos positivos del receptor GABA-A, el principal receptor inhibitorio del SNC. Se unen a un sitio especifico en la interfaz entre las subunidades alfa y gamma del receptor, aumentando la afinidad del GABA por su sitio de union y aumentando la frecuencia de apertura del canal de cloro (a diferencia de los barbituricos que aumentan la duracion). Esto potencia la hiperpolarizacion neuronal mediada por GABA, produciendo sedacion, ansiolisis, relajacion muscular, efecto anticonvulsivante y amnesia. En sobredosis, la inhibicion excesiva del SNC causa depresion del nivel de conciencia y, en casos severos, depresion respiratoria. A diferencia de los barbituricos, las benzodiacepinas tienen un efecto techo (ceiling effect) y no pueden abrir el canal de cloro sin GABA, lo que les confiere mayor seguridad en monoterapia. Sin embargo, la coingesion con otros GABAergicos (alcohol, barbituricos) o depresores del SNC (opioides) produce sinergia que elimina este margen de seguridad.",
    "mecanismoEn": "Benzodiazepines act as positive allosteric modulators of the GABA-A receptor, the main inhibitory receptor of the CNS. They bind to a specific site at the interface between the alpha and gamma subunits of the receptor, increasing GABA's affinity for its binding site and increasing the frequency of chloride channel opening (unlike barbiturates which increase duration). This potentiates GABA-mediated neuronal hyperpolarization, producing sedation, anxiolysis, muscle relaxation, anticonvulsant effect, and amnesia. In overdose, excessive CNS inhibition causes depressed level of consciousness and, in severe cases, respiratory depression. Unlike barbiturates, benzodiazepines have a ceiling effect and cannot open the chloride channel without GABA, giving them greater safety in monotherapy. However, co-ingestion with other GABAergic agents (alcohol, barbiturates) or CNS depressants (opioids) produces synergy that eliminates this safety margin.",
    "tratamientoEs": "El manejo es fundamentalmente de soporte con enfasis en la proteccion de la via aerea y monitorizacion respiratoria continua. Evaluar la via aerea, respiracion y circulacion (ABC). Si hay depresion respiratoria, asistir la ventilacion con bolsa-valvula-mascarilla e intubar si es necesario. El flumazenil es el antagonista especifico pero su uso es selectivo y controversial: esta contraindicado en pacientes con uso cronico de benzodiacepinas (riesgo de precipitar sindrome de abstinencia con convulsiones), coingesion de proconvulsivantes (antidepresivos triciclicos, cocaina), antecedente de epilepsia, y en la mayoria de las sobredosis mixtas. Cuando se usa, la dosis es 0.2 mg IV, repitiendo 0.2 mg cada minuto hasta un maximo de 3-5 mg, con monitorizacion estrecha por riesgo de resedacion (vida media del flumazenil es mas corta que la de la mayoria de benzodiacepinas). Se debe descartar coingestiones mediante panel toxicologico ampliado, nivel de paracetamol y salicilatos. El carbon activado (1 g/kg, maximo 50 g) puede administrarse si la ingesta fue en la hora previa y la via aerea esta protegida. Monitorizar durante al menos 6 horas en intoxicacion con compuestos de accion corta y 24 horas con compuestos de accion prolongada.",
    "tratamientoEn": "Management is fundamentally supportive with emphasis on airway protection and continuous respiratory monitoring. Evaluate airway, breathing, and circulation (ABCs). If respiratory depression is present, assist ventilation with bag-valve-mask and intubate if necessary. Flumazenil is the specific antagonist but its use is selective and controversial: it is contraindicated in patients with chronic benzodiazepine use (risk of precipitating withdrawal syndrome with seizures), co-ingestion of proconvulsants (tricyclic antidepressants, cocaine), history of epilepsy, and in most mixed overdoses. When used, the dose is 0.2 mg IV, repeating 0.2 mg every minute up to a maximum of 3-5 mg, with close monitoring for resedation risk (flumazenil's half-life is shorter than that of most benzodiazepines). Co-ingestions should be ruled out through expanded toxicology panel, acetaminophen level, and salicylates. Activated charcoal (1 g/kg, maximum 50 g) may be given if ingestion was within the previous hour and the airway is protected. Monitor for at least 6 hours in short-acting compound intoxication and 24 hours with long-acting compounds.",
    "antidotoEs": "Flumazenil (Anexate/Romazicon): antagonista competitivo especifico del sitio de union de las benzodiacepinas en el receptor GABA-A. Dosis: 0.2 mg IV inicial, seguido de 0.2 mg cada 60 segundos hasta efecto deseado o maximo de 3-5 mg. Inicio de accion en 1-2 minutos, duracion de 45-60 minutos. PRECAUCIONES IMPORTANTES: su vida media (40-80 minutos) es mas corta que la de la mayoria de benzodiacepinas, por lo que puede ocurrir resedacion. Contraindicado en: uso cronico de benzodiacepinas (riesgo de convulsiones por abstinencia), coingesion de antidepresivos triciclicos u otros proconvulsivantes, antecedente de trastorno convulsivo, y signos de estimulacion simpatica (sugiriendo coingesion). Su uso principal es como herramienta diagnostica en coma de causa desconocida o para revertir sedacion procedural.",
    "antidotoEn": "Flumazenil (Anexate/Romazicon): specific competitive antagonist at the benzodiazepine binding site on the GABA-A receptor. Dose: 0.2 mg IV initial, followed by 0.2 mg every 60 seconds until desired effect or maximum of 3-5 mg. Onset of action in 1-2 minutes, duration 45-60 minutes. IMPORTANT PRECAUTIONS: its half-life (40-80 minutes) is shorter than that of most benzodiazepines, so resedation may occur. Contraindicated in: chronic benzodiazepine use (risk of withdrawal seizures), co-ingestion of tricyclic antidepressants or other proconvulsants, history of seizure disorder, and signs of sympathetic stimulation (suggesting co-ingestion). Its primary use is as a diagnostic tool in coma of unknown cause or to reverse procedural sedation.",
    "primerosAuxiliosEs": "Si se sospecha sobredosis de benzodiacepinas, llamar al 911 o al centro de control de intoxicaciones inmediatamente. No dejar a la persona sola. Si esta consciente pero somnolenta, mantenerla despierta y alerta hablándole, sentandola y monitorizando su respiracion. Si esta inconsciente pero respira, colocarla en posicion lateral de seguridad para prevenir aspiracion en caso de vomito. Si no respira o la respiracion es muy lenta (menos de 8 por minuto), iniciar ventilacion de rescate y RCP si es necesario. Recoger todos los envases de medicamentos y sustancias disponibles para llevarlos al hospital. Si se sospecha coingesion de opioides y se dispone de naloxona (Narcan), administrarla segun las instrucciones. Monitorizar la respiracion continuamente hasta que llegue la ayuda.",
    "primerosAuxiliosEn": "If benzodiazepine overdose is suspected, call 911 or poison control immediately. Do not leave the person alone. If conscious but drowsy, keep them awake and alert by talking to them, sitting them up, and monitoring their breathing. If unconscious but breathing, place in the recovery position to prevent aspiration in case of vomiting. If not breathing or breathing is very slow (less than 8 per minute), begin rescue breathing and CPR if necessary. Collect all available medication containers and substances to bring to the hospital. If opioid co-ingestion is suspected and naloxone (Narcan) is available, administer it according to instructions. Monitor breathing continuously until help arrives.",
    "prevencionEs": "Tomar las benzodiacepinas estrictamente segun la prescripcion medica, sin modificar la dosis ni la frecuencia. No combinar con alcohol, opioides ni otros sedantes. Informar al medico sobre todos los medicamentos que se estan tomando, incluyendo suplementos y productos naturales. Almacenar los medicamentos en un lugar seguro fuera del alcance de ninos y adolescentes. No compartir medicamentos con otras personas. Si se tiene un trastorno por uso de sustancias, informar al medico antes de que prescriba benzodiacepinas. Considerar alternativas no benzodiazepinicas para la ansiedad y el insomnio cuando sea posible. En el ambito comunitario, disponer de naloxona si hay riesgo de exposicion a benzodiacepinas mezcladas con opioides. Buscar ayuda profesional si se desarrolla dependencia.",
    "prevencionEn": "Take benzodiazepines strictly as prescribed, without modifying the dose or frequency. Do not combine with alcohol, opioids, or other sedatives. Inform your doctor about all medications being taken, including supplements and natural products. Store medications in a safe place out of reach of children and adolescents. Do not share medications with others. If you have a substance use disorder, inform your doctor before they prescribe benzodiazepines. Consider non-benzodiazepine alternatives for anxiety and insomnia when possible. In community settings, have naloxone available if there is risk of exposure to benzodiazepines mixed with opioids. Seek professional help if dependence develops."
  }
]`);

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

export function buscarToxicologia(termino: string): ToxicologiaEntry[] {
  const t = termino.toLowerCase();
  return TOXICOLOGIA_ENTRIES.filter(e =>
    e.nombreEs.toLowerCase().includes(t) ||
    e.nombreEn.toLowerCase().includes(t) ||
    e.descripcionEs.toLowerCase().includes(t) ||
    e.descripcionEn.toLowerCase().includes(t)
  );
}

export function getToxicologiaById(id: string): ToxicologiaEntry | undefined {
  return TOXICOLOGIA_ENTRIES.find(e => e.id === id);
}

export function getToxicologiaPorCategoria(categoria: string): ToxicologiaEntry[] {
  const c = categoria.toLowerCase();
  return TOXICOLOGIA_ENTRIES.filter(e =>
    e.categoriaEs.toLowerCase().includes(c) ||
    e.categoriaEn.toLowerCase().includes(c)
  );
}
