/**
 * SOMA Enciclopedia de Enfermedades Cronicas
 * Comprehensive chronic disease management guide - Spanish first, English secondary
 * Patient education for daily management of chronic conditions
 */

export interface EnfermedadCronicaEntry {
  id: string;
  nombreEs: string;
  nombreEn: string;
  descripcionEs: string;
  descripcionEn: string;
  prevalencia: string;
  factoresRiesgoEs: string[];
  factoresRiesgoEn: string[];
  sintomasEs: string[];
  sintomasEn: string[];
  diagnosticoEs: string[];
  diagnosticoEn: string[];
  tratamientoEs: string[];
  tratamientoEn: string[];
  manejoEnCasaEs: string[];
  manejoEnCasaEn: string[];
  cambiosEstiloVidaEs: string[];
  cambiosEstiloVidaEn: string[];
  complicacionesEs: string[];
  complicacionesEn: string[];
  monitorizacionEs: string[];
  monitorizacionEn: string[];
  preguntasParaMedicoEs: string[];
  preguntasParaMedicoEn: string[];
  recursosApoyoEs: string[];
  recursosApoyoEn: string[];
  vivienDoConEs: string[];
  vivienDoConEn: string[];
  emergenciasEs: string[];
  emergenciasEn: string[];
  sistemasCorporales: string[];
}

const cronicasData: EnfermedadCronicaEntry[] = JSON.parse(`[
{
  "id": "hipertension",
  "nombreEs": "Hipertension arterial",
  "nombreEn": "Hypertension (High Blood Pressure)",
  "descripcionEs": "Condicion cronica en la que la presion de la sangre contra las paredes de las arterias es consistentemente elevada, lo que aumenta el riesgo de enfermedades cardiacas, accidentes cerebrovasculares y dano renal. Se le llama el asesino silencioso porque raramente causa sintomas.",
  "descripcionEn": "Chronic condition where blood pressure against artery walls is consistently elevated, increasing risk of heart disease, stroke, and kidney damage. Called the silent killer because it rarely causes symptoms.",
  "prevalencia": "Afecta a aproximadamente 1 de cada 3 adultos a nivel mundial",
  "factoresRiesgoEs": ["Antecedentes familiares de hipertension", "Edad avanzada (mayor de 55 anos)", "Sobrepeso u obesidad", "Consumo excesivo de sal", "Sedentarismo", "Consumo excesivo de alcohol", "Estres cronico", "Tabaquismo", "Diabetes", "Enfermedad renal cronica"],
  "factoresRiesgoEn": ["Family history of hypertension", "Advanced age (over 55)", "Overweight or obesity", "Excessive salt intake", "Sedentary lifestyle", "Excessive alcohol consumption", "Chronic stress", "Smoking", "Diabetes", "Chronic kidney disease"],
  "sintomasEs": ["Generalmente asintomatica (sin sintomas)", "Dolor de cabeza severo en crisis hipertensivas", "Vision borrosa", "Mareos", "Sangrado nasal", "Falta de aire", "Dolor en el pecho", "Zumbido en los oidos"],
  "sintomasEn": ["Generally asymptomatic (no symptoms)", "Severe headache in hypertensive crises", "Blurred vision", "Dizziness", "Nosebleeds", "Shortness of breath", "Chest pain", "Ringing in ears"],
  "diagnosticoEs": ["Medicion de presion arterial con esfigmomanometro", "Monitoreo ambulatorio de presion arterial (MAPA) de 24 horas", "Mediciones repetidas en diferentes visitas", "Analisis de sangre para funcion renal y colesterol", "Electrocardiograma", "Ecocardiograma si hay sospecha de dano cardiaco"],
  "diagnosticoEn": ["Blood pressure measurement with sphygmomanometer", "24-hour ambulatory blood pressure monitoring (ABPM)", "Repeated measurements across different visits", "Blood tests for kidney function and cholesterol", "Electrocardiogram", "Echocardiogram if cardiac damage suspected"],
  "tratamientoEs": ["Inhibidores de la ECA (enalapril, lisinopril)", "Bloqueadores del receptor de angiotensina (losartan, valsartan)", "Bloqueadores de canales de calcio (amlodipino)", "Diureticos (hidroclorotiazida, furosemida)", "Betabloqueadores (metoprolol, atenolol)", "Combinacion de medicamentos si es necesario"],
  "tratamientoEn": ["ACE inhibitors (enalapril, lisinopril)", "Angiotensin receptor blockers (losartan, valsartan)", "Calcium channel blockers (amlodipine)", "Diuretics (hydrochlorothiazide, furosemide)", "Beta-blockers (metoprolol, atenolol)", "Combination therapy if needed"],
  "manejoEnCasaEs": ["Medir la presion arterial en casa dos veces al dia", "Llevar un registro escrito de las lecturas", "Tomar los medicamentos a la misma hora cada dia", "Reducir el consumo de sal a menos de 5 gramos al dia", "Mantener un peso saludable", "No suspender los medicamentos sin consultar al medico"],
  "manejoEnCasaEn": ["Measure blood pressure at home twice daily", "Keep a written log of readings", "Take medications at the same time each day", "Reduce salt intake to less than 5 grams per day", "Maintain a healthy weight", "Never stop medications without consulting your doctor"],
  "cambiosEstiloVidaEs": ["Adoptar la dieta DASH (rica en frutas, verduras, granos integrales)", "Hacer ejercicio aerobico moderado 150 minutos por semana", "Reducir el consumo de sodio", "Limitar el alcohol a 1-2 bebidas por dia", "Dejar de fumar", "Practicar tecnicas de manejo del estres", "Dormir 7-8 horas por noche", "Perder peso si hay sobrepeso"],
  "cambiosEstiloVidaEn": ["Adopt the DASH diet (rich in fruits, vegetables, whole grains)", "Do moderate aerobic exercise 150 minutes per week", "Reduce sodium intake", "Limit alcohol to 1-2 drinks per day", "Quit smoking", "Practice stress management techniques", "Sleep 7-8 hours per night", "Lose weight if overweight"],
  "complicacionesEs": ["Infarto al miocardio", "Accidente cerebrovascular (derrame cerebral)", "Insuficiencia cardiaca", "Enfermedad renal cronica", "Dano a la retina (retinopatia hipertensiva)", "Aneurisma aortico", "Demencia vascular", "Enfermedad arterial periferica"],
  "complicacionesEn": ["Heart attack", "Stroke", "Heart failure", "Chronic kidney disease", "Retinal damage (hypertensive retinopathy)", "Aortic aneurysm", "Vascular dementia", "Peripheral artery disease"],
  "monitorizacionEs": ["Presion arterial en casa diariamente", "Analisis de sangre cada 6-12 meses (funcion renal, electrolitos)", "Examen de orina para proteinas", "Control de peso semanal", "Examen oftalmologico anual", "Electrocardiograma anual"],
  "monitorizacionEn": ["Home blood pressure daily", "Blood tests every 6-12 months (kidney function, electrolytes)", "Urine test for protein", "Weekly weight check", "Annual eye exam", "Annual electrocardiogram"],
  "preguntasParaMedicoEs": ["Cual es mi meta de presion arterial?", "Puedo reducir la dosis de mis medicamentos si mi presion mejora?", "Que efectos secundarios debo vigilar?", "Con que frecuencia debo medirme la presion en casa?", "Hay alimentos o medicamentos que debo evitar?"],
  "preguntasParaMedicoEn": ["What is my blood pressure goal?", "Can I reduce my medication dose if my pressure improves?", "What side effects should I watch for?", "How often should I check my pressure at home?", "Are there foods or medications I should avoid?"],
  "recursosApoyoEs": ["Asociacion Americana del Corazon (AHA) en espanol", "Programa de autocontrol de enfermedades cronicas", "Grupos de apoyo para pacientes hipertensos", "Aplicaciones de monitoreo de presion arterial", "Nutricionista especializado en dieta DASH"],
  "recursosApoyoEn": ["American Heart Association (AHA)", "Chronic Disease Self-Management Program", "Hypertension patient support groups", "Blood pressure monitoring apps", "Nutritionist specialized in DASH diet"],
  "vivienDoConEs": ["La hipertension se puede controlar exitosamente con medicamentos y cambios de estilo de vida", "Haga de la medicion de presion arterial una rutina diaria", "Aprenda a leer las etiquetas de los alimentos para identificar el sodio", "Cocine en casa para controlar mejor la sal", "Mantenga sus citas medicas regulares", "No se desanime si necesita ajustar medicamentos"],
  "vivienDoConEn": ["Hypertension can be successfully controlled with medication and lifestyle changes", "Make blood pressure measurement a daily routine", "Learn to read food labels to identify sodium", "Cook at home to better control salt intake", "Keep your regular medical appointments", "Do not get discouraged if medications need adjustment"],
  "emergenciasEs": ["Presion arterial mayor de 180/120 mmHg", "Dolor de cabeza severo subito con vision borrosa", "Dolor en el pecho o dificultad para respirar", "Debilidad o entumecimiento en un lado del cuerpo", "Dificultad para hablar o confusion subita", "Sangrado nasal que no se detiene"],
  "emergenciasEn": ["Blood pressure above 180/120 mmHg", "Sudden severe headache with blurred vision", "Chest pain or difficulty breathing", "Weakness or numbness on one side of the body", "Difficulty speaking or sudden confusion", "Nosebleed that will not stop"],
  "sistemasCorporales": ["cardiovascular", "renal"]
},
{
  "id": "insuficiencia-cardiaca",
  "nombreEs": "Insuficiencia cardiaca",
  "nombreEn": "Heart Failure",
  "descripcionEs": "Condicion cronica en la que el corazon no puede bombear sangre de manera suficiente para satisfacer las necesidades del cuerpo. Puede afectar el lado izquierdo, derecho o ambos lados del corazon. Es una condicion progresiva que requiere manejo de por vida.",
  "descripcionEn": "Chronic condition where the heart cannot pump enough blood to meet the body's needs. Can affect the left side, right side, or both sides of the heart. It is a progressive condition requiring lifelong management.",
  "prevalencia": "Afecta a mas de 64 millones de personas en el mundo",
  "factoresRiesgoEs": ["Enfermedad coronaria", "Hipertension arterial no controlada", "Infarto previo al miocardio", "Diabetes", "Enfermedad valvular cardiaca", "Cardiomiopatia", "Arritmias cronicas", "Obesidad", "Apnea del sueno", "Consumo excesivo de alcohol"],
  "factoresRiesgoEn": ["Coronary artery disease", "Uncontrolled hypertension", "Previous heart attack", "Diabetes", "Valvular heart disease", "Cardiomyopathy", "Chronic arrhythmias", "Obesity", "Sleep apnea", "Excessive alcohol consumption"],
  "sintomasEs": ["Falta de aire al realizar actividades o al acostarse", "Fatiga y debilidad persistente", "Hinchazon en piernas, tobillos y pies (edema)", "Latidos cardiacos rapidos o irregulares", "Tos persistente con flema blanca o rosada", "Necesidad de orinar con frecuencia por la noche", "Aumento rapido de peso por retencion de liquidos", "Falta de apetito y nauseas"],
  "sintomasEn": ["Shortness of breath during activities or when lying down", "Persistent fatigue and weakness", "Swelling in legs, ankles, and feet (edema)", "Rapid or irregular heartbeats", "Persistent cough with white or pink phlegm", "Frequent nighttime urination", "Rapid weight gain from fluid retention", "Loss of appetite and nausea"],
  "diagnosticoEs": ["Ecocardiograma para evaluar la funcion del corazon", "Analisis de sangre (BNP o NT-proBNP)", "Radiografia de torax", "Electrocardiograma", "Prueba de esfuerzo", "Resonancia magnetica cardiaca", "Cateterismo cardiaco en casos selectos"],
  "diagnosticoEn": ["Echocardiogram to evaluate heart function", "Blood tests (BNP or NT-proBNP)", "Chest X-ray", "Electrocardiogram", "Stress test", "Cardiac MRI", "Cardiac catheterization in select cases"],
  "tratamientoEs": ["Inhibidores de la ECA o bloqueadores del receptor de angiotensina", "Betabloqueadores (carvedilol, metoprolol)", "Diureticos para eliminar exceso de liquido", "Antagonistas de la aldosterona (espironolactona)", "Inhibidores de SGLT2 (dapagliflozina, empagliflozina)", "Sacubitril/valsartan en casos apropiados", "Dispositivos como desfibrilador o marcapasos en casos severos"],
  "tratamientoEn": ["ACE inhibitors or angiotensin receptor blockers", "Beta-blockers (carvedilol, metoprolol)", "Diuretics to remove excess fluid", "Aldosterone antagonists (spironolactone)", "SGLT2 inhibitors (dapagliflozin, empagliflozin)", "Sacubitril/valsartan in appropriate cases", "Devices like defibrillator or pacemaker in severe cases"],
  "manejoEnCasaEs": ["Pesarse todos los dias a la misma hora y registrar el peso", "Restringir liquidos a 1.5-2 litros por dia segun indicacion medica", "Limitar el sodio a menos de 2 gramos por dia", "Tomar todos los medicamentos segun lo prescrito", "Elevar las piernas cuando este sentado", "Usar almohadas para dormir semi-incorporado si hay dificultad para respirar"],
  "manejoEnCasaEn": ["Weigh yourself daily at the same time and record weight", "Restrict fluids to 1.5-2 liters per day as directed", "Limit sodium to less than 2 grams per day", "Take all medications as prescribed", "Elevate legs when sitting", "Use pillows to sleep propped up if breathing is difficult"],
  "cambiosEstiloVidaEs": ["Dieta baja en sodio y liquidos controlados", "Ejercicio suave y progresivo segun tolerancia", "Dejar de fumar completamente", "Eliminar el consumo de alcohol", "Controlar el peso corporal", "Manejar el estres con tecnicas de relajacion", "Vacunarse contra la gripe y neumonia anualmente"],
  "cambiosEstiloVidaEn": ["Low-sodium diet with controlled fluids", "Gentle progressive exercise as tolerated", "Stop smoking completely", "Eliminate alcohol consumption", "Control body weight", "Manage stress with relaxation techniques", "Get annual flu and pneumonia vaccines"],
  "complicacionesEs": ["Insuficiencia renal", "Arritmias cardiacas peligrosas", "Dano hepatico por congestion", "Edema pulmonar (liquido en los pulmones)", "Muerte subita cardiaca", "Caquexia cardiaca (perdida severa de masa muscular)", "Depresion y ansiedad"],
  "complicacionesEn": ["Kidney failure", "Dangerous cardiac arrhythmias", "Liver damage from congestion", "Pulmonary edema (fluid in lungs)", "Sudden cardiac death", "Cardiac cachexia (severe muscle wasting)", "Depression and anxiety"],
  "monitorizacionEs": ["Peso diario (reportar ganancia de mas de 1 kg en un dia o 2 kg en una semana)", "Presion arterial y frecuencia cardiaca diaria", "Grado de hinchazon en piernas y tobillos", "Nivel de dificultad para respirar", "Analisis de sangre periodicos (funcion renal, electrolitos, BNP)", "Fraccion de eyeccion cada 6-12 meses"],
  "monitorizacionEn": ["Daily weight (report gain of more than 1 kg in a day or 2 kg in a week)", "Daily blood pressure and heart rate", "Degree of leg and ankle swelling", "Level of breathing difficulty", "Periodic blood tests (kidney function, electrolytes, BNP)", "Ejection fraction every 6-12 months"],
  "preguntasParaMedicoEs": ["Cual es mi fraccion de eyeccion actual?", "Cuanto liquido puedo tomar al dia?", "Puedo hacer ejercicio y que tipo?", "Que debo hacer si subo de peso repentinamente?", "Necesito un dispositivo cardiaco?"],
  "preguntasParaMedicoEn": ["What is my current ejection fraction?", "How much fluid can I drink per day?", "Can I exercise and what type?", "What should I do if I gain weight suddenly?", "Do I need a cardiac device?"],
  "recursosApoyoEs": ["Fundacion del Corazon", "Programa de rehabilitacion cardiaca", "Grupos de apoyo para pacientes con insuficiencia cardiaca", "Linea de ayuda de cardiologia", "Servicios de enfermeria a domicilio"],
  "recursosApoyoEn": ["Heart Foundation", "Cardiac rehabilitation program", "Heart failure patient support groups", "Cardiology helpline", "Home nursing services"],
  "vivienDoConEs": ["Planifique sus actividades diarias para conservar energia", "Descanse entre actividades para evitar la fatiga", "Aprenda a reconocer sus limites fisicos", "Mantenga una rutina diaria de medicamentos y peso", "Comunique a su familia los signos de alerta", "Busque apoyo emocional cuando lo necesite"],
  "vivienDoConEn": ["Plan daily activities to conserve energy", "Rest between activities to avoid fatigue", "Learn to recognize your physical limits", "Maintain a daily medication and weight routine", "Tell your family about warning signs", "Seek emotional support when needed"],
  "emergenciasEs": ["Dificultad severa para respirar que no mejora con reposo", "Dolor en el pecho persistente", "Desmayo o perdida de conciencia", "Tos con esputo rosado o espumoso", "Ganancia de peso de mas de 2 kg en un dia", "Palpitaciones rapidas e irregulares con mareo"],
  "emergenciasEn": ["Severe breathing difficulty that does not improve with rest", "Persistent chest pain", "Fainting or loss of consciousness", "Cough with pink or frothy sputum", "Weight gain of more than 2 kg in one day", "Rapid irregular palpitations with dizziness"],
  "sistemasCorporales": ["cardiovascular"]
},
{
  "id": "fibrilacion-auricular",
  "nombreEs": "Fibrilacion auricular",
  "nombreEn": "Atrial Fibrillation",
  "descripcionEs": "Arritmia cardiaca cronica mas comun en la que las camaras superiores del corazon (auriculas) laten de manera irregular y descoordinada, lo que puede provocar coagulos sanguineos, accidentes cerebrovasculares e insuficiencia cardiaca.",
  "descripcionEn": "Most common chronic cardiac arrhythmia where the upper chambers of the heart (atria) beat irregularly and uncoordinated, which can cause blood clots, strokes, and heart failure.",
  "prevalencia": "Afecta a 33 millones de personas en el mundo, mas comun despues de los 65 anos",
  "factoresRiesgoEs": ["Edad avanzada", "Hipertension arterial", "Enfermedad cardiaca preexistente", "Obesidad", "Apnea del sueno", "Hipertiroidismo", "Consumo excesivo de alcohol", "Diabetes", "Enfermedad pulmonar cronica"],
  "factoresRiesgoEn": ["Advanced age", "Hypertension", "Pre-existing heart disease", "Obesity", "Sleep apnea", "Hyperthyroidism", "Excessive alcohol consumption", "Diabetes", "Chronic lung disease"],
  "sintomasEs": ["Palpitaciones o sensacion de latidos irregulares", "Fatiga inexplicable", "Mareos o sensacion de desmayo", "Falta de aire", "Dolor o presion en el pecho", "Intolerancia al ejercicio", "Algunos pacientes no tienen sintomas"],
  "sintomasEn": ["Palpitations or sensation of irregular heartbeats", "Unexplained fatigue", "Dizziness or feeling faint", "Shortness of breath", "Chest pain or pressure", "Exercise intolerance", "Some patients have no symptoms"],
  "diagnosticoEs": ["Electrocardiograma (ECG)", "Monitor Holter de 24-48 horas", "Monitor de eventos cardiacos", "Ecocardiograma", "Analisis de sangre (tiroides, funcion renal)", "Estudio electrofisiologico en casos complejos"],
  "diagnosticoEn": ["Electrocardiogram (ECG)", "24-48 hour Holter monitor", "Cardiac event monitor", "Echocardiogram", "Blood tests (thyroid, kidney function)", "Electrophysiology study in complex cases"],
  "tratamientoEs": ["Anticoagulantes para prevenir coagulos (warfarina, apixaban, rivaroxaban)", "Medicamentos para controlar la frecuencia cardiaca (betabloqueadores, digoxina)", "Medicamentos antiarritmicos (amiodarona, flecainida)", "Cardioversion electrica para restaurar el ritmo normal", "Ablacion con cateter en casos seleccionados", "Cierre de orejuela auricular izquierda"],
  "tratamientoEn": ["Anticoagulants to prevent clots (warfarin, apixaban, rivaroxaban)", "Heart rate control medications (beta-blockers, digoxin)", "Antiarrhythmic medications (amiodarone, flecainide)", "Electrical cardioversion to restore normal rhythm", "Catheter ablation in selected cases", "Left atrial appendage closure"],
  "manejoEnCasaEs": ["Tomar anticoagulantes exactamente como se indica", "Tomarse el pulso diariamente para detectar irregularidades", "Evitar el consumo excesivo de cafeina y alcohol", "Reportar cualquier sangrado inusual al medico", "Mantener un diario de sintomas y episodios", "Llevar una identificacion medica que indique el uso de anticoagulantes"],
  "manejoEnCasaEn": ["Take anticoagulants exactly as directed", "Check pulse daily to detect irregularities", "Avoid excessive caffeine and alcohol consumption", "Report any unusual bleeding to your doctor", "Keep a symptom and episode diary", "Carry medical ID indicating anticoagulant use"],
  "cambiosEstiloVidaEs": ["Limitar la cafeina y el alcohol", "Mantener un peso saludable", "Hacer ejercicio moderado regularmente", "Manejar el estres", "Tratar la apnea del sueno si esta presente", "Dejar de fumar"],
  "cambiosEstiloVidaEn": ["Limit caffeine and alcohol", "Maintain a healthy weight", "Exercise moderately and regularly", "Manage stress", "Treat sleep apnea if present", "Quit smoking"],
  "complicacionesEs": ["Accidente cerebrovascular (embolia)", "Insuficiencia cardiaca", "Deterioro cognitivo", "Fatiga cronica debilitante", "Tromboembolismo periferico"],
  "complicacionesEn": ["Stroke (embolism)", "Heart failure", "Cognitive decline", "Debilitating chronic fatigue", "Peripheral thromboembolism"],
  "monitorizacionEs": ["Pulso diario y registro de episodios", "INR regular si toma warfarina", "Analisis de sangre periodicos", "Ecocardiograma anual", "Evaluacion del riesgo de accidente cerebrovascular (escala CHA2DS2-VASc)"],
  "monitorizacionEn": ["Daily pulse and episode logging", "Regular INR if taking warfarin", "Periodic blood tests", "Annual echocardiogram", "Stroke risk assessment (CHA2DS2-VASc score)"],
  "preguntasParaMedicoEs": ["Cual es mi riesgo de accidente cerebrovascular?", "Necesito tomar anticoagulantes de por vida?", "La ablacion es una opcion para mi?", "Que hago si olvido una dosis de anticoagulante?", "Puedo hacer ejercicio intenso?"],
  "preguntasParaMedicoEn": ["What is my stroke risk?", "Do I need to take anticoagulants for life?", "Is ablation an option for me?", "What if I miss an anticoagulant dose?", "Can I do intense exercise?"],
  "recursosApoyoEs": ["Asociacion de pacientes con arritmias", "Clinicas de anticoagulacion", "Programas de rehabilitacion cardiaca", "Aplicaciones de monitoreo de ritmo cardiaco"],
  "recursosApoyoEn": ["Arrhythmia patient association", "Anticoagulation clinics", "Cardiac rehabilitation programs", "Heart rhythm monitoring apps"],
  "vivienDoConEs": ["Aprenda a tomarse el pulso correctamente", "Tenga siempre disponibles sus medicamentos anticoagulantes", "Informe a todos sus medicos y dentistas sobre su condicion", "Evite deportes de contacto por riesgo de sangrado", "Mantenga la calma durante los episodios de palpitaciones"],
  "vivienDoConEn": ["Learn to check your pulse correctly", "Always have your anticoagulant medications available", "Inform all your doctors and dentists about your condition", "Avoid contact sports due to bleeding risk", "Stay calm during palpitation episodes"],
  "emergenciasEs": ["Sintomas de accidente cerebrovascular (cara caida, debilidad en un brazo, dificultad para hablar)", "Sangrado severo que no se detiene", "Dolor de pecho severo", "Desmayo o perdida de conciencia", "Dificultad severa para respirar"],
  "emergenciasEn": ["Stroke symptoms (face drooping, arm weakness, speech difficulty)", "Severe bleeding that will not stop", "Severe chest pain", "Fainting or loss of consciousness", "Severe difficulty breathing"],
  "sistemasCorporales": ["cardiovascular"]
},
{
  "id": "enfermedad-coronaria",
  "nombreEs": "Enfermedad de las arterias coronarias",
  "nombreEn": "Coronary Artery Disease",
  "descripcionEs": "Acumulacion de placa en las arterias que suministran sangre al corazon, lo que reduce el flujo sanguineo y puede causar angina de pecho, infarto al miocardio e insuficiencia cardiaca. Es la principal causa de muerte en el mundo.",
  "descripcionEn": "Buildup of plaque in the arteries that supply blood to the heart, reducing blood flow and potentially causing angina, heart attack, and heart failure. It is the leading cause of death worldwide.",
  "prevalencia": "Causa principal de muerte a nivel global, afecta a mas de 200 millones de personas",
  "factoresRiesgoEs": ["Colesterol alto (especialmente LDL elevado)", "Hipertension arterial", "Tabaquismo", "Diabetes", "Obesidad", "Sedentarismo", "Antecedentes familiares", "Edad avanzada", "Estres cronico", "Dieta rica en grasas saturadas"],
  "factoresRiesgoEn": ["High cholesterol (especially elevated LDL)", "Hypertension", "Smoking", "Diabetes", "Obesity", "Sedentary lifestyle", "Family history", "Advanced age", "Chronic stress", "Diet high in saturated fats"],
  "sintomasEs": ["Angina de pecho (dolor o presion en el pecho)", "Dolor que se irradia al brazo izquierdo, mandibula o espalda", "Falta de aire con el esfuerzo", "Fatiga inusual", "Palpitaciones", "Mareos", "Nauseas", "Sudoracion fria"],
  "sintomasEn": ["Angina (chest pain or pressure)", "Pain radiating to left arm, jaw, or back", "Shortness of breath with exertion", "Unusual fatigue", "Palpitations", "Dizziness", "Nausea", "Cold sweating"],
  "diagnosticoEs": ["Prueba de esfuerzo", "Electrocardiograma", "Ecocardiograma", "Tomografia computarizada coronaria (angio-TAC)", "Cateterismo cardiaco y angiografia", "Perfil lipidico y marcadores cardiacos"],
  "diagnosticoEn": ["Stress test", "Electrocardiogram", "Echocardiogram", "Coronary CT angiography", "Cardiac catheterization and angiography", "Lipid panel and cardiac markers"],
  "tratamientoEs": ["Estatinas para reducir el colesterol (atorvastatina, rosuvastatina)", "Aspirina en dosis baja o antiagregantes plaquetarios", "Betabloqueadores", "Nitroglicerina para alivio de angina", "Angioplastia con colocacion de stent", "Cirugia de bypass coronario en casos severos"],
  "tratamientoEn": ["Statins to lower cholesterol (atorvastatin, rosuvastatin)", "Low-dose aspirin or antiplatelet agents", "Beta-blockers", "Nitroglycerin for angina relief", "Angioplasty with stent placement", "Coronary bypass surgery in severe cases"],
  "manejoEnCasaEs": ["Tomar aspirina y estatinas segun indicacion", "Tener nitroglicerina sublingual disponible siempre", "Conocer los sintomas de un infarto", "Realizar ejercicio segun el plan de rehabilitacion cardiaca", "Seguir una dieta cardiosaludable", "Controlar el estres"],
  "manejoEnCasaEn": ["Take aspirin and statins as directed", "Always have sublingual nitroglycerin available", "Know the symptoms of a heart attack", "Exercise according to cardiac rehab plan", "Follow a heart-healthy diet", "Manage stress"],
  "cambiosEstiloVidaEs": ["Dieta mediterranea o cardiosaludable", "Ejercicio aerobico regular 30 minutos al dia", "Dejar de fumar definitivamente", "Control de peso", "Reducir grasas saturadas y trans", "Aumentar consumo de frutas, verduras y pescado", "Manejo del estres con meditacion o yoga"],
  "cambiosEstiloVidaEn": ["Mediterranean or heart-healthy diet", "Regular aerobic exercise 30 minutes daily", "Quit smoking permanently", "Weight control", "Reduce saturated and trans fats", "Increase fruit, vegetable, and fish consumption", "Stress management with meditation or yoga"],
  "complicacionesEs": ["Infarto agudo al miocardio", "Insuficiencia cardiaca", "Arritmias cardiacas", "Muerte subita cardiaca", "Angina inestable"],
  "complicacionesEn": ["Acute myocardial infarction", "Heart failure", "Cardiac arrhythmias", "Sudden cardiac death", "Unstable angina"],
  "monitorizacionEs": ["Perfil lipidico cada 6-12 meses", "Presion arterial regular", "Glucosa en sangre si hay diabetes", "Prueba de esfuerzo anual", "Peso y circunferencia abdominal"],
  "monitorizacionEn": ["Lipid panel every 6-12 months", "Regular blood pressure", "Blood glucose if diabetic", "Annual stress test", "Weight and waist circumference"],
  "preguntasParaMedicoEs": ["Cuanto dano tienen mis arterias coronarias?", "Necesito un stent o cirugia de bypass?", "Puedo hacer ejercicio y a que intensidad?", "Mis niveles de colesterol estan en meta?", "Cuanto tiempo debo tomar aspirina?"],
  "preguntasParaMedicoEn": ["How much damage do my coronary arteries have?", "Do I need a stent or bypass surgery?", "Can I exercise and at what intensity?", "Are my cholesterol levels at goal?", "How long should I take aspirin?"],
  "recursosApoyoEs": ["Programa de rehabilitacion cardiaca", "Grupos de apoyo de sobrevivientes cardiacos", "Nutricionista cardiologico", "Programa de cesacion del tabaquismo"],
  "recursosApoyoEn": ["Cardiac rehabilitation program", "Cardiac survivor support groups", "Cardiac nutritionist", "Smoking cessation program"],
  "vivienDoConEs": ["Lleve siempre su nitroglicerina consigo", "Aprenda a reconocer la diferencia entre angina estable e inestable", "Participe activamente en su rehabilitacion cardiaca", "Mantenga relaciones sociales activas", "No tenga miedo de la actividad fisica supervisada"],
  "vivienDoConEn": ["Always carry your nitroglycerin with you", "Learn to recognize the difference between stable and unstable angina", "Actively participate in your cardiac rehabilitation", "Maintain active social relationships", "Do not fear supervised physical activity"],
  "emergenciasEs": ["Dolor de pecho que no se alivia con nitroglicerina despues de 3 dosis", "Dolor de pecho que dura mas de 5 minutos", "Sudoracion fria con nauseas y dolor de pecho", "Desmayo o perdida de conciencia", "Dificultad severa para respirar subita"],
  "emergenciasEn": ["Chest pain not relieved by nitroglycerin after 3 doses", "Chest pain lasting more than 5 minutes", "Cold sweating with nausea and chest pain", "Fainting or loss of consciousness", "Sudden severe difficulty breathing"],
  "sistemasCorporales": ["cardiovascular"]
},
{
  "id": "enfermedad-arterial-periferica",
  "nombreEs": "Enfermedad arterial periferica",
  "nombreEn": "Peripheral Artery Disease",
  "descripcionEs": "Estrechamiento de las arterias perifericas, principalmente en las piernas, debido a la acumulacion de placa ateromatosa. Reduce el flujo sanguineo a las extremidades y puede causar dolor al caminar y aumentar el riesgo de amputacion.",
  "descripcionEn": "Narrowing of peripheral arteries, mainly in the legs, due to atherosclerotic plaque buildup. Reduces blood flow to extremities and can cause pain when walking and increase amputation risk.",
  "prevalencia": "Afecta a mas de 200 millones de personas en el mundo",
  "factoresRiesgoEs": ["Tabaquismo (factor de riesgo principal)", "Diabetes", "Hipertension", "Colesterol alto", "Edad mayor de 50 anos", "Antecedentes familiares de aterosclerosis", "Obesidad", "Sedentarismo"],
  "factoresRiesgoEn": ["Smoking (primary risk factor)", "Diabetes", "Hypertension", "High cholesterol", "Age over 50", "Family history of atherosclerosis", "Obesity", "Sedentary lifestyle"],
  "sintomasEs": ["Claudicacion intermitente (dolor en piernas al caminar que alivia con reposo)", "Piernas o pies frios", "Cambio de color en la piel de las piernas", "Heridas en pies o piernas que no cicatrizan", "Pulsos debiles en los pies", "Perdida de vello en las piernas", "Dolor en reposo en casos avanzados"],
  "sintomasEn": ["Intermittent claudication (leg pain when walking that resolves with rest)", "Cold legs or feet", "Skin color changes on legs", "Non-healing wounds on feet or legs", "Weak pulses in feet", "Hair loss on legs", "Rest pain in advanced cases"],
  "diagnosticoEs": ["Indice tobillo-brazo (ITB)", "Ecografia Doppler de las arterias de las piernas", "Angiografia por resonancia magnetica o tomografia", "Angiografia invasiva", "Prueba de caminata en banda"],
  "diagnosticoEn": ["Ankle-brachial index (ABI)", "Doppler ultrasound of leg arteries", "MR or CT angiography", "Invasive angiography", "Treadmill walking test"],
  "tratamientoEs": ["Cilostazol para mejorar la distancia de caminata", "Antiagregantes plaquetarios (aspirina, clopidogrel)", "Estatinas para control del colesterol", "Programa de ejercicio supervisado", "Angioplastia y stent en casos severos", "Cirugia de bypass vascular"],
  "tratamientoEn": ["Cilostazol to improve walking distance", "Antiplatelet agents (aspirin, clopidogrel)", "Statins for cholesterol control", "Supervised exercise program", "Angioplasty and stenting in severe cases", "Vascular bypass surgery"],
  "manejoEnCasaEs": ["Caminar diariamente hasta que aparezca el dolor, descansar y repetir", "Inspeccionar los pies todos los dias", "Mantener los pies limpios y secos", "Usar calzado comodo y protector", "No caminar descalzo", "Hidratar la piel de los pies"],
  "manejoEnCasaEn": ["Walk daily until pain appears, rest, and repeat", "Inspect feet every day", "Keep feet clean and dry", "Wear comfortable protective footwear", "Never walk barefoot", "Moisturize foot skin"],
  "cambiosEstiloVidaEs": ["Dejar de fumar es lo mas importante", "Programa de caminata progresiva", "Dieta baja en grasas saturadas", "Control estricto de diabetes si esta presente", "Control de presion arterial y colesterol"],
  "cambiosEstiloVidaEn": ["Quitting smoking is the most important step", "Progressive walking program", "Low saturated fat diet", "Strict diabetes control if present", "Blood pressure and cholesterol control"],
  "complicacionesEs": ["Isquemia critica de las extremidades", "Gangrena", "Amputacion", "Infarto al miocardio (aterosclerosis sistemica)", "Accidente cerebrovascular"],
  "complicacionesEn": ["Critical limb ischemia", "Gangrene", "Amputation", "Heart attack (systemic atherosclerosis)", "Stroke"],
  "monitorizacionEs": ["Indice tobillo-brazo periodico", "Inspeccion diaria de los pies", "Distancia de caminata sin dolor", "Cicatrizacion de heridas en los pies", "Perfil lipidico y glucosa"],
  "monitorizacionEn": ["Periodic ankle-brachial index", "Daily foot inspection", "Pain-free walking distance", "Wound healing on feet", "Lipid panel and glucose"],
  "preguntasParaMedicoEs": ["Necesito un procedimiento para abrir mis arterias?", "Cual es mi riesgo de amputacion?", "Cuanto debo caminar cada dia?", "Mis heridas en los pies estan cicatrizando bien?", "Necesito ver a un cirujano vascular?"],
  "preguntasParaMedicoEn": ["Do I need a procedure to open my arteries?", "What is my amputation risk?", "How much should I walk each day?", "Are my foot wounds healing well?", "Do I need to see a vascular surgeon?"],
  "recursosApoyoEs": ["Clinica de pie diabetico y vascular", "Programa de rehabilitacion vascular", "Programa de cesacion de tabaquismo", "Podologia especializada"],
  "recursosApoyoEn": ["Diabetic foot and vascular clinic", "Vascular rehabilitation program", "Smoking cessation program", "Specialized podiatry"],
  "vivienDoConEs": ["Deje de fumar, es la medida mas efectiva", "Camine todos los dias como parte de su tratamiento", "Cuide sus pies como si fueran de cristal", "No use bolsas de agua caliente en los pies", "Mantenga las unas de los pies cortas y rectas"],
  "vivienDoConEn": ["Quit smoking, it is the most effective measure", "Walk every day as part of your treatment", "Care for your feet as if they were fragile", "Do not use hot water bottles on feet", "Keep toenails short and straight"],
  "emergenciasEs": ["Dolor severo en reposo en el pie o la pierna", "Pie o dedos que se tornan azules o negros", "Herida que se infecta con enrojecimiento, calor y pus", "Perdida subita de sensacion en la pierna o pie", "Dolor de pecho o sintomas de accidente cerebrovascular"],
  "emergenciasEn": ["Severe rest pain in foot or leg", "Foot or toes turning blue or black", "Wound becoming infected with redness, warmth, and pus", "Sudden loss of sensation in leg or foot", "Chest pain or stroke symptoms"],
  "sistemasCorporales": ["cardiovascular", "vascular"]
},
{
  "id": "diabetes-tipo-1",
  "nombreEs": "Diabetes mellitus tipo 1",
  "nombreEn": "Type 1 Diabetes Mellitus",
  "descripcionEs": "Enfermedad autoinmune cronica en la que el sistema inmunologico destruye las celulas beta del pancreas que producen insulina. Requiere administracion de insulina de por vida. Generalmente se diagnostica en la infancia o adolescencia.",
  "descripcionEn": "Chronic autoimmune disease where the immune system destroys insulin-producing beta cells in the pancreas. Requires lifelong insulin administration. Usually diagnosed in childhood or adolescence.",
  "prevalencia": "Afecta a aproximadamente 9 millones de personas en el mundo",
  "factoresRiesgoEs": ["Predisposicion genetica (genes HLA)", "Antecedentes familiares de diabetes tipo 1", "Factores ambientales (infecciones virales)", "Geografia (mas comun en climas frios)", "Autoanticuerpos presentes antes del diagnostico"],
  "factoresRiesgoEn": ["Genetic predisposition (HLA genes)", "Family history of type 1 diabetes", "Environmental factors (viral infections)", "Geography (more common in cold climates)", "Autoantibodies present before diagnosis"],
  "sintomasEs": ["Sed excesiva (polidipsia)", "Miccion frecuente (poliuria)", "Hambre constante (polifagia)", "Perdida de peso inexplicable", "Fatiga extrema", "Vision borrosa", "Nauseas y vomitos", "Aliento con olor a frutas (cetoacidosis)"],
  "sintomasEn": ["Excessive thirst (polydipsia)", "Frequent urination (polyuria)", "Constant hunger (polyphagia)", "Unexplained weight loss", "Extreme fatigue", "Blurred vision", "Nausea and vomiting", "Fruity-smelling breath (ketoacidosis)"],
  "diagnosticoEs": ["Glucosa en ayunas mayor o igual a 126 mg/dL", "Hemoglobina glicosilada (HbA1c) mayor o igual a 6.5%", "Prueba de tolerancia oral a la glucosa", "Prueba de autoanticuerpos (GAD, IA-2, IAA)", "Peptido C bajo o indetectable"],
  "diagnosticoEn": ["Fasting glucose 126 mg/dL or higher", "Glycated hemoglobin (HbA1c) 6.5% or higher", "Oral glucose tolerance test", "Autoantibody testing (GAD, IA-2, IAA)", "Low or undetectable C-peptide"],
  "tratamientoEs": ["Insulina basal (glargina, detemir, degludec)", "Insulina de accion rapida en las comidas (lispro, aspart)", "Bomba de insulina", "Monitor continuo de glucosa (MCG)", "Sistemas de asa cerrada (pancreas artificial)", "Conteo de carbohidratos para dosificacion de insulina"],
  "tratamientoEn": ["Basal insulin (glargine, detemir, degludec)", "Rapid-acting insulin with meals (lispro, aspart)", "Insulin pump", "Continuous glucose monitor (CGM)", "Closed-loop systems (artificial pancreas)", "Carbohydrate counting for insulin dosing"],
  "manejoEnCasaEs": ["Medir la glucosa al menos 4-6 veces al dia o usar monitor continuo", "Contar los carbohidratos en cada comida", "Ajustar las dosis de insulina segun la glucosa y los carbohidratos", "Llevar siempre glucosa de accion rapida para hipoglucemias", "Rotar los sitios de inyeccion de insulina", "Almacenar la insulina correctamente (refrigerada)"],
  "manejoEnCasaEn": ["Check glucose at least 4-6 times daily or use continuous monitor", "Count carbohydrates at each meal", "Adjust insulin doses based on glucose and carbohydrates", "Always carry fast-acting glucose for hypoglycemia", "Rotate insulin injection sites", "Store insulin properly (refrigerated)"],
  "cambiosEstiloVidaEs": ["Aprender el conteo de carbohidratos", "Hacer ejercicio regularmente con planificacion previa", "Ajustar insulina antes del ejercicio", "Mantener horarios regulares de comida", "No saltarse comidas", "Manejar el estres (eleva la glucosa)", "Limitar el alcohol y siempre comer al beber"],
  "cambiosEstiloVidaEn": ["Learn carbohydrate counting", "Exercise regularly with prior planning", "Adjust insulin before exercise", "Maintain regular meal times", "Do not skip meals", "Manage stress (raises glucose)", "Limit alcohol and always eat when drinking"],
  "complicacionesEs": ["Hipoglucemia severa", "Cetoacidosis diabetica", "Retinopatia diabetica", "Nefropatia diabetica", "Neuropatia diabetica", "Enfermedad cardiovascular", "Pie diabetico"],
  "complicacionesEn": ["Severe hypoglycemia", "Diabetic ketoacidosis", "Diabetic retinopathy", "Diabetic nephropathy", "Diabetic neuropathy", "Cardiovascular disease", "Diabetic foot"],
  "monitorizacionEs": ["Glucosa capilar 4-6 veces al dia o monitor continuo de glucosa", "HbA1c cada 3 meses (meta menor de 7%)", "Funcion renal y microalbuminuria anual", "Examen oftalmologico anual", "Examen de pies en cada visita", "Perfil lipidico anual", "Presion arterial en cada visita"],
  "monitorizacionEn": ["Fingerstick glucose 4-6 times daily or continuous glucose monitor", "HbA1c every 3 months (goal less than 7%)", "Annual kidney function and microalbuminuria", "Annual eye exam", "Foot exam at each visit", "Annual lipid panel", "Blood pressure at each visit"],
  "preguntasParaMedicoEs": ["Cual es mi meta de HbA1c?", "Debo usar una bomba de insulina o monitor continuo?", "Como ajusto mi insulina cuando hago ejercicio?", "Con que frecuencia debo revisar mis ojos y rinones?", "Que hago si tengo glucosa muy baja?"],
  "preguntasParaMedicoEn": ["What is my HbA1c goal?", "Should I use an insulin pump or continuous monitor?", "How do I adjust insulin when I exercise?", "How often should I check my eyes and kidneys?", "What do I do if my glucose is very low?"],
  "recursosApoyoEs": ["Asociacion de Diabetes", "Educador en diabetes certificado", "Grupos de apoyo para personas con diabetes tipo 1", "Campamentos para ninos con diabetes", "Aplicaciones de conteo de carbohidratos"],
  "recursosApoyoEn": ["Diabetes Association", "Certified diabetes educator", "Type 1 diabetes support groups", "Camps for children with diabetes", "Carbohydrate counting apps"],
  "vivienDoConEs": ["La diabetes tipo 1 no es su culpa, es una enfermedad autoinmune", "Lleve siempre un kit de emergencia con glucosa y glucagon", "Informe a sus companeros de trabajo o escuela sobre su condicion", "Use una identificacion medica de diabetes", "Planifique con anticipacion para viajes y actividades", "Busque apoyo emocional, la fatiga de la diabetes es real"],
  "vivienDoConEn": ["Type 1 diabetes is not your fault, it is an autoimmune disease", "Always carry an emergency kit with glucose and glucagon", "Inform coworkers or school about your condition", "Wear a diabetes medical ID", "Plan ahead for travel and activities", "Seek emotional support, diabetes burnout is real"],
  "emergenciasEs": ["Glucosa menor de 54 mg/dL con confusion o perdida de conciencia", "Sintomas de cetoacidosis: vomitos, dolor abdominal, respiracion rapida, aliento frutal", "Glucosa mayor de 300 mg/dL con cetonas positivas", "Convulsiones por hipoglucemia", "Incapacidad para retener alimentos o liquidos"],
  "emergenciasEn": ["Glucose below 54 mg/dL with confusion or loss of consciousness", "Ketoacidosis symptoms: vomiting, abdominal pain, rapid breathing, fruity breath", "Glucose above 300 mg/dL with positive ketones", "Seizures from hypoglycemia", "Inability to keep food or liquids down"],
  "sistemasCorporales": ["endocrino", "metabolico"]
},
{
  "id": "diabetes-tipo-2",
  "nombreEs": "Diabetes mellitus tipo 2",
  "nombreEn": "Type 2 Diabetes Mellitus",
  "descripcionEs": "Enfermedad metabolica cronica caracterizada por resistencia a la insulina y produccion insuficiente de insulina por el pancreas. Es la forma mas comun de diabetes, representando el 90-95% de todos los casos. Se puede prevenir o retrasar con cambios en el estilo de vida.",
  "descripcionEn": "Chronic metabolic disease characterized by insulin resistance and insufficient insulin production by the pancreas. It is the most common form of diabetes, representing 90-95% of all cases. It can be prevented or delayed with lifestyle changes.",
  "prevalencia": "Afecta a mas de 460 millones de personas en el mundo",
  "factoresRiesgoEs": ["Sobrepeso u obesidad", "Sedentarismo", "Antecedentes familiares de diabetes", "Edad mayor de 45 anos", "Prediabetes", "Diabetes gestacional previa", "Sindrome de ovario poliquistico", "Etnicidad (hispanos, afroamericanos, nativos americanos)"],
  "factoresRiesgoEn": ["Overweight or obesity", "Sedentary lifestyle", "Family history of diabetes", "Age over 45", "Prediabetes", "Previous gestational diabetes", "Polycystic ovary syndrome", "Ethnicity (Hispanics, African Americans, Native Americans)"],
  "sintomasEs": ["Sed excesiva", "Miccion frecuente", "Aumento de apetito", "Fatiga", "Vision borrosa", "Heridas que tardan en cicatrizar", "Infecciones frecuentes", "Hormigueo en manos y pies", "Oscurecimiento de la piel en cuello y axilas (acantosis nigricans)"],
  "sintomasEn": ["Excessive thirst", "Frequent urination", "Increased appetite", "Fatigue", "Blurred vision", "Slow-healing wounds", "Frequent infections", "Tingling in hands and feet", "Darkened skin on neck and armpits (acanthosis nigricans)"],
  "diagnosticoEs": ["Glucosa en ayunas mayor o igual a 126 mg/dL", "HbA1c mayor o igual a 6.5%", "Prueba de tolerancia oral a la glucosa", "Glucosa al azar mayor de 200 mg/dL con sintomas"],
  "diagnosticoEn": ["Fasting glucose 126 mg/dL or higher", "HbA1c 6.5% or higher", "Oral glucose tolerance test", "Random glucose above 200 mg/dL with symptoms"],
  "tratamientoEs": ["Metformina como primera linea", "Inhibidores de SGLT2 (empagliflozina, dapagliflozina)", "Agonistas del receptor GLP-1 (semaglutida, liraglutida)", "Inhibidores de DPP-4 (sitagliptina)", "Sulfonilureas (glimepirida)", "Insulina cuando los medicamentos orales no son suficientes", "Cirugia bariatrica en obesidad severa"],
  "tratamientoEn": ["Metformin as first line", "SGLT2 inhibitors (empagliflozin, dapagliflozin)", "GLP-1 receptor agonists (semaglutide, liraglutide)", "DPP-4 inhibitors (sitagliptin)", "Sulfonylureas (glimepiride)", "Insulin when oral medications are insufficient", "Bariatric surgery in severe obesity"],
  "manejoEnCasaEs": ["Medir la glucosa segun indicacion medica", "Seguir un plan de alimentacion balanceado", "Hacer ejercicio regularmente", "Tomar medicamentos a la hora indicada", "Revisar los pies diariamente", "Llevar un registro de glucosa y alimentacion"],
  "manejoEnCasaEn": ["Check glucose as directed by your doctor", "Follow a balanced meal plan", "Exercise regularly", "Take medications at the scheduled time", "Check feet daily", "Keep a glucose and food log"],
  "cambiosEstiloVidaEs": ["Perder 5-10% del peso corporal", "Hacer 150 minutos de ejercicio moderado por semana", "Dieta rica en fibra, vegetales y proteinas magras", "Reducir carbohidratos refinados y azucares", "Comer porciones controladas", "Beber agua en lugar de bebidas azucaradas", "Dormir 7-8 horas por noche"],
  "cambiosEstiloVidaEn": ["Lose 5-10% of body weight", "Do 150 minutes of moderate exercise per week", "Diet rich in fiber, vegetables, and lean proteins", "Reduce refined carbohydrates and sugars", "Eat controlled portions", "Drink water instead of sugary beverages", "Sleep 7-8 hours per night"],
  "complicacionesEs": ["Enfermedad cardiovascular", "Retinopatia diabetica", "Nefropatia diabetica", "Neuropatia periferica", "Pie diabetico y amputaciones", "Estado hiperglucemico hiperosmolar", "Infecciones recurrentes"],
  "complicacionesEn": ["Cardiovascular disease", "Diabetic retinopathy", "Diabetic nephropathy", "Peripheral neuropathy", "Diabetic foot and amputations", "Hyperglycemic hyperosmolar state", "Recurrent infections"],
  "monitorizacionEs": ["Glucosa en ayunas y post-comida segun indicacion", "HbA1c cada 3-6 meses", "Funcion renal y microalbuminuria anual", "Examen oftalmologico anual", "Examen de pies en cada visita", "Perfil lipidico anual", "Presion arterial en cada visita"],
  "monitorizacionEn": ["Fasting and post-meal glucose as directed", "HbA1c every 3-6 months", "Annual kidney function and microalbuminuria", "Annual eye exam", "Foot exam at each visit", "Annual lipid panel", "Blood pressure at each visit"],
  "preguntasParaMedicoEs": ["Mi diabetes esta bien controlada?", "Necesito insulina?", "Puedo revertir mi diabetes con cambios de estilo de vida?", "Que medicamentos nuevos hay disponibles?", "Con que frecuencia debo medirme la glucosa?"],
  "preguntasParaMedicoEn": ["Is my diabetes well controlled?", "Do I need insulin?", "Can I reverse my diabetes with lifestyle changes?", "What new medications are available?", "How often should I check my glucose?"],
  "recursosApoyoEs": ["Programa de prevencion de diabetes", "Educador en diabetes certificado", "Nutricionista especializado en diabetes", "Grupos de apoyo para diabeticos", "Aplicaciones de control de diabetes"],
  "recursosApoyoEn": ["Diabetes Prevention Program", "Certified diabetes educator", "Nutritionist specialized in diabetes", "Diabetes support groups", "Diabetes management apps"],
  "vivienDoConEs": ["La diabetes tipo 2 se puede controlar y en algunos casos revertir", "Pequeños cambios en la dieta hacen una gran diferencia", "El ejercicio es tan importante como los medicamentos", "No se sienta culpable, busque apoyo", "Celebre sus logros en el control de la glucosa", "Eduque a su familia sobre la diabetes"],
  "vivienDoConEn": ["Type 2 diabetes can be controlled and in some cases reversed", "Small dietary changes make a big difference", "Exercise is as important as medication", "Do not feel guilty, seek support", "Celebrate your glucose control achievements", "Educate your family about diabetes"],
  "emergenciasEs": ["Glucosa mayor de 400 mg/dL", "Sintomas de estado hiperosmolar: confusion severa, deshidratacion extrema", "Hipoglucemia severa con perdida de conciencia", "Infeccion severa con glucosa descontrolada", "Herida en el pie que se infecta rapidamente"],
  "emergenciasEn": ["Glucose above 400 mg/dL", "Hyperosmolar state symptoms: severe confusion, extreme dehydration", "Severe hypoglycemia with loss of consciousness", "Severe infection with uncontrolled glucose", "Foot wound becoming rapidly infected"],
  "sistemasCorporales": ["endocrino", "metabolico"]
},
{
  "id": "prediabetes",
  "nombreEs": "Prediabetes",
  "nombreEn": "Prediabetes",
  "descripcionEs": "Condicion en la que los niveles de glucosa en sangre son mas altos de lo normal pero no lo suficientemente altos para diagnosticar diabetes tipo 2. Sin intervencion, la mayoria de las personas con prediabetes desarrollaran diabetes tipo 2 en 5-10 anos.",
  "descripcionEn": "Condition where blood glucose levels are higher than normal but not high enough to diagnose type 2 diabetes. Without intervention, most people with prediabetes will develop type 2 diabetes within 5-10 years.",
  "prevalencia": "Afecta a mas de 370 millones de personas en el mundo",
  "factoresRiesgoEs": ["Sobrepeso u obesidad", "Circunferencia de cintura elevada", "Sedentarismo", "Antecedentes familiares de diabetes", "Edad mayor de 45 anos", "Sindrome metabolico", "Diabetes gestacional previa"],
  "factoresRiesgoEn": ["Overweight or obesity", "Elevated waist circumference", "Sedentary lifestyle", "Family history of diabetes", "Age over 45", "Metabolic syndrome", "Previous gestational diabetes"],
  "sintomasEs": ["Generalmente no presenta sintomas", "Oscurecimiento de la piel en cuello, axilas o ingles", "Sed ligeramente aumentada", "Fatiga leve", "Vision ligeramente borrosa"],
  "sintomasEn": ["Generally no symptoms", "Skin darkening on neck, armpits, or groin", "Slightly increased thirst", "Mild fatigue", "Slightly blurred vision"],
  "diagnosticoEs": ["Glucosa en ayunas entre 100-125 mg/dL", "HbA1c entre 5.7-6.4%", "Prueba de tolerancia oral a la glucosa entre 140-199 mg/dL"],
  "diagnosticoEn": ["Fasting glucose between 100-125 mg/dL", "HbA1c between 5.7-6.4%", "Oral glucose tolerance test between 140-199 mg/dL"],
  "tratamientoEs": ["Cambios en el estilo de vida como primera linea", "Metformina en pacientes de alto riesgo", "Programa estructurado de prevencion de diabetes", "Seguimiento medico cada 6-12 meses"],
  "tratamientoEn": ["Lifestyle changes as first line", "Metformin in high-risk patients", "Structured diabetes prevention program", "Medical follow-up every 6-12 months"],
  "manejoEnCasaEs": ["Aumentar la actividad fisica diaria", "Reducir porciones de comida", "Elegir alimentos integrales sobre procesados", "Monitorear el peso semanalmente", "Reducir el consumo de bebidas azucaradas"],
  "manejoEnCasaEn": ["Increase daily physical activity", "Reduce food portions", "Choose whole foods over processed", "Monitor weight weekly", "Reduce sugary beverage consumption"],
  "cambiosEstiloVidaEs": ["Perder 5-7% del peso corporal", "Hacer al menos 150 minutos de ejercicio moderado por semana", "Reducir el consumo de carbohidratos refinados", "Aumentar el consumo de fibra", "Dormir adecuadamente", "Manejar el estres"],
  "cambiosEstiloVidaEn": ["Lose 5-7% of body weight", "Do at least 150 minutes of moderate exercise per week", "Reduce refined carbohydrate intake", "Increase fiber consumption", "Sleep adequately", "Manage stress"],
  "complicacionesEs": ["Progresion a diabetes tipo 2", "Enfermedad cardiovascular temprana", "Dano temprano a los rinones", "Sindrome metabolico"],
  "complicacionesEn": ["Progression to type 2 diabetes", "Early cardiovascular disease", "Early kidney damage", "Metabolic syndrome"],
  "monitorizacionEs": ["HbA1c cada 6-12 meses", "Glucosa en ayunas periodica", "Peso y circunferencia de cintura", "Presion arterial y perfil lipidico"],
  "monitorizacionEn": ["HbA1c every 6-12 months", "Periodic fasting glucose", "Weight and waist circumference", "Blood pressure and lipid panel"],
  "preguntasParaMedicoEs": ["Puedo revertir la prediabetes?", "Necesito medicamentos?", "Con que frecuencia debo hacerme analisis?", "Debo ver a un nutricionista?"],
  "preguntasParaMedicoEn": ["Can I reverse prediabetes?", "Do I need medications?", "How often should I get tested?", "Should I see a nutritionist?"],
  "recursosApoyoEs": ["Programa Nacional de Prevencion de Diabetes", "Nutricionista certificado", "Programas comunitarios de ejercicio", "Aplicaciones de seguimiento de alimentos"],
  "recursosApoyoEn": ["National Diabetes Prevention Program", "Certified nutritionist", "Community exercise programs", "Food tracking apps"],
  "vivienDoConEs": ["La prediabetes es una oportunidad para prevenir la diabetes", "Los cambios pequenos y constantes son mas efectivos que los drasticos", "No es una sentencia, es una advertencia que puede cambiar su futuro", "Involucre a su familia en los cambios saludables"],
  "vivienDoConEn": ["Prediabetes is an opportunity to prevent diabetes", "Small consistent changes are more effective than drastic ones", "It is not a sentence, it is a warning that can change your future", "Involve your family in healthy changes"],
  "emergenciasEs": ["No hay emergencias tipicas asociadas con prediabetes", "Busque atencion si desarrolla sintomas de diabetes (sed excesiva, miccion frecuente, perdida de peso inexplicable)"],
  "emergenciasEn": ["No typical emergencies associated with prediabetes", "Seek care if you develop diabetes symptoms (excessive thirst, frequent urination, unexplained weight loss)"],
  "sistemasCorporales": ["endocrino", "metabolico"]
},
{
  "id": "sindrome-metabolico",
  "nombreEs": "Sindrome metabolico",
  "nombreEn": "Metabolic Syndrome",
  "descripcionEs": "Conjunto de condiciones que ocurren juntas y aumentan el riesgo de enfermedad cardiaca, accidente cerebrovascular y diabetes tipo 2. Incluye presion arterial alta, glucosa elevada, exceso de grasa abdominal y niveles anormales de colesterol o trigliceridos.",
  "descripcionEn": "Cluster of conditions occurring together that increase the risk of heart disease, stroke, and type 2 diabetes. Includes high blood pressure, elevated glucose, excess abdominal fat, and abnormal cholesterol or triglyceride levels.",
  "prevalencia": "Afecta a aproximadamente 25% de la poblacion adulta mundial",
  "factoresRiesgoEs": ["Obesidad abdominal", "Resistencia a la insulina", "Sedentarismo", "Edad avanzada", "Antecedentes familiares", "Dieta rica en carbohidratos refinados", "Tabaquismo"],
  "factoresRiesgoEn": ["Abdominal obesity", "Insulin resistance", "Sedentary lifestyle", "Advanced age", "Family history", "Diet high in refined carbohydrates", "Smoking"],
  "sintomasEs": ["Circunferencia de cintura aumentada", "Presion arterial elevada", "Glucosa en ayunas elevada", "Trigliceridos altos", "HDL colesterol bajo", "Fatiga", "Dificultad para perder peso"],
  "sintomasEn": ["Increased waist circumference", "Elevated blood pressure", "Elevated fasting glucose", "High triglycerides", "Low HDL cholesterol", "Fatigue", "Difficulty losing weight"],
  "diagnosticoEs": ["Se diagnostica cuando se tienen 3 o mas de los siguientes criterios", "Cintura mayor de 102 cm en hombres o 88 cm en mujeres", "Trigliceridos de 150 mg/dL o mas", "HDL menor de 40 mg/dL en hombres o 50 mg/dL en mujeres", "Presion arterial de 130/85 mmHg o mas", "Glucosa en ayunas de 100 mg/dL o mas"],
  "diagnosticoEn": ["Diagnosed when 3 or more of the following criteria are met", "Waist greater than 102 cm in men or 88 cm in women", "Triglycerides 150 mg/dL or higher", "HDL less than 40 mg/dL in men or 50 mg/dL in women", "Blood pressure 130/85 mmHg or higher", "Fasting glucose 100 mg/dL or higher"],
  "tratamientoEs": ["Cambios agresivos en el estilo de vida", "Estatinas si el colesterol esta elevado", "Antihipertensivos si la presion esta alta", "Metformina si hay prediabetes", "Tratamiento de cada componente individual"],
  "tratamientoEn": ["Aggressive lifestyle changes", "Statins if cholesterol is elevated", "Antihypertensives if blood pressure is high", "Metformin if prediabetes is present", "Treatment of each individual component"],
  "manejoEnCasaEs": ["Medir la cintura periodicamente", "Controlar el peso semanalmente", "Seguir dieta baja en carbohidratos refinados", "Hacer ejercicio diariamente", "Tomar medicamentos segun indicacion"],
  "manejoEnCasaEn": ["Measure waist periodically", "Monitor weight weekly", "Follow diet low in refined carbohydrates", "Exercise daily", "Take medications as directed"],
  "cambiosEstiloVidaEs": ["Perder peso (meta 7-10% del peso corporal)", "Ejercicio aerobico y de resistencia combinado", "Dieta mediterranea o baja en carbohidratos", "Reducir el consumo de azucar y harinas refinadas", "Dejar de fumar", "Limitar el alcohol"],
  "cambiosEstiloVidaEn": ["Lose weight (goal 7-10% of body weight)", "Combined aerobic and resistance exercise", "Mediterranean or low-carbohydrate diet", "Reduce sugar and refined flour consumption", "Quit smoking", "Limit alcohol"],
  "complicacionesEs": ["Diabetes tipo 2", "Enfermedad cardiovascular", "Higado graso no alcoholico", "Enfermedad renal cronica", "Apnea del sueno"],
  "complicacionesEn": ["Type 2 diabetes", "Cardiovascular disease", "Non-alcoholic fatty liver disease", "Chronic kidney disease", "Sleep apnea"],
  "monitorizacionEs": ["Perfil lipidico cada 6 meses", "Glucosa y HbA1c cada 6 meses", "Presion arterial regular", "Peso y cintura mensual", "Funcion hepatica anual"],
  "monitorizacionEn": ["Lipid panel every 6 months", "Glucose and HbA1c every 6 months", "Regular blood pressure", "Monthly weight and waist", "Annual liver function"],
  "preguntasParaMedicoEs": ["Cuantos componentes del sindrome metabolico tengo?", "Puedo revertir el sindrome metabolico?", "Que tipo de dieta me recomienda?", "Necesito medicamentos para cada componente?"],
  "preguntasParaMedicoEn": ["How many components of metabolic syndrome do I have?", "Can I reverse metabolic syndrome?", "What type of diet do you recommend?", "Do I need medications for each component?"],
  "recursosApoyoEs": ["Programa de control de peso", "Nutricionista especializado", "Programa de ejercicio supervisado", "Apoyo psicologico para cambios de habitos"],
  "recursosApoyoEn": ["Weight management program", "Specialized nutritionist", "Supervised exercise program", "Psychological support for habit changes"],
  "vivienDoConEs": ["El sindrome metabolico es reversible con cambios de estilo de vida", "Enfoquese en perder grasa abdominal", "Cada componente que mejore reduce significativamente su riesgo", "Los cambios graduales son mas sostenibles"],
  "vivienDoConEn": ["Metabolic syndrome is reversible with lifestyle changes", "Focus on losing abdominal fat", "Each component you improve significantly reduces your risk", "Gradual changes are more sustainable"],
  "emergenciasEs": ["Dolor de pecho o sintomas de infarto", "Sintomas de accidente cerebrovascular", "Glucosa muy alta con sintomas de deshidratacion"],
  "emergenciasEn": ["Chest pain or heart attack symptoms", "Stroke symptoms", "Very high glucose with dehydration symptoms"],
  "sistemasCorporales": ["endocrino", "metabolico", "cardiovascular"]
},
{
  "id": "obesidad",
  "nombreEs": "Obesidad",
  "nombreEn": "Obesity",
  "descripcionEs": "Enfermedad cronica compleja caracterizada por una acumulacion excesiva de grasa corporal que afecta la salud. Se define por un indice de masa corporal (IMC) de 30 o mas. Es un factor de riesgo importante para muchas otras enfermedades cronicas.",
  "descripcionEn": "Complex chronic disease characterized by excessive body fat accumulation affecting health. Defined by a body mass index (BMI) of 30 or higher. It is a major risk factor for many other chronic diseases.",
  "prevalencia": "Afecta a mas de 650 millones de adultos en el mundo",
  "factoresRiesgoEs": ["Dieta alta en calorias y alimentos procesados", "Sedentarismo", "Genetica y antecedentes familiares", "Factores psicologicos (estres, depresion, ansiedad)", "Medicamentos que causan aumento de peso", "Trastornos hormonales", "Falta de sueno", "Factores socioeconomicos"],
  "factoresRiesgoEn": ["High-calorie diet and processed foods", "Sedentary lifestyle", "Genetics and family history", "Psychological factors (stress, depression, anxiety)", "Weight-gaining medications", "Hormonal disorders", "Lack of sleep", "Socioeconomic factors"],
  "sintomasEs": ["IMC de 30 o mas", "Exceso de grasa corporal especialmente abdominal", "Dificultad para respirar con actividad minima", "Dolor articular por el peso excesivo", "Sudoracion excesiva", "Fatiga cronica", "Ronquidos y apnea del sueno", "Baja autoestima y problemas emocionales"],
  "sintomasEn": ["BMI of 30 or higher", "Excess body fat especially abdominal", "Difficulty breathing with minimal activity", "Joint pain from excess weight", "Excessive sweating", "Chronic fatigue", "Snoring and sleep apnea", "Low self-esteem and emotional problems"],
  "diagnosticoEs": ["Indice de masa corporal (IMC) de 30 o mas", "Medicion de circunferencia de cintura", "Analisis de composicion corporal", "Analisis de sangre (glucosa, lipidos, tiroides, funcion hepatica)", "Evaluacion de comorbilidades"],
  "diagnosticoEn": ["Body mass index (BMI) of 30 or higher", "Waist circumference measurement", "Body composition analysis", "Blood tests (glucose, lipids, thyroid, liver function)", "Comorbidity assessment"],
  "tratamientoEs": ["Terapia nutricional con deficit calorico moderado", "Programa de actividad fisica progresivo", "Terapia cognitivo-conductual", "Medicamentos para perdida de peso (semaglutida, tirzepatida, orlistat)", "Cirugia bariatrica en obesidad severa (IMC mayor de 40 o 35 con comorbilidades)", "Apoyo psicologico"],
  "tratamientoEn": ["Nutritional therapy with moderate caloric deficit", "Progressive physical activity program", "Cognitive behavioral therapy", "Weight loss medications (semaglutide, tirzepatide, orlistat)", "Bariatric surgery in severe obesity (BMI over 40 or 35 with comorbidities)", "Psychological support"],
  "manejoEnCasaEs": ["Planificar comidas y meriendas saludables", "Pesar y medir porciones", "Hacer ejercicio al menos 30 minutos diarios", "Llevar un diario de alimentos y actividad", "Beber agua antes de las comidas", "Dormir 7-9 horas por noche"],
  "manejoEnCasaEn": ["Plan healthy meals and snacks", "Weigh and measure portions", "Exercise at least 30 minutes daily", "Keep a food and activity diary", "Drink water before meals", "Sleep 7-9 hours per night"],
  "cambiosEstiloVidaEs": ["Reducir porciones gradualmente", "Eliminar bebidas azucaradas", "Cocinar en casa mas frecuentemente", "Aumentar el consumo de vegetales y fibra", "Caminar al menos 10000 pasos diarios", "Reducir el tiempo frente a pantallas", "Manejar el estres sin recurrir a la comida"],
  "cambiosEstiloVidaEn": ["Reduce portions gradually", "Eliminate sugary beverages", "Cook at home more frequently", "Increase vegetable and fiber consumption", "Walk at least 10000 steps daily", "Reduce screen time", "Manage stress without resorting to food"],
  "complicacionesEs": ["Diabetes tipo 2", "Enfermedad cardiovascular", "Apnea del sueno", "Osteoartritis", "Higado graso", "Ciertos tipos de cancer", "Infertilidad", "Depresion y ansiedad"],
  "complicacionesEn": ["Type 2 diabetes", "Cardiovascular disease", "Sleep apnea", "Osteoarthritis", "Fatty liver", "Certain types of cancer", "Infertility", "Depression and anxiety"],
  "monitorizacionEs": ["Peso semanal (no diario para evitar obsesion)", "Circunferencia de cintura mensual", "Glucosa y HbA1c cada 6 meses", "Perfil lipidico anual", "Presion arterial regular", "Evaluacion psicologica periodica"],
  "monitorizacionEn": ["Weekly weight (not daily to avoid obsession)", "Monthly waist circumference", "Glucose and HbA1c every 6 months", "Annual lipid panel", "Regular blood pressure", "Periodic psychological assessment"],
  "preguntasParaMedicoEs": ["Cuales son mis opciones de tratamiento?", "Los medicamentos para bajar de peso son adecuados para mi?", "Debo considerar cirugia bariatrica?", "Hay condiciones medicas que contribuyen a mi peso?", "Puede referirme a un nutricionista?"],
  "preguntasParaMedicoEn": ["What are my treatment options?", "Are weight loss medications appropriate for me?", "Should I consider bariatric surgery?", "Are there medical conditions contributing to my weight?", "Can you refer me to a nutritionist?"],
  "recursosApoyoEs": ["Programa multidisciplinario de control de peso", "Nutricionista clinico", "Psicologo especializado en trastornos alimentarios", "Grupos de apoyo para personas con obesidad", "Programa de ejercicio adaptado"],
  "recursosApoyoEn": ["Multidisciplinary weight management program", "Clinical nutritionist", "Psychologist specialized in eating disorders", "Obesity support groups", "Adapted exercise program"],
  "vivienDoConEs": ["La obesidad es una enfermedad, no una falta de voluntad", "Cada kilo que pierda mejora su salud significativamente", "Busque apoyo profesional, no enfrente esto solo", "Evite dietas extremas, busque cambios sostenibles", "Sea compasivo consigo mismo en el proceso"],
  "vivienDoConEn": ["Obesity is a disease, not a lack of willpower", "Every pound you lose significantly improves your health", "Seek professional support, do not face this alone", "Avoid extreme diets, seek sustainable changes", "Be compassionate with yourself in the process"],
  "emergenciasEs": ["Dificultad severa para respirar", "Dolor de pecho", "Signos de trombosis venosa (pierna hinchada, roja y dolorosa)", "Pensamientos de autolesion o suicidio", "Incapacidad para realizar actividades basicas"],
  "emergenciasEn": ["Severe difficulty breathing", "Chest pain", "Signs of venous thrombosis (swollen, red, painful leg)", "Thoughts of self-harm or suicide", "Inability to perform basic activities"],
  "sistemasCorporales": ["endocrino", "metabolico", "musculoesqueletico"]
},
{
  "id": "hipotiroidismo",
  "nombreEs": "Hipotiroidismo",
  "nombreEn": "Hypothyroidism",
  "descripcionEs": "Condicion en la que la glandula tiroides no produce suficientes hormonas tiroideas, lo que ralentiza el metabolismo del cuerpo. La causa mas comun es la tiroiditis de Hashimoto, una enfermedad autoinmune.",
  "descripcionEn": "Condition where the thyroid gland does not produce enough thyroid hormones, slowing the body's metabolism. The most common cause is Hashimoto's thyroiditis, an autoimmune disease.",
  "prevalencia": "Afecta al 5% de la poblacion, mas comun en mujeres",
  "factoresRiesgoEs": ["Sexo femenino", "Edad mayor de 60 anos", "Antecedentes familiares de enfermedad tiroidea", "Enfermedad autoinmune (Hashimoto)", "Tratamiento previo con yodo radioactivo", "Cirugia de tiroides previa", "Radiacion en cuello"],
  "factoresRiesgoEn": ["Female sex", "Age over 60", "Family history of thyroid disease", "Autoimmune disease (Hashimoto's)", "Previous radioactive iodine treatment", "Previous thyroid surgery", "Radiation to neck"],
  "sintomasEs": ["Fatiga y somnolencia", "Aumento de peso inexplicable", "Intolerancia al frio", "Piel seca y cabello quebradizo", "Estrenimiento", "Depresion", "Problemas de memoria y concentracion", "Debilidad muscular", "Menstruaciones irregulares o abundantes", "Colesterol elevado"],
  "sintomasEn": ["Fatigue and drowsiness", "Unexplained weight gain", "Cold intolerance", "Dry skin and brittle hair", "Constipation", "Depression", "Memory and concentration problems", "Muscle weakness", "Irregular or heavy menstruation", "Elevated cholesterol"],
  "diagnosticoEs": ["TSH elevada (prueba principal)", "T4 libre baja", "Anticuerpos antitiroideos (anti-TPO, antitiroglobulina)", "Ecografia de tiroides si hay nodulos"],
  "diagnosticoEn": ["Elevated TSH (primary test)", "Low free T4", "Thyroid antibodies (anti-TPO, antithyroglobulin)", "Thyroid ultrasound if nodules present"],
  "tratamientoEs": ["Levotiroxina (hormona tiroidea sintetica) de por vida", "Tomar en ayunas 30-60 minutos antes del desayuno", "Ajuste de dosis segun niveles de TSH", "No cambiar de marca sin consultar al medico"],
  "tratamientoEn": ["Levothyroxine (synthetic thyroid hormone) for life", "Take on empty stomach 30-60 minutes before breakfast", "Dose adjustment based on TSH levels", "Do not change brands without consulting doctor"],
  "manejoEnCasaEs": ["Tomar levotiroxina a la misma hora cada dia", "No tomar con calcio, hierro o antiacidos (esperar 4 horas)", "No suspender el medicamento por sentirse bien", "Mantener una dieta equilibrada", "Hacer ejercicio regular para combatir la fatiga"],
  "manejoEnCasaEn": ["Take levothyroxine at the same time each day", "Do not take with calcium, iron, or antacids (wait 4 hours)", "Do not stop medication because you feel well", "Maintain a balanced diet", "Exercise regularly to combat fatigue"],
  "cambiosEstiloVidaEs": ["Ejercicio regular para mejorar el metabolismo", "Dieta rica en selenio y yodo", "Manejar el estres", "Dormir adecuadamente", "Evitar dietas extremas"],
  "cambiosEstiloVidaEn": ["Regular exercise to improve metabolism", "Diet rich in selenium and iodine", "Manage stress", "Sleep adequately", "Avoid extreme diets"],
  "complicacionesEs": ["Bocio", "Enfermedad cardiovascular", "Neuropatia periferica", "Infertilidad", "Mixedema (hipotiroidismo severo)", "Depresion severa", "Defectos congenitos si no se trata durante el embarazo"],
  "complicacionesEn": ["Goiter", "Cardiovascular disease", "Peripheral neuropathy", "Infertility", "Myxedema (severe hypothyroidism)", "Severe depression", "Birth defects if untreated during pregnancy"],
  "monitorizacionEs": ["TSH cada 6-8 semanas al inicio, luego cada 6-12 meses", "T4 libre periodica", "Perfil lipidico anual", "Peso regular", "Sintomas de hipo o hipertiroidismo"],
  "monitorizacionEn": ["TSH every 6-8 weeks initially, then every 6-12 months", "Periodic free T4", "Annual lipid panel", "Regular weight", "Symptoms of hypo or hyperthyroidism"],
  "preguntasParaMedicoEs": ["Mi dosis de levotiroxina es adecuada?", "Necesito revision de la tiroides con ecografia?", "El hipotiroidismo afecta mi fertilidad?", "Puedo tomar otros medicamentos con levotiroxina?", "Necesitare este medicamento de por vida?"],
  "preguntasParaMedicoEn": ["Is my levothyroxine dose adequate?", "Do I need a thyroid ultrasound?", "Does hypothyroidism affect my fertility?", "Can I take other medications with levothyroxine?", "Will I need this medication for life?"],
  "recursosApoyoEs": ["Asociacion de pacientes tiroideos", "Endocrinologo", "Grupos de apoyo en linea", "Material educativo sobre tiroides"],
  "recursosApoyoEn": ["Thyroid patient association", "Endocrinologist", "Online support groups", "Thyroid educational materials"],
  "vivienDoConEs": ["Con el tratamiento adecuado, puede llevar una vida completamente normal", "Sea paciente, encontrar la dosis correcta puede tomar tiempo", "No culpe todos sus sintomas al hipotiroidismo", "Mantenga una rutina de medicamentos consistente"],
  "vivienDoConEn": ["With proper treatment, you can lead a completely normal life", "Be patient, finding the right dose may take time", "Do not blame all symptoms on hypothyroidism", "Maintain a consistent medication routine"],
  "emergenciasEs": ["Sintomas de mixedema: confusion severa, hipotermia, somnolencia extrema", "Hinchazon facial severa", "Frecuencia cardiaca muy lenta", "Dificultad para respirar"],
  "emergenciasEn": ["Myxedema symptoms: severe confusion, hypothermia, extreme drowsiness", "Severe facial swelling", "Very slow heart rate", "Difficulty breathing"],
  "sistemasCorporales": ["endocrino"]
},
{
  "id": "hipertiroidismo",
  "nombreEs": "Hipertiroidismo",
  "nombreEn": "Hyperthyroidism",
  "descripcionEs": "Condicion en la que la glandula tiroides produce exceso de hormonas tiroideas, acelerando el metabolismo del cuerpo. La causa mas comun es la enfermedad de Graves, una enfermedad autoinmune.",
  "descripcionEn": "Condition where the thyroid gland produces excess thyroid hormones, speeding up the body's metabolism. The most common cause is Graves' disease, an autoimmune disorder.",
  "prevalencia": "Afecta al 1-2% de la poblacion, mas comun en mujeres",
  "factoresRiesgoEs": ["Sexo femenino", "Antecedentes familiares de enfermedad tiroidea", "Enfermedad de Graves", "Nodulos tiroideos toxicos", "Ingesta excesiva de yodo", "Ciertos medicamentos (amiodarona)"],
  "factoresRiesgoEn": ["Female sex", "Family history of thyroid disease", "Graves' disease", "Toxic thyroid nodules", "Excessive iodine intake", "Certain medications (amiodarone)"],
  "sintomasEs": ["Perdida de peso inexplicable", "Taquicardia y palpitaciones", "Temblor en las manos", "Nerviosismo y ansiedad", "Intolerancia al calor y sudoracion excesiva", "Diarrea frecuente", "Insomnio", "Ojos saltones (en enfermedad de Graves)", "Debilidad muscular", "Menstruaciones irregulares o escasas"],
  "sintomasEn": ["Unexplained weight loss", "Tachycardia and palpitations", "Hand tremor", "Nervousness and anxiety", "Heat intolerance and excessive sweating", "Frequent diarrhea", "Insomnia", "Bulging eyes (in Graves' disease)", "Muscle weakness", "Irregular or light menstruation"],
  "diagnosticoEs": ["TSH suprimida (muy baja)", "T4 libre y T3 elevadas", "Anticuerpos contra el receptor de TSH (enfermedad de Graves)", "Gammagrafia tiroidea", "Ecografia de tiroides"],
  "diagnosticoEn": ["Suppressed TSH (very low)", "Elevated free T4 and T3", "TSH receptor antibodies (Graves' disease)", "Thyroid scan", "Thyroid ultrasound"],
  "tratamientoEs": ["Medicamentos antitiroideos (metimazol, propiltiouracilo)", "Betabloqueadores para controlar los sintomas", "Yodo radioactivo para destruir parte de la tiroides", "Cirugia de tiroides (tiroidectomia)", "Levotiroxina despues del yodo radioactivo o cirugia"],
  "tratamientoEn": ["Antithyroid medications (methimazole, propylthiouracil)", "Beta-blockers to control symptoms", "Radioactive iodine to destroy part of the thyroid", "Thyroid surgery (thyroidectomy)", "Levothyroxine after radioactive iodine or surgery"],
  "manejoEnCasaEs": ["Tomar medicamentos antitiroideos exactamente como se indica", "Evitar alimentos muy ricos en yodo", "Descansar lo suficiente", "Manejar el estres con tecnicas de relajacion", "Proteger los ojos del sol y el viento si hay oftalmopatia"],
  "manejoEnCasaEn": ["Take antithyroid medications exactly as directed", "Avoid foods very high in iodine", "Get enough rest", "Manage stress with relaxation techniques", "Protect eyes from sun and wind if ophthalmopathy present"],
  "cambiosEstiloVidaEs": ["Dieta equilibrada con calorias suficientes", "Ejercicio moderado (evitar exceso de calor)", "Reducir cafeina", "Tecnicas de relajacion para la ansiedad", "Proteccion ocular si hay enfermedad de Graves"],
  "cambiosEstiloVidaEn": ["Balanced diet with sufficient calories", "Moderate exercise (avoid excessive heat)", "Reduce caffeine", "Relaxation techniques for anxiety", "Eye protection if Graves' disease present"],
  "complicacionesEs": ["Crisis tirotoxica (tormenta tiroidea)", "Fibrilacion auricular", "Osteoporosis", "Insuficiencia cardiaca", "Oftalmopatia de Graves", "Infertilidad"],
  "complicacionesEn": ["Thyrotoxic crisis (thyroid storm)", "Atrial fibrillation", "Osteoporosis", "Heart failure", "Graves' ophthalmopathy", "Infertility"],
  "monitorizacionEs": ["TSH y T4 libre cada 4-6 semanas durante el tratamiento", "Hemograma (los antitiroideos pueden afectar globulos blancos)", "Funcion hepatica periodica", "Frecuencia cardiaca y peso", "Evaluacion oftalmologica si hay enfermedad de Graves"],
  "monitorizacionEn": ["TSH and free T4 every 4-6 weeks during treatment", "Complete blood count (antithyroid drugs can affect white cells)", "Periodic liver function", "Heart rate and weight", "Ophthalmologic evaluation if Graves' disease"],
  "preguntasParaMedicoEs": ["Cual es la causa de mi hipertiroidismo?", "Necesito yodo radioactivo o cirugia?", "Los medicamentos antitiroideos son seguros a largo plazo?", "Mis ojos estan afectados?", "Necesitare medicamentos de por vida?"],
  "preguntasParaMedicoEn": ["What is causing my hyperthyroidism?", "Do I need radioactive iodine or surgery?", "Are antithyroid medications safe long-term?", "Are my eyes affected?", "Will I need medications for life?"],
  "recursosApoyoEs": ["Endocrinologo especialista", "Oftalmologo si hay afectacion ocular", "Grupos de apoyo de Graves", "Material educativo sobre hipertiroidismo"],
  "recursosApoyoEn": ["Specialist endocrinologist", "Ophthalmologist if eyes affected", "Graves' disease support groups", "Hyperthyroidism educational materials"],
  "vivienDoConEs": ["El hipertiroidismo es tratable y controlable", "Sea paciente durante el ajuste del tratamiento", "Comunique a su medico cualquier sintoma nuevo", "Use lentes de sol y lagrimas artificiales si los ojos estan afectados"],
  "vivienDoConEn": ["Hyperthyroidism is treatable and controllable", "Be patient during treatment adjustment", "Tell your doctor about any new symptoms", "Use sunglasses and artificial tears if eyes are affected"],
  "emergenciasEs": ["Tormenta tiroidea: fiebre alta, taquicardia severa, agitacion, confusion", "Frecuencia cardiaca mayor de 150 latidos por minuto", "Fiebre con dolor de garganta (posible efecto secundario de antitiroideos)", "Ictericia (efecto secundario hepatico raro)"],
  "emergenciasEn": ["Thyroid storm: high fever, severe tachycardia, agitation, confusion", "Heart rate above 150 beats per minute", "Fever with sore throat (possible antithyroid drug side effect)", "Jaundice (rare liver side effect)"],
  "sistemasCorporales": ["endocrino"]
},
{
  "id": "osteoporosis",
  "nombreEs": "Osteoporosis",
  "nombreEn": "Osteoporosis",
  "descripcionEs": "Enfermedad cronica que debilita los huesos haciendolos fragiles y propensos a fracturas. Los huesos pierden densidad y masa osea, lo que aumenta el riesgo de fracturas con traumatismos minimos o incluso sin trauma.",
  "descripcionEn": "Chronic disease that weakens bones making them fragile and prone to fractures. Bones lose density and mass, increasing fracture risk with minimal trauma or even without trauma.",
  "prevalencia": "Afecta a 200 millones de personas en el mundo, principalmente mujeres posmenopausicas",
  "factoresRiesgoEs": ["Sexo femenino", "Menopausia y deficiencia de estrogenos", "Edad avanzada", "Antecedentes familiares de osteoporosis", "Bajo peso corporal", "Tabaquismo", "Consumo excesivo de alcohol", "Uso prolongado de corticosteroides", "Deficiencia de calcio y vitamina D", "Sedentarismo"],
  "factoresRiesgoEn": ["Female sex", "Menopause and estrogen deficiency", "Advanced age", "Family history of osteoporosis", "Low body weight", "Smoking", "Excessive alcohol consumption", "Prolonged corticosteroid use", "Calcium and vitamin D deficiency", "Sedentary lifestyle"],
  "sintomasEs": ["Generalmente no hay sintomas hasta que ocurre una fractura", "Perdida de estatura con el tiempo", "Postura encorvada (cifosis)", "Dolor de espalda por fracturas vertebrales por compresion", "Fracturas con traumatismos minimos"],
  "sintomasEn": ["Generally no symptoms until a fracture occurs", "Loss of height over time", "Stooped posture (kyphosis)", "Back pain from vertebral compression fractures", "Fractures with minimal trauma"],
  "diagnosticoEs": ["Densitometria osea (DEXA scan) con puntuacion T", "T-score de -2.5 o menor indica osteoporosis", "T-score entre -1.0 y -2.5 indica osteopenia", "Evaluacion del riesgo de fractura (FRAX)", "Analisis de sangre (calcio, vitamina D, fosfatasa alcalina)"],
  "diagnosticoEn": ["Bone density test (DEXA scan) with T-score", "T-score of -2.5 or lower indicates osteoporosis", "T-score between -1.0 and -2.5 indicates osteopenia", "Fracture risk assessment (FRAX)", "Blood tests (calcium, vitamin D, alkaline phosphatase)"],
  "tratamientoEs": ["Bisfosfonatos (alendronato, risedronato, acido zoledronico)", "Denosumab (inyeccion subcutanea cada 6 meses)", "Teriparatida o abaloparatida (agentes anabolicos oseos)", "Suplementos de calcio (1000-1200 mg/dia) y vitamina D (800-1000 UI/dia)", "Terapia hormonal en mujeres posmenopausicas seleccionadas", "Romosozumab en alto riesgo"],
  "tratamientoEn": ["Bisphosphonates (alendronate, risedronate, zoledronic acid)", "Denosumab (subcutaneous injection every 6 months)", "Teriparatide or abaloparatide (bone anabolic agents)", "Calcium supplements (1000-1200 mg/day) and vitamin D (800-1000 IU/day)", "Hormone therapy in selected postmenopausal women", "Romosozumab in high risk"],
  "manejoEnCasaEs": ["Tomar calcio y vitamina D diariamente", "Hacer ejercicios de resistencia y con peso corporal", "Prevenir caidas en el hogar (quitar alfombras sueltas, buena iluminacion)", "Usar calzado seguro y antideslizante", "Levantarse lentamente para evitar mareos", "Evitar agacharse desde la cintura, doblar las rodillas"],
  "manejoEnCasaEn": ["Take calcium and vitamin D daily", "Do resistance and weight-bearing exercises", "Prevent falls at home (remove loose rugs, good lighting)", "Wear safe non-slip footwear", "Stand up slowly to avoid dizziness", "Avoid bending from the waist, bend knees instead"],
  "cambiosEstiloVidaEs": ["Ejercicios con peso y resistencia regularmente", "Dieta rica en calcio (lacteos, vegetales verdes, sardinas)", "Exposicion segura al sol para vitamina D", "Dejar de fumar", "Limitar el alcohol", "Practicar ejercicios de equilibrio (tai chi, yoga)"],
  "cambiosEstiloVidaEn": ["Regular weight-bearing and resistance exercises", "Calcium-rich diet (dairy, green vegetables, sardines)", "Safe sun exposure for vitamin D", "Quit smoking", "Limit alcohol", "Practice balance exercises (tai chi, yoga)"],
  "complicacionesEs": ["Fracturas de cadera (alta mortalidad en ancianos)", "Fracturas vertebrales por compresion", "Fracturas de muneca", "Dolor cronico", "Discapacidad y perdida de independencia", "Cifosis severa"],
  "complicacionesEn": ["Hip fractures (high mortality in elderly)", "Vertebral compression fractures", "Wrist fractures", "Chronic pain", "Disability and loss of independence", "Severe kyphosis"],
  "monitorizacionEs": ["Densitometria osea cada 1-2 anos", "Niveles de vitamina D y calcio anuales", "Estatura en cada visita medica", "Evaluacion de riesgo de caidas", "Revision de medicamentos que afectan los huesos"],
  "monitorizacionEn": ["Bone density test every 1-2 years", "Annual vitamin D and calcium levels", "Height at each medical visit", "Fall risk assessment", "Review of medications affecting bones"],
  "preguntasParaMedicoEs": ["Cual es mi puntuacion T actual?", "Necesito medicamentos o solo suplementos?", "Cuanto calcio y vitamina D necesito?", "Que ejercicios son seguros para mi?", "Cuanto tiempo necesito tomar bisfosfonatos?"],
  "preguntasParaMedicoEn": ["What is my current T-score?", "Do I need medications or just supplements?", "How much calcium and vitamin D do I need?", "What exercises are safe for me?", "How long do I need to take bisphosphonates?"],
  "recursosApoyoEs": ["Fundacion de Osteoporosis", "Fisioterapia especializada", "Programa de prevencion de caidas", "Grupos de ejercicio para adultos mayores"],
  "recursosApoyoEn": ["Osteoporosis Foundation", "Specialized physical therapy", "Fall prevention program", "Exercise groups for older adults"],
  "vivienDoConEs": ["La osteoporosis se puede manejar y las fracturas se pueden prevenir", "La prevencion de caidas es tan importante como los medicamentos", "Nunca es tarde para fortalecer los huesos con ejercicio", "Adapte su hogar para reducir riesgo de caidas"],
  "vivienDoConEn": ["Osteoporosis can be managed and fractures can be prevented", "Fall prevention is as important as medications", "It is never too late to strengthen bones with exercise", "Adapt your home to reduce fall risk"],
  "emergenciasEs": ["Dolor severo subito en la espalda, cadera o muneca despues de una caida", "Incapacidad para ponerse de pie despues de una caida", "Dolor severo de espalda que aparece sin trauma", "Cambio subito en la estatura o postura"],
  "emergenciasEn": ["Sudden severe pain in back, hip, or wrist after a fall", "Inability to stand after a fall", "Severe back pain appearing without trauma", "Sudden change in height or posture"],
  "sistemasCorporales": ["musculoesqueletico", "endocrino"]
}
]`);

export { cronicasData };
