import { EducationalContent } from '../../types';

export const FITNESS_TRACKER_BASICS: EducationalContent = {
  id: 'wearables-fitness-tracker-basics',
  type: 'concept',
  name: 'Fitness Tracker Basics',
  alternateNames: ['Activity Trackers', 'Fitness Bands', 'Step Counters', 'Health Trackers', 'Wearable Fitness Devices'],
  levels: {
    1: {
      level: 1,
      summary: 'Fitness trackers are wearable devices, usually worn on the wrist, that count your steps, monitor your heart rate, and track your physical activity.',
      explanation: 'Fitness trackers are small electronic devices that you wear, usually like a watch or bracelet, to keep track of how active you are. They use special sensors to count how many steps you take each day, and many can also measure your heart rate by shining a light through your skin. Most fitness trackers connect to an app on your phone where you can see all your information in charts and graphs. They can track things like how far you walked or ran, how many calories you might have burned, and even how well you slept. Many trackers also send you reminders to get up and move if you have been sitting too long. Fitness trackers can help motivate you to be more active by setting goals and showing your progress. Popular brands include Fitbit, Garmin, and Apple Watch.',
      keyTerms: [
        { term: 'steps', definition: 'The number of footsteps counted by your fitness tracker' },
        { term: 'heart rate', definition: 'How fast your heart is beating, measured in beats per minute' },
        { term: 'activity', definition: 'Physical movement and exercise tracked by your device' },
        { term: 'wearable', definition: 'A device you wear on your body, like a watch or bracelet' },
        { term: 'app', definition: 'Software on your phone that shows your fitness data' },
        { term: 'goals', definition: 'Targets you set for steps, exercise, or other activities' },
      ],
    },
    2: {
      level: 2,
      summary: 'Fitness trackers are wearable devices using accelerometers, optical heart rate sensors, and other technologies to monitor physical activity, physiological metrics, and health behaviors.',
      explanation: 'Fitness trackers employ multiple sensor technologies to capture health and activity data. Accelerometers detect motion and orientation, enabling step counting, distance estimation, and activity type recognition. Optical heart rate sensors (photoplethysmography or PPG) measure pulse by detecting blood volume changes through skin. Many devices also include GPS for accurate distance and route tracking during outdoor activities. Advanced features may include altimeters for elevation tracking, skin temperature sensors, and SpO2 sensors for blood oxygen estimation. Data from these sensors is processed by onboard algorithms to calculate metrics like steps, active minutes, calories burned (estimated using metabolic equations), sleep duration and quality, and exercise intensity. The companion smartphone applications aggregate data over time, enabling users to view trends, set goals, participate in challenges, and receive personalized insights. Research evidence suggests fitness trackers can increase physical activity levels in the short term, though sustained behavior change depends on user engagement and goal-setting. Consumer fitness trackers are not regulated as medical devices and may have variable accuracy, particularly for metrics beyond step counting.',
      keyTerms: [
        { term: 'accelerometer', definition: 'Sensor detecting motion and orientation for step counting' },
        { term: 'photoplethysmography', definition: 'Light-based technology measuring heart rate through skin' },
        { term: 'GPS', definition: 'Global Positioning System for tracking outdoor distance and routes' },
        { term: 'algorithm', definition: 'Mathematical formulas processing sensor data into metrics' },
        { term: 'calories', definition: 'Estimated energy expenditure calculated from activity data' },
        { term: 'sleep tracking', definition: 'Monitoring sleep duration and quality using movement and heart rate' },
        { term: 'accuracy', definition: 'How closely device measurements match actual values' },
      ],
    },
    3: {
      level: 3,
      summary: 'Consumer fitness trackers integrate multi-sensor arrays with proprietary algorithms to estimate physical activity, cardiovascular, and sleep parameters, with validation research demonstrating variable accuracy across metrics and use contexts.',
      explanation: 'The technical architecture of fitness trackers combines hardware sensors, signal processing, and machine learning algorithms. Accelerometer-based activity recognition uses pattern classification to distinguish activities (walking, running, cycling, stationary) from raw motion data, with step detection algorithms applying filtering and peak detection to accelerometer signals. Optical heart rate measurement faces accuracy challenges during vigorous movement, darker skin tones, and poor device fit, with validation studies showing wider error margins than medical-grade devices. Energy expenditure estimation combines heart rate, motion data, and user demographics through proprietary algorithms, with research indicating systematic overestimation or underestimation depending on activity type and individual variation. Sleep staging algorithms classify sleep states (awake, light, deep, REM) using heart rate variability and movement patterns, though polysomnography validation studies show limited agreement for detailed sleep architecture. GPS-derived distance and pace metrics generally perform well for outdoor activities but face challenges in urban environments with signal occlusion. Device-specific validation is important, as algorithm quality varies significantly across manufacturers and models. Consumer awareness of accuracy limitations helps set appropriate expectations, particularly when users might make health decisions based on tracker data.',
      keyTerms: [
        { term: 'accelerometer-based activity recognition', definition: 'Using motion patterns to classify exercise types' },
        { term: 'optical heart rate accuracy', definition: 'Precision of light-based pulse measurement varying by conditions' },
        { term: 'energy expenditure algorithms', definition: 'Proprietary calculations estimating calories burned' },
        { term: 'sleep staging', definition: 'Classification of sleep into awake, light, deep, and REM phases' },
        { term: 'polysomnography validation', definition: 'Comparing device sleep data against gold-standard sleep studies' },
        { term: 'GPS accuracy', definition: 'Precision of location tracking affected by environment' },
        { term: 'algorithm variation', definition: 'Differences in accuracy across manufacturers and models' },
      ],
    },
    4: {
      level: 4,
      summary: 'Academic analysis of fitness trackers encompasses sensor validation methodologies, behavioral intervention efficacy, user engagement factors, and population health applications with attention to measurement quality and behavior change theory.',
      explanation: 'Scholarly examination of fitness trackers spans engineering, behavioral science, and public health perspectives. Validation research applies criterion measures (research-grade accelerometry, indirect calorimetry, polysomnography, ECG) to assess consumer device accuracy, with systematic reviews revealing heterogeneous results across metrics, devices, and populations. Step counting generally performs well (typically within 3-5% of criterion) while energy expenditure and sleep staging show larger, more variable errors. Behavioral intervention research examines fitness tracker efficacy for increasing physical activity, with meta-analyses suggesting modest positive effects that may not persist after intervention periods end; mediating factors include goal-setting features, social comparison, and feedback frequency. User engagement research identifies factors influencing sustained tracker use, including aesthetic appeal, ease of use, perceived usefulness, and social features, with abandonment commonly occurring within months of acquisition. Theoretical frameworks including Self-Determination Theory, Social Cognitive Theory, and the Transtheoretical Model inform understanding of how tracker features may support behavior change. Population health applications include fitness trackers as research instruments, workplace wellness program components, and public health surveillance tools, with methodological considerations around selection bias, measurement equivalence, and data privacy. Commercial business models involve data monetization and partnerships, raising ethical questions about consumer data use.',
      keyTerms: [
        { term: 'validation methodologies', definition: 'Research approaches assessing device accuracy' },
        { term: 'criterion measures', definition: 'Gold-standard references for evaluating fitness trackers' },
        { term: 'behavioral intervention', definition: 'Programs using trackers to promote physical activity' },
        { term: 'user engagement', definition: 'Factors influencing sustained tracker use over time' },
        { term: 'behavior change theory', definition: 'Frameworks explaining how trackers may support habit formation' },
        { term: 'population health', definition: 'Large-scale applications of fitness tracker data' },
        { term: 'data monetization', definition: 'Commercial use of aggregated user health information' },
        { term: 'measurement equivalence', definition: 'Comparability of data across different device types' },
      ],
    },
    5: {
      level: 5,
      summary: 'Clinical integration of fitness tracker data requires understanding of device accuracy limitations, appropriate patient selection, and evidence-based approaches to leveraging consumer devices for health behavior support.',
      explanation: 'Healthcare professionals increasingly encounter patients using fitness trackers and may consider recommending these devices for health behavior support. Clinical utility assessment should consider the evidence base for fitness trackers in relevant patient populations, recognizing that most research involves healthy adults with limited evidence for specific clinical populations. Device recommendation, when appropriate, should consider patient technological comfort, aesthetic preferences (affecting wear compliance), and specific health goals. Patient education should address accuracy limitations, helping patients interpret data appropriately without over-relying on potentially inaccurate metrics; step counts are generally reliable while calorie estimates should be interpreted cautiously. Goal-setting discussions can leverage tracker data to establish personalized, achievable activity targets aligned with clinical recommendations. Data review during clinical encounters can enhance discussions about physical activity patterns and progress, though direct data integration with EHRs remains limited. Clinicians should be alert to tracker-related anxiety where patients become distressed about daily variations or goal achievement. Population-specific considerations include potential for trackers to support cardiac rehabilitation, diabetes management, and weight loss interventions, though integration requires attention to workflow and patient support. Privacy counseling should address data sharing practices of tracker companies and connected applications.',
      keyTerms: [
        { term: 'device accuracy', definition: 'Understanding reliability limitations for clinical use' },
        { term: 'patient selection', definition: 'Identifying appropriate candidates for tracker recommendations' },
        { term: 'goal-setting', definition: 'Establishing personalized activity targets with patients' },
        { term: 'data interpretation', definition: 'Appropriately using tracker data in clinical discussions' },
        { term: 'clinical integration', definition: 'Incorporating tracker information into care workflows' },
        { term: 'tracker-related anxiety', definition: 'Distress from daily variations or goal achievement pressure' },
        { term: 'privacy counseling', definition: 'Advising patients on data sharing practices' },
        { term: 'patient education', definition: 'Setting realistic expectations about tracker capabilities' },
      ],
      clinicalNotes: 'When patients use fitness trackers, acknowledge their engagement with health data while helping set realistic expectations about accuracy, particularly for calorie and sleep metrics. Use step count trends rather than absolute numbers to discuss activity patterns. Consider recommending trackers for motivated patients seeking objective activity feedback, while recognizing that technology alone rarely sustains behavior change without supportive counseling and goal-setting. Address data privacy concerns and help patients understand how their information may be used.',
    },
  },
  media: [],
  citations: [
    {
      id: 'evenson-2015',
      type: 'article',
      title: 'Systematic review of the validity and reliability of consumer-wearable activity trackers',
      authors: ['Evenson KR', 'et al.'],
      source: 'Int J Behav Nutr Phys Act',
      page: '12:159',
    },
    {
      id: 'brickwood-2019',
      type: 'article',
      title: 'Consumer-Based Wearable Activity Trackers Increase Physical Activity Participation: Systematic Review and Meta-Analysis',
      authors: ['Brickwood KJ', 'et al.'],
      source: 'JMIR Mhealth Uhealth',
      page: '7(4):e11819',
    },
    {
      id: 'henriksen-2018',
      type: 'article',
      title: 'Using Fitness Trackers and Smartwatches to Measure Physical Activity in Research: Analysis of Consumer Wrist-Worn Wearables',
      authors: ['Henriksen A', 'et al.'],
      source: 'J Med Internet Res',
      page: '20(3):e110',
    },
    {
      id: 'patel-2015',
      type: 'article',
      title: 'Wearable Devices as Facilitators, Not Drivers, of Health Behavior Change',
      authors: ['Patel MS', 'et al.'],
      source: 'JAMA',
      page: '313(5):459-460',
    },
  ],
  crossReferences: [
    { targetId: 'activity-monitoring', targetType: 'concept', relationship: 'related', label: 'Activity Monitoring' },
    { targetId: 'health-data-privacy', targetType: 'concept', relationship: 'related', label: 'Health Data Privacy' },
    { targetId: 'data-security', targetType: 'concept', relationship: 'related', label: 'Data Security' },
    { targetId: 'continuous-glucose-monitors', targetType: 'concept', relationship: 'related', label: 'Continuous Glucose Monitors' },
  ],
  tags: {
    systems: ['digital-health'],
    topics: ['wearables', 'fitness', 'activity-tracking', 'consumer-health', 'physical-activity'],
    keywords: ['fitness trackers', 'step counting', 'heart rate', 'accelerometer', 'health behavior', 'wearable devices'],
  },
  createdAt: '2025-01-28T00:00:00.000Z',
  updatedAt: '2025-01-28T00:00:00.000Z',
  version: 1,
  status: 'published',
  contributors: ['Biological Self Content Team'],
};
