/**
 * First-Aid & Emergency Self-Care Database
 *
 * Comprehensive reference covering life-threatening emergencies, injuries,
 * environmental hazards, poisoning, medical emergencies, and common injuries.
 * DISCLAIMER: Educational purposes only — always call 911 for life-threatening emergencies.
 */

export interface FirstAidEntry {
  id: string;
  name: string;
  nameEs: string;
  category:
    | 'life-threatening'
    | 'injury'
    | 'environmental'
    | 'poisoning'
    | 'medical-emergency'
    | 'pediatric'
    | 'common-injury';
  urgency: 'call-911' | 'emergency-room' | 'urgent-care' | 'self-care';
  steps: string[];
  doNot: string[];
  whenToCall911: string;
  supplies: string[];
  prevention: string;
  patientTip: string;
}

// Compact helper
const fa = (
  id: string,
  name: string,
  nameEs: string,
  category: FirstAidEntry['category'],
  urgency: FirstAidEntry['urgency'],
  steps: string[],
  doNot: string[],
  whenToCall911: string,
  supplies: string[],
  prevention: string,
  patientTip: string,
): FirstAidEntry => ({ id, name, nameEs, category, urgency, steps, doNot, whenToCall911, supplies, prevention, patientTip });

// Database — 35 entries
export const FIRST_AID_ENTRIES: Record<string, FirstAidEntry> = {

  // === LIFE-THREATENING (6) ===

  'cpr-basics': fa('cpr-basics', 'CPR Basics (Adult)', 'RCP Básico (Adulto)', 'life-threatening', 'call-911',
    ['Call 911 immediately or have someone call while you begin CPR.',
     'Place the person on a firm, flat surface face-up.',
     'Put the heel of one hand on the center of the chest (between the nipples) and your other hand on top, interlocking fingers.',
     'Push hard and fast — at least 2 inches deep, 100–120 compressions per minute.',
     'Allow full chest recoil between compressions.',
     'If trained, give 2 rescue breaths after every 30 compressions; tilt head back, lift chin, pinch nose, and blow for 1 second each.',
     'Continue until EMS arrives or an AED is available.'],
    ['Do not stop compressions to check for pulse — let EMS do that.',
     'Do not compress too shallowly; effective CPR requires depth.',
     'Do not delay starting CPR to find an AED.'],
    'Call 911 any time a person is unresponsive and not breathing normally.',
    ['AED (if available)', 'CPR pocket mask', 'Barrier device'],
    'Learn hands-only CPR through a certified course; keep an AED accessible in public and workplace settings.',
    'Push hard, push fast, and do not stop. Even imperfect CPR is far better than no CPR at all.'),

  'choking-adult': fa('choking-adult', 'Choking (Adult)', 'Asfixia (Adulto)', 'life-threatening', 'call-911',
    ['Ask "Are you choking?" — if the person cannot speak, cough, or breathe, act immediately.',
     'Stand behind the person and wrap your arms around their waist.',
     'Make a fist with one hand and place the thumb side just above the navel, below the breastbone.',
     'Grasp the fist with your other hand and deliver quick, upward thrusts (Heimlich maneuver).',
     'Repeat thrusts until the object is expelled or the person becomes unresponsive.',
     'If the person becomes unresponsive, lower them to the ground and begin CPR; check the mouth for the object before each set of breaths.'],
    ['Do not perform abdominal thrusts on pregnant women or obese individuals — use chest thrusts instead.',
     'Do not slap the person on the back while they are upright (may lodge object further).',
     'Do not attempt a blind finger sweep.'],
    'Call 911 if the object is not dislodged after several attempts or if the person becomes unconscious.',
    ['None required — technique only'],
    'Cut food into small pieces, chew thoroughly, and avoid talking or laughing with food in your mouth.',
    'Stay calm and act fast. Five strong thrusts are often enough to clear an airway.'),

  'choking-infant': fa('choking-infant', 'Choking (Infant under 1 year)', 'Asfixia (Bebé menor de 1 año)', 'life-threatening', 'call-911',
    ['Confirm the infant cannot cough, cry, or breathe.',
     'Place the infant face-down on your forearm, supporting the head and jaw with your hand; rest your forearm on your thigh.',
     'Deliver 5 firm back blows between the shoulder blades using the heel of your hand.',
     'Turn the infant face-up, supporting the head; place 2 fingers on the center of the breastbone just below the nipple line.',
     'Give 5 chest thrusts, pressing about 1.5 inches deep.',
     'Alternate 5 back blows and 5 chest thrusts until the object is expelled or the infant becomes unresponsive.',
     'If unresponsive, begin infant CPR and call 911.'],
    ['Do not perform abdominal thrusts (Heimlich) on an infant.',
     'Do not do a blind finger sweep — only remove an object you can see.',
     'Do not hold the infant upside down by the ankles.'],
    'Call 911 immediately if the infant becomes unresponsive or turns blue.',
    ['None required — technique only'],
    'Keep small objects, grapes, hot dogs, coins, and batteries out of reach of infants.',
    'Support the infant securely and use firm, deliberate motions — hesitant blows are less effective.'),

  'severe-bleeding': fa('severe-bleeding', 'Severe Bleeding Control', 'Control de Hemorragia Severa', 'life-threatening', 'call-911',
    ['Call 911.',
     'Put on gloves if available.',
     'Apply direct, firm pressure with a clean cloth or gauze over the wound.',
     'If blood soaks through, add more material on top — do not remove the first layer.',
     'If bleeding is from a limb and cannot be controlled, apply a tourniquet 2–3 inches above the wound; note the time applied.',
     'Keep the person lying down, elevate the legs if possible (unless a spinal injury is suspected), and keep them warm.',
     'Do not remove any embedded objects — stabilize them in place.'],
    ['Do not remove the initial dressing once applied.',
     'Do not apply a tourniquet over a joint.',
     'Do not elevate a limb if a fracture is suspected.'],
    'Call 911 for any wound that spurts blood, will not stop bleeding after 10 minutes of pressure, or involves a large area of the body.',
    ['Sterile gauze/dressings', 'Disposable gloves', 'Commercial tourniquet or improvised band', 'Emergency blanket'],
    'Handle sharp tools carefully; wear protective gear during sports and hazardous activities.',
    'Pressure is your most powerful tool. Press firmly and do not peek — every time you lift the dressing, you disrupt clotting.'),

  'anaphylaxis': fa('anaphylaxis', 'Anaphylaxis / EpiPen Use', 'Anafilaxia / Uso de EpiPen', 'life-threatening', 'call-911',
    ['Call 911 immediately.',
     'Help the person use their epinephrine auto-injector (EpiPen): remove the safety cap, press the tip firmly into the outer thigh (through clothing if needed), and hold for 10 seconds.',
     'Lay the person down with legs elevated (unless they are vomiting or having difficulty breathing — then keep them sitting up).',
     'If symptoms do not improve in 5–15 minutes, administer a second dose if available.',
     'Monitor breathing and be prepared to perform CPR.',
     'Note the time of the injection for EMS.'],
    ['Do not leave the person alone.',
     'Do not have the person sit or stand if they feel faint.',
     'Do not delay using the EpiPen — antihistamines alone are not sufficient for anaphylaxis.'],
    'Call 911 for any signs of anaphylaxis: swelling of lips/tongue/throat, difficulty breathing, rapid pulse, dizziness, or widespread hives after exposure to a known allergen.',
    ['Epinephrine auto-injector (EpiPen)', 'Medical alert bracelet (for known allergies)'],
    'Identify and strictly avoid known allergens; always carry two epinephrine auto-injectors; educate family and coworkers on use.',
    'The EpiPen is a rescue device — using it is never an overreaction. After every use, go to the ER because symptoms can return.'),

  'stroke-recognition': fa('stroke-recognition', 'Stroke Recognition (BE-FAST)', 'Reconocimiento de ACV (BE-FAST)', 'life-threatening', 'call-911',
    ['Use BE-FAST to identify a stroke: B — Balance: sudden loss of balance or coordination. E — Eyes: sudden vision changes in one or both eyes. F — Face: ask the person to smile — does one side droop? A — Arms: ask them to raise both arms — does one drift down? S — Speech: ask them to repeat a simple sentence — is speech slurred? T — Time: note the time symptoms started and call 911 immediately.',
     'Have the person sit or lie down in a comfortable position.',
     'Do not give them food, water, or medication.',
     'Keep them calm and monitor until EMS arrives.',
     'If they become unresponsive and stop breathing, begin CPR.'],
    ['Do not drive the person to the hospital yourself — call 911 for faster access to stroke treatment.',
     'Do not give aspirin unless directed by a 911 dispatcher.',
     'Do not let the person fall asleep without EMS evaluation.'],
    'Call 911 the moment any BE-FAST sign is observed — treatment within the first hours is critical.',
    ['None required — recognition only'],
    'Control blood pressure, manage diabetes, exercise regularly, avoid smoking, and limit alcohol.',
    'Time is brain tissue. Note exactly when symptoms started — this information guides treatment decisions in the ER.'),

  // === INJURIES (8) ===

  'burns-thermal': fa('burns-thermal', 'Burns (Thermal)', 'Quemaduras (Térmicas)', 'injury', 'urgent-care',
    ['Remove the person from the heat source.',
     'Cool the burn under cool (not cold) running water for at least 10–20 minutes.',
     'Remove jewelry or tight clothing near the burn before swelling starts.',
     'Cover the burn loosely with a sterile, non-stick bandage or clean cloth.',
     'For minor burns, apply aloe vera or an over-the-counter burn ointment once cooled.',
     'Take an over-the-counter pain reliever if needed.'],
    ['Do not apply ice, butter, toothpaste, or grease to the burn.',
     'Do not pop blisters — they protect against infection.',
     'Do not use adhesive bandages directly on the burn.'],
    'Call 911 for burns that cover a large area, affect the face/hands/feet/genitals/joints, are deep (white or charred), or encircle a limb.',
    ['Cool running water', 'Non-stick sterile dressing', 'Aloe vera gel', 'Pain relievers'],
    'Use oven mitts, keep hot liquids away from children, and install smoke detectors.',
    'Cool water is the best first treatment — run the burn under a gentle stream for a full 20 minutes, even if it feels better sooner.'),

  'burns-chemical': fa('burns-chemical', 'Burns (Chemical)', 'Quemaduras (Químicas)', 'injury', 'emergency-room',
    ['Remove contaminated clothing carefully, avoiding spreading the chemical.',
     'Brush off any dry chemical before flushing.',
     'Flush the area with large amounts of cool running water for at least 20 minutes.',
     'If the chemical contacted the eyes, flush eyes with clean water for at least 20 minutes, blinking frequently.',
     'Cover the burn loosely with a dry, sterile bandage.',
     'Identify the chemical (keep the container) and bring it to the ER.'],
    ['Do not try to neutralize a chemical burn with another substance.',
     'Do not apply ointments or creams before medical evaluation.',
     'Do not rub the affected area.'],
    'Call 911 if the person shows signs of shock, the chemical contacted the eyes, or the burn area is large.',
    ['Running water source', 'Sterile dressings', 'Eye-wash station (workplace)'],
    'Wear protective gloves and goggles when handling chemicals; store chemicals properly and label containers.',
    'When in doubt, flush with water — volume and duration of rinsing matter more than anything else.'),

  'fractures': fa('fractures', 'Fractures / Splinting', 'Fracturas / Entablillado', 'injury', 'emergency-room',
    ['Call for medical help.',
     'Keep the injured area still — do not try to realign the bone.',
     'Apply a splint to immobilize the joint above and below the fracture using rigid material (board, rolled magazine) and padding.',
     'Secure the splint with bandages or cloth strips — firm but not tight enough to cut off circulation.',
     'Apply ice wrapped in cloth to reduce swelling (20 minutes on, 20 minutes off).',
     'Check fingers or toes beyond the splint for numbness, tingling, or color change.',
     'Elevate the injured limb if possible.'],
    ['Do not move the person if a spinal injury is suspected.',
     'Do not try to straighten a deformed limb.',
     'Do not tie the splint so tightly it restricts blood flow.'],
    'Call 911 if the bone is protruding, there is heavy bleeding, the person cannot move, or you suspect a spinal/hip/pelvis fracture.',
    ['Rigid splint material', 'Padding (towels, clothing)', 'Bandages or cloth strips', 'Ice pack'],
    'Wear appropriate footwear, use handrails, strengthen bones with weight-bearing exercise and adequate calcium/vitamin D.',
    'A good splint keeps the joints above and below the break from moving. Pad generously for comfort.'),

  'sprains-strains': fa('sprains-strains', 'Sprains & Strains', 'Esguinces y Distensiones', 'injury', 'self-care',
    ['Rest the injured area — stop the activity that caused the injury.',
     'Ice the area for 20 minutes every 2–3 hours for the first 48 hours.',
     'Compress with an elastic bandage — snug but not tight.',
     'Elevate the limb above heart level when possible.',
     'Take over-the-counter anti-inflammatory medication (ibuprofen) for pain and swelling.',
     'Begin gentle range-of-motion exercises after 48 hours if tolerated.'],
    ['Do not apply heat in the first 48 hours — it increases swelling.',
     'Do not wrap the bandage too tightly.',
     'Do not continue physical activity through significant pain.'],
    'Seek emergency care if you cannot bear weight, the joint appears deformed, or there is severe swelling or numbness.',
    ['Ice pack or frozen vegetables', 'Elastic bandage', 'Anti-inflammatory medication', 'Pillow for elevation'],
    'Warm up before exercise, wear supportive shoes, and strengthen muscles around joints.',
    'Remember RICE: Rest, Ice, Compression, Elevation. Most sprains improve significantly within 72 hours.'),

  'head-injury': fa('head-injury', 'Head Injury / Concussion', 'Lesión de Cabeza / Conmoción', 'injury', 'emergency-room',
    ['Keep the person still and calm.',
     'Apply gentle pressure with a clean cloth to any bleeding scalp wound.',
     'Monitor for signs of concussion: headache, dizziness, confusion, nausea, blurred vision, or memory problems.',
     'Check pupils — unequal pupil sizes may indicate a serious brain injury.',
     'Keep the person awake and talking for the first few hours if possible.',
     'Apply an ice pack wrapped in cloth to any bumps.'],
    ['Do not move someone with a possible spinal injury.',
     'Do not give aspirin (increases bleeding risk).',
     'Do not let the person return to sports or strenuous activity until cleared by a doctor.'],
    'Call 911 if the person loses consciousness, has repeated vomiting, seizures, worsening headache, clear fluid from the nose or ears, or unequal pupils.',
    ['Clean cloth or gauze', 'Ice pack', 'Flashlight (to check pupils)'],
    'Wear helmets during biking, skiing, and contact sports; use seat belts; prevent falls in the elderly.',
    'After any head impact, watch for worsening symptoms over 24–48 hours. When in doubt, get checked out.'),

  'eye-injury': fa('eye-injury', 'Eye Injury', 'Lesión Ocular', 'injury', 'emergency-room',
    ['For chemicals in the eye: flush with clean water for 15–20 minutes, holding the eyelid open.',
     'For a foreign object: do not rub the eye; try blinking or flushing with saline or clean water.',
     'For a blow to the eye: apply a cold compress gently without pressure.',
     'For a puncture or embedded object: do not remove it; cover both eyes loosely with a paper cup or shield and seek emergency care.',
     'For a cut to the eye or eyelid: cover lightly with a sterile pad and go to the ER immediately.'],
    ['Do not rub or press on the injured eye.',
     'Do not attempt to remove an embedded object.',
     'Do not apply medication or ointment without medical direction.'],
    'Call 911 for any puncture wound, embedded object, sudden vision loss, or chemical exposure that does not improve with flushing.',
    ['Eye-wash solution or saline', 'Sterile eye pads', 'Paper cup (for shielding)', 'Tape'],
    'Wear safety glasses for power tools and yard work; wear UV-protective sunglasses outdoors.',
    'Cover both eyes when one is injured — this reduces eye movement. Seek professional care for anything beyond a minor irritant.'),

  'nosebleed': fa('nosebleed', 'Nosebleed', 'Sangrado Nasal', 'injury', 'self-care',
    ['Sit upright and lean slightly forward.',
     'Pinch the soft part of the nose (just below the bony bridge) firmly with thumb and index finger.',
     'Hold continuous pressure for 10–15 minutes without checking.',
     'Breathe through the mouth.',
     'Apply a cold compress to the bridge of the nose.',
     'After bleeding stops, avoid blowing the nose, bending over, or straining for several hours.'],
    ['Do not tilt the head back — blood may drain into the throat and cause nausea.',
     'Do not pack the nose with tissue or cotton.',
     'Do not pick or blow the nose for at least 12 hours after it stops.'],
    'Seek emergency care if bleeding lasts more than 20 minutes despite pressure, follows a head injury, or the person is on blood thinners and cannot stop the bleed.',
    ['Cold compress', 'Tissues (for external use only)'],
    'Use a humidifier in dry environments, apply saline nasal spray, and avoid picking the nose.',
    'Pinch and hold — most nosebleeds stop within 10–15 minutes of steady, uninterrupted pressure.'),

  'wound-care': fa('wound-care', 'Wound Care / When Stitches Are Needed', 'Cuidado de Heridas / Cuándo se Necesitan Suturas', 'injury', 'urgent-care',
    ['Wash your hands or put on gloves.',
     'Apply gentle pressure with a clean cloth to stop bleeding.',
     'Clean the wound gently under running water; remove debris with tweezers cleaned with alcohol.',
     'Apply a thin layer of antibiotic ointment.',
     'Cover with a sterile bandage or adhesive strip.',
     'Change the bandage daily and whenever it gets wet or dirty.',
     'Watch for signs of infection: increasing redness, swelling, warmth, pus, or red streaks.'],
    ['Do not use hydrogen peroxide or rubbing alcohol directly in a deep wound — they damage tissue.',
     'Do not close a dirty or infected wound with butterfly strips.',
     'Do not ignore signs of infection.'],
    'Seek immediate care if the wound is deep (more than 1/4 inch), gaping, on the face, or caused by a rusty/dirty object; also if bleeding does not stop after 10 minutes.',
    ['Sterile gauze and bandages', 'Adhesive strips/butterfly closures', 'Antibiotic ointment', 'Disposable gloves', 'Tweezers'],
    'Keep sharp objects stored safely, wear gloves for yard work, and keep tetanus vaccination up to date.',
    'A wound likely needs stitches if you can see fat or muscle, edges do not stay together, or it is longer than half an inch on the face.'),

  // === ENVIRONMENTAL (6) ===

  'heat-exhaustion': fa('heat-exhaustion', 'Heat Exhaustion / Heat Stroke', 'Agotamiento por Calor / Golpe de Calor', 'environmental', 'call-911',
    ['Move the person to a cool, shaded area or air-conditioned space.',
     'Have them lie down and elevate the legs.',
     'Remove excess clothing.',
     'Cool rapidly: apply cold, wet cloths to the neck, armpits, and groin; fan the person; or immerse in cool water if possible.',
     'If the person is alert and not vomiting, give small sips of cool water or sports drink.',
     'If body temperature exceeds 104°F (40°C), the person is confused, or loses consciousness, call 911 — this is heat stroke.'],
    ['Do not give fluids to someone who is vomiting or unconscious.',
     'Do not use ice-cold water for immersion if the person is elderly (can cause shock).',
     'Do not ignore confusion or altered mental status — this signals heat stroke.'],
    'Call 911 for heat stroke: body temperature above 104°F, confusion, loss of consciousness, seizures, or hot/dry skin.',
    ['Cold water/ice packs', 'Spray bottle', 'Fan', 'Electrolyte drinks', 'Thermometer'],
    'Stay hydrated, avoid strenuous activity in extreme heat, wear light clothing, and take frequent breaks in shade.',
    'Heat exhaustion can progress to heat stroke quickly. Cooling the body is the top priority — every minute counts.'),

  'hypothermia': fa('hypothermia', 'Hypothermia', 'Hipotermia', 'environmental', 'call-911',
    ['Call 911.',
     'Move the person to a warm, dry area.',
     'Remove any wet clothing and replace with dry layers or blankets.',
     'Warm the person gradually: cover with blankets, apply warm compresses to the neck, armpits, and groin (not the extremities).',
     'If the person is alert, give warm (not hot), sweet beverages.',
     'Handle the person gently — rough movement can trigger cardiac arrest in severe hypothermia.',
     'Monitor breathing and be prepared to start CPR.'],
    ['Do not apply direct heat (heating pad, hot water) to the skin — it can cause burns or cardiac issues.',
     'Do not warm the arms and legs first — this drives cold blood to the heart.',
     'Do not give alcohol.'],
    'Call 911 for shivering that stops (sign of severe hypothermia), confusion, slurred speech, drowsiness, or loss of consciousness.',
    ['Dry blankets/sleeping bag', 'Warm compresses', 'Warm beverages', 'Dry clothing'],
    'Dress in layers, stay dry, limit exposure in cold weather, and always tell someone your plans before outdoor activities.',
    'Warm the core first. Handle the person as gently as possible — a cold heart is very sensitive to disturbance.'),

  'frostbite': fa('frostbite', 'Frostbite', 'Congelación', 'environmental', 'emergency-room',
    ['Move the person to a warm area.',
     'Remove wet clothing and jewelry from the affected area.',
     'Immerse the frostbitten area in warm (not hot) water at 98–105°F (37–40°C) for 20–30 minutes.',
     'Do not rub the area — this causes further tissue damage.',
     'Place dry, sterile gauze between frostbitten fingers or toes.',
     'Elevate the affected area to reduce swelling.',
     'Give ibuprofen for pain and to reduce inflammation.'],
    ['Do not rub or massage the frostbitten area.',
     'Do not use dry heat (fire, heating pad) — the area is numb and burns easily.',
     'Do not rewarm if there is a chance of refreezing — refreezing causes worse damage.'],
    'Seek emergency care for any frostbite that involves blistering, skin that remains numb after warming, or large affected areas.',
    ['Warm water basin', 'Sterile gauze', 'Ibuprofen', 'Dry blankets'],
    'Wear insulated, waterproof gloves and boots; cover all exposed skin in extreme cold; avoid alcohol before cold exposure.',
    'Rewarming will be painful — this is actually a good sign. Numbness that persists after warming needs emergency attention.'),

  'lightning-strike': fa('lightning-strike', 'Lightning Strike', 'Descarga de Rayo', 'environmental', 'call-911',
    ['Call 911 immediately.',
     'It is safe to touch a lightning-strike victim — they do not carry an electrical charge.',
     'Check for breathing and pulse; begin CPR if needed.',
     'Look for burns, especially at entry and exit points (often hands and feet).',
     'Treat any burns with cool water and sterile dressings.',
     'Keep the person still — spinal injury is possible from the fall or muscle contractions.',
     'Monitor for cardiac arrest, which can occur even after the person initially appears stable.'],
    ['Do not delay touching the victim out of fear of being shocked.',
     'Do not move them if a spinal injury is suspected.',
     'Do not assume the person is fine if they are conscious — delayed cardiac arrest is possible.'],
    'Always call 911 after a lightning strike, even if the person seems okay.',
    ['AED (if available)', 'Sterile burn dressings', 'CPR pocket mask'],
    'Seek shelter during thunderstorms; avoid open fields, isolated trees, and bodies of water; follow the 30-30 rule.',
    'Lightning victims do not carry a charge. Check for a pulse first — cardiac arrest is the main cause of death from lightning.'),

  'drowning-rescue': fa('drowning-rescue', 'Drowning Rescue', 'Rescate por Ahogamiento', 'environmental', 'call-911',
    ['Call 911.',
     'Reach, throw, row — do not swim to the victim unless you are a trained lifeguard.',
     'Extend a pole, rope, or towel from shore; throw a flotation device.',
     'Once the person is out of the water, check for breathing.',
     'If not breathing, begin CPR immediately — start with 5 rescue breaths, then 30 compressions to 2 breaths.',
     'If they vomit, turn them on their side to clear the airway.',
     'Even if the person recovers quickly, they must be evaluated at a hospital (secondary drowning can occur hours later).'],
    ['Do not jump in unless you are trained — drowning victims can pull rescuers under.',
     'Do not assume the person is fine after coughing up water.',
     'Do not skip the hospital visit — pulmonary edema can develop hours later.'],
    'Call 911 for any submersion event, even if the person appears to recover.',
    ['Flotation device', 'Rope or reaching pole', 'CPR pocket mask'],
    'Supervise children constantly near water, fence pools, learn to swim, and never swim alone.',
    'Remember: Reach, Throw, Row, then Go. Your safety comes first — a second victim makes rescue harder, not easier.'),

  'insect-stings': fa('insect-stings', 'Insect Stings & Bites', 'Picaduras de Insectos', 'environmental', 'self-care',
    ['Remove the stinger by scraping it off with a flat edge (credit card); do not squeeze with tweezers.',
     'Wash the area with soap and water.',
     'Apply a cold pack for 10–15 minutes to reduce swelling.',
     'Apply hydrocortisone cream or calamine lotion to relieve itching.',
     'Take an oral antihistamine (diphenhydramine/cetirizine) if swelling or itching is significant.',
     'Monitor for signs of allergic reaction for at least 30 minutes.'],
    ['Do not squeeze the stinger — it can inject more venom.',
     'Do not scratch the bite — increases infection risk.',
     'Do not ignore spreading redness or swelling beyond the sting site.'],
    'Call 911 if there is difficulty breathing, swelling of the face/lips/throat, dizziness, or rapid pulse — these indicate anaphylaxis.',
    ['Cold pack', 'Hydrocortisone cream', 'Oral antihistamine', 'Credit card or flat edge (for stinger removal)'],
    'Wear protective clothing outdoors, avoid perfumed products in insect-heavy areas, and check for ticks after hikes.',
    'Most stings cause only local reactions. Watch for any spreading or systemic symptoms within the first 30 minutes.'),

  // === POISONING (4) ===

  'ingested-poison': fa('ingested-poison', 'Ingested Poison', 'Envenenamiento por Ingestión', 'poisoning', 'call-911',
    ['Call Poison Control (1-800-222-1222 in the US) or 911.',
     'Try to identify the substance, amount, and time of ingestion.',
     'Do not induce vomiting unless specifically directed by Poison Control.',
     'If the person is conscious and Poison Control advises, give small sips of water or milk.',
     'Save the container, label, or a sample of the substance.',
     'If the person is unconscious, place them in the recovery position (on their side) and monitor breathing.'],
    ['Do not induce vomiting — caustic substances cause more damage coming back up.',
     'Do not give activated charcoal unless directed by a professional.',
     'Do not give anything by mouth to an unconscious person.'],
    'Call 911 if the person is unconscious, having seizures, difficulty breathing, or you suspect ingestion of a dangerous substance.',
    ['Poison Control number stored in phone', 'Disposable gloves'],
    'Store chemicals and medications out of children\'s reach, use child-proof caps, and label all containers clearly.',
    'Having the container or label ready when you call Poison Control saves critical time — they will guide you step by step.'),

  'carbon-monoxide': fa('carbon-monoxide', 'Carbon Monoxide Poisoning', 'Envenenamiento por Monóxido de Carbono', 'poisoning', 'call-911',
    ['Get everyone out of the building immediately into fresh air.',
     'Call 911.',
     'Do not re-enter the building.',
     'If someone is unconscious, move them outside (only if safe) and check breathing; begin CPR if needed.',
     'Keep the person warm and calm while waiting for EMS.',
     'Tell EMS you suspect carbon monoxide poisoning.'],
    ['Do not go back inside to retrieve belongings.',
     'Do not assume symptoms will pass — CO poisoning can be fatal.',
     'Do not start any vehicles or gas-powered equipment in enclosed spaces.'],
    'Call 911 if anyone experiences headache, dizziness, nausea, confusion, or loss of consciousness and CO poisoning is suspected.',
    ['Carbon monoxide detector (prevention)', 'Fresh air access'],
    'Install CO detectors on every level of your home, service fuel-burning appliances annually, and never run generators indoors.',
    'CO is odorless and invisible. If your detector goes off or multiple people in the home feel ill simultaneously, get out first and call from outside.'),

  'snake-bite': fa('snake-bite', 'Snake Bite', 'Mordedura de Serpiente', 'poisoning', 'call-911',
    ['Move away from the snake — do not try to capture or kill it.',
     'Call 911.',
     'Keep the person calm and as still as possible to slow venom spread.',
     'Remove jewelry and tight clothing near the bite before swelling begins.',
     'Keep the bitten limb at or below heart level.',
     'Clean the wound gently with soap and water.',
     'Note the time of the bite and the snake\'s appearance if observed safely.'],
    ['Do not apply a tourniquet.',
     'Do not cut the wound or try to suck out the venom.',
     'Do not apply ice or immerse in cold water.',
     'Do not give the person alcohol or aspirin.'],
    'Call 911 for all snake bites if the snake species is unknown or venomous — antivenom is time-sensitive.',
    ['Soap and water', 'Bandage', 'Marker (to trace swelling over time)'],
    'Wear boots and long pants in snake territory, watch where you step and reach, and do not handle snakes.',
    'Try to remember the snake\'s color and pattern — a photo from a safe distance helps the ER determine if antivenom is needed.'),

  'jellyfish-sting': fa('jellyfish-sting', 'Jellyfish Sting', 'Picadura de Medusa', 'poisoning', 'urgent-care',
    ['Get out of the water.',
     'Rinse the area with vinegar for at least 30 seconds to neutralize remaining nematocysts.',
     'Remove tentacles with tweezers or by scraping with a credit card — do not touch with bare hands.',
     'Immerse the area in hot water (110–113°F / 43–45°C) for 20–45 minutes to reduce pain.',
     'Take over-the-counter pain medication as needed.',
     'Apply hydrocortisone cream to reduce itching after initial treatment.'],
    ['Do not rinse with fresh water — it can trigger remaining stingers.',
     'Do not urinate on the sting (this is a myth and can worsen pain).',
     'Do not rub the area or apply ice directly.'],
    'Call 911 for box jellyfish stings, difficulty breathing, chest pain, or widespread allergic reaction.',
    ['Vinegar', 'Tweezers', 'Hot water source', 'Hydrocortisone cream', 'Pain relievers'],
    'Wear protective swimwear in jellyfish-prone waters, heed beach warnings, and shuffle feet when wading.',
    'Vinegar first, then hot water. Heat deactivates the venom proteins and provides the best pain relief.'),

  // === MEDICAL EMERGENCIES (6) ===

  'seizure': fa('seizure', 'Seizure', 'Convulsión', 'medical-emergency', 'call-911',
    ['Clear the area of hard or sharp objects.',
     'Do not restrain the person or put anything in their mouth.',
     'Gently guide them to the floor if they are standing.',
     'Turn them on their side (recovery position) to keep the airway clear.',
     'Place something soft under the head.',
     'Time the seizure.',
     'Stay with the person until they are fully aware; speak calmly and reassure them.'],
    ['Do not hold the person down.',
     'Do not place anything in their mouth — they cannot swallow their tongue.',
     'Do not give food or water until fully alert.'],
    'Call 911 if the seizure lasts longer than 5 minutes, the person does not regain consciousness, a second seizure follows quickly, the person is injured, or it is their first seizure.',
    ['Soft padding for head', 'Timer/watch'],
    'For those with epilepsy: take medications consistently, get adequate sleep, avoid known triggers, and wear a medical ID.',
    'Most seizures end on their own within 1–2 minutes. Your job is to protect the person from injury and time the episode.'),

  'diabetic-emergency': fa('diabetic-emergency', 'Diabetic Emergency (Low/High Blood Sugar)', 'Emergencia Diabética (Azúcar Alta/Baja)', 'medical-emergency', 'call-911',
    ['If the person is conscious and able to swallow, give them fast-acting sugar: fruit juice, regular soda, glucose tablets, or candy.',
     'Have them sit down and rest.',
     'Recheck in 15 minutes — if no improvement, give more sugar.',
     'If the person is unconscious, place them in the recovery position and call 911; do not give anything by mouth.',
     'If they have a glucagon emergency kit, administer it as directed.',
     'Check for a medical ID bracelet for additional information.'],
    ['Do not give insulin if you suspect low blood sugar.',
     'Do not give food or drink to an unconscious person.',
     'Do not delay calling 911 if the person does not improve after sugar.'],
    'Call 911 if the person is unconscious, having seizures, confused and unable to swallow, or does not improve after receiving sugar.',
    ['Glucose tablets or gel', 'Fruit juice', 'Glucagon kit (for known diabetics)', 'Blood glucose meter'],
    'People with diabetes should eat regular meals, monitor blood sugar, carry glucose tablets, and wear medical ID.',
    'When in doubt, give sugar. If the problem is low blood sugar, it will help immediately. If it is high blood sugar, a small amount will not significantly worsen the situation.'),

  'asthma-attack': fa('asthma-attack', 'Asthma Attack', 'Ataque de Asma', 'medical-emergency', 'emergency-room',
    ['Help the person sit upright — do not let them lie down.',
     'Help them use their rescue inhaler (usually albuterol): shake it, attach spacer if available, exhale fully, press the canister while inhaling slowly, hold breath 10 seconds.',
     'Give 2–4 puffs, waiting 1 minute between puffs.',
     'If no improvement after 4 puffs, repeat every 20 minutes up to 3 times.',
     'Keep the person calm and encourage slow, steady breathing.',
     'If symptoms do not improve or worsen, call 911.'],
    ['Do not have the person lie down.',
     'Do not let them try to "push through" worsening symptoms.',
     'Do not delay calling for help if the inhaler is not working.'],
    'Call 911 if lips or fingernails turn blue, the person cannot speak in full sentences, the inhaler provides no relief, or the person is struggling to breathe.',
    ['Rescue inhaler (albuterol/salbutamol)', 'Spacer device', 'Peak flow meter'],
    'Identify and avoid triggers, take controller medications as prescribed, keep rescue inhalers accessible, and have an asthma action plan.',
    'Sitting upright opens the airways. If the rescue inhaler is not helping after 3 rounds, this is a medical emergency — do not wait.'),

  'heart-attack': fa('heart-attack', 'Heart Attack Recognition', 'Reconocimiento de Infarto', 'medical-emergency', 'call-911',
    ['Call 911 immediately — do not drive to the hospital.',
     'Have the person chew one regular (325 mg) or four baby (81 mg) aspirin, unless allergic.',
     'Help the person sit in a comfortable position, usually semi-upright with knees bent.',
     'Loosen any tight clothing.',
     'If the person takes nitroglycerin, help them take it as prescribed.',
     'Stay with them, keep them calm, and monitor breathing.',
     'Be ready to perform CPR if they become unresponsive.'],
    ['Do not let the person convince you to "wait and see."',
     'Do not give aspirin if the person is allergic or has been told not to take it.',
     'Do not ignore atypical symptoms — women often present with jaw pain, nausea, back pain, or fatigue rather than chest pain.'],
    'Call 911 for chest pressure/pain lasting more than a few minutes, pain radiating to the arm/jaw/back, shortness of breath, cold sweat, nausea, or lightheadedness.',
    ['Aspirin (non-coated)', 'Nitroglycerin (if prescribed)', 'Phone to call 911'],
    'Exercise regularly, maintain a healthy diet, manage cholesterol/blood pressure, do not smoke, and manage stress.',
    'Time is muscle — every minute without blood flow causes heart tissue to die. Call 911 first, then give aspirin.'),

  'fainting': fa('fainting', 'Fainting (Syncope)', 'Desmayo (Síncope)', 'medical-emergency', 'urgent-care',
    ['If the person feels faint, have them lie down or sit with their head between their knees.',
     'If they have already fainted, lay them on their back and elevate the legs 12 inches.',
     'Loosen any restrictive clothing (tie, belt, collar).',
     'Check for breathing and pulse.',
     'Do not splash water on their face; instead, lightly tap their shoulders and call their name.',
     'When they recover, have them remain lying down for 10 minutes before slowly sitting up.',
     'Offer water once they are fully alert.'],
    ['Do not try to give food or water to someone who is not fully conscious.',
     'Do not sit them up immediately after they regain consciousness.',
     'Do not slap or shake the person.'],
    'Call 911 if the person does not regain consciousness within 1 minute, has chest pain, difficulty breathing, had a seizure while unconscious, or is injured from the fall.',
    ['Pillow or blanket for legs', 'Water'],
    'Stay hydrated, avoid standing for long periods, rise slowly from sitting or lying, and eat regular meals.',
    'Most fainting episodes resolve quickly. Keep the person flat with legs elevated until color returns and they feel steady.'),

  'allergic-reaction-mild': fa('allergic-reaction-mild', 'Allergic Reaction (Mild)', 'Reacción Alérgica (Leve)', 'medical-emergency', 'self-care',
    ['Identify and remove the allergen if possible (stop eating the food, move away from the substance).',
     'Take an oral antihistamine (diphenhydramine 25–50 mg or cetirizine 10 mg).',
     'For skin reactions, apply hydrocortisone cream or calamine lotion.',
     'Apply a cool compress to itchy or swollen areas.',
     'Monitor symptoms for 1–2 hours for any worsening.',
     'If hives are widespread but breathing is normal, an ER visit is recommended to rule out progression.'],
    ['Do not ignore symptoms that are worsening.',
     'Do not assume a mild reaction cannot become severe.',
     'Do not take sedating antihistamines before driving.'],
    'Call 911 if you develop any signs of anaphylaxis: throat tightness, difficulty breathing, swelling of the tongue/lips, dizziness, or rapid pulse.',
    ['Oral antihistamines', 'Hydrocortisone cream', 'Calamine lotion', 'Cold compress'],
    'Identify allergens through testing, read food labels carefully, and inform restaurants about allergies.',
    'A mild reaction today does not guarantee a mild reaction next time. Discuss an allergy action plan with your doctor.'),

  // === COMMON INJURIES (5) ===

  'minor-cuts': fa('minor-cuts', 'Minor Cuts & Scrapes', 'Cortes y Raspaduras Menores', 'common-injury', 'self-care',
    ['Wash your hands before treating the wound.',
     'Stop bleeding by applying gentle pressure with a clean cloth for a few minutes.',
     'Rinse the wound under clean running water to remove dirt and debris.',
     'Apply a thin layer of antibiotic ointment (e.g., Neosporin).',
     'Cover with an adhesive bandage or sterile gauze.',
     'Change the bandage daily or whenever it gets dirty or wet.'],
    ['Do not use hydrogen peroxide or iodine directly in the wound — they delay healing.',
     'Do not leave the wound uncovered if it is in an area prone to dirt or friction.',
     'Do not pick at scabs.'],
    'Seek care if the cut is deep, will not stop bleeding, shows signs of infection (redness, warmth, pus), or was caused by a dirty or rusty object.',
    ['Adhesive bandages', 'Sterile gauze', 'Antibiotic ointment', 'Medical tape'],
    'Wear gloves when handling sharp objects, keep knives sharp (dull blades slip more), and supervise children with scissors.',
    'Clean water is the best wound cleanser. Keep the wound moist with ointment and covered — wounds heal faster in a moist environment.'),

  'blisters': fa('blisters', 'Blisters', 'Ampollas', 'common-injury', 'self-care',
    ['Clean the blister and surrounding skin with soap and water.',
     'Leave the blister intact if possible — it is a natural bandage.',
     'Cover it with a bandage or moleskin donut (cut a hole for the blister).',
     'If the blister is large and painful: sterilize a needle with rubbing alcohol, puncture the edge of the blister, let fluid drain, but leave the skin flap in place.',
     'Apply antibiotic ointment and cover with a bandage.',
     'Change the dressing daily and watch for signs of infection.'],
    ['Do not tear off the blister roof — it protects the new skin underneath.',
     'Do not pop blisters caused by burns or unknown causes.',
     'Do not use an unsterilized instrument to drain.'],
    'Seek medical care if the blister is filled with blood or pus, shows signs of infection, or is caused by a burn or allergic reaction.',
    ['Moleskin', 'Adhesive bandages', 'Antibiotic ointment', 'Sterile needle', 'Rubbing alcohol'],
    'Wear well-fitting shoes, use moisture-wicking socks, and apply petroleum jelly to friction-prone areas before activity.',
    'If you must pop a blister, keep the skin roof on — it protects the tender new skin beneath while it heals.'),

  'splinter-removal': fa('splinter-removal', 'Splinter Removal', 'Remoción de Astilla', 'common-injury', 'self-care',
    ['Wash your hands and the area around the splinter with soap and water.',
     'Sterilize tweezers with rubbing alcohol.',
     'If the end of the splinter is visible, grasp it firmly with tweezers and pull out at the same angle it entered.',
     'If the splinter is under the skin, sterilize a needle with rubbing alcohol and gently lift the skin over the splinter to expose the end, then use tweezers.',
     'After removal, wash the area again, apply antibiotic ointment, and cover with a bandage.',
     'Check your tetanus vaccination status — if it has been more than 5 years, consult your doctor.'],
    ['Do not squeeze the skin to push the splinter out — this can break it.',
     'Do not dig aggressively with a needle.',
     'Do not ignore a splinter that is deep, large, or in a sensitive area (under a fingernail, near the eye).'],
    'Seek medical care if the splinter is deeply embedded, is glass or metal, is under a fingernail, or the area becomes infected.',
    ['Fine-tip tweezers', 'Sewing needle', 'Rubbing alcohol', 'Magnifying glass', 'Antibiotic ointment', 'Adhesive bandage'],
    'Wear gloves when handling rough wood, wear shoes outdoors, and sand or seal rough wooden surfaces.',
    'Good lighting and a magnifying glass make all the difference. Pull at the same angle the splinter went in.'),

  'tooth-knocked-out': fa('tooth-knocked-out', 'Tooth Knocked Out', 'Diente Caído por Golpe', 'common-injury', 'emergency-room',
    ['Find the tooth and pick it up by the crown (white part) — never touch the root.',
     'If dirty, gently rinse with milk or saline (not water or soap) for a few seconds.',
     'Try to reinsert the tooth into the socket: push it in gently and bite down on a cloth to hold it.',
     'If you cannot reinsert it, place the tooth in a container of milk, saline, or the person\'s saliva.',
     'Get to a dentist or ER within 30 minutes — the sooner the better.',
     'Control bleeding from the socket by biting on a gauze pad.'],
    ['Do not touch the root of the tooth.',
     'Do not scrub or clean the tooth with soap or chemicals.',
     'Do not let the tooth dry out.',
     'Do not store it in plain water for more than a few minutes.'],
    'Time is critical — go to the ER or emergency dentist immediately. Call 911 only if there are other injuries (jaw fracture, loss of consciousness).',
    ['Milk (for tooth storage)', 'Gauze pads', 'Small container with lid'],
    'Wear a mouthguard during contact sports, avoid using teeth to open packages, and address loose teeth promptly.',
    'Milk is the best storage medium for a knocked-out tooth. Time is everything — reimplantation within 30 minutes gives the best chance of saving the tooth.'),

  'muscle-cramp': fa('muscle-cramp', 'Muscle Cramp', 'Calambre Muscular', 'common-injury', 'self-care',
    ['Stop the activity that caused the cramp.',
     'Gently stretch the cramping muscle: for a calf cramp, straighten the leg and pull the toes toward you.',
     'Massage the muscle firmly with your hands.',
     'Apply a warm towel or heating pad to relax the muscle.',
     'Drink water or an electrolyte beverage.',
     'Walk gently once the cramp eases to prevent recurrence.'],
    ['Do not forcefully stretch or jolt the muscle.',
     'Do not ignore frequent cramps — they may signal dehydration or an electrolyte imbalance.',
     'Do not apply ice during the acute cramp — heat works better.'],
    'Seek medical attention if cramps are severe, happen frequently, do not improve with self-care, or are accompanied by muscle weakness or swelling.',
    ['Water/electrolyte drink', 'Heating pad or warm towel'],
    'Stay hydrated before, during, and after exercise; warm up properly; eat potassium- and magnesium-rich foods (bananas, leafy greens).',
    'Stretch gently and hold — do not bounce. Most cramps release within 1–2 minutes of steady, gentle stretching.'),
};
