/**
 * Transplant Medicine Database
 *
 * Comprehensive reference covering organ transplantation, bone marrow transplant,
 * immunosuppression, rejection, donation, post-transplant care, evaluation, and complications.
 * Educational content for the SOMA medical education platform.
 */

export type TransplantCategory =
  | 'organ-transplant'
  | 'bone-marrow'
  | 'immunosuppression'
  | 'rejection'
  | 'donation'
  | 'post-transplant'
  | 'evaluation'
  | 'complication';

export interface TransplantMedicineEntry {
  id: string;
  name: string;
  nameEs: string;
  category: TransplantCategory;
  description: string;
  indications: string[];
  procedure: string[];
  complications: string[];
  monitoring: string[];
  patientExplanation: string;
}

// Compact helper
const tm = (
  id: string,
  name: string,
  nameEs: string,
  category: TransplantCategory,
  description: string,
  indications: string[],
  procedure: string[],
  complications: string[],
  monitoring: string[],
  patientExplanation: string,
): TransplantMedicineEntry => ({
  id, name, nameEs, category, description, indications, procedure, complications, monitoring, patientExplanation,
});

// Database — 25 entries
export const TRANSPLANT_MEDICINE_ENTRIES: Record<string, TransplantMedicineEntry> = {

  // === ORGAN TRANSPLANT (4) ===

  'kidney-transplant': tm('kidney-transplant', 'Kidney Transplant', 'Trasplante de Riñón', 'organ-transplant',
    'Surgical replacement of a failing kidney with a healthy donor kidney, placed in the iliac fossa with vascular anastomoses to the iliac vessels and ureteral implantation into the bladder.',
    ['End-stage renal disease (ESRD) with GFR < 20 mL/min',
     'Dialysis-dependent chronic kidney disease',
     'Diabetic nephropathy with progressive renal failure',
     'Polycystic kidney disease with renal failure',
     'IgA nephropathy or focal segmental glomerulosclerosis unresponsive to treatment'],
    ['Recipient undergoes general anesthesia; donor kidney is inspected on a back table.',
     'An incision is made in the iliac fossa (Gibson incision).',
     'Renal artery is anastomosed end-to-side to the external iliac artery.',
     'Renal vein is anastomosed end-to-side to the external iliac vein.',
     'Ureteroneocystostomy: the donor ureter is implanted into the bladder with an anti-reflux tunnel.',
     'A ureteral stent is placed and removed at 4–6 weeks post-op.',
     'The native kidneys are typically left in place unless there is a specific indication for removal.'],
    ['Delayed graft function requiring temporary dialysis',
     'Urine leak or ureteral stricture',
     'Renal artery or vein thrombosis',
     'Lymphocele formation',
     'Acute or chronic rejection',
     'BK polyomavirus nephropathy',
     'Recurrence of primary renal disease in the allograft'],
    ['Serum creatinine and GFR daily during hospitalization, then at each clinic visit',
     'Tacrolimus trough levels twice weekly initially, then weekly',
     'Renal allograft ultrasound with Doppler at 24 hours and as clinically indicated',
     'Urinalysis and urine culture at each visit',
     'BK virus PCR monthly for the first year',
     'DSA (donor-specific antibodies) at 1, 3, 6, and 12 months',
     'Protocol biopsy at 3 and 12 months at some centers'],
    'A kidney transplant replaces the work of your failed kidneys by placing a healthy kidney from a donor into your lower abdomen. After surgery, the new kidney filters your blood and makes urine so you no longer need dialysis. You will take anti-rejection medications every day for the life of the transplant.'),

  'liver-transplant': tm('liver-transplant', 'Liver Transplant', 'Trasplante de Hígado', 'organ-transplant',
    'Orthotopic replacement of a diseased liver with a donor liver, involving a total hepatectomy and implantation with reconstruction of the hepatic veins, portal vein, hepatic artery, and bile duct.',
    ['Decompensated cirrhosis (MELD score ≥ 15)',
     'Hepatocellular carcinoma within Milan criteria',
     'Acute liver failure (acetaminophen toxicity, viral hepatitis, Wilson disease)',
     'Primary sclerosing cholangitis with recurrent cholangitis',
     'Primary biliary cholangitis unresponsive to ursodiol',
     'Metabolic liver diseases (alpha-1 antitrypsin deficiency, hereditary hemochromatosis)'],
    ['Total hepatectomy of the native liver during the anhepatic phase.',
     'Donor liver implanted orthotopically; suprahepatic and infrahepatic vena cava anastomosed (or piggyback technique).',
     'Portal vein anastomosis performed end-to-end.',
     'Hepatic artery anastomosis performed under loupe or microscope magnification.',
     'Bile duct reconstruction: choledochocholedochostomy (duct-to-duct) or Roux-en-Y hepaticojejunostomy.',
     'Reperfusion of the graft and meticulous hemostasis.',
     'Abdominal drains placed near the anastomoses.'],
    ['Primary non-function of the graft (requires re-transplant)',
     'Hepatic artery thrombosis — the most feared vascular complication',
     'Portal vein thrombosis or stenosis',
     'Biliary leak or stricture',
     'Acute cellular or antibody-mediated rejection',
     'Recurrence of hepatitis C or hepatocellular carcinoma',
     'Sepsis and multi-organ failure in the early post-operative period'],
    ['Liver function tests (AST, ALT, bilirubin, INR, albumin) daily initially',
     'Hepatic artery Doppler ultrasound on post-op day 1 and as indicated',
     'Tacrolimus trough levels daily during hospitalization',
     'Bile output and drain character monitored closely',
     'MRCP or ERCP if biliary complication suspected',
     'Hepatitis C viral load if transplanted for HCV',
     'Annual screening for de novo malignancy'],
    'A liver transplant removes your diseased liver entirely and replaces it with a healthy one from a donor. The new liver takes over all the functions your old liver could no longer perform, including clearing toxins and making proteins your body needs. Recovery takes several months, and lifelong medications prevent your body from rejecting the new organ.'),

  'heart-transplant': tm('heart-transplant', 'Heart Transplant', 'Trasplante de Corazón', 'organ-transplant',
    'Orthotopic transplantation of a donor heart in a patient with end-stage heart failure refractory to maximal medical therapy, performed with cardiopulmonary bypass and bicaval or biatrial anastomosis technique.',
    ['End-stage heart failure (NYHA Class III–IV) despite optimal medical therapy',
     'Refractory cardiogenic shock requiring mechanical circulatory support',
     'Severe ischemic cardiomyopathy not amenable to revascularization',
     'Hypertrophic or restrictive cardiomyopathy with intractable symptoms',
     'Recurrent life-threatening ventricular arrhythmias uncontrolled by ICD or ablation',
     'Congenital heart disease with failing physiology'],
    ['Median sternotomy and initiation of cardiopulmonary bypass.',
     'Cardiectomy: native heart excised leaving cuffs of left and right atria (biatrial) or complete excision (bicaval).',
     'Donor heart implanted: left atrial anastomosis performed first.',
     'Bicaval technique: SVC and IVC anastomosed separately to preserve right atrial geometry.',
     'Pulmonary artery and aortic anastomoses completed.',
     'Air is de-aired from the cardiac chambers and cross-clamp is removed.',
     'The heart is reperfused and weaned from cardiopulmonary bypass with inotropic support.'],
    ['Primary graft dysfunction in the first 24 hours',
     'Right ventricular failure due to pre-existing pulmonary hypertension',
     'Cardiac allograft vasculopathy (chronic rejection)',
     'Acute cellular or antibody-mediated rejection',
     'Bradyarrhythmias requiring permanent pacemaker',
     'Infection (mediastinitis, CMV, Aspergillus)',
     'Malignancy — particularly post-transplant lymphoproliferative disorder (PTLD)'],
    ['Endomyocardial biopsy: weekly for 6 weeks, biweekly to 3 months, then tapering schedule',
     'Echocardiogram at each clinic visit to assess graft function',
     'Right heart catheterization at 1 month and annually',
     'Coronary angiography or intravascular ultrasound annually to screen for allograft vasculopathy',
     'Tacrolimus or cyclosporine trough levels at each visit',
     'CMV and EBV viral loads monthly for 6 months',
     'Gene expression profiling (AlloMap) as non-invasive rejection surveillance after 6 months'],
    'A heart transplant gives you a new heart from a donor when your own heart can no longer pump well enough to keep you alive. After surgery, the new heart beats on its own and supplies your body with the blood it needs. You will need regular heart biopsies in the first year to check for rejection, and you will take anti-rejection medications for life.'),

  'lung-transplant': tm('lung-transplant', 'Lung Transplant', 'Trasplante de Pulmón', 'organ-transplant',
    'Replacement of one or both diseased lungs with donor lungs, performed via thoracotomy or clamshell incision, with bronchial, pulmonary artery, and pulmonary venous (left atrial cuff) anastomoses.',
    ['Chronic obstructive pulmonary disease (COPD/emphysema) — most common indication',
     'Idiopathic pulmonary fibrosis with progressive decline',
     'Cystic fibrosis with FEV1 < 30% predicted or rapidly declining',
     'Pulmonary arterial hypertension refractory to medical therapy',
     'Alpha-1 antitrypsin deficiency with end-stage lung disease',
     'Sarcoidosis with advanced pulmonary fibrosis'],
    ['Single lung: posterolateral thoracotomy; bilateral: clamshell incision (bilateral anterior thoracotomy).',
     'Pneumonectomy of the native lung(s).',
     'Donor bronchus anastomosed to recipient bronchus with telescoping technique.',
     'Pulmonary artery anastomosed end-to-end.',
     'Left atrial cuff (containing pulmonary veins) anastomosed to recipient left atrium.',
     'Lung inflated and ventilated; reperfusion assessed for primary graft dysfunction.',
     'Chest tubes placed; bronchoscopy performed to inspect anastomoses.'],
    ['Primary graft dysfunction (PGD) — leading cause of early mortality',
     'Bronchial anastomotic dehiscence or stricture',
     'Chronic lung allograft dysfunction (CLAD), including bronchiolitis obliterans syndrome',
     'Acute cellular or antibody-mediated rejection',
     'Infection: bacterial pneumonia, CMV pneumonitis, Aspergillus tracheobronchitis',
     'Gastroesophageal reflux with aspiration',
     'Native lung hyperinflation in single lung recipients (emphysema)'],
    ['Pulmonary function tests (spirometry) at each visit; FEV1 is the key metric',
     'Chest X-ray at each visit; CT chest as indicated',
     'Bronchoscopy with bronchoalveolar lavage and transbronchial biopsy per protocol',
     'Tacrolimus trough levels at each visit',
     'CMV and EBV viral loads monthly for 6–12 months',
     'Sputum cultures for bacteria and fungi at each visit',
     'Annual bone density scan due to corticosteroid use'],
    'A lung transplant replaces your damaged lungs with healthy lungs from a donor, allowing you to breathe much more easily. After the operation, your breathing improves significantly, though you will need pulmonary rehabilitation to rebuild your strength. Lifelong anti-rejection medications and regular lung function tests are essential to keep the new lungs healthy.'),

  // === BONE MARROW (3) ===

  'allogeneic-hct': tm('allogeneic-hct', 'Allogeneic Hematopoietic Cell Transplant', 'Trasplante Alogénico de Células Hematopoyéticas', 'bone-marrow',
    'Infusion of hematopoietic stem cells from a matched donor (sibling, unrelated, or haploidentical) following myeloablative or reduced-intensity conditioning, enabling donor immune reconstitution and a graft-versus-tumor effect.',
    ['Acute myeloid leukemia (AML) in first or subsequent remission',
     'Acute lymphoblastic leukemia (ALL) — high-risk or relapsed',
     'Myelodysplastic syndrome (MDS) with high-risk features',
     'Severe aplastic anemia unresponsive to immunosuppressive therapy',
     'Chronic myeloid leukemia resistant or intolerant to tyrosine kinase inhibitors',
     'Primary immunodeficiency disorders (SCID, Wiskott-Aldrich)'],
    ['HLA typing and donor selection: 8/8 matched unrelated donor or HLA-identical sibling preferred.',
     'Conditioning regimen: myeloablative (busulfan/cyclophosphamide or TBI/cyclophosphamide) or reduced-intensity.',
     'Central venous catheter placed (Hickman or PICC).',
     'Stem cells infused intravenously on day 0 — they home to the bone marrow.',
     'GVHD prophylaxis initiated (tacrolimus + methotrexate or post-transplant cyclophosphamide for haplo).',
     'Supportive care: antimicrobial prophylaxis, blood product support, total parenteral nutrition as needed.',
     'Engraftment monitored: ANC > 500 for 3 consecutive days typically by day 14–21.'],
    ['Graft-versus-host disease (GVHD) — acute (skin, liver, GI) and chronic (multi-organ)',
     'Graft failure or delayed engraftment',
     'Sinusoidal obstruction syndrome (veno-occlusive disease)',
     'Transplant-associated thrombotic microangiopathy',
     'Severe infections during neutropenic period (bacterial, fungal, viral)',
     'Engraftment syndrome with fever, rash, and capillary leak',
     'Secondary malignancies and myelodysplastic syndrome'],
    ['Daily CBC with differential until engraftment',
     'Chimerism studies (STR-PCR) at days 30, 60, 90, and then quarterly',
     'CMV and EBV PCR weekly for at least 100 days',
     'Tacrolimus levels twice weekly',
     'Liver function tests and ferritin weekly',
     'Pulmonary function tests at 100 days, 6 months, and 1 year',
     'GVHD assessment at every visit using NIH consensus criteria'],
    'An allogeneic stem cell transplant uses blood-forming cells from a matched donor to replace your bone marrow. Before the transplant, you receive chemotherapy (and sometimes radiation) to prepare your body. The donor cells rebuild your immune system and can also fight remaining cancer cells. The main risk is graft-versus-host disease, where the donor cells react against your body.'),

  'autologous-hct': tm('autologous-hct', 'Autologous Hematopoietic Cell Transplant', 'Trasplante Autólogo de Células Hematopoyéticas', 'bone-marrow',
    'Collection and reinfusion of the patient\'s own hematopoietic stem cells after high-dose myeloablative chemotherapy, allowing dose-intensive treatment while rescuing bone marrow function.',
    ['Multiple myeloma — standard of care for eligible patients',
     'Relapsed or refractory Hodgkin lymphoma',
     'Relapsed or refractory diffuse large B-cell lymphoma',
     'Relapsed germ cell tumors sensitive to salvage chemotherapy',
     'Systemic amyloidosis with cardiac involvement (selected cases)',
     'Severe autoimmune diseases refractory to conventional therapy (emerging indication)'],
    ['Mobilization: G-CSF (filgrastim) with or without plerixafor to mobilize stem cells into the blood.',
     'Apheresis: stem cells collected via a large-bore catheter over 1–3 sessions; target ≥ 2 × 10^6 CD34+ cells/kg.',
     'Stem cells cryopreserved in DMSO at −196°C.',
     'High-dose conditioning chemotherapy (e.g., melphalan 200 mg/m² for myeloma; BEAM for lymphoma).',
     'Stem cells thawed at bedside and infused intravenously on day 0.',
     'Supportive care: antimicrobial prophylaxis, transfusions, anti-emetics.',
     'Engraftment expected by day 10–14.'],
    ['Febrile neutropenia and sepsis during the aplastic phase',
     'Mucositis — severe oral and GI mucosal breakdown',
     'Engraftment syndrome with fever and capillary leak',
     'Organ toxicity from conditioning (cardiac, hepatic, pulmonary)',
     'Delayed immune reconstitution with susceptibility to viral infections',
     'Infusion reaction to DMSO during stem cell infusion (garlic-like taste, nausea)',
     'Disease relapse remains the primary cause of treatment failure'],
    ['Daily CBC until engraftment (ANC > 500 for 3 days)',
     'Daily metabolic panel and liver function tests during hospitalization',
     'Blood cultures with any fever during neutropenia',
     'Disease-specific restaging at day 100 (PET/CT, serum protein electrophoresis)',
     'Immune reconstitution assessment at 3, 6, and 12 months',
     'Revaccination schedule beginning at 3–6 months post-transplant',
     'Long-term screening for secondary myelodysplasia/leukemia'],
    'An autologous transplant uses your own stem cells. We collect them from your blood before giving you very high-dose chemotherapy to kill cancer cells. Then your stored stem cells are returned to you through an IV to rebuild your bone marrow. Because the cells are your own, there is no risk of graft-versus-host disease, but the treatment itself is intensive.'),

  'car-t-cell-therapy': tm('car-t-cell-therapy', 'CAR T-Cell Therapy', 'Terapia de Células CAR-T', 'bone-marrow',
    'A form of adoptive cell therapy in which the patient\'s T lymphocytes are genetically engineered to express a chimeric antigen receptor (CAR) targeting a tumor-associated antigen, then expanded ex vivo and reinfused to achieve tumor-directed cytotoxicity.',
    ['Relapsed/refractory B-cell acute lymphoblastic leukemia (age ≤ 25)',
     'Relapsed/refractory diffuse large B-cell lymphoma after ≥ 2 lines of therapy',
     'Relapsed/refractory follicular lymphoma after ≥ 2 lines of therapy',
     'Relapsed/refractory mantle cell lymphoma',
     'Relapsed/refractory multiple myeloma after ≥ 4 prior lines (BCMA-directed)',
     'Additional indications under investigation in clinical trials'],
    ['Leukapheresis: patient\'s T cells collected via apheresis.',
     'T cells shipped to a manufacturing facility; genetically modified using a viral vector to express the CAR.',
     'CAR T cells expanded ex vivo over 2–4 weeks to reach therapeutic dose.',
     'Bridging therapy may be given while cells are manufactured to control disease.',
     'Lymphodepleting chemotherapy (fludarabine + cyclophosphamide) given 3–5 days before infusion.',
     'CAR T cells infused intravenously as a single dose.',
     'Patient monitored in an ICU-capable setting for at least 7–10 days post-infusion.'],
    ['Cytokine release syndrome (CRS) — fever, hypotension, hypoxia, organ dysfunction',
     'Immune effector cell-associated neurotoxicity syndrome (ICANS) — confusion, aphasia, seizures',
     'Prolonged cytopenias lasting weeks to months',
     'B-cell aplasia and hypogammaglobulinemia (on-target, off-tumor effect)',
     'Infection during prolonged immunosuppression',
     'Tumor lysis syndrome',
     'Rare reports of secondary T-cell lymphoma (FDA boxed warning)'],
    ['CRS grading per ASTCT consensus criteria; monitor ferritin, CRP, IL-6 daily',
     'Neurological assessments (ICE score) every 8–12 hours for 10 days',
     'CBC with differential daily; cytopenias may persist for months',
     'Quantitative immunoglobulins monthly; IVIG replacement if IgG < 400 mg/dL',
     'Disease restaging at day 28, day 90, and then per disease-specific guidelines',
     'CAR T-cell expansion measured by flow cytometry or qPCR',
     'Long-term follow-up for 15 years per FDA mandate for gene therapy products'],
    'CAR T-cell therapy is a treatment that reprograms your own immune cells to fight cancer. Your T cells are collected, engineered in a laboratory to recognize a specific target on cancer cells, and then infused back into your body. These modified cells can cause a strong immune reaction called cytokine release syndrome, which the medical team monitors closely and treats if needed.'),

  // === IMMUNOSUPPRESSION (3) ===

  'calcineurin-inhibitors': tm('calcineurin-inhibitors', 'Calcineurin Inhibitors (Tacrolimus & Cyclosporine)', 'Inhibidores de Calcineurina (Tacrolimus y Ciclosporina)', 'immunosuppression',
    'Cornerstone maintenance immunosuppressive agents that block T-cell activation by inhibiting calcineurin, a phosphatase required for NFAT-mediated IL-2 transcription, thereby preventing T-cell proliferation and allograft rejection.',
    ['Maintenance immunosuppression after solid organ transplantation',
     'Prevention of graft-versus-host disease after allogeneic HCT',
     'Treatment of acute rejection (dose optimization)',
     'Tacrolimus preferred over cyclosporine in most modern protocols due to superior efficacy',
     'Cyclosporine still used in select populations (e.g., some heart transplant centers)'],
    ['Tacrolimus initiated at 0.05–0.1 mg/kg/day divided BID, adjusted by trough levels.',
     'Target trough: 8–12 ng/mL early post-transplant, 5–8 ng/mL for maintenance.',
     'Cyclosporine dosed at 3–5 mg/kg/day divided BID; target C2 levels per protocol.',
     'Extended-release tacrolimus (Envarsus XR, Astagraf XL) allows once-daily dosing.',
     'Sublingual administration is an alternative when oral intake is not possible.',
     'Avoid grapefruit and drug interactions (CYP3A4/P-glycoprotein substrates).',
     'Monitor for narrow therapeutic index — small dose changes cause large effect changes.'],
    ['Nephrotoxicity — dose-dependent; chronic CNI nephrotoxicity is the leading cause of late graft loss',
     'Neurotoxicity: tremor, headache, posterior reversible encephalopathy syndrome (PRES)',
     'New-onset diabetes after transplant (NODAT) — more common with tacrolimus',
     'Hypertension and electrolyte imbalances (hyperkalemia, hypomagnesemia)',
     'Alopecia (tacrolimus) or hirsutism and gingival hyperplasia (cyclosporine)',
     'Thrombotic microangiopathy (hemolytic uremic syndrome)',
     'Increased infection and malignancy risk as with all immunosuppression'],
    ['Trough levels at every clinic visit; more frequently during dose changes',
     'Serum creatinine and electrolytes (K+, Mg2+, phosphate) at each visit',
     'Fasting glucose and HbA1c every 3 months',
     'Blood pressure monitoring at every visit',
     'Lipid panel annually',
     'Neurological symptom assessment at each visit',
     'Renal biopsy if creatinine rises and drug toxicity vs. rejection cannot be distinguished clinically'],
    'Tacrolimus and cyclosporine are the most important anti-rejection medications you will take after your transplant. They work by calming your immune system so it does not attack your new organ. You must take them at the same time every day and have regular blood tests to make sure the level in your blood is in the right range — too low risks rejection, too high risks kidney damage.'),

  'induction-therapy': tm('induction-therapy', 'Transplant Induction Therapy', 'Terapia de Inducción para Trasplante', 'immunosuppression',
    'Intensive immunosuppressive therapy administered at the time of transplantation to prevent early acute rejection during the period of highest immunological risk, typically using T-cell-depleting agents or IL-2 receptor antagonists.',
    ['Standard protocol for most kidney, pancreas, and intestinal transplants',
     'High-immunologic-risk recipients (highly sensitized, re-transplants, African American ethnicity)',
     'Delayed introduction of calcineurin inhibitors to protect renal function',
     'ABO-incompatible or positive crossmatch transplants (desensitization protocols)',
     'Some heart and lung transplant protocols'],
    ['Anti-thymocyte globulin (rATG/Thymoglobulin): 1–1.5 mg/kg/day IV for 3–5 days; depletes T cells.',
     'Basiliximab (Simulect): IL-2 receptor antagonist; 20 mg IV on day 0 and day 4; blocks T-cell activation without depletion.',
     'Alemtuzumab (Campath): anti-CD52; single dose of 30 mg IV; profound lymphocyte depletion (off-label in transplant).',
     'Premedication with acetaminophen, diphenhydramine, and corticosteroids to prevent infusion reactions.',
     'Choice of agent guided by immunologic risk assessment and center protocol.',
     'CBC monitored daily; platelet and WBC thresholds determine dose adjustments for rATG.',
     'CMV and infection prophylaxis extended with depleting agents.'],
    ['Infusion reactions: fever, chills, rigors, hypotension, anaphylaxis',
     'Profound and prolonged lymphopenia (especially with rATG and alemtuzumab)',
     'Increased risk of opportunistic infections (CMV, BK virus, fungal)',
     'Serum sickness with rATG (fever, rash, arthralgias, proteinuria)',
     'Leukopenia and thrombocytopenia',
     'Post-transplant lymphoproliferative disorder (PTLD) — higher risk with T-cell depletion',
     'Cytokine release syndrome with alemtuzumab'],
    ['CBC with differential daily during administration and weekly thereafter',
     'CD3+ T-cell count (for rATG) or total lymphocyte count to guide dosing',
     'Vital signs every 15 minutes during infusion',
     'CMV IgG serostatus and viral load monitoring per protocol',
     'EBV viral load in EBV-seronegative recipients at high risk for PTLD',
     'Renal function daily — to time safe introduction of calcineurin inhibitors',
     'Wound healing assessment, as depleting agents may impair healing'],
    'Induction therapy is powerful medication given right around the time of your transplant to prevent your immune system from rejecting the new organ in the critical first days. It temporarily lowers your immune defenses significantly, which is why the transplant team will monitor you very closely for infections during this time.'),

  'maintenance-immunosuppression': tm('maintenance-immunosuppression', 'Maintenance Immunosuppression Regimen', 'Régimen de Inmunosupresión de Mantenimiento', 'immunosuppression',
    'The long-term combination of immunosuppressive agents taken daily to prevent allograft rejection, typically consisting of a calcineurin inhibitor, an antimetabolite, and corticosteroids, with ongoing dose adjustments to balance rejection prevention against drug toxicity.',
    ['All solid organ transplant recipients require lifelong maintenance immunosuppression',
     'Standard triple therapy: tacrolimus + mycophenolate + prednisone',
     'Steroid minimization or withdrawal protocols used at select centers',
     'mTOR inhibitor-based regimens (sirolimus, everolimus) for calcineurin inhibitor sparing or malignancy risk reduction',
     'Belatacept (costimulation blocker) as calcineurin inhibitor-free alternative in kidney transplant'],
    ['Triple therapy initiated perioperatively: tacrolimus + mycophenolate mofetil + prednisone.',
     'Tacrolimus target troughs tapered over time: 8–12 ng/mL early, 5–8 ng/mL at 3–6 months, 4–6 ng/mL long-term.',
     'Mycophenolate mofetil 1000 mg BID (or mycophenolic acid 720 mg BID); dose adjusted for GI side effects or leukopenia.',
     'Prednisone tapered from 20 mg/day to 5 mg/day by 3 months; some protocols withdraw steroids by 6–12 months.',
     'Conversion to mTOR inhibitor considered for CNI nephrotoxicity, certain malignancies, or BK viremia.',
     'Belatacept 5 mg/kg IV monthly as an alternative to tacrolimus in EBV-seropositive kidney recipients.',
     'Medication adherence is the single most important modifiable risk factor for graft loss.'],
    ['Calcineurin inhibitor nephrotoxicity and metabolic effects (see CNI entry)',
     'Mycophenolate: GI disturbances (diarrhea, nausea), leukopenia, teratogenicity',
     'Corticosteroids: diabetes, osteoporosis, weight gain, cataracts, adrenal suppression, mood changes',
     'mTOR inhibitors: hyperlipidemia, oral ulcers, impaired wound healing, proteinuria, pneumonitis',
     'Overall increased risk of infections (opportunistic and community-acquired)',
     'Increased risk of skin cancer, lymphoma, and other malignancies',
     'Drug-drug interactions requiring vigilant medication reconciliation'],
    ['Drug trough levels at every clinic visit (tacrolimus, sirolimus, everolimus, cyclosporine)',
     'Comprehensive metabolic panel and CBC at each visit',
     'HbA1c every 3 months for the first year, then every 6 months',
     'Bone density scan (DEXA) at baseline and every 1–2 years',
     'Annual dermatology skin cancer screening',
     'Age-appropriate cancer screening (cervical, breast, colon)',
     'Annual ophthalmology exam for cataracts and glaucoma'],
    'After your transplant, you will take a combination of medications every day to keep your immune system from rejecting the new organ. The most common regimen includes tacrolimus, mycophenolate, and prednisone. Each medication works differently, and together they provide layered protection. It is crucial never to skip doses or stop any medication without talking to your transplant team.'),

  // === REJECTION (3) ===

  'hyperacute-rejection': tm('hyperacute-rejection', 'Hyperacute Rejection', 'Rechazo Hiperagudo', 'rejection',
    'Immediate and devastating allograft rejection occurring within minutes to hours of transplantation, caused by preformed donor-specific antibodies (usually anti-ABO or anti-HLA) that activate the complement cascade, leading to diffuse intravascular thrombosis and graft necrosis.',
    ['ABO-incompatible transplant performed without desensitization',
     'Positive lymphocytotoxic crossmatch missed prior to transplantation',
     'Preformed donor-specific HLA antibodies (from prior transplant, transfusion, or pregnancy)',
     'Extremely rare in the modern era due to mandatory crossmatching and ABO verification'],
    ['Preformed antibodies bind to donor endothelium immediately upon reperfusion.',
     'Complement cascade activated, leading to endothelial injury and platelet activation.',
     'Diffuse intravascular thrombosis occurs throughout the graft vasculature.',
     'The organ becomes cyanotic, mottled, and flaccid within minutes.',
     'No effective treatment — emergent graft nephrectomy (kidney) or retransplantation required.',
     'Prevention: ABO compatibility verification, pretransplant crossmatch testing (CDC and flow cytometry).',
     'Virtual crossmatch using solid-phase antibody testing (Luminex) now standard at most centers.'],
    ['Irreversible graft loss — the defining complication',
     'Disseminated intravascular coagulation (DIC)',
     'Hemodynamic instability and shock',
     'Surgical complications from emergent graft removal',
     'Sensitization making future transplant more difficult',
     'Psychological distress for the patient',
     'Extremely rare occurrence in modern transplant medicine'],
    ['Immediate intraoperative assessment of graft perfusion and color',
     'Intraoperative biopsy if perfusion appears abnormal',
     'Pretransplant: final crossmatch result confirmed before proceeding to OR',
     'Virtual crossmatch with single-antigen bead (SAB) testing',
     'ABO verification by two independent personnel per protocol',
     'Calculated panel reactive antibody (cPRA) to quantify sensitization',
     'Post-event: evaluate for preformed DSA that may have been missed'],
    'Hyperacute rejection is the most severe form of organ rejection. It happens within minutes of transplant surgery when your blood contains antibodies that immediately attack the new organ. Thanks to modern blood testing performed before surgery, this type of rejection has become extremely rare. The crossmatch test done before your transplant is specifically designed to prevent this.'),

  'acute-rejection': tm('acute-rejection', 'Acute Allograft Rejection', 'Rechazo Agudo del Aloinjerto', 'rejection',
    'Immune-mediated injury to the allograft occurring days to months after transplantation, classified as T-cell-mediated (cellular) or antibody-mediated rejection, diagnosed by clinical findings and histological assessment on allograft biopsy using Banff classification criteria.',
    ['Most common in the first 3–6 months post-transplant',
     'T-cell-mediated rejection (TCMR): tubulitis and interstitial inflammation on biopsy',
     'Antibody-mediated rejection (ABMR): donor-specific antibodies, C4d deposition, microvascular inflammation',
     'Risk factors: non-adherence, inadequate immunosuppression, HLA mismatch, young age, African American ethnicity',
     'Can occur at any time; late acute rejection often associated with non-adherence'],
    ['Clinical suspicion: rising creatinine (kidney), elevated LFTs (liver), decreased EF (heart), declining FEV1 (lung).',
     'Allograft biopsy obtained — gold standard for diagnosis.',
     'Biopsy graded per Banff classification (kidney) or ISHLT criteria (heart, lung).',
     'TCMR treatment: high-dose pulse methylprednisolone (500–1000 mg IV × 3 days).',
     'Steroid-resistant TCMR: anti-thymocyte globulin (rATG).',
     'ABMR treatment: plasmapheresis, IVIG, rituximab; consider bortezomib or eculizumab for refractory cases.',
     'Maintenance immunosuppression optimized: ensure adequate drug levels and adherence.'],
    ['Graft dysfunction ranging from mild to graft failure',
     'Chronic antibody-mediated rejection if not fully resolved — leading cause of late graft loss',
     'Opportunistic infections from intensified immunosuppression to treat rejection',
     'Development of de novo donor-specific antibodies',
     'Recurrent rejection episodes',
     'Need for retransplantation if graft fails',
     'Emotional and psychological impact on the patient'],
    ['Serum creatinine, LFTs, or organ-specific functional markers at each visit',
     'Donor-specific antibodies (DSA) by Luminex if ABMR suspected',
     'Protocol biopsies at scheduled intervals to detect subclinical rejection',
     'Drug trough levels to ensure therapeutic immunosuppression',
     'Repeat biopsy after treatment to assess response',
     'dd-cfDNA (donor-derived cell-free DNA) as a non-invasive biomarker',
     'Medication adherence assessment at every clinic visit'],
    'Acute rejection occurs when your immune system recognizes the transplanted organ as foreign and begins to attack it. Signs include changes in blood tests, decreased organ function, or sometimes no symptoms at all — which is why regular check-ups are so important. It is usually treatable with stronger immunosuppressive medications. Taking your medications exactly as prescribed is the best way to prevent this.'),

  'chronic-rejection': tm('chronic-rejection', 'Chronic Allograft Rejection', 'Rechazo Crónico del Aloinjerto', 'rejection',
    'Progressive and often irreversible deterioration of allograft function over months to years, characterized by transplant vasculopathy, interstitial fibrosis, and tubular atrophy (kidney) or obliterative bronchiolitis (lung), driven by both immune and non-immune mechanisms.',
    ['Leading cause of long-term graft loss in all solid organ transplants',
     'Kidney: interstitial fibrosis and tubular atrophy (IF/TA) with or without transplant glomerulopathy',
     'Heart: cardiac allograft vasculopathy (CAV) — diffuse, concentric coronary narrowing',
     'Lung: chronic lung allograft dysfunction (CLAD), including bronchiolitis obliterans syndrome (BOS)',
     'Liver: vanishing bile duct syndrome (ductopenic rejection)',
     'Risk factors: prior acute rejection, non-adherence, HLA mismatch, donor-specific antibodies, CMV infection'],
    ['Gradual onset: slowly rising creatinine, declining FEV1, recurrent liver test abnormalities.',
     'Allograft biopsy demonstrates characteristic histological findings (fibrosis, vasculopathy, duct loss).',
     'No highly effective treatment for established chronic rejection — largely irreversible.',
     'Optimize maintenance immunosuppression and ensure adherence.',
     'Treat modifiable risk factors: control blood pressure, manage dyslipidemia, treat CMV/BKV.',
     'Conversion to mTOR inhibitor-based regimen may slow progression in some cases.',
     'Retransplantation may be necessary when the graft fails.'],
    ['Progressive and irreversible graft failure',
     'Return to dialysis (kidney) or need for re-listing for transplant',
     'Cardiac death from allograft vasculopathy (heart)',
     'Respiratory failure requiring supplemental oxygen or retransplant (lung)',
     'Side effects of intensified immunosuppression',
     'Increased cardiovascular mortality with declining renal graft function',
     'Psychological burden of chronic graft deterioration'],
    ['Serum creatinine trend and proteinuria quantification at each visit',
     'Spirometry at each visit for lung recipients; FEV1 decline > 20% suggests BOS',
     'Annual coronary angiography or intravascular ultrasound for heart recipients',
     'DSA monitoring every 6–12 months',
     'Protocol biopsies per center guidelines',
     'Blood pressure, lipid, and glucose management at each visit',
     'dd-cfDNA trending as a non-invasive monitoring tool'],
    'Chronic rejection is a slow process in which your immune system gradually damages the transplanted organ over months to years. Unlike acute rejection, it is much harder to reverse. The best way to slow it down is to take your medications faithfully, keep all your appointments, control your blood pressure and cholesterol, and report any changes in how you feel to your transplant team right away.'),

  // === DONATION (3) ===

  'living-kidney-donation': tm('living-kidney-donation', 'Living Kidney Donation', 'Donación de Riñón en Vida', 'donation',
    'Surgical removal of one kidney from a healthy living donor for transplantation into a recipient with end-stage renal disease, performed via laparoscopic or hand-assisted nephrectomy, providing superior graft outcomes compared to deceased-donor kidneys.',
    ['Related donors: first-degree relatives, extended family members',
     'Unrelated donors: spouses, friends, altruistic (non-directed) donors',
     'ABO-compatible or ABO-incompatible with desensitization protocol',
     'Paired kidney exchange (kidney swap) when direct donation is incompatible',
     'Donor must be in excellent health, typically age 18–70, with normal renal function'],
    ['Comprehensive donor evaluation: medical, surgical, psychosocial, and financial assessment.',
     'Independent donor advocate team ensures voluntary, informed consent.',
     'Cross-sectional imaging (CT angiogram) to assess renal anatomy and vascular variants.',
     'Laparoscopic donor nephrectomy (typically left kidney due to longer renal vein).',
     '3–4 small incisions plus a Pfannenstiel extraction incision.',
     'Kidney extracted, flushed with cold preservation solution, and transplanted immediately.',
     'Donor typically discharged on post-op day 1–2; full recovery in 4–6 weeks.'],
    ['Perioperative: bleeding, infection, DVT/PE, conversion to open surgery (< 1%)',
     'Post-donation: slightly elevated lifetime risk of ESRD (still very low — 0.3% vs. 0.1%)',
     'Mild long-term decrease in GFR (compensatory hypertrophy of remaining kidney)',
     'Gestational hypertension and preeclampsia (slight increase in female donors)',
     'No difference in overall life expectancy compared to matched non-donors',
     'Potential psychological impact: positive (altruistic satisfaction) or negative (regret, financial burden)',
     'Incisional hernia at the extraction site (uncommon)'],
    ['Post-operative: daily creatinine until discharge; clinic visit at 1 and 2 weeks',
     'Blood pressure and renal function at 6 months, 1 year, and then annually for at least 2 years',
     'Urinalysis with albumin-to-creatinine ratio annually',
     'Long-term follow-up per UNOS/OPTN requirements: 2-year mandatory, lifetime recommended',
     'Monitor for hypertension development; lower threshold for treatment in donors',
     'Psychosocial follow-up at 6 months and 1 year',
     'Encourage donors to maintain healthy lifestyle: avoid NSAIDs, stay hydrated, no smoking'],
    'Living kidney donation is one of the most generous gifts one person can give another. The surgery is performed laparoscopically through small incisions, and most donors go home within 1–2 days. Your remaining kidney grows slightly larger and takes over the full workload. Donors live just as long as non-donors and have an excellent quality of life, though lifelong follow-up is recommended.'),

  'deceased-organ-donation': tm('deceased-organ-donation', 'Deceased Organ Donation', 'Donación de Órganos de Fallecido', 'donation',
    'The process of recovering organs from a donor who has been declared dead (brain death or circulatory death) for transplantation, governed by UNOS/OPTN policies, requiring family consent and meticulous organ preservation to ensure graft viability.',
    ['Brain death: irreversible cessation of all brain function including the brainstem',
     'Donation after circulatory death (DCD): controlled withdrawal of life-sustaining treatment',
     'Standard criteria donors (SCD): younger donors without significant comorbidities',
     'Expanded criteria donors (ECD) / KDPI > 85%: older donors or those with hypertension, diabetes, or elevated creatinine',
     'One deceased donor can save up to 8 lives (organs) and improve 75+ lives (tissues)'],
    ['Brain death or imminent death identified; organ procurement organization (OPO) notified.',
     'Clinical triggers: ventilator-dependent patient with devastating neurological injury.',
     'Brain death declaration per hospital policy (two clinical exams or confirmatory test).',
     'Donor management: hemodynamic optimization, hormone resuscitation (T4, vasopressin, methylprednisolone).',
     'Family approached for consent by trained OPO staff; donor registry checked.',
     'UNOS allocation system matches organs to recipients based on medical urgency, compatibility, distance, and waiting time.',
     'Organs recovered in the OR; cold preservation (UW solution or HTK) and transported to recipient centers.'],
    ['Prolonged cold ischemia time leading to delayed graft function',
     'Disease transmission from donor (rare but possible: malignancy, infection)',
     'DCD donors: higher risk of primary non-function due to warm ischemia',
     'Extended criteria organs: higher rate of delayed graft function and shorter graft survival',
     'Organ discard rate remains problematically high in the United States',
     'Ethical considerations surrounding DCD timing and declaration of death',
     'Family distress during an emotionally overwhelming time'],
    ['Donor: serial labs (BMP, CBC, LFTs, ABG), echocardiogram, bronchoscopy, urinalysis',
     'Donor-recipient crossmatch and HLA typing prior to acceptance',
     'Cold ischemia time documented: kidney < 24 hrs, liver < 12 hrs, heart < 4–6 hrs, lung < 6–8 hrs',
     'Machine perfusion (hypothermic or normothermic) increasingly used to assess and preserve organs',
     'KDPI (Kidney Donor Profile Index) score communicated to recipient team',
     'Donor infection screening: HIV, Hepatitis B/C, CMV, EBV, HTLV, syphilis, NAT testing',
     'Post-recovery organ biopsy (e.g., wedge kidney biopsy) for quality assessment'],
    'Deceased organ donation occurs when someone who has died chooses — or their family chooses — to give their organs to people who need transplants. A single donor can save up to eight lives. The process is handled with great respect and dignity, and organ donation does not affect the appearance of the body for an open-casket funeral.'),

  'kidney-paired-exchange': tm('kidney-paired-exchange', 'Kidney Paired Exchange', 'Intercambio de Riñón en Pareja', 'donation',
    'A system that matches incompatible donor-recipient pairs with other incompatible pairs so that each donor gives a kidney to the other pair\'s recipient, overcoming ABO and HLA incompatibility barriers through swap chains that can involve multiple pairs and altruistic donors.',
    ['Donor-recipient pair with ABO blood type incompatibility',
     'Donor-recipient pair with positive crossmatch due to donor-specific HLA antibodies',
     'Desire to obtain a better HLA-matched kidney through exchange',
     'Non-directed altruistic donor willing to initiate a chain',
     'Highly sensitized recipients with high cPRA who are difficult to match'],
    ['Incompatible pair enrolls in a kidney paired donation registry (UNOS KPD, NKR, or Alliance for Paired Kidney Donation).',
     'Algorithm identifies compatible matches across multiple pairs.',
     'Domino chains: altruistic donor starts a chain, enabling multiple transplants.',
     'All surgeries in a swap are performed simultaneously (2-way swap) or sequentially (chains).',
     'Kidneys may be shipped between transplant centers for non-simultaneous chains.',
     'Virtual crossmatch and shipped blood crossmatch performed before final match confirmation.',
     'Bridge donors: donor in a chain donates later, keeping the chain going.'],
    ['Chain break: a donor in a non-simultaneous chain fails to donate, leaving a recipient without a kidney',
     'Logistical complexity of coordinating multiple ORs and centers',
     'Cold ischemia time increased when kidneys are shipped between centers',
     'Donor may decline to proceed at any stage (as is their right)',
     'Positive final crossmatch may halt a planned exchange',
     'Inequity: highly sensitized recipients may still be difficult to match even in KPD',
     'Emotional complexity when donors and recipients are at different centers'],
    ['Same monitoring as standard living donor and recipient protocols',
     'KPD registry tracks donor and recipient outcomes nationally',
     'Final crossmatch verified before all surgeries proceed',
     'Cold ischemia time monitored for shipped kidneys (target < 24 hours)',
     'Donor follow-up per OPTN Living Donor Follow-Up policy',
     'Recipient follow-up per standard kidney transplant protocol',
     'Program-specific KPD outcome reporting to SRTR (Scientific Registry of Transplant Recipients)'],
    'A kidney paired exchange is like a swap: if your willing donor is not a match for you, we pair you with another couple in the same situation. Your donor gives to their patient, and their donor gives to you. Sometimes long chains of swaps allow many transplants to happen from a single generous donor. This program greatly increases your chance of finding a compatible kidney.'),

  // === POST-TRANSPLANT (3) ===

  'infection-prophylaxis': tm('infection-prophylaxis', 'Post-Transplant Infection Prophylaxis', 'Profilaxis de Infecciones Post-Trasplante', 'post-transplant',
    'Antimicrobial prophylaxis protocols designed to prevent opportunistic infections in immunosuppressed transplant recipients, targeting the highest-risk organisms during each post-transplant time period: early (< 1 month), intermediate (1–6 months), and late (> 6 months).',
    ['All solid organ and hematopoietic cell transplant recipients',
     'Early period (< 1 month): surgical site infections, hospital-acquired pathogens',
     'Intermediate period (1–6 months): CMV, PJP, EBV, BK virus, fungal infections',
     'Late period (> 6 months): community-acquired infections, late viral reactivation',
     'Donor/recipient serostatus (CMV D+/R−) guides CMV prophylaxis strategy'],
    ['Pneumocystis jirovecii prophylaxis: trimethoprim-sulfamethoxazole (TMP-SMX) SS daily or DS 3x/week; lifelong in many centers.',
     'CMV prophylaxis: valganciclovir 900 mg daily for 3–6 months (high-risk D+/R−) or 3 months (intermediate risk).',
     'Alternative CMV strategy: preemptive monitoring with weekly CMV PCR and treatment if viremia detected.',
     'Antifungal prophylaxis: fluconazole or micafungin for liver transplant; voriconazole or posaconazole for lung transplant.',
     'Antibacterial: perioperative antibiotics per organ-specific protocol (typically 24–48 hours).',
     'Antiviral: acyclovir or valacyclovir for HSV/VZV prophylaxis if not receiving valganciclovir.',
     'Vaccinations: influenza annually; avoid live vaccines; COVID, pneumococcal, hepatitis B per guidelines.'],
    ['Drug toxicity: valganciclovir causes neutropenia; TMP-SMX causes hyperkalemia, rash, cytopenias',
     'Breakthrough infection despite prophylaxis (drug-resistant CMV, resistant PJP)',
     'Clostridium difficile colitis from broad-spectrum antibiotic exposure',
     'Drug interactions: azoles inhibit CYP3A4, increasing tacrolimus and sirolimus levels',
     'Late CMV disease after prophylaxis discontinuation ("late-onset CMV")',
     'Hypersensitivity to TMP-SMX (use atovaquone or dapsone as alternative)',
     'Financial burden of multiple prophylactic medications'],
    ['CMV PCR weekly during prophylaxis for high-risk patients; monthly after discontinuation',
     'CBC weekly during valganciclovir therapy to monitor for neutropenia',
     'BK virus PCR monthly for kidney recipients in the first year',
     'EBV viral load monitoring for EBV D+/R− recipients (highest PTLD risk)',
     'Fungal biomarkers (galactomannan, beta-D-glucan) as indicated',
     'Vaccination titers to guide revaccination schedule',
     'Tuberculosis screening (quantiFERON or PPD) pretransplant and if exposed'],
    'After your transplant, your immune system is intentionally weakened to protect the new organ, which means you are more vulnerable to infections. We prescribe several preventive medications: one to prevent a lung infection called PCP, one to prevent a virus called CMV, and others depending on your specific risk. Hand hygiene, food safety, and avoiding sick contacts are also important protections.'),

  'post-transplant-malignancy': tm('post-transplant-malignancy', 'Post-Transplant Malignancy Screening', 'Detección de Malignidades Post-Trasplante', 'post-transplant',
    'Systematic screening for malignancies in transplant recipients who have a 2- to 4-fold increased cancer risk compared to the general population, driven by chronic immunosuppression, oncogenic viral reactivation (EBV, HPV, HHV-8), and reduced immune surveillance.',
    ['All solid organ and hematopoietic cell transplant recipients',
     'Skin cancer (squamous cell and basal cell) — most common post-transplant malignancy',
     'Post-transplant lymphoproliferative disorder (PTLD) — EBV-driven in most cases',
     'Kaposi sarcoma (HHV-8), anogenital cancers (HPV), hepatocellular carcinoma (HBV/HCV)',
     'Risk increases with duration and intensity of immunosuppression',
     'Kidney transplant recipients have the highest incidence due to longest graft survival'],
    ['Annual full-body skin examination by dermatology.',
     'Sun protection education: sunscreen SPF 30+, protective clothing, avoid peak sun hours.',
     'Cervical cancer screening (Pap smear/HPV co-testing) per guidelines; HPV vaccination if eligible.',
     'Colorectal cancer screening beginning at age 45 or per risk factors.',
     'Breast cancer screening with mammography per age-appropriate guidelines.',
     'Lung cancer screening with low-dose CT in those meeting standard criteria.',
     'Consider immunosuppression reduction or conversion to mTOR inhibitor (sirolimus) for patients who develop certain cancers.'],
    ['Delayed diagnosis due to atypical presentations in immunosuppressed patients',
     'Aggressive tumor behavior: faster growth, higher recurrence rates',
     'Treatment complicated by need to balance cancer therapy with graft preservation',
     'Immunosuppression reduction risks acute rejection',
     'Chemotherapy interactions with immunosuppressive medications',
     'PTLD can range from benign polyclonal proliferation to aggressive lymphoma',
     'Significant psychological burden of cancer diagnosis in transplant recipients'],
    ['Annual dermatology exam; more frequent if prior skin cancer',
     'EBV viral load monitoring in high-risk patients (EBV D+/R−)',
     'Screening labs: LDH, CBC with differential at each visit',
     'CT imaging for unexplained lymphadenopathy, weight loss, or fevers',
     'Age-appropriate cancer screening (mammography, colonoscopy, Pap smear, PSA)',
     'Hepatocellular carcinoma screening with AFP and ultrasound every 6 months if HBV/HCV',
     'Any new mass, skin lesion, or unexplained symptom warrants prompt evaluation'],
    'Transplant recipients have a higher risk of certain cancers because the medications that protect your organ also lower the immune system\'s ability to detect and destroy abnormal cells. Skin cancer is the most common, which is why wearing sunscreen and seeing a dermatologist yearly is essential. We will also screen for other cancers on a regular schedule and adjust your medications if needed.'),

  'metabolic-complications': tm('metabolic-complications', 'Post-Transplant Metabolic Complications', 'Complicaciones Metabólicas Post-Trasplante', 'post-transplant',
    'Cluster of metabolic derangements highly prevalent in transplant recipients, including new-onset diabetes after transplant (NODAT), dyslipidemia, hypertension, obesity, and metabolic bone disease, driven by immunosuppressive medications and contributing to cardiovascular morbidity and mortality.',
    ['New-onset diabetes after transplant (NODAT): 10–40% incidence; tacrolimus and corticosteroids are major risk factors',
     'Dyslipidemia: elevated LDL, triglycerides; worsened by mTOR inhibitors and corticosteroids',
     'Hypertension: 50–90% of kidney transplant recipients; caused by CNIs, corticosteroids, and native kidney disease',
     'Obesity and weight gain: corticosteroid-driven appetite increase, improved well-being post-transplant',
     'Metabolic bone disease: corticosteroid-induced osteoporosis, hyperparathyroidism carryover from CKD'],
    ['NODAT management: lifestyle modification, metformin first-line, insulin if needed; consider tacrolimus dose reduction.',
     'Dyslipidemia: statin therapy (atorvastatin preferred due to fewer drug interactions); start at low dose due to CNI interaction.',
     'Hypertension: calcium channel blockers (amlodipine, diltiazem) preferred first-line; ACE inhibitors/ARBs used cautiously (monitor K+ and creatinine).',
     'Weight management: dietary counseling, exercise program, avoid excessive caloric intake.',
     'Bone health: calcium 1000–1200 mg/day + vitamin D 800–1000 IU/day; bisphosphonates if DEXA T-score ≤ −2.5.',
     'Steroid tapering or withdrawal when feasible to reduce metabolic burden.',
     'Comprehensive cardiovascular risk assessment and management.'],
    ['Cardiovascular disease — leading cause of death in transplant recipients with a functioning graft',
     'Diabetic complications: retinopathy, neuropathy, nephropathy affecting the allograft',
     'Statin myopathy potentiated by CNI interaction',
     'Hyperkalemia from ACE inhibitor/ARB in CNI-treated patients',
     'Osteoporotic fractures — vertebral and hip fractures more common',
     'Avascular necrosis (osteonecrosis) from corticosteroid use',
     'Gout and hyperuricemia exacerbated by cyclosporine and diuretics'],
    ['Fasting glucose and HbA1c at each visit; oral glucose tolerance test at 3 months if normal',
     'Lipid panel at 1, 3, 6, and 12 months, then annually',
     'Blood pressure at every visit; ambulatory monitoring if white-coat hypertension suspected',
     'DEXA scan at baseline, 1 year, and every 1–2 years',
     'Vitamin D level (25-OH) at baseline and annually; PTH if indicated',
     'Weight, BMI, and waist circumference at each visit',
     'Uric acid level if gout symptoms or cyclosporine use'],
    'After transplant, the medications you take can affect your blood sugar, cholesterol, blood pressure, weight, and bones. These changes are common and manageable. Your transplant team will check for these regularly and may prescribe additional medications like a statin for cholesterol or blood pressure medicine. A healthy diet, regular exercise, and maintaining a healthy weight are especially important for transplant recipients.'),

  // === EVALUATION (3) ===

  'pretransplant-evaluation': tm('pretransplant-evaluation', 'Pre-Transplant Medical Evaluation', 'Evaluación Médica Pre-Trasplante', 'evaluation',
    'Comprehensive multidisciplinary assessment of a transplant candidate to determine medical suitability, identify comorbidities that may affect outcomes, ensure informed consent, and optimize the patient\'s condition before listing for transplantation.',
    ['End-stage organ failure meeting criteria for transplant listing',
     'Evaluation for all solid organ transplants: kidney, liver, heart, lung, pancreas, intestine',
     'Reassessment if patient deactivated from the waitlist and seeking relisting',
     'Multiorgan transplant evaluation (e.g., simultaneous liver-kidney)',
     'Living donor transplant: both donor and recipient undergo parallel evaluations'],
    ['Complete history and physical examination by the transplant team.',
     'Cardiac evaluation: ECG, echocardiogram, stress test; cardiac catheterization if indicated.',
     'Pulmonary evaluation: spirometry, DLCO, chest CT; 6-minute walk test for lung candidates.',
     'Infectious disease screening: HIV, Hepatitis B/C, CMV, EBV, TB, strongyloides, coccidioides (endemic areas).',
     'Cancer screening: age-appropriate (mammography, colonoscopy, Pap smear, PSA); CT if smoking history.',
     'Laboratory: ABO/Rh, HLA typing, PRA/cPRA, comprehensive metabolic panel, CBC, coagulation, lipids, HbA1c.',
     'Psychosocial evaluation: social work assessment, substance use history, support system, insurance verification.'],
    ['Discovery of occult malignancy during workup',
     'Identification of severe coronary artery disease requiring intervention before transplant',
     'Undiagnosed active infection that must be treated before listing',
     'Psychosocial barriers: active substance use, inadequate support, untreated mental illness',
     'Sensitization (high cPRA) making donor matching extremely difficult',
     'Financial barriers to affording lifelong immunosuppression',
     'Patient may be deemed too sick or not sick enough for transplant'],
    ['All workup components completed within 12 months; outdated studies must be repeated',
     'HLA antibody testing updated at regular intervals while on the waitlist',
     'Repeat cardiac and cancer screening per age and risk-based intervals',
     'Substance use: documented period of abstinence per center policy (typically 6 months for alcohol)',
     'BMI optimization: many centers require BMI < 35–40 for listing',
     'Dental clearance: untreated dental infections must be addressed',
     'Vaccination: complete all indicated vaccines before transplant (live vaccines prohibited post-transplant)'],
    'The pre-transplant evaluation is a thorough checkup to make sure your body is ready for a transplant and that a transplant is the best option for you. You will meet with many specialists, have blood tests, imaging studies, and heart tests. We also check for infections, cancer, and dental problems that need to be treated first. The social work team will help with insurance, support, and planning for after surgery.'),

  'hla-typing-crossmatch': tm('hla-typing-crossmatch', 'HLA Typing and Crossmatch Testing', 'Tipificación HLA y Prueba de Compatibilidad Cruzada', 'evaluation',
    'Immunological testing to determine human leukocyte antigen (HLA) profiles of donor and recipient, measure pre-existing anti-HLA antibodies, and perform crossmatch testing to predict immunological compatibility and the risk of antibody-mediated rejection.',
    ['Mandatory for all organ transplants: kidney, heart, lung, liver, pancreas, intestine',
     'Kidney transplant: HLA matching has the greatest impact on outcomes',
     'Identification and avoidance of unacceptable antigens in highly sensitized patients',
     'Monitoring for de novo donor-specific antibodies post-transplant',
     'Allogeneic HCT: HLA matching is critical for donor selection (8/8 or 10/10 match)'],
    ['HLA typing: DNA-based molecular methods (PCR-SSP, PCR-SSO, next-generation sequencing) for Class I (A, B, C) and Class II (DR, DQ, DP).',
     'Antibody screening: solid-phase assays (Luminex single-antigen beads) detect and quantify anti-HLA antibodies with MFI values.',
     'Calculated PRA (cPRA): percentage of donors expected to be incompatible; determines allocation priority.',
     'Virtual crossmatch: compares recipient antibody profile against donor HLA type to predict compatibility.',
     'Physical crossmatch: complement-dependent cytotoxicity (CDC) assay — gold standard; donor cells + recipient serum + complement.',
     'Flow cytometric crossmatch: more sensitive than CDC; detects low-level antibodies.',
     'Final crossmatch performed on day of transplant before proceeding to the OR.'],
    ['False-negative crossmatch: rare but can lead to hyperacute or accelerated rejection',
     'False-positive crossmatch: may inappropriately exclude a suitable donor',
     'Highly sensitized patients (cPRA > 99%) may wait years for a compatible donor',
     'Desensitization required for positive crossmatch or ABO-incompatible transplants',
     'De novo DSA development post-transplant associated with chronic rejection',
     'HLA epitope-level mismatch analysis (eplet mismatch) is an emerging field — adds complexity',
     'Cost and turnaround time for comprehensive testing'],
    ['Pretransplant antibody screening every 3 months while on the waitlist',
     'Update antibody profile after any sensitizing event (transfusion, pregnancy, failed graft)',
     'Post-transplant DSA monitoring at 1, 3, 6, and 12 months, then annually',
     'Virtual crossmatch reviewed before every organ offer acceptance',
     'Physical crossmatch results available before anesthesia induction',
     'Unacceptable antigen list updated in UNOS system as antibody profile changes',
     'HLA lab accredited by ASHI (American Society for Histocompatibility and Immunogenetics)'],
    'HLA typing is a blood test that looks at specific markers on your cells — think of them like a biological fingerprint. We compare your markers with the donor\'s to find the best possible match. We also test your blood for antibodies that could attack a donor organ. The crossmatch test, done right before surgery, is the final safety check to confirm your body will accept the new organ.'),

  'unos-allocation': tm('unos-allocation', 'UNOS Organ Allocation System', 'Sistema de Asignación de Órganos UNOS', 'evaluation',
    'The national framework governed by the United Network for Organ Sharing (UNOS) and the Organ Procurement and Transplantation Network (OPTN) that determines how deceased-donor organs are distributed to waiting recipients based on medical urgency, compatibility, geography, and waiting time.',
    ['All deceased-donor organ allocation in the United States',
     'Kidney: allocation based on KDPI, EPTS score, HLA matching, cPRA, waiting time, and distance',
     'Liver: allocation based on MELD/PELD score (medical urgency) and distance',
     'Heart: allocation based on status (1–6) reflecting urgency and mechanical support',
     'Lung: allocation based on Lung Allocation Score (LAS) incorporating urgency and post-transplant survival',
     'Pediatric recipients receive priority for pediatric donor organs'],
    ['Donor organ becomes available; OPO enters donor data into UNOS DonorNet system.',
     'Organ-specific allocation algorithm generates a ranked match list of compatible candidates.',
     'Kidney: points for waiting time, HLA matching, cPRA (highly sensitized get priority), pediatric status, prior living donor.',
     'Liver: ranked by MELD score (Na-adjusted); exception points for HCC and other conditions.',
     'Heart: status-based system (Status 1–6); Status 1 = most urgent (e.g., VA-ECMO, BiVAD).',
     'Lung: LAS score ranges 0–100; higher score = sicker + better expected post-transplant survival.',
     'Organs offered to transplant centers in order; center accepts or declines based on organ quality and recipient status.'],
    ['Organ discards: high discard rates (especially kidneys) due to conservative acceptance practices',
     'Geographic disparities in access to transplantation',
     'Wait time varies dramatically by organ, blood type, and region',
     'MELD score may not capture true disease severity in all patients (exception requests)',
     'Allocation system cannot eliminate all inequities (race, socioeconomic status, geography)',
     'Delayed acceptance decisions increase cold ischemia time',
     'Ethical debates surrounding allocation to patients with substance use history or advanced age'],
    ['Patient status on the waitlist reviewed and updated regularly',
     'MELD score updated every 7–90 days depending on score (higher scores updated more frequently)',
     'Heart status certified and recertified per OPTN policy',
     'LAS recalculated with updated clinical data (6-minute walk, PFTs, O2 requirement)',
     'cPRA and unacceptable antigens updated after sensitizing events',
     'Waitlist mortality monitored: patients who are too sick or who die while waiting',
     'Annual program-specific reports published by SRTR for transparency'],
    'UNOS is the national organization that manages the organ transplant waiting list and decides how donated organs are shared. When an organ becomes available, a computer system matches it to the best candidate based on medical urgency, blood type compatibility, body size, distance, and how long you have been waiting. The system is designed to be as fair and transparent as possible.'),

  // === COMPLICATION (3) ===

  'gvhd': tm('gvhd', 'Graft-Versus-Host Disease (GVHD)', 'Enfermedad de Injerto contra Huésped (EICH)', 'complication',
    'An immune-mediated condition unique to allogeneic hematopoietic cell transplantation in which donor-derived T lymphocytes recognize recipient tissues as foreign and mount an immune attack, classified as acute (< 100 days, affecting skin, liver, and GI tract) or chronic (> 100 days, resembling autoimmune disorders with multi-organ involvement).',
    ['Occurs in 30–70% of allogeneic HCT recipients depending on donor match and GVHD prophylaxis',
     'Acute GVHD: skin (maculopapular rash), liver (elevated bilirubin), GI (diarrhea, nausea, abdominal pain)',
     'Chronic GVHD: skin (sclerosis, lichen planus), mouth (xerostomia, ulcers), eyes (sicca), lungs (bronchiolitis obliterans), liver, joints',
     'Risk factors: HLA mismatch, unrelated donor, older donor/recipient age, female donor to male recipient, prior acute GVHD',
     'Graft-versus-leukemia (GVL) effect: GVHD and GVL are immunologically linked — some GVHD may be protective against relapse'],
    ['Acute GVHD grading: I–IV using skin stage, liver stage, and GI stage (Glucksberg criteria or MAGIC).',
     'First-line treatment: systemic corticosteroids (methylprednisolone 2 mg/kg/day).',
     'Steroid-refractory acute GVHD: ruxolitinib (Jakafi) — FDA-approved second-line agent.',
     'Other second-line options: extracorporeal photopheresis, anti-thymocyte globulin, alpha-1 antitrypsin.',
     'Chronic GVHD: systemic steroids + calcineurin inhibitor first-line; ibrutinib, ruxolitinib, or belumosudil for steroid-refractory.',
     'Topical therapies: corticosteroid creams/ointments for skin, dexamethasone rinse for oral GVHD.',
     'Supportive care: infection prophylaxis, nutritional support, physical therapy, ophthalmology for dry eyes.'],
    ['Steroid-refractory disease: poor prognosis, 30% overall survival for grade III–IV',
     'Opportunistic infections due to profound immunodeficiency (CMV, fungal, PJP, VZV)',
     'Chronic GVHD severely impacts quality of life: fibrosis, joint contractures, dry eyes/mouth',
     'Bronchiolitis obliterans: irreversible obstructive lung disease',
     'Steroid complications: diabetes, osteoporosis, avascular necrosis, myopathy',
     'Malnutrition from severe GI GVHD',
     'Late effects: secondary cancers, cataracts, endocrine dysfunction'],
    ['Acute GVHD: daily clinical assessment of skin (body surface area), stool output (volume and frequency), bilirubin',
     'GVHD biomarkers: REG3-alpha, ST2, TNFR1 (MAGIC algorithm) for prognosis',
     'Chronic GVHD: NIH consensus criteria scoring at every visit',
     'Pulmonary function tests every 3 months if lung GVHD suspected',
     'Ophthalmology: Schirmer test for tear production',
     'Nutrition assessment: weight, albumin, prealbumin',
     'Taper immunosuppression slowly; rebound GVHD common with rapid taper'],
    'Graft-versus-host disease (GVHD) occurs when the donor immune cells that were transplanted recognize your body as "foreign" and begin to attack it. Acute GVHD usually affects the skin (rash), gut (diarrhea), and liver. Chronic GVHD can affect many organs and feel like an autoimmune condition. Treatment involves medications that calm the immune response. Importantly, a mild form of this reaction can actually help fight remaining cancer cells.'),

  'transplant-infection': tm('transplant-infection', 'Opportunistic Infections in Transplant Recipients', 'Infecciones Oportunistas en Receptores de Trasplante', 'complication',
    'Infections caused by organisms that exploit the weakened immune defenses of transplant recipients, following a predictable timeline: nosocomial infections in the first month, opportunistic pathogens during months 1–6, and community-acquired infections thereafter, with late opportunistic infections in the over-immunosuppressed.',
    ['First month: surgical site infections, catheter-related bloodstream infections, C. difficile, donor-derived infections',
     'Months 1–6: CMV, BK virus, EBV, PJP, Aspergillus, Nocardia, Listeria, reactivation of TB and endemic fungi',
     'After 6 months: community-acquired pneumonia, influenza, COVID-19, urinary tract infections',
     'Late opportunistic infections suggest excessive immunosuppression',
     'CMV is the most important viral pathogen in solid organ transplant'],
    ['Timeline-based approach to differential diagnosis.',
     'CMV disease: valganciclovir 900 mg BID (treatment dose) for 21 days minimum; IV ganciclovir if severe or unable to take PO.',
     'BK virus nephropathy (kidney transplant): reduce immunosuppression; no effective antiviral. IVIG and cidofovir used anecdotally.',
     'PJP: TMP-SMX at treatment dose (15–20 mg/kg/day TMP component); IV pentamidine if intolerant.',
     'Invasive aspergillosis: voriconazole first-line; adjust immunosuppressive levels for azole interaction.',
     'Nocardia: TMP-SMX plus imipenem or amikacin for severe disease; prolonged course (6–12 months).',
     'Reduce overall immunosuppression when safe — balance rejection risk against infection control.'],
    ['Disseminated or invasive infection with high mortality (invasive aspergillosis mortality 30–50%)',
     'CMV resistance to ganciclovir (UL97 or UL54 mutations) requiring foscarnet or maribavir',
     'BK virus graft nephropathy leading to graft loss',
     'PTLD triggered by uncontrolled EBV replication',
     'Drug interactions: azoles increase CNI and mTOR inhibitor levels dramatically',
     'Immune reconstitution inflammatory syndrome (IRIS) when immunosuppression reduced',
     'Prolonged hospitalization, readmissions, and impact on quality of life'],
    ['CMV PCR viral load: weekly during treatment, then monthly for 6 months after completion',
     'BK virus PCR monthly for 12 months, then every 3 months (kidney transplant)',
     'Blood cultures for any fever > 38.0°C',
     'Chest CT and sputum cultures/BAL for respiratory symptoms; galactomannan and beta-D-glucan',
     'Urinalysis and urine culture for urinary symptoms',
     'Adjust immunosuppression based on net state of immunosuppression assessment',
     'Respiratory viral panel during respiratory illness season'],
    'Because your anti-rejection medications lower your immune defenses, you are more susceptible to infections that healthy people can easily fight off. The risk of specific infections changes over time after transplant. Your team prescribes preventive medications and monitors you with blood tests. If you develop a fever, cough, diarrhea, or feel unwell, contact your transplant team immediately — early treatment makes a big difference.'),

  'ptld': tm('ptld', 'Post-Transplant Lymphoproliferative Disorder (PTLD)', 'Trastorno Linfoproliferativo Post-Trasplante (TLPT)', 'complication',
    'A spectrum of abnormal lymphoid proliferations occurring in immunosuppressed transplant recipients, ranging from benign polyclonal hyperplasia to aggressive monoclonal lymphoma, most commonly driven by Epstein-Barr virus (EBV) in the setting of impaired T-cell immune surveillance.',
    ['Incidence: 1–10% of transplant recipients depending on organ type and EBV serostatus',
     'Highest risk: EBV-seronegative recipient receiving organ from EBV-seropositive donor (D+/R−)',
     'Intestinal and multiorgan transplant recipients have the highest incidence',
     'Pediatric recipients at higher risk due to greater likelihood of EBV seronegativity',
     'T-cell-depleting induction therapy (rATG, alemtuzumab) increases risk',
     'Most cases occur in the first year post-transplant; late PTLD may be EBV-negative'],
    ['Clinical suspicion: unexplained lymphadenopathy, tonsillar enlargement, fevers, weight loss, organ dysfunction.',
     'Tissue biopsy: excisional lymph node or mass biopsy for histopathological classification (WHO system).',
     'Staging: PET/CT for extent of disease; bone marrow biopsy; LDH, uric acid, comprehensive labs.',
     'First-line: reduction of immunosuppression (RI) — the cornerstone of PTLD management.',
     'EBV-positive PTLD: rituximab (anti-CD20) ± RI; sequential rituximab followed by CHOP if no response.',
     'EBV-negative or aggressive PTLD: R-CHOP (rituximab, cyclophosphamide, doxorubicin, vincristine, prednisone).',
     'Adoptive immunotherapy with EBV-specific cytotoxic T lymphocytes (EBV-CTLs) in refractory cases.'],
    ['Acute rejection from immunosuppression reduction',
     'Graft loss if immunosuppression must be substantially reduced',
     'Chemotherapy toxicity: neutropenia, mucositis, cardiotoxicity (doxorubicin)',
     'Tumor lysis syndrome with bulky disease',
     'CNS involvement: poor prognosis',
     'Relapsed or refractory PTLD: limited treatment options, high mortality',
     'Secondary infections from intensified chemotherapy in an already immunosuppressed patient'],
    ['EBV viral load: weekly during active treatment, monthly during surveillance',
     'PET/CT at interim (after 2–3 cycles) and end of treatment for response assessment',
     'CBC, metabolic panel, LDH at each treatment cycle',
     'Echocardiogram if receiving doxorubicin',
     'Graft function closely monitored during immunosuppression reduction',
     'Post-remission: EBV viral load every 3 months for 2 years, then every 6 months',
     'Annual PET/CT or CT surveillance for 5 years per lymphoma guidelines'],
    'PTLD is an uncommon but serious condition in which the immune-lowering medications allow a virus called EBV to trigger abnormal growth of white blood cells, sometimes forming tumors. The first treatment is usually to reduce your anti-rejection medications so your own immune system can fight the abnormal cells. Additional treatments like rituximab or chemotherapy may be needed. Your team monitors your EBV levels regularly to catch this early.'),
};

// ---------------------------------------------------------------------------
// Utility Functions
// ---------------------------------------------------------------------------

/** Return all entries as a flat array. */
export function getAllTransplantEntries(): TransplantMedicineEntry[] {
  return Object.values(TRANSPLANT_MEDICINE_ENTRIES);
}

/** Filter entries by one or more categories. */
export function getTransplantEntriesByCategory(
  category: TransplantCategory | TransplantCategory[],
): TransplantMedicineEntry[] {
  const categories = Array.isArray(category) ? category : [category];
  return getAllTransplantEntries().filter((e) => categories.includes(e.category));
}

/** Search entries by query string across id, name, nameEs, description, and patientExplanation. */
export function searchTransplantEntries(query: string): TransplantMedicineEntry[] {
  const q = query.toLowerCase();
  return getAllTransplantEntries().filter(
    (e) =>
      e.id.toLowerCase().includes(q) ||
      e.name.toLowerCase().includes(q) ||
      e.nameEs.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.patientExplanation.toLowerCase().includes(q) ||
      e.indications.some((ind) => ind.toLowerCase().includes(q)) ||
      e.complications.some((c) => c.toLowerCase().includes(q)),
  );
}

/** Get a single entry by its ID, or undefined if not found. */
export function getTransplantEntryById(id: string): TransplantMedicineEntry | undefined {
  return TRANSPLANT_MEDICINE_ENTRIES[id];
}

/** Get all unique categories that have entries. */
export function getTransplantCategories(): TransplantCategory[] {
  const cats = new Set<TransplantCategory>();
  for (const entry of getAllTransplantEntries()) {
    cats.add(entry.category);
  }
  return Array.from(cats);
}
