/**
 * Detailed Organ Systems
 *
 * Extended anatomical structures with more detail for each organ system.
 */

import type { AnatomicalStructure } from "./AnatomyStructures";

// ============================================
// Detailed Cardiovascular System
// ============================================

export const DETAILED_CARDIOVASCULAR: AnatomicalStructure[] = [
  // Heart chambers
  {
    id: "rightAtrium",
    name: "Right Atrium",
    latinName: "Atrium Dextrum",
    parentId: "heart",
    system: "cardiovascular",
    geometry: "sphere",
    position: [-0.02, 0.52, 0.12],
    scale: [0.6, 0.8, 0.7],
    geometryArgs: [0.04, 16, 16],
    color: "#cc3333",
    roughness: 0.5,
    visibility: { structureId: "rightAtrium", minDetailLevel: "body" },
    description: "Receives deoxygenated blood from the body",
    clickable: true,
  },
  {
    id: "rightVentricle",
    name: "Right Ventricle",
    latinName: "Ventriculus Dexter",
    parentId: "heart",
    system: "cardiovascular",
    geometry: "capsule",
    position: [-0.06, 0.50, 0.08],
    rotation: [0.3, 0, 0],
    scale: [0.7, 1, 0.8],
    geometryArgs: [0.04, 0.06, 16, 16],
    color: "#cc3333",
    roughness: 0.5,
    visibility: { structureId: "rightVentricle", minDetailLevel: "body" },
    description: "Pumps blood to the lungs",
    clickable: true,
  },
  {
    id: "leftAtrium",
    name: "Left Atrium",
    latinName: "Atrium Sinistrum",
    parentId: "heart",
    system: "cardiovascular",
    geometry: "sphere",
    position: [-0.04, 0.58, 0.08],
    scale: [0.6, 0.8, 0.7],
    geometryArgs: [0.04, 16, 16],
    color: "#cc3333",
    roughness: 0.5,
    visibility: { structureId: "leftAtrium", minDetailLevel: "body" },
    description: "Receives oxygenated blood from lungs",
    clickable: true,
  },
  {
    id: "leftVentricle",
    name: "Left Ventricle",
    latinName: "Ventriculus Sinister",
    parentId: "heart",
    system: "cardiovascular",
    geometry: "capsule",
    position: [-0.08, 0.54, 0.12],
    rotation: [-0.2, 0, 0],
    scale: [0.8, 1, 0.9],
    geometryArgs: [0.045, 0.07, 16, 16],
    color: "#cc3333",
    roughness: 0.5,
    visibility: { structureId: "leftVentricle", minDetailLevel: "body" },
    description: "Pumps blood to the body",
    clickable: true,
  },
  // Major arteries
  {
    id: "pulmonaryTrunk",
    name: "Pulmonary Trunk",
    latinName: "Truncus Pulmonalis",
    parentId: "heart",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [-0.03, 0.62, 0.10],
    rotation: [0.4, 0, 0.3],
    geometryArgs: [0.02, 0.02, 0.10, 16],
    color: "#0000cc",
    roughness: 0.4,
    visibility: { structureId: "pulmonaryTrunk", minDetailLevel: "body" },
    description: "Carries blood to lungs",
    clickable: true,
  },
  {
    id: "leftCoronaryArtery",
    name: "Left Coronary Artery",
    latinName: "Arteria Coronaria Sinistra",
    parentId: "heart",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [-0.10, 0.56, 0.16],
    rotation: [0.5, 0.5, 0],
    geometryArgs: [0.008, 0.008, 0.08, 16],
    color: "#cc3333",
    roughness: 0.4,
    visibility: { structureId: "leftCoronaryArtery", minDetailLevel: "body" },
    description: "Supplies heart muscle",
    clickable: true,
  },
  {
    id: "rightCoronaryArtery",
    name: "Right Coronary Artery",
    latinName: "Arteria Coronaria Dextra",
    parentId: "heart",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [-0.02, 0.54, 0.18],
    rotation: [0.3, -0.5, 0],
    geometryArgs: [0.008, 0.008, 0.08, 16],
    color: "#cc3333",
    roughness: 0.4,
    visibility: { structureId: "rightCoronaryArtery", minDetailLevel: "body" },
    description: "Supplies heart muscle",
    clickable: true,
  },
  // Systemic arteries
  {
    id: "carotidArtery",
    name: "Common Carotid Artery",
    latinName: "Arteria Carotis Communis",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [0.02, 0.90, 0.08],
    geometryArgs: [0.012, 0.012, 0.25, 16],
    color: "#cc3333",
    roughness: 0.4,
    visibility: { structureId: "carotidArtery", minDetailLevel: "body" },
    description: "Supplies head and neck",
    clickable: true,
  },
  {
    id: "subclavianArtery",
    name: "Subclavian Artery",
    latinName: "Arteria Subclavia",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [0.15, 0.70, 0.02],
    rotation: [0, 0, 0.8],
    geometryArgs: [0.010, 0.010, 0.15, 16],
    color: "#cc3333",
    roughness: 0.4,
    visibility: { structureId: "subclavianArtery", minDetailLevel: "body" },
    description: "Supplies arm",
    clickable: true,
  },
  {
    id: "renalArtery",
    name: "Renal Artery",
    latinName: "Arteria Renalis",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [0.08, 0.08, -0.02],
    geometryArgs: [0.008, 0.008, 0.08, 16],
    color: "#cc3333",
    roughness: 0.4,
    visibility: { structureId: "renalArtery", minDetailLevel: "body" },
    description: "Supplies kidney",
    clickable: true,
  },
  {
    id: "iliacArtery",
    name: "Common Iliac Artery",
    latinName: "Arteria Iliaca Communis",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [0.05, -0.35, 0.05],
    rotation: [0, 0, -0.3],
    geometryArgs: [0.010, 0.010, 0.12, 16],
    color: "#cc3333",
    roughness: 0.4,
    visibility: { structureId: "iliacArtery", minDetailLevel: "body" },
    description: "Supplies lower body",
    clickable: true,
  },
];

// ============================================
// Detailed Respiratory System
// ============================================

export const DETAILED_RESPIRATORY: AnatomicalStructure[] = [
  {
    id: "nasalCavity",
    name: "Nasal Cavity",
    latinName: "Cavitas Nasalis",
    parentId: "head",
    system: "respiratory",
    geometry: "capsule",
    position: [0, 1.42, 0.15],
    scale: [1.5, 0.5, 0.6],
    geometryArgs: [0.06, 0.08, 16, 16],
    color: "#ffcccc",
    roughness: 0.7,
    opacity: 0.6,
    visibility: { structureId: "nasalCavity", minDetailLevel: "body" },
    description: "Filters, warms, and moistens air",
    clickable: true,
  },
  {
    id: "pharynx",
    name: "Pharynx",
    latinName: "Pharynx",
    system: "respiratory",
    geometry: "capsule",
    position: [0, 1.05, 0.06],
    geometryArgs: [0.03, 0.08, 16, 16],
    color: "#ffc0cb",
    roughness: 0.7,
    visibility: { structureId: "pharynx", minDetailLevel: "body" },
    description: "Throat passage for air and food",
    clickable: true,
  },
  {
    id: "larynx",
    name: "Larynx",
    latinName: "Larynx",
    system: "respiratory",
    geometry: "capsule",
    position: [0, 0.98, 0.05],
    geometryArgs: [0.025, 0.04, 16, 16],
    color: "#ffb0b0",
    roughness: 0.7,
    visibility: { structureId: "larynx", minDetailLevel: "body" },
    description: "Voice box",
    clickable: true,
  },
  {
    id: "epiglottis",
    name: "Epiglottis",
    latinName: "Epiglottis",
    system: "respiratory",
    geometry: "capsule",
    position: [0, 0.95, 0.07],
    rotation: [0.5, 0, 0],
    geometryArgs: [0.015, 0.02, 16, 16],
    color: "#ffb0b0",
    roughness: 0.7,
    visibility: { structureId: "epiglottis", minDetailLevel: "body" },
    description: "Protects trachea during swallowing",
    clickable: true,
  },
  {
    id: "bronchialTree",
    name: "Bronchial Tree",
    latinName: "Arbor Bronchialis",
    system: "respiratory",
    geometry: "capsule",
    position: [0, 0.48, 0],
    scale: [2, 0.8, 1.2],
    geometryArgs: [0.12, 0.15, 16, 16],
    color: "#ffa0a0",
    roughness: 0.75,
    opacity: 0.5,
    visibility: { structureId: "bronchialTree", minDetailLevel: "body" },
    description: "Network of bronchial tubes",
    clickable: true,
  },
  {
    id: "alveoli",
    name: "Alveolar Sac",
    latinName: "Sacculus Alveolaris",
    system: "respiratory",
    geometry: "sphere",
    position: [0, 0.45, 0.05],
    scale: [2, 1.5, 1.2],
    geometryArgs: [0.14, 16, 16],
    color: "#ff9999",
    roughness: 0.8,
    opacity: 0.4,
    visibility: { structureId: "alveoli", minDetailLevel: "body" },
    description: "Gas exchange surfaces",
    clickable: true,
  },
  {
    id: "pleura",
    name: "Pleural Membrane",
    latinName: "Pleura",
    system: "respiratory",
    geometry: "capsule",
    position: [0, 0.55, 0],
    scale: [1.8, 1.1, 1.4],
    geometryArgs: [0.18, 0.35, 16, 16],
    color: "#ffd0d0",
    roughness: 0.7,
    opacity: 0.15,
    visibility: { structureId: "pleura", minDetailLevel: "body" },
    description: "Membrane enclosing lungs",
    clickable: true,
  },
];

// ============================================
// Detailed Digestive System
// ============================================

export const DETAILED_DIGESTIVE: AnatomicalStructure[] = [
  {
    id: "oralCavity",
    name: "Oral Cavity",
    latinName: "Cavitas Oris",
    parentId: "head",
    system: "digestive",
    geometry: "sphere",
    position: [0, 1.30, 0.15],
    scale: [1.2, 0.6, 0.7],
    geometryArgs: [0.08, 16, 16],
    color: "#ffc0cb",
    roughness: 0.8,
    opacity: 0.7,
    visibility: { structureId: "oralCavity", minDetailLevel: "body" },
    description: "Mouth cavity",
    clickable: true,
  },
  {
    id: "salivaryGlands",
    name: "Salivary Glands",
    latinName: "Glandulae Salivariae",
    system: "digestive",
    geometry: "sphere",
    position: [0.10, 1.20, 0.10],
    geometryArgs: [0.03, 16, 16],
    color: "#ffcc99",
    roughness: 0.7,
    visibility: { structureId: "salivaryGlands", minDetailLevel: "body" },
    description: "Produce saliva",
    clickable: true,
  },
  {
    id: "pharynxDigestive",
    name: "Pharynx (Digestive)",
    latinName: "Pharynx",
    system: "digestive",
    geometry: "capsule",
    position: [0, 1.05, 0.04],
    geometryArgs: [0.02, 0.06, 16, 16],
    color: "#ffb0b0",
    roughness: 0.7,
    visibility: { structureId: "pharynxDigestive", minDetailLevel: "body" },
    description: "Swallowing passage",
    clickable: true,
  },
  {
    id: "duodenum",
    name: "Duodenum",
    latinName: "Duodenum",
    parentId: "smallIntestine",
    system: "digestive",
    geometry: "torus",
    position: [0.02, -0.05, 0.06],
    rotation: [0.5, 0, 0.3],
    geometryArgs: [0.05, 0.015, 16, 16],
    color: "#deb887",
    roughness: 0.8,
    visibility: { structureId: "duodenum", minDetailLevel: "body" },
    description: "First part of small intestine",
    clickable: true,
  },
  {
    id: "jejunum",
    name: "Jejunum",
    latinName: "Jejunum",
    parentId: "smallIntestine",
    system: "digestive",
    geometry: "torus",
    position: [0, -0.12, 0.05],
    geometryArgs: [0.06, 0.015, 16, 16],
    color: "#deb887",
    roughness: 0.8,
    visibility: { structureId: "jejunum", minDetailLevel: "body" },
    description: "Middle part of small intestine",
    clickable: true,
  },
  {
    id: "ileum",
    name: "Ileum",
    latinName: "Ileum",
    parentId: "smallIntestine",
    system: "digestive",
    geometry: "torus",
    position: [0, -0.18, 0.04],
    geometryArgs: [0.07, 0.015, 16, 16],
    color: "#deb887",
    roughness: 0.8,
    visibility: { structureId: "ileum", minDetailLevel: "body" },
    description: "Final part of small intestine",
    clickable: true,
  },
  {
    id: "cecum",
    name: "Cecum",
    latinName: "Intestinum Caecum",
    parentId: "largeIntestine",
    system: "digestive",
    geometry: "sphere",
    position: [0.12, -0.22, 0.04],
    geometryArgs: [0.04, 16, 16],
    color: "#cd853f",
    roughness: 0.8,
    visibility: { structureId: "cecum", minDetailLevel: "body" },
    description: "Beginning of large intestine",
    clickable: true,
  },
  {
    id: "colon",
    name: "Colon",
    latinName: "Colon",
    parentId: "largeIntestine",
    system: "digestive",
    geometry: "torus",
    position: [0, -0.15, 0],
    geometryArgs: [0.14, 0.02, 16, 16],
    color: "#cd853f",
    roughness: 0.8,
    visibility: { structureId: "colon", minDetailLevel: "body" },
    description: "Main part of large intestine",
    clickable: true,
  },
  {
    id: "rectum",
    name: "Rectum",
    latinName: "Rectum",
    parentId: "largeIntestine",
    system: "digestive",
    geometry: "cylinder",
    position: [0.02, -0.42, 0.02],
    rotation: [0.3, 0, 0],
    geometryArgs: [0.02, 0.02, 0.08, 16],
    color: "#cd853f",
    roughness: 0.8,
    visibility: { structureId: "rectum", minDetailLevel: "body" },
    description: "Final section of large intestine",
    clickable: true,
  },
  {
    id: "hepaticArtery",
    name: "Hepatic Artery",
    latinName: "Arteria Hepatica",
    parentId: "liver",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [0.08, 0.20, 0.08],
    rotation: [0.5, 0, 0.3],
    geometryArgs: [0.008, 0.008, 0.08, 16],
    color: "#cc3333",
    roughness: 0.4,
    visibility: { structureId: "hepaticArtery", minDetailLevel: "body" },
    description: "Supplies liver with blood",
    clickable: true,
  },
  {
    id: "portalVein",
    name: "Hepatic Portal Vein",
    latinName: "Vena Portae Hepatis",
    parentId: "liver",
    system: "cardiovascular",
    geometry: "cylinder",
    position: [0.05, 0.15, 0.04],
    rotation: [0.3, 0, 0.2],
    geometryArgs: [0.010, 0.010, 0.10, 16],
    color: "#3366cc",
    roughness: 0.4,
    visibility: { structureId: "portalVein", minDetailLevel: "body" },
    description: "Carries nutrients to liver",
    clickable: true,
  },
];

// ============================================
// Detailed Nervous System
// ============================================

export const DETAILED_NERVOUS: AnatomicalStructure[] = [
  {
    id: "frontalLobe",
    name: "Frontal Lobe",
    latinName: "Lobus Frontalis",
    parentId: "brain",
    system: "nervous",
    geometry: "sphere",
    position: [0, 1.50, 0.08],
    scale: [1, 0.6, 0.7],
    geometryArgs: [0.10, 16, 16],
    color: "#f0b0b0",
    roughness: 0.7,
    visibility: { structureId: "frontalLobe", minDetailLevel: "body" },
    description: "Executive functions, motor control",
    clickable: true,
  },
  {
    id: "parietalLobe",
    name: "Parietal Lobe",
    latinName: "Lobus Parietalis",
    parentId: "brain",
    system: "nervous",
    geometry: "sphere",
    position: [0, 1.45, 0],
    scale: [0.8, 0.7, 0.6],
    geometryArgs: [0.09, 16, 16],
    color: "#f0b0b0",
    roughness: 0.7,
    visibility: { structureId: "parietalLobe", minDetailLevel: "body" },
    description: "Sensory processing",
    clickable: true,
  },
  {
    id: "temporalLobe",
    name: "Temporal Lobe",
    latinName: "Lobus Temporalis",
    parentId: "brain",
    system: "nervous",
    geometry: "sphere",
    position: [-0.06, 1.35, 0.05],
    scale: [0.6, 0.7, 0.8],
    geometryArgs: [0.08, 16, 16],
    color: "#f0b0b0",
    roughness: 0.7,
    visibility: { structureId: "temporalLobe", minDetailLevel: "body" },
    description: "Auditory processing, memory",
    clickable: true,
  },
  {
    id: "occipitalLobe",
    name: "Occipital Lobe",
    latinName: "Lobus Occipitalis",
    parentId: "brain",
    system: "nervous",
    geometry: "sphere",
    position: [0, 1.38, -0.08],
    scale: [0.7, 0.6, 0.6],
    geometryArgs: [0.08, 16, 16],
    color: "#f0b0b0",
    roughness: 0.7,
    visibility: { structureId: "occipitalLobe", minDetailLevel: "body" },
    description: "Visual processing",
    clickable: true,
  },
  {
    id: "thalamus",
    name: "Thalamus",
    latinName: "Thalamus",
    system: "nervous",
    geometry: "sphere",
    position: [0, 1.35, 0],
    geometryArgs: [0.035, 16, 16],
    color: "#e8a0a0",
    roughness: 0.65,
    visibility: { structureId: "thalamus", minDetailLevel: "body" },
    description: "Relay center for brain signals",
    clickable: true,
  },
  {
    id: "hypothalamus",
    name: "Hypothalamus",
    latinName: "Hypothalamus",
    system: "nervous",
    geometry: "sphere",
    position: [0, 1.30, 0.02],
    geometryArgs: [0.025, 16, 16],
    color: "#e8a0a0",
    roughness: 0.65,
    visibility: { structureId: "hypothalamus", minDetailLevel: "body" },
    description: "Hormone regulation, homeostasis",
    clickable: true,
  },
  {
    id: "hippocampus",
    name: "Hippocampus",
    latinName: "Hippocampus",
    system: "nervous",
    geometry: "capsule",
    position: [-0.04, 1.32, -0.02],
    rotation: [0, 0, 0.5],
    geometryArgs: [0.015, 0.04, 16, 16],
    color: "#e09090",
    roughness: 0.7,
    visibility: { structureId: "hippocampus", minDetailLevel: "body" },
    description: "Memory formation",
    clickable: true,
  },
  {
    id: "basalGanglia",
    name: "Basal Ganglia",
    latinName: "Nuclei Basales",
    system: "nervous",
    geometry: "sphere",
    position: [0, 1.33, 0.04],
    geometryArgs: [0.030, 16, 16],
    color: "#d88080",
    roughness: 0.7,
    visibility: { structureId: "basalGanglia", minDetailLevel: "body" },
    description: "Movement control",
    clickable: true,
  },
  {
    id: "cranialNerves",
    name: "Cranial Nerves",
    latinName: "Nervi Craniales",
    system: "nervous",
    geometry: "cylinder",
    position: [0.05, 1.20, 0.10],
    rotation: [0.5, 0, 0],
    geometryArgs: [0.008, 0.008, 0.20, 16],
    color: "#ffffff",
    roughness: 0.5,
    opacity: 0.6,
    visibility: { structureId: "cranialNerves", minDetailLevel: "body" },
    description: "12 pairs of nerves from brain",
    clickable: true,
  },
  {
    id: "sciaticNerve",
    name: "Sciatic Nerve",
    latinName: "Nervus Ischiadicus",
    system: "nervous",
    geometry: "cylinder",
    position: [0.10, -0.70, 0.05],
    rotation: [0.3, 0, -0.3],
    geometryArgs: [0.012, 0.012, 0.50, 16],
    color: "#ffffff",
    roughness: 0.5,
    opacity: 0.7,
    visibility: { structureId: "sciaticNerve", minDetailLevel: "body" },
    description: "Largest nerve in body",
    clickable: true,
  },
];

// ============================================
// Detailed Urinary System
// ============================================

export const DETAILED_URINARY: AnatomicalStructure[] = [
  {
    id: "renalCortex",
    name: "Renal Cortex",
    latinName: "Cortex Renalis",
    parentId: "leftKidney",
    system: "urinary",
    geometry: "capsule",
    position: [-0.15, 0, -0.05],
    scale: [1.05, 1.05, 1.05],
    geometryArgs: [0.038, 0.075, 16, 16],
    color: "#a00000",
    roughness: 0.55,
    opacity: 0.7,
    visibility: { structureId: "renalCortex", minDetailLevel: "body" },
    description: "Outer layer of kidney",
    clickable: true,
  },
  {
    id: "renalMedulla",
    name: "Renal Medulla",
    latinName: "Medulla Renalis",
    parentId: "leftKidney",
    system: "urinary",
    geometry: "capsule",
    position: [-0.15, 0, -0.05],
    scale: [0.7, 0.7, 0.7],
    geometryArgs: [0.025, 0.05, 16, 16],
    color: "#700000",
    roughness: 0.55,
    visibility: { structureId: "renalMedulla", minDetailLevel: "body" },
    description: "Inner layer of kidney",
    clickable: true,
  },
  {
    id: "renalPelvis",
    name: "Renal Pelvis",
    latinName: "Pelvis Renalis",
    parentId: "leftKidney",
    system: "urinary",
    geometry: "capsule",
    position: [-0.15, -0.03, -0.02],
    geometryArgs: [0.015, 0.025, 16, 16],
    color: "#b05050",
    roughness: 0.55,
    visibility: { structureId: "renalPelvis", minDetailLevel: "body" },
    description: "Funnel for urine collection",
    clickable: true,
  },
  {
    id: "nephron",
    name: "Nephron",
    latinName: "Nephron",
    system: "urinary",
    geometry: "sphere",
    position: [-0.15, 0, -0.05],
    scale: [0.5, 0.5, 0.5],
    geometryArgs: [0.015, 16, 16],
    color: "#900000",
    roughness: 0.5,
    opacity: 0.5,
    visibility: { structureId: "nephron", minDetailLevel: "organ" },
    description: "Functional unit of kidney",
    clickable: true,
  },
  {
    id: "urethra",
    name: "Urethra",
    latinName: "Urethra",
    system: "urinary",
    geometry: "cylinder",
    position: [0, -0.55, 0.08],
    rotation: [0.3, 0, 0],
    geometryArgs: [0.01, 0.01, 0.15, 16],
    color: "#ddaaee",
    roughness: 0.65,
    visibility: { structureId: "urethra", minDetailLevel: "body" },
    description: "Tube for urine expulsion",
    clickable: true,
  },
];

// ============================================
// Detailed Endocrine System
// ============================================

export const DETAILED_ENDOCRINE: AnatomicalStructure[] = [
  {
    id: "pinealGland",
    name: "Pineal Gland",
    latinName: "Glandula Pinealis",
    system: "endocrine",
    geometry: "sphere",
    position: [0, 1.28, 0.02],
    geometryArgs: [0.012, 16, 16],
    color: "#e8a0a0",
    roughness: 0.6,
    visibility: { structureId: "pinealGland", minDetailLevel: "body" },
    description: "Produces melatonin",
    clickable: true,
  },
  {
    id: "parathyroidGlands",
    name: "Parathyroid Glands",
    latinName: "Glandulae Parathyroideae",
    system: "endocrine",
    geometry: "sphere",
    position: [0.01, 0.96, 0.08],
    geometryArgs: [0.008, 16, 16],
    color: "#ff8844",
    roughness: 0.55,
    visibility: { structureId: "parathyroidGlands", minDetailLevel: "body" },
    description: "Calcium regulation",
    clickable: true,
  },
  {
    id: "thymusGland",
    name: "Thymus",
    latinName: "Thymus",
    system: "endocrine",
    geometry: "capsule",
    position: [0, 0.75, 0.12],
    scale: [1.5, 0.8, 0.6],
    geometryArgs: [0.04, 0.06, 16, 16],
    color: "#ffcccc",
    roughness: 0.75,
    visibility: { structureId: "thymusGland", minDetailLevel: "body" },
    description: "Immune system development",
    clickable: true,
  },
  {
    id: "isletsOfLangerhans",
    name: "Islets of Langerhans",
    latinName: "Insulae Pancreaticae",
    parentId: "pancreas",
    system: "endocrine",
    geometry: "sphere",
    position: [0, 0.05, 0.02],
    scale: [0.4, 0.4, 0.4],
    geometryArgs: [0.015, 16, 16],
    color: "#ffcc00",
    roughness: 0.7,
    opacity: 0.5,
    visibility: { structureId: "isletsOfLangerhans", minDetailLevel: "organ" },
    description: "Produces insulin and glucagon",
    clickable: true,
  },
  {
    id: "adrenalMedulla",
    name: "Adrenal Medulla",
    latinName: "Medulla Glandulae Suprarenalis",
    parentId: "leftAdrenalGland",
    system: "endocrine",
    geometry: "sphere",
    position: [-0.15, 0.08, -0.02],
    scale: [0.5, 0.8, 0.5],
    geometryArgs: [0.012, 16, 16],
    color: "#ffdd44",
    roughness: 0.6,
    visibility: { structureId: "adrenalMedulla", minDetailLevel: "body" },
    description: "Produces adrenaline",
    clickable: true,
  },
];

// ============================================
// Detailed Lymphatic System
// ============================================

export const DETAILED_LYMPHATIC: AnatomicalStructure[] = [
  {
    id: "cervicalNodes",
    name: "Cervical Lymph Nodes",
    latinName: "Nodi Lymphatici Cervicales",
    system: "lymphatic",
    geometry: "sphere",
    position: [0.08, 1.05, 0.05],
    geometryArgs: [0.02, 16, 16],
    color: "#c0a0a0",
    roughness: 0.7,
    visibility: { structureId: "cervicalNodes", minDetailLevel: "body" },
    description: "Neck lymph nodes",
    clickable: true,
  },
  {
    id: "axillaryNodes",
    name: "Axillary Lymph Nodes",
    latinName: "Nodi Lymphatici Axillares",
    system: "lymphatic",
    geometry: "sphere",
    position: [0.20, 0.55, 0.05],
    geometryArgs: [0.025, 16, 16],
    color: "#c0a0a0",
    roughness: 0.7,
    visibility: { structureId: "axillaryNodes", minDetailLevel: "body" },
    description: "Armpit lymph nodes",
    clickable: true,
  },
  {
    id: "inguinalNodes",
    name: "Inguinal Lymph Nodes",
    latinName: "Nodi Lymphatici Inguinales",
    system: "lymphatic",
    geometry: "sphere",
    position: [0.10, -0.50, 0.05],
    geometryArgs: [0.025, 16, 16],
    color: "#c0a0a0",
    roughness: 0.7,
    visibility: { structureId: "inguinalNodes", minDetailLevel: "body" },
    description: "Groin lymph nodes",
    clickable: true,
  },
  {
    id: "thoracicDuct",
    name: "Thoracic Duct",
    latinName: "Ductus Thoracicus",
    system: "lymphatic",
    geometry: "cylinder",
    position: [0.02, 0.30, -0.08],
    rotation: [0.3, 0, 0],
    geometryArgs: [0.008, 0.008, 0.60, 16],
    color: "#ffcccc",
    roughness: 0.65,
    opacity: 0.6,
    visibility: { structureId: "thoracicDuct", minDetailLevel: "body" },
    description: "Main lymphatic vessel",
    clickable: true,
  },
  {
    id: "lymphaticVessels",
    name: "Lymphatic Vessels",
    latinName: "Vasa Lymphatica",
    system: "lymphatic",
    geometry: "cylinder",
    position: [0.15, 0.40, 0.05],
    rotation: [0, 0, 0.5],
    geometryArgs: [0.006, 0.006, 0.30, 16],
    color: "#ffdddd",
    roughness: 0.7,
    opacity: 0.5,
    visibility: { structureId: "lymphaticVessels", minDetailLevel: "body" },
    description: "Network of lymph vessels",
    clickable: true,
  },
];

// ============================================
// All Detailed Structures
// ============================================

export const ALL_DETAILED_STRUCTURES: AnatomicalStructure[] = [
  ...DETAILED_CARDIOVASCULAR,
  ...DETAILED_RESPIRATORY,
  ...DETAILED_DIGESTIVE,
  ...DETAILED_NERVOUS,
  ...DETAILED_URINARY,
  ...DETAILED_ENDOCRINE,
  ...DETAILED_LYMPHATIC,
];

export default ALL_DETAILED_STRUCTURES;
