/**
 * Physiology Question Bank
 *
 * 150+ questions on cellular, organ system, and integrative physiology.
 */

import type { QuizQuestion } from './types';

export const physiologyQuestions: QuizQuestion[] = [
  // CELLULAR PHYSIOLOGY
  {
    questionId: 'phys-cell-001',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'nervous',
    difficulty: 1,
    questionText: 'Which ion is most abundant inside cells?',
    choices: [
      { choiceId: 'a', text: 'Potassium (K+)', isCorrect: true, explanation: 'K+ is the main intracellular cation (~140 mEq/L).' },
      { choiceId: 'b', text: 'Sodium (Na+)', isCorrect: false, explanation: 'Na+ is the main extracellular cation (~140 mEq/L).' },
      { choiceId: 'c', text: 'Calcium (Ca2+)', isCorrect: false, explanation: 'Intracellular Ca2+ is very low (~0.0001 mM).' },
      { choiceId: 'd', text: 'Chloride (Cl-)', isCorrect: false, explanation: 'Cl- is mainly extracellular.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'K+ is the main intracellular cation.',
      detailed: 'The Na+/K+-ATPase pumps 3 Na+ out and 2 K+ in, maintaining high intracellular K+ (~140 mEq/L) and low intracellular Na+ (~10 mEq/L). This gradient is essential for the resting membrane potential.',
      clinicalRelevance: 'Hyperkalemia causes cardiac arrhythmias. Hypokalemia causes muscle weakness and arrhythmias.',
      relatedConcepts: ['membrane potential', 'Na/K-ATPase', 'electrolytes'],
    },
    tags: ['electrolytes', 'cell', 'beginner'],
    relatedTopicIds: ['cell-physiology', 'electrolyte-balance'],
  },
  {
    questionId: 'phys-cell-002',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'nervous',
    difficulty: 2,
    questionText: 'What is the normal resting membrane potential of a typical neuron?',
    choices: [
      { choiceId: 'a', text: '-70 mV', isCorrect: true, explanation: 'Resting neurons are about -70 mV (inside negative).' },
      { choiceId: 'b', text: '+40 mV', isCorrect: false, explanation: '+40 mV is near the peak of an action potential.' },
      { choiceId: 'c', text: '0 mV', isCorrect: false, explanation: '0 mV would indicate equal ion distribution.' },
      { choiceId: 'd', text: '-90 mV', isCorrect: false, explanation: '-90 mV is closer to the K+ equilibrium potential.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Normal resting membrane potential is about -70 mV.',
      detailed: 'The resting potential is determined primarily by K+ permeability through leak channels. It is closer to EK (-90 mV) than ENa (+60 mV) because the membrane is ~40x more permeable to K+ at rest.',
      clinicalRelevance: 'Depolarization (less negative) increases excitability. Local anesthetics block Na+ channels, preventing depolarization.',
      relatedConcepts: ['action potential', 'ion channels', 'Nernst equation'],
    },
    tags: ['membrane', 'neuron', 'intermediate'],
    relatedTopicIds: ['neurophysiology', 'membrane-potential'],
  },
  {
    questionId: 'phys-cell-003',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'nervous',
    difficulty: 3,
    questionText: 'During an action potential, which channel opens first to cause depolarization?',
    choices: [
      { choiceId: 'a', text: 'Voltage-gated Na+ channels', isCorrect: true, explanation: 'Na+ influx causes the rapid depolarization phase.' },
      { choiceId: 'b', text: 'Voltage-gated K+ channels', isCorrect: false, explanation: 'K+ channels open later to cause repolarization.' },
      { choiceId: 'c', text: 'Voltage-gated Ca2+ channels', isCorrect: false, explanation: 'Ca2+ channels are important in cardiac and smooth muscle.' },
      { choiceId: 'd', text: 'Ligand-gated Cl- channels', isCorrect: false, explanation: 'Cl- channels are important for inhibition, not action potentials.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Voltage-gated Na+ channels open first for depolarization.',
      detailed: 'When threshold (~-55 mV) is reached, voltage-gated Na+ channels rapidly open (0.1 ms). Na+ rushes in, depolarizing the membrane toward ENa (+60 mV). The Na+ channels then inactivate within 1 ms.',
      clinicalRelevance: 'Tetrodotoxin (pufferfish) blocks Na+ channels. Lidocaine is a use-dependent Na+ channel blocker used as local anesthetic.',
      relatedConcepts: ['action potential phases', 'Na+ channel inactivation', 'refractory period'],
    },
    tags: ['channels', 'action-potential', 'advanced'],
    relatedTopicIds: ['neurophysiology', 'ion-channels'],
  },
  {
    questionId: 'phys-cell-004',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'nervous',
    difficulty: 2,
    questionText: 'Which type of transport requires ATP?',
    choices: [
      { choiceId: 'a', text: 'Primary active transport', isCorrect: true, explanation: 'Primary active transport uses ATP directly (e.g., Na/K-ATPase).' },
      { choiceId: 'b', text: 'Facilitated diffusion', isCorrect: false, explanation: 'Facilitated diffusion uses carriers but no energy.' },
      { choiceId: 'c', text: 'Simple diffusion', isCorrect: false, explanation: 'Simple diffusion requires no carriers or energy.' },
      { choiceId: 'd', text: 'Osmosis', isCorrect: false, explanation: 'Osmosis is passive water movement.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Primary active transport uses ATP directly.',
      detailed: 'Primary active transport uses ATP hydrolysis to move substances against their concentration gradient. Examples: Na+/K+-ATPase, Ca2+-ATPase, H+/K+-ATPase, H+-ATPase.',
      clinicalRelevance: 'Digoxin inhibits Na+/K+-ATPase. Proton pump inhibitors block H+/K+-ATPase in stomach.',
      relatedConcepts: ['secondary active transport', 'membrane transport', 'ATPases'],
    },
    tags: ['transport', 'ATP', 'intermediate'],
    relatedTopicIds: ['membrane-transport', 'cellular-energetics'],
  },

  // CARDIOVASCULAR PHYSIOLOGY
  {
    questionId: 'phys-cv-001',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'cardiovascular',
    difficulty: 1,
    questionText: 'What is normal cardiac output at rest?',
    choices: [
      { choiceId: 'a', text: '5 L/min', isCorrect: true, explanation: 'CO = HR (70) x SV (70 mL) = ~5 L/min.' },
      { choiceId: 'b', text: '1 L/min', isCorrect: false, explanation: '1 L/min would indicate severe heart failure.' },
      { choiceId: 'c', text: '10 L/min', isCorrect: false, explanation: '10 L/min occurs during moderate exercise.' },
      { choiceId: 'd', text: '25 L/min', isCorrect: false, explanation: '25 L/min is near maximal during intense exercise.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Normal resting cardiac output is ~5 L/min.',
      detailed: 'Cardiac Output = Heart Rate x Stroke Volume. At rest: ~70 bpm x ~70 mL = 4.9 L/min. During exercise, CO can increase to 20-25 L/min in trained athletes.',
      clinicalRelevance: 'Cardiac output decreases in heart failure. Low CO causes fatigue, confusion, and organ hypoperfusion.',
      relatedConcepts: ['stroke volume', 'heart rate', 'exercise physiology'],
    },
    tags: ['cardiac-output', 'beginner'],
    relatedTopicIds: ['cardiac-physiology', 'hemodynamics'],
  },
  {
    questionId: 'phys-cv-002',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'cardiovascular',
    difficulty: 2,
    questionText: 'Which factor primarily determines stroke volume?',
    choices: [
      { choiceId: 'a', text: 'Preload, afterload, and contractility', isCorrect: true, explanation: 'All three factors determine stroke volume.' },
      { choiceId: 'b', text: 'Heart rate only', isCorrect: false, explanation: 'Heart rate affects cardiac output but not directly stroke volume.' },
      { choiceId: 'c', text: 'Blood pressure only', isCorrect: false, explanation: 'BP reflects CO x TPR, but does not solely determine SV.' },
      { choiceId: 'd', text: 'Respiratory rate', isCorrect: false, explanation: 'Respiratory rate affects venous return but not directly SV.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Stroke volume depends on preload, afterload, and contractility.',
      detailed: 'Preload (end-diastolic volume) stretches myocytes (Frank-Starling). Afterload (aortic pressure) opposes ejection. Contractility (inotropy) affects force generation independent of loading conditions.',
      clinicalRelevance: 'Heart failure treatment targets all three: diuretics reduce preload, vasodilators reduce afterload, inotropes increase contractility.',
      relatedConcepts: ['Frank-Starling', 'cardiac function', 'heart failure'],
    },
    tags: ['stroke-volume', 'hemodynamics', 'intermediate'],
    relatedTopicIds: ['cardiac-physiology', 'heart-failure'],
  },
  {
    questionId: 'phys-cv-003',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'cardiovascular',
    difficulty: 3,
    questionText: 'The "a" wave on a jugular venous pulse tracing represents:',
    choices: [
      { choiceId: 'a', text: 'Atrial contraction', isCorrect: true, explanation: '"a" wave = atrial contraction pushing blood back into veins.' },
      { choiceId: 'b', text: 'Ventricular contraction', isCorrect: false, explanation: 'Ventricular contraction causes the "c" wave.' },
      { choiceId: 'c', text: 'Tricuspid valve opening', isCorrect: false, explanation: 'Tricuspid opening causes the "y" descent.' },
      { choiceId: 'd', text: 'Atrial relaxation', isCorrect: false, explanation: 'Atrial relaxation contributes to "x" descent.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: '"a" wave = atrial contraction.',
      detailed: 'JVP waves: a = atrial contraction, c = carotid transmission/tricuspid bulging, v = venous filling during ventricular systole. Descents: x = atrial relaxation, y = tricuspid opening.',
      clinicalRelevance: 'Giant "a" waves occur in tricuspid stenosis or complete heart block. Cannon "a" waves occur when atria contract against closed tricuspid (as in complete AV block).',
      mnemonicTip: '"a" = Atrial contraction',
      relatedConcepts: ['cardiac cycle', 'venous pressure', 'JVP examination'],
    },
    tags: ['JVP', 'cardiac-cycle', 'advanced'],
    relatedTopicIds: ['cardiac-physiology', 'physical-examination'],
  },
  {
    questionId: 'phys-cv-004',
    domain: 'physiology',
    type: 'calculation',
    format: 'multiple-choice',
    system: 'cardiovascular',
    difficulty: 2,
    questionText: 'If mean arterial pressure is 90 mmHg and cardiac output is 5 L/min, what is total peripheral resistance?',
    choices: [
      { choiceId: 'a', text: '18 mmHg/(L/min) or ~1440 dynes-s/cm5', isCorrect: true, explanation: 'TPR = MAP/CO = 90/5 = 18 PRU.' },
      { choiceId: 'b', text: '450 mmHg/(L/min)', isCorrect: false, explanation: 'This would be MAP x CO, not MAP/CO.' },
      { choiceId: 'c', text: '0.055 mmHg/(L/min)', isCorrect: false, explanation: 'This would be CO/MAP.' },
      { choiceId: 'd', text: '95 mmHg/(L/min)', isCorrect: false, explanation: 'This calculation is incorrect.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'TPR = MAP/CO = 90/5 = 18 PRU.',
      detailed: 'The relationship is: MAP = CO x TPR. Rearranged: TPR = MAP/CO. In clinical units (PRU), normal TPR is 15-20. In physics units: multiply by 80 to get dynes-s/cm5 (normal ~1200-1500).',
      clinicalRelevance: 'Elevated TPR indicates vasoconstriction (e.g., essential hypertension). Vasodilators decrease TPR to lower blood pressure.',
      relatedConcepts: ['blood pressure', 'vascular resistance', 'hemodynamics'],
    },
    tags: ['hemodynamics', 'calculation', 'intermediate'],
    relatedTopicIds: ['cardiovascular-calculations', 'blood-pressure-regulation'],
  },
  {
    questionId: 'phys-cv-005',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'cardiovascular',
    difficulty: 3,
    questionText: 'What causes the dicrotic notch on an arterial pressure waveform?',
    choices: [
      { choiceId: 'a', text: 'Closure of the aortic valve', isCorrect: true, explanation: 'Aortic valve closure causes brief pressure rise (dicrotic notch).' },
      { choiceId: 'b', text: 'Closure of the mitral valve', isCorrect: false, explanation: 'Mitral closure causes S1, occurs earlier.' },
      { choiceId: 'c', text: 'Peak ventricular ejection', isCorrect: false, explanation: 'Peak ejection causes the systolic peak.' },
      { choiceId: 'd', text: 'Atrial contraction', isCorrect: false, explanation: 'Atrial contraction causes the "a" wave.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Dicrotic notch = aortic valve closure.',
      detailed: 'As ventricular pressure falls below aortic pressure, blood briefly flows backward, closing the aortic valve. This causes a small pressure rise (dicrotic notch or incisura). It marks the end of systole.',
      clinicalRelevance: 'Absent dicrotic notch suggests severe aortic regurgitation. Prominent dicrotic notch can occur with low peripheral resistance.',
      relatedConcepts: ['arterial waveform', 'cardiac cycle', 'aortic valve'],
    },
    tags: ['waveforms', 'aortic-valve', 'advanced'],
    relatedTopicIds: ['arterial-physiology', 'cardiac-cycle'],
  },

  // RESPIRATORY PHYSIOLOGY
  {
    questionId: 'phys-resp-001',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'respiratory',
    difficulty: 1,
    questionText: 'What is the normal partial pressure of oxygen (PaO2) in arterial blood?',
    choices: [
      { choiceId: 'a', text: '80-100 mmHg', isCorrect: true, explanation: 'Normal PaO2 is 80-100 mmHg at sea level.' },
      { choiceId: 'b', text: '40 mmHg', isCorrect: false, explanation: '40 mmHg is normal mixed venous PO2.' },
      { choiceId: 'c', text: '160 mmHg', isCorrect: false, explanation: '160 mmHg is atmospheric PO2 (21% of 760).' },
      { choiceId: 'd', text: '35-45 mmHg', isCorrect: false, explanation: 'This is the normal range for PaCO2.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Normal arterial PaO2 is 80-100 mmHg.',
      detailed: 'Inspired air has PO2 of ~160 mmHg. Alveolar PO2 is ~100 mmHg after humidification and CO2 exchange. Arterial PO2 is slightly lower due to V/Q mismatch and shunt.',
      clinicalRelevance: 'PaO2 <60 mmHg defines hypoxemia. This corresponds to ~90% SaO2 on the oxyhemoglobin curve (steep portion).',
      relatedConcepts: ['oxygenation', 'A-a gradient', 'hypoxemia'],
    },
    tags: ['oxygenation', 'ABG', 'beginner'],
    relatedTopicIds: ['gas-exchange', 'arterial-blood-gas'],
  },
  {
    questionId: 'phys-resp-002',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'respiratory',
    difficulty: 2,
    questionText: 'Which factor shifts the oxygen-hemoglobin dissociation curve to the RIGHT?',
    choices: [
      { choiceId: 'a', text: 'Increased temperature', isCorrect: true, explanation: 'Fever shifts curve right, facilitating O2 unloading.' },
      { choiceId: 'b', text: 'Increased pH (alkalosis)', isCorrect: false, explanation: 'Alkalosis shifts curve LEFT (Bohr effect).' },
      { choiceId: 'c', text: 'Decreased 2,3-BPG', isCorrect: false, explanation: 'Decreased 2,3-BPG shifts curve LEFT.' },
      { choiceId: 'd', text: 'Carbon monoxide', isCorrect: false, explanation: 'CO shifts curve LEFT and reduces carrying capacity.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Increased temperature shifts the curve RIGHT.',
      detailed: 'Right shift (decreased affinity, enhanced O2 release): increased temperature, increased H+ (low pH), increased CO2, increased 2,3-BPG. Remember: exercising tissues need more O2.',
      clinicalRelevance: 'Right shift helps unload O2 to metabolizing tissues. Left shift (fetal Hb, stored blood) impairs O2 delivery.',
      mnemonicTip: '"CADET, face RIGHT!" - CO2, Acid, 2,3-DPG, Exercise, Temperature',
      relatedConcepts: ['Bohr effect', 'oxygen transport', 'hemoglobin'],
    },
    tags: ['hemoglobin', 'oxygen-transport', 'intermediate'],
    relatedTopicIds: ['oxygen-hemoglobin-curve', 'gas-transport'],
  },
  {
    questionId: 'phys-resp-003',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'respiratory',
    difficulty: 2,
    questionText: 'The primary stimulus for normal ventilatory drive is:',
    choices: [
      { choiceId: 'a', text: 'Arterial CO2 (via central chemoreceptors)', isCorrect: true, explanation: 'Central chemoreceptors respond to CSF pH changes from CO2.' },
      { choiceId: 'b', text: 'Arterial O2 (via peripheral chemoreceptors)', isCorrect: false, explanation: 'O2 becomes primary driver only when very low (<60 mmHg).' },
      { choiceId: 'c', text: 'Blood pressure', isCorrect: false, explanation: 'Baroreceptors affect circulation, not primary ventilation.' },
      { choiceId: 'd', text: 'Body temperature', isCorrect: false, explanation: 'Temperature affects ventilation but is not primary driver.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'CO2 (via central chemoreceptors) is the primary ventilatory stimulus.',
      detailed: 'Central chemoreceptors in the medulla respond to H+ in CSF. CO2 freely crosses the blood-brain barrier and forms H+ via carbonic anhydrase. This is the primary drive. Peripheral chemoreceptors (carotid bodies) respond to hypoxia.',
      clinicalRelevance: 'COPD patients may rely on hypoxic drive. High-flow O2 can suppress breathing in these patients.',
      relatedConcepts: ['respiratory control', 'chemoreceptors', 'COPD'],
    },
    tags: ['respiratory-control', 'chemoreceptors', 'intermediate'],
    relatedTopicIds: ['breathing-regulation', 'chemoreceptors'],
  },
  {
    questionId: 'phys-resp-004',
    domain: 'physiology',
    type: 'calculation',
    format: 'multiple-choice',
    system: 'respiratory',
    difficulty: 3,
    questionText: 'What is the normal alveolar-arterial (A-a) oxygen gradient?',
    choices: [
      { choiceId: 'a', text: '5-15 mmHg (increases with age)', isCorrect: true, explanation: 'A-a gradient = ~2.5 + (age/4), normal <15 in young adults.' },
      { choiceId: 'b', text: '0 mmHg', isCorrect: false, explanation: 'Perfect gas exchange would give 0, but V/Q mismatch exists.' },
      { choiceId: 'c', text: '50 mmHg', isCorrect: false, explanation: '50 mmHg indicates significant gas exchange problem.' },
      { choiceId: 'd', text: '100 mmHg', isCorrect: false, explanation: 'This is the normal alveolar PO2, not the gradient.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Normal A-a gradient is 5-15 mmHg.',
      detailed: 'A-a gradient = PAO2 - PaO2. PAO2 = (FiO2)(Patm-47) - (PaCO2/0.8). Normal gradient exists due to physiologic shunt and V/Q mismatch. Increases ~1 mmHg per decade of age.',
      clinicalRelevance: 'Elevated A-a gradient indicates V/Q mismatch, shunt, or diffusion limitation. Normal A-a gradient with hypoxemia suggests hypoventilation.',
      relatedConcepts: ['gas exchange', 'V/Q mismatch', 'shunt'],
    },
    tags: ['A-a-gradient', 'calculation', 'advanced'],
    relatedTopicIds: ['gas-exchange', 'hypoxemia-workup'],
  },
  {
    questionId: 'phys-resp-005',
    domain: 'physiology',
    type: 'homeostasis',
    format: 'multiple-choice',
    system: 'respiratory',
    difficulty: 2,
    questionText: 'What is the role of surfactant in the lungs?',
    choices: [
      { choiceId: 'a', text: 'Reduce surface tension in alveoli', isCorrect: true, explanation: 'Surfactant prevents alveolar collapse by reducing surface tension.' },
      { choiceId: 'b', text: 'Transport oxygen to blood', isCorrect: false, explanation: 'Hemoglobin transports oxygen.' },
      { choiceId: 'c', text: 'Kill bacteria in airways', isCorrect: false, explanation: 'Surfactant has some antimicrobial effects but this is not its primary role.' },
      { choiceId: 'd', text: 'Produce mucus', isCorrect: false, explanation: 'Goblet cells produce mucus.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Surfactant reduces alveolar surface tension.',
      detailed: 'Surfactant (mainly DPPC) forms a monolayer at the air-water interface, reducing surface tension according to the Law of LaPlace. This prevents smaller alveoli from collapsing into larger ones.',
      clinicalRelevance: 'Premature infants lack surfactant (NRDS). Exogenous surfactant is given as treatment. ARDS involves surfactant dysfunction.',
      relatedConcepts: ['alveolar mechanics', 'NRDS', 'type II pneumocytes'],
    },
    tags: ['surfactant', 'lung-mechanics', 'intermediate'],
    relatedTopicIds: ['lung-physiology', 'neonatal-respiratory-distress'],
  },

  // RENAL PHYSIOLOGY
  {
    questionId: 'phys-renal-001',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'urinary',
    difficulty: 1,
    questionText: 'What is the normal glomerular filtration rate (GFR)?',
    choices: [
      { choiceId: 'a', text: '~120 mL/min (180 L/day)', isCorrect: true, explanation: 'Normal GFR is ~120 mL/min in healthy adults.' },
      { choiceId: 'b', text: '~1 mL/min', isCorrect: false, explanation: '1 mL/min is approximately urine output, not GFR.' },
      { choiceId: 'c', text: '~1000 mL/min', isCorrect: false, explanation: 'This would be close to total renal blood flow.' },
      { choiceId: 'd', text: '~10 mL/min', isCorrect: false, explanation: '10 mL/min indicates severe kidney disease (CKD stage 5).' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Normal GFR is ~120 mL/min.',
      detailed: 'The kidneys filter ~180 L/day but produce only ~1.5 L urine because 99% is reabsorbed. GFR is estimated clinically using creatinine and formulas like CKD-EPI.',
      clinicalRelevance: 'GFR <60 mL/min for >3 months defines CKD. GFR <15 mL/min is kidney failure (CKD stage 5).',
      relatedConcepts: ['nephron function', 'creatinine clearance', 'CKD staging'],
    },
    tags: ['GFR', 'kidney', 'beginner'],
    relatedTopicIds: ['renal-physiology', 'kidney-function'],
  },
  {
    questionId: 'phys-renal-002',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'urinary',
    difficulty: 2,
    questionText: 'Most filtered glucose is reabsorbed in which segment of the nephron?',
    choices: [
      { choiceId: 'a', text: 'Proximal convoluted tubule', isCorrect: true, explanation: 'PCT reabsorbs 100% of filtered glucose via SGLT2 and SGLT1.' },
      { choiceId: 'b', text: 'Loop of Henle', isCorrect: false, explanation: 'Loop primarily handles salt and water.' },
      { choiceId: 'c', text: 'Distal convoluted tubule', isCorrect: false, explanation: 'DCT fine-tunes Na, Ca, and Mg.' },
      { choiceId: 'd', text: 'Collecting duct', isCorrect: false, explanation: 'Collecting duct adjusts final urine concentration.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'PCT reabsorbs all filtered glucose.',
      detailed: 'SGLT2 (low affinity, high capacity) in early PCT reabsorbs 90% of glucose. SGLT1 (high affinity, low capacity) in late PCT reabsorbs remaining 10%. Glucose appears in urine when plasma exceeds Tm (~180 mg/dL).',
      clinicalRelevance: 'SGLT2 inhibitors (empagliflozin, dapagliflozin) cause glucosuria and are used for diabetes and heart failure.',
      relatedConcepts: ['glucose handling', 'SGLT2 inhibitors', 'diabetes'],
    },
    tags: ['glucose', 'PCT', 'intermediate'],
    relatedTopicIds: ['tubular-function', 'diabetes-treatment'],
  },
  {
    questionId: 'phys-renal-003',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'urinary',
    difficulty: 2,
    questionText: 'ADH (vasopressin) acts primarily on which part of the nephron?',
    choices: [
      { choiceId: 'a', text: 'Collecting duct', isCorrect: true, explanation: 'ADH inserts aquaporin-2 channels in collecting duct for water reabsorption.' },
      { choiceId: 'b', text: 'Proximal tubule', isCorrect: false, explanation: 'PT reabsorbs water obligatorily, not regulated by ADH.' },
      { choiceId: 'c', text: 'Thick ascending limb', isCorrect: false, explanation: 'TAL is impermeable to water.' },
      { choiceId: 'd', text: 'Glomerulus', isCorrect: false, explanation: 'Glomerulus is for filtration, not ADH action.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'ADH acts on collecting duct to increase water reabsorption.',
      detailed: 'ADH binds V2 receptors on principal cells, triggering cAMP cascade that inserts aquaporin-2 water channels into the apical membrane. This allows water to follow the medullary osmotic gradient.',
      clinicalRelevance: 'Diabetes insipidus (central or nephrogenic) causes dilute urine despite high osmolality. SIADH causes water retention and hyponatremia.',
      relatedConcepts: ['water balance', 'diabetes insipidus', 'SIADH'],
    },
    tags: ['ADH', 'water-balance', 'intermediate'],
    relatedTopicIds: ['water-regulation', 'sodium-balance'],
  },
  {
    questionId: 'phys-renal-004',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'urinary',
    difficulty: 3,
    questionText: 'Aldosterone increases reabsorption of which ion?',
    choices: [
      { choiceId: 'a', text: 'Sodium', isCorrect: true, explanation: 'Aldosterone increases ENaC expression for Na+ reabsorption.' },
      { choiceId: 'b', text: 'Calcium', isCorrect: false, explanation: 'PTH and vitamin D regulate calcium.' },
      { choiceId: 'c', text: 'Phosphate', isCorrect: false, explanation: 'PTH and FGF23 regulate phosphate.' },
      { choiceId: 'd', text: 'Bicarbonate', isCorrect: false, explanation: 'Bicarbonate is regulated by acid-base mechanisms.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Aldosterone increases sodium reabsorption.',
      detailed: 'Aldosterone (from adrenal zona glomerulosa) acts on principal cells of collecting duct. It increases expression of ENaC (Na+ channels) and Na+/K+-ATPase, enhancing Na+ reabsorption and K+ secretion.',
      clinicalRelevance: 'Hyperaldosteronism causes hypertension and hypokalemia. Spironolactone blocks aldosterone receptor.',
      relatedConcepts: ['RAAS', 'potassium balance', 'hypertension'],
    },
    tags: ['aldosterone', 'sodium', 'advanced'],
    relatedTopicIds: ['RAAS', 'electrolyte-balance'],
  },

  // GASTROINTESTINAL PHYSIOLOGY
  {
    questionId: 'phys-gi-001',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'digestive',
    difficulty: 1,
    questionText: 'Which enzyme initiates starch digestion in the mouth?',
    choices: [
      { choiceId: 'a', text: 'Salivary amylase', isCorrect: true, explanation: 'Salivary amylase (ptyalin) breaks alpha-1,4 glycosidic bonds.' },
      { choiceId: 'b', text: 'Pepsin', isCorrect: false, explanation: 'Pepsin digests protein in stomach.' },
      { choiceId: 'c', text: 'Lipase', isCorrect: false, explanation: 'Lingual lipase starts fat digestion but is minimal.' },
      { choiceId: 'd', text: 'Trypsin', isCorrect: false, explanation: 'Trypsin is a pancreatic enzyme.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Salivary amylase begins starch digestion.',
      detailed: 'Salivary amylase is secreted by salivary glands and cleaves starch into maltose and maltotriose. It is inactivated by gastric acid. Pancreatic amylase continues digestion in the small intestine.',
      clinicalRelevance: 'Elevated serum amylase suggests pancreatitis or salivary gland disease. Amylase is used in clinical diagnostics.',
      relatedConcepts: ['carbohydrate digestion', 'salivary glands', 'enzymes'],
    },
    tags: ['digestion', 'enzymes', 'beginner'],
    relatedTopicIds: ['carbohydrate-digestion', 'salivary-function'],
  },
  {
    questionId: 'phys-gi-002',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'digestive',
    difficulty: 2,
    questionText: 'Which hormone stimulates gastric acid secretion?',
    choices: [
      { choiceId: 'a', text: 'Gastrin', isCorrect: true, explanation: 'Gastrin from G cells stimulates parietal cells.' },
      { choiceId: 'b', text: 'Secretin', isCorrect: false, explanation: 'Secretin inhibits gastric acid and stimulates pancreatic HCO3-.' },
      { choiceId: 'c', text: 'Cholecystokinin (CCK)', isCorrect: false, explanation: 'CCK stimulates gallbladder contraction and pancreatic enzymes.' },
      { choiceId: 'd', text: 'Somatostatin', isCorrect: false, explanation: 'Somatostatin inhibits gastric acid secretion.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Gastrin stimulates gastric acid secretion.',
      detailed: 'Gastrin is released from antral G cells in response to stomach distension, peptides, and vagal stimulation. It binds CCK-B receptors on parietal cells and ECL cells (which release histamine).',
      clinicalRelevance: 'Zollinger-Ellison syndrome (gastrinoma) causes severe acid hypersecretion and ulcers. Gastrin levels are elevated with PPI use.',
      relatedConcepts: ['gastric acid regulation', 'peptic ulcer disease', 'gastrinoma'],
    },
    tags: ['gastrin', 'acid-secretion', 'intermediate'],
    relatedTopicIds: ['gastric-physiology', 'GI-hormones'],
  },
  {
    questionId: 'phys-gi-003',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'digestive',
    difficulty: 2,
    questionText: 'Where is vitamin B12 absorbed?',
    choices: [
      { choiceId: 'a', text: 'Terminal ileum', isCorrect: true, explanation: 'B12-intrinsic factor complex is absorbed in terminal ileum.' },
      { choiceId: 'b', text: 'Stomach', isCorrect: false, explanation: 'Stomach releases B12 from food and provides intrinsic factor.' },
      { choiceId: 'c', text: 'Duodenum', isCorrect: false, explanation: 'Duodenum absorbs iron and calcium, not B12.' },
      { choiceId: 'd', text: 'Colon', isCorrect: false, explanation: 'Colon absorbs water and electrolytes.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'B12 is absorbed in the terminal ileum.',
      detailed: 'B12 binds intrinsic factor (from parietal cells) in the stomach. The B12-IF complex travels to the terminal ileum where it binds cubilin receptors for receptor-mediated endocytosis.',
      clinicalRelevance: 'Crohn disease or resection of terminal ileum causes B12 deficiency. Pernicious anemia lacks IF.',
      relatedConcepts: ['B12 metabolism', 'pernicious anemia', 'malabsorption'],
    },
    tags: ['B12', 'absorption', 'intermediate'],
    relatedTopicIds: ['vitamin-absorption', 'ileal-function'],
  },
  {
    questionId: 'phys-gi-004',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'digestive',
    difficulty: 3,
    questionText: 'The enterohepatic circulation primarily involves:',
    choices: [
      { choiceId: 'a', text: 'Bile acids', isCorrect: true, explanation: 'Bile acids are reabsorbed in ileum and recycled 6-8x/day.' },
      { choiceId: 'b', text: 'Glucose', isCorrect: false, explanation: 'Glucose goes to liver via portal vein but is not enterohepatic.' },
      { choiceId: 'c', text: 'Amino acids', isCorrect: false, explanation: 'Amino acids are absorbed and metabolized, not recycled.' },
      { choiceId: 'd', text: 'Lipids', isCorrect: false, explanation: 'Lipids go via lymphatics as chylomicrons.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Enterohepatic circulation involves bile acids.',
      detailed: 'Bile acids are synthesized in liver, secreted into bile, released into duodenum, reabsorbed in terminal ileum (95%), and returned to liver via portal vein. They cycle 6-8 times daily.',
      clinicalRelevance: 'Bile acid sequestrants (cholestyramine) interrupt enterohepatic circulation to lower cholesterol. Ileal resection causes bile acid diarrhea.',
      relatedConcepts: ['bile acid synthesis', 'cholesterol metabolism', 'ileal function'],
    },
    tags: ['bile-acids', 'liver', 'advanced'],
    relatedTopicIds: ['biliary-physiology', 'cholesterol-metabolism'],
  },

  // ENDOCRINE PHYSIOLOGY
  {
    questionId: 'phys-endo-001',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'endocrine',
    difficulty: 1,
    questionText: 'Which hormone lowers blood glucose?',
    choices: [
      { choiceId: 'a', text: 'Insulin', isCorrect: true, explanation: 'Insulin is the only hormone that lowers blood glucose.' },
      { choiceId: 'b', text: 'Glucagon', isCorrect: false, explanation: 'Glucagon raises blood glucose.' },
      { choiceId: 'c', text: 'Cortisol', isCorrect: false, explanation: 'Cortisol raises blood glucose.' },
      { choiceId: 'd', text: 'Epinephrine', isCorrect: false, explanation: 'Epinephrine raises blood glucose.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Insulin is the only glucose-lowering hormone.',
      detailed: 'Insulin from pancreatic beta cells promotes glucose uptake (via GLUT4 in muscle/fat), glycogen synthesis, and lipogenesis while inhibiting gluconeogenesis and glycogenolysis.',
      clinicalRelevance: 'Type 1 diabetes lacks insulin. Type 2 diabetes has insulin resistance. Counter-regulatory hormones (glucagon, cortisol, epinephrine, GH) raise glucose.',
      relatedConcepts: ['glucose homeostasis', 'diabetes mellitus', 'insulin signaling'],
    },
    tags: ['insulin', 'glucose', 'beginner'],
    relatedTopicIds: ['glucose-regulation', 'diabetes'],
  },
  {
    questionId: 'phys-endo-002',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'endocrine',
    difficulty: 2,
    questionText: 'Which hormone is released in response to low blood calcium?',
    choices: [
      { choiceId: 'a', text: 'Parathyroid hormone (PTH)', isCorrect: true, explanation: 'PTH raises calcium by increasing bone resorption and renal reabsorption.' },
      { choiceId: 'b', text: 'Calcitonin', isCorrect: false, explanation: 'Calcitonin is released in response to HIGH calcium.' },
      { choiceId: 'c', text: 'Thyroid hormone', isCorrect: false, explanation: 'Thyroid hormone regulates metabolism, not calcium.' },
      { choiceId: 'd', text: 'Aldosterone', isCorrect: false, explanation: 'Aldosterone regulates sodium and potassium.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'PTH is released in response to low calcium.',
      detailed: 'PTH from parathyroid glands: (1) increases bone resorption releasing Ca2+, (2) increases renal Ca2+ reabsorption, (3) stimulates 1,25-(OH)2D synthesis which increases intestinal Ca2+ absorption.',
      clinicalRelevance: 'Hyperparathyroidism causes hypercalcemia ("stones, bones, moans, groans"). Hypoparathyroidism causes hypocalcemia with tetany.',
      relatedConcepts: ['calcium homeostasis', 'vitamin D', 'bone metabolism'],
    },
    tags: ['PTH', 'calcium', 'intermediate'],
    relatedTopicIds: ['calcium-regulation', 'parathyroid'],
  },
  {
    questionId: 'phys-endo-003',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'endocrine',
    difficulty: 2,
    questionText: 'The hypothalamic-pituitary-thyroid axis is regulated by:',
    choices: [
      { choiceId: 'a', text: 'Negative feedback from T3 and T4', isCorrect: true, explanation: 'T3/T4 inhibit TRH and TSH release.' },
      { choiceId: 'b', text: 'Positive feedback from T3 and T4', isCorrect: false, explanation: 'Positive feedback would cause uncontrolled hormone release.' },
      { choiceId: 'c', text: 'Negative feedback from cortisol', isCorrect: false, explanation: 'Cortisol regulates HPA axis, not HPT axis.' },
      { choiceId: 'd', text: 'TSH stimulation of hypothalamus', isCorrect: false, explanation: 'TSH acts on thyroid, not hypothalamus.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'T3/T4 provide negative feedback to hypothalamus and pituitary.',
      detailed: 'TRH (hypothalamus) stimulates TSH (pituitary), which stimulates T3/T4 (thyroid). T3/T4 inhibit both TRH and TSH release. This maintains thyroid hormone levels in normal range.',
      clinicalRelevance: 'High TSH with low T4 = primary hypothyroidism. Low TSH with high T4 = primary hyperthyroidism or exogenous T4.',
      relatedConcepts: ['HPT axis', 'thyroid function tests', 'feedback regulation'],
    },
    tags: ['thyroid', 'feedback', 'intermediate'],
    relatedTopicIds: ['thyroid-physiology', 'endocrine-regulation'],
  },
  {
    questionId: 'phys-endo-004',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'endocrine',
    difficulty: 3,
    questionText: 'Cortisol exerts its effects by:',
    choices: [
      { choiceId: 'a', text: 'Binding intracellular receptors that act as transcription factors', isCorrect: true, explanation: 'Cortisol is lipophilic and acts via nuclear receptors.' },
      { choiceId: 'b', text: 'Binding cell surface receptors coupled to G proteins', isCorrect: false, explanation: 'This is how peptide hormones work.' },
      { choiceId: 'c', text: 'Binding receptor tyrosine kinases', isCorrect: false, explanation: 'This is how insulin works.' },
      { choiceId: 'd', text: 'Opening ligand-gated ion channels', isCorrect: false, explanation: 'This is how some neurotransmitters work.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Cortisol binds intracellular receptors (nuclear receptor superfamily).',
      detailed: 'Steroid hormones (cortisol, aldosterone, sex steroids) are lipophilic and cross cell membranes. They bind cytoplasmic/nuclear receptors, which then bind DNA response elements and regulate gene transcription.',
      clinicalRelevance: 'Glucocorticoid effects take hours (gene transcription). Chronic use causes many side effects by altering gene expression.',
      relatedConcepts: ['steroid hormone action', 'nuclear receptors', 'gene transcription'],
    },
    tags: ['cortisol', 'hormone-action', 'advanced'],
    relatedTopicIds: ['steroid-hormones', 'cell-signaling'],
  },

  // NEUROPHYSIOLOGY
  {
    questionId: 'phys-neuro-001',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'nervous',
    difficulty: 2,
    questionText: 'Saltatory conduction occurs in:',
    choices: [
      { choiceId: 'a', text: 'Myelinated axons', isCorrect: true, explanation: 'Action potentials jump between nodes of Ranvier.' },
      { choiceId: 'b', text: 'Unmyelinated axons', isCorrect: false, explanation: 'Unmyelinated axons conduct continuously, slower.' },
      { choiceId: 'c', text: 'Dendrites', isCorrect: false, explanation: 'Dendrites conduct graded potentials, not saltatory.' },
      { choiceId: 'd', text: 'Cell bodies', isCorrect: false, explanation: 'Cell bodies integrate signals, do not conduct saltatory.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Saltatory conduction occurs in myelinated axons.',
      detailed: 'Myelin insulates the axon, and action potentials are regenerated only at nodes of Ranvier. This "jumping" conduction is faster (up to 120 m/s) and more energy-efficient.',
      clinicalRelevance: 'Multiple sclerosis and Guillain-Barre syndrome damage myelin, slowing or blocking conduction.',
      relatedConcepts: ['myelin', 'nodes of Ranvier', 'conduction velocity'],
    },
    tags: ['conduction', 'myelin', 'intermediate'],
    relatedTopicIds: ['neurophysiology', 'demyelinating-diseases'],
  },
  {
    questionId: 'phys-neuro-002',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'nervous',
    difficulty: 2,
    questionText: 'Which neurotransmitter is the primary excitatory transmitter in the CNS?',
    choices: [
      { choiceId: 'a', text: 'Glutamate', isCorrect: true, explanation: 'Glutamate is the main excitatory neurotransmitter.' },
      { choiceId: 'b', text: 'GABA', isCorrect: false, explanation: 'GABA is the main inhibitory neurotransmitter.' },
      { choiceId: 'c', text: 'Glycine', isCorrect: false, explanation: 'Glycine is inhibitory in spinal cord.' },
      { choiceId: 'd', text: 'Acetylcholine', isCorrect: false, explanation: 'ACh is important but not the main excitatory transmitter.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Glutamate is the main CNS excitatory neurotransmitter.',
      detailed: 'Glutamate acts on ionotropic receptors (AMPA, NMDA, kainate) and metabotropic receptors. It is involved in learning, memory, and synaptic plasticity. Excess glutamate causes excitotoxicity.',
      clinicalRelevance: 'NMDA receptor antagonists (ketamine, memantine) have clinical uses. Excitotoxicity contributes to stroke and neurodegenerative disease.',
      relatedConcepts: ['NMDA receptors', 'synaptic transmission', 'excitotoxicity'],
    },
    tags: ['neurotransmitter', 'glutamate', 'intermediate'],
    relatedTopicIds: ['synaptic-transmission', 'neurotransmitters'],
  },
  {
    questionId: 'phys-neuro-003',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'nervous',
    difficulty: 3,
    questionText: 'Long-term potentiation (LTP) primarily involves which receptor?',
    choices: [
      { choiceId: 'a', text: 'NMDA receptor', isCorrect: true, explanation: 'NMDA receptor is crucial for LTP induction.' },
      { choiceId: 'b', text: 'GABA-A receptor', isCorrect: false, explanation: 'GABA-A is inhibitory, not involved in LTP.' },
      { choiceId: 'c', text: 'Muscarinic receptor', isCorrect: false, explanation: 'Muscarinic modulates but does not induce LTP.' },
      { choiceId: 'd', text: 'Opioid receptor', isCorrect: false, explanation: 'Opioid receptors are not central to LTP.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'NMDA receptor is crucial for LTP.',
      detailed: 'The NMDA receptor is a coincidence detector - it requires both glutamate binding AND depolarization (to remove Mg2+ block). Ca2+ entry through NMDA receptors triggers molecular cascades that strengthen synapses.',
      clinicalRelevance: 'LTP is a cellular model for learning and memory. Alzheimer disease involves synaptic dysfunction and impaired plasticity.',
      relatedConcepts: ['synaptic plasticity', 'learning', 'memory'],
    },
    tags: ['LTP', 'NMDA', 'advanced'],
    relatedTopicIds: ['synaptic-plasticity', 'memory-mechanisms'],
  },

  // MUSCLE PHYSIOLOGY
  {
    questionId: 'phys-muscle-001',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'musculoskeletal',
    difficulty: 2,
    questionText: 'In the sliding filament theory, which protein "walks" along actin?',
    choices: [
      { choiceId: 'a', text: 'Myosin', isCorrect: true, explanation: 'Myosin heads bind actin and pull thin filaments toward M-line.' },
      { choiceId: 'b', text: 'Actin', isCorrect: false, explanation: 'Actin is stationary; myosin moves along it.' },
      { choiceId: 'c', text: 'Tropomyosin', isCorrect: false, explanation: 'Tropomyosin regulates but does not generate force.' },
      { choiceId: 'd', text: 'Titin', isCorrect: false, explanation: 'Titin is elastic, connecting thick filaments to Z-line.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Myosin walks along actin filaments.',
      detailed: 'The myosin head binds ATP, hydrolyzes it to ADP+Pi, binds actin, releases Pi (power stroke), releases ADP, then binds new ATP and detaches. This cycle shortens the sarcomere.',
      clinicalRelevance: 'Rigor mortis occurs when ATP is depleted and myosin cannot detach. Myasthenia gravis affects neuromuscular junction, not the contractile mechanism.',
      relatedConcepts: ['cross-bridge cycle', 'sarcomere', 'ATP'],
    },
    tags: ['muscle', 'contraction', 'intermediate'],
    relatedTopicIds: ['muscle-physiology', 'sarcomere-structure'],
  },
  {
    questionId: 'phys-muscle-002',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'musculoskeletal',
    difficulty: 2,
    questionText: 'Calcium initiates muscle contraction by binding to:',
    choices: [
      { choiceId: 'a', text: 'Troponin C (in skeletal/cardiac muscle)', isCorrect: true, explanation: 'Ca2+ binds troponin C, causing tropomyosin to move and expose myosin binding sites.' },
      { choiceId: 'b', text: 'Actin directly', isCorrect: false, explanation: 'Ca2+ does not bind actin directly.' },
      { choiceId: 'c', text: 'Myosin heads', isCorrect: false, explanation: 'Myosin binds ATP, not calcium.' },
      { choiceId: 'd', text: 'Sarcoplasmic reticulum', isCorrect: false, explanation: 'SR releases Ca2+, it does not bind it for contraction.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Calcium binds troponin C in striated muscle.',
      detailed: 'At rest, tropomyosin blocks myosin binding sites on actin. Ca2+ binding to troponin C causes conformational change, moving tropomyosin and exposing actin binding sites for myosin.',
      clinicalRelevance: 'Troponin I and T are cardiac biomarkers for MI. Smooth muscle uses calmodulin instead of troponin.',
      relatedConcepts: ['excitation-contraction coupling', 'tropomyosin', 'calcium'],
    },
    tags: ['calcium', 'troponin', 'intermediate'],
    relatedTopicIds: ['muscle-contraction', 'cardiac-markers'],
  },
];

export const physiologyQuestionsChunk2: QuizQuestion[] = [
  // More cardiovascular
  {
    questionId: 'phys-cv-006',
    domain: 'physiology',
    type: 'homeostasis',
    format: 'multiple-choice',
    system: 'cardiovascular',
    difficulty: 2,
    questionText: 'The baroreceptor reflex responds to:',
    choices: [
      { choiceId: 'a', text: 'Changes in arterial blood pressure', isCorrect: true, explanation: 'Baroreceptors in carotid sinus and aortic arch sense stretch from BP.' },
      { choiceId: 'b', text: 'Changes in blood oxygen', isCorrect: false, explanation: 'Chemoreceptors sense O2 and CO2.' },
      { choiceId: 'c', text: 'Changes in body temperature', isCorrect: false, explanation: 'Thermoreceptors sense temperature.' },
      { choiceId: 'd', text: 'Changes in blood glucose', isCorrect: false, explanation: 'Pancreatic cells sense glucose.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Baroreceptors sense blood pressure changes.',
      detailed: 'High BP stretches baroreceptors, increasing firing rate. This inhibits sympathetic and increases parasympathetic output, causing vasodilation and bradycardia. Low BP has opposite effects.',
      clinicalRelevance: 'Baroreceptor sensitivity decreases with age and hypertension. Orthostatic hypotension results from impaired baroreflex.',
      relatedConcepts: ['blood pressure regulation', 'autonomic nervous system', 'orthostatic hypotension'],
    },
    tags: ['baroreceptors', 'BP-regulation', 'intermediate'],
    relatedTopicIds: ['cardiovascular-reflexes', 'autonomic-regulation'],
  },
  {
    questionId: 'phys-cv-007',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'cardiovascular',
    difficulty: 3,
    questionText: 'Starling forces governing fluid movement across capillaries include:',
    choices: [
      { choiceId: 'a', text: 'Hydrostatic and oncotic pressures', isCorrect: true, explanation: 'Pc and Pi push fluid out; pic and pii pull fluid.' },
      { choiceId: 'b', text: 'Osmotic pressure only', isCorrect: false, explanation: 'Oncotic is a subset of osmotic; hydrostatic also matters.' },
      { choiceId: 'c', text: 'Arterial pressure only', isCorrect: false, explanation: 'Capillary, not arterial pressure, determines filtration.' },
      { choiceId: 'd', text: 'Venous pressure only', isCorrect: false, explanation: 'Both arterial and venous ends of capillary matter.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Starling forces are hydrostatic and oncotic pressures.',
      detailed: 'Net filtration = Kf[(Pc - Pi) - sigma(pic - pii)]. Capillary hydrostatic pressure favors filtration; plasma oncotic pressure favors absorption. Imbalance causes edema.',
      clinicalRelevance: 'Heart failure increases venous/capillary pressure causing edema. Hypoalbuminemia reduces oncotic pressure causing edema.',
      relatedConcepts: ['capillary dynamics', 'edema', 'fluid balance'],
    },
    tags: ['starling-forces', 'capillary', 'advanced'],
    relatedTopicIds: ['microcirculation', 'edema-pathophysiology'],
  },

  // More respiratory
  {
    questionId: 'phys-resp-006',
    domain: 'physiology',
    type: 'homeostasis',
    format: 'multiple-choice',
    system: 'respiratory',
    difficulty: 3,
    questionText: 'What is the Henderson-Hasselbalch equation used for?',
    choices: [
      { choiceId: 'a', text: 'Calculating blood pH from bicarbonate and CO2', isCorrect: true, explanation: 'pH = 6.1 + log([HCO3-]/(0.03 x PCO2)).' },
      { choiceId: 'b', text: 'Calculating oxygen saturation', isCorrect: false, explanation: 'Oxyhemoglobin curve determines saturation.' },
      { choiceId: 'c', text: 'Calculating cardiac output', isCorrect: false, explanation: 'Fick principle calculates CO.' },
      { choiceId: 'd', text: 'Calculating GFR', isCorrect: false, explanation: 'Creatinine clearance estimates GFR.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Henderson-Hasselbalch calculates pH from HCO3- and CO2.',
      detailed: 'pH = pKa + log([A-]/[HA]). For blood: pH = 6.1 + log([HCO3-]/(0.03 x PCO2)). This shows how respiratory (CO2) and metabolic (HCO3-) components determine pH.',
      clinicalRelevance: 'Essential for interpreting ABGs. Respiratory compensation changes CO2; metabolic compensation changes HCO3-.',
      relatedConcepts: ['acid-base balance', 'ABG interpretation', 'buffer systems'],
    },
    tags: ['acid-base', 'equation', 'advanced'],
    relatedTopicIds: ['acid-base-physiology', 'ABG-interpretation'],
  },
  {
    questionId: 'phys-resp-007',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'respiratory',
    difficulty: 2,
    questionText: 'Dead space refers to:',
    choices: [
      { choiceId: 'a', text: 'Lung volume not participating in gas exchange', isCorrect: true, explanation: 'Anatomic dead space (~150 mL) + alveolar dead space = physiologic dead space.' },
      { choiceId: 'b', text: 'Total lung capacity', isCorrect: false, explanation: 'TLC includes all lung volumes.' },
      { choiceId: 'c', text: 'Residual volume', isCorrect: false, explanation: 'RV is air remaining after maximal expiration.' },
      { choiceId: 'd', text: 'Tidal volume', isCorrect: false, explanation: 'TV is normal breath volume.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Dead space is lung volume not exchanging gas.',
      detailed: 'Anatomic dead space = conducting airways (~150 mL). Alveolar dead space = ventilated but not perfused alveoli. Physiologic dead space = anatomic + alveolar dead space.',
      clinicalRelevance: 'Increased dead space in PE (alveolar) or COPD (both). Dead space ventilation wastes respiratory effort.',
      relatedConcepts: ['ventilation', 'V/Q matching', 'pulmonary embolism'],
    },
    tags: ['dead-space', 'ventilation', 'intermediate'],
    relatedTopicIds: ['lung-volumes', 'ventilation-perfusion'],
  },

  // More renal
  {
    questionId: 'phys-renal-005',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'urinary',
    difficulty: 3,
    questionText: 'The countercurrent multiplier in the kidney is established by:',
    choices: [
      { choiceId: 'a', text: 'Loop of Henle', isCorrect: true, explanation: 'Thick ascending limb pumps NaCl, creating medullary gradient.' },
      { choiceId: 'b', text: 'Proximal tubule', isCorrect: false, explanation: 'PT reabsorbs isosmotically.' },
      { choiceId: 'c', text: 'Distal tubule', isCorrect: false, explanation: 'DCT fine-tunes but does not create gradient.' },
      { choiceId: 'd', text: 'Collecting duct', isCorrect: false, explanation: 'CD responds to gradient but does not create it.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Loop of Henle creates the countercurrent multiplier.',
      detailed: 'The thick ascending limb actively pumps NaCl into the interstitium (Na-K-2Cl cotransporter). The descending limb is permeable to water. This creates a hyperosmotic medulla (up to 1200 mOsm/kg).',
      clinicalRelevance: 'Loop diuretics (furosemide) block Na-K-2Cl, impairing concentration ability. Medullary washout can occur with high urine flow.',
      relatedConcepts: ['urine concentration', 'loop of Henle', 'diuretics'],
    },
    tags: ['loop-of-Henle', 'concentration', 'advanced'],
    relatedTopicIds: ['urine-concentration', 'renal-physiology'],
  },

  // More GI
  {
    questionId: 'phys-gi-005',
    domain: 'physiology',
    type: 'process-mechanism',
    format: 'multiple-choice',
    system: 'digestive',
    difficulty: 2,
    questionText: 'Pancreatic bicarbonate secretion is primarily stimulated by:',
    choices: [
      { choiceId: 'a', text: 'Secretin', isCorrect: true, explanation: 'Secretin from S cells stimulates pancreatic HCO3- secretion.' },
      { choiceId: 'b', text: 'CCK', isCorrect: false, explanation: 'CCK stimulates enzyme secretion and gallbladder contraction.' },
      { choiceId: 'c', text: 'Gastrin', isCorrect: false, explanation: 'Gastrin stimulates gastric acid.' },
      { choiceId: 'd', text: 'Motilin', isCorrect: false, explanation: 'Motilin regulates migrating motor complex.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'Secretin stimulates pancreatic bicarbonate secretion.',
      detailed: 'Acidic chyme entering duodenum stimulates S cells to release secretin. Secretin acts on pancreatic duct cells to secrete HCO3-, neutralizing gastric acid.',
      clinicalRelevance: 'Secretin stimulation test diagnoses gastrinoma. Pancreatic insufficiency reduces HCO3- secretion.',
      relatedConcepts: ['pancreatic secretion', 'duodenal physiology', 'GI hormones'],
    },
    tags: ['secretin', 'pancreas', 'intermediate'],
    relatedTopicIds: ['pancreatic-physiology', 'GI-hormones'],
  },

  // More endocrine
  {
    questionId: 'phys-endo-005',
    domain: 'physiology',
    type: 'regulatory-pathway',
    format: 'multiple-choice',
    system: 'endocrine',
    difficulty: 3,
    questionText: 'Growth hormone secretion is stimulated by:',
    choices: [
      { choiceId: 'a', text: 'GHRH from hypothalamus', isCorrect: true, explanation: 'GHRH stimulates GH release from somatotrophs.' },
      { choiceId: 'b', text: 'Somatostatin', isCorrect: false, explanation: 'Somatostatin inhibits GH release.' },
      { choiceId: 'c', text: 'IGF-1', isCorrect: false, explanation: 'IGF-1 provides negative feedback to inhibit GH.' },
      { choiceId: 'd', text: 'Dopamine', isCorrect: false, explanation: 'Dopamine inhibits prolactin, not primary GH regulator.' },
    ],
    correctAnswer: 'a',
    explanation: {
      brief: 'GHRH stimulates growth hormone release.',
      detailed: 'GHRH from hypothalamic arcuate nucleus stimulates GH release. Somatostatin inhibits. GH acts on liver to produce IGF-1, which provides negative feedback to hypothalamus and pituitary.',
      clinicalRelevance: 'GH excess causes gigantism (children) or acromegaly (adults). GH deficiency causes short stature.',
      relatedConcepts: ['GH axis', 'IGF-1', 'pituitary hormones'],
    },
    tags: ['GH', 'GHRH', 'advanced'],
    relatedTopicIds: ['growth-hormone', 'pituitary-physiology'],
  },
];

export const allPhysiologyQuestions: QuizQuestion[] = [
  ...physiologyQuestions,
  ...physiologyQuestionsChunk2,
];
