/**
 * Quality of Life Measures - Educational Content
 */

import { EducationalContent } from '../../types';

export const qualityOfLifeMeasures: EducationalContent = {
  id: 'rehab-quality-of-life-measures',
  type: 'concept',
  name: 'Quality of Life Measures',
  alternateNames: ['HRQOL', 'Patient-Reported Outcomes', 'PROs'],

  levels: {
    1: { level: 1, summary: 'Quality of life measures ask patients about their health, well-being, and how conditions affect their daily lives.', explanation: 'These questionnaires capture what matters most to patients - not just medical tests, but how they feel and function.', keyTerms: [{ term: 'quality of life', definition: 'Overall sense of well-being and life satisfaction' }, { term: 'patient-reported outcome', definition: 'Information reported directly by patients about their health' }], analogies: ['Quality of life measures are like asking how you really feel, not just what the tests show.'], examples: ['Filling out a questionnaire about pain, energy, and mood during a clinic visit.'] },
    2: { level: 2, summary: 'Health-related quality of life (HRQOL) measures assess physical, mental, and social well-being using validated questionnaires to capture patient perspectives on health status.', explanation: '**Types of Measures:**\n\n**Generic:**\n- SF-36/SF-12 (general health)\n- EQ-5D (utility-based)\n- WHOQOL (WHO instrument)\n\n**Disease-Specific:**\n- WOMAC (arthritis)\n- SGRQ (respiratory)\n- FACT (cancer)\n- PDQ-39 (Parkinson\'s)\n\n**Domains:**\n- Physical function\n- Role limitations\n- Pain\n- Mental health\n- Social function\n- Vitality/energy', keyTerms: [{ term: 'SF-36', definition: 'Short Form 36 - widely used generic health measure' }, { term: 'HRQOL', definition: 'Health-related quality of life' }, { term: 'utility', definition: 'Single number representing health state preference (0-1)' }], analogies: ['Generic measures are like a general health checkup, while disease-specific ones focus on particular conditions.'] },
    3: { level: 3, summary: 'HRQOL assessment uses psychometrically validated instruments capturing multiple domains to evaluate treatment effectiveness, track disease trajectory, and inform shared decision-making.', explanation: '## Measurement Properties\n\n**Reliability:**\n- Internal consistency (Cronbach alpha)\n- Test-retest reliability\n\n**Validity:**\n- Content validity\n- Construct validity\n- Criterion validity\n\n**Responsiveness:**\n- Ability to detect change\n- MCID (minimal clinically important difference)\n\n## Common Instruments\n\n| Instrument | Type | Domains | Items |\n|------------|------|---------|-------|\n| SF-36 | Generic | 8 domains | 36 |\n| EQ-5D | Generic/utility | 5 dimensions | 5 |\n| PROMIS | Generic, item bank | Multiple | Variable |\n| KOOS | Knee-specific | 5 subscales | 42 |\n\n## Uses in Rehabilitation\n\n- Baseline assessment\n- Progress monitoring\n- Treatment comparison\n- Research outcomes\n- Quality metrics', keyTerms: [{ term: 'MCID', definition: 'Minimal clinically important difference - smallest meaningful change' }, { term: 'Cronbach alpha', definition: 'Measure of internal consistency reliability' }, { term: 'PROMIS', definition: 'Patient-Reported Outcomes Measurement Information System' }], clinicalNotes: 'PROMIS measures use item response theory and computerized adaptive testing to provide precise measurement with fewer questions.' },
    4: { level: 4, summary: 'Advanced HRQOL assessment integrates preference-based utilities, condition-specific measures, and modern measurement theory for comprehensive patient-centered evaluation and health economic analysis.', explanation: '## Utility Measures\n\n**Purpose:**\n- Health economic analysis\n- QALY calculation\n- Cost-effectiveness research\n\n**Instruments:**\n- EQ-5D (most common)\n- SF-6D (derived from SF-36)\n- HUI (Health Utilities Index)\n\n## Modern Measurement\n\n**PROMIS System:**\n- Item response theory basis\n- Computerized adaptive testing\n- Cross-disease comparison\n- Minimal burden\n\n**Person-Centered:**\n- Individualized assessment\n- Patient priorities\n- Goal attainment scaling\n- Shared decision-making\n\n## Implementation\n\n**Clinical Practice:**\n- Routine collection\n- Decision support\n- Treatment selection\n- Patient engagement\n\n**Barriers:**\n- Time and workflow\n- Technology needs\n- Interpretation challenges\n- Action on results', keyTerms: [{ term: 'QALY', definition: 'Quality-adjusted life year - measure combining quantity and quality of life' }, { term: 'goal attainment scaling', definition: 'Individualized outcome measure based on patient-set goals' }], clinicalNotes: 'EQ-5D is commonly used in health economic analyses due to its brevity and availability of population-based utility values.' },
    5: { level: 5, summary: 'Contemporary HRQOL research explores technology-enabled assessment, real-time monitoring, and integration with clinical care and value-based healthcare models.', explanation: '## Digital Integration\n\n**Remote Collection:**\n- Patient portals\n- Mobile apps\n- Wearables\n- Ecological momentary assessment\n\n**Real-Time Use:**\n- Clinical decision support\n- Symptom alerts\n- Treatment adjustment\n\n## Value-Based Care\n\n**Quality Metrics:**\n- PROs in quality measurement\n- Payment models\n- Public reporting\n- Benchmarking\n\n## Research Frontiers\n\n**Personalization:**\n- Individual-level trajectories\n- Precision outcomes\n- Predictive models\n\n**Global Perspective:**\n- Cross-cultural validation\n- Health equity\n- Resource-limited settings', keyTerms: [{ term: 'ecological momentary assessment', definition: 'Real-time, real-world data collection on patient status' }, { term: 'PRO-PM', definition: 'Patient-reported outcome performance measure for quality assessment' }], clinicalNotes: 'CMS is increasingly incorporating PROs into quality measurement programs. Clinical integration of PRO collection is becoming standard in many settings.' },
  },

  media: [],
  citations: [],
  crossReferences: [{ targetId: 'rehab-functional-assessment-overview', targetType: 'topic', relationship: 'parent', label: 'Functional Assessment Overview' }],
  tags: { systems: ['functional'], topics: ['rehabilitation', 'quality of life', 'patient-reported outcomes'], clinicalRelevance: 'high', examRelevance: { usmle: true, nbme: true, shelf: ['medicine'] } },
  createdAt: '2026-01-24T00:00:00.000Z',
  updatedAt: '2026-01-24T00:00:00.000Z',
  version: 1,
  status: 'published',
};

export default qualityOfLifeMeasures;
