// =============================================================================
// SOMA Salud de la Mujer Enciclopedia — Spanish-First Bilingual
// Women's Health Patient Education Content
// =============================================================================
// ARCHITECTURE: JSON.parse() wrapper prevents TS2590 "expression too complex"
// =============================================================================

export interface SaludMujerEntry {
  id: string;
  nombreEs: string;
  nombreEn: string;
  categoriaEs: string;
  categoriaEn: string;
  descripcionEs: string;
  descripcionEn: string;
  sintomasEs: string[];
  sintomasEn: string[];
  causasFactoresEs: string[];
  causasFactoresEn: string[];
  diagnosticoEs: string[];
  diagnosticoEn: string[];
  tratamientosEs: string[];
  tratamientosEn: string[];
  prevencionEs: string[];
  prevencionEn: string[];
  cuandoConsultarEs: string[];
  cuandoConsultarEn: string[];
  datosClaveEs: string[];
  datosClaveEn: string[];
  edadRiesgo?: string;
  afectaPorcentaje?: string;
}

export const saludMujerEnciclopedia: SaludMujerEntry[] = JSON.parse(`[
  {
    "id": "sm-sindrome-premenstrual",
    "nombreEs": "Sindrome Premenstrual (SPM)",
    "nombreEn": "Premenstrual Syndrome (PMS)",
    "categoriaEs": "Trastornos Menstruales",
    "categoriaEn": "Menstrual Disorders",
    "descripcionEs": "Conjunto de sintomas fisicos y emocionales que ocurren 1-2 semanas antes de la menstruacion. Afecta hasta el 75% de las mujeres en edad reproductiva. Los sintomas desaparecen con el inicio del periodo.",
    "descripcionEn": "Collection of physical and emotional symptoms occurring 1-2 weeks before menstruation. Affects up to 75% of reproductive-age women. Symptoms resolve with period onset.",
    "sintomasEs": ["Hinchazon abdominal y retencion de liquidos", "Sensibilidad mamaria", "Cambios de humor, irritabilidad", "Fatiga y dificultad para concentrarse", "Antojos de alimentos dulces o salados"],
    "sintomasEn": ["Abdominal bloating and fluid retention", "Breast tenderness", "Mood swings, irritability", "Fatigue and difficulty concentrating", "Cravings for sweet or salty foods"],
    "causasFactoresEs": ["Fluctuaciones hormonales de estrogeno y progesterona", "Cambios en serotonina cerebral", "Deficiencia de calcio y magnesio", "Estres y falta de ejercicio"],
    "causasFactoresEn": ["Estrogen and progesterone hormonal fluctuations", "Brain serotonin changes", "Calcium and magnesium deficiency", "Stress and lack of exercise"],
    "diagnosticoEs": ["Diario de sintomas por 2-3 ciclos menstruales", "Exclusion de otras condiciones (tiroides, depresion)", "No existe prueba de laboratorio especifica"],
    "diagnosticoEn": ["Symptom diary for 2-3 menstrual cycles", "Exclusion of other conditions (thyroid, depression)", "No specific lab test exists"],
    "tratamientosEs": ["Ejercicio aerobico regular", "Suplementos de calcio (1200mg/dia) y magnesio", "ISRS en casos severos (TDPM)", "Anticonceptivos hormonales para regular ciclo", "AINEs para dolor"],
    "tratamientosEn": ["Regular aerobic exercise", "Calcium supplements (1200mg/day) and magnesium", "SSRIs for severe cases (PMDD)", "Hormonal contraceptives to regulate cycle", "NSAIDs for pain"],
    "prevencionEs": ["Ejercicio regular 150 min/semana", "Dieta equilibrada baja en sal y cafeina", "Manejo del estres", "Sueno adecuado 7-9 horas"],
    "prevencionEn": ["Regular exercise 150 min/week", "Balanced diet low in salt and caffeine", "Stress management", "Adequate sleep 7-9 hours"],
    "cuandoConsultarEs": ["Sintomas que interfieren con trabajo o relaciones", "Depresion severa premenstrual", "Sintomas que no mejoran con cambios de estilo de vida"],
    "cuandoConsultarEn": ["Symptoms interfering with work or relationships", "Severe premenstrual depression", "Symptoms not improving with lifestyle changes"],
    "datosClaveEs": ["El TDPM (forma severa) afecta al 3-8% de mujeres", "Los sintomas suelen empeorar despues de los 30 anos", "Desaparecen con la menopausia"],
    "datosClaveEn": ["PMDD (severe form) affects 3-8% of women", "Symptoms often worsen after age 30", "Resolve with menopause"],
    "edadRiesgo": "15-50 anos",
    "afectaPorcentaje": "75% de mujeres en edad reproductiva"
  },
  {
    "id": "sm-endometriosis",
    "nombreEs": "Endometriosis",
    "nombreEn": "Endometriosis",
    "categoriaEs": "Ginecologica",
    "categoriaEn": "Gynecological",
    "descripcionEs": "Enfermedad cronica en la que tejido similar al endometrio crece fuera del utero, causando inflamacion, dolor y adherencias. Afecta al 10% de mujeres en edad reproductiva y es causa frecuente de infertilidad.",
    "descripcionEn": "Chronic disease in which tissue similar to the endometrium grows outside the uterus, causing inflammation, pain, and adhesions. Affects 10% of reproductive-age women and is a frequent cause of infertility.",
    "sintomasEs": ["Dolor pelvico cronico que empeora con la menstruacion", "Dismenorrea severa progresiva", "Dolor durante relaciones sexuales (dispareunia profunda)", "Infertilidad", "Dolor al defecar o orinar durante la menstruacion"],
    "sintomasEn": ["Chronic pelvic pain worsening with menstruation", "Progressive severe dysmenorrhea", "Pain during intercourse (deep dyspareunia)", "Infertility", "Pain with bowel movements or urination during menstruation"],
    "causasFactoresEs": ["Menstruacion retrograda (teoria mas aceptada)", "Factores inmunologicos y geneticos", "Transformacion de celulas peritoneales", "Historia familiar de endometriosis"],
    "causasFactoresEn": ["Retrograde menstruation (most accepted theory)", "Immunological and genetic factors", "Peritoneal cell transformation", "Family history of endometriosis"],
    "diagnosticoEs": ["Laparoscopia diagnostica (gold standard)", "Ultrasonido transvaginal para endometriomas", "Resonancia magnetica pelvica", "Historia clinica y examen fisico"],
    "diagnosticoEn": ["Diagnostic laparoscopy (gold standard)", "Transvaginal ultrasound for endometriomas", "Pelvic MRI", "Clinical history and physical exam"],
    "tratamientosEs": ["AINEs para manejo del dolor", "Anticonceptivos hormonales continuos", "Progestagenos (dienogest, medroxiprogesterona)", "Agonistas de GnRH para casos severos", "Cirugia laparoscopica para excision de implantes"],
    "tratamientosEn": ["NSAIDs for pain management", "Continuous hormonal contraceptives", "Progestins (dienogest, medroxyprogesterone)", "GnRH agonists for severe cases", "Laparoscopic surgery for implant excision"],
    "prevencionEs": ["No hay prevencion conocida", "Diagnostico temprano reduce progresion", "Embarazo temprano puede ser protector", "Ejercicio regular puede reducir sintomas"],
    "prevencionEn": ["No known prevention", "Early diagnosis reduces progression", "Early pregnancy may be protective", "Regular exercise may reduce symptoms"],
    "cuandoConsultarEs": ["Dolor menstrual que no responde a analgesicos comunes", "Infertilidad despues de 12 meses de intentar concebir", "Dolor pelvico cronico que afecta calidad de vida"],
    "cuandoConsultarEn": ["Menstrual pain not responding to common analgesics", "Infertility after 12 months trying to conceive", "Chronic pelvic pain affecting quality of life"],
    "datosClaveEs": ["El diagnostico se retrasa en promedio 7-10 anos", "30-50% de mujeres con endometriosis tienen infertilidad", "No es lo mismo que cancer de endometrio"],
    "datosClaveEn": ["Diagnosis is delayed on average 7-10 years", "30-50% of women with endometriosis have infertility", "It is not the same as endometrial cancer"],
    "edadRiesgo": "25-40 anos",
    "afectaPorcentaje": "10% de mujeres en edad reproductiva"
  },
  {
    "id": "sm-ovario-poliquistico",
    "nombreEs": "Sindrome de Ovario Poliquistico (SOP)",
    "nombreEn": "Polycystic Ovary Syndrome (PCOS)",
    "categoriaEs": "Endocrina/Ginecologica",
    "categoriaEn": "Endocrine/Gynecological",
    "descripcionEs": "Trastorno endocrino comun caracterizado por hiperandrogenismo, ovulacion irregular y ovarios poliquisticos. Es la causa mas comun de infertilidad anovulatoria y aumenta el riesgo de diabetes tipo 2 y enfermedad cardiovascular.",
    "descripcionEn": "Common endocrine disorder characterized by hyperandrogenism, irregular ovulation, and polycystic ovaries. It is the most common cause of anovulatory infertility and increases risk of type 2 diabetes and cardiovascular disease.",
    "sintomasEs": ["Ciclos menstruales irregulares o ausentes", "Acne y piel grasa", "Exceso de vello facial y corporal (hirsutismo)", "Aumento de peso, especialmente abdominal", "Dificultad para quedar embarazada", "Oscurecimiento de piel en pliegues (acantosis nigricans)"],
    "sintomasEn": ["Irregular or absent menstrual cycles", "Acne and oily skin", "Excess facial and body hair (hirsutism)", "Weight gain, especially abdominal", "Difficulty getting pregnant", "Skin darkening in folds (acanthosis nigricans)"],
    "causasFactoresEs": ["Resistencia a la insulina (70% de casos)", "Exceso de produccion de androgenos", "Factores geneticos (herencia familiar)", "Inflamacion cronica de bajo grado"],
    "causasFactoresEn": ["Insulin resistance (70% of cases)", "Excess androgen production", "Genetic factors (family inheritance)", "Chronic low-grade inflammation"],
    "diagnosticoEs": ["Criterios de Rotterdam: 2 de 3 (oligoovulacion, hiperandrogenismo, ovarios poliquisticos)", "Analisis hormonal: testosterona, DHEA-S, LH/FSH", "Ultrasonido transvaginal", "Glucosa en ayunas e insulina"],
    "diagnosticoEn": ["Rotterdam criteria: 2 of 3 (oligo-ovulation, hyperandrogenism, polycystic ovaries)", "Hormonal analysis: testosterone, DHEA-S, LH/FSH", "Transvaginal ultrasound", "Fasting glucose and insulin"],
    "tratamientosEs": ["Cambios de estilo de vida: perdida de 5-10% de peso", "Metformina para resistencia a la insulina", "Anticonceptivos orales para regular ciclos", "Espironolactona para hirsutismo", "Letrozol o clomifeno para induccion de ovulacion"],
    "tratamientosEn": ["Lifestyle changes: 5-10% weight loss", "Metformin for insulin resistance", "Oral contraceptives to regulate cycles", "Spironolactone for hirsutism", "Letrozole or clomiphene for ovulation induction"],
    "prevencionEs": ["Mantener peso saludable", "Ejercicio regular", "Dieta baja en indice glucemico", "Control regular de glucosa y lipidos"],
    "prevencionEn": ["Maintain healthy weight", "Regular exercise", "Low glycemic index diet", "Regular glucose and lipid monitoring"],
    "cuandoConsultarEs": ["Periodos irregulares por mas de 3 meses", "Crecimiento excesivo de vello", "Dificultad para embarazarse", "Acne severo que no responde a tratamiento"],
    "cuandoConsultarEn": ["Irregular periods for more than 3 months", "Excessive hair growth", "Difficulty getting pregnant", "Severe acne not responding to treatment"],
    "datosClaveEs": ["Afecta al 6-12% de mujeres en edad reproductiva", "50% no estan diagnosticadas", "No todas tienen quistes ovaricos visibles"],
    "datosClaveEn": ["Affects 6-12% of reproductive-age women", "50% are undiagnosed", "Not all have visible ovarian cysts"],
    "edadRiesgo": "15-44 anos",
    "afectaPorcentaje": "6-12% de mujeres en edad reproductiva"
  },
  {
    "id": "sm-miomas-uterinos",
    "nombreEs": "Miomas Uterinos (Fibromas)",
    "nombreEn": "Uterine Fibroids (Leiomyomas)",
    "categoriaEs": "Ginecologica",
    "categoriaEn": "Gynecological",
    "descripcionEs": "Tumores benignos del musculo liso uterino. Son los tumores pelvicos mas comunes en mujeres. La mayoria son asintomaticos, pero pueden causar sangrado abundante, dolor y problemas de fertilidad segun su tamano y ubicacion.",
    "descripcionEn": "Benign tumors of uterine smooth muscle. They are the most common pelvic tumors in women. Most are asymptomatic but can cause heavy bleeding, pain, and fertility issues depending on size and location.",
    "sintomasEs": ["Sangrado menstrual abundante y prolongado", "Dolor pelvico o presion", "Necesidad frecuente de orinar (compresion vesical)", "Estrenimiento (compresion rectal)", "Aumento del tamano abdominal"],
    "sintomasEn": ["Heavy and prolonged menstrual bleeding", "Pelvic pain or pressure", "Frequent urination (bladder compression)", "Constipation (rectal compression)", "Increased abdominal size"],
    "causasFactoresEs": ["Estimulacion por estrogenos y progesterona", "Predisposicion genetica", "Raza afroamericana (3x mayor riesgo)", "Obesidad y nuliparidad"],
    "causasFactoresEn": ["Stimulation by estrogen and progesterone", "Genetic predisposition", "African American race (3x higher risk)", "Obesity and nulliparity"],
    "diagnosticoEs": ["Ultrasonido pelvico (primera linea)", "Resonancia magnetica para mapeo preciso", "Histeroscopia para miomas submucosos", "Examen pelvico bimanual"],
    "diagnosticoEn": ["Pelvic ultrasound (first line)", "MRI for precise mapping", "Hysteroscopy for submucosal fibroids", "Bimanual pelvic exam"],
    "tratamientosEs": ["Observacion si asintomaticos", "AINEs y acido tranexamico para sangrado", "Agonistas de GnRH para reducir tamano preoperatorio", "Embolizacion de arteria uterina", "Miomectomia (conserva utero)", "Histerectomia (definitiva)"],
    "tratamientosEn": ["Observation if asymptomatic", "NSAIDs and tranexamic acid for bleeding", "GnRH agonists to reduce preoperative size", "Uterine artery embolization", "Myomectomy (preserves uterus)", "Hysterectomy (definitive)"],
    "prevencionEs": ["No hay prevencion comprobada", "Mantener peso saludable", "Consumo de frutas y verduras verdes", "Actividad fisica regular"],
    "prevencionEn": ["No proven prevention", "Maintain healthy weight", "Green fruits and vegetables consumption", "Regular physical activity"],
    "cuandoConsultarEs": ["Sangrado menstrual que empapa una toalla por hora", "Anemia por sangrado abundante", "Dolor pelvico persistente", "Crecimiento rapido del mioma en ultrasonido"],
    "cuandoConsultarEn": ["Menstrual bleeding soaking a pad per hour", "Anemia from heavy bleeding", "Persistent pelvic pain", "Rapid fibroid growth on ultrasound"],
    "datosClaveEs": ["Afectan al 70-80% de mujeres antes de los 50 anos", "Regresan naturalmente con la menopausia", "Rara vez se malignizan (<0.1%)"],
    "datosClaveEn": ["Affect 70-80% of women before age 50", "Naturally regress with menopause", "Rarely become malignant (<0.1%)"],
    "edadRiesgo": "30-50 anos",
    "afectaPorcentaje": "70-80% de mujeres antes de los 50"
  },
  {
    "id": "sm-cancer-mama",
    "nombreEs": "Cancer de Mama",
    "nombreEn": "Breast Cancer",
    "categoriaEs": "Oncologica",
    "categoriaEn": "Oncological",
    "descripcionEs": "El cancer mas comun en mujeres a nivel mundial. Se origina en las celulas del tejido mamario, generalmente en los conductos (ductal) o lobulillos (lobulillar). La deteccion temprana mediante mamografia mejora significativamente la supervivencia.",
    "descripcionEn": "The most common cancer in women worldwide. It originates in breast tissue cells, usually in ducts (ductal) or lobules (lobular). Early detection through mammography significantly improves survival.",
    "sintomasEs": ["Bulto o masa en la mama (generalmente indoloro)", "Cambio en tamano o forma de la mama", "Retraccion del pezon o secrecion sanguinolenta", "Piel de naranja (edema cutaneo)", "Ganglios axilares inflamados"],
    "sintomasEn": ["Lump or mass in breast (usually painless)", "Change in breast size or shape", "Nipple retraction or bloody discharge", "Orange peel skin (cutaneous edema)", "Swollen axillary lymph nodes"],
    "causasFactoresEs": ["Edad avanzada (mayor riesgo despues de 50)", "Mutaciones BRCA1/BRCA2", "Historia familiar de cancer de mama", "Menarquia temprana o menopausia tardia", "Terapia hormonal de reemplazo prolongada", "Obesidad postmenopausica"],
    "causasFactoresEn": ["Advanced age (higher risk after 50)", "BRCA1/BRCA2 mutations", "Family history of breast cancer", "Early menarche or late menopause", "Prolonged hormone replacement therapy", "Postmenopausal obesity"],
    "diagnosticoEs": ["Mamografia de tamizaje (anual desde 40-50 anos)", "Ultrasonido mamario complementario", "Biopsia con aguja gruesa (core biopsy)", "Resonancia magnetica mamaria para alto riesgo", "Estudio de receptores hormonales y HER2"],
    "diagnosticoEn": ["Screening mammography (annually from age 40-50)", "Complementary breast ultrasound", "Core needle biopsy", "Breast MRI for high risk", "Hormone receptor and HER2 testing"],
    "tratamientosEs": ["Cirugia: lumpectomia o mastectomia", "Radioterapia adyuvante", "Quimioterapia neoadyuvante o adyuvante", "Terapia hormonal (tamoxifeno, inhibidores de aromatasa)", "Terapia dirigida (trastuzumab para HER2+)", "Inmunoterapia en subtipos especificos"],
    "tratamientosEn": ["Surgery: lumpectomy or mastectomy", "Adjuvant radiation therapy", "Neoadjuvant or adjuvant chemotherapy", "Hormonal therapy (tamoxifen, aromatase inhibitors)", "Targeted therapy (trastuzumab for HER2+)", "Immunotherapy for specific subtypes"],
    "prevencionEs": ["Mamografia regular segun edad y riesgo", "Autoexamen mamario mensual", "Ejercicio regular 150+ min/semana", "Limitar alcohol a <1 bebida/dia", "Lactancia materna (efecto protector)"],
    "prevencionEn": ["Regular mammography based on age and risk", "Monthly breast self-exam", "Regular exercise 150+ min/week", "Limit alcohol to <1 drink/day", "Breastfeeding (protective effect)"],
    "cuandoConsultarEs": ["Cualquier bulto nuevo en la mama", "Cambio en la piel de la mama", "Secrecion por el pezon (especialmente sanguinolenta)", "Dolor mamario persistente unilateral"],
    "cuandoConsultarEn": ["Any new breast lump", "Change in breast skin", "Nipple discharge (especially bloody)", "Persistent unilateral breast pain"],
    "datosClaveEs": ["1 de cada 8 mujeres desarrollara cancer de mama", "Supervivencia a 5 anos en estadio I: >95%", "Los hombres tambien pueden desarrollarlo (1% de casos)"],
    "datosClaveEn": ["1 in 8 women will develop breast cancer", "5-year survival in stage I: >95%", "Men can also develop it (1% of cases)"],
    "edadRiesgo": ">40 anos, pico 60-70",
    "afectaPorcentaje": "12.5% de mujeres en su vida"
  },
  {
    "id": "sm-cancer-cervicouterino",
    "nombreEs": "Cancer Cervicouterino",
    "nombreEn": "Cervical Cancer",
    "categoriaEs": "Oncologica",
    "categoriaEn": "Oncological",
    "descripcionEs": "Cancer que se origina en el cuello uterino, casi siempre causado por infeccion persistente con VPH de alto riesgo (tipos 16 y 18). Es prevenible mediante vacunacion contra VPH y deteccion con Papanicolaou.",
    "descripcionEn": "Cancer originating in the cervix, almost always caused by persistent high-risk HPV infection (types 16 and 18). It is preventable through HPV vaccination and Pap smear screening.",
    "sintomasEs": ["Sangrado vaginal anormal (entre periodos, postcoital)", "Flujo vaginal con mal olor", "Dolor pelvico en estadios avanzados", "Dolor durante relaciones sexuales", "Asintomatico en estadios tempranos"],
    "sintomasEn": ["Abnormal vaginal bleeding (between periods, postcoital)", "Foul-smelling vaginal discharge", "Pelvic pain in advanced stages", "Pain during intercourse", "Asymptomatic in early stages"],
    "causasFactoresEs": ["Infeccion persistente por VPH de alto riesgo", "Inicio temprano de relaciones sexuales", "Multiples parejas sexuales", "Tabaquismo", "Inmunosupresion (VIH)", "No realizarse Papanicolaou regularmente"],
    "causasFactoresEn": ["Persistent high-risk HPV infection", "Early onset of sexual activity", "Multiple sexual partners", "Smoking", "Immunosuppression (HIV)", "Not getting regular Pap smears"],
    "diagnosticoEs": ["Papanicolaou (citologia cervical)", "Prueba de VPH (co-test)", "Colposcopia con biopsia si hay anormalidad", "TAC y resonancia para estadificacion"],
    "diagnosticoEn": ["Pap smear (cervical cytology)", "HPV test (co-test)", "Colposcopy with biopsy if abnormality found", "CT and MRI for staging"],
    "tratamientosEs": ["Lesiones premalignas: crioterapia, LEEP, conizacion", "Estadio temprano: histerectomia radical", "Estadios avanzados: quimiorradiacion concurrente", "Inmunoterapia (pembrolizumab) para recurrente"],
    "tratamientosEn": ["Premalignant lesions: cryotherapy, LEEP, conization", "Early stage: radical hysterectomy", "Advanced stages: concurrent chemoradiation", "Immunotherapy (pembrolizumab) for recurrent"],
    "prevencionEs": ["Vacuna contra VPH (9-26 anos, idealmente antes de inicio sexual)", "Papanicolaou regular cada 3 anos (21-65 anos)", "Co-test (Pap + VPH) cada 5 anos (30-65 anos)", "Uso de condon (reduce pero no elimina riesgo de VPH)", "No fumar"],
    "prevencionEn": ["HPV vaccine (ages 9-26, ideally before sexual debut)", "Regular Pap smear every 3 years (ages 21-65)", "Co-test (Pap + HPV) every 5 years (ages 30-65)", "Condom use (reduces but does not eliminate HPV risk)", "Do not smoke"],
    "cuandoConsultarEs": ["Sangrado entre periodos o despues de relaciones", "Flujo vaginal inusual persistente", "Resultado anormal de Papanicolaou"],
    "cuandoConsultarEn": ["Bleeding between periods or after intercourse", "Persistent unusual vaginal discharge", "Abnormal Pap smear result"],
    "datosClaveEs": ["99% de casos son causados por VPH", "La vacuna contra VPH previene hasta el 90% de casos", "Es el 4to cancer mas comun en mujeres a nivel mundial"],
    "datosClaveEn": ["99% of cases are caused by HPV", "HPV vaccine prevents up to 90% of cases", "It is the 4th most common cancer in women worldwide"],
    "edadRiesgo": "30-50 anos (pico)",
    "afectaPorcentaje": "Variable segun acceso a deteccion"
  },
  {
    "id": "sm-menopausia",
    "nombreEs": "Menopausia",
    "nombreEn": "Menopause",
    "categoriaEs": "Endocrina/Reproductiva",
    "categoriaEn": "Endocrine/Reproductive",
    "descripcionEs": "Cese permanente de la menstruacion por 12 meses consecutivos, marcando el fin de la etapa reproductiva. La edad promedio es 51 anos. La perimenopausia (transicion) puede durar 4-8 anos con sintomas fluctuantes.",
    "descripcionEn": "Permanent cessation of menstruation for 12 consecutive months, marking the end of the reproductive stage. Average age is 51. Perimenopause (transition) can last 4-8 years with fluctuating symptoms.",
    "sintomasEs": ["Bochornos/sofocos y sudoracion nocturna", "Irregularidad menstrual progresiva", "Sequedad vaginal y dispareunia", "Cambios de humor, irritabilidad, ansiedad", "Insomnio y alteraciones del sueno", "Disminucion de la libido"],
    "sintomasEn": ["Hot flashes and night sweats", "Progressive menstrual irregularity", "Vaginal dryness and dyspareunia", "Mood changes, irritability, anxiety", "Insomnia and sleep disturbances", "Decreased libido"],
    "causasFactoresEs": ["Declive natural de funcion ovarica con la edad", "Agotamiento de foliculos ovaricos", "Menopausia quirurgica (ooforectomia)", "Quimioterapia o radioterapia pelvica", "Insuficiencia ovarica prematura"],
    "causasFactoresEn": ["Natural decline of ovarian function with age", "Ovarian follicle depletion", "Surgical menopause (oophorectomy)", "Chemotherapy or pelvic radiation", "Premature ovarian insufficiency"],
    "diagnosticoEs": ["Diagnostico clinico: 12 meses sin menstruacion despues de los 45", "FSH elevada (>30 UI/L) si hay duda", "No se requieren estudios en edad tipica", "Descartar embarazo y patologia tiroidea"],
    "diagnosticoEn": ["Clinical diagnosis: 12 months without menstruation after age 45", "Elevated FSH (>30 IU/L) if doubt exists", "No studies required at typical age", "Rule out pregnancy and thyroid pathology"],
    "tratamientosEs": ["Terapia hormonal de reemplazo (THR) para sintomas moderados-severos", "Estrogeno vaginal topico para sequedad", "ISRS/IRSN para bochornos si THR contraindicada", "Lubricantes vaginales", "Fitoestrógenos (evidencia limitada)"],
    "tratamientosEn": ["Hormone replacement therapy (HRT) for moderate-severe symptoms", "Topical vaginal estrogen for dryness", "SSRIs/SNRIs for hot flashes if HRT contraindicated", "Vaginal lubricants", "Phytoestrogens (limited evidence)"],
    "prevencionEs": ["No se puede prevenir (proceso natural)", "Ejercicio regular para mantener salud osea", "Calcio y vitamina D para prevenir osteoporosis", "Control cardiovascular regular"],
    "prevencionEn": ["Cannot be prevented (natural process)", "Regular exercise to maintain bone health", "Calcium and vitamin D to prevent osteoporosis", "Regular cardiovascular monitoring"],
    "cuandoConsultarEs": ["Bochornos que interfieren con calidad de vida", "Sangrado vaginal despues de la menopausia (siempre evaluar)", "Sintomas de depresion severa", "Menopausia antes de los 40 anos"],
    "cuandoConsultarEn": ["Hot flashes interfering with quality of life", "Vaginal bleeding after menopause (always evaluate)", "Severe depression symptoms", "Menopause before age 40"],
    "datosClaveEs": ["Edad promedio: 51 anos", "Menopausia prematura (<40 anos) afecta al 1%", "Riesgo cardiovascular aumenta significativamente post-menopausia"],
    "datosClaveEn": ["Average age: 51 years", "Premature menopause (<40 years) affects 1%", "Cardiovascular risk increases significantly post-menopause"],
    "edadRiesgo": "45-55 anos (perimenopausia desde 40)",
    "afectaPorcentaje": "100% de mujeres"
  },
  {
    "id": "sm-preeclampsia",
    "nombreEs": "Preeclampsia",
    "nombreEn": "Preeclampsia",
    "categoriaEs": "Obstetrica",
    "categoriaEn": "Obstetric",
    "descripcionEs": "Complicacion del embarazo caracterizada por hipertension arterial nueva y proteinuria despues de las 20 semanas de gestacion. Puede progresar a eclampsia (convulsiones) o sindrome HELLP, ambos potencialmente fatales para madre y bebe.",
    "descripcionEn": "Pregnancy complication characterized by new-onset hypertension and proteinuria after 20 weeks gestation. Can progress to eclampsia (seizures) or HELLP syndrome, both potentially fatal for mother and baby.",
    "sintomasEs": ["Presion arterial elevada (>140/90 mmHg)", "Hinchazon subita de cara y manos", "Dolor de cabeza severo persistente", "Vision borrosa o destellos luminosos", "Dolor en epigastrio o hipocondrio derecho", "Disminucion de orina"],
    "sintomasEn": ["Elevated blood pressure (>140/90 mmHg)", "Sudden swelling of face and hands", "Severe persistent headache", "Blurred vision or light flashes", "Pain in epigastrium or right upper quadrant", "Decreased urine output"],
    "causasFactoresEs": ["Implantacion placentaria anormal", "Primer embarazo (nuliparidad)", "Historia personal o familiar de preeclampsia", "Embarazo multiple", "Obesidad y diabetes pregestacional", "Edad materna >35 anos o <20 anos"],
    "causasFactoresEn": ["Abnormal placental implantation", "First pregnancy (nulliparity)", "Personal or family history of preeclampsia", "Multiple pregnancy", "Obesity and pregestational diabetes", "Maternal age >35 or <20 years"],
    "diagnosticoEs": ["Presion arterial >140/90 en 2 tomas separadas por 4 horas", "Proteinuria >300mg/24h o relacion proteina/creatinina >0.3", "Laboratorios: plaquetas, funcion hepatica, creatinina", "Pruebas de bienestar fetal"],
    "diagnosticoEn": ["Blood pressure >140/90 on 2 readings 4 hours apart", "Proteinuria >300mg/24h or protein/creatinine ratio >0.3", "Labs: platelets, liver function, creatinine", "Fetal well-being tests"],
    "tratamientosEs": ["El unico tratamiento definitivo es el parto", "Sulfato de magnesio para prevencion de convulsiones", "Antihipertensivos: labetalol, nifedipino", "Corticosteroides para madurez pulmonar fetal si <34 semanas", "Monitorizacion intensiva materno-fetal"],
    "tratamientosEn": ["The only definitive treatment is delivery", "Magnesium sulfate for seizure prevention", "Antihypertensives: labetalol, nifedipine", "Corticosteroids for fetal lung maturity if <34 weeks", "Intensive maternal-fetal monitoring"],
    "prevencionEs": ["Aspirina a dosis baja (81mg) desde semana 12 en alto riesgo", "Control prenatal regular", "Mantener peso saludable antes del embarazo", "Control de enfermedades cronicas preexistentes"],
    "prevencionEn": ["Low-dose aspirin (81mg) from week 12 in high risk", "Regular prenatal care", "Maintain healthy weight before pregnancy", "Control of pre-existing chronic diseases"],
    "cuandoConsultarEs": ["Presion arterial >140/90 en cualquier momento del embarazo", "Hinchazon subita de cara o manos", "Dolor de cabeza severo que no cede con analgesicos", "Vision borrosa o dolor abdominal superior"],
    "cuandoConsultarEn": ["Blood pressure >140/90 at any point in pregnancy", "Sudden face or hand swelling", "Severe headache not relieved by analgesics", "Blurred vision or upper abdominal pain"],
    "datosClaveEs": ["Afecta al 2-8% de embarazos", "Causa principal de mortalidad materna en paises en desarrollo", "Puede recurrir en embarazos posteriores (20-50%)"],
    "datosClaveEn": ["Affects 2-8% of pregnancies", "Leading cause of maternal mortality in developing countries", "Can recur in subsequent pregnancies (20-50%)"],
    "edadRiesgo": "Cualquier edad en embarazo",
    "afectaPorcentaje": "2-8% de embarazos"
  },
  {
    "id": "sm-diabetes-gestacional",
    "nombreEs": "Diabetes Gestacional",
    "nombreEn": "Gestational Diabetes",
    "categoriaEs": "Obstetrica/Metabolica",
    "categoriaEn": "Obstetric/Metabolic",
    "descripcionEs": "Intolerancia a la glucosa diagnosticada por primera vez durante el embarazo. La placenta produce hormonas que generan resistencia a la insulina. Sin control adecuado, aumenta riesgo de macrosomia fetal y complicaciones del parto.",
    "descripcionEn": "Glucose intolerance first diagnosed during pregnancy. The placenta produces hormones causing insulin resistance. Without adequate control, it increases risk of fetal macrosomia and delivery complications.",
    "sintomasEs": ["Generalmente asintomatica (se detecta en tamizaje)", "Sed excesiva", "Orinar con mas frecuencia de lo normal para el embarazo", "Fatiga excesiva", "Vision borrosa"],
    "sintomasEn": ["Generally asymptomatic (detected on screening)", "Excessive thirst", "Urinating more frequently than normal for pregnancy", "Excessive fatigue", "Blurred vision"],
    "causasFactoresEs": ["Resistencia a la insulina por hormonas placentarias", "Obesidad o sobrepeso pregestacional", "Edad materna >25 anos", "Historia familiar de diabetes tipo 2", "SOP", "Diabetes gestacional en embarazo previo"],
    "causasFactoresEn": ["Insulin resistance from placental hormones", "Pre-pregnancy obesity or overweight", "Maternal age >25 years", "Family history of type 2 diabetes", "PCOS", "Gestational diabetes in previous pregnancy"],
    "diagnosticoEs": ["Tamizaje con carga de glucosa 50g entre semanas 24-28", "Confirmacion con curva de tolerancia a glucosa 75g o 100g", "Glucosa en ayunas >=92 mg/dL (criterio IADPSG)", "Tamizaje temprano en mujeres de alto riesgo"],
    "diagnosticoEn": ["Screening with 50g glucose load between weeks 24-28", "Confirmation with 75g or 100g glucose tolerance test", "Fasting glucose >=92 mg/dL (IADPSG criteria)", "Early screening in high-risk women"],
    "tratamientosEs": ["Dieta con control de carbohidratos", "Automonitoreo de glucosa 4 veces al dia", "Ejercicio moderado 30 min/dia", "Insulina si no se logran metas con dieta (metformina como alternativa)", "Vigilancia fetal con ultrasonidos seriados"],
    "tratamientosEn": ["Carbohydrate-controlled diet", "Self-monitoring glucose 4 times daily", "Moderate exercise 30 min/day", "Insulin if goals not met with diet (metformin as alternative)", "Fetal surveillance with serial ultrasounds"],
    "prevencionEs": ["Peso saludable antes del embarazo", "Actividad fisica regular", "Dieta saludable desde el inicio del embarazo", "Control prenatal temprano"],
    "prevencionEn": ["Healthy weight before pregnancy", "Regular physical activity", "Healthy diet from beginning of pregnancy", "Early prenatal care"],
    "cuandoConsultarEs": ["Glucosa en ayunas >95 mg/dL", "Glucosa postprandial >140 mg/dL a pesar de dieta", "Crecimiento fetal excesivo en ultrasonido"],
    "cuandoConsultarEn": ["Fasting glucose >95 mg/dL", "Postprandial glucose >140 mg/dL despite diet", "Excessive fetal growth on ultrasound"],
    "datosClaveEs": ["Afecta al 6-14% de embarazos", "50% desarrollara diabetes tipo 2 en 10-20 anos", "Se resuelve tras el parto en la mayoria de casos"],
    "datosClaveEn": ["Affects 6-14% of pregnancies", "50% will develop type 2 diabetes in 10-20 years", "Resolves after delivery in most cases"],
    "edadRiesgo": "Cualquier edad en embarazo, mayor riesgo >25",
    "afectaPorcentaje": "6-14% de embarazos"
  },
  {
    "id": "sm-depresion-postparto",
    "nombreEs": "Depresion Postparto",
    "nombreEn": "Postpartum Depression",
    "categoriaEs": "Salud Mental/Obstetrica",
    "categoriaEn": "Mental Health/Obstetric",
    "descripcionEs": "Trastorno depresivo que inicia durante el embarazo o dentro de las primeras 4 semanas postparto (puede presentarse hasta un ano despues). Es mas severa y prolongada que el baby blues. Requiere tratamiento profesional.",
    "descripcionEn": "Depressive disorder beginning during pregnancy or within first 4 weeks postpartum (can present up to one year after). More severe and prolonged than baby blues. Requires professional treatment.",
    "sintomasEs": ["Tristeza persistente y llanto frecuente", "Perdida de interes en el bebe o actividades", "Sentimientos de culpa, inutilidad o inadecuacion como madre", "Insomnio o hipersomnia", "Ansiedad severa sobre la salud del bebe", "Pensamientos de hacerse dano o danar al bebe"],
    "sintomasEn": ["Persistent sadness and frequent crying", "Loss of interest in baby or activities", "Feelings of guilt, worthlessness or inadequacy as mother", "Insomnia or hypersomnia", "Severe anxiety about baby's health", "Thoughts of harming self or baby"],
    "causasFactoresEs": ["Cambios hormonales bruscos postparto", "Historia previa de depresion o ansiedad", "Falta de apoyo social", "Complicaciones del embarazo o parto", "Parto prematuro o bebe en UCIN", "Eventos estresantes durante el embarazo"],
    "causasFactoresEn": ["Abrupt postpartum hormonal changes", "Previous history of depression or anxiety", "Lack of social support", "Pregnancy or delivery complications", "Premature birth or baby in NICU", "Stressful events during pregnancy"],
    "diagnosticoEs": ["Escala de Edimburgo para depresion postparto (EPDS >12)", "Evaluacion clinica por salud mental", "Descartar trastorno tiroideo", "Tamizaje de rutina en visitas postparto"],
    "diagnosticoEn": ["Edinburgh Postnatal Depression Scale (EPDS >12)", "Clinical mental health evaluation", "Rule out thyroid disorder", "Routine screening at postpartum visits"],
    "tratamientosEs": ["Psicoterapia (terapia cognitivo-conductual)", "Antidepresivos (sertralina compatible con lactancia)", "Grupos de apoyo para madres", "Brexanolona IV para casos severos", "Zuranolona oral (nuevo tratamiento aprobado)"],
    "tratamientosEn": ["Psychotherapy (cognitive behavioral therapy)", "Antidepressants (sertraline compatible with breastfeeding)", "Support groups for mothers", "IV brexanolone for severe cases", "Oral zuranolone (newly approved treatment)"],
    "prevencionEs": ["Tamizaje prenatal de factores de riesgo", "Red de apoyo durante y despues del embarazo", "Educacion sobre depresion postparto", "Planificacion de ayuda practica postparto"],
    "prevencionEn": ["Prenatal screening for risk factors", "Support network during and after pregnancy", "Education about postpartum depression", "Planning practical postpartum help"],
    "cuandoConsultarEs": ["Tristeza que dura mas de 2 semanas postparto", "Incapacidad para cuidar al bebe", "Pensamientos de hacerse dano o danar al bebe (URGENTE)", "Incapacidad para dormir aun cuando el bebe duerme"],
    "cuandoConsultarEn": ["Sadness lasting more than 2 weeks postpartum", "Inability to care for baby", "Thoughts of harming self or baby (URGENT)", "Inability to sleep even when baby sleeps"],
    "datosClaveEs": ["Afecta al 10-20% de madres", "Baby blues (leve) afecta al 80% y se resuelve en 2 semanas", "La psicosis postparto es rara (0.1%) pero es emergencia psiquiatrica"],
    "datosClaveEn": ["Affects 10-20% of mothers", "Baby blues (mild) affects 80% and resolves in 2 weeks", "Postpartum psychosis is rare (0.1%) but is a psychiatric emergency"],
    "edadRiesgo": "Cualquier edad en periodo perinatal",
    "afectaPorcentaje": "10-20% de madres"
  },
  {
    "id": "sm-vaginosis-bacteriana",
    "nombreEs": "Vaginosis Bacteriana",
    "nombreEn": "Bacterial Vaginosis",
    "categoriaEs": "Infecciosa/Ginecologica",
    "categoriaEn": "Infectious/Gynecological",
    "descripcionEs": "Desequilibrio de la flora vaginal normal con sobrecrecimiento de bacterias anaerobias (Gardnerella vaginalis y otras) y disminucion de lactobacilos. Es la infeccion vaginal mas comun en mujeres en edad reproductiva.",
    "descripcionEn": "Imbalance of normal vaginal flora with overgrowth of anaerobic bacteria (Gardnerella vaginalis and others) and decreased lactobacilli. It is the most common vaginal infection in reproductive-age women.",
    "sintomasEs": ["Flujo vaginal grisaceo-blanquecino con olor a pescado", "Olor que empeora despues de relaciones sexuales", "Puede ser asintomatica (50% de casos)", "Ardor leve al orinar"],
    "sintomasEn": ["Gray-white vaginal discharge with fishy odor", "Odor worsening after sexual intercourse", "May be asymptomatic (50% of cases)", "Mild burning with urination"],
    "causasFactoresEs": ["Desequilibrio del microbioma vaginal", "Duchas vaginales", "Multiples parejas sexuales", "Uso de DIU", "Tabaquismo"],
    "causasFactoresEn": ["Vaginal microbiome imbalance", "Vaginal douching", "Multiple sexual partners", "IUD use", "Smoking"],
    "diagnosticoEs": ["Criterios de Amsel (3 de 4): flujo homogeneo, pH >4.5, celulas clave, prueba de aminas positiva", "Puntuacion de Nugent en tincion de Gram", "Prueba rapida de pH vaginal"],
    "diagnosticoEn": ["Amsel criteria (3 of 4): homogeneous discharge, pH >4.5, clue cells, positive amine test", "Nugent score on Gram stain", "Rapid vaginal pH test"],
    "tratamientosEs": ["Metronidazol oral 500mg cada 12h por 7 dias", "Metronidazol gel vaginal al 0.75%", "Clindamicina crema vaginal al 2%", "Probioticos vaginales como complemento"],
    "tratamientosEn": ["Oral metronidazole 500mg every 12h for 7 days", "Vaginal metronidazole 0.75% gel", "Vaginal clindamycin 2% cream", "Vaginal probiotics as complement"],
    "prevencionEs": ["No hacer duchas vaginales", "Uso de condon", "Ropa interior de algodon", "Evitar jabones perfumados en area genital"],
    "prevencionEn": ["Do not douche", "Condom use", "Cotton underwear", "Avoid perfumed soaps in genital area"],
    "cuandoConsultarEs": ["Flujo con mal olor persistente", "Sintomas recurrentes (3+ episodios/ano)", "Sintomas durante el embarazo"],
    "cuandoConsultarEn": ["Persistent foul-smelling discharge", "Recurrent symptoms (3+ episodes/year)", "Symptoms during pregnancy"],
    "datosClaveEs": ["Afecta al 29% de mujeres de 14-49 anos", "No es una ITS pero se asocia a actividad sexual", "Aumenta riesgo de parto prematuro y EIP"],
    "datosClaveEn": ["Affects 29% of women ages 14-49", "Not an STI but associated with sexual activity", "Increases risk of preterm birth and PID"],
    "edadRiesgo": "15-44 anos",
    "afectaPorcentaje": "29% de mujeres 14-49 anos"
  },
  {
    "id": "sm-candidiasis-vaginal",
    "nombreEs": "Candidiasis Vaginal",
    "nombreEn": "Vaginal Yeast Infection",
    "categoriaEs": "Infecciosa/Ginecologica",
    "categoriaEn": "Infectious/Gynecological",
    "descripcionEs": "Infeccion fungica causada principalmente por Candida albicans. Ocurre por sobrecrecimiento del hongo que normalmente habita la vagina. Es la segunda causa mas comun de vaginitis despues de la vaginosis bacteriana.",
    "descripcionEn": "Fungal infection primarily caused by Candida albicans. Occurs from overgrowth of the fungus that normally inhabits the vagina. It is the second most common cause of vaginitis after bacterial vaginosis.",
    "sintomasEs": ["Prurito vulvar intenso", "Flujo blanco espeso tipo requesón sin olor", "Enrojecimiento e hinchazon vulvar", "Dolor y ardor al orinar", "Dolor durante relaciones sexuales"],
    "sintomasEn": ["Intense vulvar itching", "Thick white cottage cheese-like odorless discharge", "Vulvar redness and swelling", "Pain and burning with urination", "Pain during intercourse"],
    "causasFactoresEs": ["Uso reciente de antibioticos", "Diabetes mal controlada", "Embarazo", "Inmunosupresion", "Anticonceptivos orales de alta dosis", "Ropa ajustada y humeda"],
    "causasFactoresEn": ["Recent antibiotic use", "Poorly controlled diabetes", "Pregnancy", "Immunosuppression", "High-dose oral contraceptives", "Tight and damp clothing"],
    "diagnosticoEs": ["Examen fisico y descripcion de sintomas", "Examen en fresco con KOH (hifas y pseudohifas)", "pH vaginal normal (<4.5)", "Cultivo vaginal si es recurrente o no responde"],
    "diagnosticoEn": ["Physical exam and symptom description", "Wet mount with KOH (hyphae and pseudohyphae)", "Normal vaginal pH (<4.5)", "Vaginal culture if recurrent or non-responsive"],
    "tratamientosEs": ["Fluconazol oral 150mg dosis unica (no complicada)", "Miconazol o clotrimazol ovulos vaginales", "Recurrente: fluconazol semanal por 6 meses", "Acido borico vaginal para Candida no-albicans"],
    "tratamientosEn": ["Oral fluconazole 150mg single dose (uncomplicated)", "Miconazole or clotrimazole vaginal ovules", "Recurrent: weekly fluconazole for 6 months", "Vaginal boric acid for non-albicans Candida"],
    "prevencionEs": ["Ropa interior de algodon", "Evitar ropa ajustada y humeda", "No usar duchas vaginales", "Control adecuado de diabetes"],
    "prevencionEn": ["Cotton underwear", "Avoid tight damp clothing", "Do not use vaginal douches", "Adequate diabetes control"],
    "cuandoConsultarEs": ["Primera vez que presenta sintomas", "4 o mas episodios al ano", "Sintomas que no mejoran con tratamiento", "Embarazada con sintomas"],
    "cuandoConsultarEn": ["First time experiencing symptoms", "4 or more episodes per year", "Symptoms not improving with treatment", "Pregnant with symptoms"],
    "datosClaveEs": ["75% de mujeres tendran al menos un episodio", "5-8% tienen candidiasis recurrente", "No es una ITS pero puede transmitirse sexualmente"],
    "datosClaveEn": ["75% of women will have at least one episode", "5-8% have recurrent candidiasis", "Not an STI but can be sexually transmitted"],
    "edadRiesgo": "15-50 anos",
    "afectaPorcentaje": "75% al menos una vez en la vida"
  },
  {
    "id": "sm-incontinencia-urinaria",
    "nombreEs": "Incontinencia Urinaria Femenina",
    "nombreEn": "Female Urinary Incontinence",
    "categoriaEs": "Uroginecologica",
    "categoriaEn": "Urogynecological",
    "descripcionEs": "Perdida involuntaria de orina que afecta la calidad de vida. Los tipos principales son: de esfuerzo (al toser, reir, ejercicio), de urgencia (vejiga hiperactiva) y mixta. Es mas comun de lo que se reporta por vergüenza.",
    "descripcionEn": "Involuntary loss of urine affecting quality of life. Main types are: stress (coughing, laughing, exercise), urgency (overactive bladder), and mixed. More common than reported due to embarrassment.",
    "sintomasEs": ["Escape de orina al toser, estornudar o hacer ejercicio (esfuerzo)", "Urgencia subita e incontrolable de orinar (urgencia)", "Orinar mas de 8 veces al dia", "Levantarse mas de 2 veces por la noche a orinar", "Sensacion de vaciamiento incompleto"],
    "sintomasEn": ["Urine leakage when coughing, sneezing or exercising (stress)", "Sudden uncontrollable urge to urinate (urgency)", "Urinating more than 8 times daily", "Waking more than 2 times at night to urinate", "Sensation of incomplete emptying"],
    "causasFactoresEs": ["Embarazo y parto vaginal (dano al piso pelvico)", "Menopausia y deficiencia de estrogenos", "Obesidad", "Cirugia pelvica previa", "Envejecimiento", "Tos cronica"],
    "causasFactoresEn": ["Pregnancy and vaginal delivery (pelvic floor damage)", "Menopause and estrogen deficiency", "Obesity", "Prior pelvic surgery", "Aging", "Chronic cough"],
    "diagnosticoEs": ["Historia clinica detallada y diario miccional", "Examen pelvico", "Analisis de orina para descartar infeccion", "Estudio urodinamico en casos complejos", "Ultrasonido vesical post-miccional"],
    "diagnosticoEn": ["Detailed clinical history and voiding diary", "Pelvic exam", "Urinalysis to rule out infection", "Urodynamic study in complex cases", "Post-void bladder ultrasound"],
    "tratamientosEs": ["Ejercicios de Kegel (fortalecimiento del piso pelvico)", "Entrenamiento vesical (aumentar intervalos entre micciones)", "Perdida de peso si hay sobrepeso", "Estrogeno vaginal topico en postmenopausia", "Anticolinergicos para vejiga hiperactiva (oxibutinina, tolterodina)", "Cirugia con cinta suburetral (TVT/TOT) para esfuerzo severa"],
    "tratamientosEn": ["Kegel exercises (pelvic floor strengthening)", "Bladder training (increasing intervals between voiding)", "Weight loss if overweight", "Topical vaginal estrogen in postmenopause", "Anticholinergics for overactive bladder (oxybutynin, tolterodine)", "Suburethral sling surgery (TVT/TOT) for severe stress"],
    "prevencionEs": ["Ejercicios de Kegel desde el embarazo", "Mantener peso saludable", "Tratar estrenimiento cronico", "Evitar cargar objetos muy pesados"],
    "prevencionEn": ["Kegel exercises from pregnancy", "Maintain healthy weight", "Treat chronic constipation", "Avoid lifting very heavy objects"],
    "cuandoConsultarEs": ["Escape de orina que afecta actividades diarias", "Necesidad de usar protectores diariamente", "Infecciones urinarias recurrentes asociadas"],
    "cuandoConsultarEn": ["Urine leakage affecting daily activities", "Need to use pads daily", "Associated recurrent urinary infections"],
    "datosClaveEs": ["Afecta al 25-45% de mujeres adultas", "Solo el 25% busca atencion medica", "Es tratable y curable en la mayoria de casos"],
    "datosClaveEn": ["Affects 25-45% of adult women", "Only 25% seek medical attention", "Treatable and curable in most cases"],
    "edadRiesgo": ">40 anos, aumenta con la edad",
    "afectaPorcentaje": "25-45% de mujeres adultas"
  },
  {
    "id": "sm-osteoporosis-postmenopausica",
    "nombreEs": "Osteoporosis Postmenopausica",
    "nombreEn": "Postmenopausal Osteoporosis",
    "categoriaEs": "Musculoesqueletica/Endocrina",
    "categoriaEn": "Musculoskeletal/Endocrine",
    "descripcionEs": "Enfermedad esqueletica caracterizada por disminucion de la densidad osea y deterioro de la microarquitectura, aumentando la fragilidad y riesgo de fracturas. La perdida acelerada de hueso ocurre en los primeros 5-7 anos post-menopausia.",
    "descripcionEn": "Skeletal disease characterized by decreased bone density and microarchitecture deterioration, increasing fragility and fracture risk. Accelerated bone loss occurs in the first 5-7 years post-menopause.",
    "sintomasEs": ["Generalmente asintomatica hasta que ocurre fractura", "Perdida de estatura progresiva", "Cifosis dorsal (joroba de viuda)", "Dolor de espalda por fracturas vertebrales por compresion", "Fracturas por traumatismo minimo"],
    "sintomasEn": ["Generally asymptomatic until fracture occurs", "Progressive height loss", "Dorsal kyphosis (dowager's hump)", "Back pain from vertebral compression fractures", "Fractures from minimal trauma"],
    "causasFactoresEs": ["Deficiencia de estrogenos post-menopausia", "Baja ingesta de calcio y vitamina D", "Sedentarismo", "Historia familiar de osteoporosis", "Bajo peso corporal", "Tabaquismo y alcoholismo", "Uso cronico de corticosteroides"],
    "causasFactoresEn": ["Estrogen deficiency post-menopause", "Low calcium and vitamin D intake", "Sedentary lifestyle", "Family history of osteoporosis", "Low body weight", "Smoking and alcoholism", "Chronic corticosteroid use"],
    "diagnosticoEs": ["Densitometria osea (DEXA) — T-score <=-2.5", "FRAX para calcular riesgo de fractura a 10 anos", "Radiografia si se sospecha fractura vertebral", "Laboratorios: calcio, vitamina D, PTH, funcion renal"],
    "diagnosticoEn": ["Bone densitometry (DEXA) — T-score <=-2.5", "FRAX to calculate 10-year fracture risk", "X-ray if vertebral fracture suspected", "Labs: calcium, vitamin D, PTH, renal function"],
    "tratamientosEs": ["Calcio 1200mg/dia + vitamina D 800-1000 UI/dia", "Bisfosfonatos (alendronato, risedronato) primera linea", "Denosumab cada 6 meses", "Teriparatida (anabolico oseo) para osteoporosis severa", "Ejercicio de carga de peso", "Prevencion de caidas"],
    "tratamientosEn": ["Calcium 1200mg/day + vitamin D 800-1000 IU/day", "Bisphosphonates (alendronate, risedronate) first line", "Denosumab every 6 months", "Teriparatide (bone anabolic) for severe osteoporosis", "Weight-bearing exercise", "Fall prevention"],
    "prevencionEs": ["Ejercicio de carga de peso regular desde la juventud", "Ingesta adecuada de calcio y vitamina D", "No fumar", "Limitar alcohol", "Densitometria de tamizaje a los 65 anos"],
    "prevencionEn": ["Regular weight-bearing exercise from youth", "Adequate calcium and vitamin D intake", "Do not smoke", "Limit alcohol", "Screening densitometry at age 65"],
    "cuandoConsultarEs": ["Fractura por traumatismo minimo", "Perdida de estatura >3 cm", "Dolor de espalda nuevo despues de los 50", "Historia familiar fuerte de osteoporosis"],
    "cuandoConsultarEn": ["Fracture from minimal trauma", "Height loss >3 cm", "New back pain after age 50", "Strong family history of osteoporosis"],
    "datosClaveEs": ["1 de cada 3 mujeres >50 anos sufrira fractura osteoporotica", "Fractura de cadera tiene 20% mortalidad al ano", "La masa osea maxima se alcanza a los 30 anos"],
    "datosClaveEn": ["1 in 3 women >50 will suffer an osteoporotic fracture", "Hip fracture has 20% one-year mortality", "Peak bone mass is reached at age 30"],
    "edadRiesgo": ">50 anos, mayor riesgo >65",
    "afectaPorcentaje": "30% de mujeres postmenopausicas"
  },
  {
    "id": "sm-infeccion-urinaria-recurrente",
    "nombreEs": "Infecciones Urinarias Recurrentes",
    "nombreEn": "Recurrent Urinary Tract Infections",
    "categoriaEs": "Urologica/Ginecologica",
    "categoriaEn": "Urological/Gynecological",
    "descripcionEs": "Definida como 3 o mas infecciones urinarias en un ano o 2 o mas en 6 meses. Las mujeres son mas susceptibles por la uretra corta y su proximidad al area perianal. E. coli causa el 80-90% de los casos.",
    "descripcionEn": "Defined as 3 or more UTIs in a year or 2 or more in 6 months. Women are more susceptible due to short urethra and proximity to perianal area. E. coli causes 80-90% of cases.",
    "sintomasEs": ["Ardor y dolor al orinar (disuria)", "Urgencia y frecuencia urinaria", "Orina turbia o con olor fuerte", "Dolor suprapubico", "Hematuria (sangre en orina)"],
    "sintomasEn": ["Burning and pain with urination (dysuria)", "Urgency and urinary frequency", "Cloudy or strong-smelling urine", "Suprapubic pain", "Hematuria (blood in urine)"],
    "causasFactoresEs": ["Relaciones sexuales frecuentes", "Uso de espermicidas y diafragma", "Menopausia (atrofia vaginal)", "Antecedente de ITU en la infancia", "Anomalias anatomicas", "Diabetes mellitus"],
    "causasFactoresEn": ["Frequent sexual intercourse", "Use of spermicides and diaphragm", "Menopause (vaginal atrophy)", "History of childhood UTI", "Anatomical abnormalities", "Diabetes mellitus"],
    "diagnosticoEs": ["Urocultivo con >100,000 UFC/mL", "Analisis de orina con esterasa leucocitaria y nitritos", "Ultrasonido renal y vesical si hay sospecha de anomalia", "Cistoscopia en casos seleccionados"],
    "diagnosticoEn": ["Urine culture with >100,000 CFU/mL", "Urinalysis with leukocyte esterase and nitrites", "Renal and bladder ultrasound if anomaly suspected", "Cystoscopy in selected cases"],
    "tratamientosEs": ["Antibioticos segun cultivo y sensibilidad", "Trimetoprim-sulfametoxazol o nitrofurantoina primera linea", "Profilaxis antibiotica post-coital o continua a dosis baja", "Estrogeno vaginal en postmenopausicas", "Arandano (evidencia limitada pero bajo riesgo)"],
    "tratamientosEn": ["Antibiotics based on culture and sensitivity", "Trimethoprim-sulfamethoxazole or nitrofurantoin first line", "Post-coital or continuous low-dose antibiotic prophylaxis", "Vaginal estrogen in postmenopausal women", "Cranberry (limited evidence but low risk)"],
    "prevencionEs": ["Orinar despues de relaciones sexuales", "Buena hidratacion (2-3 litros/dia)", "Limpiarse de adelante hacia atras", "Evitar espermicidas", "No aguantar las ganas de orinar"],
    "prevencionEn": ["Urinate after sexual intercourse", "Good hydration (2-3 liters/day)", "Wipe front to back", "Avoid spermicides", "Do not hold urine"],
    "cuandoConsultarEs": ["3 o mas infecciones en un ano", "Fiebre, dolor lumbar o escalofrios (posible pielonefritis)", "Sangre en orina", "Sintomas que no mejoran en 48h con antibioticos"],
    "cuandoConsultarEn": ["3 or more infections in a year", "Fever, back pain or chills (possible pyelonephritis)", "Blood in urine", "Symptoms not improving in 48h with antibiotics"],
    "datosClaveEs": ["50-60% de mujeres tendran al menos una ITU en su vida", "27% tendran recurrencia en 6 meses", "La resistencia a antibioticos es un problema creciente"],
    "datosClaveEn": ["50-60% of women will have at least one UTI in their lifetime", "27% will have recurrence within 6 months", "Antibiotic resistance is a growing problem"],
    "edadRiesgo": "Todas las edades, picos en edad sexual activa y postmenopausia",
    "afectaPorcentaje": "50-60% al menos una vez, 20-30% recurrente"
  },
  {
    "id": "sm-enfermedad-inflamatoria-pelvica",
    "nombreEs": "Enfermedad Inflamatoria Pelvica (EIP)",
    "nombreEn": "Pelvic Inflammatory Disease (PID)",
    "categoriaEs": "Infecciosa/Ginecologica",
    "categoriaEn": "Infectious/Gynecological",
    "descripcionEs": "Infeccion ascendente del tracto genital superior femenino que afecta utero, trompas de Falopio y ovarios. Usualmente causada por Chlamydia trachomatis o Neisseria gonorrhoeae. Es la principal causa prevenible de infertilidad tubaria.",
    "descripcionEn": "Ascending infection of the female upper genital tract affecting uterus, fallopian tubes, and ovaries. Usually caused by Chlamydia trachomatis or Neisseria gonorrhoeae. It is the leading preventable cause of tubal infertility.",
    "sintomasEs": ["Dolor pelvico bilateral", "Flujo vaginal anormal purulento", "Sangrado intermenstrual o postcoital", "Fiebre y malestar general", "Dolor a la movilizacion cervical en examen"],
    "sintomasEn": ["Bilateral pelvic pain", "Abnormal purulent vaginal discharge", "Intermenstrual or postcoital bleeding", "Fever and malaise", "Cervical motion tenderness on exam"],
    "causasFactoresEs": ["Infeccion por Chlamydia o gonorrea no tratada", "Multiples parejas sexuales", "Edad <25 anos", "No uso de condon", "DIU (pequeño riesgo en primeras 3 semanas)"],
    "causasFactoresEn": ["Untreated Chlamydia or gonorrhea infection", "Multiple sexual partners", "Age <25 years", "No condom use", "IUD (small risk in first 3 weeks)"],
    "diagnosticoEs": ["Criterios clinicos: dolor pelvico + sensibilidad anexial o cervical", "Pruebas de Chlamydia y gonorrea", "PCR elevada, VSG", "Ultrasonido pelvico (absceso tubo-ovarico)", "Laparoscopia en casos dudosos"],
    "diagnosticoEn": ["Clinical criteria: pelvic pain + adnexal or cervical tenderness", "Chlamydia and gonorrhea testing", "Elevated CRP, ESR", "Pelvic ultrasound (tubo-ovarian abscess)", "Laparoscopy in doubtful cases"],
    "tratamientosEs": ["Tratamiento empirico con antibioticos de amplio espectro", "Ambulatorio: ceftriaxona IM + doxiciclina oral +/- metronidazol", "Hospitalario: cefoxitina IV + doxiciclina", "Tratar a la pareja sexual", "Drenaje quirurgico de absceso tubo-ovarico si no responde"],
    "tratamientosEn": ["Empiric broad-spectrum antibiotic treatment", "Outpatient: IM ceftriaxone + oral doxycycline +/- metronidazole", "Inpatient: IV cefoxitin + doxycycline", "Treat sexual partner", "Surgical drainage of tubo-ovarian abscess if unresponsive"],
    "prevencionEs": ["Uso correcto y constante de condon", "Tamizaje anual de Chlamydia en mujeres <25 anos", "Tratamiento rapido de ITS", "Tratamiento de la pareja"],
    "prevencionEn": ["Correct and consistent condom use", "Annual Chlamydia screening in women <25", "Prompt STI treatment", "Partner treatment"],
    "cuandoConsultarEs": ["Dolor pelvico con fiebre", "Flujo vaginal anormal con dolor", "Antecedente de ITS reciente con dolor pelvico nuevo"],
    "cuandoConsultarEn": ["Pelvic pain with fever", "Abnormal vaginal discharge with pain", "Recent STI history with new pelvic pain"],
    "datosClaveEs": ["Cada episodio de EIP duplica el riesgo de infertilidad", "25% de mujeres con EIP desarrollan secuelas a largo plazo", "El 85% de casos es por ITS no tratadas"],
    "datosClaveEn": ["Each PID episode doubles infertility risk", "25% of women with PID develop long-term sequelae", "85% of cases are from untreated STIs"],
    "edadRiesgo": "15-25 anos",
    "afectaPorcentaje": "4-12% de mujeres jovenes sexualmente activas"
  },
  {
    "id": "sm-quistes-ovaricos",
    "nombreEs": "Quistes Ovaricos",
    "nombreEn": "Ovarian Cysts",
    "categoriaEs": "Ginecologica",
    "categoriaEn": "Gynecological",
    "descripcionEs": "Sacos llenos de liquido en o sobre los ovarios. La mayoria son funcionales (foliculos o cuerpo luteo) y se resuelven espontaneamente. Los quistes no funcionales incluyen endometriomas, dermoides y cistoadenomas que pueden requerir cirugia.",
    "descripcionEn": "Fluid-filled sacs on or within ovaries. Most are functional (follicular or corpus luteum) and resolve spontaneously. Non-functional cysts include endometriomas, dermoids, and cystadenomas that may require surgery.",
    "sintomasEs": ["Dolor pelvico unilateral intermitente", "Sensacion de presion o pesadez pelvica", "Hinchazon abdominal", "Dolor agudo subito si hay ruptura o torsion", "Irregularidad menstrual"],
    "sintomasEn": ["Intermittent unilateral pelvic pain", "Pelvic pressure or heaviness sensation", "Abdominal bloating", "Sudden acute pain if rupture or torsion", "Menstrual irregularity"],
    "causasFactoresEs": ["Proceso normal de ovulacion (funcionales)", "Endometriosis (endometriomas)", "Celulas germinales (dermoides)", "Estimulacion ovarica por medicamentos de fertilidad"],
    "causasFactoresEn": ["Normal ovulation process (functional)", "Endometriosis (endometriomas)", "Germ cells (dermoids)", "Ovarian stimulation by fertility medications"],
    "diagnosticoEs": ["Ultrasonido transvaginal (primer estudio)", "Marcadores tumorales (CA-125) si >40 anos", "Resonancia magnetica para quistes indeterminados", "Doppler para evaluar flujo sanguineo"],
    "diagnosticoEn": ["Transvaginal ultrasound (first study)", "Tumor markers (CA-125) if >40 years", "MRI for indeterminate cysts", "Doppler to evaluate blood flow"],
    "tratamientosEs": ["Observacion con ultrasonido de seguimiento (quistes funcionales <5cm)", "Anticonceptivos orales para prevenir nuevos quistes funcionales", "Cirugia laparoscopica para quistes persistentes >5cm", "Ooforectomia si hay sospecha de malignidad"],
    "tratamientosEn": ["Observation with follow-up ultrasound (functional cysts <5cm)", "Oral contraceptives to prevent new functional cysts", "Laparoscopic surgery for persistent cysts >5cm", "Oophorectomy if malignancy suspected"],
    "prevencionEs": ["No hay prevencion para quistes funcionales", "Anticonceptivos orales reducen formacion de quistes funcionales", "Control ginecologico regular"],
    "prevencionEn": ["No prevention for functional cysts", "Oral contraceptives reduce functional cyst formation", "Regular gynecological checkups"],
    "cuandoConsultarEs": ["Dolor pelvico agudo y severo (posible torsion — urgencia)", "Dolor pelvico con fiebre", "Quiste que persiste mas de 3 ciclos menstruales"],
    "cuandoConsultarEn": ["Acute severe pelvic pain (possible torsion — emergency)", "Pelvic pain with fever", "Cyst persisting more than 3 menstrual cycles"],
    "datosClaveEs": ["La mayoria de quistes funcionales desaparecen en 2-3 ciclos", "La torsion ovarica es una emergencia quirurgica", "Quistes en postmenopausicas requieren mas atencion"],
    "datosClaveEn": ["Most functional cysts disappear in 2-3 cycles", "Ovarian torsion is a surgical emergency", "Cysts in postmenopausal women require more attention"],
    "edadRiesgo": "15-50 anos (funcionales), cualquier edad (no funcionales)",
    "afectaPorcentaje": "7-10% de mujeres"
  },
  {
    "id": "sm-embarazo-ectopico",
    "nombreEs": "Embarazo Ectopico",
    "nombreEn": "Ectopic Pregnancy",
    "categoriaEs": "Obstetrica/Emergencia",
    "categoriaEn": "Obstetric/Emergency",
    "descripcionEs": "Implantacion del embrion fuera del utero, mas frecuentemente en la trompa de Falopio (95%). Es una emergencia potencialmente mortal si se rompe, causando hemorragia intraabdominal. No es un embarazo viable.",
    "descripcionEn": "Embryo implantation outside the uterus, most frequently in the fallopian tube (95%). It is a potentially life-threatening emergency if ruptured, causing intra-abdominal hemorrhage. Not a viable pregnancy.",
    "sintomasEs": ["Dolor pelvico unilateral agudo", "Sangrado vaginal anormal en embarazo temprano", "Mareo o desmayo (si hay ruptura)", "Dolor de hombro (irritacion diafragmatica por sangre)", "Prueba de embarazo positiva con sintomas"],
    "sintomasEn": ["Acute unilateral pelvic pain", "Abnormal vaginal bleeding in early pregnancy", "Dizziness or fainting (if ruptured)", "Shoulder pain (diaphragmatic irritation from blood)", "Positive pregnancy test with symptoms"],
    "causasFactoresEs": ["EIP previa o cirugia tubaria", "Embarazo ectopico previo", "DIU en su lugar", "Tratamientos de fertilidad", "Tabaquismo", "Endometriosis"],
    "causasFactoresEn": ["Previous PID or tubal surgery", "Previous ectopic pregnancy", "IUD in place", "Fertility treatments", "Smoking", "Endometriosis"],
    "diagnosticoEs": ["Beta-hCG seriada (no duplica cada 48h como en embarazo normal)", "Ultrasonido transvaginal: utero vacio con hCG >1500-2000", "Masa anexial en ultrasonido", "Liquido libre en fondo de saco"],
    "diagnosticoEn": ["Serial beta-hCG (does not double every 48h as in normal pregnancy)", "Transvaginal ultrasound: empty uterus with hCG >1500-2000", "Adnexal mass on ultrasound", "Free fluid in cul-de-sac"],
    "tratamientosEs": ["Metotrexato IM (si <3.5cm, sin ruptura, hCG <5000)", "Salpingostomia o salpingectomia laparoscopica", "Cirugia de emergencia si hay ruptura con inestabilidad", "Seguimiento de hCG hasta llegar a cero"],
    "tratamientosEn": ["IM methotrexate (if <3.5cm, no rupture, hCG <5000)", "Laparoscopic salpingostomy or salpingectomy", "Emergency surgery if ruptured with instability", "hCG monitoring until zero"],
    "prevencionEs": ["Tratamiento temprano de ITS (previene dano tubario)", "No fumar", "Consulta temprana ante sospecha de embarazo con dolor"],
    "prevencionEn": ["Early STI treatment (prevents tubal damage)", "Do not smoke", "Early consultation for suspected pregnancy with pain"],
    "cuandoConsultarEs": ["Prueba positiva con dolor pelvico (URGENTE)", "Sangrado vaginal en embarazo temprano con dolor", "Mareo subito con prueba de embarazo positiva (EMERGENCIA)"],
    "cuandoConsultarEn": ["Positive test with pelvic pain (URGENT)", "Vaginal bleeding in early pregnancy with pain", "Sudden dizziness with positive pregnancy test (EMERGENCY)"],
    "datosClaveEs": ["Representa el 1-2% de todos los embarazos", "Es la principal causa de muerte materna en el primer trimestre", "10-15% de recurrencia despues del primero"],
    "datosClaveEn": ["Represents 1-2% of all pregnancies", "Leading cause of maternal death in first trimester", "10-15% recurrence after the first"],
    "edadRiesgo": "Cualquier edad reproductiva",
    "afectaPorcentaje": "1-2% de embarazos"
  },
  {
    "id": "sm-mastitis",
    "nombreEs": "Mastitis",
    "nombreEn": "Mastitis",
    "categoriaEs": "Obstetrica/Mamaria",
    "categoriaEn": "Obstetric/Breast",
    "descripcionEs": "Infeccion del tejido mamario que ocurre frecuentemente durante la lactancia. Causada usualmente por Staphylococcus aureus que entra a traves de grietas en el pezon. Puede progresar a absceso mamario si no se trata.",
    "descripcionEn": "Breast tissue infection frequently occurring during breastfeeding. Usually caused by Staphylococcus aureus entering through nipple cracks. Can progress to breast abscess if untreated.",
    "sintomasEs": ["Dolor mamario localizado e intenso", "Enrojecimiento en forma de cuna en la mama", "Hinchazon y calor en el area afectada", "Fiebre >38.5C y escalofrios", "Sintomas gripales: malestar, fatiga"],
    "sintomasEn": ["Localized intense breast pain", "Wedge-shaped redness on breast", "Swelling and warmth in affected area", "Fever >101.3F and chills", "Flu-like symptoms: malaise, fatigue"],
    "causasFactoresEs": ["Estasis de leche (vaciamiento incompleto)", "Grietas o heridas en el pezon", "Tecnica de lactancia inadecuada", "Estres y fatiga materna", "Sujetador muy apretado"],
    "causasFactoresEn": ["Milk stasis (incomplete emptying)", "Nipple cracks or wounds", "Inadequate breastfeeding technique", "Maternal stress and fatigue", "Very tight bra"],
    "diagnosticoEs": ["Diagnostico clinico (historia y examen fisico)", "Cultivo de leche si no responde a tratamiento", "Ultrasonido si se sospecha absceso"],
    "diagnosticoEn": ["Clinical diagnosis (history and physical exam)", "Milk culture if not responding to treatment", "Ultrasound if abscess suspected"],
    "tratamientosEs": ["Continuar lactancia (NO suspender — es terapeutico)", "Antibioticos: dicloxacilina o cefalexina por 10-14 dias", "Analgesicos (ibuprofeno es preferido — antiinflamatorio)", "Compresas tibias antes de amamantar", "Drenaje quirurgico si hay absceso"],
    "tratamientosEn": ["Continue breastfeeding (do NOT stop — it is therapeutic)", "Antibiotics: dicloxacillin or cephalexin for 10-14 days", "Analgesics (ibuprofen preferred — anti-inflammatory)", "Warm compresses before nursing", "Surgical drainage if abscess present"],
    "prevencionEs": ["Vaciamiento completo de ambas mamas en cada toma", "Tecnica correcta de agarre del bebe", "Alternar posiciones de lactancia", "Tratar grietas del pezon tempranamente"],
    "prevencionEn": ["Complete emptying of both breasts at each feeding", "Correct baby latching technique", "Alternate breastfeeding positions", "Treat nipple cracks early"],
    "cuandoConsultarEs": ["Fiebre con dolor mamario durante la lactancia", "Masa fluctuante en la mama (posible absceso)", "No mejora en 48 horas de antibioticos"],
    "cuandoConsultarEn": ["Fever with breast pain during breastfeeding", "Fluctuant mass in breast (possible abscess)", "No improvement after 48 hours of antibiotics"],
    "datosClaveEs": ["Afecta al 10-33% de mujeres lactantes", "Mas comun en las primeras 6 semanas de lactancia", "La lactancia NO debe suspenderse durante el tratamiento"],
    "datosClaveEn": ["Affects 10-33% of breastfeeding women", "Most common in first 6 weeks of breastfeeding", "Breastfeeding should NOT be stopped during treatment"],
    "edadRiesgo": "Cualquier edad durante la lactancia",
    "afectaPorcentaje": "10-33% de mujeres lactantes"
  },
  {
    "id": "sm-dismenorrea",
    "nombreEs": "Dismenorrea (Dolor Menstrual)",
    "nombreEn": "Dysmenorrhea (Menstrual Pain)",
    "categoriaEs": "Trastornos Menstruales",
    "categoriaEn": "Menstrual Disorders",
    "descripcionEs": "Dolor menstrual calambriforme en bajo vientre que puede irradiar a espalda y muslos. La primaria (sin patologia) es causada por prostaglandinas. La secundaria es causada por condiciones como endometriosis, miomas o adenomiosis.",
    "descripcionEn": "Cramping menstrual pain in the lower abdomen that may radiate to back and thighs. Primary (no pathology) is caused by prostaglandins. Secondary is caused by conditions like endometriosis, fibroids, or adenomyosis.",
    "sintomasEs": ["Dolor calambriforme en hipogastrio que inicia con la menstruacion", "Dolor que irradia a region lumbar y muslos", "Nauseas, diarrea, dolor de cabeza", "Fatiga y malestar general", "Dura 1-3 dias del ciclo"],
    "sintomasEn": ["Cramping pain in lower abdomen starting with menstruation", "Pain radiating to lower back and thighs", "Nausea, diarrhea, headache", "Fatigue and malaise", "Lasts 1-3 days of cycle"],
    "causasFactoresEs": ["Primaria: exceso de prostaglandinas uterinas", "Secundaria: endometriosis, miomas, adenomiosis, EIP", "Menarquia temprana (<12 anos)", "Flujo menstrual abundante", "Tabaquismo y estres"],
    "causasFactoresEn": ["Primary: excess uterine prostaglandins", "Secondary: endometriosis, fibroids, adenomyosis, PID", "Early menarche (<12 years)", "Heavy menstrual flow", "Smoking and stress"],
    "diagnosticoEs": ["Historia clinica (edad de inicio, patron del dolor)", "Examen pelvico para descartar causa secundaria", "Ultrasonido pelvico si hay sospecha de patologia", "Laparoscopia si se sospecha endometriosis"],
    "diagnosticoEn": ["Clinical history (age of onset, pain pattern)", "Pelvic exam to rule out secondary cause", "Pelvic ultrasound if pathology suspected", "Laparoscopy if endometriosis suspected"],
    "tratamientosEs": ["AINEs (ibuprofeno 400-600mg cada 6-8h) iniciados antes del dolor", "Anticonceptivos hormonales (reducen prostaglandinas)", "Calor local en bajo vientre", "Ejercicio regular", "Acido tranexamico si hay menorragia asociada"],
    "tratamientosEn": ["NSAIDs (ibuprofen 400-600mg every 6-8h) started before pain", "Hormonal contraceptives (reduce prostaglandins)", "Local heat on lower abdomen", "Regular exercise", "Tranexamic acid if associated menorrhagia"],
    "prevencionEs": ["Ejercicio aerobico regular", "Dieta antiinflamatoria (omega-3)", "Iniciar AINEs 1-2 dias antes de menstruacion", "Manejo del estres"],
    "prevencionEn": ["Regular aerobic exercise", "Anti-inflammatory diet (omega-3)", "Start NSAIDs 1-2 days before menstruation", "Stress management"],
    "cuandoConsultarEs": ["Dolor que no responde a AINEs", "Dolor que empeora progresivamente con los anos", "Dolor fuera del periodo menstrual", "Inicio de dolor menstrual severo despues de los 25 anos (sugiere causa secundaria)"],
    "cuandoConsultarEn": ["Pain not responding to NSAIDs", "Pain progressively worsening over years", "Pain outside menstrual period", "Onset of severe menstrual pain after age 25 (suggests secondary cause)"],
    "datosClaveEs": ["Afecta al 50-90% de mujeres en edad reproductiva", "Es la causa mas comun de ausentismo escolar y laboral en mujeres", "La primaria suele mejorar despues de los 30 y con los embarazos"],
    "datosClaveEn": ["Affects 50-90% of reproductive-age women", "Most common cause of school and work absenteeism in women", "Primary usually improves after 30 and with pregnancies"],
    "edadRiesgo": "15-25 anos (primaria), cualquier edad (secundaria)",
    "afectaPorcentaje": "50-90% de mujeres"
  },
  {
    "id": "sm-prolapso-pelvico",
    "nombreEs": "Prolapso de Organos Pelvicos",
    "nombreEn": "Pelvic Organ Prolapse",
    "categoriaEs": "Uroginecologica",
    "categoriaEn": "Urogynecological",
    "descripcionEs": "Descenso de organos pelvicos (vejiga, utero, recto) por debilidad del piso pelvico. Puede ser cistocele (vejiga), rectocele (recto), uterocele (utero) o enterocele (intestino delgado). Afecta significativamente la calidad de vida.",
    "descripcionEn": "Descent of pelvic organs (bladder, uterus, rectum) due to pelvic floor weakness. Can be cystocele (bladder), rectocele (rectum), uterocele (uterus), or enterocele (small bowel). Significantly affects quality of life.",
    "sintomasEs": ["Sensacion de bulto o presion vaginal", "Sensacion de que algo se sale por la vagina", "Dolor lumbar que empeora al estar de pie", "Dificultad para vaciar la vejiga completamente", "Dificultad para defecar (necesidad de reducir manualmente)"],
    "sintomasEn": ["Sensation of vaginal bulge or pressure", "Feeling of something coming out of the vagina", "Back pain worsening when standing", "Difficulty completely emptying bladder", "Difficulty defecating (need to manually reduce)"],
    "causasFactoresEs": ["Partos vaginales multiples", "Menopausia y deficiencia de estrogenos", "Obesidad", "Tos cronica y estrenimiento (pujo repetido)", "Histerectomia previa", "Trabajo fisico pesado"],
    "causasFactoresEn": ["Multiple vaginal deliveries", "Menopause and estrogen deficiency", "Obesity", "Chronic cough and constipation (repeated straining)", "Previous hysterectomy", "Heavy physical labor"],
    "diagnosticoEs": ["Examen fisico con maniobra de Valsalva", "Clasificacion POP-Q (estadificacion)", "Evaluacion de defectos especificos", "Estudio urodinamico si hay incontinencia"],
    "diagnosticoEn": ["Physical exam with Valsalva maneuver", "POP-Q classification (staging)", "Specific defect evaluation", "Urodynamic study if incontinence present"],
    "tratamientosEs": ["Ejercicios de Kegel y fisioterapia del piso pelvico", "Pesario vaginal (dispositivo de soporte)", "Estrogeno vaginal topico", "Cirugia reconstructiva del piso pelvico", "Colpocleisis (cierre vaginal) en pacientes ancianas"],
    "tratamientosEn": ["Kegel exercises and pelvic floor physical therapy", "Vaginal pessary (support device)", "Topical vaginal estrogen", "Pelvic floor reconstructive surgery", "Colpocleisis (vaginal closure) in elderly patients"],
    "prevencionEs": ["Ejercicios de Kegel regulares desde la juventud", "Evitar pujo excesivo (tratar estrenimiento)", "Mantener peso saludable", "Tecnica adecuada al levantar peso"],
    "prevencionEn": ["Regular Kegel exercises from youth", "Avoid excessive straining (treat constipation)", "Maintain healthy weight", "Proper lifting technique"],
    "cuandoConsultarEs": ["Sensacion de bulto vaginal", "Dificultad para orinar o defecar por prolapso", "Prolapso visible fuera de la vagina"],
    "cuandoConsultarEn": ["Sensation of vaginal bulge", "Difficulty urinating or defecating from prolapse", "Visible prolapse outside vagina"],
    "datosClaveEs": ["Afecta al 50% de mujeres con partos vaginales en algun grado", "Solo 10-20% tienen sintomas significativos", "No es peligroso pero afecta mucho la calidad de vida"],
    "datosClaveEn": ["Affects 50% of women with vaginal deliveries to some degree", "Only 10-20% have significant symptoms", "Not dangerous but greatly affects quality of life"],
    "edadRiesgo": ">50 anos",
    "afectaPorcentaje": "50% en algun grado post parto vaginal"
  }
]`);

// -----------------------------------------------------------------------------
// HELPER FUNCTIONS
// -----------------------------------------------------------------------------

export function buscarSaludMujer(query: string): SaludMujerEntry[] {
  const q = query.toLowerCase();
  return saludMujerEnciclopedia.filter(e =>
    e.nombreEs.toLowerCase().includes(q) ||
    e.nombreEn.toLowerCase().includes(q) ||
    e.categoriaEs.toLowerCase().includes(q) ||
    e.categoriaEn.toLowerCase().includes(q) ||
    e.descripcionEs.toLowerCase().includes(q) ||
    e.descripcionEn.toLowerCase().includes(q)
  );
}

export function getSaludMujerById(id: string): SaludMujerEntry | undefined {
  return saludMujerEnciclopedia.find(e => e.id === id);
}

export function getSaludMujerPorCategoria(cat: string): SaludMujerEntry[] {
  const c = cat.toLowerCase();
  return saludMujerEnciclopedia.filter(e =>
    e.categoriaEs.toLowerCase().includes(c) ||
    e.categoriaEn.toLowerCase().includes(c)
  );
}
