
// ============================================================================
// Drug-Food Interactions
// ============================================================================

import { DrugInteraction } from './database';

export const FOOD_INTERACTIONS: DrugInteraction[] = [
  {
    id: 'food-001',
    type: 'drug-food',
    severity: 'major',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { foods: ['leafy greens', 'spinach', 'kale', 'broccoli', 'brussels sprouts', 'vitamin K rich foods'] },
    description: 'Vitamin K is the antidote for warfarin. High intake reduces anticoagulant effect.',
    clinicalEffects: ['Decreased INR', 'Thrombosis risk', 'Treatment failure'],
    onset: 'rapid',
    recommendation: 'Keep vitamin K intake CONSISTENT, not absent. Sudden increases or decreases affect INR.',
    alternatives: ['Consistent diet', 'Discuss with anticoagulation clinic'],
    monitoringRequired: ['INR if diet changes'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-002',
    type: 'drug-food',
    severity: 'major',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { foods: ['cranberry juice', 'cranberry supplements'] },
    description: 'Cranberry may increase warfarin effect and bleeding risk.',
    clinicalEffects: ['Increased INR', 'Bleeding'],
    onset: 'delayed',
    recommendation: 'Avoid large amounts of cranberry products.',
    alternatives: ['Other juices'],
    monitoringRequired: ['INR if cranberry consumed'],
    evidenceLevel: 'case-reports'
  },
  {
    id: 'food-003',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'pharmacokinetic',
    primaryDrug: { name: 'Statins', genericNames: ['atorvastatin', 'simvastatin', 'lovastatin'], drugClasses: ['statins'] },
    interactsWith: { foods: ['grapefruit', 'grapefruit juice'] },
    description: 'Grapefruit inhibits intestinal CYP3A4, increasing statin absorption.',
    clinicalEffects: ['Increased statin levels', 'Myopathy risk', 'Rhabdomyolysis'],
    onset: 'rapid',
    recommendation: 'Avoid grapefruit with simvastatin, lovastatin, atorvastatin. Pravastatin and rosuvastatin are OK.',
    alternatives: ['Orange juice', 'Other citrus', 'Pravastatin', 'Rosuvastatin'],
    monitoringRequired: ['Muscle symptoms if grapefruit consumed'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-004',
    type: 'drug-food',
    severity: 'major',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'MAOIs', genericNames: ['phenelzine', 'tranylcypromine'], drugClasses: ['maois'] },
    interactsWith: { foods: ['aged cheese', 'red wine', 'fermented foods', 'cured meats', 'soy products', 'tyramine-rich foods'] },
    description: 'MAOIs block tyramine breakdown; high tyramine causes hypertensive crisis.',
    clinicalEffects: ['Hypertensive crisis', 'Severe headache', 'Stroke', 'Death'],
    onset: 'rapid',
    recommendation: 'Avoid all tyramine-rich foods while taking MAOIs and for 2 weeks after stopping.',
    alternatives: ['Follow dietary restrictions strictly'],
    monitoringRequired: ['Blood pressure', 'Headache'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-005',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'absorption-reduction',
    primaryDrug: { name: 'Tetracyclines', genericNames: ['tetracycline', 'doxycycline', 'minocycline'] },
    interactsWith: { foods: ['dairy', 'milk', 'cheese', 'yogurt', 'calcium supplements', 'antacids'] },
    description: 'Calcium binds tetracyclines in gut, preventing absorption.',
    clinicalEffects: ['Reduced antibiotic efficacy', 'Treatment failure'],
    onset: 'rapid',
    recommendation: 'Take tetracyclines 2 hours before or 4-6 hours after dairy/calcium.',
    alternatives: ['Time separation of doses'],
    monitoringRequired: ['Infection response'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-006',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'absorption-reduction',
    primaryDrug: { name: 'Fluoroquinolones', genericNames: ['ciprofloxacin', 'levofloxacin', 'moxifloxacin'], drugClasses: ['quinolones'] },
    interactsWith: { foods: ['dairy', 'milk', 'calcium-fortified foods', 'antacids'] },
    description: 'Cations (calcium, magnesium, aluminum) bind fluoroquinolones, reducing absorption.',
    clinicalEffects: ['Reduced antibiotic efficacy', 'Treatment failure'],
    onset: 'rapid',
    recommendation: 'Take fluoroquinolones 2 hours before or 6 hours after dairy/antacids.',
    alternatives: ['Time separation'],
    monitoringRequired: ['Infection response'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-007',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'absorption-reduction',
    primaryDrug: { name: 'Bisphosphonates', genericNames: ['alendronate', 'risedronate', 'ibandronate'] },
    interactsWith: { foods: ['food', 'beverages other than water', 'calcium supplements'] },
    description: 'Food and beverages markedly reduce bisphosphonate absorption.',
    clinicalEffects: ['Reduced drug efficacy', 'Treatment failure', 'Fracture risk'],
    onset: 'rapid',
    recommendation: 'Take first thing in morning with full glass of plain water, 30-60 minutes before any food/drink/medications.',
    alternatives: ['Strict fasting protocol'],
    monitoringRequired: ['Bone density', 'Fracture risk'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-008',
    type: 'drug-food',
    severity: 'minor',
    mechanism: 'pharmacokinetic',
    primaryDrug: { name: 'Metformin', genericNames: ['metformin'] },
    interactsWith: { foods: ['alcohol'] },
    description: 'Alcohol increases risk of lactic acidosis.',
    clinicalEffects: ['Lactic acidosis', 'Hypoglycemia'],
    onset: 'variable',
    recommendation: 'Limit alcohol. Avoid binge drinking.',
    alternatives: ['Moderate consumption only'],
    monitoringRequired: ['Symptoms of lactic acidosis'],
    evidenceLevel: 'theoretical'
  },
  {
    id: 'food-009',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'ACE Inhibitors', genericNames: ['lisinopril', 'enalapril'], drugClasses: ['ace-inhibitors'] },
    interactsWith: { foods: ['potassium supplements', 'salt substitutes', 'low-sodium salt'] },
    description: 'ACE inhibitors reduce potassium excretion; salt substitutes contain potassium.',
    clinicalEffects: ['Hyperkalemia', 'Arrhythmias'],
    onset: 'delayed',
    recommendation: 'Avoid potassium-containing salt substitutes.',
    alternatives: ['Regular salt in moderation', 'Herbs/spices'],
    monitoringRequired: ['Potassium levels'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-010',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'pharmacokinetic',
    primaryDrug: { name: 'Levothyroxine', genericNames: ['levothyroxine', 'synthroid'] },
    interactsWith: { foods: ['coffee', 'espresso', 'calcium supplements', 'iron supplements', 'soy', 'high-fiber foods'] },
    description: 'Coffee and other substances reduce levothyroxine absorption.',
    clinicalEffects: ['Reduced thyroid hormone levels', 'Hypothyroid symptoms'],
    onset: 'delayed',
    recommendation: 'Take levothyroxine on empty stomach 30-60 minutes before breakfast. Wait 4 hours before coffee/calcium/iron.',
    alternatives: ['Take at bedtime (4 hours after last meal)'],
    monitoringRequired: ['TSH level'],
    evidenceLevel: 'clinical-trial'
  },
  {
    id: 'food-011',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Lithium', genericNames: ['lithium carbonate'] },
    interactsWith: { foods: ['caffeine', 'coffee', 'soda'] },
    description: 'Caffeine increases lithium excretion; sudden cessation increases lithium levels.',
    clinicalEffects: ['Variable lithium levels', 'Toxicity if caffeine stopped suddenly'],
    onset: 'variable',
    recommendation: 'Keep caffeine intake consistent. If stopping caffeine, monitor lithium levels.',
    alternatives: ['Consistent intake'],
    monitoringRequired: ['Lithium level if caffeine intake changes'],
    evidenceLevel: 'case-reports'
  },
  {
    id: 'food-012',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Alendronate', genericNames: ['alendronate'] },
    interactsWith: { foods: ['coffee', 'tea', 'orange juice'] },
    description: 'Beverages other than water reduce alendronate absorption.',
    clinicalEffects: ['Reduced efficacy', 'Fracture risk'],
    onset: 'rapid',
    recommendation: 'Take only with plain water. Wait 30-60 minutes before any other beverage.',
    alternatives: ['Plain water only'],
    monitoringRequired: ['Bone density'],
    evidenceLevel: 'established'
  },
  {
    id: 'food-013',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'pharmacokinetic',
    primaryDrug: { name: 'Carvedilol', genericNames: ['carvedilol'], drugClasses: ['beta-blockers'] },
    interactsWith: { foods: ['grapefruit juice'] },
    description: 'Grapefruit increases carvedilol bioavailability.',
    clinicalEffects: ['Increased carvedilol levels', 'Hypotension', 'Bradycardia'],
    onset: 'rapid',
    recommendation: 'Avoid grapefruit juice with carvedilol.',
    alternatives: ['Other beverages'],
    monitoringRequired: ['Blood pressure', 'Heart rate'],
    evidenceLevel: 'clinical-trial'
  },
  {
    id: 'food-014',
    type: 'drug-food',
    severity: 'minor',
    mechanism: 'pharmacokinetic',
    primaryDrug: { name: 'Propranolol', genericNames: ['propranolol'], drugClasses: ['beta-blockers'] },
    interactsWith: { foods: ['protein-rich meals'] },
    description: 'Food increases propranolol bioavailability.',
    clinicalEffects: ['Increased propranolol levels'],
    onset: 'rapid',
    recommendation: 'Take consistently with or without food.',
    alternatives: ['Consistent administration'],
    monitoringRequired: ['Blood pressure', 'Heart rate'],
    evidenceLevel: 'clinical-trial'
  },
  {
    id: 'food-015',
    type: 'drug-food',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Insulin', genericNames: ['insulin'] },
    interactsWith: { foods: ['alcohol'] },
    description: 'Alcohol can cause hypoglycemia by blocking gluconeogenesis.',
    clinicalEffects: ['Hypoglycemia', 'Delayed hypoglycemia'],
    onset: 'variable',
    recommendation: 'Take alcohol with food. Monitor glucose.',
    alternatives: ['Consume with meals', 'Glucose monitoring'],
    monitoringRequired: ['Blood glucose'],
    evidenceLevel: 'established'
  }
];
