
// ============================================================================
// Drug-Supplement Interactions
// ============================================================================

import { DrugInteraction } from './database';

export const SUPPLEMENT_INTERACTIONS: DrugInteraction[] = [
  {
    id: 'supp-001',
    type: 'drug-supplement',
    severity: 'major',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'SSRIs', genericNames: ['sertraline', 'fluoxetine', 'paroxetine'], drugClasses: ['ssris'] },
    interactsWith: { supplements: ['St. John\'s Wort', '5-HTP', 'tryptophan'] },
    description: 'Additive serotonergic effects increase serotonin syndrome risk.',
    clinicalEffects: ['Serotonin syndrome', 'Agitation', 'Confusion', 'Tremor', 'Hyperthermia'],
    onset: 'variable',
    recommendation: 'Avoid St. John\'s Wort, 5-HTP, and tryptophan with SSRIs.',
    alternatives: ['Discuss with doctor before any supplement'],
    monitoringRequired: ['Mental status', 'Temperature'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-002',
    type: 'drug-supplement',
    severity: 'major',
    mechanism: 'bleeding-risk',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { supplements: ['fish oil', 'omega-3', 'high dose vitamin E', 'ginkgo', 'garlic supplements'] },
    description: 'These supplements have antiplatelet effects and increase bleeding risk.',
    clinicalEffects: ['Increased bleeding', 'Hemorrhage', 'Bruising'],
    onset: 'delayed',
    recommendation: 'Use supplements cautiously. Monitor INR more frequently.',
    alternatives: ['Low doses', 'INR monitoring'],
    monitoringRequired: ['INR', 'Signs of bleeding'],
    evidenceLevel: 'case-reports'
  },
  {
    id: 'supp-003',
    type: 'drug-supplement',
    severity: 'major',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { supplements: ['vitamin K', 'coenzyme Q10'] },
    description: 'Vitamin K antagonizes warfarin effect. CoQ10 is structurally similar.',
    clinicalEffects: ['Decreased INR', 'Thrombosis risk'],
    onset: 'rapid',
    recommendation: 'Keep vitamin K intake consistent. Avoid CoQ10 or monitor closely.',
    alternatives: ['Consistent dosing', 'INR monitoring'],
    monitoringRequired: ['INR'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-004',
    type: 'drug-supplement',
    severity: 'major',
    mechanism: 'cyp450-induction',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { supplements: ['ginseng', 'St. John\'s Wort'] },
    description: 'These supplements induce CYP enzymes, reducing warfarin effect.',
    clinicalEffects: ['Decreased INR', 'Thrombosis risk'],
    onset: 'delayed',
    recommendation: 'Avoid these supplements with warfarin.',
    alternatives: ['No reliable alternatives with warfarin'],
    monitoringRequired: ['INR if supplement started'],
    evidenceLevel: 'case-reports'
  },
  {
    id: 'supp-005',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Digoxin', genericNames: ['digoxin'] },
    interactsWith: { supplements: ['St. John\'s Wort', 'ginseng', 'licorice'] },
    description: 'St. John\'s Wort reduces digoxin levels; others may increase toxicity.',
    clinicalEffects: ['Variable digoxin levels', 'Toxicity or treatment failure'],
    onset: 'variable',
    recommendation: 'Avoid herbal supplements with digoxin.',
    alternatives: ['None recommended'],
    monitoringRequired: ['Digoxin level'],
    evidenceLevel: 'case-reports'
  },
  {
    id: 'supp-006',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacokinetic',
    primaryDrug: { name: 'Cyclosporine', genericNames: ['cyclosporine', 'tacrolimus'], drugClasses: ['immunosuppressants'] },
    interactsWith: { supplements: ['St. John\'s Wort'] },
    description: 'St. John\'s Wort induces drug metabolism, reducing immunosuppressant levels.',
    clinicalEffects: ['Subtherapeutic levels', 'Transplant rejection'],
    onset: 'delayed',
    recommendation: 'ABSOLUTELY avoid St. John\'s Wort with immunosuppressants.',
    alternatives: ['None'],
    monitoringRequired: ['Drug levels if supplement used accidentally'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-007',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Statins', genericNames: ['atorvastatin', 'simvastatin'], drugClasses: ['statins'] },
    interactsWith: { supplements: ['red yeast rice'] },
    description: 'Red yeast rice contains lovastatin; additive myotoxicity risk.',
    clinicalEffects: ['Myopathy', 'Rhabdomyolysis', 'Additive statin effects'],
    onset: 'delayed',
    recommendation: 'Avoid red yeast rice when taking prescription statins.',
    alternatives: ['Choose one or the other'],
    monitoringRequired: ['CK if used together'],
    evidenceLevel: 'case-reports'
  },
  {
    id: 'supp-008',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Thyroid Hormone', genericNames: ['levothyroxine', 'liothyronine'] },
    interactsWith: { supplements: ['calcium', 'iron', 'soy', 'fiber supplements'] },
    description: 'These supplements reduce thyroid hormone absorption.',
    clinicalEffects: ['Reduced thyroid levels', 'Hypothyroid symptoms'],
    onset: 'delayed',
    recommendation: 'Separate thyroid medication from supplements by 4 hours.',
    alternatives: ['Time separation'],
    monitoringRequired: ['TSH level'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-009',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Bisphosphonates', genericNames: ['alendronate', 'risedronate'] },
    interactsWith: { supplements: ['calcium', 'magnesium', 'iron', 'multivitamins'] },
    description: 'Minerals bind bisphosphonates in gut, preventing absorption.',
    clinicalEffects: ['Reduced efficacy', 'Fracture risk'],
    onset: 'rapid',
    recommendation: 'Take bisphosphonates 30-60 minutes before any supplements.',
    alternatives: ['Time separation'],
    monitoringRequired: ['Bone density'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-010',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Fluoroquinolones', genericNames: ['ciprofloxacin', 'levofloxacin'], drugClasses: ['quinolones'] },
    interactsWith: { supplements: ['calcium', 'magnesium', 'zinc', 'iron'] },
    description: 'Cations bind fluoroquinolones, reducing absorption.',
    clinicalEffects: ['Reduced antibiotic efficacy', 'Treatment failure'],
    onset: 'rapid',
    recommendation: 'Take antibiotics 2 hours before or 6 hours after mineral supplements.',
    alternatives: ['Time separation'],
    monitoringRequired: ['Infection response'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-011',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Tetracyclines', genericNames: ['doxycycline', 'minocycline'] },
    interactsWith: { supplements: ['calcium', 'magnesium', 'zinc', 'iron'] },
    description: 'Cations bind tetracyclines, preventing absorption.',
    clinicalEffects: ['Reduced antibiotic efficacy'],
    onset: 'rapid',
    recommendation: 'Separate by 2-4 hours.',
    alternatives: ['Time separation'],
    monitoringRequired: ['Infection response'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-012',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'ACE Inhibitors', genericNames: ['lisinopril', 'enalapril'], drugClasses: ['ace-inhibitors'] },
    interactsWith: { supplements: ['potassium', 'potassium chloride'] },
    description: 'Additive hyperkalemia risk.',
    clinicalEffects: ['Hyperkalemia', 'Arrhythmias'],
    onset: 'delayed',
    recommendation: 'Avoid potassium supplements unless prescribed.',
    alternatives: ['Dietary potassium only'],
    monitoringRequired: ['Potassium level'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-013',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Spironolactone', genericNames: ['spironolactone'], drugClasses: ['diuretics'] },
    interactsWith: { supplements: ['potassium', 'potassium chloride'] },
    description: 'Additive hyperkalemia risk.',
    clinicalEffects: ['Severe hyperkalemia', 'Cardiac arrest'],
    onset: 'delayed',
    recommendation: 'Avoid potassium supplements with spironolactone.',
    alternatives: ['None'],
    monitoringRequired: ['Potassium level'],
    evidenceLevel: 'established'
  },
  {
    id: 'supp-014',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Ketoconazole', genericNames: ['ketoconazole'], drugClasses: ['azole-antifungals'] },
    interactsWith: { supplements: ['St. John\'s Wort'] },
    description: 'St. John\'s Wort reduces ketoconazole levels.',
    clinicalEffects: ['Treatment failure'],
    onset: 'delayed',
    recommendation: 'Avoid St. John\'s Wort with antifungals.',
    alternatives: ['None'],
    monitoringRequired: ['Clinical response'],
    evidenceLevel: 'clinical-trial'
  },
  {
    id: 'supp-015',
    type: 'drug-supplement',
    severity: 'moderate',
    mechanism: 'pharmacodynamic',
    primaryDrug: { name: 'Oral Contraceptives', genericNames: ['ethinyl estradiol'] },
    interactsWith: { supplements: ['St. John\'s Wort'] },
    description: 'St. John\'s Wort induces metabolism, reducing contraceptive efficacy.',
    clinicalEffects: ['Contraceptive failure', 'Unplanned pregnancy'],
    onset: 'delayed',
    recommendation: 'Avoid St. John\'s Wort with hormonal contraceptives.',
    alternatives: ['Alternative contraception', 'Different supplements'],
    monitoringRequired: ['Backup contraception'],
    evidenceLevel: 'clinical-trial'
  }
];
