
// ============================================================================
// Common Drug-Drug Interactions (100+)
// ============================================================================

export const DRUG_INTERACTIONS: DrugInteraction[] = [
  // ============================================================================
  // CYP450 Interactions - Statins
  // ============================================================================
  {
    id: 'ddi-001',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Simvastatin', genericNames: ['simvastatin'], drugClasses: ['statins'] },
    interactsWith: { name: 'Clarithromycin', genericNames: ['clarithromycin'], drugClasses: ['macrolide-antibiotics'] },
    description: 'Clarithromycin inhibits CYP3A4, significantly increasing simvastatin plasma levels.',
    clinicalEffects: ['Increased risk of myopathy', 'Rhabdomyolysis', 'Elevated CK', 'Muscle pain/weakness'],
    onset: 'delayed',
    recommendation: 'Avoid concurrent use. If unavoidable, temporarily hold simvastatin during antibiotic course.',
    alternatives: ['Pravastatin', 'Rosuvastatin', 'Azithromycin (less interaction)'],
    monitoringRequired: ['CK levels if muscle symptoms', 'Report muscle pain immediately'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-002',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Simvastatin', genericNames: ['simvastatin'], drugClasses: ['statins'] },
    interactsWith: { name: 'Itraconazole', genericNames: ['itraconazole'], drugClasses: ['azole-antifungals'] },
    description: 'Itraconazole is a potent CYP3A4 inhibitor, dramatically increasing simvastatin levels.',
    clinicalEffects: ['Severe myopathy', 'Rhabdomyolysis', 'Acute kidney injury from myoglobinuria'],
    onset: 'rapid',
    recommendation: 'Contraindicated. Do not use together.',
    alternatives: ['Fluconazole (monitor closely)', 'Pravastatin (CYP-independent)'],
    monitoringRequired: ['Avoid combination entirely'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-003',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Atorvastatin', genericNames: ['atorvastatin'], drugClasses: ['statins'] },
    interactsWith: { name: 'Clarithromycin', genericNames: ['clarithromycin'], drugClasses: ['macrolide-antibiotics'] },
    description: 'Clarithromycin inhibits CYP3A4 metabolism of atorvastatin.',
    clinicalEffects: ['Increased atorvastatin levels', 'Muscle toxicity risk', 'Myopathy'],
    onset: 'delayed',
    recommendation: 'Avoid if possible. If necessary, use lowest atorvastatin dose and monitor closely.',
    alternatives: ['Azithromycin', 'Pravastatin', 'Rosuvastatin'],
    monitoringRequired: ['Muscle symptoms', 'CK if symptoms present'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-004',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Atorvastatin', genericNames: ['atorvastatin'], drugClasses: ['statins'] },
    interactsWith: { name: 'Diltiazem', genericNames: ['diltiazem'], drugClasses: ['calcium-channel-blockers'] },
    description: 'Diltiazem moderately inhibits CYP3A4, increasing statin levels.',
    clinicalEffects: ['Increased myopathy risk', 'Higher statin exposure'],
    onset: 'delayed',
    recommendation: 'Limit atorvastatin dose to max 40mg daily with diltiazem. Monitor for muscle symptoms.',
    alternatives: ['Pravastatin', 'Rosuvastatin'],
    monitoringRequired: ['Muscle pain/weakness'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-005',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Lovastatin', genericNames: ['lovastatin'], drugClasses: ['statins'] },
    interactsWith: { name: 'Amiodarone', genericNames: ['amiodarone'] },
    description: 'Amiodarone inhibits CYP3A4 and P-glycoprotein.',
    clinicalEffects: ['Increased lovastatin levels', 'Myopathy risk', 'Rhabdomyolysis in susceptible patients'],
    onset: 'delayed',
    recommendation: 'Do not exceed 40mg lovastatin with amiodarone. Monitor for muscle symptoms.',
    alternatives: ['Pravastatin', 'Rosuvastatin'],
    monitoringRequired: ['Muscle symptoms', 'CK if indicated'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // Warfarin Interactions
  // ============================================================================
  {
    id: 'ddi-006',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Metronidazole', genericNames: ['metronidazole'] },
    description: 'Metronidazole inhibits CYP2C9 metabolism of warfarin S-enantiomer.',
    clinicalEffects: ['Significantly increased INR', 'Bleeding risk', 'Hemorrhage'],
    onset: 'rapid',
    recommendation: 'Avoid if possible. If necessary, reduce warfarin dose 30-50% and monitor INR closely.',
    alternatives: ['Amoxicillin (less interaction)', 'Switch to DOAC if appropriate'],
    monitoringRequired: ['INR within 2-3 days', 'Signs of bleeding'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-007',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Fluconazole', genericNames: ['fluconazole'], drugClasses: ['azole-antifungals'] },
    description: 'Fluconazole inhibits CYP2C9 and CYP3A4, increasing warfarin levels.',
    clinicalEffects: ['Markedly increased INR', 'Spontaneous bleeding', 'GI bleeding'],
    onset: 'rapid',
    recommendation: 'Avoid combination. If unavoidable, reduce warfarin dose 50% and monitor INR frequently.',
    alternatives: ['Topical antifungals', 'Nystatin', 'Switch to DOAC'],
    monitoringRequired: ['INR within 48-72 hours', 'Weekly INR until stable'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-008',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Amiodarone', genericNames: ['amiodarone'] },
    description: 'Amiodarone inhibits CYP2C9 and CYP3A4; also affects thyroid which alters warfarin response.',
    clinicalEffects: ['30-50% increase in INR', 'Significant bleeding risk', 'Requires major dose reduction'],
    onset: 'delayed',
    recommendation: 'Reduce warfarin dose 30-50% when starting amiodarone. Monitor INR weekly for 4 weeks.',
    alternatives: ['Switch to DOAC', 'Dronedarone (less interaction but still present)'],
    monitoringRequired: ['INR weekly x 4 weeks', 'Then every 2 weeks'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-009',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-induction',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Carbamazepine', genericNames: ['carbamazepine'], drugClasses: ['anticonvulsants'] },
    description: 'Carbamazepine induces CYP enzymes, accelerating warfarin metabolism.',
    clinicalEffects: ['Decreased INR', 'Therapeutic failure', 'Thrombosis risk'],
    onset: 'delayed',
    recommendation: 'May need to increase warfarin dose 2-3x. Monitor INR weekly during titration.',
    alternatives: ['Switch to DOAC (apixaban has less interaction)', 'Valproic acid'],
    monitoringRequired: ['INR weekly until stable', 'Check for thrombotic symptoms'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-010',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'cyp450-induction',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Rifampin', genericNames: ['rifampin'] },
    description: 'Rifampin is a potent inducer of multiple CYP enzymes including CYP2C9.',
    clinicalEffects: ['Dramatically decreased INR', 'Rapid loss of anticoagulation', 'High thrombosis risk'],
    onset: 'rapid',
    recommendation: 'May require 2-3x warfarin dose increase. Monitor INR every 2-3 days initially.',
    alternatives: ['Rifabutin (less interaction)', 'Switch to DOAC'],
    monitoringRequired: ['INR every 2-3 days x 2 weeks', 'Then weekly'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-011',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'protein-binding-displacement',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Aspirin', genericNames: ['aspirin', 'acetylsalicylic acid'], drugClasses: ['nsaids', 'antiplatelets'] },
    description: 'Aspirin displaces warfarin from protein binding and affects platelet function.',
    clinicalEffects: ['Increased free warfarin', 'Additive bleeding risk', 'GI bleeding', 'Hemorrhagic stroke'],
    onset: 'rapid',
    recommendation: 'Avoid regular aspirin with warfarin. If indicated (e.g., mechanical heart valve), use low dose (81mg) with careful monitoring.',
    alternatives: ['Acetaminophen for pain', 'Avoid combination if possible'],
    monitoringRequired: ['INR more frequently', 'Signs of bleeding', 'Hemoglobin/hematocrit'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-012',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'bleeding-risk',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'NSAIDs', genericNames: ['ibuprofen', 'naproxen', 'diclofenac'], drugClasses: ['nsaids'] },
    description: 'NSAIDs increase GI bleeding risk and may affect platelet function.',
    clinicalEffects: ['GI ulceration', 'Bleeding', 'Hemorrhage', 'Nephrotoxicity'],
    onset: 'variable',
    recommendation: 'Avoid regular NSAID use with warfarin. Use acetaminophen instead or lowest effective NSAID dose with PPI.',
    alternatives: ['Acetaminophen', 'Topical NSAIDs', 'Celecoxib (somewhat safer but still risk)'],
    monitoringRequired: ['Signs of GI bleeding', 'Hemoglobin', 'Stool guaiac'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-013',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Ciprofloxacin', genericNames: ['ciprofloxacin'], drugClasses: ['quinolones'] },
    description: 'Ciprofloxacin inhibits CYP1A2 and may displace warfarin from protein binding.',
    clinicalEffects: ['Increased INR', 'Bleeding risk', 'Usually mild but significant in some patients'],
    onset: 'delayed',
    recommendation: 'Monitor INR within 3-5 days of starting ciprofloxacin. May need warfarin dose reduction.',
    alternatives: ['Amoxicillin', 'Nitrofurantoin', 'TMP-SMX'],
    monitoringRequired: ['INR 3-5 days after start', 'Weekly if prolonged use'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-014',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'TMP-SMX', genericNames: ['trimethoprim-sulfamethoxazole', 'sulfamethoxazole-trimethoprim'] },
    description: 'Sulfamethoxazole inhibits CYP2C9; trimethoprim may affect folate metabolism.',
    clinicalEffects: ['Increased INR', 'Bleeding', 'Particularly in elderly'],
    onset: 'rapid',
    recommendation: 'Monitor INR within 3-5 days. Consider 10-20% warfarin dose reduction.',
    alternatives: ['Amoxicillin', 'Cephalexin', 'Nitrofurantoin'],
    monitoringRequired: ['INR 3-5 days after start', 'Signs of bleeding'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-015',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'cyp450-inhibition',
    primaryDrug: { name: 'Warfarin', genericNames: ['warfarin'], drugClasses: ['anticoagulants'] },
    interactsWith: { name: 'Cimetidine', genericNames: ['cimetidine'], drugClasses: ['h2-blockers'] },
    description: 'Cimetidine inhibits multiple CYP enzymes including CYP2C9 and CYP3A4.',
    clinicalEffects: ['Increased INR', 'Bleeding risk'],
    onset: 'delayed',
    recommendation: 'Switch to famotidine or ranitidine. If cimetidine necessary, monitor INR closely.',
    alternatives: ['Famotidine', 'Ranitidine', 'PPIs'],
    monitoringRequired: ['INR within 1 week'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // Serotonin Syndrome Interactions
  // ============================================================================
  {
    id: 'ddi-016',
    type: 'drug-drug',
    severity: 'contraindicated',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'MAOIs', genericNames: ['phenelzine', 'tranylcypromine', 'isocarboxazid'], drugClasses: ['maois'] },
    interactsWith: { name: 'SSRIs', genericNames: ['fluoxetine', 'sertraline', 'paroxetine', 'citalopram', 'escitalopram'], drugClasses: ['ssris'] },
    description: 'Combined serotonergic effects can cause life-threatening serotonin syndrome.',
    clinicalEffects: ['Serotonin syndrome', 'Hyperthermia', 'Muscle rigidity', 'Autonomic instability', 'Death'],
    onset: 'rapid',
    recommendation: 'Absolutely contraindicated. Must have 14-day washout between MAOI and SSRI use.',
    alternatives: ['Switch classes with proper washout', 'Consider mirtazapine or bupropion after washout'],
    monitoringRequired: ['Never combine - no monitoring approach makes this safe'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-017',
    type: 'drug-drug',
    severity: 'contraindicated',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'MAOIs', genericNames: ['phenelzine', 'tranylcypromine', 'isocarboxazid'], drugClasses: ['maois'] },
    interactsWith: { name: 'Tramadol', genericNames: ['tramadol'], drugClasses: ['opioids'] },
    description: 'Tramadol has serotonergic properties that interact fatally with MAOIs.',
    clinicalEffects: ['Serotonin syndrome', 'Seizures', 'Death'],
    onset: 'rapid',
    recommendation: 'Contraindicated. Use alternative analgesics.',
    alternatives: ['Morphine', 'Oxycodone', 'Acetaminophen', 'NSAIDs'],
    monitoringRequired: ['Avoid combination entirely'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-018',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'SSRIs', genericNames: ['fluoxetine', 'sertraline', 'paroxetine'], drugClasses: ['ssris'] },
    interactsWith: { name: 'Tramadol', genericNames: ['tramadol'], drugClasses: ['opioids'] },
    description: 'Combined serotonergic effects increase serotonin syndrome risk.',
    clinicalEffects: ['Serotonin syndrome', 'Agitation', 'Confusion', 'Tremor', 'Hyperthermia'],
    onset: 'variable',
    recommendation: 'Use with caution. Monitor for serotonin syndrome symptoms, especially when starting or increasing doses.',
    alternatives: ['Morphine', 'Oxycodone', 'Hydrocodone'],
    monitoringRequired: ['Mental status', 'Temperature', 'Muscle rigidity', 'Hyperreflexia'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-019',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'SSRIs', genericNames: ['fluoxetine', 'sertraline'], drugClasses: ['ssris'] },
    interactsWith: { name: 'Triptans', genericNames: ['sumatriptan', 'rizatriptan', 'zolmitriptan'], drugClasses: ['triptans'] },
    description: 'Combined serotonergic effects may increase serotonin syndrome risk.',
    clinicalEffects: ['Serotonin syndrome (rare but serious)', 'Tremor', 'Restlessness'],
    onset: 'rapid',
    recommendation: 'Generally safe for most patients but be aware of interaction. Use lowest effective triptan dose.',
    alternatives: ['Acetaminophen for migraines', 'NSAIDs'],
    monitoringRequired: ['First few doses closely', 'Signs of serotonin syndrome'],
    evidenceLevel: 'clinical-trial'
  },
  {
    id: 'ddi-020',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'SSRIs', genericNames: ['fluoxetine', 'sertraline', 'paroxetine'], drugClasses: ['ssris'] },
    interactsWith: { name: 'St. John\'s Wort', genericNames: ['st. john\'s wort', 'hypericum perforatum'] },
    description: 'St. John\'s Wort has serotonergic properties and may induce serotonin syndrome with SSRIs.',
    clinicalEffects: ['Serotonin syndrome', 'Photosensitivity', 'May also reduce SSRI effectiveness (CYP induction)'],
    onset: 'variable',
    recommendation: 'Avoid combination. Stop St. John\'s Wort at least 2 weeks before starting SSRI.',
    alternatives: ['Prescription antidepressants only'],
    monitoringRequired: ['Avoid concurrent use'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-021',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'TCAs', genericNames: ['amitriptyline', 'nortriptyline'], drugClasses: ['tcas'] },
    interactsWith: { name: 'MAOIs', genericNames: ['phenelzine', 'tranylcypromine'], drugClasses: ['maois'] },
    description: 'Can cause severe serotonin syndrome and cardiovascular effects.',
    clinicalEffects: ['Serotonin syndrome', 'Severe hypertension', 'Hyperpyrexia', 'Death'],
    onset: 'rapid',
    recommendation: 'Contraindicated. Requires 14-day washout between classes.',
    alternatives: ['Switch with proper washout'],
    monitoringRequired: ['Never combine'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-022',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'Linezolid', genericNames: ['linezolid'] },
    interactsWith: { name: 'SSRIs', genericNames: ['sertraline', 'fluoxetine', 'paroxetine'], drugClasses: ['ssris'] },
    description: 'Linezolid is a weak reversible MAOI with serotonergic properties.',
    clinicalEffects: ['Serotonin syndrome', 'Confusion', 'Hyperthermia', 'Death'],
    onset: 'rapid',
    recommendation: 'Avoid concurrent use. If linezolid essential, hold SSRI during treatment.',
    alternatives: ['Hold SSRI temporarily', 'Use different antibiotic'],
    monitoringRequired: ['Mental status', 'Temperature', 'Muscle symptoms'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-023',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'serotonergic',
    primaryDrug: { name: 'Dextromethorphan', genericNames: ['dextromethorphan'] },
    interactsWith: { name: 'MAOIs', genericNames: ['phenelzine', 'tranylcypromine'], drugClasses: ['maois'] },
    description: 'Dextromethorphan increases serotonin release and inhibits reuptake.',
    clinicalEffects: ['Serotonin syndrome', 'Hypertension', 'Hyperthermia', 'Agitation'],
    onset: 'rapid',
    recommendation: 'Avoid all cough/cold products containing dextromethorphan with MAOIs.',
    alternatives: ['Guaifenesin', 'Honey', 'Dextromethorphan-free products'],
    monitoringRequired: ['Avoid combination'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // QT Prolongation Interactions
  // ============================================================================
  {
    id: 'ddi-024',
    type: 'drug-drug',
    severity: 'contraindicated',
    mechanism: 'qt-prolongation',
    primaryDrug: { name: 'Cisapride', genericNames: ['cisapride'] },
    interactsWith: { name: 'Azole Antifungals', genericNames: ['ketoconazole', 'itraconazole', 'fluconazole'], drugClasses: ['azole-antifungals'] },
    description: 'Combined QT prolongation effects with CYP3A4 inhibition of cisapride metabolism.',
    clinicalEffects: ['Torsades de pointes', 'Sudden cardiac death', 'Ventricular arrhythmias'],
    onset: 'rapid',
    recommendation: 'Contraindicated. Cisapride is restricted/restricted in most countries due to this risk.',
    alternatives: ['Metoclopramide', 'Domperidone (where available)'],
    monitoringRequired: ['Never combine'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-025',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'qt-prolongation',
    primaryDrug: { name: 'Haloperidol', genericNames: ['haloperidol'], drugClasses: ['antipsychotics'] },
    interactsWith: { name: 'Fluconazole', genericNames: ['fluconazole'], drugClasses: ['azole-antifungals'] },
    description: 'Haloperidol prolongs QT; fluconazole inhibits its metabolism.',
    clinicalEffects: ['QT prolongation', 'Torsades de pointes', 'Sudden death'],
    onset: 'rapid',
    recommendation: 'Avoid if possible. If necessary, ECG monitoring required.',
    alternatives: ['Olanzapine', 'Risperidone', 'Topical antifungal'],
    monitoringRequired: ['Baseline ECG', 'Follow-up ECG', 'Electrolytes'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-026',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'qt-prolongation',
    primaryDrug: { name: 'Methadone', genericNames: ['methadone'], drugClasses: ['opioids'] },
    interactsWith: { name: 'Fluconazole', genericNames: ['fluconazole'], drugClasses: ['azole-antifungals'] },
    description: 'Methadone prolongs QT; fluconazole inhibits CYP3A4 metabolism.',
    clinicalEffects: ['QT prolongation', 'Torsades de pointes', 'Death'],
    onset: 'delayed',
    recommendation: 'Avoid if possible. If necessary, ECG monitoring and consider dose reduction.',
    alternatives: ['Buprenorphine', 'Morphine', 'Topical antifungal'],
    monitoringRequired: ['ECG at baseline and during therapy', 'Electrolytes (K, Mg)'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-027',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'qt-prolongation',
    primaryDrug: { name: 'Azithromycin', genericNames: ['azithromycin'], drugClasses: ['macrolide-antibiotics'] },
    interactsWith: { name: 'Amiodarone', genericNames: ['amiodarone'] },
    description: 'Both drugs prolong QT interval; additive effect.',
    clinicalEffects: ['QT prolongation', 'Torsades de pointes', 'Sudden death'],
    onset: 'variable',
    recommendation: 'Avoid combination in patients with prolonged QT, electrolyte abnormalities, or heart failure.',
    alternatives: ['Amoxicillin', 'Doxycycline'],
    monitoringRequired: ['Baseline ECG', 'Electrolytes', 'Consider alternatives'],
    evidenceLevel: 'clinical-trial'
  },
  {
    id: 'ddi-028',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'qt-prolongation',
    primaryDrug: { name: 'Moxifloxacin', genericNames: ['moxifloxacin'], drugClasses: ['quinolones'] },
    interactsWith: { name: 'Haloperidol', genericNames: ['haloperidol'], drugClasses: ['antipsychotics'] },
    description: 'Both drugs prolong QT; additive effect increases arrhythmia risk.',
    clinicalEffects: ['QT prolongation', 'Torsades de pointes', 'Sudden cardiac death'],
    onset: 'rapid',
    recommendation: 'Avoid combination. Use alternative antibiotic or antipsychotic.',
    alternatives: ['Ciprofloxacin (less QT effect)', 'Levofloxacin (monitor)', 'Risperidone'],
    monitoringRequired: ['ECG if must use together', 'Electrolytes'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-029',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'qt-prolongation',
    primaryDrug: { name: 'Droperidol', genericNames: ['droperidol'] },
    interactsWith: { name: 'Haloperidol', genericNames: ['haloperidol'], drugClasses: ['antipsychotics'] },
    description: 'Both drugs significantly prolong QT interval.',
    clinicalEffects: ['Severe QT prolongation', 'Torsades de pointes'],
    onset: 'rapid',
    recommendation: 'Avoid concurrent use.',
    alternatives: ['Ondansetron', 'Metoclopramide', 'Single agent only'],
    monitoringRequired: ['Never combine'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // Hypotensive Interactions
  // ============================================================================
  {
    id: 'ddi-030',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hypotensive',
    primaryDrug: { name: 'Sildenafil', genericNames: ['sildenafil'], drugClasses: ['pde5-inhibitors'] },
    interactsWith: { name: 'Nitrates', genericNames: ['nitroglycerin', 'isosorbide'], drugClasses: ['nitrates'] },
    description: 'PDE5 inhibitors potentiate nitrate-induced vasodilation causing severe hypotension.',
    clinicalEffects: ['Severe hypotension', 'Cardiovascular collapse', 'Myocardial infarction', 'Death'],
    onset: 'rapid',
    recommendation: 'ABSOLUTE CONTRAINDICATION. Never use together. Nitrates cannot be given within 24-48 hours of sildenafil.',
    alternatives: ['None - avoid combination completely'],
    monitoringRequired: ['Never combine - medical emergency if it occurs'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-031',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hypotensive',
    primaryDrug: { name: 'Tadalafil', genericNames: ['tadalafil'], drugClasses: ['pde5-inhibitors'] },
    interactsWith: { name: 'Nitrates', genericNames: ['nitroglycerin', 'isosorbide'], drugClasses: ['nitrates'] },
    description: 'Longer-acting PDE5 inhibitor with prolonged risk window.',
    clinicalEffects: ['Severe hypotension', 'Cardiovascular collapse', 'Death'],
    onset: 'rapid',
    recommendation: 'ABSOLUTE CONTRAINDICATION. Nitrates cannot be used within 48 hours of tadalafil due to long half-life.',
    alternatives: ['None'],
    monitoringRequired: ['Never combine'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-032',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'hypotensive',
    primaryDrug: { name: 'Alpha-blockers', genericNames: ['tamsulosin', 'doxazosin', 'terazosin'] },
    interactsWith: { name: 'PDE5 Inhibitors', genericNames: ['sildenafil', 'tadalafil', 'vardenafil'], drugClasses: ['pde5-inhibitors'] },
    description: 'Additive hypotensive effects.',
    clinicalEffects: ['Orthostatic hypotension', 'Dizziness', 'Syncope', 'Falls (especially elderly)'],
    onset: 'rapid',
    recommendation: 'Start PDE5 inhibitor at lowest dose, separate dosing by 4+ hours, monitor BP.',
    alternatives: ['Lower doses', 'Careful titration'],
    monitoringRequired: ['Blood pressure', 'Orthostatic vital signs', 'Fall risk'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-033',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'hypotensive',
    primaryDrug: { name: 'ACE Inhibitors', genericNames: ['lisinopril', 'enalapril'], drugClasses: ['ace-inhibitors'] },
    interactsWith: { name: 'Diuretics', genericNames: ['furosemide', 'hydrochlorothiazide'], drugClasses: ['diuretics'] },
    description: 'Additive hypotensive effect, especially with volume depletion.',
    clinicalEffects: ['First-dose hypotension', 'Dizziness', 'Syncope', 'Acute kidney injury'],
    onset: 'rapid',
    recommendation: 'Start ACE inhibitor at low dose, consider holding diuretic 2-3 days before initiation.',
    alternatives: ['Gradual titration', 'Monitor closely'],
    monitoringRequired: ['Blood pressure', 'Creatinine', 'Potassium'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // Hyperkalemia Interactions
  // ============================================================================
  {
    id: 'ddi-034',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hyperkalemia',
    primaryDrug: { name: 'ACE Inhibitors', genericNames: ['lisinopril', 'enalapril', 'ramipril'], drugClasses: ['ace-inhibitors'] },
    interactsWith: { name: 'Spironolactone', genericNames: ['spironolactone'], drugClasses: ['diuretics'] },
    description: 'Both reduce potassium excretion; additive hyperkalemia risk.',
    clinicalEffects: ['Hyperkalemia', 'Arrhythmias', 'Cardiac arrest'],
    onset: 'delayed',
    recommendation: 'Use together only when indicated (heart failure). Monitor potassium closely.',
    alternatives: ['Thiazide diuretic instead of spironolactone'],
    monitoringRequired: ['Potassium within 1 week', 'Then monthly x 3, then every 3-6 months', 'Creatinine'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-035',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hyperkalemia',
    primaryDrug: { name: 'ACE Inhibitors', genericNames: ['lisinopril', 'enalapril'], drugClasses: ['ace-inhibitors'] },
    interactsWith: { name: 'ARBs', genericNames: ['losartan', 'valsartan'], drugClasses: ['arbs'] },
    description: 'Dual blockade of RAAS increases hyperkalemia and kidney injury risk.',
    clinicalEffects: ['Hyperkalemia', 'Acute kidney injury', 'Hypotension'],
    onset: 'delayed',
    recommendation: 'Generally avoid dual RAAS blockade unless specifically indicated (e.g., specific heart failure protocols).',
    alternatives: ['Choose ACE OR ARB, not both', 'Add dihydropyridine CCB'],
    monitoringRequired: ['Potassium', 'Creatinine', 'Blood pressure'],
    evidenceLevel: 'clinical-trial'
  },
  {
    id: 'ddi-036',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hyperkalemia',
    primaryDrug: { name: 'Spironolactone', genericNames: ['spironolactone'], drugClasses: ['diuretics'] },
    interactsWith: { name: 'Potassium Supplements', genericNames: ['potassium chloride', 'potassium citrate'] },
    description: 'Additive potassium retention.',
    clinicalEffects: ['Severe hyperkalemia', 'Life-threatening arrhythmias'],
    onset: 'delayed',
    recommendation: 'Avoid routine potassium supplementation with spironolactone. If needed, monitor very closely.',
    alternatives: ['Dietary potassium only', 'Thiazide diuretic'],
    monitoringRequired: ['Potassium within 1 week', 'Frequent monitoring'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-037',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hyperkalemia',
    primaryDrug: { name: 'Trimethoprim', genericNames: ['trimethoprim'] },
    interactsWith: { name: 'ACE Inhibitors', genericNames: ['lisinopril', 'enalapril'], drugClasses: ['ace-inhibitors'] },
    description: 'Trimethoprim acts like a potassium-sparing diuretic in the distal nephron.',
    clinicalEffects: ['Hyperkalemia', 'Arrhythmias', 'Particularly in elderly and CKD patients'],
    onset: 'delayed',
    recommendation: 'Use lower dose TMP-SMX (e.g., single strength BID) and monitor potassium within 1 week.',
    alternatives: ['Amoxicillin', 'Nitrofurantoin', 'Cephalexin'],
    monitoringRequired: ['Potassium within 3-5 days', 'Creatinine'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // Nephrotoxic Interactions
  // ============================================================================
  {
    id: 'ddi-038',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'nephrotoxic',
    primaryDrug: { name: 'ACE Inhibitors', genericNames: ['lisinopril', 'enalapril'], drugClasses: ['ace-inhibitors'] },
    interactsWith: { name: 'NSAIDs', genericNames: ['ibuprofen', 'naproxen', 'diclofenac'], drugClasses: ['nsaids'] },
    description: 'ACE inhibitors dilate efferent arteriole; NSAIDs constrict afferent arteriole - combined effect reduces GFR.',
    clinicalEffects: ['Acute kidney injury', 'Hyperkalemia', 'Accelerated hypertension'],
    onset: 'rapid',
    recommendation: 'Avoid regular NSAID use with ACE inhibitors, especially in elderly, dehydration, or CKD.',
    alternatives: ['Acetaminophen', 'Topical NSAIDs', 'Short-term use with monitoring'],
    monitoringRequired: ['Creatinine within 1-2 weeks of starting NSAIDs', 'Potassium'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-039',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'nephrotoxic',
    primaryDrug: { name: 'Diuretics', genericNames: ['furosemide', 'hydrochlorothiazide'], drugClasses: ['diuretics'] },
    interactsWith: { name: 'NSAIDs', genericNames: ['ibuprofen', 'naproxen'], drugClasses: ['nsaids'] },
    description: 'NSAIDs blunt diuretic response and can cause acute kidney injury with volume depletion.',
    clinicalEffects: ['Reduced diuretic efficacy', 'Acute kidney injury', 'Fluid retention', 'Hypertension'],
    onset: 'variable',
    recommendation: 'Avoid chronic NSAID use with diuretics. If needed, use lowest dose and monitor kidney function.',
    alternatives: ['Acetaminophen', 'Topical NSAIDs'],
    monitoringRequired: ['Weight', 'Edema', 'Creatinine', 'Blood pressure'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-040',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'nephrotoxic',
    primaryDrug: { name: 'Vancomycin', genericNames: ['vancomycin'] },
    interactsWith: { name: 'Aminoglycosides', genericNames: ['gentamicin', 'tobramycin', 'amikacin'] },
    description: 'Additive nephrotoxicity and ototoxicity.',
    clinicalEffects: ['Acute tubular necrosis', 'Kidney failure', 'Ototoxicity'],
    onset: 'delayed',
    recommendation: 'Avoid if possible. If necessary, extend dosing intervals, monitor levels, ensure hydration.',
    alternatives: ['Different antibiotic combinations'],
    monitoringRequired: ['Vancomycin troughs', 'Creatinine daily', 'Drug levels'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-041',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'nephrotoxic',
    primaryDrug: { name: 'Cisplatin', genericNames: ['cisplatin'] },
    interactsWith: { name: 'Aminoglycosides', genericNames: ['gentamicin', 'tobramycin'] },
    description: 'Additive nephrotoxicity.',
    clinicalEffects: ['Severe nephrotoxicity', 'Kidney failure', 'Magnesium wasting'],
    onset: 'delayed',
    recommendation: 'Avoid concurrent use if possible. If necessary, aggressive hydration and close monitoring.',
    alternatives: ['Different chemotherapy', 'Radiation'],
    monitoringRequired: ['Creatinine', 'Magnesium', 'Urine output', 'Hydration status'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-042',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'nephrotoxic',
    primaryDrug: { name: 'Tacrolimus', genericNames: ['tacrolimus'], drugClasses: ['immunosuppressants'] },
    interactsWith: { name: 'Amphotericin B', genericNames: ['amphotericin b'] },
    description: 'Additive nephrotoxicity.',
    clinicalEffects: ['Acute kidney injury', 'Electrolyte abnormalities', 'Nephrocalcinosis'],
    onset: 'delayed',
    recommendation: 'Avoid if possible. If necessary, liposomal amphotericin and very close monitoring.',
    alternatives: ['Echinocandins', 'Azoles (less nephrotoxic)'],
    monitoringRequired: ['Creatinine', 'Electrolytes', 'Tacrolimus levels', 'Urine output'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // Hepatotoxic Interactions
  // ============================================================================
  {
    id: 'ddi-043',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hepatotoxic',
    primaryDrug: { name: 'Isoniazid', genericNames: ['isoniazid', 'inh'] },
    interactsWith: { name: 'Rifampin', genericNames: ['rifampin'] },
    description: 'Both hepatotoxic; additive liver injury risk, especially with underlying liver disease.',
    clinicalEffects: ['Hepatitis', 'Liver failure', 'Elevated transaminases', 'Jaundice'],
    onset: 'delayed',
    recommendation: 'Use together as indicated for TB (standard therapy). Monitor liver function closely.',
    alternatives: ['Different TB regimen if hepatotoxicity occurs'],
    monitoringRequired: ['LFTs baseline, 2 weeks, monthly', 'Symptoms of hepatitis'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-044',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'hepatotoxic',
    primaryDrug: { name: 'Acetaminophen', genericNames: ['acetaminophen', 'paracetamol', 'apap'] },
    interactsWith: { name: 'Alcohol', genericNames: ['ethanol', 'alcohol'] },
    description: 'Chronic alcohol use induces CYP2E1 which produces toxic metabolite NAPQI; also depletes glutathione.',
    clinicalEffects: ['Hepatotoxicity', 'Liver failure', 'Lower threshold for overdose toxicity'],
    onset: 'delayed',
    recommendation: 'Limit acetaminophen to 2g/day in chronic alcohol users. Avoid in acute alcohol intoxication.',
    alternatives: ['NSAIDs (if appropriate)', 'Tramadol', 'Non-pharmacologic pain management'],
    monitoringRequired: ['Total daily acetaminophen dose', 'LFTs if chronic use'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-045',
    type: 'drug-drug',
    severity: 'moderate',
    mechanism: 'hepatotoxic',
    primaryDrug: { name: 'Methotrexate', genericNames: ['methotrexate'] },
    interactsWith: { name: 'Alcohol', genericNames: ['ethanol', 'alcohol'] },
    description: 'Additive hepatotoxicity.',
    clinicalEffects: ['Hepatic fibrosis', 'Cirrhosis', 'Elevated liver enzymes'],
    onset: 'delayed',
    recommendation: 'Avoid or strictly limit alcohol with methotrexate. Many protocols require abstinence.',
    alternatives: ['Abstain from alcohol'],
    monitoringRequired: ['LFTs regularly', 'Liver biopsy if long-term high-dose'],
    evidenceLevel: 'established'
  },

  // ============================================================================
  // Respiratory Depression Interactions
  // ============================================================================
  {
    id: 'ddi-046',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'respiratory-depression',
    primaryDrug: { name: 'Opioids', genericNames: ['morphine', 'oxycodone', 'hydrocodone'], drugClasses: ['opioids'] },
    interactsWith: { name: 'Benzodiazepines', genericNames: ['alprazolam', 'diazepam', 'lorazepam'], drugClasses: ['benzodiazepines'] },
    description: 'Additive CNS and respiratory depression; increased sedation and overdose risk.',
    clinicalEffects: ['Respiratory depression', 'Sedation', 'Coma', 'Death from overdose'],
    onset: 'rapid',
    recommendation: 'Avoid concurrent use when possible. If necessary, use lowest effective doses, short duration.',
    alternatives: ['Non-benzodiazepine sleep aids', 'Gabapentin for anxiety', 'One agent only'],
    monitoringRequired: ['Respiratory rate', 'Sedation level', 'Avoid in sleep apnea'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-047',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'respiratory-depression',
    primaryDrug: { name: 'Opioids', genericNames: ['morphine', 'oxycodone'], drugClasses: ['opioids'] },
    interactsWith: { name: 'Alcohol', genericNames: ['ethanol', 'alcohol'] },
    description: 'Additive CNS depression and respiratory suppression.',
    clinicalEffects: ['Respiratory arrest', 'Severe sedation', 'Coma', 'Death'],
    onset: 'rapid',
    recommendation: 'Avoid alcohol completely while taking opioids.',
    alternatives: ['Abstain from alcohol'],
    monitoringRequired: ['Never combine'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-048',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'respiratory-depression',
    primaryDrug: { name: 'Opioids', genericNames: ['morphine', 'oxycodone'], drugClasses: ['opioids'] },
    interactsWith: { name: 'Sedatives', genericNames: ['zolpidem', 'eszopiclone', 'zaleplon'], drugClasses: ['sedatives'] },
    description: 'Additive CNS depression.',
    clinicalEffects: ['Respiratory depression', 'Oversedation', 'Impaired coordination', 'Falls'],
    onset: 'rapid',
    recommendation: 'Avoid concurrent use. If necessary, separate timing and use lowest doses.',
    alternatives: ['Non-drug sleep hygiene', 'Trazodone', 'Melatonin'],
    monitoringRequired: ['Sedation level', 'Fall risk'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-049',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'respiratory-depression',
    primaryDrug: { name: 'Gabapentin', genericNames: ['gabapentin', 'pregabalin'] },
    interactsWith: { name: 'Opioids', genericNames: ['morphine', 'oxycodone'], drugClasses: ['opioids'] },
    description: 'Gabapentinoids enhance opioid respiratory depression.',
    clinicalEffects: ['Respiratory depression', 'Sedation', 'Overdose risk'],
    onset: 'rapid',
    recommendation: 'Use caution with combination, especially with renal impairment. Reduce gabapentin dose.',
    alternatives: ['Lower doses of both', 'Alternative neuropathic agents'],
    monitoringRequired: ['Respiratory rate', 'Sedation', 'Renal function'],
    evidenceLevel: 'established'
  },
  {
    id: 'ddi-050',
    type: 'drug-drug',
    severity: 'major',
    mechanism: 'respiratory-depression',
    primaryDrug: { name: 'Muscle Relaxants', genericNames: ['carisoprodol', 'cyclobenzaprine'], drugClasses: ['muscle-relaxants', 'tca-related'] },
    interactsWith: { name: 'Opioids', genericNames: ['oxycodone', 'hydrocodone'], drugClasses: ['opioids'] },
    description: 'Additive CNS depression and sedation.',
    clinicalEffects: ['Severe sedation', 'Respiratory depression', 'Impaired psychomotor function'],
    onset: 'rapid',
    recommendation: 'Avoid concurrent use. Consider non-pharmacologic alternatives for muscle spasm.',
    alternatives: ['Physical therapy', 'Heat/ice', 'NSAIDs', 'One agent only'],
    monitoringRequired: ['Sedation', 'Respiratory status'],
    evidenceLevel: 'established'
  }
];
