// =============================================================================
// Medical Specialty Knowledge Map
// Comprehensive mapping of all medical specialties and subspecialties
// =============================================================================

export type BodySystemFocus =
  | 'cardiovascular'
  | 'respiratory'
  | 'gastrointestinal'
  | 'neurological'
  | 'musculoskeletal'
  | 'endocrine'
  | 'renal'
  | 'reproductive'
  | 'hematologic'
  | 'immune'
  | 'integumentary'
  | 'hepatic'
  | 'lymphatic'
  | 'psychiatric'
  | 'sensory'
  | 'multi-system';

export type AnatomyRegion =
  | 'head'
  | 'face'
  | 'neck'
  | 'chest'
  | 'abdomen'
  | 'pelvis'
  | 'upper-extremity'
  | 'lower-extremity'
  | 'spine'
  | 'brain'
  | 'heart'
  | 'lungs'
  | 'liver'
  | 'kidneys'
  | 'skin'
  | 'eyes'
  | 'ears'
  | 'throat'
  | 'genitourinary'
  | 'breast'
  | 'full-body';

export interface MedicalSpecialty {
  specialtyId: string;
  name: string;
  spanishName: string;
  category: 'primary-care' | 'surgical' | 'medical' | 'womens-reproductive' | 'mental-health' | 'diagnostic' | 'other';
  description: {
    en: string;
    es: string;
  };
  bodySystemsFocus: BodySystemFocus[];
  commonConditions: string[];
  commonProcedures: string[];
  commonMedications: string[];
  anatomyRegions: AnatomyRegion[];
  relatedSpecialties: string[];
}

// =============================================================================
// PRIMARY CARE SPECIALTIES
// =============================================================================

const familyMedicine: MedicalSpecialty = {
  specialtyId: 'family-medicine',
  name: 'Family Medicine',
  spanishName: 'Medicina Familiar',
  category: 'primary-care',
  description: {
    en: 'Comprehensive healthcare for individuals and families across all ages, genders, and diseases. Emphasizes prevention, wellness, and continuity of care.',
    es: 'Atención médica integral para individuos y familias de todas las edades, géneros y enfermedades. Enfatiza la prevención, el bienestar y la continuidad de la atención.',
  },
  bodySystemsFocus: ['multi-system', 'cardiovascular', 'respiratory', 'endocrine', 'musculoskeletal'],
  commonConditions: [
    'essential-hypertension',
    'type-2-diabetes',
    'hyperlipidemia',
    'major-depressive-disorder',
    'generalized-anxiety-disorder',
    'upper-respiratory-infection',
    'urinary-tract-infection',
    'osteoarthritis',
    'low-back-pain',
    'obesity',
    'allergic-rhinitis',
    'hypothyroidism',
    'gastroesophageal-reflux',
    'otitis-media',
    'sinusitis',
    'dermatitis',
    'acne-vulgaris',
    'asthma',
    'copd',
    'iron-deficiency-anemia',
  ],
  commonProcedures: [
    'Annual wellness exam',
    'Immunization administration',
    'Skin lesion removal',
    'Joint injection',
    'Laceration repair',
    'Pap smear',
    'Spirometry',
    'EKG interpretation',
    'Incision and drainage',
    'Cryotherapy for warts',
  ],
  commonMedications: [
    'ACE inhibitors',
    'Metformin / biguanides',
    'Statins',
    'SSRIs',
    'Proton pump inhibitors',
    'Beta-blockers',
    'NSAIDs',
    'Antibiotics (broad-spectrum)',
    'Inhaled corticosteroids',
    'Levothyroxine',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['internal-medicine', 'pediatrics', 'geriatrics', 'preventive-medicine'],
};

const internalMedicine: MedicalSpecialty = {
  specialtyId: 'internal-medicine',
  name: 'Internal Medicine',
  spanishName: 'Medicina Interna',
  category: 'primary-care',
  description: {
    en: 'Diagnosis, treatment, and prevention of adult diseases. Internists manage complex, multi-system illnesses and coordinate subspecialty care.',
    es: 'Diagnóstico, tratamiento y prevención de enfermedades en adultos. Los internistas manejan enfermedades complejas multisistémicas y coordinan la atención subespecializada.',
  },
  bodySystemsFocus: ['multi-system', 'cardiovascular', 'respiratory', 'gastrointestinal', 'endocrine', 'renal'],
  commonConditions: [
    'essential-hypertension',
    'type-2-diabetes',
    'heart-failure',
    'coronary-artery-disease',
    'copd',
    'chronic-kidney-disease',
    'pneumonia',
    'atrial-fibrillation',
    'deep-vein-thrombosis',
    'pulmonary-embolism',
    'cirrhosis',
    'anemia',
    'sepsis',
    'hyperlipidemia',
    'hypothyroidism',
    'gout',
    'osteoporosis',
    'electrolyte-disorders',
    'cellulitis',
    'acute-kidney-injury',
  ],
  commonProcedures: [
    'Central venous catheter placement',
    'Arterial blood gas interpretation',
    'Thoracentesis',
    'Paracentesis',
    'Lumbar puncture',
    'Joint aspiration',
    'EKG interpretation',
    'Chest X-ray interpretation',
    'Bone marrow biopsy',
    'Nasogastric tube placement',
  ],
  commonMedications: [
    'ACE inhibitors / ARBs',
    'Beta-blockers',
    'Diuretics',
    'Statins',
    'Anticoagulants',
    'Insulin',
    'Antibiotics (IV and oral)',
    'Proton pump inhibitors',
    'Corticosteroids',
    'Antiarrhythmics',
  ],
  anatomyRegions: ['full-body', 'chest', 'abdomen'],
  relatedSpecialties: ['family-medicine', 'cardiology', 'pulmonology', 'gastroenterology', 'nephrology', 'endocrinology'],
};

const pediatrics: MedicalSpecialty = {
  specialtyId: 'pediatrics',
  name: 'Pediatrics',
  spanishName: 'Pediatría',
  category: 'primary-care',
  description: {
    en: 'Medical care for infants, children, and adolescents up to age 18. Covers development, preventive care, and management of childhood diseases.',
    es: 'Atención médica para lactantes, niños y adolescentes hasta los 18 años. Abarca el desarrollo, la atención preventiva y el manejo de enfermedades infantiles.',
  },
  bodySystemsFocus: ['multi-system', 'respiratory', 'immune', 'gastrointestinal', 'neurological'],
  commonConditions: [
    'otitis-media',
    'pharyngitis',
    'asthma',
    'bronchiolitis',
    'croup',
    'attention-deficit-hyperactivity-disorder',
    'autism-spectrum-disorder',
    'febrile-seizures',
    'gastroenteritis',
    'eczema',
    'allergic-rhinitis',
    'urinary-tract-infection',
    'pneumonia',
    'type-1-diabetes',
    'congenital-heart-defects',
    'failure-to-thrive',
    'iron-deficiency-anemia',
    'kawasaki-disease',
    'scoliosis',
    'obesity',
  ],
  commonProcedures: [
    'Well-child exam',
    'Immunization administration',
    'Developmental screening',
    'Hearing screening',
    'Vision screening',
    'Newborn screening',
    'Circumcision',
    'Tympanometry',
    'Growth chart assessment',
    'Fluoride varnish application',
  ],
  commonMedications: [
    'Amoxicillin',
    'Albuterol / bronchodilators',
    'Inhaled corticosteroids',
    'Acetaminophen',
    'Ibuprofen',
    'Oral rehydration solutions',
    'Topical corticosteroids',
    'Stimulants (methylphenidate)',
    'Antihistamines',
    'Iron supplements',
  ],
  anatomyRegions: ['full-body', 'ears', 'throat', 'lungs'],
  relatedSpecialties: ['family-medicine', 'pediatric-surgery', 'child-psychiatry', 'neonatology'],
};

const geriatrics: MedicalSpecialty = {
  specialtyId: 'geriatrics',
  name: 'Geriatrics',
  spanishName: 'Geriatría',
  category: 'primary-care',
  description: {
    en: 'Healthcare for elderly adults, focusing on complex multi-morbidity, polypharmacy, functional decline, cognitive impairment, and end-of-life care.',
    es: 'Atención médica para adultos mayores, enfocada en la multimorbilidad compleja, la polifarmacia, el deterioro funcional, el deterioro cognitivo y los cuidados al final de la vida.',
  },
  bodySystemsFocus: ['multi-system', 'neurological', 'cardiovascular', 'musculoskeletal'],
  commonConditions: [
    'alzheimers-disease',
    'dementia',
    'osteoporosis',
    'osteoarthritis',
    'falls',
    'urinary-incontinence',
    'heart-failure',
    'atrial-fibrillation',
    'type-2-diabetes',
    'chronic-kidney-disease',
    'depression-in-elderly',
    'delirium',
    'pressure-ulcers',
    'malnutrition',
    'sarcopenia',
    'polypharmacy-adverse-effects',
    'parkinson-disease',
    'macular-degeneration',
    'hearing-loss',
    'hip-fracture',
  ],
  commonProcedures: [
    'Cognitive assessment (MMSE/MoCA)',
    'Functional assessment (ADLs/IADLs)',
    'Fall risk assessment',
    'Medication reconciliation',
    'Advance directive counseling',
    'Nutritional assessment',
    'Gait analysis',
    'Depression screening (GDS)',
    'Bone density interpretation',
    'Caregiver support counseling',
  ],
  commonMedications: [
    'Cholinesterase inhibitors',
    'Bisphosphonates',
    'Calcium / Vitamin D',
    'Low-dose aspirin',
    'ACE inhibitors',
    'Diuretics',
    'Acetaminophen',
    'Melatonin',
    'Laxatives / stool softeners',
    'Anticoagulants (DOACs)',
  ],
  anatomyRegions: ['full-body', 'brain', 'spine', 'lower-extremity'],
  relatedSpecialties: ['internal-medicine', 'neurology', 'palliative-care', 'physical-medicine-rehabilitation'],
};

// =============================================================================
// SURGICAL SPECIALTIES
// =============================================================================

const generalSurgery: MedicalSpecialty = {
  specialtyId: 'general-surgery',
  name: 'General Surgery',
  spanishName: 'Cirugía General',
  category: 'surgical',
  description: {
    en: 'Surgical management of abdominal organs, breast, skin, soft tissue, endocrine glands, and trauma. Includes open and minimally invasive techniques.',
    es: 'Manejo quirúrgico de órganos abdominales, mama, piel, tejidos blandos, glándulas endocrinas y trauma. Incluye técnicas abiertas y mínimamente invasivas.',
  },
  bodySystemsFocus: ['gastrointestinal', 'hepatic', 'endocrine', 'integumentary'],
  commonConditions: [
    'appendicitis',
    'cholecystitis',
    'cholelithiasis',
    'inguinal-hernia',
    'ventral-hernia',
    'bowel-obstruction',
    'diverticulitis',
    'colorectal-cancer',
    'breast-cancer',
    'thyroid-nodules',
    'thyroid-cancer',
    'hemorrhoids',
    'pilonidal-cyst',
    'soft-tissue-abscess',
    'gastrointestinal-bleeding',
    'pancreatic-cancer',
    'melanoma',
    'abdominal-trauma',
    'gastric-cancer',
    'bariatric-obesity',
  ],
  commonProcedures: [
    'Appendectomy',
    'Cholecystectomy',
    'Hernia repair (inguinal/ventral)',
    'Colectomy',
    'Thyroidectomy',
    'Mastectomy / lumpectomy',
    'Laparoscopic surgery',
    'Exploratory laparotomy',
    'Hemorrhoidectomy',
    'Bariatric surgery (gastric bypass/sleeve)',
    'Whipple procedure',
    'Incision and drainage',
    'Sentinel lymph node biopsy',
  ],
  commonMedications: [
    'Prophylactic antibiotics (cefazolin)',
    'Opioid analgesics',
    'Antiemetics (ondansetron)',
    'DVT prophylaxis (heparin/enoxaparin)',
    'NSAIDs',
    'Proton pump inhibitors',
    'Bowel prep agents',
    'Local anesthetics',
    'Acetaminophen',
    'Anticoagulants',
  ],
  anatomyRegions: ['abdomen', 'chest', 'neck', 'breast', 'skin'],
  relatedSpecialties: ['gastroenterology', 'oncology', 'endocrinology', 'trauma-surgery', 'anesthesiology'],
};

const orthopedicSurgery: MedicalSpecialty = {
  specialtyId: 'orthopedic-surgery',
  name: 'Orthopedic Surgery',
  spanishName: 'Cirugía Ortopédica',
  category: 'surgical',
  description: {
    en: 'Surgical and non-surgical treatment of musculoskeletal disorders including bones, joints, ligaments, tendons, muscles, and nerves.',
    es: 'Tratamiento quirúrgico y no quirúrgico de trastornos musculoesqueléticos incluyendo huesos, articulaciones, ligamentos, tendones, músculos y nervios.',
  },
  bodySystemsFocus: ['musculoskeletal'],
  commonConditions: [
    'hip-fracture',
    'distal-radius-fracture',
    'ankle-fracture',
    'osteoarthritis',
    'rheumatoid-arthritis',
    'anterior-cruciate-ligament-tear',
    'meniscus-tear',
    'rotator-cuff-tear',
    'carpal-tunnel-syndrome',
    'lumbar-disc-herniation',
    'spinal-stenosis',
    'scoliosis',
    'osteoporotic-fracture',
    'tendinitis',
    'plantar-fasciitis',
    'bone-tumor',
    'osteomyelitis',
    'compartment-syndrome',
    'trigger-finger',
    'bunion',
  ],
  commonProcedures: [
    'Total hip replacement',
    'Total knee replacement',
    'ACL reconstruction',
    'Rotator cuff repair',
    'Fracture fixation (ORIF)',
    'Arthroscopy (knee/shoulder)',
    'Spinal fusion',
    'Carpal tunnel release',
    'Joint aspiration/injection',
    'Tendon repair',
    'External fixation',
    'Bone grafting',
  ],
  commonMedications: [
    'NSAIDs',
    'Opioid analgesics',
    'Corticosteroid injections',
    'Bisphosphonates',
    'Muscle relaxants',
    'Prophylactic antibiotics',
    'DVT prophylaxis (enoxaparin)',
    'Calcium / Vitamin D',
    'Acetaminophen',
    'Hyaluronic acid injections',
  ],
  anatomyRegions: ['upper-extremity', 'lower-extremity', 'spine', 'pelvis'],
  relatedSpecialties: ['rheumatology', 'physical-medicine-rehabilitation', 'sports-medicine', 'pain-medicine'],
};

const neurosurgery: MedicalSpecialty = {
  specialtyId: 'neurosurgery',
  name: 'Neurosurgery',
  spanishName: 'Neurocirugía',
  category: 'surgical',
  description: {
    en: 'Surgical treatment of disorders of the central and peripheral nervous system, including the brain, spinal cord, and peripheral nerves.',
    es: 'Tratamiento quirúrgico de trastornos del sistema nervioso central y periférico, incluyendo cerebro, médula espinal y nervios periféricos.',
  },
  bodySystemsFocus: ['neurological'],
  commonConditions: [
    'brain-tumor',
    'glioblastoma',
    'meningioma',
    'subarachnoid-hemorrhage',
    'intracranial-aneurysm',
    'subdural-hematoma',
    'epidural-hematoma',
    'traumatic-brain-injury',
    'hydrocephalus',
    'lumbar-disc-herniation',
    'spinal-stenosis',
    'spinal-cord-tumor',
    'trigeminal-neuralgia',
    'chiari-malformation',
    'arteriovenous-malformation',
    'pituitary-adenoma',
    'cervical-myelopathy',
    'epilepsy-surgical',
    'carpal-tunnel-syndrome',
    'peripheral-nerve-injury',
  ],
  commonProcedures: [
    'Craniotomy',
    'Tumor resection (brain)',
    'Aneurysm clipping',
    'VP shunt placement',
    'Spinal decompression',
    'Spinal fusion',
    'Microdiscectomy',
    'Deep brain stimulation',
    'Stereotactic radiosurgery',
    'Endoscopic endonasal surgery',
    'Burr hole evacuation',
    'Peripheral nerve decompression',
  ],
  commonMedications: [
    'Antiepileptics (levetiracetam)',
    'Dexamethasone',
    'Mannitol / hypertonic saline',
    'Opioid analgesics',
    'Prophylactic antibiotics',
    'DVT prophylaxis',
    'Nimodipine (SAH)',
    'Temozolomide (glioma)',
    'Antihypertensives',
    'Antiemetics',
  ],
  anatomyRegions: ['brain', 'spine', 'head', 'neck'],
  relatedSpecialties: ['neurology', 'oncology', 'radiology', 'critical-care'],
};

const cardiothoracicSurgery: MedicalSpecialty = {
  specialtyId: 'cardiothoracic-surgery',
  name: 'Cardiac / Cardiothoracic Surgery',
  spanishName: 'Cirugía Cardiotorácica',
  category: 'surgical',
  description: {
    en: 'Surgical treatment of diseases of the heart, lungs, esophagus, and other organs in the chest. Includes coronary bypass, valve repair, and lung resection.',
    es: 'Tratamiento quirúrgico de enfermedades del corazón, pulmones, esófago y otros órganos del tórax. Incluye bypass coronario, reparación valvular y resección pulmonar.',
  },
  bodySystemsFocus: ['cardiovascular', 'respiratory'],
  commonConditions: [
    'coronary-artery-disease',
    'aortic-stenosis',
    'mitral-regurgitation',
    'aortic-aneurysm',
    'aortic-dissection',
    'lung-cancer',
    'atrial-fibrillation',
    'heart-failure',
    'pericardial-effusion',
    'congenital-heart-defects',
    'esophageal-cancer',
    'pneumothorax',
    'empyema',
    'mediastinal-tumor',
    'tricuspid-regurgitation',
    'endocarditis',
    'cardiac-tamponade',
    'patent-foramen-ovale',
    'pulmonary-valve-disease',
    'thoracic-outlet-syndrome',
  ],
  commonProcedures: [
    'Coronary artery bypass graft (CABG)',
    'Aortic valve replacement (AVR)',
    'Mitral valve repair/replacement',
    'Lobectomy / pneumonectomy',
    'Heart transplant',
    'Lung transplant',
    'LVAD implantation',
    'Aortic root replacement',
    'VATS (video-assisted thoracic surgery)',
    'Maze procedure',
    'Pericardiectomy',
    'Esophagectomy',
  ],
  commonMedications: [
    'Heparin / protamine',
    'Cardioplegia solutions',
    'Vasopressors (norepinephrine)',
    'Inotropes (milrinone/dobutamine)',
    'Anticoagulants (warfarin)',
    'Antiplatelet agents',
    'Beta-blockers',
    'Amiodarone',
    'Prophylactic antibiotics',
    'Opioid analgesics',
  ],
  anatomyRegions: ['heart', 'lungs', 'chest'],
  relatedSpecialties: ['cardiology', 'pulmonology', 'anesthesiology', 'critical-care', 'vascular-surgery'],
};

const vascularSurgery: MedicalSpecialty = {
  specialtyId: 'vascular-surgery',
  name: 'Vascular Surgery',
  spanishName: 'Cirugía Vascular',
  category: 'surgical',
  description: {
    en: 'Surgical and endovascular management of diseases of the arteries, veins, and lymphatic system, excluding coronary and intracranial vessels.',
    es: 'Manejo quirúrgico y endovascular de enfermedades de las arterias, venas y sistema linfático, excluyendo vasos coronarios e intracraneales.',
  },
  bodySystemsFocus: ['cardiovascular'],
  commonConditions: [
    'peripheral-arterial-disease',
    'abdominal-aortic-aneurysm',
    'carotid-artery-stenosis',
    'deep-vein-thrombosis',
    'varicose-veins',
    'chronic-venous-insufficiency',
    'diabetic-foot-ulcer',
    'critical-limb-ischemia',
    'mesenteric-ischemia',
    'renal-artery-stenosis',
    'aortic-dissection',
    'thoracic-aortic-aneurysm',
    'lymphedema',
    'arteriovenous-fistula',
    'iliac-artery-stenosis',
    'popliteal-aneurysm',
    'subclavian-steal-syndrome',
    'thoracic-outlet-syndrome',
    'claudication',
    'venous-ulcer',
  ],
  commonProcedures: [
    'Carotid endarterectomy',
    'Aortic aneurysm repair (open/EVAR)',
    'Peripheral bypass graft',
    'Angioplasty and stenting',
    'Embolectomy / thrombectomy',
    'AV fistula creation (dialysis access)',
    'Vein stripping / ablation',
    'Amputation',
    'Wound debridement',
    'Endovascular aortic repair',
  ],
  commonMedications: [
    'Anticoagulants (heparin/warfarin)',
    'Antiplatelet agents (aspirin/clopidogrel)',
    'Statins',
    'Antihypertensives',
    'Cilostazol',
    'Pentoxifylline',
    'Prophylactic antibiotics',
    'DVT prophylaxis',
    'Analgesics',
    'ACE inhibitors',
  ],
  anatomyRegions: ['lower-extremity', 'abdomen', 'neck', 'chest', 'upper-extremity'],
  relatedSpecialties: ['cardiology', 'cardiothoracic-surgery', 'interventional-radiology', 'wound-care'],
};

const plasticSurgery: MedicalSpecialty = {
  specialtyId: 'plastic-surgery',
  name: 'Plastic Surgery',
  spanishName: 'Cirugía Plástica',
  category: 'surgical',
  description: {
    en: 'Reconstructive and aesthetic surgery of the face, body, and extremities. Includes burn care, hand surgery, microsurgery, and craniofacial reconstruction.',
    es: 'Cirugía reconstructiva y estética de la cara, cuerpo y extremidades. Incluye atención de quemaduras, cirugía de mano, microcirugía y reconstrucción craneofacial.',
  },
  bodySystemsFocus: ['integumentary', 'musculoskeletal'],
  commonConditions: [
    'burn-injury',
    'cleft-lip-palate',
    'breast-reconstruction',
    'skin-cancer',
    'melanoma',
    'hand-fracture',
    'flexor-tendon-injury',
    'peripheral-nerve-injury',
    'facial-fracture',
    'scar-contracture',
    'pressure-ulcers',
    'lymphedema',
    'dupuytren-contracture',
    'gynecomastia',
    'congenital-hand-anomaly',
    'soft-tissue-sarcoma',
    'craniosynostosis',
    'traumatic-amputation',
    'facial-paralysis',
    'keloid',
  ],
  commonProcedures: [
    'Skin graft (split/full thickness)',
    'Flap reconstruction (free/pedicled)',
    'Breast reconstruction (implant/autologous)',
    'Cleft lip/palate repair',
    'Rhinoplasty',
    'Abdominoplasty',
    'Hand tendon repair',
    'Nerve repair/graft',
    'Burn debridement and grafting',
    'Scar revision',
    'Microsurgery / free tissue transfer',
    'Fracture fixation (hand/face)',
  ],
  commonMedications: [
    'Prophylactic antibiotics',
    'Opioid analgesics',
    'NSAIDs',
    'Topical antimicrobials (silver sulfadiazine)',
    'Local anesthetics',
    'DVT prophylaxis',
    'Silicone scar sheets',
    'Corticosteroid injections (keloids)',
    'Antiemetics',
    'Muscle relaxants',
  ],
  anatomyRegions: ['face', 'breast', 'upper-extremity', 'skin', 'full-body'],
  relatedSpecialties: ['dermatology', 'orthopedic-surgery', 'ent-otolaryngology', 'general-surgery'],
};

const urologicSurgery: MedicalSpecialty = {
  specialtyId: 'urologic-surgery',
  name: 'Urologic Surgery',
  spanishName: 'Cirugía Urológica',
  category: 'surgical',
  description: {
    en: 'Surgical management of diseases of the urinary tract in both sexes and the male reproductive system, including kidneys, ureters, bladder, prostate, and genitalia.',
    es: 'Manejo quirúrgico de enfermedades del tracto urinario en ambos sexos y del sistema reproductivo masculino, incluyendo riñones, uréteres, vejiga, próstata y genitales.',
  },
  bodySystemsFocus: ['renal', 'reproductive'],
  commonConditions: [
    'benign-prostatic-hyperplasia',
    'prostate-cancer',
    'bladder-cancer',
    'kidney-cancer',
    'kidney-stones',
    'urinary-tract-infection',
    'urinary-incontinence',
    'erectile-dysfunction',
    'testicular-cancer',
    'varicocele',
    'hydrocele',
    'urethral-stricture',
    'vesicoureteral-reflux',
    'cryptorchidism',
    'overactive-bladder',
    'pyelonephritis',
    'ureteropelvic-junction-obstruction',
    'penile-cancer',
    'adrenal-tumor',
    'neurogenic-bladder',
  ],
  commonProcedures: [
    'Transurethral resection of prostate (TURP)',
    'Radical prostatectomy',
    'Nephrectomy (partial/radical)',
    'Cystectomy',
    'Ureteroscopy with lithotripsy',
    'Extracorporeal shockwave lithotripsy',
    'Cystoscopy',
    'Vasectomy',
    'Circumcision',
    'Orchiectomy',
    'Ureteral stent placement',
    'Penile prosthesis implantation',
  ],
  commonMedications: [
    'Alpha-blockers (tamsulosin)',
    '5-alpha reductase inhibitors (finasteride)',
    'PDE5 inhibitors (sildenafil)',
    'Antimuscarinics (oxybutynin)',
    'Beta-3 agonists (mirabegron)',
    'Antibiotics (fluoroquinolones)',
    'Androgen deprivation therapy',
    'Potassium citrate',
    'Prophylactic antibiotics',
    'Opioid analgesics',
  ],
  anatomyRegions: ['genitourinary', 'pelvis', 'abdomen', 'kidneys'],
  relatedSpecialties: ['nephrology', 'oncology', 'gynecology', 'radiology'],
};

const ophthalmologicSurgery: MedicalSpecialty = {
  specialtyId: 'ophthalmologic-surgery',
  name: 'Ophthalmologic Surgery',
  spanishName: 'Cirugía Oftalmológica',
  category: 'surgical',
  description: {
    en: 'Surgical procedures of the eye and adnexa, including cataract extraction, retinal surgery, glaucoma procedures, and oculoplastic surgery.',
    es: 'Procedimientos quirúrgicos del ojo y sus anexos, incluyendo extracción de cataratas, cirugía retiniana, procedimientos de glaucoma y cirugía oculoplástica.',
  },
  bodySystemsFocus: ['sensory'],
  commonConditions: [
    'cataract',
    'glaucoma',
    'retinal-detachment',
    'diabetic-retinopathy',
    'macular-degeneration',
    'corneal-transplant-indications',
    'strabismus',
    'ptosis',
    'epiretinal-membrane',
    'macular-hole',
    'vitreous-hemorrhage',
    'ocular-melanoma',
    'keratoconus',
    'pterygium',
    'lacrimal-duct-obstruction',
    'orbital-fracture',
  ],
  commonProcedures: [
    'Cataract surgery (phacoemulsification)',
    'Trabeculectomy',
    'LASIK / PRK',
    'Vitrectomy',
    'Retinal laser photocoagulation',
    'Corneal transplant',
    'Strabismus surgery',
    'Glaucoma shunt placement',
    'Intravitreal injection',
    'Ptosis repair',
    'Oculoplastic reconstruction',
    'Scleral buckle',
  ],
  commonMedications: [
    'Topical prostaglandins (latanoprost)',
    'Topical beta-blockers (timolol)',
    'Anti-VEGF agents (bevacizumab/ranibizumab)',
    'Topical corticosteroids',
    'Topical antibiotics',
    'Mydriatics / cycloplegics',
    'Carbonic anhydrase inhibitors',
    'Topical NSAIDs',
    'Alpha agonists (brimonidine)',
    'Topical anesthetics',
  ],
  anatomyRegions: ['eyes'],
  relatedSpecialties: ['ophthalmology', 'neurology', 'endocrinology', 'rheumatology'],
};

const entOtolaryngology: MedicalSpecialty = {
  specialtyId: 'ent-otolaryngology',
  name: 'ENT / Otolaryngology',
  spanishName: 'Otorrinolaringología',
  category: 'surgical',
  description: {
    en: 'Medical and surgical management of diseases of the ear, nose, throat, head, and neck, including hearing, balance, swallowing, and voice disorders.',
    es: 'Manejo médico y quirúrgico de enfermedades del oído, nariz, garganta, cabeza y cuello, incluyendo trastornos de audición, equilibrio, deglución y voz.',
  },
  bodySystemsFocus: ['sensory', 'respiratory'],
  commonConditions: [
    'chronic-sinusitis',
    'otitis-media',
    'otitis-externa',
    'hearing-loss',
    'tinnitus',
    'vertigo',
    'menieres-disease',
    'obstructive-sleep-apnea',
    'tonsillitis',
    'vocal-cord-nodules',
    'laryngeal-cancer',
    'thyroid-nodules',
    'head-neck-cancer',
    'nasal-polyps',
    'deviated-septum',
    'epistaxis',
    'salivary-gland-tumor',
    'cholesteatoma',
    'peritonsillar-abscess',
    'laryngopharyngeal-reflux',
  ],
  commonProcedures: [
    'Tonsillectomy/adenoidectomy',
    'Functional endoscopic sinus surgery (FESS)',
    'Septoplasty',
    'Tympanoplasty',
    'Mastoidectomy',
    'Cochlear implant',
    'Thyroidectomy',
    'Parotidectomy',
    'Laryngoscopy',
    'Neck dissection',
    'Myringotomy with tubes',
    'Uvulopalatopharyngoplasty (UPPP)',
    'Tracheostomy',
  ],
  commonMedications: [
    'Intranasal corticosteroids',
    'Antibiotics (amoxicillin-clavulanate)',
    'Antihistamines',
    'Decongestants',
    'Ototopical antibiotics',
    'Vestibular suppressants (meclizine)',
    'Proton pump inhibitors (LPR)',
    'Oral corticosteroids',
    'Topical antifungals (otic)',
    'Analgesics',
  ],
  anatomyRegions: ['ears', 'throat', 'face', 'neck', 'head'],
  relatedSpecialties: ['allergy-immunology', 'pulmonology', 'neurology', 'oncology'],
};

const oralMaxillofacialSurgery: MedicalSpecialty = {
  specialtyId: 'oral-maxillofacial-surgery',
  name: 'Oral / Maxillofacial Surgery',
  spanishName: 'Cirugía Oral y Maxilofacial',
  category: 'surgical',
  description: {
    en: 'Surgical treatment of diseases, injuries, and defects of the mouth, jaws, face, and skull. Includes dental extractions, jaw reconstruction, and facial trauma.',
    es: 'Tratamiento quirúrgico de enfermedades, lesiones y defectos de la boca, mandíbulas, cara y cráneo. Incluye extracciones dentales, reconstrucción mandibular y trauma facial.',
  },
  bodySystemsFocus: ['musculoskeletal', 'gastrointestinal'],
  commonConditions: [
    'impacted-wisdom-teeth',
    'jaw-fracture',
    'temporomandibular-joint-disorder',
    'oral-cancer',
    'cleft-lip-palate',
    'facial-fracture',
    'dental-abscess',
    'odontogenic-cyst',
    'obstructive-sleep-apnea',
    'malocclusion',
    'osteonecrosis-of-jaw',
    'salivary-gland-disease',
    'oral-leukoplakia',
    'ameloblastoma',
    'osteoradionecrosis',
  ],
  commonProcedures: [
    'Wisdom tooth extraction',
    'Dental implant placement',
    'Orthognathic surgery (jaw realignment)',
    'Open reduction of facial fractures',
    'TMJ arthroscopy',
    'Jaw reconstruction',
    'Cleft palate repair',
    'Biopsy of oral lesion',
    'Bone grafting',
    'Apicoectomy',
  ],
  commonMedications: [
    'Antibiotics (amoxicillin/clindamycin)',
    'Opioid analgesics',
    'NSAIDs',
    'Local anesthetics (lidocaine)',
    'Oral corticosteroids',
    'Chlorhexidine mouthwash',
    'Muscle relaxants',
    'Antifungals (oral candidiasis)',
    'Antiemetics',
    'Prophylactic antibiotics',
  ],
  anatomyRegions: ['face', 'head', 'neck', 'throat'],
  relatedSpecialties: ['ent-otolaryngology', 'plastic-surgery', 'oncology', 'dentistry'],
};

// =============================================================================
// MEDICAL SPECIALTIES
// =============================================================================

const cardiology: MedicalSpecialty = {
  specialtyId: 'cardiology',
  name: 'Cardiology',
  spanishName: 'Cardiología',
  category: 'medical',
  description: {
    en: 'Diagnosis and non-surgical treatment of heart and cardiovascular system disorders, including coronary disease, heart failure, arrhythmias, and valvular disease.',
    es: 'Diagnóstico y tratamiento no quirúrgico de trastornos del corazón y del sistema cardiovascular, incluyendo enfermedad coronaria, insuficiencia cardíaca, arritmias y enfermedad valvular.',
  },
  bodySystemsFocus: ['cardiovascular'],
  commonConditions: [
    'coronary-artery-disease',
    'myocardial-infarction',
    'heart-failure',
    'atrial-fibrillation',
    'hypertension',
    'aortic-stenosis',
    'mitral-regurgitation',
    'cardiomyopathy',
    'pericarditis',
    'endocarditis',
    'pulmonary-hypertension',
    'deep-vein-thrombosis',
    'pulmonary-embolism',
    'stable-angina',
    'unstable-angina',
    'aortic-aneurysm',
    'peripheral-arterial-disease',
    'cardiac-arrhythmias',
    'congenital-heart-defects',
    'myocarditis',
    'syncope',
    'supraventricular-tachycardia',
    'ventricular-tachycardia',
    'heart-block',
    'hypertrophic-cardiomyopathy',
  ],
  commonProcedures: [
    'Echocardiography (TTE/TEE)',
    'Cardiac catheterization',
    'Percutaneous coronary intervention (PCI)',
    'Stress testing (exercise/pharmacologic)',
    'Holter / event monitoring',
    'Pacemaker implantation',
    'ICD implantation',
    'Cardioversion',
    'Catheter ablation',
    'Transcatheter aortic valve replacement (TAVR)',
    'Cardiac MRI',
    'Coronary CT angiography',
  ],
  commonMedications: [
    'ACE inhibitors / ARBs',
    'Beta-blockers',
    'Statins',
    'Antiplatelet agents (aspirin/clopidogrel)',
    'Anticoagulants (warfarin/DOACs)',
    'Diuretics (furosemide/spironolactone)',
    'Calcium channel blockers',
    'Nitrates',
    'Amiodarone',
    'SGLT2 inhibitors (heart failure)',
    'Digoxin',
    'Sacubitril/valsartan',
  ],
  anatomyRegions: ['heart', 'chest'],
  relatedSpecialties: ['cardiothoracic-surgery', 'vascular-surgery', 'internal-medicine', 'critical-care', 'pulmonology'],
};

const pulmonology: MedicalSpecialty = {
  specialtyId: 'pulmonology',
  name: 'Pulmonology',
  spanishName: 'Neumología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of diseases of the respiratory system, including the lungs, airways, and breathing mechanics.',
    es: 'Diagnóstico y tratamiento de enfermedades del sistema respiratorio, incluyendo pulmones, vías aéreas y mecánica respiratoria.',
  },
  bodySystemsFocus: ['respiratory'],
  commonConditions: [
    'asthma',
    'copd',
    'pneumonia',
    'lung-cancer',
    'pulmonary-embolism',
    'pulmonary-fibrosis',
    'pleural-effusion',
    'pneumothorax',
    'obstructive-sleep-apnea',
    'bronchiectasis',
    'sarcoidosis',
    'tuberculosis',
    'pulmonary-hypertension',
    'acute-respiratory-distress-syndrome',
    'interstitial-lung-disease',
    'cystic-fibrosis',
    'occupational-lung-disease',
    'hemoptysis',
    'chronic-cough',
    'respiratory-failure',
  ],
  commonProcedures: [
    'Pulmonary function tests (spirometry)',
    'Bronchoscopy',
    'Thoracentesis',
    'Chest tube placement',
    'Endobronchial ultrasound (EBUS)',
    'Polysomnography (sleep study)',
    'CPAP/BiPAP titration',
    'CT-guided lung biopsy',
    'Arterial blood gas interpretation',
    'Pleural biopsy',
    'Bronchoalveolar lavage',
    'Cardiopulmonary exercise testing',
  ],
  commonMedications: [
    'Inhaled corticosteroids',
    'Short-acting beta-agonists (albuterol)',
    'Long-acting beta-agonists (salmeterol)',
    'Long-acting muscarinic antagonists (tiotropium)',
    'Systemic corticosteroids',
    'Antibiotics (respiratory)',
    'Antifibrotics (pirfenidone/nintedanib)',
    'Leukotriene modifiers',
    'Phosphodiesterase-5 inhibitors (PH)',
    'Biologics (omalizumab/mepolizumab)',
  ],
  anatomyRegions: ['lungs', 'chest'],
  relatedSpecialties: ['critical-care', 'cardiology', 'infectious-disease', 'allergy-immunology', 'cardiothoracic-surgery'],
};

const gastroenterology: MedicalSpecialty = {
  specialtyId: 'gastroenterology',
  name: 'Gastroenterology',
  spanishName: 'Gastroenterología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of diseases of the digestive system, including the esophagus, stomach, intestines, liver, gallbladder, and pancreas.',
    es: 'Diagnóstico y tratamiento de enfermedades del sistema digestivo, incluyendo esófago, estómago, intestinos, hígado, vesícula biliar y páncreas.',
  },
  bodySystemsFocus: ['gastrointestinal', 'hepatic'],
  commonConditions: [
    'gastroesophageal-reflux',
    'peptic-ulcer-disease',
    'inflammatory-bowel-disease',
    'crohn-disease',
    'ulcerative-colitis',
    'irritable-bowel-syndrome',
    'celiac-disease',
    'colorectal-cancer',
    'hepatitis-b',
    'hepatitis-c',
    'cirrhosis',
    'fatty-liver-disease',
    'pancreatitis',
    'pancreatic-cancer',
    'cholelithiasis',
    'gastrointestinal-bleeding',
    'diverticulitis',
    'barrett-esophagus',
    'esophageal-cancer',
    'gastroparesis',
    'c-difficile-infection',
    'colon-polyps',
    'hepatocellular-carcinoma',
    'primary-biliary-cholangitis',
    'achalasia',
  ],
  commonProcedures: [
    'Esophagogastroduodenoscopy (EGD)',
    'Colonoscopy',
    'Endoscopic retrograde cholangiopancreatography (ERCP)',
    'Endoscopic ultrasound (EUS)',
    'Liver biopsy',
    'Paracentesis',
    'Polypectomy',
    'Esophageal dilation',
    'PEG tube placement',
    'Capsule endoscopy',
    'Hemorrhoidal banding',
    'FibroScan (transient elastography)',
  ],
  commonMedications: [
    'Proton pump inhibitors',
    'H2 receptor antagonists',
    'Aminosalicylates (mesalamine)',
    'Biologic agents (infliximab/adalimumab)',
    'Immunomodulators (azathioprine)',
    'Corticosteroids',
    'Antiemetics',
    'Laxatives / osmotic agents',
    'Antidiarrheals (loperamide)',
    'Ursodeoxycholic acid',
    'Lactulose (hepatic encephalopathy)',
    'Antiviral agents (hepatitis)',
  ],
  anatomyRegions: ['abdomen', 'liver'],
  relatedSpecialties: ['general-surgery', 'oncology', 'hepatology', 'internal-medicine', 'radiology'],
};

const nephrology: MedicalSpecialty = {
  specialtyId: 'nephrology',
  name: 'Nephrology',
  spanishName: 'Nefrología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of kidney diseases, including chronic kidney disease, dialysis management, electrolyte disorders, and hypertension.',
    es: 'Diagnóstico y tratamiento de enfermedades renales, incluyendo enfermedad renal crónica, manejo de diálisis, trastornos electrolíticos e hipertensión.',
  },
  bodySystemsFocus: ['renal'],
  commonConditions: [
    'chronic-kidney-disease',
    'acute-kidney-injury',
    'end-stage-renal-disease',
    'diabetic-nephropathy',
    'glomerulonephritis',
    'nephrotic-syndrome',
    'polycystic-kidney-disease',
    'kidney-stones',
    'renal-artery-stenosis',
    'hypertensive-nephropathy',
    'lupus-nephritis',
    'iga-nephropathy',
    'electrolyte-disorders',
    'hyperkalemia',
    'hyponatremia',
    'metabolic-acidosis',
    'urinary-tract-infection',
    'pyelonephritis',
    'renal-cell-carcinoma',
    'membranous-nephropathy',
  ],
  commonProcedures: [
    'Hemodialysis catheter placement',
    'Peritoneal dialysis catheter placement',
    'Kidney biopsy',
    'AV fistula assessment',
    'Dialysis prescription management',
    'Renal ultrasound interpretation',
    'Continuous renal replacement therapy (CRRT)',
    'Electrolyte management protocols',
    'Transplant evaluation',
    'Urine microscopy',
  ],
  commonMedications: [
    'ACE inhibitors / ARBs',
    'Erythropoiesis-stimulating agents',
    'Phosphate binders',
    'Vitamin D analogs (calcitriol)',
    'Diuretics (furosemide/metolazone)',
    'Sodium bicarbonate',
    'Potassium binders (patiromer)',
    'Immunosuppressants (transplant)',
    'Iron supplements (IV/oral)',
    'SGLT2 inhibitors',
  ],
  anatomyRegions: ['kidneys', 'abdomen'],
  relatedSpecialties: ['internal-medicine', 'urologic-surgery', 'endocrinology', 'rheumatology', 'cardiology'],
};

const endocrinology: MedicalSpecialty = {
  specialtyId: 'endocrinology',
  name: 'Endocrinology',
  spanishName: 'Endocrinología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of disorders of the endocrine system, including hormones, glands, metabolism, diabetes, thyroid, and bone disorders.',
    es: 'Diagnóstico y tratamiento de trastornos del sistema endocrino, incluyendo hormonas, glándulas, metabolismo, diabetes, tiroides y trastornos óseos.',
  },
  bodySystemsFocus: ['endocrine'],
  commonConditions: [
    'type-1-diabetes',
    'type-2-diabetes',
    'hypothyroidism',
    'hyperthyroidism',
    'graves-disease',
    'hashimoto-thyroiditis',
    'thyroid-nodules',
    'thyroid-cancer',
    'adrenal-insufficiency',
    'cushing-syndrome',
    'pheochromocytoma',
    'hyperaldosteronism',
    'osteoporosis',
    'hyperparathyroidism',
    'hypoparathyroidism',
    'pituitary-adenoma',
    'acromegaly',
    'diabetes-insipidus',
    'polycystic-ovary-syndrome',
    'hypogonadism',
    'metabolic-syndrome',
    'hypoglycemia',
    'adrenal-tumor',
    'multiple-endocrine-neoplasia',
  ],
  commonProcedures: [
    'Thyroid ultrasound',
    'Fine needle aspiration (thyroid)',
    'Continuous glucose monitor placement',
    'Insulin pump management',
    'DEXA bone density scan interpretation',
    'Dynamic endocrine testing (ACTH stim, DST)',
    'Thyroid function test interpretation',
    'Adrenal venous sampling',
    'Radioactive iodine therapy',
    'Pituitary MRI interpretation',
  ],
  commonMedications: [
    'Insulin (basal/bolus/mixed)',
    'Metformin',
    'SGLT2 inhibitors',
    'GLP-1 receptor agonists',
    'Sulfonylureas',
    'Levothyroxine',
    'Methimazole / propylthiouracil',
    'Bisphosphonates',
    'Denosumab',
    'Hydrocortisone / fludrocortisone',
    'Growth hormone',
    'Testosterone replacement',
  ],
  anatomyRegions: ['neck', 'abdomen', 'brain', 'full-body'],
  relatedSpecialties: ['internal-medicine', 'reproductive-endocrinology', 'nephrology', 'cardiology', 'ophthalmology'],
};

const hematologyOncology: MedicalSpecialty = {
  specialtyId: 'hematology-oncology',
  name: 'Hematology / Oncology',
  spanishName: 'Hematología / Oncología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of blood disorders and cancers. Encompasses benign and malignant hematology, solid tumors, and cancer pharmacotherapy.',
    es: 'Diagnóstico y tratamiento de trastornos de la sangre y cánceres. Abarca hematología benigna y maligna, tumores sólidos y farmacoterapia oncológica.',
  },
  bodySystemsFocus: ['hematologic', 'immune', 'lymphatic', 'multi-system'],
  commonConditions: [
    'iron-deficiency-anemia',
    'anemia-of-chronic-disease',
    'sickle-cell-disease',
    'thalassemia',
    'leukemia-acute-lymphoblastic',
    'leukemia-acute-myeloid',
    'leukemia-chronic-lymphocytic',
    'leukemia-chronic-myeloid',
    'lymphoma-hodgkin',
    'lymphoma-non-hodgkin',
    'multiple-myeloma',
    'lung-cancer',
    'breast-cancer',
    'colorectal-cancer',
    'pancreatic-cancer',
    'prostate-cancer',
    'deep-vein-thrombosis',
    'pulmonary-embolism',
    'thrombocytopenia',
    'hemophilia',
    'von-willebrand-disease',
    'disseminated-intravascular-coagulation',
    'myelodysplastic-syndrome',
    'polycythemia-vera',
    'essential-thrombocythemia',
  ],
  commonProcedures: [
    'Bone marrow biopsy',
    'Chemotherapy administration',
    'Immunotherapy administration',
    'Lumbar puncture (intrathecal chemo)',
    'Port-a-cath placement',
    'Blood transfusion',
    'Apheresis / plasmapheresis',
    'Stem cell transplant coordination',
    'Tumor biopsy',
    'PET/CT interpretation',
    'Peripheral blood smear review',
    'Flow cytometry interpretation',
  ],
  commonMedications: [
    'Cytotoxic chemotherapy agents',
    'Immune checkpoint inhibitors (pembrolizumab/nivolumab)',
    'Targeted therapy (imatinib/trastuzumab)',
    'Antiemetics (ondansetron/aprepitant)',
    'Growth factors (G-CSF/filgrastim)',
    'Erythropoiesis-stimulating agents',
    'Anticoagulants (heparin/enoxaparin/DOACs)',
    'Iron supplementation (IV/oral)',
    'Corticosteroids',
    'Hormonal therapy (tamoxifen/letrozole)',
    'Bisphosphonates (bone metastases)',
    'CAR-T cell therapy',
  ],
  anatomyRegions: ['full-body', 'chest', 'abdomen'],
  relatedSpecialties: ['internal-medicine', 'radiation-oncology', 'pathology', 'general-surgery', 'palliative-care'],
};

const rheumatology: MedicalSpecialty = {
  specialtyId: 'rheumatology',
  name: 'Rheumatology',
  spanishName: 'Reumatología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of autoimmune and inflammatory diseases of the joints, muscles, bones, and connective tissues.',
    es: 'Diagnóstico y tratamiento de enfermedades autoinmunes e inflamatorias de las articulaciones, músculos, huesos y tejidos conectivos.',
  },
  bodySystemsFocus: ['musculoskeletal', 'immune'],
  commonConditions: [
    'rheumatoid-arthritis',
    'systemic-lupus-erythematosus',
    'osteoarthritis',
    'gout',
    'pseudogout',
    'ankylosing-spondylitis',
    'psoriatic-arthritis',
    'sjogren-syndrome',
    'systemic-sclerosis',
    'polymyalgia-rheumatica',
    'giant-cell-arteritis',
    'vasculitis',
    'dermatomyositis',
    'polymyositis',
    'fibromyalgia',
    'antiphospholipid-syndrome',
    'sarcoidosis',
    'reactive-arthritis',
    'mixed-connective-tissue-disease',
    'raynaud-phenomenon',
  ],
  commonProcedures: [
    'Joint aspiration and analysis',
    'Corticosteroid injection (joint)',
    'Musculoskeletal ultrasound',
    'Autoantibody panel interpretation',
    'Nailfold capillaroscopy',
    'Salivary gland biopsy',
    'Skin biopsy',
    'DEXA scan interpretation',
    'Temporal artery biopsy',
    'Disease activity scoring (DAS28)',
  ],
  commonMedications: [
    'Methotrexate',
    'Hydroxychloroquine',
    'Sulfasalazine',
    'Leflunomide',
    'Biologic DMARDs (TNF inhibitors: adalimumab/etanercept)',
    'IL-6 inhibitors (tocilizumab)',
    'JAK inhibitors (tofacitinib)',
    'Corticosteroids',
    'NSAIDs',
    'Colchicine',
    'Allopurinol / febuxostat',
    'Rituximab',
  ],
  anatomyRegions: ['upper-extremity', 'lower-extremity', 'spine', 'full-body'],
  relatedSpecialties: ['orthopedic-surgery', 'dermatology', 'nephrology', 'pulmonology', 'internal-medicine'],
};

const infectiousDisease: MedicalSpecialty = {
  specialtyId: 'infectious-disease',
  name: 'Infectious Disease',
  spanishName: 'Enfermedades Infecciosas',
  category: 'medical',
  description: {
    en: 'Diagnosis and management of infections caused by bacteria, viruses, fungi, and parasites, including HIV, antimicrobial stewardship, and travel medicine.',
    es: 'Diagnóstico y manejo de infecciones causadas por bacterias, virus, hongos y parásitos, incluyendo VIH, gestión de antimicrobianos y medicina del viajero.',
  },
  bodySystemsFocus: ['immune', 'multi-system'],
  commonConditions: [
    'hiv-aids',
    'pneumonia',
    'tuberculosis',
    'urinary-tract-infection',
    'sepsis',
    'cellulitis',
    'osteomyelitis',
    'endocarditis',
    'meningitis',
    'hepatitis-b',
    'hepatitis-c',
    'covid-19',
    'influenza',
    'c-difficile-infection',
    'mrsa-infection',
    'fungal-infections',
    'malaria',
    'lyme-disease',
    'sexually-transmitted-infections',
    'prosthetic-joint-infection',
    'opportunistic-infections',
    'herpes-zoster',
    'cytomegalovirus-infection',
    'toxoplasmosis',
  ],
  commonProcedures: [
    'Blood culture interpretation',
    'Antimicrobial susceptibility review',
    'Lumbar puncture',
    'Wound culture/biopsy',
    'HIV viral load/CD4 monitoring',
    'Infectious disease consultation',
    'Antimicrobial stewardship',
    'Travel medicine counseling',
    'Vaccination recommendations',
    'Infection control protocols',
  ],
  commonMedications: [
    'Beta-lactam antibiotics (penicillins/cephalosporins)',
    'Fluoroquinolones',
    'Vancomycin',
    'Carbapenems',
    'Antiretrovirals (ART regimens)',
    'Antifungals (fluconazole/amphotericin B)',
    'Antiviral agents (acyclovir/oseltamivir)',
    'Anti-tuberculosis drugs (RIPE)',
    'Trimethoprim-sulfamethoxazole',
    'Daptomycin / linezolid',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['internal-medicine', 'pulmonology', 'critical-care', 'hematology-oncology', 'gastroenterology'],
};

const neurology: MedicalSpecialty = {
  specialtyId: 'neurology',
  name: 'Neurology',
  spanishName: 'Neurología',
  category: 'medical',
  description: {
    en: 'Diagnosis and non-surgical treatment of disorders of the nervous system, including the brain, spinal cord, peripheral nerves, and muscles.',
    es: 'Diagnóstico y tratamiento no quirúrgico de trastornos del sistema nervioso, incluyendo cerebro, médula espinal, nervios periféricos y músculos.',
  },
  bodySystemsFocus: ['neurological'],
  commonConditions: [
    'stroke-ischemic',
    'stroke-hemorrhagic',
    'transient-ischemic-attack',
    'epilepsy',
    'migraine',
    'tension-headache',
    'cluster-headache',
    'multiple-sclerosis',
    'parkinson-disease',
    'alzheimers-disease',
    'dementia',
    'amyotrophic-lateral-sclerosis',
    'myasthenia-gravis',
    'guillain-barre-syndrome',
    'peripheral-neuropathy',
    'bell-palsy',
    'essential-tremor',
    'meningitis',
    'brain-tumor',
    'vertigo',
    'carpal-tunnel-syndrome',
    'restless-legs-syndrome',
    'narcolepsy',
    'trigeminal-neuralgia',
    'huntington-disease',
  ],
  commonProcedures: [
    'Electroencephalography (EEG)',
    'Electromyography / nerve conduction studies (EMG/NCS)',
    'Lumbar puncture',
    'Brain MRI interpretation',
    'CT angiography (stroke)',
    'Carotid duplex ultrasound',
    'Neuropsychological testing',
    'Botox injection (migraine/spasticity)',
    'tPA administration (stroke)',
    'Video EEG monitoring',
    'Transcranial Doppler',
    'Evoked potentials',
  ],
  commonMedications: [
    'Antiepileptics (levetiracetam/valproate/lamotrigine)',
    'Triptans (sumatriptan)',
    'CGRP inhibitors (erenumab)',
    'Carbidopa/levodopa',
    'Dopamine agonists',
    'Disease-modifying therapies (MS: interferons/natalizumab/ocrelizumab)',
    'tPA (alteplase)',
    'Anticoagulants (stroke prevention)',
    'Cholinesterase inhibitors',
    'Muscle relaxants (baclofen)',
    'Corticosteroids (acute exacerbations)',
    'Immunoglobulin (IVIG)',
  ],
  anatomyRegions: ['brain', 'spine', 'head', 'full-body'],
  relatedSpecialties: ['neurosurgery', 'psychiatry', 'physical-medicine-rehabilitation', 'internal-medicine'],
};

const dermatology: MedicalSpecialty = {
  specialtyId: 'dermatology',
  name: 'Dermatology',
  spanishName: 'Dermatología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of skin, hair, nail, and mucous membrane disorders, including skin cancer, autoimmune conditions, and cosmetic dermatology.',
    es: 'Diagnóstico y tratamiento de trastornos de la piel, cabello, uñas y mucosas, incluyendo cáncer de piel, condiciones autoinmunes y dermatología cosmética.',
  },
  bodySystemsFocus: ['integumentary', 'immune'],
  commonConditions: [
    'acne-vulgaris',
    'eczema',
    'psoriasis',
    'dermatitis',
    'melanoma',
    'basal-cell-carcinoma',
    'squamous-cell-carcinoma',
    'urticaria',
    'rosacea',
    'fungal-skin-infections',
    'herpes-simplex',
    'herpes-zoster',
    'warts',
    'alopecia',
    'vitiligo',
    'seborrheic-dermatitis',
    'contact-dermatitis',
    'cellulitis',
    'scabies',
    'lichen-planus',
    'bullous-pemphigoid',
    'pemphigus-vulgaris',
    'keloid',
    'hidradenitis-suppurativa',
  ],
  commonProcedures: [
    'Skin biopsy (shave/punch/excisional)',
    'Cryotherapy',
    'Electrodesiccation and curettage',
    'Mohs micrographic surgery',
    'Excision of skin lesion',
    'Dermoscopy',
    'Phototherapy (UVB/PUVA)',
    'Intralesional injection',
    'Chemical peel',
    'Laser therapy',
    'Patch testing (allergy)',
    'Acne extraction',
  ],
  commonMedications: [
    'Topical corticosteroids',
    'Topical retinoids (tretinoin)',
    'Oral isotretinoin',
    'Topical antifungals',
    'Topical calcineurin inhibitors (tacrolimus)',
    'Biologic agents (IL-17/IL-23 inhibitors)',
    'Methotrexate',
    'Oral antibiotics (doxycycline)',
    'Antihistamines',
    'Topical antibiotics',
    'Dupilumab (eczema)',
    'Oral antifungals (terbinafine)',
  ],
  anatomyRegions: ['skin', 'full-body'],
  relatedSpecialties: ['rheumatology', 'allergy-immunology', 'plastic-surgery', 'pathology'],
};

const allergyImmunology: MedicalSpecialty = {
  specialtyId: 'allergy-immunology',
  name: 'Allergy / Immunology',
  spanishName: 'Alergia e Inmunología',
  category: 'medical',
  description: {
    en: 'Diagnosis and treatment of allergic diseases, asthma, and immune system disorders including immunodeficiency and autoimmunity.',
    es: 'Diagnóstico y tratamiento de enfermedades alérgicas, asma y trastornos del sistema inmunológico incluyendo inmunodeficiencia y autoinmunidad.',
  },
  bodySystemsFocus: ['immune', 'respiratory'],
  commonConditions: [
    'allergic-rhinitis',
    'asthma',
    'anaphylaxis',
    'food-allergy',
    'drug-allergy',
    'urticaria',
    'angioedema',
    'allergic-contact-dermatitis',
    'eczema',
    'eosinophilic-esophagitis',
    'primary-immunodeficiency',
    'common-variable-immunodeficiency',
    'selective-iga-deficiency',
    'hereditary-angioedema',
    'serum-sickness',
    'allergic-bronchopulmonary-aspergillosis',
    'latex-allergy',
    'insect-sting-allergy',
    'mast-cell-disorders',
    'chronic-spontaneous-urticaria',
  ],
  commonProcedures: [
    'Skin prick testing',
    'Intradermal skin testing',
    'Patch testing',
    'Spirometry / PFTs',
    'Methacholine challenge test',
    'Allergen immunotherapy (subcutaneous)',
    'Sublingual immunotherapy',
    'Drug desensitization',
    'Food oral challenge',
    'IgE / immunoglobulin level testing',
    'Complement level assessment',
    'Lymphocyte subset analysis',
  ],
  commonMedications: [
    'Antihistamines (cetirizine/loratadine)',
    'Intranasal corticosteroids',
    'Epinephrine auto-injector',
    'Inhaled corticosteroids',
    'Leukotriene receptor antagonists',
    'Omalizumab (anti-IgE)',
    'Biologics (dupilumab/mepolizumab)',
    'Oral corticosteroids',
    'Immunoglobulin replacement (IVIG/SCIG)',
    'Cromolyn sodium',
    'Decongestants',
    'Allergen extracts (immunotherapy)',
  ],
  anatomyRegions: ['lungs', 'skin', 'throat', 'full-body'],
  relatedSpecialties: ['pulmonology', 'dermatology', 'ent-otolaryngology', 'rheumatology', 'gastroenterology'],
};

// =============================================================================
// WOMEN'S / REPRODUCTIVE SPECIALTIES
// =============================================================================

const obgyn: MedicalSpecialty = {
  specialtyId: 'obgyn',
  name: 'Obstetrics & Gynecology',
  spanishName: 'Obstetricia y Ginecología',
  category: 'womens-reproductive',
  description: {
    en: 'Medical and surgical care of the female reproductive system, pregnancy, childbirth, and postpartum period.',
    es: 'Atención médica y quirúrgica del sistema reproductivo femenino, embarazo, parto y período posparto.',
  },
  bodySystemsFocus: ['reproductive'],
  commonConditions: [
    'pregnancy-normal',
    'preeclampsia',
    'gestational-diabetes',
    'ectopic-pregnancy',
    'miscarriage',
    'placenta-previa',
    'uterine-fibroids',
    'endometriosis',
    'polycystic-ovary-syndrome',
    'ovarian-cyst',
    'ovarian-cancer',
    'cervical-cancer',
    'endometrial-cancer',
    'pelvic-inflammatory-disease',
    'abnormal-uterine-bleeding',
    'urinary-incontinence',
    'pelvic-organ-prolapse',
    'sexually-transmitted-infections',
    'menopause',
    'infertility',
    'vulvovaginitis',
    'cervical-dysplasia',
    'preterm-labor',
    'postpartum-hemorrhage',
  ],
  commonProcedures: [
    'Cesarean section',
    'Vaginal delivery',
    'Hysterectomy',
    'Colposcopy',
    'LEEP / cone biopsy',
    'Dilation and curettage (D&C)',
    'Laparoscopy (diagnostic/surgical)',
    'IUD insertion',
    'Pap smear',
    'Obstetric ultrasound',
    'Amniocentesis',
    'Endometrial biopsy',
    'Hysteroscopy',
    'Tubal ligation',
  ],
  commonMedications: [
    'Prenatal vitamins',
    'Progesterone supplementation',
    'Oxytocin',
    'Magnesium sulfate',
    'Oral contraceptives',
    'Medroxyprogesterone',
    'Misoprostol',
    'Antibiotics (GBS prophylaxis)',
    'GnRH agonists/antagonists',
    'Hormone replacement therapy',
    'Methotrexate (ectopic pregnancy)',
    'Tocolytics (nifedipine/terbutaline)',
  ],
  anatomyRegions: ['pelvis', 'breast', 'genitourinary', 'abdomen'],
  relatedSpecialties: ['maternal-fetal-medicine', 'reproductive-endocrinology', 'urologic-surgery', 'oncology'],
};

const maternalFetalMedicine: MedicalSpecialty = {
  specialtyId: 'maternal-fetal-medicine',
  name: 'Maternal-Fetal Medicine',
  spanishName: 'Medicina Materno-Fetal',
  category: 'womens-reproductive',
  description: {
    en: 'Subspecialty of OB/GYN focused on high-risk pregnancies, prenatal diagnosis, fetal therapy, and management of maternal complications.',
    es: 'Subespecialidad de ginecobstetricia enfocada en embarazos de alto riesgo, diagnóstico prenatal, terapia fetal y manejo de complicaciones maternas.',
  },
  bodySystemsFocus: ['reproductive', 'cardiovascular', 'endocrine'],
  commonConditions: [
    'preeclampsia',
    'eclampsia',
    'hellp-syndrome',
    'gestational-diabetes',
    'preterm-labor',
    'placenta-previa',
    'placental-abruption',
    'placenta-accreta',
    'fetal-growth-restriction',
    'multiple-gestation',
    'rh-incompatibility',
    'congenital-anomalies',
    'cervical-insufficiency',
    'preterm-premature-rupture-of-membranes',
    'chronic-hypertension-in-pregnancy',
    'antiphospholipid-syndrome',
    'fetal-hydrops',
    'oligohydramnios',
    'polyhydramnios',
    'cholestasis-of-pregnancy',
  ],
  commonProcedures: [
    'High-risk prenatal ultrasound',
    'Amniocentesis',
    'Chorionic villus sampling (CVS)',
    'Fetal echocardiography',
    'Cervical cerclage',
    'Fetal blood sampling (cordocentesis)',
    'Non-stress test (NST)',
    'Biophysical profile',
    'Cell-free DNA screening',
    'Fetal MRI interpretation',
    'External cephalic version',
    'Intrauterine transfusion',
  ],
  commonMedications: [
    'Magnesium sulfate',
    'Betamethasone (fetal lung maturity)',
    'Labetalol / nifedipine (BP management)',
    'Progesterone (preterm prevention)',
    'Insulin (gestational diabetes)',
    'Low-dose aspirin (preeclampsia prevention)',
    'RhoGAM (anti-D immunoglobulin)',
    'Tocolytics',
    'Antibiotics (PPROM)',
    'Ursodeoxycholic acid (cholestasis)',
  ],
  anatomyRegions: ['pelvis', 'abdomen'],
  relatedSpecialties: ['obgyn', 'neonatology', 'genetics', 'cardiology'],
};

const reproductiveEndocrinology: MedicalSpecialty = {
  specialtyId: 'reproductive-endocrinology',
  name: 'Reproductive Endocrinology',
  spanishName: 'Endocrinología Reproductiva',
  category: 'womens-reproductive',
  description: {
    en: 'Subspecialty focused on reproductive hormonal disorders, infertility evaluation and treatment, and assisted reproductive technology.',
    es: 'Subespecialidad enfocada en trastornos hormonales reproductivos, evaluación y tratamiento de infertilidad y tecnología de reproducción asistida.',
  },
  bodySystemsFocus: ['reproductive', 'endocrine'],
  commonConditions: [
    'infertility',
    'polycystic-ovary-syndrome',
    'endometriosis',
    'premature-ovarian-insufficiency',
    'amenorrhea',
    'recurrent-pregnancy-loss',
    'uterine-fibroids',
    'tubal-factor-infertility',
    'male-factor-infertility',
    'ovulatory-dysfunction',
    'diminished-ovarian-reserve',
    'hyperprolactinemia',
    'hypothalamic-amenorrhea',
    'uterine-anomalies',
    'asherman-syndrome',
  ],
  commonProcedures: [
    'In vitro fertilization (IVF)',
    'Intrauterine insemination (IUI)',
    'Ovarian stimulation protocols',
    'Egg retrieval (oocyte aspiration)',
    'Embryo transfer',
    'Hysterosalpingogram (HSG)',
    'Saline infusion sonogram',
    'Laparoscopy (endometriosis/tubal)',
    'Semen analysis',
    'Endometrial biopsy',
    'Preimplantation genetic testing',
    'Fertility preservation (egg/embryo/sperm freezing)',
  ],
  commonMedications: [
    'Clomiphene citrate',
    'Letrozole',
    'Gonadotropins (FSH/LH)',
    'GnRH agonists (leuprolide)',
    'GnRH antagonists (cetrorelix/ganirelix)',
    'Progesterone supplementation',
    'Estradiol',
    'hCG trigger',
    'Metformin (PCOS)',
    'Cabergoline (prolactinoma)',
  ],
  anatomyRegions: ['pelvis', 'genitourinary'],
  relatedSpecialties: ['obgyn', 'endocrinology', 'urologic-surgery', 'genetics'],
};

// =============================================================================
// MENTAL HEALTH SPECIALTIES
// =============================================================================

const psychiatry: MedicalSpecialty = {
  specialtyId: 'psychiatry',
  name: 'Psychiatry',
  spanishName: 'Psiquiatría',
  category: 'mental-health',
  description: {
    en: 'Diagnosis, treatment, and prevention of mental, emotional, and behavioral disorders using pharmacotherapy, psychotherapy, and other interventions.',
    es: 'Diagnóstico, tratamiento y prevención de trastornos mentales, emocionales y del comportamiento utilizando farmacoterapia, psicoterapia y otras intervenciones.',
  },
  bodySystemsFocus: ['psychiatric', 'neurological'],
  commonConditions: [
    'major-depressive-disorder',
    'generalized-anxiety-disorder',
    'panic-disorder',
    'bipolar-disorder',
    'schizophrenia',
    'schizoaffective-disorder',
    'post-traumatic-stress-disorder',
    'obsessive-compulsive-disorder',
    'social-anxiety-disorder',
    'attention-deficit-hyperactivity-disorder',
    'anorexia-nervosa',
    'bulimia-nervosa',
    'borderline-personality-disorder',
    'insomnia',
    'substance-use-disorder',
    'alcohol-use-disorder',
    'opioid-use-disorder',
    'autism-spectrum-disorder',
    'adjustment-disorder',
    'somatic-symptom-disorder',
    'conversion-disorder',
    'delirium',
    'psychosis',
    'suicidal-ideation',
  ],
  commonProcedures: [
    'Psychiatric evaluation',
    'Mental status examination',
    'Psychotherapy (CBT/DBT/psychodynamic)',
    'Medication management',
    'Electroconvulsive therapy (ECT)',
    'Transcranial magnetic stimulation (TMS)',
    'Psychological testing',
    'Suicide risk assessment',
    'Substance use screening (CAGE/AUDIT)',
    'PHQ-9 / GAD-7 scoring',
    'Involuntary commitment evaluation',
    'Crisis intervention',
  ],
  commonMedications: [
    'SSRIs (sertraline/fluoxetine/escitalopram)',
    'SNRIs (venlafaxine/duloxetine)',
    'Atypical antipsychotics (quetiapine/risperidone/aripiprazole)',
    'Mood stabilizers (lithium/valproate/lamotrigine)',
    'Benzodiazepines (lorazepam/clonazepam)',
    'Stimulants (methylphenidate/amphetamine)',
    'Bupropion',
    'Trazodone',
    'Buspirone',
    'Clozapine',
    'MAOIs',
    'Ketamine / esketamine',
  ],
  anatomyRegions: ['brain'],
  relatedSpecialties: ['neurology', 'addiction-medicine', 'internal-medicine', 'pediatrics'],
};

const addictionMedicine: MedicalSpecialty = {
  specialtyId: 'addiction-medicine',
  name: 'Addiction Medicine',
  spanishName: 'Medicina de Adicciones',
  category: 'mental-health',
  description: {
    en: 'Prevention, evaluation, diagnosis, and treatment of substance use disorders and addictive behaviors, including medical detoxification and harm reduction.',
    es: 'Prevención, evaluación, diagnóstico y tratamiento de trastornos por uso de sustancias y comportamientos adictivos, incluyendo desintoxicación médica y reducción de daños.',
  },
  bodySystemsFocus: ['psychiatric', 'neurological', 'hepatic'],
  commonConditions: [
    'alcohol-use-disorder',
    'opioid-use-disorder',
    'tobacco-use-disorder',
    'cannabis-use-disorder',
    'stimulant-use-disorder',
    'benzodiazepine-use-disorder',
    'alcohol-withdrawal',
    'opioid-withdrawal',
    'delirium-tremens',
    'wernicke-encephalopathy',
    'alcoholic-liver-disease',
    'drug-overdose',
    'fetal-alcohol-syndrome',
    'gambling-disorder',
    'polysubstance-abuse',
  ],
  commonProcedures: [
    'Substance use assessment (SBIRT)',
    'Medical detoxification',
    'CIWA-Ar scoring (alcohol withdrawal)',
    'COWS scoring (opioid withdrawal)',
    'Motivational interviewing',
    'Urine drug screen interpretation',
    'Naloxone administration training',
    'MAT (medication-assisted treatment) initiation',
    'Group therapy facilitation',
    '12-step facilitation',
    'Contingency management',
    'Harm reduction counseling',
  ],
  commonMedications: [
    'Buprenorphine / naloxone (Suboxone)',
    'Methadone',
    'Naltrexone (oral/injectable)',
    'Acamprosate',
    'Disulfiram',
    'Nicotine replacement therapy',
    'Varenicline',
    'Bupropion (smoking cessation)',
    'Gabapentin (alcohol use)',
    'Chlordiazepoxide (alcohol withdrawal)',
    'Clonidine (opioid withdrawal)',
    'Thiamine / folate supplementation',
  ],
  anatomyRegions: ['brain'],
  relatedSpecialties: ['psychiatry', 'internal-medicine', 'emergency-medicine', 'gastroenterology'],
};

// =============================================================================
// DIAGNOSTIC SPECIALTIES
// =============================================================================

const radiology: MedicalSpecialty = {
  specialtyId: 'radiology',
  name: 'Radiology',
  spanishName: 'Radiología',
  category: 'diagnostic',
  description: {
    en: 'Medical imaging for diagnosis and treatment of diseases. Includes X-ray, CT, MRI, ultrasound, mammography, and interventional procedures.',
    es: 'Imagenología médica para diagnóstico y tratamiento de enfermedades. Incluye rayos X, TC, RM, ultrasonido, mamografía y procedimientos intervencionistas.',
  },
  bodySystemsFocus: ['multi-system'],
  commonConditions: [
    'fractures',
    'pneumonia',
    'lung-cancer',
    'pulmonary-embolism',
    'stroke-ischemic',
    'brain-tumor',
    'abdominal-aortic-aneurysm',
    'appendicitis',
    'bowel-obstruction',
    'kidney-stones',
    'breast-cancer',
    'liver-lesions',
    'spinal-stenosis',
    'deep-vein-thrombosis',
    'aortic-dissection',
    'intracranial-hemorrhage',
    'pleural-effusion',
    'pancreatitis',
    'ovarian-cyst',
    'musculoskeletal-tumors',
  ],
  commonProcedures: [
    'X-ray interpretation',
    'CT scan interpretation',
    'MRI interpretation',
    'Ultrasound interpretation',
    'Mammography / tomosynthesis',
    'Fluoroscopy',
    'CT-guided biopsy',
    'Angiography',
    'Embolization',
    'Drainage catheter placement',
    'Venous access placement (PICC/port)',
    'Ablation (RFA/microwave)',
  ],
  commonMedications: [
    'Iodinated contrast agents',
    'Gadolinium contrast agents',
    'Barium sulfate',
    'Sedation agents (midazolam/propofol)',
    'Local anesthetics',
    'Epinephrine (contrast reaction)',
    'Diphenhydramine (contrast reaction)',
    'Glucagon (GI imaging)',
    'Steroids (contrast allergy premedication)',
    'Acetylcysteine (renal protection)',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['all specialties'],
};

const pathology: MedicalSpecialty = {
  specialtyId: 'pathology',
  name: 'Pathology',
  spanishName: 'Patología',
  category: 'diagnostic',
  description: {
    en: 'Laboratory study of disease through examination of tissues, cells, and body fluids. Includes surgical pathology, cytopathology, and clinical laboratory medicine.',
    es: 'Estudio de laboratorio de enfermedades mediante el examen de tejidos, células y fluidos corporales. Incluye patología quirúrgica, citopatología y medicina de laboratorio clínico.',
  },
  bodySystemsFocus: ['multi-system'],
  commonConditions: [
    'cancer-all-types',
    'lymphoma',
    'leukemia',
    'anemia',
    'coagulopathy',
    'autoimmune-diseases',
    'infectious-diseases',
    'inflammatory-conditions',
    'thyroid-nodules',
    'cervical-dysplasia',
    'glomerulonephritis',
    'hepatitis',
    'vasculitis',
    'transplant-rejection',
    'amyloidosis',
  ],
  commonProcedures: [
    'Surgical specimen gross examination',
    'Histopathologic analysis',
    'Frozen section analysis',
    'Fine needle aspiration cytology',
    'Pap smear interpretation',
    'Immunohistochemistry',
    'Flow cytometry',
    'Molecular diagnostics (PCR/FISH/NGS)',
    'Blood bank / transfusion medicine',
    'Autopsy',
    'Bone marrow biopsy interpretation',
    'Special stains',
  ],
  commonMedications: [
    'Laboratory reagents',
    'Fixatives (formalin)',
    'Staining agents (H&E, special stains)',
    'Blood products (pRBC/FFP/platelets/cryo)',
    'Transfusion reaction management agents',
    'Immunohistochemistry antibodies',
    'Molecular probes',
    'Tissue processing reagents',
    'Quality control materials',
    'Cytology fixatives',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['all specialties'],
};

const nuclearMedicine: MedicalSpecialty = {
  specialtyId: 'nuclear-medicine',
  name: 'Nuclear Medicine',
  spanishName: 'Medicina Nuclear',
  category: 'diagnostic',
  description: {
    en: 'Use of radioactive tracers for diagnosis and treatment of disease, including PET/CT, thyroid scans, cardiac imaging, and radionuclide therapy.',
    es: 'Uso de trazadores radioactivos para diagnóstico y tratamiento de enfermedades, incluyendo PET/TC, gammagrafía tiroidea, imagen cardíaca y terapia con radionúclidos.',
  },
  bodySystemsFocus: ['multi-system'],
  commonConditions: [
    'thyroid-cancer',
    'hyperthyroidism',
    'lung-cancer',
    'lymphoma',
    'bone-metastases',
    'coronary-artery-disease',
    'pulmonary-embolism',
    'osteomyelitis',
    'neuroendocrine-tumors',
    'pheochromocytoma',
    'parathyroid-adenoma',
    'gastrointestinal-bleeding',
    'brain-tumor',
    'dementia',
    'epilepsy',
  ],
  commonProcedures: [
    'PET/CT scan',
    'Thyroid uptake and scan',
    'Bone scan (scintigraphy)',
    'Myocardial perfusion imaging',
    'VQ scan (ventilation-perfusion)',
    'MUGA scan',
    'Renal scan (MAG3/DTPA)',
    'Hepatobiliary scan (HIDA)',
    'Parathyroid sestamibi scan',
    'Sentinel lymph node mapping',
    'I-131 therapy (thyroid)',
    'Octreotide scan',
  ],
  commonMedications: [
    'Technetium-99m radiopharmaceuticals',
    'Fluorodeoxyglucose (FDG) F-18',
    'Iodine-131 (thyroid ablation)',
    'Thallium-201',
    'Gallium-67',
    'Lutetium-177 (PRRT)',
    'Radium-223 (bone metastases)',
    'Dipyridamole / adenosine (stress agents)',
    'Regadenoson',
    'Thyroid blocking agents (potassium iodide)',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['radiology', 'endocrinology', 'oncology', 'cardiology'],
};

// =============================================================================
// OTHER SPECIALTIES
// =============================================================================

const emergencyMedicine: MedicalSpecialty = {
  specialtyId: 'emergency-medicine',
  name: 'Emergency Medicine',
  spanishName: 'Medicina de Emergencias',
  category: 'other',
  description: {
    en: 'Immediate evaluation, stabilization, diagnosis, and treatment of acute illnesses and injuries in the emergency department.',
    es: 'Evaluación inmediata, estabilización, diagnóstico y tratamiento de enfermedades agudas y lesiones en el departamento de emergencias.',
  },
  bodySystemsFocus: ['multi-system', 'cardiovascular', 'neurological', 'respiratory'],
  commonConditions: [
    'myocardial-infarction',
    'stroke-ischemic',
    'trauma',
    'sepsis',
    'pneumonia',
    'fractures',
    'appendicitis',
    'pulmonary-embolism',
    'anaphylaxis',
    'asthma-exacerbation',
    'drug-overdose',
    'diabetic-ketoacidosis',
    'gastrointestinal-bleeding',
    'acute-abdomen',
    'cardiac-arrest',
    'ectopic-pregnancy',
    'suicidal-ideation',
    'laceration',
    'burns',
    'seizure',
    'aortic-dissection',
    'meningitis',
    'kidney-stones',
    'testicular-torsion',
  ],
  commonProcedures: [
    'Advanced cardiac life support (ACLS)',
    'Endotracheal intubation',
    'Central venous access',
    'Chest tube placement',
    'Laceration repair',
    'Fracture reduction and splinting',
    'Procedural sedation',
    'Rapid sequence intubation',
    'Cardioversion / defibrillation',
    'Lumbar puncture',
    'Focused ultrasound (FAST/eFAST)',
    'IO access',
    'Needle thoracostomy',
    'Pericardiocentesis',
  ],
  commonMedications: [
    'Epinephrine',
    'tPA (alteplase)',
    'Morphine / fentanyl',
    'Norepinephrine',
    'Broad-spectrum antibiotics',
    'Heparin / enoxaparin',
    'Nitroglycerin',
    'Albuterol',
    'Ondansetron',
    'Ketamine',
    'Naloxone',
    'Activated charcoal',
    'Normal saline / lactated Ringer',
    'Amiodarone',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['critical-care', 'trauma-surgery', 'cardiology', 'neurology', 'internal-medicine'],
};

const criticalCare: MedicalSpecialty = {
  specialtyId: 'critical-care',
  name: 'Critical Care / ICU',
  spanishName: 'Cuidados Intensivos / UCI',
  category: 'other',
  description: {
    en: 'Management of life-threatening conditions requiring intensive monitoring, organ support, and complex medical decision-making in the ICU.',
    es: 'Manejo de condiciones potencialmente mortales que requieren monitoreo intensivo, soporte de órganos y toma de decisiones médicas complejas en la UCI.',
  },
  bodySystemsFocus: ['multi-system', 'cardiovascular', 'respiratory', 'neurological', 'renal'],
  commonConditions: [
    'sepsis',
    'septic-shock',
    'acute-respiratory-distress-syndrome',
    'respiratory-failure',
    'cardiogenic-shock',
    'multiorgan-failure',
    'traumatic-brain-injury',
    'status-epilepticus',
    'acute-kidney-injury',
    'disseminated-intravascular-coagulation',
    'massive-hemorrhage',
    'cardiac-arrest',
    'pulmonary-embolism',
    'pneumonia',
    'diabetic-ketoacidosis',
    'hepatic-failure',
    'pancreatitis',
    'burns',
    'anaphylaxis',
    'rhabdomyolysis',
  ],
  commonProcedures: [
    'Mechanical ventilation management',
    'Central venous catheter placement',
    'Arterial line placement',
    'Endotracheal intubation',
    'Bronchoscopy (ICU)',
    'Continuous renal replacement therapy',
    'Prone positioning',
    'Hemodynamic monitoring (Swan-Ganz)',
    'Tracheostomy',
    'Chest tube management',
    'Targeted temperature management',
    'ECMO management',
    'Paracentesis / thoracentesis',
  ],
  commonMedications: [
    'Vasopressors (norepinephrine/vasopressin)',
    'Sedatives (propofol/midazolam/dexmedetomidine)',
    'Analgesics (fentanyl/morphine)',
    'Neuromuscular blockers',
    'Broad-spectrum antibiotics',
    'Insulin drip',
    'Blood products',
    'Corticosteroids',
    'Diuretics',
    'Electrolyte replacements',
    'DVT prophylaxis',
    'Stress ulcer prophylaxis',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['emergency-medicine', 'pulmonology', 'cardiology', 'anesthesiology', 'neurology'],
};

const anesthesiology: MedicalSpecialty = {
  specialtyId: 'anesthesiology',
  name: 'Anesthesiology',
  spanishName: 'Anestesiología',
  category: 'other',
  description: {
    en: 'Administration of anesthesia for surgical and procedural care, perioperative medicine, pain management, and critical care.',
    es: 'Administración de anestesia para atención quirúrgica y procedimientos, medicina perioperatoria, manejo del dolor y cuidados intensivos.',
  },
  bodySystemsFocus: ['neurological', 'cardiovascular', 'respiratory'],
  commonConditions: [
    'perioperative-management',
    'malignant-hyperthermia',
    'difficult-airway',
    'postoperative-nausea-vomiting',
    'postoperative-pain',
    'local-anesthetic-toxicity',
    'anaphylaxis',
    'bronchospasm',
    'hypotension',
    'aspiration-pneumonitis',
    'awareness-under-anesthesia',
    'epidural-hematoma',
    'spinal-headache',
    'transfusion-reactions',
    'obstructive-sleep-apnea',
  ],
  commonProcedures: [
    'General anesthesia induction/maintenance',
    'Endotracheal intubation',
    'Spinal anesthesia',
    'Epidural anesthesia',
    'Peripheral nerve block',
    'Arterial line placement',
    'Central venous catheter placement',
    'Fiberoptic intubation',
    'Laryngeal mask airway placement',
    'Monitored anesthesia care (MAC)',
    'Transesophageal echocardiography',
    'Regional anesthesia (ultrasound-guided)',
  ],
  commonMedications: [
    'Propofol',
    'Sevoflurane / desflurane',
    'Fentanyl / remifentanil / sufentanil',
    'Rocuronium / succinylcholine',
    'Midazolam',
    'Ketamine',
    'Dexmedetomidine',
    'Bupivacaine / ropivacaine / lidocaine',
    'Neostigmine / sugammadex',
    'Ondansetron / dexamethasone',
    'Ephedrine / phenylephrine',
    'Glycopyrrolate / atropine',
  ],
  anatomyRegions: ['full-body', 'spine'],
  relatedSpecialties: ['critical-care', 'pain-medicine', 'emergency-medicine'],
};

const physicalMedicineRehabilitation: MedicalSpecialty = {
  specialtyId: 'physical-medicine-rehabilitation',
  name: 'Physical Medicine & Rehabilitation',
  spanishName: 'Medicina Física y Rehabilitación',
  category: 'other',
  description: {
    en: 'Restoration of functional ability and quality of life for patients with physical impairments or disabilities affecting the brain, spinal cord, nerves, bones, joints, and muscles.',
    es: 'Restauración de la capacidad funcional y calidad de vida para pacientes con impedimentos físicos o discapacidades que afectan cerebro, médula espinal, nervios, huesos, articulaciones y músculos.',
  },
  bodySystemsFocus: ['musculoskeletal', 'neurological'],
  commonConditions: [
    'stroke-rehabilitation',
    'traumatic-brain-injury-rehabilitation',
    'spinal-cord-injury',
    'low-back-pain',
    'cervical-radiculopathy',
    'lumbar-radiculopathy',
    'carpal-tunnel-syndrome',
    'osteoarthritis',
    'amputation-rehabilitation',
    'multiple-sclerosis',
    'post-joint-replacement-rehabilitation',
    'sports-injury',
    'tendinitis',
    'bursitis',
    'fibromyalgia',
    'complex-regional-pain-syndrome',
    'spasticity',
    'deconditioning',
    'lymphedema',
    'neurogenic-bladder',
  ],
  commonProcedures: [
    'Electromyography / nerve conduction studies',
    'Joint injection (corticosteroid/hyaluronic)',
    'Trigger point injection',
    'Botox injection (spasticity)',
    'Fluoroscopic-guided injection',
    'Functional capacity evaluation',
    'Gait analysis',
    'Wheelchair assessment and fitting',
    'Prosthetic prescription',
    'Orthotic prescription',
    'Physical therapy prescription',
    'Occupational therapy coordination',
  ],
  commonMedications: [
    'NSAIDs',
    'Muscle relaxants (baclofen/tizanidine)',
    'Gabapentin / pregabalin',
    'Corticosteroid injections',
    'Botulinum toxin (spasticity)',
    'Acetaminophen',
    'Duloxetine',
    'Topical analgesics (diclofenac/lidocaine)',
    'Antispasticity agents (dantrolene)',
    'Tricyclic antidepressants (neuropathic pain)',
  ],
  anatomyRegions: ['spine', 'upper-extremity', 'lower-extremity', 'brain', 'full-body'],
  relatedSpecialties: ['neurology', 'orthopedic-surgery', 'pain-medicine', 'sports-medicine'],
};

const ophthalmology: MedicalSpecialty = {
  specialtyId: 'ophthalmology',
  name: 'Ophthalmology',
  spanishName: 'Oftalmología',
  category: 'other',
  description: {
    en: 'Comprehensive medical and surgical eye care, including diagnosis and treatment of all eye diseases, vision correction, and preventive eye care.',
    es: 'Atención oftalmológica integral médica y quirúrgica, incluyendo diagnóstico y tratamiento de todas las enfermedades oculares, corrección de la visión y atención preventiva.',
  },
  bodySystemsFocus: ['sensory'],
  commonConditions: [
    'cataract',
    'glaucoma',
    'macular-degeneration',
    'diabetic-retinopathy',
    'refractive-errors',
    'dry-eye-syndrome',
    'conjunctivitis',
    'uveitis',
    'retinal-detachment',
    'optic-neuritis',
    'corneal-ulcer',
    'keratoconus',
    'blepharitis',
    'strabismus',
    'amblyopia',
    'orbital-cellulitis',
    'central-retinal-artery-occlusion',
    'central-retinal-vein-occlusion',
    'papilledema',
    'pterygium',
  ],
  commonProcedures: [
    'Comprehensive eye exam',
    'Slit lamp examination',
    'Tonometry (IOP measurement)',
    'Fundoscopy / dilated eye exam',
    'Optical coherence tomography (OCT)',
    'Visual field testing',
    'Fluorescein angiography',
    'Cataract surgery',
    'Intravitreal injection',
    'Laser photocoagulation',
    'LASIK / refractive surgery',
    'Trabeculectomy',
  ],
  commonMedications: [
    'Topical prostaglandins (latanoprost)',
    'Topical beta-blockers (timolol)',
    'Anti-VEGF agents (ranibizumab/aflibercept)',
    'Topical corticosteroids (prednisolone)',
    'Topical antibiotics (moxifloxacin)',
    'Artificial tears',
    'Cycloplegics (atropine/cyclopentolate)',
    'Carbonic anhydrase inhibitors',
    'Topical NSAIDs (ketorolac)',
    'Immunosuppressants (uveitis)',
  ],
  anatomyRegions: ['eyes'],
  relatedSpecialties: ['ophthalmologic-surgery', 'neurology', 'endocrinology', 'rheumatology'],
};

const painMedicine: MedicalSpecialty = {
  specialtyId: 'pain-medicine',
  name: 'Pain Medicine',
  spanishName: 'Medicina del Dolor',
  category: 'other',
  description: {
    en: 'Multidisciplinary evaluation and treatment of acute and chronic pain using pharmacologic, interventional, and behavioral approaches.',
    es: 'Evaluación y tratamiento multidisciplinario del dolor agudo y crónico utilizando enfoques farmacológicos, intervencionistas y conductuales.',
  },
  bodySystemsFocus: ['neurological', 'musculoskeletal'],
  commonConditions: [
    'chronic-low-back-pain',
    'cervical-radiculopathy',
    'lumbar-radiculopathy',
    'complex-regional-pain-syndrome',
    'fibromyalgia',
    'neuropathic-pain',
    'cancer-pain',
    'post-surgical-pain',
    'headache-disorders',
    'trigeminal-neuralgia',
    'phantom-limb-pain',
    'myofascial-pain-syndrome',
    'facet-joint-syndrome',
    'sacroiliac-joint-pain',
    'spinal-stenosis',
    'failed-back-surgery-syndrome',
    'diabetic-neuropathy',
    'postherpetic-neuralgia',
    'pelvic-pain',
    'abdominal-pain-chronic',
  ],
  commonProcedures: [
    'Epidural steroid injection',
    'Facet joint injection / medial branch block',
    'Radiofrequency ablation',
    'Spinal cord stimulator implantation',
    'Trigger point injection',
    'Nerve block (peripheral)',
    'Sacroiliac joint injection',
    'Intrathecal drug delivery system',
    'Stellate ganglion block',
    'Celiac plexus block',
    'Sympathetic nerve block',
    'Kyphoplasty / vertebroplasty',
  ],
  commonMedications: [
    'Gabapentin / pregabalin',
    'Duloxetine / venlafaxine',
    'Tricyclic antidepressants (amitriptyline)',
    'NSAIDs',
    'Muscle relaxants',
    'Opioid analgesics (monitored use)',
    'Topical lidocaine',
    'Topical capsaicin',
    'Corticosteroids (injections)',
    'Ketamine (infusion)',
    'Acetaminophen',
    'Buprenorphine (pain formulation)',
  ],
  anatomyRegions: ['spine', 'full-body'],
  relatedSpecialties: ['anesthesiology', 'physical-medicine-rehabilitation', 'neurology', 'orthopedic-surgery'],
};

const palliativeCare: MedicalSpecialty = {
  specialtyId: 'palliative-care',
  name: 'Palliative Care',
  spanishName: 'Cuidados Paliativos',
  category: 'other',
  description: {
    en: 'Specialized medical care focused on relief of symptoms, pain, and stress of serious illness, improving quality of life for patients and families.',
    es: 'Atención médica especializada enfocada en el alivio de síntomas, dolor y estrés de enfermedades graves, mejorando la calidad de vida de pacientes y familias.',
  },
  bodySystemsFocus: ['multi-system'],
  commonConditions: [
    'cancer-advanced',
    'heart-failure-advanced',
    'copd-advanced',
    'chronic-kidney-disease-advanced',
    'dementia-advanced',
    'amyotrophic-lateral-sclerosis',
    'cirrhosis-advanced',
    'pulmonary-fibrosis',
    'cancer-pain',
    'nausea-vomiting-terminal',
    'dyspnea-terminal',
    'delirium',
    'cachexia',
    'constipation-chronic',
    'anxiety-end-of-life',
  ],
  commonProcedures: [
    'Goals of care discussion',
    'Advance directive completion',
    'Symptom assessment scales',
    'Family meeting facilitation',
    'Code status determination',
    'Hospice referral',
    'Pain assessment and management',
    'Prognostic counseling',
    'Palliative sedation assessment',
    'Spiritual care coordination',
    'Bereavement support',
    'Ethics consultation coordination',
  ],
  commonMedications: [
    'Opioid analgesics (morphine/oxycodone/hydromorphone)',
    'Antiemetics (ondansetron/haloperidol/metoclopramide)',
    'Anxiolytics (lorazepam)',
    'Corticosteroids (dexamethasone)',
    'Laxatives (senna/docusate/polyethylene glycol)',
    'Anticholinergics (glycopyrrolate/scopolamine)',
    'Haloperidol (delirium)',
    'Gabapentin (neuropathic pain)',
    'Mirtazapine (appetite/nausea)',
    'Nebulized morphine (dyspnea)',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['oncology', 'geriatrics', 'internal-medicine', 'pain-medicine', 'psychiatry'],
};

const sportsMedicine: MedicalSpecialty = {
  specialtyId: 'sports-medicine',
  name: 'Sports Medicine',
  spanishName: 'Medicina Deportiva',
  category: 'other',
  description: {
    en: 'Prevention, diagnosis, and treatment of sports-related injuries and exercise-related conditions, promoting physical fitness and athletic performance.',
    es: 'Prevención, diagnóstico y tratamiento de lesiones deportivas y condiciones relacionadas con el ejercicio, promoviendo la aptitud física y el rendimiento atlético.',
  },
  bodySystemsFocus: ['musculoskeletal'],
  commonConditions: [
    'anterior-cruciate-ligament-tear',
    'meniscus-tear',
    'rotator-cuff-tear',
    'ankle-sprain',
    'concussion',
    'stress-fracture',
    'tennis-elbow',
    'golfers-elbow',
    'patellofemoral-syndrome',
    'shin-splints',
    'achilles-tendinitis',
    'plantar-fasciitis',
    'hamstring-strain',
    'groin-strain',
    'iliotibial-band-syndrome',
    'shoulder-dislocation',
    'labral-tear',
    'exercise-induced-asthma',
    'heat-illness',
    'overtraining-syndrome',
  ],
  commonProcedures: [
    'Musculoskeletal ultrasound',
    'Joint injection (corticosteroid/PRP)',
    'Concussion evaluation (SCAT5)',
    'Pre-participation physical exam',
    'Sideline assessment',
    'Fracture/dislocation reduction',
    'Splinting / casting',
    'Return-to-play protocol',
    'Exercise prescription',
    'Body composition analysis',
    'Gait and biomechanical analysis',
    'Platelet-rich plasma (PRP) injection',
  ],
  commonMedications: [
    'NSAIDs',
    'Acetaminophen',
    'Corticosteroid injections',
    'Topical analgesics',
    'Muscle relaxants',
    'Albuterol (exercise-induced asthma)',
    'Platelet-rich plasma (PRP)',
    'Hyaluronic acid injections',
    'Ice / compression protocols',
    'Oral electrolyte solutions',
  ],
  anatomyRegions: ['lower-extremity', 'upper-extremity', 'spine', 'head'],
  relatedSpecialties: ['orthopedic-surgery', 'physical-medicine-rehabilitation', 'family-medicine', 'emergency-medicine'],
};

const preventiveMedicine: MedicalSpecialty = {
  specialtyId: 'preventive-medicine',
  name: 'Preventive Medicine / Public Health',
  spanishName: 'Medicina Preventiva / Salud Pública',
  category: 'other',
  description: {
    en: 'Prevention of disease and promotion of health at individual and population levels, including epidemiology, occupational medicine, and health policy.',
    es: 'Prevención de enfermedades y promoción de la salud a nivel individual y poblacional, incluyendo epidemiología, medicina ocupacional y políticas de salud.',
  },
  bodySystemsFocus: ['multi-system'],
  commonConditions: [
    'obesity',
    'tobacco-use-disorder',
    'hypertension',
    'hyperlipidemia',
    'type-2-diabetes',
    'vaccine-preventable-diseases',
    'occupational-lung-disease',
    'lead-poisoning',
    'sexually-transmitted-infections',
    'tuberculosis',
    'cancer-screening-conditions',
    'cardiovascular-risk',
    'vitamin-d-deficiency',
    'iron-deficiency-anemia',
    'travel-related-illness',
  ],
  commonProcedures: [
    'Health risk assessment',
    'Cancer screening coordination (mammogram/colonoscopy/Pap)',
    'Immunization administration',
    'Smoking cessation counseling',
    'Nutritional counseling',
    'Exercise prescription',
    'Occupational health evaluation',
    'STI screening',
    'Blood pressure screening',
    'Cholesterol screening',
    'Diabetes screening (HbA1c/FPG)',
    'Travel medicine consultation',
    'Epidemiologic investigation',
  ],
  commonMedications: [
    'Vaccines (all types)',
    'Statins (primary prevention)',
    'Low-dose aspirin (selected populations)',
    'Nicotine replacement therapy',
    'Varenicline',
    'PrEP (HIV prevention)',
    'Folic acid supplementation',
    'Vitamin D supplementation',
    'Fluoride supplementation',
    'Malaria prophylaxis',
  ],
  anatomyRegions: ['full-body'],
  relatedSpecialties: ['family-medicine', 'internal-medicine', 'infectious-disease', 'occupational-medicine'],
};

// =============================================================================
// MASTER COLLECTION
// =============================================================================

export const MEDICAL_SPECIALTIES: MedicalSpecialty[] = [
  // Primary Care
  familyMedicine,
  internalMedicine,
  pediatrics,
  geriatrics,
  // Surgical
  generalSurgery,
  orthopedicSurgery,
  neurosurgery,
  cardiothoracicSurgery,
  vascularSurgery,
  plasticSurgery,
  urologicSurgery,
  ophthalmologicSurgery,
  entOtolaryngology,
  oralMaxillofacialSurgery,
  // Medical
  cardiology,
  pulmonology,
  gastroenterology,
  nephrology,
  endocrinology,
  hematologyOncology,
  rheumatology,
  infectiousDisease,
  neurology,
  dermatology,
  allergyImmunology,
  // Women's / Reproductive
  obgyn,
  maternalFetalMedicine,
  reproductiveEndocrinology,
  // Mental Health
  psychiatry,
  addictionMedicine,
  // Diagnostic
  radiology,
  pathology,
  nuclearMedicine,
  // Other
  emergencyMedicine,
  criticalCare,
  anesthesiology,
  physicalMedicineRehabilitation,
  ophthalmology,
  painMedicine,
  palliativeCare,
  sportsMedicine,
  preventiveMedicine,
];

// =============================================================================
// LOOKUP INDEXES (built once at load time)
// =============================================================================

const _specialtyById = new Map<string, MedicalSpecialty>();
const _specialtiesByCondition = new Map<string, MedicalSpecialty[]>();
const _specialtiesByRegion = new Map<AnatomyRegion, MedicalSpecialty[]>();
const _specialtiesBySystem = new Map<BodySystemFocus, MedicalSpecialty[]>();

function _buildIndexes(): void {
  for (const spec of MEDICAL_SPECIALTIES) {
    _specialtyById.set(spec.specialtyId, spec);

    for (const condId of spec.commonConditions) {
      const list = _specialtiesByCondition.get(condId) ?? [];
      list.push(spec);
      _specialtiesByCondition.set(condId, list);
    }

    for (const region of spec.anatomyRegions) {
      const list = _specialtiesByRegion.get(region) ?? [];
      list.push(spec);
      _specialtiesByRegion.set(region, list);
    }

    for (const system of spec.bodySystemsFocus) {
      const list = _specialtiesBySystem.get(system) ?? [];
      list.push(spec);
      _specialtiesBySystem.set(system, list);
    }
  }
}

_buildIndexes();

// =============================================================================
// PUBLIC API
// =============================================================================

/**
 * Get a single specialty by its ID.
 * Returns undefined if not found.
 */
export function getSpecialty(specialtyId: string): MedicalSpecialty | undefined {
  return _specialtyById.get(specialtyId);
}

/**
 * Get all specialties that list a given conditionId among their common conditions.
 * Returns an empty array if no specialty covers the condition.
 */
export function getSpecialtiesForCondition(conditionId: string): MedicalSpecialty[] {
  return _specialtiesByCondition.get(conditionId) ?? [];
}

/**
 * Get all specialties relevant to a given anatomy region.
 * Returns an empty array if no specialty maps to that region.
 */
export function getSpecialtiesForRegion(region: AnatomyRegion): MedicalSpecialty[] {
  return _specialtiesByRegion.get(region) ?? [];
}

/**
 * Get all specialties that focus on a given body system.
 * Returns an empty array if no specialty covers that system.
 */
export function getSpecialtiesForBodySystem(system: BodySystemFocus): MedicalSpecialty[] {
  return _specialtiesBySystem.get(system) ?? [];
}

/**
 * Get all specialties in a given category.
 */
export function getSpecialtiesByCategory(category: MedicalSpecialty['category']): MedicalSpecialty[] {
  return MEDICAL_SPECIALTIES.filter((s) => s.category === category);
}

/**
 * Search specialties by name (case-insensitive, matches English or Spanish name).
 */
export function searchSpecialties(query: string): MedicalSpecialty[] {
  const q = query.toLowerCase();
  return MEDICAL_SPECIALTIES.filter(
    (s) => s.name.toLowerCase().includes(q) || s.spanishName.toLowerCase().includes(q)
  );
}
