/**
 * Gastrointestinal Conditions Database
 *
 * Comprehensive reference for GI conditions with bilingual support,
 * ICD-11 codes, and patient education content.
 */

export interface GIConditionEntry {
  id: string;
  name: string;
  nameEs: string;
  category: 'esophageal' | 'gastric' | 'intestinal' | 'hepatobiliary' | 'pancreatic' | 'colorectal' | 'functional';
  icd11: string;
  description: string;
  pathophysiology: string;
  symptoms: string[];
  diagnostics: string[];
  treatment: string[];
  dietaryGuidance: string[];
  complications: string[];
  patientExplanation: string;
  emergencySigns: string[];
}

export const GI_CONDITIONS: Record<string, GIConditionEntry> = {
  // ─── ESOPHAGEAL ───────────────────────────────────────────────
  gerd: {
    id: 'gi-gerd',
    name: 'Gastroesophageal Reflux Disease',
    nameEs: 'Enfermedad por Reflujo Gastroesofágico',
    category: 'esophageal',
    icd11: 'DA22',
    description: 'Chronic reflux of gastric contents into esophagus causing symptoms and/or mucosal injury.',
    pathophysiology: 'Transient lower esophageal sphincter relaxations, impaired esophageal clearance, hiatal hernia, and defective mucosal defense allow gastric acid to damage esophageal epithelium.',
    symptoms: ['Heartburn', 'Regurgitation', 'Dysphagia', 'Chronic cough', 'Laryngitis', 'Chest pain', 'Globus sensation'],
    diagnostics: ['Clinical diagnosis with PPI trial', 'Upper endoscopy (alarm symptoms)', '24-hr pH-impedance monitoring', 'Esophageal manometry'],
    treatment: ['Lifestyle modifications', 'PPI therapy (omeprazole, pantoprazole)', 'H2 blockers as step-down', 'Nissen fundoplication for refractory cases', 'LINX magnetic sphincter augmentation'],
    dietaryGuidance: ['Avoid spicy, fatty, acidic foods', 'Limit caffeine, alcohol, chocolate', 'Small frequent meals', 'No eating 3 hrs before bed', 'Elevate head of bed 6-8 inches'],
    complications: ['Erosive esophagitis', 'Esophageal stricture', 'Barrett esophagus', 'Esophageal adenocarcinoma'],
    patientExplanation: 'A valve between your stomach and food pipe does not close tightly, letting acid splash upward and cause burning. Medication and lifestyle changes usually control it well.',
    emergencySigns: ['Difficulty swallowing that worsens', 'Unintentional weight loss', 'Vomiting blood', 'Black tarry stools', 'Severe chest pain (rule out cardiac cause)'],
  },

  barretts_esophagus: {
    id: 'gi-barretts',
    name: 'Barrett Esophagus',
    nameEs: 'Esófago de Barrett',
    category: 'esophageal',
    icd11: 'DA23.0',
    description: 'Intestinal metaplasia of esophageal squamous epithelium, a premalignant complication of chronic GERD.',
    pathophysiology: 'Chronic acid exposure causes squamous-to-columnar intestinal metaplasia in the distal esophagus. Goblet cells confirm diagnosis. Dysplasia may progress to adenocarcinoma.',
    symptoms: ['Often asymptomatic', 'GERD symptoms (heartburn, regurgitation)', 'Dysphagia if stricture develops'],
    diagnostics: ['Upper endoscopy with biopsy (salmon-colored mucosa)', 'Histology showing goblet cells (intestinal metaplasia)', 'Surveillance per dysplasia grade'],
    treatment: ['Long-term PPI therapy', 'Endoscopic surveillance every 3-5 yrs (no dysplasia)', 'Radiofrequency ablation for dysplasia', 'Endoscopic mucosal resection for visible lesions', 'Esophagectomy for high-grade dysplasia/cancer'],
    dietaryGuidance: ['Follow GERD dietary guidelines', 'Maintain healthy weight', 'Increase fruits and vegetables', 'Limit processed and red meat'],
    complications: ['Low-grade dysplasia', 'High-grade dysplasia', 'Esophageal adenocarcinoma (~0.5%/yr with dysplasia)'],
    patientExplanation: 'The lining of your lower food pipe has changed due to long-term acid exposure. It needs regular monitoring with endoscopy because it can, in rare cases, turn into cancer.',
    emergencySigns: ['New or worsening dysphagia', 'Unintentional weight loss', 'GI bleeding', 'Chest pain'],
  },

  esophageal_cancer: {
    id: 'gi-esophageal-cancer',
    name: 'Esophageal Cancer',
    nameEs: 'Cáncer de Esófago',
    category: 'esophageal',
    icd11: '2B70',
    description: 'Malignancy of the esophagus, primarily squamous cell carcinoma (proximal/mid) or adenocarcinoma (distal/GEJ).',
    pathophysiology: 'SCC arises from squamous mucosa (alcohol, smoking, achalasia). Adenocarcinoma arises from Barrett metaplasia. Both invade transmurally and spread to lymph nodes early.',
    symptoms: ['Progressive dysphagia (solids then liquids)', 'Unintentional weight loss', 'Odynophagia', 'Chest pain', 'Hoarseness (recurrent laryngeal nerve)', 'Iron deficiency anemia'],
    diagnostics: ['Upper endoscopy with biopsy', 'CT chest/abdomen for staging', 'EUS for T and N staging', 'PET-CT for metastatic workup'],
    treatment: ['Endoscopic resection (T1a)', 'Neoadjuvant chemoradiation + esophagectomy', 'Definitive chemoradiation (unresectable)', 'Palliative stenting for dysphagia', 'Immunotherapy (pembrolizumab, nivolumab)'],
    dietaryGuidance: ['Soft or pureed foods if dysphagia present', 'High-calorie, high-protein diet', 'Small frequent meals', 'Nutritional supplementation', 'Enteral feeding if oral intake insufficient'],
    complications: ['Tracheoesophageal fistula', 'Aspiration pneumonia', 'SVC syndrome', 'Malnutrition', 'Metastatic disease'],
    patientExplanation: 'A tumor in your food pipe makes swallowing increasingly difficult. Treatment depends on the stage and may include surgery, chemotherapy, and radiation.',
    emergencySigns: ['Complete inability to swallow', 'Vomiting blood', 'Severe chest pain', 'Signs of aspiration (fever, cough after eating)', 'Rapid weight loss'],
  },

  achalasia: {
    id: 'gi-achalasia',
    name: 'Achalasia',
    nameEs: 'Acalasia',
    category: 'esophageal',
    icd11: 'DA21.0',
    description: 'Esophageal motility disorder with impaired LES relaxation and absent peristalsis due to loss of inhibitory neurons.',
    pathophysiology: 'Degeneration of myenteric (Auerbach) plexus neurons leads to loss of inhibitory NO/VIP signaling. The LES fails to relax, and peristalsis is absent, causing functional obstruction.',
    symptoms: ['Dysphagia to solids AND liquids simultaneously', 'Regurgitation of undigested food', 'Chest pain', 'Weight loss', 'Nocturnal cough/aspiration'],
    diagnostics: ['Barium swallow (bird-beak sign, dilated esophagus)', 'Esophageal manometry (gold standard): absent peristalsis, impaired LES relaxation', 'Upper endoscopy to rule out pseudoachalasia (GEJ tumor)'],
    treatment: ['Pneumatic dilation', 'Heller myotomy with partial fundoplication', 'Per-oral endoscopic myotomy (POEM)', 'Botulinum toxin injection (poor surgical candidates)'],
    dietaryGuidance: ['Eat slowly, chew thoroughly', 'Upright position during and after meals', 'Liquid or soft foods if dysphagia severe', 'Warm liquids may help passage', 'Avoid eating before bed'],
    complications: ['Aspiration pneumonia', 'Megaesophagus', 'Esophageal squamous cell carcinoma (long-term)', 'Malnutrition'],
    patientExplanation: 'The muscle at the bottom of your food pipe does not open properly, trapping food. Procedures can open this valve and restore your ability to eat normally.',
    emergencySigns: ['Inability to swallow liquids', 'Severe chest pain', 'Signs of aspiration pneumonia', 'Significant weight loss'],
  },

  esophageal_varices: {
    id: 'gi-esophageal-varices',
    name: 'Esophageal Varices',
    nameEs: 'Varices Esofágicas',
    category: 'esophageal',
    icd11: 'DA23.3',
    description: 'Dilated submucosal veins in the esophagus due to portal hypertension, most commonly from cirrhosis.',
    pathophysiology: 'Portal hypertension shunts blood through portosystemic collaterals. Esophageal submucosal veins dilate under increased pressure. Rupture causes life-threatening upper GI hemorrhage.',
    symptoms: ['Often asymptomatic until bleeding', 'Hematemesis (vomiting blood)', 'Melena', 'Hypovolemic shock', 'Signs of chronic liver disease'],
    diagnostics: ['Screening EGD in all cirrhotics', 'Grading: small vs large varices', 'Assess for red wale marks (high rupture risk)', 'Hepatic venous pressure gradient >10 mmHg'],
    treatment: ['Primary prophylaxis: non-selective beta-blockers (propranolol, nadolol) or endoscopic variceal ligation', 'Acute bleed: IV octreotide, emergent EGD with band ligation, balloon tamponade if uncontrolled', 'TIPS for refractory bleeding', 'Secondary prophylaxis: band ligation + beta-blocker'],
    dietaryGuidance: ['Sodium restriction (<2g/day) if ascites', 'Alcohol cessation mandatory', 'Soft diet to avoid mechanical rupture', 'Adequate protein unless encephalopathy'],
    complications: ['Variceal hemorrhage (mortality 15-20% per episode)', 'Hemorrhagic shock', 'Hepatic encephalopathy post-bleed', 'Rebleeding'],
    patientExplanation: 'Liver disease causes swollen veins in your food pipe that can burst and bleed dangerously. Medication and endoscopic procedures prevent and treat bleeding.',
    emergencySigns: ['Vomiting blood or coffee-ground material', 'Black tarry stools', 'Dizziness/fainting', 'Rapid heart rate', 'Confusion'],
  },

  mallory_weiss: {
    id: 'gi-mallory-weiss',
    name: 'Mallory-Weiss Tear',
    nameEs: 'Desgarro de Mallory-Weiss',
    category: 'esophageal',
    icd11: 'DA23.2',
    description: 'Mucosal tear at the gastroesophageal junction caused by forceful vomiting or retching.',
    pathophysiology: 'Sudden increase in intra-abdominal pressure (vomiting, retching, coughing) causes longitudinal mucosal lacerations at the GEJ. Tears involve mucosa and submucosa but not full thickness.',
    symptoms: ['Hematemesis after forceful vomiting', 'Epigastric pain', 'Melena', 'Often preceded by retching/vomiting episode'],
    diagnostics: ['Upper endoscopy (diagnostic and therapeutic)', 'CBC, coagulation studies', 'Clinical history of preceding vomiting episode'],
    treatment: ['Majority (90%) stop bleeding spontaneously', 'Endoscopic hemostasis if active bleeding', 'PPI therapy', 'Antiemetics to prevent further retching', 'Angiographic embolization or surgery if refractory'],
    dietaryGuidance: ['NPO initially if active bleeding', 'Clear liquids then advance as tolerated', 'Avoid alcohol (common precipitant)', 'Small frequent meals during recovery'],
    complications: ['Significant hemorrhage (uncommon)', 'Boerhaave syndrome (full-thickness perforation - different entity)', 'Rebleeding'],
    patientExplanation: 'Forceful vomiting caused a small tear where your food pipe meets your stomach. Most tears heal on their own within a few days.',
    emergencySigns: ['Ongoing vomiting of blood', 'Signs of shock (lightheaded, rapid pulse)', 'Severe chest/abdominal pain (concern for perforation)'],
  },

  eosinophilic_esophagitis: {
    id: 'gi-eoe',
    name: 'Eosinophilic Esophagitis',
    nameEs: 'Esofagitis Eosinofílica',
    category: 'esophageal',
    icd11: 'DA22.1',
    description: 'Chronic immune-mediated esophageal disease with eosinophilic infiltration causing dysphagia and food impaction.',
    pathophysiology: 'Th2-mediated immune response to food/environmental antigens causes eosinophilic infiltration (>=15 eos/HPF) of esophageal mucosa, leading to fibrosis, remodeling, and stricture.',
    symptoms: ['Dysphagia to solids', 'Food impaction', 'Chest pain', 'Heartburn (PPI-unresponsive)', 'Children: feeding difficulties, failure to thrive'],
    diagnostics: ['Upper endoscopy: rings (trachealization), furrows, white plaques, strictures', 'Biopsy: >=15 eosinophils/HPF', 'Allergy testing (skin prick, patch)', 'Rule out other causes of eosinophilia'],
    treatment: ['PPI trial (some respond)', 'Swallowed topical corticosteroids (fluticasone, budesonide slurry)', 'Dupilumab (FDA-approved biologic)', 'Elimination diet (6-food or targeted)', 'Endoscopic dilation for strictures'],
    dietaryGuidance: ['Six-food elimination diet (dairy, wheat, soy, eggs, nuts, seafood)', 'Step-up or step-down elimination approach', 'Elemental diet (most effective but difficult)', 'Work with allergist and dietitian', 'Reintroduce foods sequentially with repeat endoscopy'],
    complications: ['Esophageal stricture', 'Food impaction requiring emergency removal', 'Esophageal perforation (rare, usually iatrogenic)', 'Nutritional deficiency from restrictive diets'],
    patientExplanation: 'Your immune system reacts to certain foods, causing white blood cells to inflame your food pipe and make swallowing difficult. Treatment involves medication and identifying trigger foods.',
    emergencySigns: ['Complete food impaction (cannot swallow saliva)', 'Severe chest pain after food impaction', 'Signs of perforation (fever, subcutaneous crepitus)'],
  },

  esophageal_stricture: {
    id: 'gi-esophageal-stricture',
    name: 'Esophageal Stricture',
    nameEs: 'Estenosis Esofágica',
    category: 'esophageal',
    icd11: 'DA23.1',
    description: 'Narrowing of the esophageal lumen, most commonly from chronic GERD (peptic stricture), caustic injury, or radiation.',
    pathophysiology: 'Chronic inflammation or injury causes submucosal fibrosis and collagen deposition, progressively narrowing the esophageal lumen. Dysphagia occurs when lumen <13mm.',
    symptoms: ['Progressive dysphagia (solids > liquids)', 'Food impaction', 'Weight loss', 'Chest pain with eating', 'Regurgitation'],
    diagnostics: ['Barium swallow (smooth tapering in peptic; irregular in malignant)', 'Upper endoscopy with biopsy (rule out malignancy)', 'EUS if suspicious for malignant stricture'],
    treatment: ['Endoscopic bougie or balloon dilation', 'PPI therapy for peptic strictures', 'Repeat dilations as needed', 'Intralesional steroid injection for refractory strictures', 'Stenting for malignant strictures'],
    dietaryGuidance: ['Soft or pureed foods during symptomatic period', 'Chew food thoroughly', 'Take small bites with liquids', 'Avoid tough meats and bread that lodge easily', 'Advance diet after successful dilation'],
    complications: ['Perforation during dilation', 'Recurrent stricture', 'Aspiration', 'Malnutrition'],
    patientExplanation: 'Scarring has narrowed your food pipe, making it hard to swallow. A procedure can stretch it open, and medication helps prevent it from narrowing again.',
    emergencySigns: ['Complete inability to swallow', 'Severe chest pain after dilation procedure', 'Fever after dilation (possible perforation)', 'Signs of aspiration'],
  },

  // ─── GASTRIC ──────────────────────────────────────────────────
  peptic_ulcer: {
    id: 'gi-peptic-ulcer',
    name: 'Peptic Ulcer Disease',
    nameEs: 'Enfermedad Ulcerosa Péptica',
    category: 'gastric',
    icd11: 'DA43',
    description: 'Mucosal defects in the stomach or duodenum caused by H. pylori infection, NSAIDs, or acid hypersecretion.',
    pathophysiology: 'Disruption of mucosal defense (mucus, bicarbonate, prostaglandins) by H. pylori urease/cytotoxins or NSAID COX-1 inhibition allows acid-peptic digestion of mucosa, forming ulcers.',
    symptoms: ['Epigastric pain (burning, gnawing)', 'Gastric ulcer: pain worse with eating', 'Duodenal ulcer: pain relieved by eating, worse at night', 'Nausea, bloating', 'Early satiety'],
    diagnostics: ['Upper endoscopy (gold standard, biopsy for H. pylori and malignancy)', 'H. pylori testing: urea breath test, stool antigen, biopsy urease test', 'Hold PPIs 2 wks, antibiotics 4 wks before testing', 'CBC (anemia), stool guaiac'],
    treatment: ['H. pylori eradication: triple therapy (PPI + clarithromycin + amoxicillin) or bismuth quadruple', 'PPI therapy 4-8 weeks', 'Discontinue NSAIDs if possible', 'Confirm H. pylori eradication', 'Repeat endoscopy for gastric ulcers to exclude malignancy'],
    dietaryGuidance: ['Avoid NSAIDs, alcohol, smoking', 'No evidence for bland diet but avoid personal trigger foods', 'Regular meal schedule', 'Limit caffeine', 'Probiotics may support eradication therapy'],
    complications: ['GI bleeding (most common)', 'Perforation (acute abdomen)', 'Gastric outlet obstruction', 'Penetration into adjacent organs'],
    patientExplanation: 'You have a sore (ulcer) in the lining of your stomach or upper intestine, often caused by a bacteria called H. pylori or pain medications. Antibiotics and acid-reducing medicine can heal it.',
    emergencySigns: ['Vomiting blood or coffee-ground emesis', 'Black tarry stools', 'Sudden severe abdominal pain (perforation)', 'Dizziness/fainting from blood loss', 'Persistent vomiting (outlet obstruction)'],
  },

  h_pylori_gastritis: {
    id: 'gi-h-pylori',
    name: 'Helicobacter pylori Gastritis',
    nameEs: 'Gastritis por Helicobacter pylori',
    category: 'gastric',
    icd11: 'DA42.0',
    description: 'Chronic gastric inflammation caused by H. pylori colonization, the most common cause of gastritis worldwide.',
    pathophysiology: 'H. pylori colonizes gastric epithelium using urease to buffer acid. It induces chronic inflammation via CagA/VacA virulence factors, causing mucosal damage, altered acid secretion, and increased cancer risk.',
    symptoms: ['Often asymptomatic', 'Dyspepsia', 'Epigastric discomfort', 'Nausea', 'Bloating', 'May present with complications (ulcer, cancer)'],
    diagnostics: ['Non-invasive: urea breath test (preferred), stool antigen', 'Invasive: endoscopic biopsy with rapid urease test, histology, culture', 'Serology (IgG) only for epidemiologic studies (remains positive after eradication)'],
    treatment: ['First-line: PPI + clarithromycin + amoxicillin x 14 days', 'Bismuth quadruple therapy (PPI + bismuth + metronidazole + tetracycline)', 'Confirm eradication 4 weeks after treatment completion', 'Rifabutin or levofloxacin-based salvage regimens'],
    dietaryGuidance: ['No specific diet required', 'Probiotics (Lactobacillus, Saccharomyces boulardii) may improve eradication and reduce side effects', 'Avoid alcohol during treatment', 'Broccoli sprouts (sulforaphane) may have adjunctive benefit'],
    complications: ['Peptic ulcer disease', 'Gastric adenocarcinoma', 'MALT lymphoma', 'Iron deficiency anemia', 'Vitamin B12 deficiency'],
    patientExplanation: 'A common stomach bacteria called H. pylori is causing inflammation. A course of antibiotics and acid medication will clear the infection and let your stomach heal.',
    emergencySigns: ['Vomiting blood', 'Severe abdominal pain', 'Unexplained weight loss', 'Persistent vomiting'],
  },

  gastric_cancer: {
    id: 'gi-gastric-cancer',
    name: 'Gastric Cancer',
    nameEs: 'Cáncer Gástrico',
    category: 'gastric',
    icd11: '2B72',
    description: 'Malignant neoplasm of the stomach, predominantly intestinal-type or diffuse-type adenocarcinoma.',
    pathophysiology: 'Intestinal type follows Correa cascade: chronic gastritis -> atrophy -> intestinal metaplasia -> dysplasia -> carcinoma (H. pylori driven). Diffuse type involves CDH1 (E-cadherin) loss with signet ring cells.',
    symptoms: ['Early: often asymptomatic or vague dyspepsia', 'Weight loss', 'Abdominal pain', 'Nausea/vomiting', 'Early satiety', 'Dysphagia (proximal tumors)', 'GI bleeding'],
    diagnostics: ['Upper endoscopy with multiple biopsies', 'CT chest/abdomen/pelvis for staging', 'EUS for T/N staging', 'PET-CT', 'HER2 testing', 'Staging laparoscopy'],
    treatment: ['Endoscopic resection for early T1a', 'Gastrectomy (subtotal or total) with D2 lymphadenectomy', 'Perioperative chemo (FLOT regimen)', 'Trastuzumab for HER2+ disease', 'Immunotherapy (nivolumab) for advanced disease'],
    dietaryGuidance: ['Post-gastrectomy: small frequent meals', 'Avoid dumping syndrome triggers (high sugar)', 'Iron, B12, calcium, vitamin D supplementation', 'High-protein diet for healing', 'Limit salt-preserved and smoked foods (prevention)'],
    complications: ['Gastric outlet obstruction', 'GI bleeding', 'Peritoneal carcinomatosis (Krukenberg tumor)', 'Dumping syndrome post-surgery', 'Nutritional deficiencies'],
    patientExplanation: 'A tumor has been found in your stomach. Treatment usually involves surgery to remove the affected area, often combined with chemotherapy to improve outcomes.',
    emergencySigns: ['Vomiting blood', 'Severe abdominal pain', 'Inability to eat or drink', 'Signs of obstruction (persistent vomiting)', 'Rapid weight loss'],
  },

  gastroparesis: {
    id: 'gi-gastroparesis',
    name: 'Gastroparesis',
    nameEs: 'Gastroparesia',
    category: 'gastric',
    icd11: 'DA44',
    description: 'Delayed gastric emptying without mechanical obstruction, most commonly idiopathic, diabetic, or postsurgical.',
    pathophysiology: 'Loss or dysfunction of interstitial cells of Cajal (gastric pacemaker cells), autonomic neuropathy (diabetic), or vagal nerve injury impairs gastric motility and emptying.',
    symptoms: ['Nausea (predominant symptom)', 'Vomiting (often undigested food hours after eating)', 'Early satiety', 'Postprandial fullness', 'Bloating', 'Abdominal pain', 'Weight loss'],
    diagnostics: ['Gastric emptying scintigraphy (gold standard): >10% retention at 4 hrs', 'Upper endoscopy to exclude obstruction', 'Wireless motility capsule', 'HbA1c and glucose control assessment'],
    treatment: ['Dietary modification (first-line)', 'Metoclopramide (prokinetic, FDA black box)', 'Domperidone (not FDA-approved, access programs)', 'Antiemetics (ondansetron, prochlorperazine)', 'Gastric electrical stimulation (Enterra) for refractory nausea/vomiting', 'Pyloric interventions (G-POEM)'],
    dietaryGuidance: ['Small, frequent meals (4-6/day)', 'Low-fat, low-fiber diet', 'Well-cooked soft foods preferred', 'Liquid calories if solids not tolerated', 'Avoid carbonated beverages', 'Stay upright 1-2 hrs after eating', 'Chew food thoroughly'],
    complications: ['Malnutrition and weight loss', 'Bezoar formation', 'Poor glycemic control in diabetics', 'Aspiration', 'Reduced quality of life'],
    patientExplanation: 'Your stomach empties food too slowly, causing nausea and vomiting. Eating smaller meals with easy-to-digest foods and certain medications can help your stomach work better.',
    emergencySigns: ['Inability to keep any food or liquids down', 'Signs of dehydration', 'Severe abdominal pain', 'Bezoar causing obstruction', 'Uncontrolled blood sugar in diabetics'],
  },

  zollinger_ellison: {
    id: 'gi-zollinger-ellison',
    name: 'Zollinger-Ellison Syndrome',
    nameEs: 'Síndrome de Zollinger-Ellison',
    category: 'gastric',
    icd11: '5A41',
    description: 'Gastrin-secreting tumor (gastrinoma) causing severe peptic ulcer disease and diarrhea from gastric acid hypersecretion.',
    pathophysiology: 'Gastrinomas (usually duodenal or pancreatic) secrete excessive gastrin, driving parietal cell hyperplasia and massive HCl production. ~25% occur in MEN1 syndrome.',
    symptoms: ['Severe/refractory peptic ulcers', 'Diarrhea (due to acid inactivating pancreatic enzymes)', 'Epigastric pain', 'GERD symptoms', 'Steatorrhea', 'Weight loss'],
    diagnostics: ['Fasting serum gastrin >1000 pg/mL (diagnostic)', 'Secretin stimulation test (paradoxical gastrin rise)', 'Gastric pH <2 with elevated gastrin', 'CT/MRI for tumor localization', 'Somatostatin receptor scintigraphy (OctreoScan)', 'EUS for small tumors'],
    treatment: ['High-dose PPI for acid control', 'Surgical resection of gastrinoma (curative if localized)', 'Somatostatin analogs (octreotide) for metastatic disease', 'MEN1 screening if indicated', 'Chemotherapy for metastatic (streptozocin, 5-FU, everolimus)'],
    dietaryGuidance: ['PPI must be taken before meals', 'Avoid irritant foods while ulcers heal', 'Regular balanced diet once acid controlled', 'Monitor for nutritional deficiencies'],
    complications: ['GI bleeding', 'Peptic ulcer perforation', 'Metastatic gastrinoma (60% malignant)', 'MEN1-associated tumors (parathyroid, pituitary)'],
    patientExplanation: 'A small tumor is producing too much of a hormone called gastrin, which tells your stomach to make excess acid. This causes severe ulcers. Medication controls the acid while we locate and treat the tumor.',
    emergencySigns: ['GI bleeding signs', 'Severe abdominal pain (perforation)', 'Signs of MEN1 (hypercalcemia symptoms)', 'Intractable diarrhea with dehydration'],
  },

  // ─── INTESTINAL ───────────────────────────────────────────────
  celiac_disease: {
    id: 'gi-celiac',
    name: 'Celiac Disease',
    nameEs: 'Enfermedad Celíaca',
    category: 'intestinal',
    icd11: 'DA95.0',
    description: 'Autoimmune enteropathy triggered by gluten ingestion in genetically susceptible individuals (HLA-DQ2/DQ8).',
    pathophysiology: 'Gluten-derived gliadin peptides are deamidated by tissue transglutaminase, presented on HLA-DQ2/DQ8, triggering T-cell-mediated destruction of small intestinal villi (villous atrophy).',
    symptoms: ['Chronic diarrhea', 'Bloating, flatulence', 'Weight loss', 'Iron deficiency anemia', 'Fatigue', 'Dermatitis herpetiformis', 'Osteoporosis', 'Peripheral neuropathy'],
    diagnostics: ['Serology: tissue transglutaminase IgA (tTG-IgA) - first-line', 'Total IgA level (rule out IgA deficiency)', 'Endomysial antibodies (confirmatory)', 'Duodenal biopsy: villous atrophy, crypt hyperplasia, intraepithelial lymphocytosis', 'HLA-DQ2/DQ8 (high negative predictive value)'],
    treatment: ['Strict lifelong gluten-free diet (cornerstone)', 'Dietitian counseling', 'Monitor tTG-IgA for adherence', 'Correct nutritional deficiencies (iron, folate, B12, calcium, vitamin D)', 'Dapsone for dermatitis herpetiformis', 'Repeat biopsy to confirm mucosal healing'],
    dietaryGuidance: ['Eliminate all wheat, barley, rye, and their derivatives', 'Oats are usually safe (ensure gluten-free certified)', 'Read all food labels carefully', 'Beware of cross-contamination', 'Safe grains: rice, corn, quinoa, millet, buckwheat', 'Many processed foods contain hidden gluten', 'Restaurant awareness and communication'],
    complications: ['Refractory celiac disease', 'Enteropathy-associated T-cell lymphoma (EATL)', 'Small bowel adenocarcinoma', 'Osteoporosis', 'Infertility', 'Hyposplenism'],
    patientExplanation: 'Your immune system reacts to gluten, a protein in wheat, barley, and rye, damaging your small intestine and blocking nutrient absorption. A gluten-free diet heals the damage completely.',
    emergencySigns: ['Severe malnutrition or dehydration', 'Worsening symptoms despite strict gluten-free diet (refractory)', 'New abdominal mass or obstruction (lymphoma)', 'Severe anemia'],
  },

  crohn_disease: {
    id: 'gi-crohn',
    name: 'Crohn Disease',
    nameEs: 'Enfermedad de Crohn',
    category: 'intestinal',
    icd11: 'DD70',
    description: 'Chronic transmural inflammatory bowel disease that can affect any part of the GI tract (mouth to anus), with skip lesions.',
    pathophysiology: 'Dysregulated mucosal immune response to intestinal microbiota in genetically susceptible hosts (NOD2/CARD15). Transmural inflammation causes granulomas, fistulae, and strictures.',
    symptoms: ['Chronic diarrhea (often non-bloody)', 'Abdominal pain (especially RLQ)', 'Weight loss', 'Fatigue', 'Perianal disease (fistulae, abscesses)', 'Mouth ulcers', 'Extraintestinal: arthritis, uveitis, erythema nodosum'],
    diagnostics: ['Colonoscopy with ileal intubation and biopsies (cobblestoning, skip lesions, granulomas)', 'MR enterography (small bowel involvement, strictures, fistulae)', 'CT enterography for acute presentations', 'Labs: CRP, ESR, fecal calprotectin', 'Capsule endoscopy for small bowel evaluation'],
    treatment: ['Induction: corticosteroids, exclusive enteral nutrition (pediatric)', 'Maintenance: thiopurines (azathioprine), methotrexate', 'Biologics: anti-TNF (infliximab, adalimumab), vedolizumab, ustekinumab, risankizumab', 'Small molecules: upadacitinib', 'Surgery for complications (strictureplasty, resection)', 'Perianal disease: seton placement, anti-TNF, exam under anesthesia'],
    dietaryGuidance: ['No universal diet; individualize', 'Exclusive enteral nutrition effective for induction (esp. pediatric)', 'Mediterranean-style diet may be beneficial', 'Low-residue diet during flares/strictures', 'Identify and avoid personal trigger foods', 'Nutritional supplementation (iron, B12, folate, vitamin D)'],
    complications: ['Strictures with bowel obstruction', 'Fistulae (enteroenteric, enterocutaneous, perianal)', 'Abscess formation', 'Colorectal cancer (long-standing colitis)', 'Short bowel syndrome post-surgery', 'Malnutrition'],
    patientExplanation: 'Crohn disease causes ongoing inflammation in your digestive tract, leading to pain, diarrhea, and sometimes complications. Modern medications can control inflammation and help you feel well.',
    emergencySigns: ['Signs of bowel obstruction (vomiting, distention, no bowel movements)', 'High fever with abdominal pain (abscess)', 'Severe perianal pain/swelling', 'Significant rectal bleeding', 'Signs of perforation'],
  },

  ulcerative_colitis: {
    id: 'gi-ulcerative-colitis',
    name: 'Ulcerative Colitis',
    nameEs: 'Colitis Ulcerosa',
    category: 'intestinal',
    icd11: 'DD71',
    description: 'Chronic inflammatory bowel disease limited to the colonic mucosa, extending continuously from the rectum proximally.',
    pathophysiology: 'Dysregulated mucosal immunity causes superficial (mucosal/submucosal) inflammation. Always involves the rectum with continuous proximal extension. No skip lesions or transmural involvement.',
    symptoms: ['Bloody diarrhea (hallmark)', 'Urgency and tenesmus', 'Abdominal cramping', 'Rectal pain', 'Mucus in stool', 'Extraintestinal: arthritis, pyoderma gangrenosum, primary sclerosing cholangitis'],
    diagnostics: ['Colonoscopy with biopsies: continuous inflammation from rectum, loss of haustra, pseudopolyps', 'Histology: crypt abscesses, mucosal inflammation', 'Labs: CRP, ESR, fecal calprotectin, p-ANCA (supportive)', 'Stool studies to exclude infection (especially C. diff)'],
    treatment: ['Mild-moderate: 5-ASA (mesalamine) oral and rectal', 'Moderate-severe: corticosteroids for induction', 'Maintenance: 5-ASA, thiopurines, biologics (infliximab, adalimumab, vedolizumab, ustekinumab)', 'Small molecules: tofacitinib, ozanimod', 'Proctocolectomy with ileal pouch-anal anastomosis (curative)', 'Acute severe UC: IV steroids, rescue therapy (infliximab or cyclosporine)'],
    dietaryGuidance: ['Low-residue diet during flares', 'Adequate hydration', 'Calcium and vitamin D supplementation', 'Probiotics (VSL#3) may have modest benefit in mild UC', 'Avoid foods that worsen symptoms individually', 'Mediterranean-type diet in remission'],
    complications: ['Toxic megacolon', 'Perforation', 'Colorectal cancer (risk increases after 8-10 yrs)', 'Strictures', 'Iron deficiency anemia', 'Primary sclerosing cholangitis'],
    patientExplanation: 'Your large intestine is chronically inflamed, causing bloody diarrhea and urgency. Medications can calm inflammation and keep you in remission; surgery is curative if needed.',
    emergencySigns: ['More than 6 bloody stools/day with fever or tachycardia (acute severe UC)', 'Abdominal distension (toxic megacolon)', 'Severe abdominal pain (perforation)', 'Profuse bleeding', 'Signs of sepsis'],
  },

  small_bowel_obstruction: {
    id: 'gi-sbo',
    name: 'Small Bowel Obstruction',
    nameEs: 'Obstrucción de Intestino Delgado',
    category: 'intestinal',
    icd11: 'DB30',
    description: 'Mechanical blockage of the small intestine, most commonly caused by adhesions, hernias, or tumors.',
    pathophysiology: 'Mechanical obstruction causes proximal bowel dilation, fluid/gas accumulation, increased intraluminal pressure, mucosal edema, and if unrelieved, ischemia and perforation.',
    symptoms: ['Colicky abdominal pain', 'Nausea and vomiting (bilious)', 'Abdominal distension', 'Obstipation (complete obstruction)', 'High-pitched bowel sounds early, absent later'],
    diagnostics: ['Abdominal X-ray: dilated small bowel, air-fluid levels, absence of colonic gas', 'CT abdomen with IV contrast (preferred): transition point, strangulation signs', 'Labs: BMP (electrolytes), lactate, CBC (leukocytosis)'],
    treatment: ['NPO, NG tube decompression, IV fluids, electrolyte correction', 'Partial/adhesive SBO: trial of conservative management 48-72 hrs', 'Water-soluble contrast (Gastrografin) challenge for adhesive SBO', 'Surgery: strangulation signs, complete obstruction, hernia, failure of conservative management'],
    dietaryGuidance: ['NPO during acute obstruction', 'Clear liquids first when resolving', 'Low-residue diet initially after resolution', 'Small frequent meals', 'Chew food well; avoid large chunks of fibrous foods', 'Gradual return to normal diet'],
    complications: ['Strangulation with bowel necrosis', 'Perforation and peritonitis', 'Sepsis', 'Electrolyte derangements', 'Aspiration', 'Recurrent obstruction'],
    patientExplanation: 'Something is blocking your small intestine, preventing food and fluids from passing through. We will rest your bowel and give IV fluids; surgery may be needed if it does not open up.',
    emergencySigns: ['Fever with peritoneal signs (rigid abdomen)', 'Worsening pain becoming constant (strangulation)', 'Hemodynamic instability', 'Lactic acidosis', 'Failure to improve with conservative management'],
  },

  intussusception: {
    id: 'gi-intussusception',
    name: 'Intussusception',
    nameEs: 'Intususcepción',
    category: 'intestinal',
    icd11: 'DB31',
    description: 'Telescoping of a proximal bowel segment into a distal segment, most common in children (ileocolic) and adults (lead point tumors).',
    pathophysiology: 'A lead point (Peyer patch hypertrophy in children, polyp/tumor in adults) causes the proximal segment to invaginate into the distal segment, pulling mesentery with it and causing venous congestion, edema, ischemia.',
    symptoms: ['Children: intermittent colicky pain, drawing up legs, currant-jelly stool, palpable sausage-shaped mass', 'Adults: intermittent abdominal pain, nausea, obstructive symptoms', 'Lethargy (children)', 'Bloody stool'],
    diagnostics: ['Ultrasound: target sign/donut sign (pediatric first-line)', 'CT abdomen: target sign, bowel-within-bowel (adult)', 'Air or barium enema (diagnostic and therapeutic in children)'],
    treatment: ['Pediatric: air or hydrostatic enema reduction', 'Surgical reduction if enema fails or peritonitis present', 'Adult: surgical resection (high rate of pathologic lead point)', 'Evaluate for underlying lead point'],
    dietaryGuidance: ['NPO during acute episode', 'Clear liquids then advance post-reduction', 'Resume normal age-appropriate diet once resolved', 'Monitor for recurrence'],
    complications: ['Bowel necrosis', 'Perforation', 'Recurrence (5-10% in children)', 'Missed lead point pathology in adults'],
    patientExplanation: 'Part of the intestine has folded into itself like a telescope, blocking the flow. In children, a special procedure can usually push it back; adults may need surgery.',
    emergencySigns: ['Signs of perforation (rigid abdomen, fever)', 'Shock', 'Failed enema reduction', 'Recurrent episodes (evaluate for lead point)'],
  },

  mesenteric_ischemia: {
    id: 'gi-mesenteric-ischemia',
    name: 'Mesenteric Ischemia',
    nameEs: 'Isquemia Mesentérica',
    category: 'intestinal',
    icd11: 'DB90',
    description: 'Inadequate blood flow to the intestine causing ischemia, either acute (embolic/thrombotic) or chronic (mesenteric angina).',
    pathophysiology: 'Acute: SMA embolism (50%, often from AFib), SMA thrombosis, NOMI (low-flow states), or mesenteric venous thrombosis. Chronic: atherosclerotic narrowing of >=2 mesenteric arteries.',
    symptoms: ['Acute: sudden severe periumbilical pain out of proportion to exam', 'Nausea, vomiting, diarrhea (may be bloody)', 'Chronic: postprandial pain (intestinal angina), food fear, weight loss', 'Late: peritonitis, sepsis'],
    diagnostics: ['CT angiography (first-line for acute)', 'Serum lactate (elevated = late finding)', 'Mesenteric angiography (gold standard, allows intervention)', 'D-dimer, leukocytosis, metabolic acidosis', 'Duplex ultrasound for chronic disease'],
    treatment: ['Acute: emergent revascularization (embolectomy, thrombectomy, bypass)', 'IV heparin anticoagulation', 'Resection of nonviable bowel', 'NOMI: vasodilators (papaverine), treat underlying cause', 'Chronic: mesenteric stenting or surgical bypass', 'Second-look laparotomy at 24-48 hrs'],
    dietaryGuidance: ['NPO during acute episode', 'Chronic: small frequent meals to reduce postprandial demand', 'Low-fat diet may help chronic symptoms', 'Adequate hydration', 'Gradually increase intake after revascularization'],
    complications: ['Bowel infarction and necrosis', 'Sepsis and multiorgan failure', 'Short bowel syndrome', 'Mortality 60-80% if diagnosis delayed'],
    patientExplanation: 'Blood flow to your intestine is blocked, causing severe pain and potential damage. This is an emergency that requires rapid treatment to restore blood flow and save the bowel.',
    emergencySigns: ['Severe abdominal pain out of proportion to physical findings', 'Bloody stool with abdominal pain', 'Signs of shock', 'Peritoneal signs', 'Lactic acidosis'],
  },

  carcinoid_tumor: {
    id: 'gi-carcinoid',
    name: 'Carcinoid Tumor (GI Neuroendocrine Tumor)',
    nameEs: 'Tumor Carcinoide (Tumor Neuroendocrino GI)',
    category: 'intestinal',
    icd11: '2B80',
    description: 'Slow-growing neuroendocrine tumors arising from enterochromaffin cells, most commonly in the small intestine and appendix.',
    pathophysiology: 'Enterochromaffin cell neoplasm secreting serotonin (5-HT) and other vasoactive substances. Carcinoid syndrome occurs when secreted products bypass hepatic metabolism (liver metastases or extra-portal drainage).',
    symptoms: ['Often asymptomatic (found incidentally)', 'Carcinoid syndrome (10%): episodic flushing, diarrhea, wheezing, right-sided heart disease', 'Abdominal pain', 'Bowel obstruction', 'GI bleeding'],
    diagnostics: ['24-hr urine 5-HIAA (serotonin metabolite)', 'Serum chromogranin A', 'CT/MRI for localization', 'Somatostatin receptor scintigraphy (OctreoScan) or Ga-68 DOTATATE PET', 'Echocardiogram (carcinoid heart disease)'],
    treatment: ['Surgical resection (curative if localized)', 'Somatostatin analogs (octreotide LAR) for carcinoid syndrome', 'Peptide receptor radionuclide therapy (PRRT) with Lu-177 DOTATATE', 'Everolimus for progressive disease', 'Hepatic-directed therapy for liver metastases'],
    dietaryGuidance: ['Avoid tyramine-rich foods if on certain medications', 'Niacin supplementation (tryptophan diverted to serotonin)', 'Balanced protein intake', 'Avoid alcohol (may trigger flushing)'],
    complications: ['Carcinoid heart disease (tricuspid regurgitation, pulmonary stenosis)', 'Carcinoid crisis (massive hormone release, hemodynamic collapse)', 'Bowel obstruction from desmoplastic reaction', 'Mesenteric fibrosis', 'Niacin deficiency (pellagra)'],
    patientExplanation: 'You have a slow-growing tumor that produces hormones. These can cause flushing and diarrhea. Treatment with medication controls symptoms, and surgery can often remove the tumor.',
    emergencySigns: ['Carcinoid crisis (severe flushing, hypotension, bronchospasm)', 'Signs of bowel obstruction', 'Heart failure symptoms (carcinoid heart disease)', 'Severe diarrhea with dehydration'],
  },

  // ─── HEPATOBILIARY ────────────────────────────────────────────
  autoimmune_hepatitis: {
    id: 'gi-autoimmune-hepatitis',
    name: 'Autoimmune Hepatitis',
    nameEs: 'Hepatitis Autoinmune',
    category: 'hepatobiliary',
    icd11: 'DB96.0',
    description: 'Chronic liver inflammation caused by immune-mediated attack on hepatocytes, predominantly affecting women.',
    pathophysiology: 'Loss of immune tolerance to hepatocyte antigens causes T-cell-mediated destruction. Type 1 (ANA, ASMA) most common in adults; Type 2 (anti-LKM1) more common in children.',
    symptoms: ['Fatigue', 'Jaundice', 'Abdominal discomfort', 'Arthralgias', 'May present acutely as fulminant hepatitis', 'Amenorrhea', 'Skin rashes', 'Often associated with other autoimmune conditions'],
    diagnostics: ['Elevated aminotransferases (often >10x ULN)', 'Elevated IgG', 'Autoantibodies: ANA, ASMA (Type 1), anti-LKM1 (Type 2)', 'Liver biopsy: interface hepatitis, plasma cell infiltration', 'Simplified diagnostic scoring system'],
    treatment: ['Prednisone + azathioprine (standard induction)', 'Budesonide + azathioprine (alternative, fewer steroid side effects)', 'Azathioprine or mycophenolate maintenance', 'Second-line: tacrolimus, cyclosporine, rituximab', 'Liver transplant for decompensated cirrhosis or fulminant disease'],
    dietaryGuidance: ['Balanced diet adequate in calcium and vitamin D (steroid use)', 'Avoid alcohol', 'Moderate protein intake', 'Monitor for steroid-related weight gain', 'Osteoporosis prevention diet'],
    complications: ['Cirrhosis', 'Hepatocellular carcinoma', 'Steroid side effects (osteoporosis, diabetes, weight gain)', 'Drug-induced cytopenias (azathioprine)', 'Fulminant hepatic failure'],
    patientExplanation: 'Your immune system is mistakenly attacking your liver. Medications that calm the immune system can stop the damage and prevent scarring.',
    emergencySigns: ['Severe jaundice with confusion (acute liver failure)', 'Signs of decompensated cirrhosis (ascites, variceal bleed)', 'Severe abdominal pain', 'Coagulopathy with bleeding'],
  },

  cirrhosis: {
    id: 'gi-cirrhosis',
    name: 'Cirrhosis',
    nameEs: 'Cirrosis Hepática',
    category: 'hepatobiliary',
    icd11: 'DB93.1',
    description: 'End-stage chronic liver disease with diffuse fibrosis, regenerative nodules, and architectural distortion.',
    pathophysiology: 'Chronic hepatocyte injury (alcohol, viral, metabolic) activates hepatic stellate cells, producing excess collagen. Progressive fibrosis replaces functional parenchyma, causing portal hypertension and synthetic failure.',
    symptoms: ['Early (compensated): fatigue, weakness, anorexia', 'Jaundice', 'Spider angiomata, palmar erythema', 'Ascites', 'Hepatic encephalopathy (confusion)', 'Gynecomastia', 'Splenomegaly', 'Caput medusae'],
    diagnostics: ['Liver biopsy (gold standard)', 'FibroScan (transient elastography)', 'FIB-4, APRI scores', 'Labs: elevated bilirubin, low albumin, elevated INR, thrombocytopenia', 'Imaging: nodular liver, splenomegaly, ascites', 'Child-Pugh and MELD scores for severity'],
    treatment: ['Treat underlying cause (alcohol cessation, antivirals, etc.)', 'Manage complications: diuretics for ascites, lactulose for encephalopathy', 'Variceal screening and prophylaxis', 'HCC surveillance (ultrasound +/- AFP every 6 months)', 'Liver transplant evaluation for decompensated disease', 'Avoid hepatotoxic medications'],
    dietaryGuidance: ['Sodium restriction <2g/day if ascites', 'Adequate protein (1.2-1.5 g/kg/day) despite encephalopathy (BCAA supplements if needed)', 'Late evening snack to prevent catabolism', 'Alcohol cessation (absolute)', 'Multivitamin supplementation', 'Small frequent meals'],
    complications: ['Portal hypertension', 'Ascites and spontaneous bacterial peritonitis', 'Variceal hemorrhage', 'Hepatic encephalopathy', 'Hepatorenal syndrome', 'Hepatocellular carcinoma', 'Coagulopathy'],
    patientExplanation: 'Your liver has been scarred by chronic injury and cannot function as well as it should. We focus on treating the cause, managing complications, and protecting the remaining liver function.',
    emergencySigns: ['Vomiting blood (variceal bleed)', 'Confusion or altered mental status (encephalopathy)', 'Fever with ascites (SBP)', 'Rapid abdominal swelling', 'Decreased urine output (hepatorenal syndrome)'],
  },

  nafld_nash: {
    id: 'gi-nafld-nash',
    name: 'Non-Alcoholic Fatty Liver Disease / NASH',
    nameEs: 'Enfermedad de Hígado Graso No Alcohólico / EHNA',
    category: 'hepatobiliary',
    icd11: 'DB92.0',
    description: 'Spectrum from hepatic steatosis (NAFLD) to steatohepatitis with inflammation and fibrosis (NASH), now also termed MASLD/MASH.',
    pathophysiology: 'Insulin resistance drives hepatic lipid accumulation (first hit). Oxidative stress, lipotoxicity, and inflammation cause hepatocyte injury and fibrosis (second hit/multiple parallel hits model).',
    symptoms: ['Usually asymptomatic', 'Fatigue', 'Vague RUQ discomfort', 'Hepatomegaly', 'Acanthosis nigricans (insulin resistance)', 'May present with complications of cirrhosis'],
    diagnostics: ['Elevated ALT (may be normal in advanced disease)', 'Ultrasound: hepatic steatosis', 'FibroScan or MR elastography for fibrosis staging', 'FIB-4 score for risk stratification', 'Liver biopsy (gold standard for NASH diagnosis)', 'Rule out alcohol, viral, autoimmune causes'],
    treatment: ['Weight loss 7-10% (most effective intervention)', 'Exercise (150 min/week moderate intensity)', 'Pioglitazone (NASH with or without diabetes)', 'Vitamin E 800 IU/day (non-diabetic NASH)', 'Resmetirom (FDA-approved thyroid hormone receptor agonist for NASH with fibrosis)', 'GLP-1 receptor agonists (semaglutide)', 'Bariatric surgery for obesity-associated NASH'],
    dietaryGuidance: ['Mediterranean diet (strongest evidence)', 'Reduce saturated fats and refined carbohydrates', 'Eliminate sugar-sweetened beverages', 'Increase omega-3 fatty acids (fish, walnuts)', 'Coffee consumption may be protective', 'Avoid fructose-heavy processed foods', 'Caloric deficit for weight loss'],
    complications: ['Progression to cirrhosis', 'Hepatocellular carcinoma (can occur without cirrhosis)', 'Cardiovascular disease (leading cause of death)', 'Type 2 diabetes'],
    patientExplanation: 'Fat has built up in your liver, which can cause inflammation and scarring over time. Losing weight through diet and exercise is the most effective treatment and can reverse early damage.',
    emergencySigns: ['Signs of liver failure (jaundice, confusion, bleeding)', 'Rapid weight loss or gain', 'New ascites', 'Upper GI bleeding'],
  },

  cholelithiasis: {
    id: 'gi-cholelithiasis',
    name: 'Cholelithiasis (Gallstones)',
    nameEs: 'Colelitiasis (Cálculos Biliares)',
    category: 'hepatobiliary',
    icd11: 'DC11',
    description: 'Formation of calculi in the gallbladder; cholesterol stones (80%) or pigment stones (20%).',
    pathophysiology: 'Cholesterol stones: supersaturation of bile with cholesterol, gallbladder hypomotility, accelerated nucleation. Pigment stones: excess unconjugated bilirubin (hemolysis, cirrhosis, biliary infections).',
    symptoms: ['Often asymptomatic (80%)', 'Biliary colic: episodic RUQ pain after fatty meals, lasting 30 min-6 hrs', 'Nausea, vomiting', 'Pain radiating to right shoulder or back'],
    diagnostics: ['RUQ ultrasound (first-line, >95% sensitivity)', 'Labs usually normal (unless complication)', 'HIDA scan if ultrasound equivocal and clinical suspicion high'],
    treatment: ['Asymptomatic: observation', 'Symptomatic: laparoscopic cholecystectomy (definitive)', 'Ursodiol (poor surgical candidates, small cholesterol stones)', 'Low-fat diet to reduce symptoms while awaiting surgery'],
    dietaryGuidance: ['Low-fat diet to reduce biliary colic episodes', 'Avoid rapid weight loss (increases stone formation)', 'Gradual weight loss if overweight', 'Increase fiber intake', 'Adequate hydration', 'Post-cholecystectomy: may need to limit fat initially then gradual increase'],
    complications: ['Acute cholecystitis', 'Choledocholithiasis (CBD stones)', 'Cholangitis', 'Gallstone pancreatitis', 'Gallstone ileus', 'Gallbladder cancer (rare, porcelain gallbladder)'],
    patientExplanation: 'You have stones in your gallbladder. If they cause pain after fatty meals, the best treatment is surgery to remove the gallbladder, which you can live well without.',
    emergencySigns: ['Persistent pain >6 hrs with fever (cholecystitis)', 'Jaundice with fever and RUQ pain (cholangitis)', 'Severe epigastric pain radiating to back (pancreatitis)', 'Signs of sepsis'],
  },

  cholecystitis: {
    id: 'gi-cholecystitis',
    name: 'Acute Cholecystitis',
    nameEs: 'Colecistitis Aguda',
    category: 'hepatobiliary',
    icd11: 'DC12',
    description: 'Inflammation of the gallbladder, usually from cystic duct obstruction by a gallstone.',
    pathophysiology: 'Gallstone impaction in cystic duct causes bile stasis, gallbladder distension, mucosal inflammation, and secondary bacterial infection. Acalculous cholecystitis (5-10%) occurs in critically ill patients.',
    symptoms: ['Persistent RUQ pain (>6 hrs, distinguishing from biliary colic)', 'Fever', 'Nausea, vomiting', 'Murphy sign (arrest of inspiration during RUQ palpation)', 'Guarding'],
    diagnostics: ['RUQ ultrasound: gallstones, wall thickening >4mm, pericholecystic fluid, sonographic Murphy sign', 'Labs: leukocytosis, mildly elevated LFTs', 'HIDA scan (if ultrasound equivocal): non-filling of gallbladder'],
    treatment: ['NPO, IV fluids, IV antibiotics', 'Early laparoscopic cholecystectomy (within 72 hrs preferred)', 'Percutaneous cholecystostomy (high surgical risk)', 'IV antibiotics: piperacillin-tazobactam or ceftriaxone + metronidazole'],
    dietaryGuidance: ['NPO during acute episode', 'Clear liquid diet when improving', 'Low-fat diet before surgery', 'Post-cholecystectomy: gradual reintroduction of fats', 'Most patients resume normal diet within weeks of surgery'],
    complications: ['Gangrenous cholecystitis', 'Gallbladder perforation', 'Emphysematous cholecystitis', 'Cholecystoenteric fistula', 'Mirizzi syndrome', 'Sepsis'],
    patientExplanation: 'A gallstone is stuck in your gallbladder, causing pain, inflammation, and infection. You need antibiotics and surgery to remove the gallbladder.',
    emergencySigns: ['High fever with rigors', 'Worsening abdominal pain with peritoneal signs', 'Signs of sepsis (tachycardia, hypotension)', 'Jaundice (suggests CBD involvement)'],
  },

  cholangitis: {
    id: 'gi-cholangitis',
    name: 'Acute Cholangitis',
    nameEs: 'Colangitis Aguda',
    category: 'hepatobiliary',
    icd11: 'DC15',
    description: 'Bacterial infection of the biliary system due to obstruction, most commonly from choledocholithiasis.',
    pathophysiology: 'Biliary obstruction (CBD stone, stricture, tumor) causes bile stasis and bacterial proliferation. Increased biliary pressure forces bacteria into bloodstream, causing bacteremia and sepsis.',
    symptoms: ['Charcot triad: RUQ pain, fever, jaundice (50-70%)', 'Reynolds pentad: adds altered mental status and hypotension (severe/suppurative)', 'Rigors', 'Nausea, vomiting'],
    diagnostics: ['Labs: leukocytosis, elevated bilirubin, ALP, GGT, aminotransferases', 'Blood cultures', 'RUQ ultrasound: CBD dilation, choledocholithiasis', 'MRCP or EUS for definitive biliary imaging', 'Tokyo Guidelines severity grading'],
    treatment: ['IV antibiotics (broad-spectrum: pip-tazo, carbapenems)', 'Urgent biliary drainage: ERCP with sphincterotomy and stone extraction', 'Percutaneous transhepatic biliary drainage if ERCP fails', 'Subsequent cholecystectomy for gallstone-related cholangitis'],
    dietaryGuidance: ['NPO during acute episode', 'Clear liquids then advance post-ERCP', 'Low-fat diet during recovery', 'Adequate hydration'],
    complications: ['Sepsis and septic shock', 'Hepatic abscess', 'Multiorgan failure', 'Biliary stricture', 'Recurrent cholangitis'],
    patientExplanation: 'A blockage in your bile duct has caused a serious infection. You need antibiotics and an urgent procedure to clear the blockage and drain the infected bile.',
    emergencySigns: ['Reynolds pentad (confusion, hypotension)', 'Signs of septic shock', 'Failure to improve after 24 hrs of antibiotics', 'Worsening jaundice'],
  },

  primary_biliary_cholangitis: {
    id: 'gi-pbc',
    name: 'Primary Biliary Cholangitis',
    nameEs: 'Colangitis Biliar Primaria',
    category: 'hepatobiliary',
    icd11: 'DB96.2',
    description: 'Chronic autoimmune destruction of intrahepatic small bile ducts, predominantly affecting middle-aged women.',
    pathophysiology: 'Autoimmune attack (anti-mitochondrial antibodies target PDC-E2) destroys small interlobular bile ducts, causing cholestasis, inflammation, fibrosis, and eventually cirrhosis.',
    symptoms: ['Fatigue (most common, often debilitating)', 'Pruritus (often precedes jaundice by years)', 'Jaundice (later stage)', 'Xanthomas, xanthelasma', 'Dry eyes and mouth (Sjogren overlap)', 'Hepatomegaly', 'Osteoporosis'],
    diagnostics: ['Anti-mitochondrial antibodies (AMA) positive in >90%', 'Elevated ALP and GGT (cholestatic pattern)', 'Elevated IgM', 'Liver biopsy: florid duct lesion (granulomatous destruction)', 'AMA-negative PBC diagnosed by biopsy'],
    treatment: ['Ursodeoxycholic acid (UDCA) - first-line, improves survival', 'Obeticholic acid (second-line if incomplete UDCA response)', 'Fibrates (bezafibrate) as add-on therapy', 'Pruritus: cholestyramine, rifampin, naltrexone, sertraline', 'Liver transplant for decompensated disease (low recurrence)', 'Calcium, vitamin D, DEXA screening'],
    dietaryGuidance: ['Calcium and vitamin D supplementation (osteoporosis prevention)', 'Fat-soluble vitamin supplementation (A, D, E, K) if cholestasis severe', 'Moderate fat intake (may worsen steatorrhea)', 'Avoid alcohol', 'Mediterranean-style diet'],
    complications: ['Cirrhosis and portal hypertension', 'Osteoporosis (metabolic bone disease)', 'Fat-soluble vitamin deficiency', 'Hyperlipidemia', 'Hepatocellular carcinoma', 'Overlap with autoimmune hepatitis'],
    patientExplanation: 'Your immune system is slowly damaging the small bile ducts in your liver. A medication called UDCA can slow this process and protect your liver for many years.',
    emergencySigns: ['Signs of liver failure', 'Variceal bleeding', 'Severe intractable pruritus', 'Fractures from osteoporosis'],
  },

  primary_sclerosing_cholangitis: {
    id: 'gi-psc',
    name: 'Primary Sclerosing Cholangitis',
    nameEs: 'Colangitis Esclerosante Primaria',
    category: 'hepatobiliary',
    icd11: 'DB96.3',
    description: 'Chronic progressive fibro-obliterative disease of intrahepatic and/or extrahepatic bile ducts, strongly associated with IBD.',
    pathophysiology: 'Immune-mediated periductal fibrosis causes multifocal strictures and dilation of bile ducts ("beaded" appearance). 70-80% have concurrent ulcerative colitis. Leads to biliary cirrhosis.',
    symptoms: ['Fatigue', 'Pruritus', 'Jaundice (intermittent or progressive)', 'RUQ pain', 'Fevers/chills (if bacterial cholangitis superimposed)', 'Often diagnosed incidentally via abnormal LFTs in IBD patient'],
    diagnostics: ['MRCP: multifocal strictures and dilations (beaded appearance)', 'ERCP for therapeutic intervention', 'Elevated ALP, GGT', 'p-ANCA positive (~80%)', 'Liver biopsy: onion-skin periductal fibrosis', 'No specific diagnostic autoantibody (unlike PBC)'],
    treatment: ['No proven medical therapy to halt progression', 'UDCA (controversial, may improve biochemistry but not outcomes)', 'ERCP with dilation/stenting for dominant strictures', 'Colonoscopy surveillance for IBD-associated colorectal cancer annually', 'Liver transplant (definitive treatment, but 20% recurrence)', 'Cholangiocarcinoma screening (CA 19-9, MRCP)'],
    dietaryGuidance: ['Fat-soluble vitamin supplementation', 'Calcium and vitamin D for bone health', 'Avoid alcohol', 'Balanced diet adequate in calories', 'Manage IBD dietary needs concurrently'],
    complications: ['Cholangiocarcinoma (10-15% lifetime risk)', 'Dominant strictures with cholangitis', 'Biliary cirrhosis', 'Colorectal cancer (with IBD)', 'Fat-soluble vitamin deficiency', 'Osteoporosis'],
    patientExplanation: 'Scarring is gradually narrowing your bile ducts, which can damage the liver over time. We monitor closely, treat complications, and a liver transplant may be needed eventually.',
    emergencySigns: ['Fever with jaundice (acute cholangitis)', 'Rapid worsening of jaundice (cholangiocarcinoma or dominant stricture)', 'Signs of liver decompensation', 'New abdominal mass'],
  },

  hepatocellular_carcinoma: {
    id: 'gi-hcc',
    name: 'Hepatocellular Carcinoma',
    nameEs: 'Carcinoma Hepatocelular',
    category: 'hepatobiliary',
    icd11: '2C12.0',
    description: 'Primary liver malignancy arising from hepatocytes, typically in the setting of cirrhosis or chronic liver disease.',
    pathophysiology: 'Chronic hepatocyte injury and regeneration in cirrhosis promotes DNA mutations and carcinogenesis. Risk factors: HBV, HCV, alcohol, NASH, aflatoxin B1. HBV can cause HCC without cirrhosis.',
    symptoms: ['Often asymptomatic (detected on surveillance)', 'RUQ pain or fullness', 'Weight loss', 'Hepatomegaly with palpable mass', 'Decompensation of previously stable cirrhosis', 'Paraneoplastic: erythrocytosis, hypercalcemia, hypoglycemia'],
    diagnostics: ['Surveillance: ultrasound +/- AFP every 6 months in cirrhotics', 'Multiphase CT or MRI: arterial enhancement with venous washout (LI-RADS)', 'AFP, AFP-L3, DCP (PIVKA-II)', 'Biopsy rarely needed if imaging diagnostic', 'BCLC staging system'],
    treatment: ['Very early/early: resection or liver transplant (Milan criteria: single <=5cm or <=3 nodules each <=3cm)', 'Ablation (radiofrequency, microwave) for small tumors', 'Transarterial chemoembolization (TACE) for intermediate stage', 'Systemic: atezolizumab + bevacizumab (first-line advanced)', 'Sorafenib, lenvatinib, cabozantinib, regorafenib'],
    dietaryGuidance: ['Follow cirrhosis dietary guidelines', 'Adequate protein and calories to prevent sarcopenia', 'Avoid alcohol', 'Hepatotoxin avoidance (aflatoxin in contaminated grains)', 'Nutritional support during systemic therapy'],
    complications: ['Tumor rupture and hemoperitoneum', 'Portal vein thrombosis', 'Hepatic decompensation', 'Metastatic disease', 'Paraneoplastic syndromes'],
    patientExplanation: 'A cancer has developed in your liver, often related to chronic liver disease. Depending on size and location, treatment may include surgery, transplant, ablation, or targeted medications.',
    emergencySigns: ['Sudden severe abdominal pain (tumor rupture)', 'Rapid liver decompensation', 'Signs of GI bleeding', 'New confusion (encephalopathy or brain metastases)'],
  },

  // ─── PANCREATIC ───────────────────────────────────────────────
  acute_pancreatitis: {
    id: 'gi-acute-pancreatitis',
    name: 'Acute Pancreatitis',
    nameEs: 'Pancreatitis Aguda',
    category: 'pancreatic',
    icd11: 'DC31',
    description: 'Acute inflammatory process of the pancreas, most commonly caused by gallstones or alcohol.',
    pathophysiology: 'Premature intrapancreatic activation of trypsinogen to trypsin triggers autodigestion. Causes: gallstone impaction at ampulla (40%), alcohol (30%), hypertriglyceridemia, post-ERCP, drugs, idiopathic.',
    symptoms: ['Severe epigastric pain radiating to the back', 'Pain worse supine, improved leaning forward', 'Nausea and vomiting', 'Abdominal tenderness and guarding', 'Fever and tachycardia', 'Severe: Grey Turner sign (flank ecchymosis), Cullen sign (periumbilical ecchymosis)'],
    diagnostics: ['Diagnosis requires 2 of 3: characteristic pain, lipase >3x ULN, imaging findings', 'Lipase preferred over amylase (more specific)', 'CT abdomen (for complications, not required for diagnosis)', 'RUQ ultrasound (gallstone etiology)', 'MRCP or EUS for occult choledocholithiasis', 'Severity: BISAP score, Ranson criteria, APACHE II'],
    treatment: ['Aggressive IV fluid resuscitation (goal-directed, lactated Ringer)', 'Early oral feeding as tolerated (within 24 hrs)', 'Pain management (multimodal, avoid morphine myth)', 'NPO only if unable to tolerate oral intake', 'ERCP within 24 hrs for cholangitis or persistent biliary obstruction', 'Cholecystectomy during same admission for mild gallstone pancreatitis', 'ICU for organ failure'],
    dietaryGuidance: ['Early oral feeding (low-fat, solid diet) as tolerated', 'No need for prolonged NPO', 'Low-fat diet during recovery', 'Strict alcohol abstinence', 'If unable to eat: enteral nutrition via nasojejunal tube preferred over TPN', 'Long-term: moderate fat, avoid trigger foods'],
    complications: ['Pancreatic necrosis (sterile or infected)', 'Pseudocyst (>4 weeks)', 'Walled-off necrosis', 'Organ failure (pulmonary, renal, cardiovascular)', 'SIRS and sepsis', 'Splenic vein thrombosis'],
    patientExplanation: 'Your pancreas is inflamed, causing severe belly pain. Treatment focuses on IV fluids, pain control, and finding the cause. Most cases resolve with supportive care.',
    emergencySigns: ['Persistent organ failure >48 hrs (severe pancreatitis)', 'Fever with necrosis (infected necrosis)', 'Worsening abdominal pain', 'Signs of shock', 'Respiratory distress'],
  },

  chronic_pancreatitis: {
    id: 'gi-chronic-pancreatitis',
    name: 'Chronic Pancreatitis',
    nameEs: 'Pancreatitis Crónica',
    category: 'pancreatic',
    icd11: 'DC32',
    description: 'Progressive inflammatory disease with irreversible structural damage leading to exocrine and endocrine insufficiency.',
    pathophysiology: 'Recurrent pancreatic injury (alcohol most common) causes persistent inflammation, progressive fibrosis, calcification, duct dilation/stricture, and loss of acinar and islet cells.',
    symptoms: ['Chronic epigastric pain (may burn out over years)', 'Steatorrhea (greasy, foul-smelling stools)', 'Weight loss and malnutrition', 'Diabetes mellitus (type 3c)', 'Bloating', 'Nausea'],
    diagnostics: ['CT: calcifications, duct dilation, atrophy', 'MRCP/secretin-MRCP: ductal changes', 'EUS: earliest changes (parenchymal and ductal criteria)', 'Fecal elastase-1 (<200 = exocrine insufficiency)', 'HbA1c for endocrine insufficiency', 'Rule out pancreatic cancer in new-onset symptoms'],
    treatment: ['Pain management: stepwise approach (non-opioid first, celiac plexus block, surgery)', 'Pancreatic enzyme replacement therapy (PERT) with meals', 'Alcohol and smoking cessation (critical)', 'Fat-soluble vitamin supplementation (A, D, E, K)', 'Insulin for pancreatogenic diabetes', 'ERCP for dominant strictures/stones', 'Surgery: Frey procedure, Puestow, total pancreatectomy with islet autotransplantation'],
    dietaryGuidance: ['Small frequent meals (5-6/day)', 'Moderate fat diet (not ultra-low-fat; needs PERT coverage)', 'PERT taken with every meal and snack', 'MCT oil for caloric supplementation', 'Fat-soluble vitamin supplementation', 'Strict alcohol and tobacco avoidance', 'High-calorie diet to prevent weight loss'],
    complications: ['Exocrine insufficiency (steatorrhea, malnutrition)', 'Endocrine insufficiency (diabetes)', 'Pseudocyst', 'Pancreatic duct stones', 'Bile duct stricture', 'Splenic vein thrombosis', 'Pancreatic cancer (4% lifetime risk)'],
    patientExplanation: 'Long-term inflammation has scarred your pancreas, affecting its ability to digest food and control blood sugar. Enzyme supplements with meals and lifestyle changes are key to managing this.',
    emergencySigns: ['Acute flare with severe pain', 'Signs of infected pseudocyst', 'New-onset jaundice (bile duct stricture or cancer)', 'Severe malnutrition or uncontrolled diabetes', 'GI bleeding (splenic vein thrombosis)'],
  },

  pancreatic_cancer: {
    id: 'gi-pancreatic-cancer',
    name: 'Pancreatic Cancer',
    nameEs: 'Cáncer de Páncreas',
    category: 'pancreatic',
    icd11: '2C10',
    description: 'Malignant neoplasm of the pancreas, predominantly ductal adenocarcinoma, with poor prognosis (5-yr survival ~12%).',
    pathophysiology: 'KRAS mutations (>90%) drive pancreatic intraepithelial neoplasia (PanIN) progression through additional loss of TP53, CDKN2A, SMAD4. Dense desmoplastic stroma limits drug delivery and immune infiltration.',
    symptoms: ['Painless jaundice (head tumors, 70%)', 'Weight loss', 'New-onset diabetes', 'Epigastric pain radiating to back', 'Anorexia', 'Steatorrhea', 'Courvoisier sign (palpable nontender gallbladder)', 'Trousseau syndrome (migratory thrombophlebitis)'],
    diagnostics: ['CT pancreas protocol (triple-phase)', 'CA 19-9 (not screening, used for monitoring)', 'EUS with FNA for tissue diagnosis', 'MRCP for biliary anatomy', 'PET-CT for staging', 'Staging laparoscopy before resection', 'Genetic testing (BRCA, PALB2)'],
    treatment: ['Resectable: pancreaticoduodenectomy (Whipple) or distal pancreatectomy', 'Neoadjuvant therapy (FOLFIRINOX) increasingly favored', 'Adjuvant: modified FOLFIRINOX or gemcitabine + capecitabine', 'Borderline resectable: neoadjuvant chemo +/- radiation', 'Unresectable/metastatic: FOLFIRINOX or gem/nab-paclitaxel, olaparib (BRCA+)', 'Biliary stent for jaundice palliation', 'Celiac plexus neurolysis for pain'],
    dietaryGuidance: ['Pancreatic enzyme replacement with meals', 'High-calorie, high-protein diet', 'Small frequent meals', 'Nutritional counseling essential', 'Fat-soluble vitamin supplementation', 'Consider oral nutritional supplements', 'Address anorexia management'],
    complications: ['Biliary obstruction', 'Gastric outlet obstruction', 'Pancreatic exocrine insufficiency', 'Venous thromboembolism', 'Cachexia', 'Peritoneal carcinomatosis', 'Liver metastases'],
    patientExplanation: 'A cancer has been found in your pancreas. Treatment depends on whether it can be surgically removed. We will discuss surgery, chemotherapy, and supportive care options.',
    emergencySigns: ['Complete biliary obstruction with cholangitis', 'GI obstruction (persistent vomiting)', 'Severe uncontrolled pain', 'Deep vein thrombosis or PE', 'Rapid clinical deterioration'],
  },

  pancreatic_pseudocyst: {
    id: 'gi-pancreatic-pseudocyst',
    name: 'Pancreatic Pseudocyst',
    nameEs: 'Pseudoquiste Pancreático',
    category: 'pancreatic',
    icd11: 'DC33',
    description: 'Encapsulated collection of pancreatic fluid lacking an epithelial lining, typically arising >4 weeks after acute pancreatitis.',
    pathophysiology: 'Pancreatic duct disruption leaks enzyme-rich fluid that becomes walled off by inflammatory tissue (no true epithelial lining, distinguishing from true cysts). Requires mature wall for intervention.',
    symptoms: ['Persistent abdominal pain after pancreatitis', 'Palpable epigastric mass', 'Early satiety (gastric compression)', 'Nausea, vomiting', 'Weight loss', 'May be asymptomatic'],
    diagnostics: ['CT abdomen: well-defined fluid collection with wall, no solid component', 'MRI/MRCP: better characterization', 'EUS with FNA: fluid analysis (high amylase, low CEA distinguishes from mucinous cyst)', 'Distinguish from walled-off necrosis, cystic neoplasm'],
    treatment: ['Small, asymptomatic: observation (many resolve spontaneously)', 'Symptomatic or >6cm or complicated: drainage', 'EUS-guided cystogastrostomy (preferred endoscopic approach)', 'Surgical drainage (cystogastrostomy, cystojejunostomy)', 'Percutaneous drainage (last resort, risk of external fistula)'],
    dietaryGuidance: ['Low-fat diet during observation period', 'Small frequent meals', 'Advance diet after successful drainage', 'Alcohol avoidance', 'PERT if concurrent exocrine insufficiency'],
    complications: ['Infection (pancreatic abscess)', 'Hemorrhage into pseudocyst', 'Rupture', 'Biliary or gastric obstruction', 'Pseudoaneurysm of adjacent vessels', 'Splenic vein thrombosis'],
    patientExplanation: 'A fluid-filled pocket formed near your pancreas after inflammation. Small ones often resolve on their own. If it causes symptoms, a procedure can drain it through your stomach wall.',
    emergencySigns: ['Fever (infected pseudocyst)', 'Sudden severe pain or hemodynamic instability (rupture/hemorrhage)', 'Rapid increase in size', 'GI bleeding (pseudoaneurysm erosion)', 'Signs of obstruction'],
  },

  // ─── COLORECTAL ───────────────────────────────────────────────
  colorectal_cancer: {
    id: 'gi-colorectal-cancer',
    name: 'Colorectal Cancer',
    nameEs: 'Cáncer Colorrectal',
    category: 'colorectal',
    icd11: '2B90',
    description: 'Malignant neoplasm of the colon or rectum, the third most common cancer, typically arising from adenomatous polyps.',
    pathophysiology: 'Adenoma-carcinoma sequence: APC mutation -> KRAS -> TP53 loss over 10-15 years. Alternative: microsatellite instability pathway (Lynch syndrome, MLH1 methylation). Serrated pathway via BRAF mutation.',
    symptoms: ['Change in bowel habits', 'Rectal bleeding or hematochezia', 'Iron deficiency anemia (right-sided)', 'Abdominal pain', 'Unintentional weight loss', 'Obstruction (left-sided, apple-core lesion)', 'Tenesmus (rectal cancer)'],
    diagnostics: ['Colonoscopy with biopsy (gold standard)', 'CT chest/abdomen/pelvis for staging', 'CEA (prognostic and monitoring, not screening)', 'MSI/MMR testing (all CRC)', 'KRAS, NRAS, BRAF testing (metastatic)', 'MRI pelvis for rectal cancer staging', 'Screening: colonoscopy at 45 (average risk)'],
    treatment: ['Polyp with cancer: endoscopic resection if favorable features', 'Colon: surgical resection with lymphadenectomy (>12 nodes)', 'Adjuvant chemo (stage III): FOLFOX or CAPOX', 'Rectal: neoadjuvant chemoradiation then TME, or total neoadjuvant therapy', 'Metastatic: FOLFOX/FOLFIRI +/- bevacizumab or cetuximab (RAS WT, left-sided)', 'Immunotherapy: pembrolizumab for MSI-H/dMMR (first-line)'],
    dietaryGuidance: ['Increase fiber, fruits, vegetables (prevention)', 'Limit red and processed meat', 'Adequate calcium and vitamin D', 'Limit alcohol', 'Maintain healthy weight', 'Post-surgery: low-residue initially, advance gradually', 'Aspirin may reduce risk (discuss with physician)'],
    complications: ['Bowel obstruction', 'Perforation', 'Liver/lung metastases', 'Anastomotic leak post-surgery', 'Local recurrence (rectal)', 'Lynch syndrome cancer risks in family'],
    patientExplanation: 'Cancer was found in your colon or rectum. Regular screening catches it early when it is most curable. Treatment usually involves surgery and may include chemotherapy.',
    emergencySigns: ['Complete bowel obstruction', 'Perforation with peritonitis', 'Massive rectal bleeding', 'Signs of metastatic disease (jaundice, bone pain)'],
  },

  diverticular_disease: {
    id: 'gi-diverticular',
    name: 'Diverticulosis and Diverticulitis',
    nameEs: 'Diverticulosis y Diverticulitis',
    category: 'colorectal',
    icd11: 'DB33',
    description: 'Diverticulosis: colonic outpouchings (pseudodiverticula). Diverticulitis: inflammation/infection of diverticula, typically in the sigmoid colon.',
    pathophysiology: 'High intraluminal pressure from low-fiber diet pushes mucosa through weakened muscular wall at vasa recta penetration points. Fecalith obstruction of diverticulum leads to microperforation, inflammation, and infection.',
    symptoms: ['Diverticulosis: usually asymptomatic, painless rectal bleeding', 'Diverticulitis: LLQ pain (Western), fever, altered bowel habits', 'Nausea, vomiting', 'Localized peritoneal signs', 'Urinary symptoms if adjacent to bladder'],
    diagnostics: ['CT abdomen/pelvis with IV contrast (diverticulitis): wall thickening, pericolic fat stranding, abscess', 'Avoid colonoscopy during acute diverticulitis', 'Colonoscopy 6-8 weeks after resolution to exclude cancer', 'Labs: leukocytosis, elevated CRP', 'Hinchey classification for complicated disease'],
    treatment: ['Uncomplicated diverticulitis: antibiotics (cipro + metronidazole or augmentin) or observation if mild', 'Clear liquid then advance diet', 'Complicated: CT-guided percutaneous drainage for abscess >3cm', 'Surgery: sigmoid colectomy for recurrent or complicated disease', 'Emergency surgery: Hartmann procedure for perforation/peritonitis', 'Diverticular bleeding: colonoscopy with hemostasis, angiographic embolization'],
    dietaryGuidance: ['High-fiber diet for prevention (25-30g/day)', 'Gradual increase to prevent bloating', 'No evidence to avoid seeds, nuts, or popcorn (old myth)', 'Low-residue diet during acute diverticulitis', 'Adequate hydration with high fiber', 'Resume high-fiber after acute episode resolves'],
    complications: ['Abscess', 'Perforation with peritonitis', 'Fistula (colovesical, colovaginal)', 'Stricture with obstruction', 'Diverticular hemorrhage (usually painless, brisk)', 'Recurrence'],
    patientExplanation: 'Small pouches formed in your colon wall. If one gets inflamed or infected, it causes pain and fever. A high-fiber diet helps prevent problems, and most episodes respond to antibiotics.',
    emergencySigns: ['Severe abdominal pain with peritoneal signs (perforation)', 'High fever with sepsis', 'Heavy rectal bleeding', 'Pneumaturia or fecaluria (colovesical fistula)', 'Signs of obstruction'],
  },

  hemorrhoids: {
    id: 'gi-hemorrhoids',
    name: 'Hemorrhoids',
    nameEs: 'Hemorroides',
    category: 'colorectal',
    icd11: 'DB60',
    description: 'Dilated vascular cushions of the anal canal; internal (above dentate line) or external (below dentate line).',
    pathophysiology: 'Straining, constipation, pregnancy, and aging cause engorgement and displacement of anal vascular cushions. Internal hemorrhoids are covered by insensate mucosa; external by somatic-innervated skin.',
    symptoms: ['Painless bright red rectal bleeding (internal)', 'Prolapse through anus (internal grades II-IV)', 'Perianal lump, pain (external, especially if thrombosed)', 'Pruritus ani', 'Mucous discharge', 'Incomplete evacuation sensation'],
    diagnostics: ['Digital rectal exam and anoscopy', 'Grading (internal): I (no prolapse), II (spontaneous reduction), III (manual reduction), IV (irreducible)', 'Colonoscopy to exclude other bleeding sources if indicated', 'Exclude colorectal cancer in patients >45 or with red flags'],
    treatment: ['Conservative: fiber supplementation, adequate fluids, sitz baths, topical agents', 'Office procedures (Grade I-III): rubber band ligation (most effective), sclerotherapy, infrared coagulation', 'Surgical hemorrhoidectomy (Grade III-IV, failed office treatment)', 'Stapled hemorrhoidopexy', 'Thrombosed external: excision within 72 hrs or conservative if >72 hrs'],
    dietaryGuidance: ['High-fiber diet (25-30g/day) - cornerstone of management', 'Psyllium husk supplementation', 'Adequate water intake (8+ glasses/day)', 'Avoid straining (no prolonged toilet sitting)', 'Avoid constipation-causing foods', 'Limit spicy foods if they worsen symptoms'],
    complications: ['Thrombosis (external)', 'Strangulation (Grade IV internal)', 'Anemia from chronic bleeding', 'Perianal skin tags', 'Recurrence'],
    patientExplanation: 'Swollen blood vessels around your anus cause bleeding and discomfort. More fiber, fluids, and avoiding straining usually help. Simple procedures can treat stubborn cases.',
    emergencySigns: ['Severe acute pain (thrombosed or strangulated hemorrhoid)', 'Significant bleeding requiring transfusion', 'Signs of infection (fever, perianal cellulitis)', 'Unable to reduce prolapse'],
  },

  anal_fissure: {
    id: 'gi-anal-fissure',
    name: 'Anal Fissure',
    nameEs: 'Fisura Anal',
    category: 'colorectal',
    icd11: 'DB61',
    description: 'Linear tear in the anoderm below the dentate line, most commonly at the posterior midline.',
    pathophysiology: 'Passage of hard stool tears the anoderm. Internal anal sphincter spasm reduces blood flow, impairing healing. Chronic ischemia at the posterior midline perpetuates the cycle.',
    symptoms: ['Severe sharp pain during and after bowel movements', 'Bright red blood on toilet paper or stool surface', 'Anal spasm', 'Fear of defecation', 'Sentinel pile (chronic fissure)'],
    diagnostics: ['Visual inspection (gentle separation of buttocks)', 'Posterior midline location most common', 'Atypical location (lateral) warrants evaluation for: Crohn disease, HIV, syphilis, TB, cancer', 'Digital exam deferred if too painful; exam under anesthesia if needed'],
    treatment: ['Conservative (first-line): high-fiber diet, stool softeners, sitz baths, adequate hydration', 'Topical nitroglycerin 0.4% or diltiazem 2% (relax sphincter)', 'Botulinum toxin injection into internal sphincter', 'Lateral internal sphincterotomy (definitive for chronic refractory)', 'Fissurectomy with flap advancement (alternative)'],
    dietaryGuidance: ['High-fiber diet (25-30g/day)', 'Fiber supplements (psyllium)', 'Adequate water intake', 'Stool softeners (docusate)', 'Avoid constipation and straining', 'Avoid spicy foods during acute phase'],
    complications: ['Chronic fissure (>6-8 weeks)', 'Sentinel skin tag', 'Anal stenosis (rare, post-surgery)', 'Incontinence risk with sphincterotomy (small)', 'Abscess or fistula (rare)'],
    patientExplanation: 'You have a small tear in the skin at your anus, causing sharp pain with bowel movements. Keeping stools soft with fiber and fluids, plus prescription ointment, heals most fissures.',
    emergencySigns: ['Signs of infection (abscess formation)', 'Significant bleeding', 'Atypical location suggesting underlying disease', 'Failure to heal after 8 weeks of treatment'],
  },

  cdiff_colitis: {
    id: 'gi-cdiff',
    name: 'Clostridioides difficile Colitis',
    nameEs: 'Colitis por Clostridioides difficile',
    category: 'colorectal',
    icd11: '1A03',
    description: 'Toxin-mediated colitis caused by C. difficile, typically following antibiotic exposure disrupting normal gut flora.',
    pathophysiology: 'Antibiotics deplete commensal flora, allowing C. difficile spore germination and vegetative growth. Toxins A and B cause epithelial damage, inflammation, and pseudomembrane formation.',
    symptoms: ['Watery diarrhea (>=3 stools/day)', 'Abdominal pain and cramping', 'Fever', 'Leukocytosis (may be very high)', 'Anorexia', 'Nausea', 'Foul-smelling stool'],
    diagnostics: ['Stool testing: NAAT (PCR) for toxin gene or two-step (GDH screen + toxin EIA)', 'Only test diarrheal stool (Bristol 5-7)', 'Do not test for cure', 'Labs: leukocytosis (WBC may exceed 30k), elevated creatinine, low albumin', 'CT: colonic wall thickening, accordion sign', 'Colonoscopy: pseudomembranes (avoid in fulminant disease)'],
    treatment: ['Non-severe: fidaxomicin (preferred) or oral vancomycin 125mg QID x 10 days', 'Severe (WBC>15k, Cr>1.5): oral vancomycin', 'Fulminant: oral vancomycin + IV metronidazole, consider rectal vancomycin', 'First recurrence: fidaxomicin or vancomycin taper/pulse', 'Multiple recurrences: fecal microbiota transplant (FMT)', 'Bezlotoxumab (anti-toxin B) for recurrence prevention', 'Discontinue inciting antibiotic if possible'],
    dietaryGuidance: ['Adequate hydration (critical)', 'Electrolyte replacement', 'BRAT diet if tolerated during acute phase', 'Probiotics (S. boulardii) may reduce recurrence (limited evidence)', 'Advance diet as tolerated', 'Avoid dairy if lactose intolerance develops'],
    complications: ['Toxic megacolon', 'Perforation', 'Sepsis', 'Recurrence (20-30% after first episode)', 'Prolonged ileus', 'Death (fulminant colitis)'],
    patientExplanation: 'Antibiotics disrupted the normal bacteria in your colon, allowing a harmful bacteria called C. diff to grow and cause inflammation and diarrhea. Specific antibiotics will treat this infection.',
    emergencySigns: ['Abdominal distension (toxic megacolon)', 'Ileus (no stool output despite infection)', 'Hemodynamic instability', 'WBC >30,000 or rapidly rising', 'Lactic acidosis', 'Signs of peritonitis'],
  },

  ischemic_colitis: {
    id: 'gi-ischemic-colitis',
    name: 'Ischemic Colitis',
    nameEs: 'Colitis Isquémica',
    category: 'colorectal',
    icd11: 'DB90.1',
    description: 'Transient reduction of blood flow to the colon causing mucosal ischemia, typically at watershed areas (splenic flexure, rectosigmoid).',
    pathophysiology: 'Low-flow state or small vessel disease causes mucosal ischemia at watershed areas (splenic flexure = Griffith point, rectosigmoid = Sudeck point). Usually non-occlusive. Most cases are self-limiting.',
    symptoms: ['Sudden crampy abdominal pain (usually left-sided)', 'Urge to defecate', 'Bloody diarrhea or hematochezia within 24 hrs', 'Mild abdominal tenderness', 'Low-grade fever'],
    diagnostics: ['CT abdomen: segmental colonic wall thickening, thumbprinting, pericolonic fat stranding', 'Colonoscopy within 48 hrs: segmental mucosal edema, hemorrhage, ulceration at watershed areas', 'Biopsy to confirm and exclude other causes', 'Labs: mild leukocytosis, elevated lactate (severe), lactic acidosis (gangrene)'],
    treatment: ['Supportive care (90% resolve with conservative management)', 'IV fluids, bowel rest', 'Broad-spectrum antibiotics if signs of infection', 'Avoid vasoconstrictors, correct hypotension', 'Discontinue offending medications (constipation-causing drugs, vasoconstrictors)', 'Surgery: gangrenous bowel, perforation, clinical deterioration'],
    dietaryGuidance: ['NPO or clear liquids during acute phase', 'Advance diet as symptoms resolve', 'Adequate hydration to maintain perfusion', 'Heart-healthy diet to address underlying vascular disease', 'Fiber supplementation to prevent constipation'],
    complications: ['Gangrenous colitis (15%)', 'Stricture formation', 'Perforation', 'Chronic segmental colitis', 'Recurrence'],
    patientExplanation: 'Blood flow to a section of your colon was temporarily reduced, causing pain and bloody diarrhea. Most cases heal on their own with rest, fluids, and monitoring.',
    emergencySigns: ['Worsening abdominal pain with peritoneal signs (gangrene)', 'Right-sided colonic involvement (more severe, worse prognosis)', 'Signs of sepsis', 'Lactic acidosis', 'Profuse bleeding'],
  },

  // ─── FUNCTIONAL ───────────────────────────────────────────────
  ibs: {
    id: 'gi-ibs',
    name: 'Irritable Bowel Syndrome',
    nameEs: 'Síndrome de Intestino Irritable',
    category: 'functional',
    icd11: 'DD91',
    description: 'Functional GI disorder with recurrent abdominal pain related to defecation and altered bowel habits, without structural pathology.',
    pathophysiology: 'Multifactorial: visceral hypersensitivity, gut-brain axis dysfunction, altered motility, intestinal dysbiosis, mucosal immune activation, and central sensitization. Post-infectious IBS in 10-15%.',
    symptoms: ['Recurrent abdominal pain related to defecation', 'Altered stool frequency or form', 'Bloating', 'Mucus in stool', 'Subtypes: IBS-D (diarrhea), IBS-C (constipation), IBS-M (mixed)'],
    diagnostics: ['Rome IV criteria: pain >=1 day/week x 3 months, related to defecation, stool frequency, or stool form', 'Limited testing to exclude red flags: CBC, CRP, celiac serology, fecal calprotectin', 'Colonoscopy only if alarm features', 'No specific biomarker'],
    treatment: ['Diet: low-FODMAP diet (supervised by dietitian)', 'Fiber: soluble fiber (psyllium) for IBS-C', 'IBS-D: loperamide, rifaximin, eluxadoline', 'IBS-C: linaclotide, lubiprostone, PEG', 'Pain: antispasmodics, low-dose TCAs (IBS-D) or SSRIs (IBS-C)', 'Behavioral: CBT, gut-directed hypnotherapy'],
    dietaryGuidance: ['Low-FODMAP elimination then reintroduction (dietitian-supervised)', 'Regular meal timing', 'Adequate hydration', 'Limit caffeine, alcohol, carbonated drinks', 'Soluble fiber over insoluble fiber', 'Food diary to identify personal triggers', 'Peppermint oil capsules may reduce pain'],
    complications: ['Reduced quality of life', 'Anxiety and depression (comorbid)', 'Unnecessary surgeries if misdiagnosed', 'Nutritional deficiency from overly restrictive diets', 'Opioid dependence from chronic pain management'],
    patientExplanation: 'Your gut is extra sensitive and does not process signals normally, causing pain and bowel changes. Diet modifications, stress management, and targeted medications can significantly improve your symptoms.',
    emergencySigns: ['Red flags suggesting organic disease: rectal bleeding, weight loss, anemia, nighttime symptoms, age >50 new onset', 'Family history of IBD or colon cancer', 'Progressive worsening despite treatment'],
  },

  functional_dyspepsia: {
    id: 'gi-functional-dyspepsia',
    name: 'Functional Dyspepsia',
    nameEs: 'Dispepsia Funcional',
    category: 'functional',
    icd11: 'DD90.0',
    description: 'Chronic upper GI symptoms (epigastric pain, early satiety, postprandial fullness) without structural explanation on endoscopy.',
    pathophysiology: 'Impaired gastric accommodation, visceral hypersensitivity, delayed gastric emptying (in subset), duodenal eosinophilia, altered duodenal permeability, and psychosocial factors.',
    symptoms: ['Epigastric pain or burning (epigastric pain syndrome)', 'Postprandial fullness (postprandial distress syndrome)', 'Early satiety', 'Nausea', 'Bloating', 'Overlap with GERD and IBS common'],
    diagnostics: ['Rome IV criteria: >=1 of bothersome postprandial fullness, early satiety, epigastric pain/burning for 3 months', 'Upper endoscopy to exclude organic disease (required)', 'H. pylori testing and treatment (test-and-treat)', 'No structural cause identified'],
    treatment: ['H. pylori eradication if positive', 'PPI trial (4-8 weeks)', 'TCAs (amitriptyline 25-50mg) if PPI fails', 'Prokinetics (metoclopramide, short-term) for postprandial distress', 'Mirtazapine for weight loss/nausea-predominant', 'Psychological therapy (CBT, psychodynamic)', 'Buspirone (fundic relaxation)'],
    dietaryGuidance: ['Small frequent meals', 'Low-fat diet may help postprandial symptoms', 'Avoid individual trigger foods', 'Eat slowly, chew well', 'Limit spicy, acidic, and fatty foods', 'Regular meal schedule', 'Consider trial of wheat/gluten reduction'],
    complications: ['Chronic symptom burden', 'Weight loss from food avoidance', 'Reduced quality of life', 'Anxiety and depression', 'Unnecessary investigations and procedures'],
    patientExplanation: 'Your stomach is sensitive and causes discomfort even though no structural problem was found. This is a real condition involving nerve-gut communication. Medication and dietary changes can help.',
    emergencySigns: ['Alarm features: GI bleeding, progressive dysphagia, persistent vomiting, weight loss >5%', 'Anemia', 'New onset after age 60', 'Family history of upper GI cancer'],
  },

  cyclic_vomiting: {
    id: 'gi-cyclic-vomiting',
    name: 'Cyclic Vomiting Syndrome',
    nameEs: 'Síndrome de Vómitos Cíclicos',
    category: 'functional',
    icd11: 'DD91.1',
    description: 'Recurrent stereotypical episodes of intense nausea and vomiting separated by symptom-free intervals, often associated with migraine.',
    pathophysiology: 'Likely involves mitochondrial dysfunction, hypothalamic-pituitary-adrenal axis dysregulation, and autonomic nervous system dysfunction. Strong association with migraine (maternal inheritance, similar triggers).',
    symptoms: ['Stereotypical episodes of intense nausea and vomiting', 'Episodes last hours to days', 'Symptom-free intervals between episodes', 'Prodromal phase (pallor, nausea, abdominal pain)', 'Lethargy', 'Often triggered by stress, menses, infection, certain foods'],
    diagnostics: ['Rome IV criteria: >=2 episodes of intense nausea/vomiting in 6 months, stereotypical, >=1 week apart', 'Exclusion of organic causes (metabolic, CNS, GI structural)', 'Upper endoscopy, CT/MRI brain, metabolic workup', 'Cannabis hyperemesis must be excluded (cannabinoid use history)'],
    treatment: ['Abortive: triptans (sumatriptan) at prodrome, ondansetron, IV fluids', 'Prophylaxis: amitriptyline (first-line adults), topiramate, propranolol', 'CoQ10 and L-carnitine supplementation', 'Aprepitant for refractory episodes', 'Avoid triggers', 'Cannabis cessation if cannabis hyperemesis suspected'],
    dietaryGuidance: ['Identify and avoid food triggers (chocolate, cheese, MSG)', 'Avoid fasting (maintain regular meals)', 'Adequate hydration between episodes', 'Clear liquids during prodrome', 'BRAT diet during recovery phase', 'CoQ10-rich foods (organ meats, spinach, broccoli)', 'Avoid alcohol and caffeine excess'],
    complications: ['Severe dehydration and electrolyte imbalance', 'Mallory-Weiss tear from vomiting', 'Dental enamel erosion', 'Nutritional deficiency', 'Missed work/school', 'Opioid dependency from ER visits'],
    patientExplanation: 'You experience repeated episodes of severe vomiting with healthy periods in between. This is related to migraine-like brain signaling. Daily preventive medication can reduce episode frequency and severity.',
    emergencySigns: ['Severe dehydration (unable to keep fluids down)', 'Hematemesis (Mallory-Weiss tear)', 'Electrolyte abnormalities (muscle cramps, cardiac symptoms)', 'Altered mental status', 'Episodes changing in pattern (re-evaluate diagnosis)'],
  },
};

/**
 * Helper: get conditions by category
 */
export function getGIConditionsByCategory(category: GIConditionEntry['category']): GIConditionEntry[] {
  return Object.values(GI_CONDITIONS).filter(c => c.category === category);
}

/**
 * Helper: search conditions by keyword
 */
export function searchGIConditions(query: string): GIConditionEntry[] {
  const q = query.toLowerCase();
  return Object.values(GI_CONDITIONS).filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.nameEs.toLowerCase().includes(q) ||
    c.description.toLowerCase().includes(q) ||
    c.symptoms.some(s => s.toLowerCase().includes(q))
  );
}

/**
 * Category labels for display
 */
export const GI_CATEGORY_LABELS: Record<GIConditionEntry['category'], { en: string; es: string }> = {
  esophageal: { en: 'Esophageal Disorders', es: 'Trastornos Esofágicos' },
  gastric: { en: 'Gastric Disorders', es: 'Trastornos Gástricos' },
  intestinal: { en: 'Intestinal Disorders', es: 'Trastornos Intestinales' },
  hepatobiliary: { en: 'Hepatobiliary Disorders', es: 'Trastornos Hepatobiliares' },
  pancreatic: { en: 'Pancreatic Disorders', es: 'Trastornos Pancreáticos' },
  colorectal: { en: 'Colorectal Disorders', es: 'Trastornos Colorrectales' },
  functional: { en: 'Functional GI Disorders', es: 'Trastornos GI Funcionales' },
};
