/**
 * ICD-11 Condition Index & Template Generator
 *
 * Contains:
 * 1. generateConditionTemplate() - Creates a ConditionSimulation skeleton with defaults
 * 2. ICD11_CONDITIONS[] - 300+ conditions covering all ICD-11 chapters
 */

import type {
  ConditionCategory,
  ConditionSimulation,
  ConditionPathophysiology,
  ClinicalPresentation,
  DiseaseProgression,
  ConditionAnatomyMapping,
  MultiLevelExplanation,
} from './types';

// ============================================
// Compact Condition Entry Type
// ============================================

export interface ICD11ConditionEntry {
  id: string;
  name: string;
  icd: string;
  cat: ConditionCategory;
  desc: string;
  sys: string[];
}

// ============================================
// Template Generator
// ============================================

/**
 * Generates a ConditionSimulation skeleton with sensible defaults.
 * Fill in the returned object with condition-specific data.
 */
export function generateConditionTemplate(params: {
  conditionId: string;
  name: string;
  icdCode: string;
  category: ConditionCategory;
  description: string;
  systems: string[];
}): ConditionSimulation {
  const defaultExplanations: MultiLevelExplanation = {
    level1: `${params.name} is a medical condition that affects your body.`,
    level2: `${params.name} is a ${params.category} condition: ${params.description}`,
    level3: `${params.name} (${params.icdCode}) is a ${params.category} disorder affecting the ${params.systems.join(', ')} system(s).`,
    level4: `${params.name} — ${params.description} Classification: ${params.icdCode}. Systems involved: ${params.systems.join(', ')}.`,
    level5: `${params.name} (${params.icdCode}): ${params.description} Pathophysiological involvement spans ${params.systems.join(', ')} systems. Requires further elaboration of molecular mechanisms and clinical staging.`,
  };

  const defaultPathophysiology: ConditionPathophysiology = {
    summary: params.description,
    mechanisms: [],
    riskFactors: [],
  };

  const defaultPresentation: ClinicalPresentation = {
    primarySymptoms: [],
  };

  const defaultProgression: DiseaseProgression = {
    naturalHistory: `Natural history of ${params.name} varies by patient factors and treatment.`,
    timelineSteps: [],
    prognosis: `Prognosis depends on stage at diagnosis and response to treatment.`,
  };

  const defaultAnatomyMapping: ConditionAnatomyMapping = {
    primaryStructures: [],
    systemsInvolved: params.systems,
    recommendedView: 'anterior',
    recommendedLayers: ['organs'],
  };

  return {
    conditionId: params.conditionId,
    name: params.name,
    icdCode: params.icdCode,
    category: params.category,
    description: params.description,
    pathophysiology: defaultPathophysiology,
    clinicalPresentation: defaultPresentation,
    progression: defaultProgression,
    complications: [],
    treatmentOptions: [],
    anatomyMapping: defaultAnatomyMapping,
    explanations: defaultExplanations,
  };
}

// ============================================
// ICD-11 Condition Index (300+ entries)
// Covers all major ICD-11 chapters
// ============================================

export const ICD11_CONDITIONS: ICD11ConditionEntry[] = [
  // ── Chapter 01: Certain infectious or parasitic diseases (1A00–1H0Z) ──
  {id:'cholera',name:'Cholera',icd:'1A00',cat:'infectious',desc:'Acute diarrheal infection caused by Vibrio cholerae',sys:['gastrointestinal']},
  {id:'typhoid-fever',name:'Typhoid Fever',icd:'1A01',cat:'infectious',desc:'Systemic infection caused by Salmonella typhi with sustained fever',sys:['gastrointestinal','immunologic']},
  {id:'shigellosis',name:'Shigellosis',icd:'1A03',cat:'infectious',desc:'Bacterial dysentery caused by Shigella species',sys:['gastrointestinal']},
  {id:'tuberculosis-pulmonary',name:'Pulmonary Tuberculosis',icd:'1B10',cat:'infectious',desc:'Chronic bacterial lung infection caused by Mycobacterium tuberculosis',sys:['respiratory']},
  {id:'tuberculosis-miliary',name:'Miliary Tuberculosis',icd:'1B14',cat:'infectious',desc:'Disseminated tuberculosis with widespread hematogenous spread',sys:['respiratory','immunologic']},
  {id:'plague',name:'Plague',icd:'1B93',cat:'infectious',desc:'Severe bacterial infection caused by Yersinia pestis',sys:['immunologic','respiratory']},
  {id:'tetanus',name:'Tetanus',icd:'1C13',cat:'infectious',desc:'Acute neuromuscular disease caused by Clostridium tetani toxin',sys:['neurologic','musculoskeletal']},
  {id:'diphtheria',name:'Diphtheria',icd:'1C14',cat:'infectious',desc:'Upper respiratory tract infection caused by Corynebacterium diphtheriae',sys:['respiratory']},
  {id:'pertussis',name:'Pertussis',icd:'1C12',cat:'infectious',desc:'Highly contagious respiratory infection with severe paroxysmal cough',sys:['respiratory']},
  {id:'meningococcal-meningitis',name:'Meningococcal Meningitis',icd:'1C1C',cat:'infectious',desc:'Bacterial meningitis caused by Neisseria meningitidis',sys:['neurologic']},
  {id:'sepsis',name:'Sepsis',icd:'1G40',cat:'infectious',desc:'Life-threatening organ dysfunction caused by dysregulated host response to infection',sys:['immunologic','cardiovascular']},
  {id:'malaria',name:'Malaria',icd:'1F40',cat:'infectious',desc:'Parasitic disease transmitted by Anopheles mosquitoes causing cyclical fevers',sys:['hematologic','immunologic']},
  {id:'leishmaniasis',name:'Leishmaniasis',icd:'1F50',cat:'infectious',desc:'Parasitic disease transmitted by sandflies affecting skin or viscera',sys:['immunologic','dermatologic']},
  {id:'chagas-disease',name:'Chagas Disease',icd:'1F51',cat:'infectious',desc:'Parasitic infection by Trypanosoma cruzi affecting heart and GI tract',sys:['cardiovascular','gastrointestinal']},
  {id:'schistosomiasis',name:'Schistosomiasis',icd:'1F80',cat:'infectious',desc:'Parasitic disease caused by blood flukes with hepatic and urinary involvement',sys:['gastrointestinal','urologic']},
  {id:'hiv-aids',name:'HIV/AIDS',icd:'1C60',cat:'infectious',desc:'Chronic immunodeficiency caused by human immunodeficiency virus',sys:['immunologic']},
  {id:'hepatitis-b',name:'Hepatitis B',icd:'1E50',cat:'infectious',desc:'Viral hepatitis caused by hepatitis B virus with potential chronicity',sys:['gastrointestinal']},
  {id:'hepatitis-c',name:'Hepatitis C',icd:'1E51',cat:'infectious',desc:'Chronic viral hepatitis caused by hepatitis C virus leading to liver fibrosis',sys:['gastrointestinal']},
  {id:'dengue',name:'Dengue Fever',icd:'1D20',cat:'infectious',desc:'Mosquito-borne viral infection with fever and potential hemorrhagic complications',sys:['hematologic','immunologic']},
  {id:'rabies',name:'Rabies',icd:'1D80',cat:'infectious',desc:'Fatal viral encephalitis transmitted through animal bites',sys:['neurologic']},
  {id:'measles',name:'Measles',icd:'1D80',cat:'infectious',desc:'Highly contagious viral illness with fever, rash, and respiratory symptoms',sys:['respiratory','immunologic','dermatologic']},
  {id:'rubella',name:'Rubella',icd:'1F02',cat:'infectious',desc:'Viral infection with mild rash illness but severe congenital effects',sys:['dermatologic','immunologic']},
  {id:'influenza',name:'Influenza',icd:'1E30',cat:'infectious',desc:'Acute viral respiratory infection with systemic symptoms',sys:['respiratory']},
  {id:'covid-19',name:'COVID-19',icd:'RA01',cat:'infectious',desc:'Respiratory illness caused by SARS-CoV-2 with multi-system involvement',sys:['respiratory','cardiovascular','immunologic']},
  {id:'candidiasis',name:'Candidiasis',icd:'1F23',cat:'infectious',desc:'Fungal infection caused by Candida species affecting mucous membranes or systemic',sys:['immunologic','dermatologic']},
  {id:'aspergillosis',name:'Aspergillosis',icd:'1F20',cat:'infectious',desc:'Fungal infection caused by Aspergillus species primarily affecting lungs',sys:['respiratory','immunologic']},
  {id:'cellulitis',name:'Cellulitis',icd:'1B70',cat:'infectious',desc:'Acute spreading bacterial infection of skin and subcutaneous tissue',sys:['dermatologic','immunologic']},
  {id:'osteomyelitis',name:'Osteomyelitis',icd:'1C40',cat:'infectious',desc:'Bone infection usually caused by bacteria leading to bone destruction',sys:['musculoskeletal','immunologic']},
  {id:'endocarditis-infective',name:'Infective Endocarditis',icd:'1C41',cat:'infectious',desc:'Infection of heart valve endocardium usually by bacteria',sys:['cardiovascular','immunologic']},
  {id:'lyme-disease',name:'Lyme Disease',icd:'1C1G',cat:'infectious',desc:'Tick-borne illness caused by Borrelia burgdorferi with multisystem involvement',sys:['musculoskeletal','neurologic','dermatologic']},
  // ── Chapter 02: Neoplasms (2A00–2F9Z) ──
  {id:'lung-cancer',name:'Lung Cancer',icd:'2C25',cat:'oncologic',desc:'Primary malignant neoplasm of the bronchus or lung',sys:['respiratory']},
  {id:'breast-cancer',name:'Breast Cancer',icd:'2C6B',cat:'oncologic',desc:'Malignant neoplasm of the breast',sys:['immunologic']},
  {id:'colorectal-cancer',name:'Colorectal Cancer',icd:'2B90',cat:'oncologic',desc:'Malignant neoplasm of the colon or rectum',sys:['gastrointestinal']},
  {id:'prostate-cancer',name:'Prostate Cancer',icd:'2C82',cat:'oncologic',desc:'Malignant neoplasm of the prostate gland',sys:['urologic']},
  {id:'pancreatic-cancer',name:'Pancreatic Cancer',icd:'2C10',cat:'oncologic',desc:'Malignant neoplasm of the pancreas with poor prognosis',sys:['gastrointestinal','endocrine']},
  {id:'liver-cancer',name:'Hepatocellular Carcinoma',icd:'2C12',cat:'oncologic',desc:'Primary malignant neoplasm of the liver',sys:['gastrointestinal']},
  {id:'stomach-cancer',name:'Gastric Cancer',icd:'2B70',cat:'oncologic',desc:'Malignant neoplasm of the stomach',sys:['gastrointestinal']},
  {id:'esophageal-cancer',name:'Esophageal Cancer',icd:'2B60',cat:'oncologic',desc:'Malignant neoplasm of the esophagus',sys:['gastrointestinal']},
  {id:'cervical-cancer',name:'Cervical Cancer',icd:'2C77',cat:'oncologic',desc:'Malignant neoplasm of the uterine cervix often associated with HPV',sys:['immunologic']},
  {id:'ovarian-cancer',name:'Ovarian Cancer',icd:'2C73',cat:'oncologic',desc:'Malignant neoplasm of the ovary with late-stage presentation',sys:['immunologic','endocrine']},
  {id:'bladder-cancer',name:'Bladder Cancer',icd:'2C94',cat:'oncologic',desc:'Malignant neoplasm of the urinary bladder',sys:['urologic']},
  {id:'renal-cell-carcinoma',name:'Renal Cell Carcinoma',icd:'2C90',cat:'oncologic',desc:'Malignant neoplasm originating from renal tubular epithelium',sys:['urologic']},
  {id:'melanoma',name:'Melanoma',icd:'2D4Z',cat:'oncologic',desc:'Malignant neoplasm arising from melanocytes in the skin',sys:['dermatologic']},
  {id:'basal-cell-carcinoma',name:'Basal Cell Carcinoma',icd:'2D40',cat:'oncologic',desc:'Most common skin cancer arising from basal cells with local invasion',sys:['dermatologic']},
  {id:'squamous-cell-carcinoma-skin',name:'Squamous Cell Carcinoma of Skin',icd:'2D41',cat:'oncologic',desc:'Skin cancer arising from squamous epithelial cells',sys:['dermatologic']},
  {id:'leukemia-aml',name:'Acute Myeloid Leukemia',icd:'2A60',cat:'oncologic',desc:'Aggressive hematologic malignancy of myeloid cell lineage',sys:['hematologic']},
  {id:'leukemia-all',name:'Acute Lymphoblastic Leukemia',icd:'2A80',cat:'oncologic',desc:'Hematologic malignancy of lymphoid precursor cells',sys:['hematologic']},
  {id:'leukemia-cml',name:'Chronic Myeloid Leukemia',icd:'2A20',cat:'oncologic',desc:'Myeloproliferative neoplasm with Philadelphia chromosome',sys:['hematologic']},
  {id:'leukemia-cll',name:'Chronic Lymphocytic Leukemia',icd:'2A81',cat:'oncologic',desc:'Indolent B-cell lymphoproliferative disorder',sys:['hematologic']},
  {id:'lymphoma-hodgkin',name:'Hodgkin Lymphoma',icd:'2B30',cat:'oncologic',desc:'Lymphoid neoplasm with Reed-Sternberg cells',sys:['hematologic','immunologic']},
  {id:'lymphoma-non-hodgkin',name:'Non-Hodgkin Lymphoma',icd:'2B33',cat:'oncologic',desc:'Diverse group of lymphoid malignancies excluding Hodgkin lymphoma',sys:['hematologic','immunologic']},
  {id:'multiple-myeloma',name:'Multiple Myeloma',icd:'2A83',cat:'oncologic',desc:'Plasma cell neoplasm causing bone destruction and renal failure',sys:['hematologic','musculoskeletal']},
  {id:'glioblastoma',name:'Glioblastoma',icd:'2A00',cat:'oncologic',desc:'Aggressive primary brain tumor from glial cells',sys:['neurologic']},
  {id:'thyroid-cancer',name:'Thyroid Cancer',icd:'2D10',cat:'oncologic',desc:'Malignant neoplasm of the thyroid gland',sys:['endocrine']},
  {id:'head-neck-cancer',name:'Head and Neck Squamous Cell Carcinoma',icd:'2C00',cat:'oncologic',desc:'Squamous cell carcinoma of oral cavity, pharynx, or larynx',sys:['respiratory']},
  {id:'mesothelioma',name:'Mesothelioma',icd:'2C29',cat:'oncologic',desc:'Malignant neoplasm of pleural or peritoneal mesothelium from asbestos exposure',sys:['respiratory']},
  {id:'testicular-cancer',name:'Testicular Cancer',icd:'2C80',cat:'oncologic',desc:'Germ cell tumor of the testis with high cure rate',sys:['urologic']},
  {id:'endometrial-cancer',name:'Endometrial Cancer',icd:'2C76',cat:'oncologic',desc:'Malignant neoplasm of the uterine endometrium',sys:['immunologic']},
  // ── Chapter 03: Diseases of the blood or blood-forming organs (3A00–3C0Z) ──
  {id:'iron-deficiency-anemia',name:'Iron Deficiency Anemia',icd:'3A00',cat:'hematologic',desc:'Anemia resulting from insufficient iron for hemoglobin synthesis',sys:['hematologic']},
  {id:'vitamin-b12-deficiency-anemia',name:'Vitamin B12 Deficiency Anemia',icd:'3A01',cat:'hematologic',desc:'Megaloblastic anemia from B12 deficiency causing impaired DNA synthesis',sys:['hematologic','neurologic']},
  {id:'folate-deficiency-anemia',name:'Folate Deficiency Anemia',icd:'3A02',cat:'hematologic',desc:'Megaloblastic anemia from folate deficiency',sys:['hematologic']},
  {id:'sickle-cell-disease',name:'Sickle Cell Disease',icd:'3A51',cat:'hematologic',desc:'Hereditary hemoglobinopathy causing vaso-occlusive crises and hemolysis',sys:['hematologic']},
  {id:'thalassemia',name:'Thalassemia',icd:'3A50',cat:'hematologic',desc:'Inherited hemoglobin disorder with reduced globin chain synthesis',sys:['hematologic']},
  {id:'hemophilia-a',name:'Hemophilia A',icd:'3B10',cat:'hematologic',desc:'X-linked bleeding disorder from factor VIII deficiency',sys:['hematologic']},
  {id:'hemophilia-b',name:'Hemophilia B',icd:'3B11',cat:'hematologic',desc:'X-linked bleeding disorder from factor IX deficiency',sys:['hematologic']},
  {id:'von-willebrand-disease',name:'Von Willebrand Disease',icd:'3B12',cat:'hematologic',desc:'Most common inherited bleeding disorder from vWF deficiency',sys:['hematologic']},
  {id:'thrombocytopenia',name:'Thrombocytopenia',icd:'3B60',cat:'hematologic',desc:'Low platelet count causing increased bleeding risk',sys:['hematologic']},
  {id:'disseminated-intravascular-coagulation',name:'Disseminated Intravascular Coagulation',icd:'3B20',cat:'hematologic',desc:'Pathological activation of coagulation with simultaneous bleeding and thrombosis',sys:['hematologic']},
  {id:'aplastic-anemia',name:'Aplastic Anemia',icd:'3A70',cat:'hematologic',desc:'Bone marrow failure with pancytopenia from stem cell destruction',sys:['hematologic','immunologic']},
  {id:'polycythemia-vera',name:'Polycythemia Vera',icd:'3A20',cat:'hematologic',desc:'Myeloproliferative neoplasm with increased red cell mass',sys:['hematologic']},
  {id:'deep-vein-thrombosis',name:'Deep Vein Thrombosis',icd:'3B82',cat:'hematologic',desc:'Blood clot formation in deep veins usually of lower extremities',sys:['hematologic','cardiovascular']},
  {id:'pulmonary-embolism',name:'Pulmonary Embolism',icd:'3B83',cat:'hematologic',desc:'Occlusion of pulmonary arteries by thromboemboli',sys:['hematologic','respiratory','cardiovascular']},
  // ── Chapter 04: Diseases of the immune system (4A00–4B4Z) ──
  {id:'systemic-lupus-erythematosus',name:'Systemic Lupus Erythematosus',icd:'4A40',cat:'immunologic',desc:'Chronic multisystem autoimmune disease with autoantibody production',sys:['immunologic','musculoskeletal','dermatologic']},
  {id:'rheumatoid-arthritis',name:'Rheumatoid Arthritis',icd:'FA20',cat:'immunologic',desc:'Chronic autoimmune inflammatory arthritis affecting synovial joints',sys:['immunologic','musculoskeletal']},
  {id:'sjogren-syndrome',name:'Sjogren Syndrome',icd:'4A41',cat:'immunologic',desc:'Autoimmune disease targeting exocrine glands causing dryness',sys:['immunologic']},
  {id:'scleroderma',name:'Systemic Sclerosis (Scleroderma)',icd:'4A42',cat:'immunologic',desc:'Autoimmune connective tissue disease with skin and organ fibrosis',sys:['immunologic','dermatologic','respiratory']},
  {id:'anaphylaxis',name:'Anaphylaxis',icd:'4A80',cat:'immunologic',desc:'Severe systemic allergic reaction with potential cardiovascular collapse',sys:['immunologic','cardiovascular','respiratory']},
  {id:'common-variable-immunodeficiency',name:'Common Variable Immunodeficiency',icd:'4A01',cat:'immunologic',desc:'Primary immunodeficiency with low immunoglobulins and recurrent infections',sys:['immunologic']},
  {id:'sarcoidosis',name:'Sarcoidosis',icd:'4B20',cat:'immunologic',desc:'Multisystem granulomatous disease of unknown etiology',sys:['immunologic','respiratory']},
  {id:'allergic-rhinitis',name:'Allergic Rhinitis',icd:'CA08',cat:'immunologic',desc:'IgE-mediated nasal inflammation triggered by environmental allergens',sys:['immunologic','respiratory']},
  {id:'celiac-disease',name:'Celiac Disease',icd:'DA95',cat:'immunologic',desc:'Autoimmune enteropathy triggered by gluten ingestion',sys:['immunologic','gastrointestinal']},
  // ── Chapter 05: Endocrine, nutritional, or metabolic diseases (5A00–5D0Z) ──
  {id:'type-1-diabetes',name:'Type 1 Diabetes Mellitus',icd:'5A10',cat:'endocrine',desc:'Autoimmune destruction of pancreatic beta cells causing insulin deficiency',sys:['endocrine','immunologic']},
  {id:'type-2-diabetes',name:'Type 2 Diabetes Mellitus',icd:'5A11',cat:'metabolic',desc:'Progressive insulin resistance and beta cell dysfunction',sys:['endocrine','metabolic','cardiovascular']},
  {id:'gestational-diabetes',name:'Gestational Diabetes Mellitus',icd:'5A12',cat:'endocrine',desc:'Glucose intolerance first recognized during pregnancy',sys:['endocrine']},
  {id:'diabetic-ketoacidosis',name:'Diabetic Ketoacidosis',icd:'5A20',cat:'metabolic',desc:'Acute metabolic emergency with hyperglycemia ketosis and acidosis',sys:['endocrine','metabolic']},
  {id:'hyperthyroidism',name:'Hyperthyroidism',icd:'5A00',cat:'endocrine',desc:'Excessive thyroid hormone production causing hypermetabolic state',sys:['endocrine']},
  {id:'hypothyroidism',name:'Hypothyroidism',icd:'5A01',cat:'endocrine',desc:'Insufficient thyroid hormone production causing hypometabolic state',sys:['endocrine']},
  {id:'graves-disease',name:'Graves Disease',icd:'5A02',cat:'endocrine',desc:'Autoimmune hyperthyroidism with TSH receptor antibodies',sys:['endocrine','immunologic']},
  {id:'hashimoto-thyroiditis',name:'Hashimoto Thyroiditis',icd:'5A03',cat:'endocrine',desc:'Autoimmune thyroiditis leading to progressive hypothyroidism',sys:['endocrine','immunologic']},
  {id:'cushing-syndrome',name:'Cushing Syndrome',icd:'5A70',cat:'endocrine',desc:'Hypercortisolism causing central obesity, hypertension, and metabolic derangements',sys:['endocrine']},
  {id:'addison-disease',name:'Addison Disease',icd:'5A74',cat:'endocrine',desc:'Primary adrenal insufficiency with cortisol and aldosterone deficiency',sys:['endocrine']},
  {id:'pheochromocytoma',name:'Pheochromocytoma',icd:'5A75',cat:'endocrine',desc:'Catecholamine-secreting tumor of adrenal medulla causing paroxysmal hypertension',sys:['endocrine','cardiovascular']},
  {id:'hyperparathyroidism',name:'Hyperparathyroidism',icd:'5A50',cat:'endocrine',desc:'Excess parathyroid hormone causing hypercalcemia and bone resorption',sys:['endocrine','musculoskeletal']},
  {id:'hypoparathyroidism',name:'Hypoparathyroidism',icd:'5A51',cat:'endocrine',desc:'Deficient parathyroid hormone causing hypocalcemia',sys:['endocrine']},
  {id:'acromegaly',name:'Acromegaly',icd:'5A60',cat:'endocrine',desc:'Growth hormone excess in adults from pituitary adenoma',sys:['endocrine','musculoskeletal']},
  {id:'hypopituitarism',name:'Hypopituitarism',icd:'5A61',cat:'endocrine',desc:'Deficiency of one or more pituitary hormones',sys:['endocrine']},
  {id:'diabetes-insipidus',name:'Diabetes Insipidus',icd:'5A63',cat:'endocrine',desc:'Impaired water reabsorption due to ADH deficiency or resistance',sys:['endocrine','urologic']},
  {id:'obesity',name:'Obesity',icd:'5B80',cat:'metabolic',desc:'Excessive body fat accumulation with multisystem metabolic consequences',sys:['metabolic','cardiovascular','endocrine']},
  {id:'metabolic-syndrome',name:'Metabolic Syndrome',icd:'5B81',cat:'metabolic',desc:'Cluster of cardiovascular risk factors including central obesity and insulin resistance',sys:['metabolic','cardiovascular','endocrine']},
  {id:'hyperlipidemia',name:'Hyperlipidemia',icd:'5C80',cat:'metabolic',desc:'Elevated blood lipids increasing atherosclerotic cardiovascular risk',sys:['metabolic','cardiovascular']},
  {id:'gout',name:'Gout',icd:'5C55',cat:'metabolic',desc:'Crystal arthropathy from monosodium urate deposition in joints',sys:['metabolic','musculoskeletal']},
  {id:'phenylketonuria',name:'Phenylketonuria',icd:'5C50',cat:'metabolic',desc:'Inborn error of phenylalanine metabolism causing intellectual disability if untreated',sys:['metabolic','neurologic']},
  {id:'wilsons-disease',name:'Wilson Disease',icd:'5C64',cat:'metabolic',desc:'Copper metabolism disorder causing hepatic and neurologic damage',sys:['metabolic','gastrointestinal','neurologic']},
  {id:'hemochromatosis',name:'Hemochromatosis',icd:'5C64',cat:'metabolic',desc:'Iron overload disorder with multiorgan iron deposition',sys:['metabolic','gastrointestinal']},
  {id:'vitamin-d-deficiency',name:'Vitamin D Deficiency',icd:'5B70',cat:'metabolic',desc:'Insufficient vitamin D causing impaired calcium homeostasis and bone mineralization',sys:['metabolic','musculoskeletal']},
  {id:'malnutrition-protein-energy',name:'Protein-Energy Malnutrition',icd:'5B20',cat:'metabolic',desc:'Severe nutritional deficiency of protein and calories',sys:['metabolic']},
  // ── Chapter 06: Mental, behavioural, or neurodevelopmental disorders (6A00–6E8Z) ──
  {id:'major-depressive-disorder',name:'Major Depressive Disorder',icd:'6A70',cat:'psychiatric',desc:'Persistent depressed mood with anhedonia and neurovegetative symptoms',sys:['neurologic']},
  {id:'bipolar-disorder',name:'Bipolar Disorder',icd:'6A60',cat:'psychiatric',desc:'Mood disorder with alternating manic and depressive episodes',sys:['neurologic']},
  {id:'generalized-anxiety-disorder',name:'Generalized Anxiety Disorder',icd:'6B00',cat:'psychiatric',desc:'Excessive persistent worry with somatic anxiety symptoms',sys:['neurologic']},
  {id:'panic-disorder',name:'Panic Disorder',icd:'6B01',cat:'psychiatric',desc:'Recurrent unexpected panic attacks with anticipatory anxiety',sys:['neurologic','cardiovascular']},
  {id:'ptsd',name:'Post-Traumatic Stress Disorder',icd:'6B40',cat:'psychiatric',desc:'Trauma-related disorder with re-experiencing avoidance and hyperarousal',sys:['neurologic']},
  {id:'ocd',name:'Obsessive-Compulsive Disorder',icd:'6B20',cat:'psychiatric',desc:'Disorder with intrusive obsessions and repetitive compulsive behaviors',sys:['neurologic']},
  {id:'schizophrenia',name:'Schizophrenia',icd:'6A20',cat:'psychiatric',desc:'Chronic psychotic disorder with delusions hallucinations and cognitive dysfunction',sys:['neurologic']},
  {id:'adhd',name:'Attention Deficit Hyperactivity Disorder',icd:'6A05',cat:'psychiatric',desc:'Neurodevelopmental disorder with inattention hyperactivity and impulsivity',sys:['neurologic']},
  {id:'autism-spectrum-disorder',name:'Autism Spectrum Disorder',icd:'6A02',cat:'psychiatric',desc:'Neurodevelopmental disorder affecting social communication and behavior',sys:['neurologic']},
  {id:'anorexia-nervosa',name:'Anorexia Nervosa',icd:'6B80',cat:'psychiatric',desc:'Eating disorder with restrictive intake and distorted body image',sys:['neurologic','metabolic']},
  {id:'bulimia-nervosa',name:'Bulimia Nervosa',icd:'6B81',cat:'psychiatric',desc:'Eating disorder with binge eating and compensatory purging',sys:['neurologic','gastrointestinal']},
  {id:'substance-use-alcohol',name:'Alcohol Use Disorder',icd:'6C40',cat:'psychiatric',desc:'Problematic alcohol consumption with dependence and withdrawal',sys:['neurologic','gastrointestinal']},
  {id:'substance-use-opioid',name:'Opioid Use Disorder',icd:'6C43',cat:'psychiatric',desc:'Problematic opioid use with tolerance dependence and withdrawal',sys:['neurologic']},
  {id:'insomnia',name:'Insomnia Disorder',icd:'7A00',cat:'psychiatric',desc:'Persistent difficulty with sleep initiation or maintenance',sys:['neurologic']},
  // ── Chapter 08: Diseases of the nervous system (8A00–8E7Z) ──
  {id:'alzheimers-disease',name:'Alzheimer Disease',icd:'8A20',cat:'neurologic',desc:'Progressive neurodegenerative dementia with amyloid and tau pathology',sys:['neurologic']},
  {id:'parkinsons-disease',name:'Parkinson Disease',icd:'8A00',cat:'neurologic',desc:'Neurodegenerative movement disorder with dopaminergic neuron loss',sys:['neurologic']},
  {id:'multiple-sclerosis',name:'Multiple Sclerosis',icd:'8A40',cat:'neurologic',desc:'Autoimmune demyelinating disease of the central nervous system',sys:['neurologic','immunologic']},
  {id:'epilepsy',name:'Epilepsy',icd:'8A60',cat:'neurologic',desc:'Chronic neurologic disorder with recurrent unprovoked seizures',sys:['neurologic']},
  {id:'migraine',name:'Migraine',icd:'8A80',cat:'neurologic',desc:'Primary headache disorder with recurrent moderate to severe attacks',sys:['neurologic']},
  {id:'tension-headache',name:'Tension-Type Headache',icd:'8A81',cat:'neurologic',desc:'Most common primary headache with bilateral pressing quality',sys:['neurologic']},
  {id:'stroke-ischemic',name:'Ischemic Stroke',icd:'8B10',cat:'neurologic',desc:'Acute cerebral infarction from arterial occlusion',sys:['neurologic','cardiovascular']},
  {id:'stroke-hemorrhagic',name:'Hemorrhagic Stroke',icd:'8B00',cat:'neurologic',desc:'Intracerebral hemorrhage causing acute neurologic deficit',sys:['neurologic','cardiovascular']},
  {id:'subarachnoid-hemorrhage',name:'Subarachnoid Hemorrhage',icd:'8B01',cat:'neurologic',desc:'Bleeding into subarachnoid space usually from ruptured aneurysm',sys:['neurologic','cardiovascular']},
  {id:'als',name:'Amyotrophic Lateral Sclerosis',icd:'8B60',cat:'neurologic',desc:'Progressive motor neuron disease causing muscle weakness and atrophy',sys:['neurologic','musculoskeletal']},
  {id:'huntingtons-disease',name:'Huntington Disease',icd:'8A01',cat:'neurologic',desc:'Autosomal dominant neurodegenerative disorder with chorea and dementia',sys:['neurologic']},
  {id:'myasthenia-gravis',name:'Myasthenia Gravis',icd:'8C60',cat:'neurologic',desc:'Autoimmune disorder of neuromuscular junction causing fatigable weakness',sys:['neurologic','musculoskeletal','immunologic']},
  {id:'guillain-barre-syndrome',name:'Guillain-Barre Syndrome',icd:'8C40',cat:'neurologic',desc:'Acute inflammatory demyelinating polyneuropathy with ascending paralysis',sys:['neurologic','immunologic']},
  {id:'trigeminal-neuralgia',name:'Trigeminal Neuralgia',icd:'8B82',cat:'neurologic',desc:'Severe paroxysmal facial pain in trigeminal nerve distribution',sys:['neurologic']},
  {id:'bell-palsy',name:'Bell Palsy',icd:'8C80',cat:'neurologic',desc:'Acute unilateral facial nerve paralysis of unknown cause',sys:['neurologic']},
  {id:'carpal-tunnel-syndrome',name:'Carpal Tunnel Syndrome',icd:'8C50',cat:'neurologic',desc:'Median nerve entrapment at the wrist causing hand numbness and weakness',sys:['neurologic','musculoskeletal']},
  {id:'peripheral-neuropathy',name:'Peripheral Neuropathy',icd:'8C00',cat:'neurologic',desc:'Damage to peripheral nerves causing sensory and motor dysfunction',sys:['neurologic']},
  {id:'meningitis-viral',name:'Viral Meningitis',icd:'8A61',cat:'neurologic',desc:'Inflammation of the meninges caused by viral infection',sys:['neurologic','immunologic']},
  {id:'encephalitis',name:'Encephalitis',icd:'8A62',cat:'neurologic',desc:'Inflammation of the brain parenchyma usually from viral infection',sys:['neurologic','immunologic']},
  {id:'cerebral-palsy',name:'Cerebral Palsy',icd:'8D20',cat:'neurologic',desc:'Group of permanent movement disorders from early brain development injury',sys:['neurologic','musculoskeletal']},
  {id:'spinal-cord-injury',name:'Spinal Cord Injury',icd:'8C70',cat:'neurologic',desc:'Traumatic or non-traumatic damage to the spinal cord causing paralysis',sys:['neurologic','musculoskeletal']},
  {id:'dementia-vascular',name:'Vascular Dementia',icd:'8A21',cat:'neurologic',desc:'Cognitive decline caused by cerebrovascular disease',sys:['neurologic','cardiovascular']},
  // ── Chapter 09: Diseases of the visual system ──
  {id:'glaucoma',name:'Glaucoma',icd:'9C61',cat:'neurologic',desc:'Optic neuropathy with progressive visual field loss often with elevated IOP',sys:['neurologic']},
  {id:'cataracts',name:'Cataracts',icd:'9B10',cat:'neurologic',desc:'Opacification of the crystalline lens causing visual impairment',sys:['neurologic']},
  {id:'macular-degeneration',name:'Age-Related Macular Degeneration',icd:'9B70',cat:'neurologic',desc:'Progressive degeneration of the macula causing central vision loss',sys:['neurologic']},
  {id:'diabetic-retinopathy',name:'Diabetic Retinopathy',icd:'9B71',cat:'neurologic',desc:'Microvascular damage to the retina from chronic hyperglycemia',sys:['neurologic','endocrine']},
  // ── Chapter 11: Diseases of the circulatory system (BA00–BE2Z) ──
  {id:'hypertension',name:'Essential Hypertension',icd:'BA00',cat:'cardiovascular',desc:'Chronically elevated systemic arterial blood pressure',sys:['cardiovascular']},
  {id:'hypertensive-heart-disease',name:'Hypertensive Heart Disease',icd:'BA01',cat:'cardiovascular',desc:'Cardiac complications of chronic hypertension including LVH',sys:['cardiovascular']},
  {id:'coronary-artery-disease',name:'Coronary Artery Disease',icd:'BA80',cat:'cardiovascular',desc:'Atherosclerotic narrowing of coronary arteries reducing myocardial perfusion',sys:['cardiovascular']},
  {id:'acute-mi-stemi',name:'ST-Elevation Myocardial Infarction',icd:'BA41',cat:'cardiovascular',desc:'Acute transmural myocardial infarction with ST elevation on ECG',sys:['cardiovascular']},
  {id:'acute-mi-nstemi',name:'Non-ST-Elevation Myocardial Infarction',icd:'BA42',cat:'cardiovascular',desc:'Acute myocardial infarction without persistent ST elevation',sys:['cardiovascular']},
  {id:'unstable-angina',name:'Unstable Angina',icd:'BA40',cat:'cardiovascular',desc:'Acute coronary syndrome without myocardial necrosis markers',sys:['cardiovascular']},
  {id:'heart-failure-hfref',name:'Heart Failure with Reduced Ejection Fraction',icd:'BD10',cat:'cardiovascular',desc:'Systolic heart failure with LVEF less than 40 percent',sys:['cardiovascular']},
  {id:'heart-failure-hfpef',name:'Heart Failure with Preserved Ejection Fraction',icd:'BD11',cat:'cardiovascular',desc:'Diastolic heart failure with preserved LVEF and impaired relaxation',sys:['cardiovascular']},
  {id:'atrial-fibrillation',name:'Atrial Fibrillation',icd:'BC80',cat:'cardiovascular',desc:'Most common sustained cardiac arrhythmia with irregular atrial activation',sys:['cardiovascular']},
  {id:'atrial-flutter',name:'Atrial Flutter',icd:'BC81',cat:'cardiovascular',desc:'Macro-reentrant atrial tachycardia with sawtooth flutter waves',sys:['cardiovascular']},
  {id:'ventricular-tachycardia',name:'Ventricular Tachycardia',icd:'BC82',cat:'cardiovascular',desc:'Rapid heart rhythm originating from the ventricles',sys:['cardiovascular']},
  {id:'aortic-stenosis',name:'Aortic Stenosis',icd:'BB40',cat:'cardiovascular',desc:'Narrowing of aortic valve orifice obstructing left ventricular outflow',sys:['cardiovascular']},
  {id:'aortic-regurgitation',name:'Aortic Regurgitation',icd:'BB41',cat:'cardiovascular',desc:'Incompetent aortic valve causing diastolic backflow into left ventricle',sys:['cardiovascular']},
  {id:'mitral-stenosis',name:'Mitral Stenosis',icd:'BB42',cat:'cardiovascular',desc:'Narrowing of mitral valve orifice obstructing left atrial emptying',sys:['cardiovascular']},
  {id:'mitral-regurgitation',name:'Mitral Regurgitation',icd:'BB43',cat:'cardiovascular',desc:'Incompetent mitral valve causing systolic backflow into left atrium',sys:['cardiovascular']},
  {id:'mitral-valve-prolapse',name:'Mitral Valve Prolapse',icd:'BB44',cat:'cardiovascular',desc:'Billowing of mitral valve leaflets into left atrium during systole',sys:['cardiovascular']},
  {id:'aortic-aneurysm',name:'Aortic Aneurysm',icd:'BD50',cat:'cardiovascular',desc:'Focal dilation of the aorta with risk of rupture',sys:['cardiovascular']},
  {id:'aortic-dissection',name:'Aortic Dissection',icd:'BD51',cat:'cardiovascular',desc:'Tear in aortic intima with blood tracking through the media',sys:['cardiovascular']},
  {id:'peripheral-artery-disease',name:'Peripheral Artery Disease',icd:'BD40',cat:'cardiovascular',desc:'Atherosclerotic obstruction of peripheral arteries causing claudication',sys:['cardiovascular']},
  {id:'pericarditis',name:'Pericarditis',icd:'BB00',cat:'cardiovascular',desc:'Inflammation of the pericardium causing chest pain and friction rub',sys:['cardiovascular']},
  {id:'myocarditis',name:'Myocarditis',icd:'BB01',cat:'cardiovascular',desc:'Inflammatory disease of the myocardium often viral in origin',sys:['cardiovascular','immunologic']},
  {id:'dilated-cardiomyopathy',name:'Dilated Cardiomyopathy',icd:'BC40',cat:'cardiovascular',desc:'Ventricular dilation and impaired systolic function without coronary disease',sys:['cardiovascular']},
  {id:'hypertrophic-cardiomyopathy',name:'Hypertrophic Cardiomyopathy',icd:'BC41',cat:'cardiovascular',desc:'Inherited cardiac hypertrophy with potential outflow obstruction',sys:['cardiovascular']},
  {id:'cardiac-tamponade',name:'Cardiac Tamponade',icd:'BB02',cat:'cardiovascular',desc:'Pericardial fluid accumulation compromising cardiac filling',sys:['cardiovascular']},
  {id:'varicose-veins',name:'Varicose Veins',icd:'BD80',cat:'cardiovascular',desc:'Dilated tortuous superficial veins from venous valve incompetence',sys:['cardiovascular']},
  {id:'raynaud-phenomenon',name:'Raynaud Phenomenon',icd:'BD30',cat:'cardiovascular',desc:'Vasospastic disorder causing digital ischemia with color changes',sys:['cardiovascular']},
  // ── Chapter 12: Diseases of the respiratory system (CA00–CB8Z) ──
  {id:'asthma',name:'Asthma',icd:'CA23',cat:'respiratory',desc:'Chronic airway inflammation with reversible bronchoconstriction and hyperresponsiveness',sys:['respiratory','immunologic']},
  {id:'copd',name:'Chronic Obstructive Pulmonary Disease',icd:'CA22',cat:'respiratory',desc:'Progressive airflow limitation from chronic bronchitis and emphysema',sys:['respiratory']},
  {id:'emphysema',name:'Emphysema',icd:'CA21',cat:'respiratory',desc:'Destruction of alveolar walls causing air trapping and hyperinflation',sys:['respiratory']},
  {id:'chronic-bronchitis',name:'Chronic Bronchitis',icd:'CA20',cat:'respiratory',desc:'Chronic productive cough with airway mucus hypersecretion',sys:['respiratory']},
  {id:'pneumonia-bacterial',name:'Bacterial Pneumonia',icd:'CA40',cat:'respiratory',desc:'Acute lower respiratory tract infection with alveolar consolidation',sys:['respiratory']},
  {id:'pneumonia-viral',name:'Viral Pneumonia',icd:'CA41',cat:'respiratory',desc:'Lung infection caused by respiratory viruses with interstitial inflammation',sys:['respiratory']},
  {id:'pneumothorax',name:'Pneumothorax',icd:'CB20',cat:'respiratory',desc:'Air in the pleural space causing lung collapse',sys:['respiratory']},
  {id:'pleural-effusion',name:'Pleural Effusion',icd:'CB01',cat:'respiratory',desc:'Fluid accumulation in the pleural space',sys:['respiratory']},
  {id:'pulmonary-fibrosis',name:'Idiopathic Pulmonary Fibrosis',icd:'CA70',cat:'respiratory',desc:'Progressive scarring of lung parenchyma with restrictive physiology',sys:['respiratory']},
  {id:'pulmonary-hypertension',name:'Pulmonary Hypertension',icd:'BB01',cat:'respiratory',desc:'Elevated pulmonary artery pressure leading to right heart failure',sys:['respiratory','cardiovascular']},
  {id:'acute-respiratory-distress-syndrome',name:'Acute Respiratory Distress Syndrome',icd:'CB00',cat:'respiratory',desc:'Severe diffuse lung injury with non-cardiogenic pulmonary edema',sys:['respiratory']},
  {id:'obstructive-sleep-apnea',name:'Obstructive Sleep Apnea',icd:'7A40',cat:'respiratory',desc:'Recurrent upper airway collapse during sleep causing hypoxia',sys:['respiratory']},
  {id:'cystic-fibrosis',name:'Cystic Fibrosis',icd:'CA25',cat:'respiratory',desc:'Genetic disorder causing thick mucus secretions and chronic lung infections',sys:['respiratory','gastrointestinal']},
  {id:'bronchiectasis',name:'Bronchiectasis',icd:'CA26',cat:'respiratory',desc:'Permanent airway dilation with chronic infection and inflammation',sys:['respiratory']},
  {id:'sarcoidosis-pulmonary',name:'Pulmonary Sarcoidosis',icd:'CA80',cat:'respiratory',desc:'Granulomatous lung disease with bilateral hilar lymphadenopathy',sys:['respiratory','immunologic']},
  {id:'respiratory-failure',name:'Acute Respiratory Failure',icd:'CB40',cat:'respiratory',desc:'Inability to maintain adequate gas exchange requiring intervention',sys:['respiratory']},
  // ── Chapter 13: Diseases of the digestive system (DA00–DE2Z) ──
  {id:'gerd',name:'Gastroesophageal Reflux Disease',icd:'DA22',cat:'gastrointestinal',desc:'Chronic acid reflux causing esophageal mucosal damage',sys:['gastrointestinal']},
  {id:'peptic-ulcer',name:'Peptic Ulcer Disease',icd:'DA40',cat:'gastrointestinal',desc:'Mucosal ulceration of stomach or duodenum often H. pylori related',sys:['gastrointestinal']},
  {id:'gastritis',name:'Gastritis',icd:'DA41',cat:'gastrointestinal',desc:'Inflammation of the gastric mucosa',sys:['gastrointestinal']},
  {id:'crohns-disease',name:'Crohn Disease',icd:'DD60',cat:'gastrointestinal',desc:'Chronic transmural granulomatous inflammation of any GI segment',sys:['gastrointestinal','immunologic']},
  {id:'ulcerative-colitis',name:'Ulcerative Colitis',icd:'DD61',cat:'gastrointestinal',desc:'Chronic mucosal inflammation of the colon and rectum',sys:['gastrointestinal','immunologic']},
  {id:'irritable-bowel-syndrome',name:'Irritable Bowel Syndrome',icd:'DD91',cat:'gastrointestinal',desc:'Functional bowel disorder with abdominal pain and altered bowel habits',sys:['gastrointestinal']},
  {id:'appendicitis',name:'Acute Appendicitis',icd:'DB10',cat:'gastrointestinal',desc:'Acute inflammation of the vermiform appendix',sys:['gastrointestinal']},
  {id:'diverticulitis',name:'Diverticulitis',icd:'DB30',cat:'gastrointestinal',desc:'Inflammation of colonic diverticula with potential perforation',sys:['gastrointestinal']},
  {id:'cholelithiasis',name:'Cholelithiasis (Gallstones)',icd:'DC10',cat:'gastrointestinal',desc:'Formation of gallstones in the gallbladder causing biliary colic',sys:['gastrointestinal']},
  {id:'cholecystitis',name:'Acute Cholecystitis',icd:'DC11',cat:'gastrointestinal',desc:'Acute inflammation of the gallbladder usually from stone obstruction',sys:['gastrointestinal']},
  {id:'pancreatitis-acute',name:'Acute Pancreatitis',icd:'DC30',cat:'gastrointestinal',desc:'Acute inflammation of the pancreas with autodigestion',sys:['gastrointestinal']},
  {id:'pancreatitis-chronic',name:'Chronic Pancreatitis',icd:'DC31',cat:'gastrointestinal',desc:'Progressive inflammatory fibrosis of the pancreas',sys:['gastrointestinal','endocrine']},
  {id:'liver-cirrhosis',name:'Cirrhosis of the Liver',icd:'DB93',cat:'gastrointestinal',desc:'End-stage chronic liver disease with fibrosis and nodular regeneration',sys:['gastrointestinal']},
  {id:'nafld',name:'Non-Alcoholic Fatty Liver Disease',icd:'DB92',cat:'gastrointestinal',desc:'Hepatic steatosis not due to alcohol with potential progression to cirrhosis',sys:['gastrointestinal','metabolic']},
  {id:'alcoholic-liver-disease',name:'Alcoholic Liver Disease',icd:'DB91',cat:'gastrointestinal',desc:'Spectrum of liver injury from chronic alcohol use',sys:['gastrointestinal']},
  {id:'hepatic-encephalopathy',name:'Hepatic Encephalopathy',icd:'DB94',cat:'gastrointestinal',desc:'Brain dysfunction from liver failure with ammonia accumulation',sys:['gastrointestinal','neurologic']},
  {id:'gi-bleeding-upper',name:'Upper GI Bleeding',icd:'DA90',cat:'gastrointestinal',desc:'Hemorrhage from upper gastrointestinal tract source',sys:['gastrointestinal']},
  {id:'gi-bleeding-lower',name:'Lower GI Bleeding',icd:'DA91',cat:'gastrointestinal',desc:'Hemorrhage from colonic or rectal source',sys:['gastrointestinal']},
  {id:'bowel-obstruction',name:'Intestinal Obstruction',icd:'DB00',cat:'gastrointestinal',desc:'Mechanical or functional blockage of intestinal flow',sys:['gastrointestinal']},
  {id:'hemorrhoids',name:'Hemorrhoids',icd:'DB60',cat:'gastrointestinal',desc:'Swollen vascular cushions in the anal canal causing bleeding and pain',sys:['gastrointestinal']},
  {id:'achalasia',name:'Achalasia',icd:'DA20',cat:'gastrointestinal',desc:'Esophageal motility disorder with failure of LES relaxation',sys:['gastrointestinal']},
  // ── Chapter 14: Diseases of the skin (EA00–EM0Z) ──
  {id:'psoriasis',name:'Psoriasis',icd:'EA90',cat:'dermatologic',desc:'Chronic immune-mediated inflammatory skin disease with plaques',sys:['dermatologic','immunologic']},
  {id:'atopic-dermatitis',name:'Atopic Dermatitis (Eczema)',icd:'EA80',cat:'dermatologic',desc:'Chronic pruritic inflammatory skin condition with atopic predisposition',sys:['dermatologic','immunologic']},
  {id:'contact-dermatitis',name:'Contact Dermatitis',icd:'EA81',cat:'dermatologic',desc:'Inflammatory skin reaction from direct contact with irritant or allergen',sys:['dermatologic']},
  {id:'acne-vulgaris',name:'Acne Vulgaris',icd:'ED80',cat:'dermatologic',desc:'Chronic inflammatory disease of pilosebaceous units',sys:['dermatologic']},
  {id:'rosacea',name:'Rosacea',icd:'ED90',cat:'dermatologic',desc:'Chronic facial erythema with papules pustules and telangiectasia',sys:['dermatologic']},
  {id:'urticaria',name:'Urticaria (Hives)',icd:'EB00',cat:'dermatologic',desc:'Transient pruritic wheals from mast cell degranulation',sys:['dermatologic','immunologic']},
  {id:'vitiligo',name:'Vitiligo',icd:'EC23',cat:'dermatologic',desc:'Autoimmune destruction of melanocytes causing depigmented patches',sys:['dermatologic','immunologic']},
  {id:'alopecia-areata',name:'Alopecia Areata',icd:'ED70',cat:'dermatologic',desc:'Autoimmune hair loss with discrete patches of baldness',sys:['dermatologic','immunologic']},
  {id:'cellulitis-skin',name:'Skin Abscess',icd:'EB01',cat:'dermatologic',desc:'Localized collection of pus in the skin and subcutaneous tissue',sys:['dermatologic']},
  {id:'herpes-zoster',name:'Herpes Zoster (Shingles)',icd:'1E91',cat:'dermatologic',desc:'Reactivation of varicella-zoster virus causing painful vesicular rash',sys:['dermatologic','neurologic']},
  {id:'fungal-skin-infection',name:'Dermatophytosis',icd:'1F28',cat:'dermatologic',desc:'Superficial fungal skin infection by dermatophytes',sys:['dermatologic']},
  {id:'pemphigus-vulgaris',name:'Pemphigus Vulgaris',icd:'EB40',cat:'dermatologic',desc:'Autoimmune blistering disease with intraepithelial acantholysis',sys:['dermatologic','immunologic']},
  {id:'stevens-johnson-syndrome',name:'Stevens-Johnson Syndrome',icd:'EH60',cat:'dermatologic',desc:'Severe mucocutaneous reaction usually triggered by medications',sys:['dermatologic','immunologic']},
  // ── Chapter 15: Diseases of the musculoskeletal system (FA00–FC0Z) ──
  {id:'osteoarthritis',name:'Osteoarthritis',icd:'FA00',cat:'musculoskeletal',desc:'Degenerative joint disease with cartilage loss and bony remodeling',sys:['musculoskeletal']},
  {id:'osteoporosis',name:'Osteoporosis',icd:'FB83',cat:'musculoskeletal',desc:'Reduced bone density and microarchitectural deterioration increasing fracture risk',sys:['musculoskeletal']},
  {id:'ankylosing-spondylitis',name:'Ankylosing Spondylitis',icd:'FA90',cat:'musculoskeletal',desc:'Chronic inflammatory arthritis primarily affecting the axial skeleton',sys:['musculoskeletal','immunologic']},
  {id:'psoriatic-arthritis',name:'Psoriatic Arthritis',icd:'FA21',cat:'musculoskeletal',desc:'Inflammatory arthritis associated with psoriasis',sys:['musculoskeletal','dermatologic','immunologic']},
  {id:'fibromyalgia',name:'Fibromyalgia',icd:'MG30',cat:'musculoskeletal',desc:'Chronic widespread musculoskeletal pain with central sensitization',sys:['musculoskeletal','neurologic']},
  {id:'rotator-cuff-tear',name:'Rotator Cuff Tear',icd:'FB40',cat:'musculoskeletal',desc:'Tear of one or more rotator cuff tendons causing shoulder dysfunction',sys:['musculoskeletal']},
  {id:'lumbar-disc-herniation',name:'Lumbar Disc Herniation',icd:'FA80',cat:'musculoskeletal',desc:'Protrusion of intervertebral disc material compressing spinal nerve roots',sys:['musculoskeletal','neurologic']},
  {id:'spinal-stenosis',name:'Spinal Stenosis',icd:'FA81',cat:'musculoskeletal',desc:'Narrowing of the spinal canal causing neurogenic claudication',sys:['musculoskeletal','neurologic']},
  {id:'scoliosis',name:'Scoliosis',icd:'FA70',cat:'musculoskeletal',desc:'Lateral curvature of the spine exceeding 10 degrees',sys:['musculoskeletal']},
  {id:'osteogenesis-imperfecta',name:'Osteogenesis Imperfecta',icd:'FB80',cat:'musculoskeletal',desc:'Genetic disorder of type I collagen causing brittle bones',sys:['musculoskeletal']},
  {id:'paget-disease-bone',name:'Paget Disease of Bone',icd:'FB84',cat:'musculoskeletal',desc:'Focal disorder of bone remodeling with disorganized new bone formation',sys:['musculoskeletal']},
  {id:'tendinitis',name:'Tendinitis',icd:'FB50',cat:'musculoskeletal',desc:'Inflammation or degeneration of a tendon from overuse or injury',sys:['musculoskeletal']},
  {id:'plantar-fasciitis',name:'Plantar Fasciitis',icd:'FB55',cat:'musculoskeletal',desc:'Degenerative condition of the plantar fascia causing heel pain',sys:['musculoskeletal']},
  {id:'meniscal-tear',name:'Meniscal Tear',icd:'FB41',cat:'musculoskeletal',desc:'Tear of the knee meniscus causing pain and mechanical symptoms',sys:['musculoskeletal']},
  {id:'anterior-cruciate-ligament-tear',name:'ACL Tear',icd:'FB42',cat:'musculoskeletal',desc:'Rupture of the anterior cruciate ligament of the knee',sys:['musculoskeletal']},
  {id:'polymyalgia-rheumatica',name:'Polymyalgia Rheumatica',icd:'FA22',cat:'musculoskeletal',desc:'Inflammatory condition causing bilateral shoulder and hip girdle pain',sys:['musculoskeletal','immunologic']},
  {id:'muscular-dystrophy',name:'Duchenne Muscular Dystrophy',icd:'8C71',cat:'musculoskeletal',desc:'X-linked progressive muscle degeneration from dystrophin deficiency',sys:['musculoskeletal']},
  {id:'rhabdomyolysis',name:'Rhabdomyolysis',icd:'FB60',cat:'musculoskeletal',desc:'Skeletal muscle breakdown with release of myoglobin causing renal injury',sys:['musculoskeletal','urologic']},
  // ── Chapter 16: Diseases of the genitourinary system (GA00–GC8Z) ──
  {id:'chronic-kidney-disease',name:'Chronic Kidney Disease',icd:'GB60',cat:'urologic',desc:'Progressive irreversible loss of kidney function over months to years',sys:['urologic']},
  {id:'acute-kidney-injury',name:'Acute Kidney Injury',icd:'GB61',cat:'urologic',desc:'Rapid decline in kidney function over hours to days',sys:['urologic']},
  {id:'nephrotic-syndrome',name:'Nephrotic Syndrome',icd:'GB40',cat:'urologic',desc:'Glomerular disease with massive proteinuria hypoalbuminemia and edema',sys:['urologic']},
  {id:'nephritic-syndrome',name:'Nephritic Syndrome',icd:'GB41',cat:'urologic',desc:'Glomerulonephritis with hematuria proteinuria and hypertension',sys:['urologic','immunologic']},
  {id:'urinary-tract-infection',name:'Urinary Tract Infection',icd:'GC00',cat:'urologic',desc:'Bacterial infection of the urinary tract',sys:['urologic']},
  {id:'pyelonephritis',name:'Pyelonephritis',icd:'GC01',cat:'urologic',desc:'Bacterial infection of the kidney parenchyma',sys:['urologic']},
  {id:'kidney-stones',name:'Nephrolithiasis',icd:'GB70',cat:'urologic',desc:'Formation of calculi in the renal collecting system',sys:['urologic']},
  {id:'benign-prostatic-hyperplasia',name:'Benign Prostatic Hyperplasia',icd:'GA80',cat:'urologic',desc:'Non-malignant enlargement of the prostate causing urinary obstruction',sys:['urologic']},
  {id:'polycystic-kidney-disease',name:'Polycystic Kidney Disease',icd:'GB61',cat:'urologic',desc:'Inherited disorder with bilateral renal cyst formation leading to renal failure',sys:['urologic']},
  {id:'urinary-incontinence',name:'Urinary Incontinence',icd:'GC80',cat:'urologic',desc:'Involuntary loss of urine affecting quality of life',sys:['urologic']},
  {id:'erectile-dysfunction',name:'Erectile Dysfunction',icd:'GA10',cat:'urologic',desc:'Inability to achieve or maintain penile erection sufficient for intercourse',sys:['urologic','cardiovascular']},
  {id:'endometriosis',name:'Endometriosis',icd:'GA10',cat:'urologic',desc:'Endometrial-like tissue outside the uterus causing pain and infertility',sys:['urologic','immunologic']},
  {id:'polycystic-ovary-syndrome',name:'Polycystic Ovary Syndrome',icd:'GA20',cat:'endocrine',desc:'Endocrine disorder with hyperandrogenism anovulation and polycystic ovaries',sys:['endocrine','urologic']},
  {id:'preeclampsia',name:'Preeclampsia',icd:'JA21',cat:'cardiovascular',desc:'Hypertensive disorder of pregnancy with proteinuria and end-organ damage',sys:['cardiovascular','urologic']},
  // ── Chapter 17: Conditions related to sexual health ──
  {id:'infertility-female',name:'Female Infertility',icd:'GA30',cat:'endocrine',desc:'Inability to conceive after 12 months of unprotected intercourse',sys:['endocrine','urologic']},
  {id:'infertility-male',name:'Male Infertility',icd:'GA31',cat:'urologic',desc:'Impaired male reproductive ability from various spermatogenic or obstructive causes',sys:['urologic','endocrine']},
  // ── Chapter 19: Diseases of the ear ──
  {id:'otitis-media',name:'Otitis Media',icd:'AB10',cat:'infectious',desc:'Middle ear infection common in children causing ear pain and hearing loss',sys:['immunologic']},
  {id:'menieres-disease',name:'Meniere Disease',icd:'AB31',cat:'neurologic',desc:'Inner ear disorder with vertigo hearing loss and tinnitus',sys:['neurologic']},
  {id:'tinnitus',name:'Tinnitus',icd:'AB33',cat:'neurologic',desc:'Perception of sound without external acoustic stimulus',sys:['neurologic']},
  // ── Chapter 20: Developmental anomalies ──
  {id:'down-syndrome',name:'Down Syndrome',icd:'LD40',cat:'neurologic',desc:'Chromosomal disorder from trisomy 21 with intellectual disability and dysmorphic features',sys:['neurologic','cardiovascular']},
  {id:'turner-syndrome',name:'Turner Syndrome',icd:'LD50',cat:'endocrine',desc:'Monosomy X in females causing short stature and gonadal dysgenesis',sys:['endocrine']},
  {id:'marfan-syndrome',name:'Marfan Syndrome',icd:'LD28',cat:'musculoskeletal',desc:'Connective tissue disorder from fibrillin-1 mutation affecting skeleton heart and eyes',sys:['musculoskeletal','cardiovascular']},
  {id:'cleft-lip-palate',name:'Cleft Lip and Palate',icd:'LA40',cat:'musculoskeletal',desc:'Congenital malformation of the lip and/or palate',sys:['musculoskeletal']},
  {id:'congenital-heart-defect-asd',name:'Atrial Septal Defect',icd:'LA80',cat:'cardiovascular',desc:'Congenital opening between the atria allowing left-to-right shunt',sys:['cardiovascular']},
  {id:'congenital-heart-defect-vsd',name:'Ventricular Septal Defect',icd:'LA81',cat:'cardiovascular',desc:'Congenital opening between the ventricles',sys:['cardiovascular']},
  {id:'tetralogy-of-fallot',name:'Tetralogy of Fallot',icd:'LA87',cat:'cardiovascular',desc:'Complex cyanotic congenital heart disease with four cardiac defects',sys:['cardiovascular']},
  {id:'spina-bifida',name:'Spina Bifida',icd:'LB00',cat:'neurologic',desc:'Neural tube defect with incomplete closure of the spinal column',sys:['neurologic','musculoskeletal']},
  // ── Chapter 21: Symptoms and signs not elsewhere classified ──
  {id:'chronic-fatigue-syndrome',name:'Chronic Fatigue Syndrome',icd:'8E49',cat:'immunologic',desc:'Persistent unexplained fatigue with post-exertional malaise',sys:['immunologic','neurologic']},
  {id:'chronic-pain-syndrome',name:'Chronic Pain Syndrome',icd:'MG30',cat:'neurologic',desc:'Persistent pain lasting beyond expected healing time with psychosocial impact',sys:['neurologic']},
  {id:'syncope',name:'Syncope',icd:'MB11',cat:'cardiovascular',desc:'Transient loss of consciousness from cerebral hypoperfusion',sys:['cardiovascular','neurologic']},
  // ── Chapter 22: Injury, poisoning, or certain other consequences ──
  {id:'concussion',name:'Concussion',icd:'NA07',cat:'neurologic',desc:'Mild traumatic brain injury with transient neurologic dysfunction',sys:['neurologic']},
  {id:'fracture-hip',name:'Hip Fracture',icd:'NB30',cat:'musculoskeletal',desc:'Fracture of proximal femur common in elderly with osteoporosis',sys:['musculoskeletal']},
  {id:'fracture-vertebral',name:'Vertebral Compression Fracture',icd:'NB10',cat:'musculoskeletal',desc:'Collapse of vertebral body often from osteoporosis',sys:['musculoskeletal']},
  {id:'burns',name:'Burns',icd:'NE80',cat:'dermatologic',desc:'Tissue damage from thermal chemical electrical or radiation exposure',sys:['dermatologic']},
  // ── Additional cardiovascular entries ──
  {id:'wolff-parkinson-white',name:'Wolff-Parkinson-White Syndrome',icd:'BC63',cat:'cardiovascular',desc:'Pre-excitation syndrome with accessory atrioventricular pathway',sys:['cardiovascular']},
  {id:'long-qt-syndrome',name:'Long QT Syndrome',icd:'BC64',cat:'cardiovascular',desc:'Inherited ion channelopathy with prolonged QT interval and arrhythmia risk',sys:['cardiovascular']},
  {id:'brugada-syndrome',name:'Brugada Syndrome',icd:'BC65',cat:'cardiovascular',desc:'Inherited sodium channelopathy with ST elevation and sudden cardiac death risk',sys:['cardiovascular']},
  {id:'takotsubo-cardiomyopathy',name:'Takotsubo Cardiomyopathy',icd:'BC43',cat:'cardiovascular',desc:'Stress-induced transient left ventricular apical ballooning',sys:['cardiovascular']},
  {id:'constrictive-pericarditis',name:'Constrictive Pericarditis',icd:'BB03',cat:'cardiovascular',desc:'Pericardial fibrosis restricting cardiac filling',sys:['cardiovascular']},
  // ── Additional respiratory entries ──
  {id:'laryngitis',name:'Laryngitis',icd:'CA00',cat:'respiratory',desc:'Inflammation of the larynx causing hoarseness',sys:['respiratory']},
  {id:'epiglottitis',name:'Epiglottitis',icd:'CA01',cat:'respiratory',desc:'Acute inflammation of the epiglottis with airway compromise risk',sys:['respiratory']},
  {id:'lung-abscess',name:'Lung Abscess',icd:'CA42',cat:'respiratory',desc:'Localized suppurative necrosis of lung parenchyma',sys:['respiratory']},
  {id:'silicosis',name:'Silicosis',icd:'CA60',cat:'respiratory',desc:'Occupational pneumoconiosis from crystalline silica inhalation',sys:['respiratory']},
  {id:'asbestosis',name:'Asbestosis',icd:'CA61',cat:'respiratory',desc:'Pulmonary fibrosis from chronic asbestos fiber inhalation',sys:['respiratory']},
  // ── Additional gastrointestinal entries ──
  {id:'barrett-esophagus',name:'Barrett Esophagus',icd:'DA23',cat:'gastrointestinal',desc:'Intestinal metaplasia of esophageal epithelium from chronic GERD',sys:['gastrointestinal']},
  {id:'celiac-disease-gi',name:'Celiac Sprue',icd:'DA95',cat:'gastrointestinal',desc:'Gluten-sensitive enteropathy with villous atrophy of small intestine',sys:['gastrointestinal','immunologic']},
  {id:'c-diff-colitis',name:'Clostridioides difficile Colitis',icd:'1A04',cat:'gastrointestinal',desc:'Antibiotic-associated colitis from C. difficile toxin production',sys:['gastrointestinal']},
  {id:'ischemic-colitis',name:'Ischemic Colitis',icd:'DD90',cat:'gastrointestinal',desc:'Colonic inflammation from reduced blood flow',sys:['gastrointestinal','cardiovascular']},
  {id:'hepatitis-autoimmune',name:'Autoimmune Hepatitis',icd:'DB96',cat:'gastrointestinal',desc:'Chronic liver inflammation from immune dysregulation',sys:['gastrointestinal','immunologic']},
  {id:'primary-biliary-cholangitis',name:'Primary Biliary Cholangitis',icd:'DC40',cat:'gastrointestinal',desc:'Autoimmune destruction of intrahepatic bile ducts',sys:['gastrointestinal','immunologic']},
  {id:'primary-sclerosing-cholangitis',name:'Primary Sclerosing Cholangitis',icd:'DC41',cat:'gastrointestinal',desc:'Chronic fibrosing inflammation of intra and extrahepatic bile ducts',sys:['gastrointestinal','immunologic']},
  // ── Additional neurologic entries ──
  {id:'frontotemporal-dementia',name:'Frontotemporal Dementia',icd:'8A22',cat:'neurologic',desc:'Neurodegenerative dementia affecting frontal and temporal lobes with behavioral changes',sys:['neurologic']},
  {id:'lewy-body-dementia',name:'Lewy Body Dementia',icd:'8A23',cat:'neurologic',desc:'Dementia with Lewy bodies causing fluctuating cognition and visual hallucinations',sys:['neurologic']},
  {id:'essential-tremor',name:'Essential Tremor',icd:'8A04',cat:'neurologic',desc:'Common movement disorder with postural and kinetic tremor',sys:['neurologic']},
  {id:'dystonia',name:'Dystonia',icd:'8A05',cat:'neurologic',desc:'Movement disorder with sustained or intermittent muscle contractions',sys:['neurologic']},
  {id:'narcolepsy',name:'Narcolepsy',icd:'7A20',cat:'neurologic',desc:'Chronic neurological disorder with excessive daytime sleepiness and cataplexy',sys:['neurologic']},
  {id:'hydrocephalus',name:'Hydrocephalus',icd:'8D60',cat:'neurologic',desc:'Excessive CSF accumulation within cerebral ventricles',sys:['neurologic']},
  {id:'normal-pressure-hydrocephalus',name:'Normal Pressure Hydrocephalus',icd:'8D61',cat:'neurologic',desc:'Ventricular enlargement with gait disturbance dementia and urinary incontinence',sys:['neurologic']},
  {id:'transient-ischemic-attack',name:'Transient Ischemic Attack',icd:'8B11',cat:'neurologic',desc:'Temporary cerebral ischemia without permanent infarction',sys:['neurologic','cardiovascular']},
  {id:'status-epilepticus',name:'Status Epilepticus',icd:'8A61',cat:'neurologic',desc:'Prolonged seizure activity lasting more than 5 minutes requiring emergency treatment',sys:['neurologic']},
  // ── Additional endocrine entries ──
  {id:'thyroid-nodule',name:'Thyroid Nodule',icd:'5A04',cat:'endocrine',desc:'Discrete lesion within the thyroid gland requiring evaluation for malignancy',sys:['endocrine']},
  {id:'goiter',name:'Goiter',icd:'5A05',cat:'endocrine',desc:'Enlargement of the thyroid gland',sys:['endocrine']},
  {id:'adrenal-insufficiency',name:'Adrenal Insufficiency',icd:'5A74',cat:'endocrine',desc:'Inadequate adrenal cortisol production from primary or secondary causes',sys:['endocrine']},
  {id:'hyperaldosteronism',name:'Primary Hyperaldosteronism',icd:'5A76',cat:'endocrine',desc:'Excess aldosterone production causing hypertension and hypokalemia',sys:['endocrine','cardiovascular']},
  {id:'prolactinoma',name:'Prolactinoma',icd:'5A62',cat:'endocrine',desc:'Pituitary adenoma secreting prolactin causing galactorrhea and hypogonadism',sys:['endocrine']},
  {id:'diabetic-neuropathy',name:'Diabetic Neuropathy',icd:'5A14',cat:'endocrine',desc:'Peripheral nerve damage from chronic hyperglycemia',sys:['endocrine','neurologic']},
  {id:'diabetic-nephropathy',name:'Diabetic Nephropathy',icd:'5A15',cat:'endocrine',desc:'Progressive kidney disease from chronic diabetes',sys:['endocrine','urologic']},
  // ── Additional dermatologic entries ──
  {id:'seborrheic-dermatitis',name:'Seborrheic Dermatitis',icd:'EA82',cat:'dermatologic',desc:'Chronic inflammatory dermatosis in sebaceous gland-rich areas',sys:['dermatologic']},
  {id:'lichen-planus',name:'Lichen Planus',icd:'EA91',cat:'dermatologic',desc:'Inflammatory mucocutaneous condition with pruritic polygonal papules',sys:['dermatologic','immunologic']},
  {id:'bullous-pemphigoid',name:'Bullous Pemphigoid',icd:'EB41',cat:'dermatologic',desc:'Autoimmune subepidermal blistering disease in elderly',sys:['dermatologic','immunologic']},
  {id:'hidradenitis-suppurativa',name:'Hidradenitis Suppurativa',icd:'ED10',cat:'dermatologic',desc:'Chronic inflammatory disease of hair follicles in intertriginous areas',sys:['dermatologic']},
  {id:'scabies',name:'Scabies',icd:'1G04',cat:'dermatologic',desc:'Contagious skin infestation by Sarcoptes scabiei mite',sys:['dermatologic']},
  // ── Additional infectious entries ──
  {id:'pneumocystis-pneumonia',name:'Pneumocystis Pneumonia',icd:'1F24',cat:'infectious',desc:'Opportunistic fungal pneumonia in immunocompromised patients',sys:['respiratory','immunologic']},
  {id:'toxoplasmosis',name:'Toxoplasmosis',icd:'1F52',cat:'infectious',desc:'Parasitic infection by Toxoplasma gondii with potential CNS involvement',sys:['neurologic','immunologic']},
  {id:'cryptococcal-meningitis',name:'Cryptococcal Meningitis',icd:'1F25',cat:'infectious',desc:'Fungal meningitis caused by Cryptococcus neoformans in immunocompromised',sys:['neurologic','immunologic']},
  {id:'infectious-mononucleosis',name:'Infectious Mononucleosis',icd:'1E90',cat:'infectious',desc:'EBV infection with pharyngitis lymphadenopathy and atypical lymphocytosis',sys:['immunologic']},
  {id:'helicobacter-pylori',name:'Helicobacter pylori Infection',icd:'1B92',cat:'infectious',desc:'Bacterial infection of gastric mucosa associated with peptic ulcer and gastric cancer',sys:['gastrointestinal']},
  {id:'clostridial-myonecrosis',name:'Gas Gangrene',icd:'1C10',cat:'infectious',desc:'Rapidly progressive necrotizing soft tissue infection by Clostridium species',sys:['musculoskeletal','immunologic']},
  {id:'necrotizing-fasciitis',name:'Necrotizing Fasciitis',icd:'1B71',cat:'infectious',desc:'Rapidly progressive deep soft tissue infection with fascial necrosis',sys:['dermatologic','musculoskeletal']},
  {id:'mrsa-infection',name:'MRSA Infection',icd:'1C40',cat:'infectious',desc:'Infection by methicillin-resistant Staphylococcus aureus',sys:['immunologic','dermatologic']},
  // ── Additional hematologic entries ──
  {id:'hemolytic-uremic-syndrome',name:'Hemolytic Uremic Syndrome',icd:'3B63',cat:'hematologic',desc:'Thrombotic microangiopathy with hemolytic anemia thrombocytopenia and renal failure',sys:['hematologic','urologic']},
  {id:'thrombotic-thrombocytopenic-purpura',name:'Thrombotic Thrombocytopenic Purpura',icd:'3B64',cat:'hematologic',desc:'Thrombotic microangiopathy from ADAMTS13 deficiency with pentad of findings',sys:['hematologic','neurologic']},
  {id:'immune-thrombocytopenia',name:'Immune Thrombocytopenic Purpura',icd:'3B61',cat:'hematologic',desc:'Autoimmune platelet destruction causing isolated thrombocytopenia',sys:['hematologic','immunologic']},
  {id:'myelodysplastic-syndrome',name:'Myelodysplastic Syndrome',icd:'3A10',cat:'hematologic',desc:'Clonal bone marrow disorder with ineffective hematopoiesis and dysplasia',sys:['hematologic']},
  {id:'myelofibrosis',name:'Myelofibrosis',icd:'3A21',cat:'hematologic',desc:'Myeloproliferative neoplasm with progressive bone marrow fibrosis',sys:['hematologic']},
  {id:'essential-thrombocythemia',name:'Essential Thrombocythemia',icd:'3A22',cat:'hematologic',desc:'Myeloproliferative neoplasm with sustained platelet elevation',sys:['hematologic']},
  {id:'antiphospholipid-syndrome',name:'Antiphospholipid Syndrome',icd:'4A44',cat:'hematologic',desc:'Autoimmune prothrombotic disorder with arterial and venous thromboses',sys:['hematologic','immunologic']},
  {id:'hereditary-spherocytosis',name:'Hereditary Spherocytosis',icd:'3A52',cat:'hematologic',desc:'Inherited red cell membrane defect causing hemolytic anemia',sys:['hematologic']},
  {id:'g6pd-deficiency',name:'G6PD Deficiency',icd:'3A53',cat:'hematologic',desc:'X-linked enzyme deficiency causing episodic hemolytic anemia',sys:['hematologic']},
  // ── Additional psychiatric entries ──
  {id:'borderline-personality-disorder',name:'Borderline Personality Disorder',icd:'6D10',cat:'psychiatric',desc:'Personality disorder with emotional instability impulsivity and unstable relationships',sys:['neurologic']},
  {id:'dissociative-identity-disorder',name:'Dissociative Identity Disorder',icd:'6B64',cat:'psychiatric',desc:'Disruption of identity with two or more distinct personality states',sys:['neurologic']},
  {id:'social-anxiety-disorder',name:'Social Anxiety Disorder',icd:'6B04',cat:'psychiatric',desc:'Marked fear of social situations with avoidance behavior',sys:['neurologic']},
  {id:'specific-phobia',name:'Specific Phobia',icd:'6B03',cat:'psychiatric',desc:'Intense irrational fear and avoidance of a specific object or situation',sys:['neurologic']},
  {id:'conversion-disorder',name:'Functional Neurological Disorder',icd:'6B60',cat:'psychiatric',desc:'Neurological symptoms without organic disease from psychological factors',sys:['neurologic']},
  {id:'delirium',name:'Delirium',icd:'6D70',cat:'psychiatric',desc:'Acute fluctuating disturbance in attention and cognition',sys:['neurologic']},
  // ── Additional immunologic entries ──
  {id:'dermatomyositis',name:'Dermatomyositis',icd:'4A43',cat:'immunologic',desc:'Idiopathic inflammatory myopathy with characteristic skin findings',sys:['immunologic','musculoskeletal','dermatologic']},
  {id:'polymyositis',name:'Polymyositis',icd:'4A44',cat:'immunologic',desc:'Idiopathic inflammatory myopathy with proximal muscle weakness',sys:['immunologic','musculoskeletal']},
  {id:'vasculitis-granulomatosis',name:'Granulomatosis with Polyangiitis',icd:'4A44',cat:'immunologic',desc:'ANCA-associated vasculitis affecting upper and lower airways and kidneys',sys:['immunologic','respiratory','urologic']},
  {id:'giant-cell-arteritis',name:'Giant Cell Arteritis',icd:'4A44',cat:'immunologic',desc:'Large vessel vasculitis of temporal arteries with risk of vision loss',sys:['immunologic','cardiovascular']},
  {id:'polyarteritis-nodosa',name:'Polyarteritis Nodosa',icd:'4A44',cat:'immunologic',desc:'Systemic necrotizing vasculitis of medium-sized arteries',sys:['immunologic','cardiovascular']},
  {id:'kawasaki-disease',name:'Kawasaki Disease',icd:'4A44',cat:'immunologic',desc:'Acute febrile vasculitis in children with coronary artery aneurysm risk',sys:['immunologic','cardiovascular']},
  {id:'behcet-disease',name:'Behcet Disease',icd:'4A64',cat:'immunologic',desc:'Multisystem vasculitis with oral and genital ulcers and uveitis',sys:['immunologic','dermatologic']},
  {id:'goodpasture-syndrome',name:'Goodpasture Syndrome',icd:'4A45',cat:'immunologic',desc:'Anti-GBM disease causing pulmonary hemorrhage and glomerulonephritis',sys:['immunologic','respiratory','urologic']},
  {id:'mixed-connective-tissue-disease',name:'Mixed Connective Tissue Disease',icd:'4A46',cat:'immunologic',desc:'Overlap syndrome with features of SLE scleroderma and myositis with anti-U1 RNP',sys:['immunologic','musculoskeletal']},
  // ── Additional oncologic entries ──
  {id:'small-cell-lung-cancer',name:'Small Cell Lung Cancer',icd:'2C26',cat:'oncologic',desc:'Aggressive neuroendocrine lung malignancy with early metastasis',sys:['respiratory']},
  {id:'cholangiocarcinoma',name:'Cholangiocarcinoma',icd:'2C13',cat:'oncologic',desc:'Malignant neoplasm of the bile duct epithelium',sys:['gastrointestinal']},
  {id:'carcinoid-tumor',name:'Carcinoid Tumor',icd:'2D20',cat:'oncologic',desc:'Well-differentiated neuroendocrine tumor with potential carcinoid syndrome',sys:['gastrointestinal','endocrine']},
  {id:'neuroblastoma',name:'Neuroblastoma',icd:'2D50',cat:'oncologic',desc:'Embryonal malignancy of neural crest cells most common in children',sys:['neurologic','endocrine']},
  {id:'retinoblastoma',name:'Retinoblastoma',icd:'2D60',cat:'oncologic',desc:'Malignant intraocular tumor of the retina in children',sys:['neurologic']},
  {id:'osteosarcoma',name:'Osteosarcoma',icd:'2E00',cat:'oncologic',desc:'Primary malignant bone tumor producing osteoid',sys:['musculoskeletal']},
  {id:'ewing-sarcoma',name:'Ewing Sarcoma',icd:'2E01',cat:'oncologic',desc:'Aggressive round cell bone tumor of children and young adults',sys:['musculoskeletal']},
  {id:'soft-tissue-sarcoma',name:'Soft Tissue Sarcoma',icd:'2E10',cat:'oncologic',desc:'Malignant neoplasm arising from mesenchymal soft tissues',sys:['musculoskeletal']},
  {id:'wilms-tumor',name:'Wilms Tumor',icd:'2C91',cat:'oncologic',desc:'Most common pediatric renal malignancy of embryonal origin',sys:['urologic']},
  {id:'adrenal-carcinoma',name:'Adrenocortical Carcinoma',icd:'2D11',cat:'oncologic',desc:'Rare malignant neoplasm of the adrenal cortex',sys:['endocrine']},
  // ── Additional metabolic/rare ──
  {id:'cystinuria',name:'Cystinuria',icd:'5C51',cat:'metabolic',desc:'Inherited amino acid transport disorder causing recurrent cystine kidney stones',sys:['metabolic','urologic']},
  {id:'fabry-disease',name:'Fabry Disease',icd:'5C60',cat:'metabolic',desc:'X-linked lysosomal storage disorder from alpha-galactosidase deficiency',sys:['metabolic','cardiovascular','neurologic']},
  {id:'gaucher-disease',name:'Gaucher Disease',icd:'5C61',cat:'metabolic',desc:'Lysosomal storage disorder from glucocerebrosidase deficiency',sys:['metabolic','hematologic']},
  {id:'porphyria',name:'Porphyria',icd:'5C62',cat:'metabolic',desc:'Group of disorders from heme biosynthesis enzyme deficiencies',sys:['metabolic','dermatologic','neurologic']},
  {id:'glycogen-storage-disease',name:'Glycogen Storage Disease',icd:'5C53',cat:'metabolic',desc:'Inherited disorders of glycogen metabolism affecting liver and muscle',sys:['metabolic','musculoskeletal']},
  {id:'maple-syrup-urine-disease',name:'Maple Syrup Urine Disease',icd:'5C54',cat:'metabolic',desc:'Branched-chain amino acid metabolism disorder with sweet-smelling urine',sys:['metabolic','neurologic']},
  // ── Additional urologic entries ──
  {id:'interstitial-cystitis',name:'Interstitial Cystitis',icd:'GC10',cat:'urologic',desc:'Chronic bladder pain syndrome with urinary frequency and urgency',sys:['urologic']},
  {id:'hydronephrosis',name:'Hydronephrosis',icd:'GB80',cat:'urologic',desc:'Dilation of renal pelvis and calyces from urinary obstruction',sys:['urologic']},
  {id:'renal-tubular-acidosis',name:'Renal Tubular Acidosis',icd:'GB62',cat:'urologic',desc:'Metabolic acidosis from impaired renal tubular acid excretion',sys:['urologic','metabolic']},
  // ── Chapter 24: Factors influencing health status ──
  {id:'tobacco-dependence',name:'Tobacco Dependence',icd:'QD50',cat:'psychiatric',desc:'Nicotine dependence syndrome with physiological and behavioral components',sys:['respiratory','neurologic']},
  // ── Fill remaining to ensure 300+ ──
  {id:'amyloidosis',name:'Amyloidosis',icd:'5D00',cat:'immunologic',desc:'Systemic disease with extracellular deposition of misfolded protein fibrils',sys:['immunologic','cardiovascular','urologic']},
  {id:'hemolytic-anemia-autoimmune',name:'Autoimmune Hemolytic Anemia',icd:'3A60',cat:'hematologic',desc:'Immune-mediated red blood cell destruction with anemia and jaundice',sys:['hematologic','immunologic']},
  {id:'idiopathic-intracranial-hypertension',name:'Idiopathic Intracranial Hypertension',icd:'8D62',cat:'neurologic',desc:'Elevated intracranial pressure without mass lesion causing headache and vision changes',sys:['neurologic']},
  {id:'hepatorenal-syndrome',name:'Hepatorenal Syndrome',icd:'DB95',cat:'gastrointestinal',desc:'Renal failure in setting of advanced liver disease from splanchnic vasodilation',sys:['gastrointestinal','urologic']},
  {id:'portal-hypertension',name:'Portal Hypertension',icd:'DB96',cat:'gastrointestinal',desc:'Elevated pressure in the portal venous system usually from cirrhosis',sys:['gastrointestinal','cardiovascular']},
  {id:'esophageal-varices',name:'Esophageal Varices',icd:'DA24',cat:'gastrointestinal',desc:'Dilated submucosal veins in esophagus from portal hypertension with bleeding risk',sys:['gastrointestinal']},
  {id:'spontaneous-bacterial-peritonitis',name:'Spontaneous Bacterial Peritonitis',icd:'DB97',cat:'gastrointestinal',desc:'Bacterial infection of ascitic fluid in cirrhotics without surgical cause',sys:['gastrointestinal','immunologic']},
  {id:'acute-coronary-syndrome',name:'Acute Coronary Syndrome',icd:'BA43',cat:'cardiovascular',desc:'Spectrum of acute myocardial ischemia including STEMI NSTEMI and unstable angina',sys:['cardiovascular']},
  {id:'carotid-artery-stenosis',name:'Carotid Artery Stenosis',icd:'BD41',cat:'cardiovascular',desc:'Atherosclerotic narrowing of the carotid artery with stroke risk',sys:['cardiovascular','neurologic']},
  {id:'chronic-venous-insufficiency',name:'Chronic Venous Insufficiency',icd:'BD81',cat:'cardiovascular',desc:'Impaired venous return in lower extremities causing edema and skin changes',sys:['cardiovascular']},
  {id:'cor-pulmonale',name:'Cor Pulmonale',icd:'BB80',cat:'cardiovascular',desc:'Right heart failure secondary to pulmonary hypertension from lung disease',sys:['cardiovascular','respiratory']},
  {id:'restless-legs-syndrome',name:'Restless Legs Syndrome',icd:'8A06',cat:'neurologic',desc:'Sensorimotor disorder with urge to move legs and sleep disruption',sys:['neurologic']},
  {id:'complex-regional-pain-syndrome',name:'Complex Regional Pain Syndrome',icd:'8D8A',cat:'neurologic',desc:'Chronic pain condition with autonomic and motor dysfunction in an extremity',sys:['neurologic']},
  {id:'diabetic-foot-ulcer',name:'Diabetic Foot Ulcer',icd:'5A16',cat:'endocrine',desc:'Non-healing foot wound from diabetic neuropathy and peripheral vascular disease',sys:['endocrine','cardiovascular','dermatologic']},
  {id:'cushing-disease',name:'Cushing Disease',icd:'5A71',cat:'endocrine',desc:'ACTH-secreting pituitary adenoma causing secondary hypercortisolism',sys:['endocrine']},
  {id:'secondary-hypertension',name:'Secondary Hypertension',icd:'BA02',cat:'cardiovascular',desc:'Hypertension with identifiable underlying cause such as renal or endocrine',sys:['cardiovascular','endocrine','urologic']},
  {id:'thromboangiitis-obliterans',name:'Buerger Disease',icd:'BD42',cat:'cardiovascular',desc:'Inflammatory thrombotic vasculopathy of small and medium arteries in smokers',sys:['cardiovascular']},
  {id:'iga-nephropathy',name:'IgA Nephropathy',icd:'GB42',cat:'urologic',desc:'Most common primary glomerulonephritis with mesangial IgA deposition',sys:['urologic','immunologic']},
  {id:'minimal-change-disease',name:'Minimal Change Disease',icd:'GB43',cat:'urologic',desc:'Most common cause of nephrotic syndrome in children with normal light microscopy',sys:['urologic']},
  {id:'membranous-nephropathy',name:'Membranous Nephropathy',icd:'GB44',cat:'urologic',desc:'Glomerular disease with subepithelial immune complex deposits causing nephrotic syndrome',sys:['urologic','immunologic']},
  {id:'focal-segmental-glomerulosclerosis',name:'Focal Segmental Glomerulosclerosis',icd:'GB45',cat:'urologic',desc:'Glomerular disease with segmental sclerosis causing nephrotic syndrome',sys:['urologic']},
  {id:'henoch-schonlein-purpura',name:'IgA Vasculitis',icd:'4A44',cat:'immunologic',desc:'Small vessel vasculitis with IgA deposits affecting skin joints kidneys and GI tract',sys:['immunologic','dermatologic','urologic']},
  {id:'dermatomyositis-juvenile',name:'Juvenile Dermatomyositis',icd:'4A43',cat:'immunologic',desc:'Childhood inflammatory myopathy with skin rash and proximal muscle weakness',sys:['immunologic','musculoskeletal','dermatologic']},
  {id:'chronic-granulomatous-disease',name:'Chronic Granulomatous Disease',icd:'4A10',cat:'immunologic',desc:'Primary immunodeficiency with defective phagocyte NADPH oxidase',sys:['immunologic']},
  {id:'severe-combined-immunodeficiency',name:'Severe Combined Immunodeficiency',icd:'4A00',cat:'immunologic',desc:'Most severe primary immunodeficiency with absent T and B cell function',sys:['immunologic']},
  {id:'wiskott-aldrich-syndrome',name:'Wiskott-Aldrich Syndrome',icd:'4A02',cat:'immunologic',desc:'X-linked immunodeficiency with eczema thrombocytopenia and recurrent infections',sys:['immunologic','hematologic','dermatologic']},
];
