// =============================================================================
// Batch 2: Eyes + ENT + Cardiovascular + Respiratory Symptoms
// =============================================================================

import type { SintomaEntry } from './tipos';

export const SINTOMAS_OJOS_ENT_CARDIO_RESP: SintomaEntry[] = [
  // ---- OJOS ----
  {
    id: 'vision-borrosa',
    nombreEs: 'Visión borrosa',
    nombreEn: 'Blurred vision',
    descripcionEs: 'Pérdida de la agudeza visual que hace que los objetos se vean desenfocados o poco nítidos. Puede afectar uno o ambos ojos.',
    descripcionEn: 'Loss of visual acuity that makes objects appear out of focus or unclear. It can affect one or both eyes.',
    categorias: ['oftalmológico'],
    urgencia: 'media',
    causasComunesEs: ['Errores de refracción (miopía, hipermetropía, astigmatismo)', 'Ojo seco', 'Cataratas', 'Diabetes (retinopatía diabética)', 'Glaucoma', 'Degeneración macular'],
    causasComunesEn: ['Refractive errors (nearsightedness, farsightedness, astigmatism)', 'Dry eye', 'Cataracts', 'Diabetes (diabetic retinopathy)', 'Glaucoma', 'Macular degeneration'],
    cuandoVerMedicoEs: ['Visión borrosa repentina en uno o ambos ojos', 'Visión borrosa acompañada de dolor ocular', 'Visión borrosa con destellos de luz o moscas volantes', 'Pérdida parcial del campo visual'],
    cuandoVerMedicoEn: ['Sudden blurred vision in one or both eyes', 'Blurred vision accompanied by eye pain', 'Blurred vision with flashes of light or floaters', 'Partial loss of visual field'],
    autoCuidadoEs: ['Descansar los ojos de pantallas cada 20 minutos', 'Usar lágrimas artificiales para el ojo seco', 'Usar gafas o lentes de contacto actualizados', 'Mantener buena iluminación al leer'],
    autoCuidadoEn: ['Rest eyes from screens every 20 minutes', 'Use artificial tears for dry eye', 'Use updated glasses or contact lenses', 'Maintain good lighting when reading'],
    preguntasParaMedicoEs: ['¿Necesito cambiar la graduación de mis lentes?', '¿Mi visión borrosa podría estar relacionada con la diabetes?', '¿Debería ver a un oftalmólogo?'],
    preguntasParaMedicoEn: ['Do I need to change my lens prescription?', 'Could my blurred vision be related to diabetes?', 'Should I see an ophthalmologist?'],
    sintomasRelacionados: ['dolor-ocular', 'moscas-volantes', 'sensibilidad-a-la-luz', 'dolor-de-cabeza'],
    sistemasCorporales: ['oftalmológico']
  },
  {
    id: 'ojo-rojo',
    nombreEs: 'Ojo rojo',
    nombreEn: 'Red eye',
    descripcionEs: 'Enrojecimiento de la parte blanca del ojo (esclerótica) debido a la dilatación de los vasos sanguíneos. Puede afectar uno o ambos ojos.',
    descripcionEn: 'Redness of the white part of the eye (sclera) due to dilation of blood vessels. It can affect one or both eyes.',
    categorias: ['oftalmológico'],
    urgencia: 'media',
    causasComunesEs: ['Conjuntivitis (viral, bacteriana o alérgica)', 'Ojo seco', 'Irritación por sustancias', 'Hemorragia subconjuntival', 'Glaucoma agudo', 'Uso excesivo de lentes de contacto'],
    causasComunesEn: ['Conjunctivitis (viral, bacterial, or allergic)', 'Dry eye', 'Irritation from substances', 'Subconjunctival hemorrhage', 'Acute glaucoma', 'Excessive contact lens use'],
    cuandoVerMedicoEs: ['Ojo rojo con dolor intenso', 'Ojo rojo con cambios en la visión', 'Ojo rojo después de un trauma', 'Secreción abundante del ojo'],
    cuandoVerMedicoEn: ['Red eye with severe pain', 'Red eye with vision changes', 'Red eye after trauma', 'Heavy discharge from the eye'],
    autoCuidadoEs: ['Aplicar compresas frías', 'Usar lágrimas artificiales sin conservantes', 'No frotar los ojos', 'Retirar lentes de contacto si los usa'],
    autoCuidadoEn: ['Apply cold compresses', 'Use preservative-free artificial tears', 'Do not rub the eyes', 'Remove contact lenses if wearing them'],
    preguntasParaMedicoEs: ['¿Es contagioso?', '¿Necesito gotas con antibiótico?', '¿Puedo seguir usando lentes de contacto?'],
    preguntasParaMedicoEn: ['Is it contagious?', 'Do I need antibiotic drops?', 'Can I continue wearing contact lenses?'],
    sintomasRelacionados: ['dolor-ocular', 'vision-borrosa', 'sensibilidad-a-la-luz', 'picazon'],
    sistemasCorporales: ['oftalmológico']
  },
  {
    id: 'dolor-ocular',
    nombreEs: 'Dolor ocular',
    nombreEn: 'Eye pain',
    descripcionEs: 'Dolor en o alrededor del ojo que puede ser agudo, punzante, ardoroso o como presión. Puede originarse en la superficie del ojo o en estructuras más profundas.',
    descripcionEn: 'Pain in or around the eye that can be sharp, stabbing, burning, or pressure-like. It can originate from the eye surface or deeper structures.',
    categorias: ['oftalmológico'],
    urgencia: 'alta',
    causasComunesEs: ['Cuerpo extraño en el ojo', 'Abrasión corneal', 'Glaucoma agudo', 'Uveítis', 'Sinusitis', 'Cefalea en racimo'],
    causasComunesEn: ['Foreign body in the eye', 'Corneal abrasion', 'Acute glaucoma', 'Uveitis', 'Sinusitis', 'Cluster headache'],
    cuandoVerMedicoEs: ['Dolor ocular severo o repentino', 'Dolor con disminución de la visión', 'Dolor después de una lesión en el ojo', 'Dolor con náuseas y vómitos (posible glaucoma)'],
    cuandoVerMedicoEn: ['Severe or sudden eye pain', 'Pain with decreased vision', 'Pain after eye injury', 'Pain with nausea and vomiting (possible glaucoma)'],
    autoCuidadoEs: ['No frotar el ojo afectado', 'Enjuagar con agua limpia si hay irritante', 'Descansar la vista', 'No intentar retirar objetos incrustados'],
    autoCuidadoEn: ['Do not rub the affected eye', 'Rinse with clean water if irritant present', 'Rest the eyes', 'Do not attempt to remove embedded objects'],
    preguntasParaMedicoEs: ['¿Necesito examen con lámpara de hendidura?', '¿Podría ser glaucoma?', '¿Necesito gotas para el dolor?'],
    preguntasParaMedicoEn: ['Do I need a slit lamp examination?', 'Could it be glaucoma?', 'Do I need drops for the pain?'],
    sintomasRelacionados: ['ojo-rojo', 'vision-borrosa', 'sensibilidad-a-la-luz', 'dolor-de-cabeza'],
    sistemasCorporales: ['oftalmológico']
  },
  {
    id: 'moscas-volantes',
    nombreEs: 'Moscas volantes',
    nombreEn: 'Floaters',
    descripcionEs: 'Pequeñas manchas, puntos, líneas o telarañas que parecen flotar en el campo visual. Se mueven cuando mueve los ojos y son más visibles con fondos claros.',
    descripcionEn: 'Small spots, dots, lines, or cobwebs that appear to float in the visual field. They move when you move your eyes and are more visible against light backgrounds.',
    categorias: ['oftalmológico'],
    urgencia: 'media',
    causasComunesEs: ['Cambios por envejecimiento del humor vítreo', 'Desprendimiento posterior del vítreo', 'Desprendimiento de retina', 'Hemorragia vítrea', 'Inflamación ocular'],
    causasComunesEn: ['Age-related changes in the vitreous humor', 'Posterior vitreous detachment', 'Retinal detachment', 'Vitreous hemorrhage', 'Ocular inflammation'],
    cuandoVerMedicoEs: ['Aumento repentino de moscas volantes', 'Moscas volantes acompañadas de destellos de luz', 'Sombra o cortina oscura en la visión', 'Pérdida parcial del campo visual'],
    cuandoVerMedicoEn: ['Sudden increase in floaters', 'Floaters accompanied by flashes of light', 'Shadow or dark curtain in vision', 'Partial loss of visual field'],
    autoCuidadoEs: ['Mover los ojos para desplazar las moscas del campo visual', 'Realizar exámenes oculares regulares', 'Proteger los ojos del sol con gafas oscuras'],
    autoCuidadoEn: ['Move eyes to shift floaters from visual field', 'Get regular eye exams', 'Protect eyes from sun with dark glasses'],
    preguntasParaMedicoEs: ['¿Mis moscas volantes son normales para mi edad?', '¿Necesito un examen de fondo de ojo?', '¿Hay riesgo de desprendimiento de retina?'],
    preguntasParaMedicoEn: ['Are my floaters normal for my age?', 'Do I need a fundoscopic exam?', 'Is there a risk of retinal detachment?'],
    sintomasRelacionados: ['vision-borrosa', 'sensibilidad-a-la-luz', 'dolor-ocular'],
    sistemasCorporales: ['oftalmológico']
  },
  {
    id: 'sensibilidad-a-la-luz',
    nombreEs: 'Sensibilidad a la luz (fotofobia)',
    nombreEn: 'Sensitivity to light (photophobia)',
    descripcionEs: 'Incomodidad o dolor en los ojos causado por la exposición a la luz. La luz normal puede resultar excesivamente brillante o molesta.',
    descripcionEn: 'Discomfort or eye pain caused by light exposure. Normal light may seem excessively bright or bothersome.',
    categorias: ['oftalmológico', 'neurológico'],
    urgencia: 'media',
    causasComunesEs: ['Migraña', 'Conjuntivitis', 'Abrasión corneal', 'Uveítis', 'Meningitis', 'Dilatación pupilar por medicamentos'],
    causasComunesEn: ['Migraine', 'Conjunctivitis', 'Corneal abrasion', 'Uveitis', 'Meningitis', 'Pupil dilation from medications'],
    cuandoVerMedicoEs: ['Fotofobia severa con fiebre y rigidez de cuello', 'Fotofobia repentina con ojo rojo', 'Fotofobia que no mejora en pocos días', 'Fotofobia con dolor de cabeza intenso'],
    cuandoVerMedicoEn: ['Severe photophobia with fever and neck stiffness', 'Sudden photophobia with red eye', 'Photophobia not improving in a few days', 'Photophobia with severe headache'],
    autoCuidadoEs: ['Usar gafas de sol en exteriores', 'Reducir el brillo de las pantallas', 'Evitar luces fluorescentes cuando sea posible', 'Usar sombrero de ala ancha'],
    autoCuidadoEn: ['Wear sunglasses outdoors', 'Reduce screen brightness', 'Avoid fluorescent lights when possible', 'Wear a wide-brimmed hat'],
    preguntasParaMedicoEs: ['¿La sensibilidad a la luz está relacionada con mis migrañas?', '¿Necesito un examen ocular completo?', '¿Hay lentes especiales que podrían ayudarme?'],
    preguntasParaMedicoEn: ['Is my light sensitivity related to my migraines?', 'Do I need a complete eye exam?', 'Are there special lenses that could help me?'],
    sintomasRelacionados: ['migrana', 'dolor-ocular', 'ojo-rojo', 'dolor-de-cabeza'],
    sistemasCorporales: ['oftalmológico', 'neurológico']
  },
  // ---- OIDOS / NARIZ / GARGANTA ----
  {
    id: 'dolor-de-oido',
    nombreEs: 'Dolor de oído (otalgia)',
    nombreEn: 'Ear pain (otalgia)',
    descripcionEs: 'Dolor dentro o alrededor del oído que puede ser agudo, sordo o pulsátil. Puede afectar uno o ambos oídos.',
    descripcionEn: 'Pain inside or around the ear that can be sharp, dull, or throbbing. It can affect one or both ears.',
    categorias: ['otorrinolaringología', 'oído'],
    urgencia: 'media',
    causasComunesEs: ['Infección del oído medio (otitis media)', 'Infección del oído externo (otitis externa)', 'Acumulación de cerumen', 'Disfunción de la trompa de Eustaquio', 'Dolor referido de garganta o mandíbula'],
    causasComunesEn: ['Middle ear infection (otitis media)', 'Outer ear infection (otitis externa)', 'Earwax buildup', 'Eustachian tube dysfunction', 'Referred pain from throat or jaw'],
    cuandoVerMedicoEs: ['Dolor de oído severo o que empeora', 'Secreción del oído', 'Fiebre acompañante', 'Pérdida de audición asociada', 'Dolor de oído en niños pequeños'],
    cuandoVerMedicoEn: ['Severe or worsening ear pain', 'Ear discharge', 'Accompanying fever', 'Associated hearing loss', 'Ear pain in young children'],
    autoCuidadoEs: ['Aplicar compresa tibia sobre el oído', 'Tomar analgésicos de venta libre', 'No introducir objetos en el oído', 'Mantener el oído seco'],
    autoCuidadoEn: ['Apply warm compress over the ear', 'Take over-the-counter pain relievers', 'Do not insert objects into the ear', 'Keep the ear dry'],
    preguntasParaMedicoEs: ['¿Tengo una infección de oído?', '¿Necesito antibióticos?', '¿Debo ver a un otorrinolaringólogo?'],
    preguntasParaMedicoEn: ['Do I have an ear infection?', 'Do I need antibiotics?', 'Should I see an ENT specialist?'],
    sintomasRelacionados: ['perdida-de-audicion', 'zumbido', 'fiebre', 'dolor-de-garganta'],
    sistemasCorporales: ['otorrinolaringológico']
  },
  {
    id: 'perdida-de-audicion',
    nombreEs: 'Pérdida de audición',
    nombreEn: 'Hearing loss',
    descripcionEs: 'Disminución parcial o total de la capacidad para escuchar sonidos en uno o ambos oídos. Puede ser gradual o repentina.',
    descripcionEn: 'Partial or total decrease in the ability to hear sounds in one or both ears. It can be gradual or sudden.',
    categorias: ['otorrinolaringología', 'oído'],
    urgencia: 'media',
    causasComunesEs: ['Envejecimiento (presbiacusia)', 'Exposición prolongada a ruido fuerte', 'Acumulación de cerumen', 'Infecciones del oído', 'Otosclerosis', 'Enfermedad de Ménière'],
    causasComunesEn: ['Aging (presbycusis)', 'Prolonged exposure to loud noise', 'Earwax buildup', 'Ear infections', 'Otosclerosis', 'Meniere disease'],
    cuandoVerMedicoEs: ['Pérdida de audición súbita (urgencia médica)', 'Pérdida progresiva de audición', 'Pérdida de audición en un solo oído', 'Pérdida acompañada de vértigo o zumbido'],
    cuandoVerMedicoEn: ['Sudden hearing loss (medical emergency)', 'Progressive hearing loss', 'Hearing loss in one ear only', 'Loss accompanied by vertigo or tinnitus'],
    autoCuidadoEs: ['Proteger los oídos del ruido excesivo', 'Usar protección auditiva en ambientes ruidosos', 'Evitar el uso de hisopos de algodón dentro del oído', 'Realizar audiometrías periódicas'],
    autoCuidadoEn: ['Protect ears from excessive noise', 'Use hearing protection in noisy environments', 'Avoid using cotton swabs inside the ear', 'Get periodic hearing tests'],
    preguntasParaMedicoEs: ['¿Necesito un audífono?', '¿Mi pérdida de audición es reversible?', '¿Debería hacerme una audiometría?'],
    preguntasParaMedicoEn: ['Do I need a hearing aid?', 'Is my hearing loss reversible?', 'Should I get an audiometry test?'],
    sintomasRelacionados: ['zumbido', 'dolor-de-oido', 'vertigo', 'congestion-nasal'],
    sistemasCorporales: ['otorrinolaringológico']
  },
  {
    id: 'zumbido',
    nombreEs: 'Zumbido en los oídos (tinnitus)',
    nombreEn: 'Ringing in ears (tinnitus)',
    descripcionEs: 'Percepción de ruidos en los oídos como zumbidos, silbidos, pitidos o rugidos sin una fuente de sonido externa.',
    descripcionEn: 'Perception of noises in the ears such as buzzing, whistling, ringing, or roaring without an external sound source.',
    categorias: ['otorrinolaringología', 'oído'],
    urgencia: 'baja',
    causasComunesEs: ['Exposición a ruido fuerte', 'Pérdida de audición relacionada con la edad', 'Tapón de cerumen', 'Enfermedad de Ménière', 'Ciertos medicamentos (aspirina, antibióticos)', 'Estrés'],
    causasComunesEn: ['Exposure to loud noise', 'Age-related hearing loss', 'Earwax plug', 'Meniere disease', 'Certain medications (aspirin, antibiotics)', 'Stress'],
    cuandoVerMedicoEs: ['Zumbido que empeora o no desaparece', 'Zumbido en un solo oído', 'Zumbido pulsátil (al ritmo del corazón)', 'Zumbido con pérdida de audición'],
    cuandoVerMedicoEn: ['Tinnitus that worsens or does not go away', 'Tinnitus in one ear only', 'Pulsatile tinnitus (in rhythm with heartbeat)', 'Tinnitus with hearing loss'],
    autoCuidadoEs: ['Usar sonidos de fondo o ruido blanco para enmascarar', 'Evitar el silencio total', 'Reducir el consumo de cafeína y sal', 'Practicar técnicas de relajación'],
    autoCuidadoEn: ['Use background sounds or white noise to mask', 'Avoid complete silence', 'Reduce caffeine and salt intake', 'Practice relaxation techniques'],
    preguntasParaMedicoEs: ['¿Qué está causando mi zumbido?', '¿Hay tratamientos disponibles?', '¿Alguno de mis medicamentos podría ser la causa?'],
    preguntasParaMedicoEn: ['What is causing my tinnitus?', 'Are there treatments available?', 'Could any of my medications be the cause?'],
    sintomasRelacionados: ['perdida-de-audicion', 'vertigo', 'dolor-de-oido', 'ansiedad'],
    sistemasCorporales: ['otorrinolaringológico']
  },
  {
    id: 'congestion-nasal',
    nombreEs: 'Congestión nasal',
    nombreEn: 'Nasal congestion',
    descripcionEs: 'Obstrucción o taponamiento de las fosas nasales debido a la inflamación de los tejidos y vasos sanguíneos de la nariz.',
    descripcionEn: 'Obstruction or stuffiness of the nasal passages due to inflammation of nasal tissues and blood vessels.',
    categorias: ['otorrinolaringología', 'respiratorio'],
    urgencia: 'baja',
    causasComunesEs: ['Resfriado común', 'Alergias (rinitis alérgica)', 'Sinusitis', 'Desviación del tabique nasal', 'Pólipos nasales', 'Cambios hormonales'],
    causasComunesEn: ['Common cold', 'Allergies (allergic rhinitis)', 'Sinusitis', 'Deviated nasal septum', 'Nasal polyps', 'Hormonal changes'],
    cuandoVerMedicoEs: ['Congestión que dura más de 10 días', 'Congestión con dolor facial severo', 'Secreción nasal con mal olor o color verdoso', 'Congestión con fiebre alta'],
    cuandoVerMedicoEn: ['Congestion lasting more than 10 days', 'Congestion with severe facial pain', 'Nasal discharge with bad smell or greenish color', 'Congestion with high fever'],
    autoCuidadoEs: ['Usar solución salina nasal', 'Inhalar vapor de agua caliente', 'Mantenerse hidratado', 'Elevar la cabeza al dormir', 'Usar un humidificador'],
    autoCuidadoEn: ['Use saline nasal solution', 'Inhale warm water steam', 'Stay hydrated', 'Elevate head when sleeping', 'Use a humidifier'],
    preguntasParaMedicoEs: ['¿Tengo sinusitis o alergias?', '¿Necesito un descongestionante con receta?', '¿Debería hacerme pruebas de alergia?'],
    preguntasParaMedicoEn: ['Do I have sinusitis or allergies?', 'Do I need a prescription decongestant?', 'Should I get allergy testing?'],
    sintomasRelacionados: ['sangrado-nasal', 'dolor-de-garganta', 'dolor-de-cabeza', 'tos'],
    sistemasCorporales: ['otorrinolaringológico', 'respiratorio']
  },
  {
    id: 'sangrado-nasal',
    nombreEs: 'Sangrado nasal (epistaxis)',
    nombreEn: 'Nosebleed (epistaxis)',
    descripcionEs: 'Sangrado que proviene de los vasos sanguíneos dentro de la nariz. Puede ser anterior (por la parte frontal) o posterior (hacia la garganta).',
    descripcionEn: 'Bleeding from blood vessels inside the nose. It can be anterior (from the front) or posterior (toward the throat).',
    categorias: ['otorrinolaringología'],
    urgencia: 'media',
    causasComunesEs: ['Aire seco', 'Rascado o hurgado nasal', 'Resfriados e irritación nasal', 'Hipertensión arterial', 'Uso de anticoagulantes', 'Desviación del tabique nasal'],
    causasComunesEn: ['Dry air', 'Nose picking or scratching', 'Colds and nasal irritation', 'High blood pressure', 'Use of blood thinners', 'Deviated nasal septum'],
    cuandoVerMedicoEs: ['Sangrado que no para después de 20 minutos de presión', 'Sangrado abundante o que fluye hacia la garganta', 'Sangrados nasales frecuentes', 'Sangrado después de un trauma facial'],
    cuandoVerMedicoEn: ['Bleeding not stopping after 20 minutes of pressure', 'Heavy bleeding or bleeding flowing to the throat', 'Frequent nosebleeds', 'Bleeding after facial trauma'],
    autoCuidadoEs: ['Sentarse inclinado hacia adelante', 'Apretar la parte blanda de la nariz durante 10-15 minutos', 'No inclinar la cabeza hacia atrás', 'Usar humidificador si el aire es seco'],
    autoCuidadoEn: ['Sit leaning forward', 'Pinch the soft part of the nose for 10-15 minutes', 'Do not tilt head backward', 'Use a humidifier if the air is dry'],
    preguntasParaMedicoEs: ['¿Mis sangrados nasales podrían indicar un problema de coagulación?', '¿Necesito cauterización nasal?', '¿Debo suspender algún medicamento?'],
    preguntasParaMedicoEn: ['Could my nosebleeds indicate a clotting problem?', 'Do I need nasal cauterization?', 'Should I stop any medications?'],
    sintomasRelacionados: ['congestion-nasal', 'presion-arterial-alta', 'dolor-de-cabeza'],
    sistemasCorporales: ['otorrinolaringológico']
  },
  {
    id: 'dolor-de-garganta',
    nombreEs: 'Dolor de garganta',
    nombreEn: 'Sore throat',
    descripcionEs: 'Dolor, irritación o sensación de raspado en la garganta que suele empeorar al tragar. Es uno de los síntomas más comunes de consulta médica.',
    descripcionEn: 'Pain, irritation, or scratchy sensation in the throat that usually worsens when swallowing. It is one of the most common symptoms for medical visits.',
    categorias: ['otorrinolaringología'],
    urgencia: 'baja',
    causasComunesEs: ['Infección viral (resfriado, gripe)', 'Faringitis estreptocócica', 'Alergias', 'Aire seco', 'Reflujo gastroesofágico', 'Uso excesivo de la voz'],
    causasComunesEn: ['Viral infection (cold, flu)', 'Strep throat', 'Allergies', 'Dry air', 'Gastroesophageal reflux', 'Overuse of voice'],
    cuandoVerMedicoEs: ['Dolor de garganta severo o que dura más de una semana', 'Dificultad para tragar o respirar', 'Fiebre alta con dolor de garganta', 'Bulto en el cuello o ronquera que persiste'],
    cuandoVerMedicoEn: ['Severe sore throat or lasting more than a week', 'Difficulty swallowing or breathing', 'High fever with sore throat', 'Lump in the neck or persistent hoarseness'],
    autoCuidadoEs: ['Hacer gárgaras con agua tibia con sal', 'Beber líquidos calientes como té con miel', 'Chupar pastillas para la garganta', 'Descansar la voz'],
    autoCuidadoEn: ['Gargle with warm salt water', 'Drink warm liquids such as tea with honey', 'Suck on throat lozenges', 'Rest the voice'],
    preguntasParaMedicoEs: ['¿Necesito una prueba rápida de estreptococo?', '¿Debo tomar antibióticos?', '¿Podría ser algo más que una infección?'],
    preguntasParaMedicoEn: ['Do I need a rapid strep test?', 'Should I take antibiotics?', 'Could it be something other than an infection?'],
    sintomasRelacionados: ['ronquera', 'dificultad-para-tragar', 'fiebre', 'congestion-nasal'],
    sistemasCorporales: ['otorrinolaringológico']
  },
  {
    id: 'ronquera',
    nombreEs: 'Ronquera (disfonía)',
    nombreEn: 'Hoarseness (dysphonia)',
    descripcionEs: 'Cambio anormal en la voz que puede sonar áspera, rasposa, débil o entrecortada. Indica alteración en las cuerdas vocales.',
    descripcionEn: 'Abnormal change in the voice that may sound rough, raspy, weak, or strained. It indicates alteration in the vocal cords.',
    categorias: ['otorrinolaringología'],
    urgencia: 'baja',
    causasComunesEs: ['Uso excesivo de la voz', 'Laringitis viral', 'Reflujo gastroesofágico', 'Alergias', 'Nódulos o pólipos en cuerdas vocales', 'Tabaquismo'],
    causasComunesEn: ['Overuse of the voice', 'Viral laryngitis', 'Gastroesophageal reflux', 'Allergies', 'Vocal cord nodules or polyps', 'Smoking'],
    cuandoVerMedicoEs: ['Ronquera que dura más de 3 semanas', 'Ronquera sin causa aparente', 'Ronquera con dificultad para respirar', 'Ronquera en fumadores'],
    cuandoVerMedicoEn: ['Hoarseness lasting more than 3 weeks', 'Hoarseness without apparent cause', 'Hoarseness with difficulty breathing', 'Hoarseness in smokers'],
    autoCuidadoEs: ['Descansar la voz', 'Hidratarse abundantemente', 'Evitar susurrar (daña más las cuerdas vocales)', 'Evitar humo de tabaco e irritantes'],
    autoCuidadoEn: ['Rest the voice', 'Stay well hydrated', 'Avoid whispering (it damages vocal cords more)', 'Avoid tobacco smoke and irritants'],
    preguntasParaMedicoEs: ['¿Necesito una laringoscopia?', '¿Podría ser algo serio?', '¿Me beneficiaría la terapia de voz?'],
    preguntasParaMedicoEn: ['Do I need a laryngoscopy?', 'Could it be something serious?', 'Would voice therapy benefit me?'],
    sintomasRelacionados: ['dolor-de-garganta', 'dificultad-para-tragar', 'tos', 'acidez'],
    sistemasCorporales: ['otorrinolaringológico']
  },
  {
    id: 'dificultad-para-tragar',
    nombreEs: 'Dificultad para tragar (disfagia)',
    nombreEn: 'Difficulty swallowing (dysphagia)',
    descripcionEs: 'Sensación de que los alimentos o líquidos se atoran en la garganta o el pecho al tragar. Puede haber dolor al tragar (odinofagia).',
    descripcionEn: 'Sensation that food or liquids get stuck in the throat or chest when swallowing. There may be pain when swallowing (odynophagia).',
    categorias: ['otorrinolaringología', 'gastrointestinal'],
    urgencia: 'alta',
    causasComunesEs: ['Reflujo gastroesofágico crónico', 'Estrechamiento del esófago', 'Esofagitis eosinofílica', 'Infección de garganta', 'Trastornos neuromusculares', 'Tumores esofágicos'],
    causasComunesEn: ['Chronic gastroesophageal reflux', 'Esophageal narrowing', 'Eosinophilic esophagitis', 'Throat infection', 'Neuromuscular disorders', 'Esophageal tumors'],
    cuandoVerMedicoEs: ['Dificultad para tragar que empeora progresivamente', 'Imposibilidad de tragar líquidos', 'Pérdida de peso asociada', 'Regurgitación de alimentos', 'Sensación de obstrucción persistente'],
    cuandoVerMedicoEn: ['Difficulty swallowing that progressively worsens', 'Inability to swallow liquids', 'Associated weight loss', 'Food regurgitation', 'Persistent sensation of obstruction'],
    autoCuidadoEs: ['Comer despacio y masticar bien', 'Cortar los alimentos en trozos pequeños', 'Sentarse erguido al comer', 'Evitar alimentos muy secos o duros'],
    autoCuidadoEn: ['Eat slowly and chew thoroughly', 'Cut food into small pieces', 'Sit upright when eating', 'Avoid very dry or hard foods'],
    preguntasParaMedicoEs: ['¿Necesito una endoscopia?', '¿Podría haber una obstrucción?', '¿Debería ver a un gastroenterólogo?'],
    preguntasParaMedicoEn: ['Do I need an endoscopy?', 'Could there be an obstruction?', 'Should I see a gastroenterologist?'],
    sintomasRelacionados: ['dolor-de-garganta', 'acidez', 'perdida-de-peso', 'ronquera'],
    sistemasCorporales: ['otorrinolaringológico', 'gastrointestinal']
  },
  // ---- CARDIOVASCULAR ----
  {
    id: 'dolor-de-pecho',
    nombreEs: 'Dolor de pecho',
    nombreEn: 'Chest pain',
    descripcionEs: 'Dolor, presión, opresión o malestar en cualquier zona del pecho, desde el cuello hasta la parte superior del abdomen. Puede tener causas cardíacas y no cardíacas.',
    descripcionEn: 'Pain, pressure, tightness, or discomfort in any area of the chest, from the neck to the upper abdomen. It can have cardiac and non-cardiac causes.',
    categorias: ['cardiovascular', 'respiratorio'],
    urgencia: 'emergencia',
    causasComunesEs: ['Angina de pecho o infarto al miocardio', 'Reflujo gastroesofágico', 'Dolor musculoesquelético de la pared torácica', 'Ansiedad y ataques de pánico', 'Embolia pulmonar', 'Neumotórax'],
    causasComunesEn: ['Angina or myocardial infarction', 'Gastroesophageal reflux', 'Musculoskeletal chest wall pain', 'Anxiety and panic attacks', 'Pulmonary embolism', 'Pneumothorax'],
    cuandoVerMedicoEs: ['Dolor de pecho con presión u opresión: llamar al 911', 'Dolor que se irradia al brazo izquierdo, mandíbula o espalda', 'Dolor con dificultad para respirar o sudoración', 'Dolor de pecho nuevo o diferente al habitual'],
    cuandoVerMedicoEn: ['Chest pain with pressure or tightness: call 911', 'Pain radiating to left arm, jaw, or back', 'Pain with difficulty breathing or sweating', 'New or different chest pain than usual'],
    autoCuidadoEs: ['Si sospecha causa cardíaca: llamar a emergencias de inmediato', 'Si es dolor musculoesquelético: descanso y analgésicos', 'Si es acidez: antiácidos de venta libre', 'No ignorar dolor de pecho nuevo'],
    autoCuidadoEn: ['If cardiac cause suspected: call emergency services immediately', 'If musculoskeletal pain: rest and pain relievers', 'If heartburn: over-the-counter antacids', 'Do not ignore new chest pain'],
    preguntasParaMedicoEs: ['¿Mi dolor de pecho podría ser del corazón?', '¿Necesito un electrocardiograma o prueba de esfuerzo?', '¿Debo tomar aspirina si tengo dolor de pecho?'],
    preguntasParaMedicoEn: ['Could my chest pain be from the heart?', 'Do I need an EKG or stress test?', 'Should I take aspirin if I have chest pain?'],
    sintomasRelacionados: ['palpitaciones', 'falta-de-aire', 'acidez', 'ansiedad'],
    sistemasCorporales: ['cardiovascular', 'respiratorio', 'gastrointestinal']
  },
  {
    id: 'palpitaciones',
    nombreEs: 'Palpitaciones',
    nombreEn: 'Palpitations',
    descripcionEs: 'Sensación de que el corazón late demasiado rápido, fuerte, irregularmente, o que se salta latidos. Se percibe como golpeteo, aleteo o carrera en el pecho.',
    descripcionEn: 'Sensation that the heart is beating too fast, hard, irregularly, or skipping beats. Perceived as pounding, fluttering, or racing in the chest.',
    categorias: ['cardiovascular'],
    urgencia: 'media',
    causasComunesEs: ['Ansiedad o estrés', 'Consumo excesivo de cafeína', 'Ejercicio intenso', 'Arritmias cardíacas', 'Anemia', 'Hipertiroidismo'],
    causasComunesEn: ['Anxiety or stress', 'Excessive caffeine intake', 'Intense exercise', 'Cardiac arrhythmias', 'Anemia', 'Hyperthyroidism'],
    cuandoVerMedicoEs: ['Palpitaciones frecuentes o prolongadas', 'Palpitaciones con mareos o desmayo', 'Palpitaciones con dolor de pecho', 'Palpitaciones con dificultad para respirar', 'Antecedentes de enfermedad cardíaca'],
    cuandoVerMedicoEn: ['Frequent or prolonged palpitations', 'Palpitations with dizziness or fainting', 'Palpitations with chest pain', 'Palpitations with difficulty breathing', 'History of heart disease'],
    autoCuidadoEs: ['Reducir o eliminar la cafeína', 'Practicar técnicas de respiración profunda', 'Llevar un registro de cuándo ocurren', 'Reducir el estrés', 'Evitar estimulantes'],
    autoCuidadoEn: ['Reduce or eliminate caffeine', 'Practice deep breathing techniques', 'Keep a log of when they occur', 'Reduce stress', 'Avoid stimulants'],
    preguntasParaMedicoEs: ['¿Necesito un monitoreo cardíaco (Holter)?', '¿Podría tener una arritmia?', '¿Mis palpitaciones son peligrosas?'],
    preguntasParaMedicoEn: ['Do I need cardiac monitoring (Holter)?', 'Could I have an arrhythmia?', 'Are my palpitations dangerous?'],
    sintomasRelacionados: ['dolor-de-pecho', 'mareos', 'desmayo', 'ansiedad', 'falta-de-aire'],
    sistemasCorporales: ['cardiovascular']
  },
  {
    id: 'falta-de-aire',
    nombreEs: 'Falta de aire (disnea)',
    nombreEn: 'Shortness of breath (dyspnea)',
    descripcionEs: 'Sensación de no poder respirar lo suficiente o de esfuerzo al respirar. Puede ocurrir en reposo o con la actividad física.',
    descripcionEn: 'Sensation of not being able to breathe enough or effort when breathing. It can occur at rest or with physical activity.',
    categorias: ['cardiovascular', 'respiratorio'],
    urgencia: 'alta',
    causasComunesEs: ['Asma', 'Insuficiencia cardíaca', 'Enfermedad pulmonar obstructiva crónica (EPOC)', 'Neumonía', 'Anemia', 'Ansiedad', 'Embolia pulmonar'],
    causasComunesEn: ['Asthma', 'Heart failure', 'Chronic obstructive pulmonary disease (COPD)', 'Pneumonia', 'Anemia', 'Anxiety', 'Pulmonary embolism'],
    cuandoVerMedicoEs: ['Falta de aire repentina o severa', 'Falta de aire al acostarse (necesitar dormir sentado)', 'Falta de aire con dolor de pecho', 'Labios o dedos azulados', 'Dificultad para hablar por falta de aire'],
    cuandoVerMedicoEn: ['Sudden or severe shortness of breath', 'Shortness of breath when lying down (needing to sleep sitting up)', 'Shortness of breath with chest pain', 'Blue lips or fingers', 'Difficulty speaking due to shortness of breath'],
    autoCuidadoEs: ['Sentarse erguido para facilitar la respiración', 'Respirar con los labios fruncidos', 'Usar ventilador dirigido a la cara', 'Si tiene inhalador: usarlo según indicaciones'],
    autoCuidadoEn: ['Sit upright to ease breathing', 'Practice pursed-lip breathing', 'Use a fan directed at the face', 'If you have an inhaler: use as directed'],
    preguntasParaMedicoEs: ['¿Mi falta de aire es del corazón o los pulmones?', '¿Necesito oxígeno suplementario?', '¿Debería hacerme una espirometría?'],
    preguntasParaMedicoEn: ['Is my shortness of breath from the heart or lungs?', 'Do I need supplemental oxygen?', 'Should I get a spirometry test?'],
    sintomasRelacionados: ['dolor-de-pecho', 'tos', 'sibilancias', 'hinchazón-de-piernas', 'palpitaciones'],
    sistemasCorporales: ['cardiovascular', 'respiratorio']
  },
  {
    id: 'hinchazón-de-piernas',
    nombreEs: 'Hinchazón de piernas (edema)',
    nombreEn: 'Leg swelling (edema)',
    descripcionEs: 'Acumulación de líquido en los tejidos de las piernas, tobillos o pies que causa aumento de volumen. Al presionar la piel, puede dejar una marca hundida.',
    descripcionEn: 'Fluid accumulation in the tissues of the legs, ankles, or feet causing increased volume. Pressing the skin may leave an indentation.',
    categorias: ['cardiovascular', 'renal'],
    urgencia: 'media',
    causasComunesEs: ['Insuficiencia cardíaca', 'Insuficiencia venosa crónica', 'Estar de pie por períodos prolongados', 'Embarazo', 'Ciertos medicamentos', 'Enfermedad renal', 'Trombosis venosa profunda'],
    causasComunesEn: ['Heart failure', 'Chronic venous insufficiency', 'Standing for prolonged periods', 'Pregnancy', 'Certain medications', 'Kidney disease', 'Deep vein thrombosis'],
    cuandoVerMedicoEs: ['Hinchazón repentina en una sola pierna (posible trombosis)', 'Hinchazón con dolor de pecho o falta de aire', 'Hinchazón progresiva que empeora', 'Hinchazón con enrojecimiento y calor local'],
    cuandoVerMedicoEn: ['Sudden swelling in one leg only (possible thrombosis)', 'Swelling with chest pain or shortness of breath', 'Progressive swelling that worsens', 'Swelling with redness and local warmth'],
    autoCuidadoEs: ['Elevar las piernas por encima del corazón', 'Reducir el consumo de sal', 'Caminar regularmente para activar la circulación', 'Usar medias de compresión', 'Evitar estar sentado o de pie mucho tiempo'],
    autoCuidadoEn: ['Elevate legs above heart level', 'Reduce salt intake', 'Walk regularly to promote circulation', 'Wear compression stockings', 'Avoid sitting or standing for long periods'],
    preguntasParaMedicoEs: ['¿Mi hinchazón podría indicar un problema cardíaco o renal?', '¿Necesito un ultrasonido para descartar trombosis?', '¿Debería usar medias de compresión?'],
    preguntasParaMedicoEn: ['Could my swelling indicate a heart or kidney problem?', 'Do I need an ultrasound to rule out thrombosis?', 'Should I use compression stockings?'],
    sintomasRelacionados: ['falta-de-aire', 'dolor-de-pecho', 'frecuencia-urinaria', 'dolor-articular'],
    sistemasCorporales: ['cardiovascular', 'renal']
  },
  {
    id: 'presion-arterial-alta',
    nombreEs: 'Presión arterial alta (hipertensión)',
    nombreEn: 'High blood pressure (hypertension)',
    descripcionEs: 'Presión de la sangre contra las paredes de las arterias que es consistentemente demasiado alta (mayor de 130/80 mmHg). Generalmente no causa síntomas.',
    descripcionEn: 'Pressure of blood against artery walls that is consistently too high (above 130/80 mmHg). It usually does not cause symptoms.',
    categorias: ['cardiovascular'],
    urgencia: 'alta',
    causasComunesEs: ['Factores genéticos', 'Exceso de sal en la dieta', 'Obesidad', 'Sedentarismo', 'Estrés crónico', 'Apnea del sueño', 'Enfermedad renal'],
    causasComunesEn: ['Genetic factors', 'Excess salt in diet', 'Obesity', 'Sedentary lifestyle', 'Chronic stress', 'Sleep apnea', 'Kidney disease'],
    cuandoVerMedicoEs: ['Presión mayor de 180/120 mmHg (crisis hipertensiva)', 'Dolor de cabeza severo con presión alta', 'Visión borrosa con presión alta', 'Dolor de pecho con presión alta'],
    cuandoVerMedicoEn: ['Pressure above 180/120 mmHg (hypertensive crisis)', 'Severe headache with high pressure', 'Blurred vision with high pressure', 'Chest pain with high pressure'],
    autoCuidadoEs: ['Reducir el consumo de sal', 'Hacer ejercicio regularmente (30 minutos al día)', 'Mantener un peso saludable', 'Limitar el consumo de alcohol', 'Monitorear la presión en casa regularmente'],
    autoCuidadoEn: ['Reduce salt intake', 'Exercise regularly (30 minutes per day)', 'Maintain a healthy weight', 'Limit alcohol intake', 'Monitor blood pressure at home regularly'],
    preguntasParaMedicoEs: ['¿Cuál es mi meta de presión arterial?', '¿Necesito medicamento o puedo manejarla con cambios de estilo de vida?', '¿Con qué frecuencia debo checar mi presión?'],
    preguntasParaMedicoEn: ['What is my blood pressure goal?', 'Do I need medication or can I manage with lifestyle changes?', 'How often should I check my blood pressure?'],
    sintomasRelacionados: ['dolor-de-cabeza', 'vision-borrosa', 'sangrado-nasal', 'dolor-de-pecho'],
    sistemasCorporales: ['cardiovascular']
  },
  // ---- RESPIRATORIO ----
  {
    id: 'tos',
    nombreEs: 'Tos',
    nombreEn: 'Cough',
    descripcionEs: 'Reflejo del cuerpo para limpiar las vías respiratorias de irritantes, mucosidad o cuerpos extraños. Puede ser seca o productiva (con flema).',
    descripcionEn: 'Body reflex to clear the airways of irritants, mucus, or foreign bodies. It can be dry or productive (with phlegm).',
    categorias: ['respiratorio'],
    urgencia: 'baja',
    causasComunesEs: ['Resfriado o gripe', 'Alergias', 'Asma', 'Reflujo gastroesofágico', 'Goteo posnasal', 'Medicamentos (inhibidores de la ECA)', 'Tabaquismo'],
    causasComunesEn: ['Cold or flu', 'Allergies', 'Asthma', 'Gastroesophageal reflux', 'Postnasal drip', 'Medications (ACE inhibitors)', 'Smoking'],
    cuandoVerMedicoEs: ['Tos que dura más de 3 semanas', 'Tos con sangre', 'Tos con dificultad para respirar', 'Tos con fiebre alta', 'Tos que empeora por la noche impidiendo dormir'],
    cuandoVerMedicoEn: ['Cough lasting more than 3 weeks', 'Cough with blood', 'Cough with difficulty breathing', 'Cough with high fever', 'Cough worsening at night preventing sleep'],
    autoCuidadoEs: ['Beber líquidos tibios con miel', 'Usar humidificador', 'Evitar humo y otros irritantes', 'Elevar la cabeza al dormir', 'Chupar pastillas para la tos'],
    autoCuidadoEn: ['Drink warm liquids with honey', 'Use a humidifier', 'Avoid smoke and other irritants', 'Elevate head when sleeping', 'Suck on cough drops'],
    preguntasParaMedicoEs: ['¿Mi tos podría ser asma?', '¿Necesito una radiografía de tórax?', '¿Algún medicamento que tomo podría causar tos?'],
    preguntasParaMedicoEn: ['Could my cough be asthma?', 'Do I need a chest X-ray?', 'Could any medication I take be causing the cough?'],
    sintomasRelacionados: ['falta-de-aire', 'congestion-nasal', 'dolor-de-garganta', 'sibilancias', 'tos-con-sangre'],
    sistemasCorporales: ['respiratorio']
  },
  {
    id: 'tos-con-sangre',
    nombreEs: 'Tos con sangre (hemoptisis)',
    nombreEn: 'Coughing up blood (hemoptysis)',
    descripcionEs: 'Expulsión de sangre o moco con sangre al toser, proveniente de las vías respiratorias o los pulmones.',
    descripcionEn: 'Expelling blood or blood-streaked mucus when coughing, coming from the airways or lungs.',
    categorias: ['respiratorio'],
    urgencia: 'emergencia',
    causasComunesEs: ['Bronquitis aguda o crónica', 'Neumonía', 'Tuberculosis', 'Cáncer de pulmón', 'Embolia pulmonar', 'Bronquiectasias'],
    causasComunesEn: ['Acute or chronic bronchitis', 'Pneumonia', 'Tuberculosis', 'Lung cancer', 'Pulmonary embolism', 'Bronchiectasis'],
    cuandoVerMedicoEs: ['Cualquier episodio de tos con sangre amerita evaluación', 'Tos con sangre abundante: ir a urgencias', 'Tos con sangre con dificultad para respirar', 'Tos con sangre recurrente'],
    cuandoVerMedicoEn: ['Any episode of coughing up blood warrants evaluation', 'Coughing up large amounts of blood: go to ER', 'Coughing up blood with difficulty breathing', 'Recurrent blood-tinged cough'],
    autoCuidadoEs: ['Mantener la calma', 'Sentarse erguido', 'No tomar aspirina ni anticoagulantes sin indicación', 'Buscar atención médica de inmediato'],
    autoCuidadoEn: ['Stay calm', 'Sit upright', 'Do not take aspirin or blood thinners without guidance', 'Seek medical attention immediately'],
    preguntasParaMedicoEs: ['¿De dónde viene el sangrado?', '¿Necesito una tomografía o broncoscopia?', '¿Podría ser algo grave como cáncer?'],
    preguntasParaMedicoEn: ['Where is the bleeding coming from?', 'Do I need a CT scan or bronchoscopy?', 'Could it be something serious like cancer?'],
    sintomasRelacionados: ['tos', 'falta-de-aire', 'dolor-de-pecho', 'perdida-de-peso'],
    sistemasCorporales: ['respiratorio']
  },
  {
    id: 'sibilancias',
    nombreEs: 'Sibilancias',
    nombreEn: 'Wheezing',
    descripcionEs: 'Sonido silbante agudo que se produce al respirar, especialmente al exhalar. Indica estrechamiento de las vías respiratorias.',
    descripcionEn: 'High-pitched whistling sound produced when breathing, especially when exhaling. Indicates narrowing of the airways.',
    categorias: ['respiratorio'],
    urgencia: 'media',
    causasComunesEs: ['Asma', 'EPOC', 'Bronquitis', 'Alergias', 'Infecciones respiratorias', 'Insuficiencia cardíaca', 'Cuerpo extraño aspirado'],
    causasComunesEn: ['Asthma', 'COPD', 'Bronchitis', 'Allergies', 'Respiratory infections', 'Heart failure', 'Aspirated foreign body'],
    cuandoVerMedicoEs: ['Sibilancias nuevas o que empeoran', 'Sibilancias con dificultad respiratoria significativa', 'Sibilancias acompañadas de labios o piel azulada', 'Sibilancias que no mejoran con el inhalador'],
    cuandoVerMedicoEn: ['New or worsening wheezing', 'Wheezing with significant breathing difficulty', 'Wheezing with blue lips or skin', 'Wheezing not improving with inhaler'],
    autoCuidadoEs: ['Usar el inhalador de rescate si está prescrito', 'Alejarse de alérgenos conocidos', 'Mantener la calma y respirar lentamente', 'Beber líquidos tibios'],
    autoCuidadoEn: ['Use rescue inhaler if prescribed', 'Move away from known allergens', 'Stay calm and breathe slowly', 'Drink warm fluids'],
    preguntasParaMedicoEs: ['¿Tengo asma?', '¿Necesito pruebas de función pulmonar?', '¿Debo usar un inhalador diariamente?'],
    preguntasParaMedicoEn: ['Do I have asthma?', 'Do I need pulmonary function tests?', 'Should I use an inhaler daily?'],
    sintomasRelacionados: ['tos', 'falta-de-aire', 'dolor-de-pecho', 'dificultad-para-respirar'],
    sistemasCorporales: ['respiratorio']
  },
  {
    id: 'dificultad-para-respirar',
    nombreEs: 'Dificultad para respirar',
    nombreEn: 'Difficulty breathing',
    descripcionEs: 'Sensación de esfuerzo excesivo para respirar, respiración trabajosa o sensación de ahogo. Diferente de la falta de aire leve con el esfuerzo.',
    descripcionEn: 'Sensation of excessive effort to breathe, labored breathing, or feeling of suffocation. Different from mild shortness of breath with exertion.',
    categorias: ['respiratorio'],
    urgencia: 'emergencia',
    causasComunesEs: ['Crisis asmática severa', 'Neumonía grave', 'Embolia pulmonar', 'Neumotórax', 'Reacción alérgica severa (anafilaxia)', 'EPOC exacerbada'],
    causasComunesEn: ['Severe asthma attack', 'Severe pneumonia', 'Pulmonary embolism', 'Pneumothorax', 'Severe allergic reaction (anaphylaxis)', 'COPD exacerbation'],
    cuandoVerMedicoEs: ['Dificultad respiratoria severa: llamar al 911', 'Labios o uñas azuladas', 'Incapacidad para completar frases', 'Respiración muy rápida o superficial'],
    cuandoVerMedicoEn: ['Severe breathing difficulty: call 911', 'Blue lips or nails', 'Inability to complete sentences', 'Very rapid or shallow breathing'],
    autoCuidadoEs: ['Sentarse erguido o inclinado hacia adelante', 'Usar medicamentos de rescate si están prescritos', 'Aflojar ropa ajustada', 'Abrir ventanas para aire fresco', 'Llamar a emergencias si es severo'],
    autoCuidadoEn: ['Sit upright or lean forward', 'Use rescue medications if prescribed', 'Loosen tight clothing', 'Open windows for fresh air', 'Call emergency services if severe'],
    preguntasParaMedicoEs: ['¿Necesito oxígeno en casa?', '¿Qué debo hacer si tengo una crisis respiratoria?', '¿Debo tener un plan de acción para el asma?'],
    preguntasParaMedicoEn: ['Do I need oxygen at home?', 'What should I do if I have a respiratory crisis?', 'Should I have an asthma action plan?'],
    sintomasRelacionados: ['falta-de-aire', 'sibilancias', 'tos', 'dolor-de-pecho', 'respiracion-rapida'],
    sistemasCorporales: ['respiratorio']
  },
  {
    id: 'respiracion-rapida',
    nombreEs: 'Respiración rápida (taquipnea)',
    nombreEn: 'Rapid breathing (tachypnea)',
    descripcionEs: 'Frecuencia respiratoria anormalmente elevada, generalmente más de 20 respiraciones por minuto en adultos en reposo.',
    descripcionEn: 'Abnormally elevated respiratory rate, generally more than 20 breaths per minute in resting adults.',
    categorias: ['respiratorio'],
    urgencia: 'alta',
    causasComunesEs: ['Fiebre alta', 'Ansiedad o ataques de pánico', 'Neumonía', 'Acidosis metabólica', 'Embolia pulmonar', 'Sepsis'],
    causasComunesEn: ['High fever', 'Anxiety or panic attacks', 'Pneumonia', 'Metabolic acidosis', 'Pulmonary embolism', 'Sepsis'],
    cuandoVerMedicoEs: ['Respiración rápida persistente en reposo', 'Respiración rápida con confusión o somnolencia', 'Respiración rápida con dolor de pecho', 'Respiración rápida en niños con tiraje intercostal'],
    cuandoVerMedicoEn: ['Persistent rapid breathing at rest', 'Rapid breathing with confusion or drowsiness', 'Rapid breathing with chest pain', 'Rapid breathing in children with intercostal retractions'],
    autoCuidadoEs: ['Intentar técnicas de respiración lenta y profunda', 'Si es por ansiedad: respirar en bolsa de papel brevemente', 'Sentarse cómodamente', 'Buscar atención médica si persiste'],
    autoCuidadoEn: ['Try slow deep breathing techniques', 'If due to anxiety: briefly breathe into paper bag', 'Sit comfortably', 'Seek medical attention if persistent'],
    preguntasParaMedicoEs: ['¿Mi respiración rápida indica un problema pulmonar?', '¿Necesito gasometría arterial?', '¿Podría ser por ansiedad?'],
    preguntasParaMedicoEn: ['Does my rapid breathing indicate a lung problem?', 'Do I need arterial blood gas testing?', 'Could it be from anxiety?'],
    sintomasRelacionados: ['falta-de-aire', 'dificultad-para-respirar', 'fiebre', 'ansiedad', 'dolor-de-pecho'],
    sistemasCorporales: ['respiratorio']
  }
];
