// =============================================================================
// Batch 4: Musculoskeletal + Skin + Reproductive + Mental Symptoms
// =============================================================================

import type { SintomaEntry } from './tipos';

export const SINTOMAS_MSK_PIEL_REPRO_MENTAL: SintomaEntry[] = [
  // ---- MUSCULOESQUELÉTICO ----
  {
    id: 'dolor-de-espalda',
    nombreEs: 'Dolor de espalda',
    nombreEn: 'Back pain',
    descripcionEs: 'Dolor en cualquier zona de la espalda, desde la región cervical hasta la lumbar. Es una de las causas más comunes de discapacidad laboral.',
    descripcionEn: 'Pain in any area of the back, from the cervical to the lumbar region. It is one of the most common causes of work disability.',
    categorias: ['musculoesquelético'],
    urgencia: 'baja',
    causasComunesEs: ['Tensión muscular o esguince', 'Hernia de disco', 'Artritis degenerativa', 'Mala postura', 'Ciática', 'Estenosis espinal', 'Osteoporosis'],
    causasComunesEn: ['Muscle strain or sprain', 'Herniated disc', 'Degenerative arthritis', 'Poor posture', 'Sciatica', 'Spinal stenosis', 'Osteoporosis'],
    cuandoVerMedicoEs: ['Dolor de espalda con pérdida del control de esfínteres', 'Dolor que irradia a las piernas con debilidad', 'Dolor de espalda después de un traumatismo', 'Dolor nocturno que despierta del sueño', 'Dolor con fiebre o pérdida de peso'],
    cuandoVerMedicoEn: ['Back pain with loss of bladder or bowel control', 'Pain radiating to legs with weakness', 'Back pain after trauma', 'Night pain that wakes from sleep', 'Pain with fever or weight loss'],
    autoCuidadoEs: ['Mantenerse activo (reposo en cama NO recomendado)', 'Aplicar calor o frío local', 'Hacer ejercicios de fortalecimiento del core', 'Mantener una buena postura', 'Tomar analgésicos de venta libre si es necesario'],
    autoCuidadoEn: ['Stay active (bed rest NOT recommended)', 'Apply local heat or cold', 'Do core strengthening exercises', 'Maintain good posture', 'Take over-the-counter pain relievers if needed'],
    preguntasParaMedicoEs: ['¿Necesito una resonancia magnética?', '¿Me beneficiaría la fisioterapia?', '¿Podría ser una hernia de disco?'],
    preguntasParaMedicoEn: ['Do I need an MRI?', 'Would physical therapy benefit me?', 'Could it be a herniated disc?'],
    sintomasRelacionados: ['entumecimiento', 'hormigueo', 'debilidad-muscular', 'rigidez', 'dolor-articular'],
    sistemasCorporales: ['musculoesquelético']
  },
  {
    id: 'dolor-articular',
    nombreEs: 'Dolor articular',
    nombreEn: 'Joint pain',
    descripcionEs: 'Dolor, sensibilidad o molestia en una o más articulaciones del cuerpo. Puede afectar la movilidad y la calidad de vida.',
    descripcionEn: 'Pain, tenderness, or discomfort in one or more joints of the body. It can affect mobility and quality of life.',
    categorias: ['musculoesquelético'],
    urgencia: 'baja',
    causasComunesEs: ['Osteoartritis (desgaste)', 'Artritis reumatoide', 'Gota', 'Bursitis', 'Tendinitis', 'Lesiones deportivas', 'Lupus'],
    causasComunesEn: ['Osteoarthritis (wear and tear)', 'Rheumatoid arthritis', 'Gout', 'Bursitis', 'Tendinitis', 'Sports injuries', 'Lupus'],
    cuandoVerMedicoEs: ['Articulación roja, caliente e hinchada (posible infección)', 'Dolor articular con fiebre', 'Dolor que impide actividades normales', 'Dolor en múltiples articulaciones de inicio reciente', 'Deformidad articular'],
    cuandoVerMedicoEn: ['Red, warm, and swollen joint (possible infection)', 'Joint pain with fever', 'Pain preventing normal activities', 'Recent onset pain in multiple joints', 'Joint deformity'],
    autoCuidadoEs: ['Alternar calor y frío', 'Mantener las articulaciones en movimiento con ejercicio suave', 'Mantener un peso saludable', 'Usar soportes o férulas si es necesario', 'Tomar antiinflamatorios según indicaciones'],
    autoCuidadoEn: ['Alternate heat and cold', 'Keep joints moving with gentle exercise', 'Maintain a healthy weight', 'Use braces or splints if needed', 'Take anti-inflammatories as directed'],
    preguntasParaMedicoEs: ['¿Podría tener artritis?', '¿Necesito análisis de sangre para inflamación?', '¿Me beneficiaría la inyección articular?'],
    preguntasParaMedicoEn: ['Could I have arthritis?', 'Do I need blood tests for inflammation?', 'Would a joint injection benefit me?'],
    sintomasRelacionados: ['rigidez', 'inflamacion-articular', 'debilidad-muscular', 'dolor-de-espalda'],
    sistemasCorporales: ['musculoesquelético']
  },
  {
    id: 'rigidez',
    nombreEs: 'Rigidez articular',
    nombreEn: 'Joint stiffness',
    descripcionEs: 'Dificultad para mover una articulación con libertad, sensación de que la articulación está trabada o agarrotada, especialmente al despertar.',
    descripcionEn: 'Difficulty moving a joint freely, feeling that the joint is locked or stiff, especially upon waking.',
    categorias: ['musculoesquelético'],
    urgencia: 'baja',
    causasComunesEs: ['Osteoartritis', 'Artritis reumatoide', 'Falta de actividad física', 'Lesiones previas', 'Enfermedad de Parkinson', 'Fibromialgia'],
    causasComunesEn: ['Osteoarthritis', 'Rheumatoid arthritis', 'Lack of physical activity', 'Previous injuries', 'Parkinson disease', 'Fibromyalgia'],
    cuandoVerMedicoEs: ['Rigidez matutina que dura más de 30 minutos', 'Rigidez que empeora con el tiempo', 'Rigidez con hinchazón articular', 'Rigidez que limita las actividades diarias'],
    cuandoVerMedicoEn: ['Morning stiffness lasting more than 30 minutes', 'Stiffness that worsens over time', 'Stiffness with joint swelling', 'Stiffness limiting daily activities'],
    autoCuidadoEs: ['Hacer estiramientos suaves por la mañana', 'Aplicar calor a las articulaciones rígidas', 'Mantenerse físicamente activo', 'Realizar ejercicios de rango de movimiento'],
    autoCuidadoEn: ['Do gentle stretches in the morning', 'Apply heat to stiff joints', 'Stay physically active', 'Perform range-of-motion exercises'],
    preguntasParaMedicoEs: ['¿Mi rigidez matutina podría indicar artritis reumatoide?', '¿Necesito análisis de factor reumatoide?', '¿La fisioterapia ayudaría?'],
    preguntasParaMedicoEn: ['Could my morning stiffness indicate rheumatoid arthritis?', 'Do I need rheumatoid factor testing?', 'Would physical therapy help?'],
    sintomasRelacionados: ['dolor-articular', 'inflamacion-articular', 'dolor-de-espalda', 'debilidad-muscular'],
    sistemasCorporales: ['musculoesquelético']
  },
  {
    id: 'inflamacion-articular',
    nombreEs: 'Inflamación articular',
    nombreEn: 'Joint swelling',
    descripcionEs: 'Aumento de tamaño de una articulación debido a acumulación de líquido, inflamación de los tejidos o proliferación ósea.',
    descripcionEn: 'Increase in joint size due to fluid accumulation, tissue inflammation, or bone proliferation.',
    categorias: ['musculoesquelético'],
    urgencia: 'media',
    causasComunesEs: ['Artritis (osteoartritis, reumatoide, gotosa)', 'Lesiones (esguinces, fracturas)', 'Bursitis', 'Infección articular (artritis séptica)', 'Lupus'],
    causasComunesEn: ['Arthritis (osteoarthritis, rheumatoid, gouty)', 'Injuries (sprains, fractures)', 'Bursitis', 'Joint infection (septic arthritis)', 'Lupus'],
    cuandoVerMedicoEs: ['Articulación muy hinchada, roja y caliente', 'Inflamación con fiebre', 'Inflamación después de una lesión', 'Inflamación que no mejora en días', 'Inflamación en múltiples articulaciones'],
    cuandoVerMedicoEn: ['Very swollen, red, and warm joint', 'Swelling with fever', 'Swelling after injury', 'Swelling not improving in days', 'Swelling in multiple joints'],
    autoCuidadoEs: ['Reposo relativo de la articulación afectada', 'Aplicar hielo envuelto en tela', 'Elevar la articulación afectada', 'Usar compresión suave', 'Tomar antiinflamatorios'],
    autoCuidadoEn: ['Relative rest of the affected joint', 'Apply ice wrapped in cloth', 'Elevate the affected joint', 'Use gentle compression', 'Take anti-inflammatories'],
    preguntasParaMedicoEs: ['¿Necesito que me aspiren líquido de la articulación?', '¿Podría ser gota?', '¿Necesito radiografías?'],
    preguntasParaMedicoEn: ['Do I need fluid aspirated from the joint?', 'Could it be gout?', 'Do I need X-rays?'],
    sintomasRelacionados: ['dolor-articular', 'rigidez', 'fiebre', 'ojo-rojo'],
    sistemasCorporales: ['musculoesquelético']
  },
  {
    id: 'debilidad-muscular',
    nombreEs: 'Debilidad muscular',
    nombreEn: 'Muscle weakness',
    descripcionEs: 'Reducción de la fuerza en uno o más grupos musculares, lo que dificulta la realización de movimientos voluntarios normales.',
    descripcionEn: 'Reduction in strength in one or more muscle groups, making it difficult to perform normal voluntary movements.',
    categorias: ['musculoesquelético', 'neurológico'],
    urgencia: 'media',
    causasComunesEs: ['Falta de uso muscular (desacondicionamiento)', 'Enfermedades neuromusculares', 'Deficiencias de electrolitos', 'Hipotiroidismo', 'Medicamentos (estatinas)', 'Miastenia gravis'],
    causasComunesEn: ['Lack of muscle use (deconditioning)', 'Neuromuscular diseases', 'Electrolyte deficiencies', 'Hypothyroidism', 'Medications (statins)', 'Myasthenia gravis'],
    cuandoVerMedicoEs: ['Debilidad muscular progresiva', 'Debilidad repentina en un lado del cuerpo', 'Debilidad con dificultad para tragar o respirar', 'Debilidad con dolor muscular severo'],
    cuandoVerMedicoEn: ['Progressive muscle weakness', 'Sudden weakness on one side of the body', 'Weakness with difficulty swallowing or breathing', 'Weakness with severe muscle pain'],
    autoCuidadoEs: ['Hacer ejercicio de fortalecimiento progresivo', 'Mantener una buena nutrición con proteínas adecuadas', 'Descansar entre actividades', 'Consultar con un fisioterapeuta'],
    autoCuidadoEn: ['Do progressive strengthening exercises', 'Maintain good nutrition with adequate protein', 'Rest between activities', 'Consult a physical therapist'],
    preguntasParaMedicoEs: ['¿Mi debilidad podría ser neurológica?', '¿Necesito pruebas de electromiografía?', '¿Mis medicamentos podrían estar causando debilidad?'],
    preguntasParaMedicoEn: ['Could my weakness be neurological?', 'Do I need electromyography tests?', 'Could my medications be causing weakness?'],
    sintomasRelacionados: ['fatiga', 'entumecimiento', 'calambres', 'dolor-articular', 'debilidad'],
    sistemasCorporales: ['musculoesquelético', 'neurológico']
  },
  {
    id: 'calambres',
    nombreEs: 'Calambres musculares',
    nombreEn: 'Muscle cramps',
    descripcionEs: 'Contracciones musculares involuntarias, repentinas y dolorosas. Generalmente afectan las piernas y suelen ocurrir durante la noche.',
    descripcionEn: 'Involuntary, sudden, and painful muscle contractions. They usually affect the legs and often occur during the night.',
    categorias: ['musculoesquelético'],
    urgencia: 'baja',
    causasComunesEs: ['Deshidratación', 'Deficiencia de electrolitos (potasio, magnesio, calcio)', 'Ejercicio excesivo', 'Mala circulación', 'Compresión nerviosa', 'Ciertos medicamentos (diuréticos, estatinas)'],
    causasComunesEn: ['Dehydration', 'Electrolyte deficiency (potassium, magnesium, calcium)', 'Excessive exercise', 'Poor circulation', 'Nerve compression', 'Certain medications (diuretics, statins)'],
    cuandoVerMedicoEs: ['Calambres muy frecuentes o severos', 'Calambres que no mejoran con medidas caseras', 'Calambres con debilidad o hinchazón muscular', 'Calambres que interfieren con el sueño regularmente'],
    cuandoVerMedicoEn: ['Very frequent or severe cramps', 'Cramps not improving with home measures', 'Cramps with muscle weakness or swelling', 'Cramps regularly interfering with sleep'],
    autoCuidadoEs: ['Estirar el músculo afectado suavemente', 'Mantenerse bien hidratado', 'Consumir alimentos ricos en potasio y magnesio', 'Hacer estiramientos antes de dormir', 'Aplicar calor al músculo acalambrado'],
    autoCuidadoEn: ['Gently stretch the affected muscle', 'Stay well hydrated', 'Eat foods rich in potassium and magnesium', 'Stretch before bed', 'Apply heat to the cramped muscle'],
    preguntasParaMedicoEs: ['¿Mis niveles de electrolitos están bien?', '¿Debería tomar suplementos de magnesio?', '¿Alguno de mis medicamentos causa calambres?'],
    preguntasParaMedicoEn: ['Are my electrolyte levels okay?', 'Should I take magnesium supplements?', 'Do any of my medications cause cramps?'],
    sintomasRelacionados: ['debilidad-muscular', 'hormigueo', 'dolor-articular', 'hinchazón-de-piernas'],
    sistemasCorporales: ['musculoesquelético']
  },
  // ---- PIEL ----
  {
    id: 'erupcion-cutanea',
    nombreEs: 'Erupción cutánea',
    nombreEn: 'Skin rash',
    descripcionEs: 'Cambio visible en la textura o color de la piel que puede incluir enrojecimiento, ampollas, descamación, protuberancias o manchas.',
    descripcionEn: 'Visible change in skin texture or color that may include redness, blisters, scaling, bumps, or patches.',
    categorias: ['dermatológico'],
    urgencia: 'baja',
    causasComunesEs: ['Dermatitis de contacto', 'Eccema (dermatitis atópica)', 'Alergias a medicamentos', 'Infecciones virales', 'Infecciones fúngicas', 'Psoriasis'],
    causasComunesEn: ['Contact dermatitis', 'Eczema (atopic dermatitis)', 'Drug allergies', 'Viral infections', 'Fungal infections', 'Psoriasis'],
    cuandoVerMedicoEs: ['Erupción que cubre gran parte del cuerpo', 'Erupción con fiebre', 'Erupción que se extiende rápidamente', 'Erupción con ampollas o piel desprendida', 'Erupción dolorosa'],
    cuandoVerMedicoEn: ['Rash covering a large area of the body', 'Rash with fever', 'Rapidly spreading rash', 'Rash with blisters or peeling skin', 'Painful rash'],
    autoCuidadoEs: ['Evitar rascarse', 'Aplicar crema hidratante sin fragancia', 'Usar compresas frías para aliviar la comezón', 'Identificar y evitar posibles desencadenantes', 'Usar ropa de algodón suave'],
    autoCuidadoEn: ['Avoid scratching', 'Apply fragrance-free moisturizer', 'Use cold compresses to relieve itching', 'Identify and avoid possible triggers', 'Wear soft cotton clothing'],
    preguntasParaMedicoEs: ['¿Podría ser una reacción alérgica?', '¿Necesito una biopsia de piel?', '¿Es contagioso?'],
    preguntasParaMedicoEn: ['Could it be an allergic reaction?', 'Do I need a skin biopsy?', 'Is it contagious?'],
    sintomasRelacionados: ['picazon', 'urticaria', 'fiebre', 'dolor-articular'],
    sistemasCorporales: ['dermatológico']
  },
  {
    id: 'picazon',
    nombreEs: 'Picazón (prurito)',
    nombreEn: 'Itching (pruritus)',
    descripcionEs: 'Sensación irritante en la piel que provoca el deseo de rascarse. Puede ser localizada o generalizada por todo el cuerpo.',
    descripcionEn: 'Irritating sensation in the skin that causes the desire to scratch. It can be localized or generalized throughout the body.',
    categorias: ['dermatológico'],
    urgencia: 'baja',
    causasComunesEs: ['Piel seca', 'Dermatitis', 'Alergias', 'Picaduras de insectos', 'Enfermedades hepáticas', 'Enfermedades renales', 'Reacciones a medicamentos'],
    causasComunesEn: ['Dry skin', 'Dermatitis', 'Allergies', 'Insect bites', 'Liver diseases', 'Kidney diseases', 'Drug reactions'],
    cuandoVerMedicoEs: ['Picazón generalizada sin erupción visible', 'Picazón que interfiere con el sueño', 'Picazón que dura más de 2 semanas', 'Picazón con piel amarillenta (ictericia)'],
    cuandoVerMedicoEn: ['Generalized itching without visible rash', 'Itching interfering with sleep', 'Itching lasting more than 2 weeks', 'Itching with yellowish skin (jaundice)'],
    autoCuidadoEs: ['Hidratar la piel frecuentemente', 'Usar jabones suaves sin fragancia', 'Evitar baños muy calientes o prolongados', 'Aplicar compresas frías', 'Usar antihistamínicos de venta libre'],
    autoCuidadoEn: ['Moisturize skin frequently', 'Use mild fragrance-free soaps', 'Avoid very hot or prolonged baths', 'Apply cold compresses', 'Use over-the-counter antihistamines'],
    preguntasParaMedicoEs: ['¿La picazón podría ser señal de algo interno?', '¿Debería hacerme pruebas de función hepática o renal?', '¿Necesito un dermatólogo?'],
    preguntasParaMedicoEn: ['Could the itching be a sign of something internal?', 'Should I get liver or kidney function tests?', 'Do I need a dermatologist?'],
    sintomasRelacionados: ['erupcion-cutanea', 'urticaria', 'piel-seca', 'ojo-rojo'],
    sistemasCorporales: ['dermatológico']
  },
  {
    id: 'urticaria',
    nombreEs: 'Urticaria (ronchas)',
    nombreEn: 'Hives (urticaria)',
    descripcionEs: 'Ronchas elevadas, rojas y con picazón que aparecen en la piel. Pueden cambiar de forma y lugar en cuestión de horas.',
    descripcionEn: 'Raised, red, itchy welts that appear on the skin. They can change shape and location within hours.',
    categorias: ['dermatológico', 'inmunológico'],
    urgencia: 'media',
    causasComunesEs: ['Reacciones alérgicas a alimentos o medicamentos', 'Picaduras de insectos', 'Infecciones virales', 'Estrés', 'Exposición al frío o calor', 'Causa desconocida (urticaria idiopática)'],
    causasComunesEn: ['Allergic reactions to food or medications', 'Insect stings', 'Viral infections', 'Stress', 'Cold or heat exposure', 'Unknown cause (idiopathic urticaria)'],
    cuandoVerMedicoEs: ['Urticaria con hinchazón de labios, lengua o garganta (anafilaxia)', 'Urticaria con dificultad para respirar: llamar al 911', 'Urticaria que dura más de 6 semanas', 'Urticaria recurrente'],
    cuandoVerMedicoEn: ['Hives with swelling of lips, tongue, or throat (anaphylaxis)', 'Hives with difficulty breathing: call 911', 'Hives lasting more than 6 weeks', 'Recurrent hives'],
    autoCuidadoEs: ['Tomar antihistamínicos de venta libre', 'Evitar alérgenos conocidos', 'Aplicar compresas frías', 'Usar ropa holgada y suave', 'Evitar calor excesivo y estrés'],
    autoCuidadoEn: ['Take over-the-counter antihistamines', 'Avoid known allergens', 'Apply cold compresses', 'Wear loose soft clothing', 'Avoid excessive heat and stress'],
    preguntasParaMedicoEs: ['¿Necesito pruebas de alergia?', '¿Debería cargar epinefrina de emergencia?', '¿La urticaria podría indicar una enfermedad autoinmune?'],
    preguntasParaMedicoEn: ['Do I need allergy testing?', 'Should I carry emergency epinephrine?', 'Could hives indicate an autoimmune disease?'],
    sintomasRelacionados: ['picazon', 'erupcion-cutanea', 'falta-de-aire', 'dificultad-para-tragar'],
    sistemasCorporales: ['dermatológico', 'inmunológico']
  },
  {
    id: 'cambios-en-lunares',
    nombreEs: 'Cambios en lunares',
    nombreEn: 'Changes in moles',
    descripcionEs: 'Modificaciones en el tamaño, forma, color, bordes o textura de un lunar existente, o aparición de un lunar nuevo con características inusuales.',
    descripcionEn: 'Modifications in the size, shape, color, borders, or texture of an existing mole, or appearance of a new mole with unusual characteristics.',
    categorias: ['dermatológico'],
    urgencia: 'alta',
    causasComunesEs: ['Melanoma (cáncer de piel)', 'Nevos displásicos (lunares atípicos)', 'Cambios hormonales', 'Exposición solar crónica', 'Envejecimiento natural'],
    causasComunesEn: ['Melanoma (skin cancer)', 'Dysplastic nevi (atypical moles)', 'Hormonal changes', 'Chronic sun exposure', 'Natural aging'],
    cuandoVerMedicoEs: ['Lunar que cambia de tamaño, forma o color', 'Lunar asimétrico o con bordes irregulares', 'Lunar con múltiples colores', 'Lunar que sangra, pica o duele', 'Lunar nuevo después de los 30 años'],
    cuandoVerMedicoEn: ['Mole changing in size, shape, or color', 'Asymmetric mole or one with irregular borders', 'Mole with multiple colors', 'Mole that bleeds, itches, or hurts', 'New mole after age 30'],
    autoCuidadoEs: ['Revisarse la piel mensualmente', 'Usar regla ABCDE (Asimetría, Bordes, Color, Diámetro, Evolución)', 'Protegerse del sol con protector solar', 'Fotografiar lunares para seguimiento', 'Evitar camas de bronceado'],
    autoCuidadoEn: ['Check skin monthly', 'Use ABCDE rule (Asymmetry, Borders, Color, Diameter, Evolution)', 'Protect from sun with sunscreen', 'Photograph moles for monitoring', 'Avoid tanning beds'],
    preguntasParaMedicoEs: ['¿Necesito una biopsia de este lunar?', '¿Con qué frecuencia debo revisarme los lunares?', '¿Tengo mayor riesgo de melanoma?'],
    preguntasParaMedicoEn: ['Do I need a biopsy of this mole?', 'How often should I have my moles checked?', 'Am I at increased risk for melanoma?'],
    sintomasRelacionados: ['erupcion-cutanea', 'picazon', 'heridas-que-no-cicatrizan'],
    sistemasCorporales: ['dermatológico']
  },
  {
    id: 'heridas-que-no-cicatrizan',
    nombreEs: 'Heridas que no cicatrizan',
    nombreEn: 'Non-healing wounds',
    descripcionEs: 'Heridas o llagas en la piel que no muestran signos de curación después de un período razonable (generalmente más de 4 semanas).',
    descripcionEn: 'Wounds or sores on the skin that show no signs of healing after a reasonable period (generally more than 4 weeks).',
    categorias: ['dermatológico'],
    urgencia: 'alta',
    causasComunesEs: ['Diabetes mal controlada', 'Insuficiencia venosa', 'Enfermedad arterial periférica', 'Cáncer de piel', 'Infección de la herida', 'Uso de ciertos medicamentos (corticosteroides)'],
    causasComunesEn: ['Poorly controlled diabetes', 'Venous insufficiency', 'Peripheral arterial disease', 'Skin cancer', 'Wound infection', 'Use of certain medications (corticosteroids)'],
    cuandoVerMedicoEs: ['Herida que no mejora después de 2-4 semanas', 'Herida con signos de infección (pus, enrojecimiento, calor)', 'Herida que empeora o se agranda', 'Herida con mal olor'],
    cuandoVerMedicoEn: ['Wound not improving after 2-4 weeks', 'Wound with signs of infection (pus, redness, warmth)', 'Wound that worsens or enlarges', 'Foul-smelling wound'],
    autoCuidadoEs: ['Mantener la herida limpia y seca', 'Cambiar vendajes regularmente', 'Mantener un buen control de la diabetes si aplica', 'No fumar (el tabaco retarda la cicatrización)'],
    autoCuidadoEn: ['Keep the wound clean and dry', 'Change bandages regularly', 'Maintain good diabetes control if applicable', 'Do not smoke (tobacco delays healing)'],
    preguntasParaMedicoEs: ['¿Necesito una biopsia de la herida?', '¿Debería ver a un especialista en heridas?', '¿Mi diabetes podría estar afectando la cicatrización?'],
    preguntasParaMedicoEn: ['Do I need a wound biopsy?', 'Should I see a wound care specialist?', 'Could my diabetes be affecting healing?'],
    sintomasRelacionados: ['cambios-en-lunares', 'hinchazón-de-piernas', 'entumecimiento'],
    sistemasCorporales: ['dermatológico']
  },
  {
    id: 'piel-seca',
    nombreEs: 'Piel seca',
    nombreEn: 'Dry skin',
    descripcionEs: 'Piel que se siente áspera, tirante, escamosa o agrietada. Puede causar picazón y molestia, especialmente en climas fríos o secos.',
    descripcionEn: 'Skin that feels rough, tight, flaky, or cracked. It can cause itching and discomfort, especially in cold or dry climates.',
    categorias: ['dermatológico'],
    urgencia: 'baja',
    causasComunesEs: ['Clima frío y seco', 'Baños frecuentes con agua caliente', 'Jabones agresivos', 'Envejecimiento', 'Eccema', 'Hipotiroidismo', 'Deshidratación'],
    causasComunesEn: ['Cold and dry climate', 'Frequent hot water baths', 'Harsh soaps', 'Aging', 'Eczema', 'Hypothyroidism', 'Dehydration'],
    cuandoVerMedicoEs: ['Piel seca que no mejora con hidratación', 'Grietas profundas o sangrado', 'Piel seca con picazón severa', 'Piel seca generalizada con cambios recientes'],
    cuandoVerMedicoEn: ['Dry skin not improving with moisturizing', 'Deep cracks or bleeding', 'Dry skin with severe itching', 'Generalized dry skin with recent changes'],
    autoCuidadoEs: ['Aplicar crema hidratante después del baño', 'Usar jabones suaves y sin fragancia', 'Bañarse con agua tibia (no caliente)', 'Usar humidificador en casa', 'Beber suficiente agua'],
    autoCuidadoEn: ['Apply moisturizer after bathing', 'Use mild fragrance-free soaps', 'Bathe with warm (not hot) water', 'Use a humidifier at home', 'Drink enough water'],
    preguntasParaMedicoEs: ['¿Podría tener problemas de tiroides?', '¿Qué tipo de crema me recomienda?', '¿Podría ser eccema?'],
    preguntasParaMedicoEn: ['Could I have thyroid problems?', 'What type of cream do you recommend?', 'Could it be eczema?'],
    sintomasRelacionados: ['picazon', 'erupcion-cutanea', 'fatiga'],
    sistemasCorporales: ['dermatológico']
  },
  {
    id: 'sudoracion-excesiva',
    nombreEs: 'Sudoración excesiva (hiperhidrosis)',
    nombreEn: 'Excessive sweating (hyperhidrosis)',
    descripcionEs: 'Producción de sudor que excede lo necesario para regular la temperatura corporal. Puede afectar manos, pies, axilas o todo el cuerpo.',
    descripcionEn: 'Sweat production exceeding what is necessary to regulate body temperature. It can affect hands, feet, armpits, or the whole body.',
    categorias: ['dermatológico', 'endocrino'],
    urgencia: 'baja',
    causasComunesEs: ['Hiperhidrosis primaria (sin causa conocida)', 'Ansiedad', 'Menopausia', 'Hipertiroidismo', 'Diabetes (hipoglucemia)', 'Ciertos medicamentos', 'Infecciones'],
    causasComunesEn: ['Primary hyperhidrosis (no known cause)', 'Anxiety', 'Menopause', 'Hyperthyroidism', 'Diabetes (hypoglycemia)', 'Certain medications', 'Infections'],
    cuandoVerMedicoEs: ['Sudoración que interfiere con actividades diarias', 'Sudoración nocturna recurrente', 'Sudoración con pérdida de peso o fiebre', 'Sudoración de inicio reciente sin causa clara'],
    cuandoVerMedicoEn: ['Sweating interfering with daily activities', 'Recurrent night sweats', 'Sweating with weight loss or fever', 'Recent onset sweating without clear cause'],
    autoCuidadoEs: ['Usar antitranspirantes con cloruro de aluminio', 'Vestir ropa de telas naturales', 'Llevar ropa extra si es necesario', 'Evitar alimentos picantes y cafeína'],
    autoCuidadoEn: ['Use antiperspirants with aluminum chloride', 'Wear natural fabric clothing', 'Carry extra clothes if needed', 'Avoid spicy foods and caffeine'],
    preguntasParaMedicoEs: ['¿Hay tratamientos médicos para la sudoración excesiva?', '¿Podría ser un problema hormonal?', '¿Me beneficiarían las inyecciones de toxina botulínica?'],
    preguntasParaMedicoEn: ['Are there medical treatments for excessive sweating?', 'Could it be a hormonal problem?', 'Would botulinum toxin injections benefit me?'],
    sintomasRelacionados: ['sudoracion-nocturna', 'ansiedad', 'palpitaciones', 'perdida-de-peso'],
    sistemasCorporales: ['dermatológico', 'endocrino']
  },
  // ---- REPRODUCTIVO ----
  {
    id: 'sangrado-menstrual-abundante',
    nombreEs: 'Sangrado menstrual abundante (menorragia)',
    nombreEn: 'Heavy menstrual bleeding (menorrhagia)',
    descripcionEs: 'Sangrado menstrual excesivamente abundante o prolongado que interfiere con las actividades diarias. Usar más de una toalla por hora o sangrado que dura más de 7 días.',
    descripcionEn: 'Excessively heavy or prolonged menstrual bleeding that interferes with daily activities. Using more than one pad per hour or bleeding lasting more than 7 days.',
    categorias: ['reproductivo'],
    urgencia: 'media',
    causasComunesEs: ['Miomas uterinos', 'Desequilibrios hormonales', 'Pólipos endometriales', 'Dispositivo intrauterino (DIU)', 'Trastornos de la coagulación', 'Endometriosis'],
    causasComunesEn: ['Uterine fibroids', 'Hormonal imbalances', 'Endometrial polyps', 'Intrauterine device (IUD)', 'Bleeding disorders', 'Endometriosis'],
    cuandoVerMedicoEs: ['Necesitar cambiar protección cada hora', 'Pasar coágulos grandes', 'Sangrado que dura más de 7 días', 'Signos de anemia (fatiga, mareos)', 'Sangrado entre períodos'],
    cuandoVerMedicoEn: ['Needing to change protection every hour', 'Passing large clots', 'Bleeding lasting more than 7 days', 'Signs of anemia (fatigue, dizziness)', 'Bleeding between periods'],
    autoCuidadoEs: ['Llevar un registro de su ciclo menstrual', 'Consumir alimentos ricos en hierro', 'Descansar durante los días de sangrado abundante', 'Usar protección doble si es necesario'],
    autoCuidadoEn: ['Keep track of your menstrual cycle', 'Eat iron-rich foods', 'Rest during heavy bleeding days', 'Use double protection if needed'],
    preguntasParaMedicoEs: ['¿Debería hacerme un ultrasonido pélvico?', '¿Necesito análisis de anemia?', '¿Hay tratamientos hormonales que puedan ayudar?'],
    preguntasParaMedicoEn: ['Should I get a pelvic ultrasound?', 'Do I need anemia testing?', 'Are there hormonal treatments that can help?'],
    sintomasRelacionados: ['dolor-menstrual', 'fatiga', 'mareos', 'dolor-abdominal'],
    sistemasCorporales: ['reproductivo']
  },
  {
    id: 'dolor-menstrual',
    nombreEs: 'Dolor menstrual (dismenorrea)',
    nombreEn: 'Menstrual pain (dysmenorrhea)',
    descripcionEs: 'Dolor tipo cólico en la parte baja del abdomen que ocurre antes o durante la menstruación. Puede irradiarse a la espalda baja y los muslos.',
    descripcionEn: 'Cramping pain in the lower abdomen occurring before or during menstruation. It can radiate to the lower back and thighs.',
    categorias: ['reproductivo'],
    urgencia: 'baja',
    causasComunesEs: ['Producción excesiva de prostaglandinas', 'Endometriosis', 'Miomas uterinos', 'Adenomiosis', 'Enfermedad inflamatoria pélvica', 'Estenosis cervical'],
    causasComunesEn: ['Excessive prostaglandin production', 'Endometriosis', 'Uterine fibroids', 'Adenomyosis', 'Pelvic inflammatory disease', 'Cervical stenosis'],
    cuandoVerMedicoEs: ['Dolor que no mejora con analgésicos comunes', 'Dolor que empeora con cada ciclo', 'Dolor que incapacita para trabajar o estudiar', 'Dolor con sangrado muy abundante'],
    cuandoVerMedicoEn: ['Pain not improving with common pain relievers', 'Pain worsening with each cycle', 'Pain that prevents work or study', 'Pain with very heavy bleeding'],
    autoCuidadoEs: ['Aplicar calor en el bajo vientre', 'Tomar ibuprofeno o naproxeno al inicio de los síntomas', 'Hacer ejercicio suave', 'Practicar técnicas de relajación', 'Tomar baños calientes'],
    autoCuidadoEn: ['Apply heat to the lower abdomen', 'Take ibuprofen or naproxen at onset of symptoms', 'Do gentle exercise', 'Practice relaxation techniques', 'Take warm baths'],
    preguntasParaMedicoEs: ['¿Podría tener endometriosis?', '¿Los anticonceptivos podrían ayudar con el dolor?', '¿Necesito una laparoscopia diagnóstica?'],
    preguntasParaMedicoEn: ['Could I have endometriosis?', 'Could birth control help with the pain?', 'Do I need a diagnostic laparoscopy?'],
    sintomasRelacionados: ['sangrado-menstrual-abundante', 'dolor-abdominal', 'dolor-de-espalda', 'nauseas'],
    sistemasCorporales: ['reproductivo']
  },
  {
    id: 'secrecion-vaginal',
    nombreEs: 'Secreción vaginal anormal',
    nombreEn: 'Abnormal vaginal discharge',
    descripcionEs: 'Cambio en el color, olor, consistencia o cantidad del flujo vaginal normal. Puede indicar una infección u otra condición.',
    descripcionEn: 'Change in the color, odor, consistency, or amount of normal vaginal discharge. It may indicate an infection or other condition.',
    categorias: ['reproductivo'],
    urgencia: 'media',
    causasComunesEs: ['Vaginosis bacteriana', 'Candidiasis vaginal', 'Tricomoniasis', 'Infección de transmisión sexual', 'Cambios hormonales', 'Reacción a productos de higiene'],
    causasComunesEn: ['Bacterial vaginosis', 'Vaginal candidiasis', 'Trichomoniasis', 'Sexually transmitted infection', 'Hormonal changes', 'Reaction to hygiene products'],
    cuandoVerMedicoEs: ['Secreción con mal olor', 'Secreción verdosa o grisácea', 'Secreción espesa como requesón con picazón', 'Secreción con dolor pélvico o fiebre', 'Secreción con sangrado fuera del período'],
    cuandoVerMedicoEn: ['Foul-smelling discharge', 'Greenish or grayish discharge', 'Thick cottage cheese-like discharge with itching', 'Discharge with pelvic pain or fever', 'Discharge with bleeding outside period'],
    autoCuidadoEs: ['Evitar duchas vaginales', 'Usar ropa interior de algodón', 'Evitar jabones perfumados en el área genital', 'Practicar buena higiene', 'Usar protección en relaciones sexuales'],
    autoCuidadoEn: ['Avoid vaginal douching', 'Wear cotton underwear', 'Avoid scented soaps in the genital area', 'Practice good hygiene', 'Use protection during sexual intercourse'],
    preguntasParaMedicoEs: ['¿Necesito un cultivo vaginal?', '¿Podría ser una infección de transmisión sexual?', '¿Mi pareja necesita tratamiento también?'],
    preguntasParaMedicoEn: ['Do I need a vaginal culture?', 'Could it be a sexually transmitted infection?', 'Does my partner need treatment too?'],
    sintomasRelacionados: ['picazon', 'dolor-al-orinar', 'dolor-abdominal', 'fiebre'],
    sistemasCorporales: ['reproductivo']
  },
  {
    id: 'disfuncion-erectil',
    nombreEs: 'Disfunción eréctil',
    nombreEn: 'Erectile dysfunction',
    descripcionEs: 'Dificultad persistente para lograr o mantener una erección suficiente para una actividad sexual satisfactoria.',
    descripcionEn: 'Persistent difficulty achieving or maintaining an erection sufficient for satisfactory sexual activity.',
    categorias: ['reproductivo', 'cardiovascular'],
    urgencia: 'baja',
    causasComunesEs: ['Enfermedad cardiovascular', 'Diabetes', 'Hipertensión arterial', 'Niveles bajos de testosterona', 'Estrés, ansiedad o depresión', 'Medicamentos (antihipertensivos, antidepresivos)', 'Tabaquismo'],
    causasComunesEn: ['Cardiovascular disease', 'Diabetes', 'High blood pressure', 'Low testosterone levels', 'Stress, anxiety, or depression', 'Medications (antihypertensives, antidepressants)', 'Smoking'],
    cuandoVerMedicoEs: ['Dificultad persistente (más de 3 meses)', 'Disfunción eréctil con problemas de salud conocidos', 'Impacto en la relación de pareja o bienestar emocional', 'Preocupaciones sobre medicamentos que podrían contribuir'],
    cuandoVerMedicoEn: ['Persistent difficulty (more than 3 months)', 'Erectile dysfunction with known health issues', 'Impact on partner relationship or emotional well-being', 'Concerns about medications that might contribute'],
    autoCuidadoEs: ['Hacer ejercicio regularmente', 'Mantener un peso saludable', 'Dejar de fumar', 'Limitar el alcohol', 'Manejar el estrés', 'Dormir suficiente'],
    autoCuidadoEn: ['Exercise regularly', 'Maintain a healthy weight', 'Quit smoking', 'Limit alcohol', 'Manage stress', 'Get enough sleep'],
    preguntasParaMedicoEs: ['¿Podría indicar un problema cardiovascular?', '¿Necesito un análisis hormonal?', '¿Qué opciones de tratamiento existen?'],
    preguntasParaMedicoEn: ['Could it indicate a cardiovascular problem?', 'Do I need hormonal testing?', 'What treatment options are available?'],
    sintomasRelacionados: ['depresion', 'ansiedad', 'fatiga', 'presion-arterial-alta'],
    sistemasCorporales: ['reproductivo', 'cardiovascular']
  },
  // ---- SALUD MENTAL ----
  {
    id: 'ansiedad',
    nombreEs: 'Ansiedad',
    nombreEn: 'Anxiety',
    descripcionEs: 'Sentimiento persistente de preocupación excesiva, nerviosismo o miedo que puede interferir con las actividades diarias. Puede incluir síntomas físicos.',
    descripcionEn: 'Persistent feeling of excessive worry, nervousness, or fear that can interfere with daily activities. It can include physical symptoms.',
    categorias: ['salud mental'],
    urgencia: 'media',
    causasComunesEs: ['Trastorno de ansiedad generalizada', 'Estrés laboral o personal', 'Trastorno de pánico', 'Fobias', 'Efectos de la cafeína o estimulantes', 'Condiciones médicas (hipertiroidismo)'],
    causasComunesEn: ['Generalized anxiety disorder', 'Work or personal stress', 'Panic disorder', 'Phobias', 'Effects of caffeine or stimulants', 'Medical conditions (hyperthyroidism)'],
    cuandoVerMedicoEs: ['Ansiedad que interfiere con el trabajo o las relaciones', 'Ataques de pánico frecuentes', 'Pensamientos de hacerse daño', 'Uso de alcohol o drogas para manejar la ansiedad', 'Síntomas físicos persistentes como palpitaciones'],
    cuandoVerMedicoEn: ['Anxiety interfering with work or relationships', 'Frequent panic attacks', 'Thoughts of self-harm', 'Use of alcohol or drugs to manage anxiety', 'Persistent physical symptoms like palpitations'],
    autoCuidadoEs: ['Practicar ejercicios de respiración profunda', 'Hacer ejercicio regularmente', 'Limitar cafeína y alcohol', 'Practicar meditación o mindfulness', 'Mantener un horario de sueño regular', 'Hablar con personas de confianza'],
    autoCuidadoEn: ['Practice deep breathing exercises', 'Exercise regularly', 'Limit caffeine and alcohol', 'Practice meditation or mindfulness', 'Maintain a regular sleep schedule', 'Talk to trusted people'],
    preguntasParaMedicoEs: ['¿Debería considerar terapia psicológica?', '¿Necesito medicación para la ansiedad?', '¿Mi ansiedad podría tener una causa médica?'],
    preguntasParaMedicoEn: ['Should I consider psychological therapy?', 'Do I need medication for anxiety?', 'Could my anxiety have a medical cause?'],
    sintomasRelacionados: ['palpitaciones', 'insomnio', 'dolor-de-cabeza', 'nauseas', 'sudoracion-excesiva', 'respiracion-rapida'],
    sistemasCorporales: ['salud mental']
  },
  {
    id: 'depresion',
    nombreEs: 'Depresión',
    nombreEn: 'Depression',
    descripcionEs: 'Estado de ánimo persistentemente triste o pérdida de interés en actividades que antes se disfrutaban, que dura al menos dos semanas y afecta el funcionamiento diario.',
    descripcionEn: 'Persistently sad mood or loss of interest in previously enjoyed activities, lasting at least two weeks and affecting daily functioning.',
    categorias: ['salud mental'],
    urgencia: 'alta',
    causasComunesEs: ['Desequilibrios químicos cerebrales', 'Eventos traumáticos o pérdidas', 'Estrés crónico', 'Antecedentes familiares', 'Enfermedades crónicas', 'Ciertos medicamentos', 'Aislamiento social'],
    causasComunesEn: ['Brain chemical imbalances', 'Traumatic events or losses', 'Chronic stress', 'Family history', 'Chronic diseases', 'Certain medications', 'Social isolation'],
    cuandoVerMedicoEs: ['Pensamientos de suicidio o autolesión (buscar ayuda inmediata)', 'Síntomas que duran más de 2 semanas', 'Incapacidad para realizar actividades diarias', 'Uso de alcohol o drogas para sentirse mejor', 'Sentimiento de desesperanza persistente'],
    cuandoVerMedicoEn: ['Thoughts of suicide or self-harm (seek immediate help)', 'Symptoms lasting more than 2 weeks', 'Inability to perform daily activities', 'Use of alcohol or drugs to feel better', 'Persistent feelings of hopelessness'],
    autoCuidadoEs: ['Mantener una rutina diaria', 'Hacer ejercicio aunque sea caminar 30 minutos', 'Mantener contacto con amigos y familiares', 'Evitar el aislamiento', 'Dormir horarios regulares', 'Buscar ayuda profesional'],
    autoCuidadoEn: ['Maintain a daily routine', 'Exercise even if just walking 30 minutes', 'Stay in touch with friends and family', 'Avoid isolation', 'Keep regular sleep hours', 'Seek professional help'],
    preguntasParaMedicoEs: ['¿Necesito antidepresivos?', '¿Qué tipo de terapia es más efectiva para mi caso?', '¿Cuánto tiempo dura el tratamiento típicamente?'],
    preguntasParaMedicoEn: ['Do I need antidepressants?', 'What type of therapy is most effective for my case?', 'How long does treatment typically last?'],
    sintomasRelacionados: ['fatiga', 'insomnio', 'perdida-de-apetito', 'perdida-de-concentracion', 'perdida-de-peso', 'cambios-de-humor'],
    sistemasCorporales: ['salud mental']
  },
  {
    id: 'insomnio',
    nombreEs: 'Insomnio',
    nombreEn: 'Insomnia',
    descripcionEs: 'Dificultad para conciliar el sueño, mantenerse dormido o despertarse demasiado temprano, con incapacidad para volver a dormir. Resulta en sueño no reparador.',
    descripcionEn: 'Difficulty falling asleep, staying asleep, or waking too early with inability to go back to sleep. Results in non-restorative sleep.',
    categorias: ['salud mental', 'neurológico'],
    urgencia: 'baja',
    causasComunesEs: ['Estrés y preocupaciones', 'Ansiedad o depresión', 'Malos hábitos de sueño', 'Consumo de cafeína o alcohol', 'Dolor crónico', 'Apnea del sueño', 'Jet lag o trabajo por turnos'],
    causasComunesEn: ['Stress and worries', 'Anxiety or depression', 'Poor sleep habits', 'Caffeine or alcohol consumption', 'Chronic pain', 'Sleep apnea', 'Jet lag or shift work'],
    cuandoVerMedicoEs: ['Insomnio que dura más de un mes', 'Insomnio que afecta el rendimiento diario', 'Somnolencia excesiva durante el día', 'Ronquidos fuertes o pausas en la respiración al dormir'],
    cuandoVerMedicoEn: ['Insomnia lasting more than a month', 'Insomnia affecting daily performance', 'Excessive daytime sleepiness', 'Loud snoring or breathing pauses during sleep'],
    autoCuidadoEs: ['Mantener horarios fijos para acostarse y levantarse', 'Crear un ambiente oscuro, fresco y silencioso', 'Evitar pantallas una hora antes de dormir', 'No consumir cafeína después del mediodía', 'Hacer ejercicio temprano en el día, no antes de dormir'],
    autoCuidadoEn: ['Keep fixed bedtime and wake-up schedules', 'Create a dark, cool, and quiet environment', 'Avoid screens one hour before bed', 'Do not consume caffeine after noon', 'Exercise early in the day, not before bed'],
    preguntasParaMedicoEs: ['¿Podría tener apnea del sueño?', '¿Necesito un estudio del sueño?', '¿Los somníferos son seguros a largo plazo?'],
    preguntasParaMedicoEn: ['Could I have sleep apnea?', 'Do I need a sleep study?', 'Are sleeping pills safe long-term?'],
    sintomasRelacionados: ['fatiga', 'ansiedad', 'depresion', 'perdida-de-concentracion', 'dolor-de-cabeza'],
    sistemasCorporales: ['salud mental', 'neurológico']
  },
  {
    id: 'cambios-de-humor',
    nombreEs: 'Cambios de humor',
    nombreEn: 'Mood changes',
    descripcionEs: 'Variaciones rápidas o extremas en el estado emocional, pasando de la alegría a la tristeza, irritabilidad o enojo sin causa proporcionada.',
    descripcionEn: 'Rapid or extreme variations in emotional state, shifting from happiness to sadness, irritability, or anger without proportionate cause.',
    categorias: ['salud mental'],
    urgencia: 'media',
    causasComunesEs: ['Cambios hormonales (ciclo menstrual, menopausia)', 'Estrés', 'Trastorno bipolar', 'Depresión', 'Efectos de medicamentos', 'Problemas de tiroides', 'Falta de sueño'],
    causasComunesEn: ['Hormonal changes (menstrual cycle, menopause)', 'Stress', 'Bipolar disorder', 'Depression', 'Medication effects', 'Thyroid problems', 'Lack of sleep'],
    cuandoVerMedicoEs: ['Cambios de humor extremos que afectan relaciones', 'Alternancia entre euforia y depresión profunda', 'Cambios de humor con comportamientos impulsivos', 'Pensamientos de hacerse daño durante episodios bajos'],
    cuandoVerMedicoEn: ['Extreme mood changes affecting relationships', 'Alternating between euphoria and deep depression', 'Mood changes with impulsive behaviors', 'Thoughts of self-harm during low episodes'],
    autoCuidadoEs: ['Llevar un diario de estados de ánimo', 'Hacer ejercicio regular', 'Practicar técnicas de regulación emocional', 'Dormir suficiente', 'Limitar alcohol y drogas'],
    autoCuidadoEn: ['Keep a mood journal', 'Exercise regularly', 'Practice emotional regulation techniques', 'Get enough sleep', 'Limit alcohol and drugs'],
    preguntasParaMedicoEs: ['¿Podría tener trastorno bipolar?', '¿Mis cambios de humor son hormonales?', '¿Debería ver a un psiquiatra?'],
    preguntasParaMedicoEn: ['Could I have bipolar disorder?', 'Are my mood changes hormonal?', 'Should I see a psychiatrist?'],
    sintomasRelacionados: ['depresion', 'ansiedad', 'insomnio', 'fatiga', 'perdida-de-concentracion'],
    sistemasCorporales: ['salud mental']
  },
  {
    id: 'perdida-de-concentracion',
    nombreEs: 'Pérdida de concentración',
    nombreEn: 'Difficulty concentrating',
    descripcionEs: 'Dificultad para mantener la atención enfocada en una tarea, pensar con claridad o procesar información de manera eficiente.',
    descripcionEn: 'Difficulty maintaining focused attention on a task, thinking clearly, or processing information efficiently.',
    categorias: ['salud mental', 'neurológico'],
    urgencia: 'baja',
    causasComunesEs: ['Falta de sueño', 'Estrés', 'Ansiedad o depresión', 'Trastorno por déficit de atención (TDAH)', 'Deficiencias nutricionales', 'Efectos de medicamentos', 'Problemas de tiroides'],
    causasComunesEn: ['Lack of sleep', 'Stress', 'Anxiety or depression', 'Attention deficit disorder (ADHD)', 'Nutritional deficiencies', 'Medication effects', 'Thyroid problems'],
    cuandoVerMedicoEs: ['Dificultad de concentración que afecta trabajo o estudios', 'Pérdida de concentración de inicio reciente', 'Acompañada de confusión o pérdida de memoria', 'Dificultad que empeora progresivamente'],
    cuandoVerMedicoEn: ['Concentration difficulty affecting work or studies', 'Recent onset loss of concentration', 'Accompanied by confusion or memory loss', 'Difficulty progressively worsening'],
    autoCuidadoEs: ['Dormir entre 7 y 9 horas', 'Dividir tareas grandes en partes pequeñas', 'Reducir distracciones', 'Hacer ejercicio regularmente', 'Practicar técnicas de atención plena'],
    autoCuidadoEn: ['Sleep 7 to 9 hours', 'Break large tasks into small parts', 'Reduce distractions', 'Exercise regularly', 'Practice mindfulness techniques'],
    preguntasParaMedicoEs: ['¿Podría tener TDAH?', '¿Mis problemas de concentración podrían ser por ansiedad?', '¿Necesito pruebas neuropsicológicas?'],
    preguntasParaMedicoEn: ['Could I have ADHD?', 'Could my concentration problems be from anxiety?', 'Do I need neuropsychological testing?'],
    sintomasRelacionados: ['fatiga', 'insomnio', 'ansiedad', 'depresion', 'perdida-de-memoria'],
    sistemasCorporales: ['salud mental', 'neurológico']
  },
  // ---- ADDITIONAL SYMPTOMS TO REACH 80+ ----
  {
    id: 'dolor-de-cuello',
    nombreEs: 'Dolor de cuello',
    nombreEn: 'Neck pain',
    descripcionEs: 'Dolor o rigidez en la región cervical que puede limitar el movimiento de la cabeza. Puede irradiarse a los hombros o los brazos.',
    descripcionEn: 'Pain or stiffness in the cervical region that can limit head movement. It may radiate to the shoulders or arms.',
    categorias: ['musculoesquelético'],
    urgencia: 'baja',
    causasComunesEs: ['Tensión muscular por mala postura', 'Uso prolongado de dispositivos electrónicos', 'Artrosis cervical', 'Hernia de disco cervical', 'Latigazo cervical', 'Estrés'],
    causasComunesEn: ['Muscle tension from poor posture', 'Prolonged use of electronic devices', 'Cervical osteoarthritis', 'Cervical disc herniation', 'Whiplash', 'Stress'],
    cuandoVerMedicoEs: ['Dolor de cuello con fiebre y rigidez (posible meningitis)', 'Dolor con entumecimiento o debilidad en brazos', 'Dolor después de un accidente o caída', 'Dolor que empeora progresivamente'],
    cuandoVerMedicoEn: ['Neck pain with fever and stiffness (possible meningitis)', 'Pain with numbness or weakness in arms', 'Pain after an accident or fall', 'Pain that progressively worsens'],
    autoCuidadoEs: ['Ajustar la posición de la pantalla a la altura de los ojos', 'Hacer pausas y estiramientos frecuentes', 'Aplicar calor o frío', 'Dormir con una almohada adecuada'],
    autoCuidadoEn: ['Adjust screen position to eye level', 'Take frequent breaks and stretch', 'Apply heat or cold', 'Sleep with an appropriate pillow'],
    preguntasParaMedicoEs: ['¿Necesito radiografías del cuello?', '¿Debería hacer fisioterapia?', '¿Podría ser una hernia cervical?'],
    preguntasParaMedicoEn: ['Do I need neck X-rays?', 'Should I do physical therapy?', 'Could it be a cervical herniation?'],
    sintomasRelacionados: ['dolor-de-cabeza', 'dolor-de-espalda', 'entumecimiento', 'rigidez'],
    sistemasCorporales: ['musculoesquelético']
  },
  {
    id: 'hipo',
    nombreEs: 'Hipo persistente',
    nombreEn: 'Persistent hiccups',
    descripcionEs: 'Contracciones involuntarias y repetidas del diafragma seguidas del cierre abrupto de las cuerdas vocales. El hipo que dura más de 48 horas se considera persistente.',
    descripcionEn: 'Involuntary repeated contractions of the diaphragm followed by abrupt closure of the vocal cords. Hiccups lasting more than 48 hours are considered persistent.',
    categorias: ['gastrointestinal', 'neurológico'],
    urgencia: 'baja',
    causasComunesEs: ['Comer en exceso o muy rápido', 'Bebidas carbonatadas', 'Reflujo gastroesofágico', 'Irritación del nervio frénico', 'Lesiones del sistema nervioso central', 'Ciertos medicamentos'],
    causasComunesEn: ['Overeating or eating too fast', 'Carbonated beverages', 'Gastroesophageal reflux', 'Phrenic nerve irritation', 'Central nervous system lesions', 'Certain medications'],
    cuandoVerMedicoEs: ['Hipo que dura más de 48 horas', 'Hipo que interfiere con comer o dormir', 'Hipo acompañado de dolor abdominal', 'Hipo con vómitos'],
    cuandoVerMedicoEn: ['Hiccups lasting more than 48 hours', 'Hiccups interfering with eating or sleeping', 'Hiccups accompanied by abdominal pain', 'Hiccups with vomiting'],
    autoCuidadoEs: ['Respirar dentro de una bolsa de papel brevemente', 'Tragar agua fría lentamente', 'Contener la respiración por unos segundos', 'Tirar suavemente de la lengua'],
    autoCuidadoEn: ['Briefly breathe into a paper bag', 'Slowly swallow cold water', 'Hold your breath for a few seconds', 'Gently pull on the tongue'],
    preguntasParaMedicoEs: ['¿Mi hipo podría tener una causa seria?', '¿Hay medicamentos para el hipo persistente?', '¿Necesito pruebas adicionales?'],
    preguntasParaMedicoEn: ['Could my hiccups have a serious cause?', 'Are there medications for persistent hiccups?', 'Do I need additional tests?'],
    sintomasRelacionados: ['acidez', 'dolor-abdominal', 'nauseas', 'dificultad-para-tragar'],
    sistemasCorporales: ['gastrointestinal', 'neurológico']
  },
  {
    id: 'ganglios-inflamados',
    nombreEs: 'Ganglios linfáticos inflamados',
    nombreEn: 'Swollen lymph nodes',
    descripcionEs: 'Agrandamiento de uno o más ganglios linfáticos que se sienten como bultos blandos debajo de la piel, generalmente en el cuello, axilas o ingle.',
    descripcionEn: 'Enlargement of one or more lymph nodes that feel like soft lumps under the skin, usually in the neck, armpits, or groin.',
    categorias: ['inmunológico', 'general'],
    urgencia: 'media',
    causasComunesEs: ['Infecciones virales (resfriado, gripe)', 'Infecciones bacterianas (faringitis estreptocócica)', 'Infecciones del oído o dentales', 'Mononucleosis', 'Enfermedades autoinmunes', 'Linfoma u otros cánceres'],
    causasComunesEn: ['Viral infections (cold, flu)', 'Bacterial infections (strep throat)', 'Ear or dental infections', 'Mononucleosis', 'Autoimmune diseases', 'Lymphoma or other cancers'],
    cuandoVerMedicoEs: ['Ganglios que persisten más de 2 semanas', 'Ganglios duros, fijos o que crecen rápidamente', 'Ganglios inflamados sin infección aparente', 'Ganglios con sudoración nocturna o pérdida de peso'],
    cuandoVerMedicoEn: ['Lymph nodes persisting more than 2 weeks', 'Hard, fixed, or rapidly growing lymph nodes', 'Swollen lymph nodes without apparent infection', 'Lymph nodes with night sweats or weight loss'],
    autoCuidadoEs: ['Aplicar compresas tibias sobre los ganglios', 'Descansar adecuadamente', 'Tomar analgésicos si hay dolor', 'Tratar la infección subyacente si se conoce'],
    autoCuidadoEn: ['Apply warm compresses over the lymph nodes', 'Rest adequately', 'Take pain relievers if painful', 'Treat the underlying infection if known'],
    preguntasParaMedicoEs: ['¿Mis ganglios inflamados son preocupantes?', '¿Necesito una biopsia?', '¿Debería hacerme análisis de sangre?'],
    preguntasParaMedicoEn: ['Are my swollen lymph nodes concerning?', 'Do I need a biopsy?', 'Should I get blood tests?'],
    sintomasRelacionados: ['fiebre', 'fatiga', 'dolor-de-garganta', 'sudoracion-nocturna', 'perdida-de-peso'],
    sistemasCorporales: ['inmunológico', 'general']
  },
  {
    id: 'sed-excesiva',
    nombreEs: 'Sed excesiva (polidipsia)',
    nombreEn: 'Excessive thirst (polydipsia)',
    descripcionEs: 'Sensación anormal e intensa de sed que no se satisface con la ingesta habitual de líquidos. Puede ser un signo de condiciones metabólicas.',
    descripcionEn: 'Abnormal and intense feeling of thirst not satisfied by usual fluid intake. It can be a sign of metabolic conditions.',
    categorias: ['endocrino', 'general'],
    urgencia: 'media',
    causasComunesEs: ['Diabetes mellitus tipo 1 o 2', 'Diabetes insípida', 'Deshidratación', 'Medicamentos (diuréticos, litio)', 'Boca seca por medicamentos', 'Ejercicio intenso sin reposición'],
    causasComunesEn: ['Type 1 or 2 diabetes mellitus', 'Diabetes insipidus', 'Dehydration', 'Medications (diuretics, lithium)', 'Dry mouth from medications', 'Intense exercise without replenishment'],
    cuandoVerMedicoEs: ['Sed excesiva persistente sin explicación', 'Sed con micción frecuente', 'Sed con pérdida de peso inexplicable', 'Sed con visión borrosa o fatiga extrema'],
    cuandoVerMedicoEn: ['Persistent excessive thirst without explanation', 'Thirst with frequent urination', 'Thirst with unexplained weight loss', 'Thirst with blurred vision or extreme fatigue'],
    autoCuidadoEs: ['Mantenerse hidratado con agua', 'Evitar bebidas azucaradas', 'Registrar la ingesta de líquidos y frecuencia urinaria', 'Consultar al médico si persiste'],
    autoCuidadoEn: ['Stay hydrated with water', 'Avoid sugary drinks', 'Track fluid intake and urinary frequency', 'Consult a doctor if persistent'],
    preguntasParaMedicoEs: ['¿Podría tener diabetes?', '¿Necesito una prueba de glucosa en sangre?', '¿Alguno de mis medicamentos causa sed excesiva?'],
    preguntasParaMedicoEn: ['Could I have diabetes?', 'Do I need a blood glucose test?', 'Does any of my medication cause excessive thirst?'],
    sintomasRelacionados: ['frecuencia-urinaria', 'perdida-de-peso', 'fatiga', 'vision-borrosa'],
    sistemasCorporales: ['endocrino', 'general']
  },
  {
    id: 'dolor-de-mandibula',
    nombreEs: 'Dolor de mandíbula',
    nombreEn: 'Jaw pain',
    descripcionEs: 'Dolor en la articulación temporomandibular (ATM) o en los músculos de la mandíbula que puede dificultar masticar, hablar o abrir la boca.',
    descripcionEn: 'Pain in the temporomandibular joint (TMJ) or jaw muscles that can make chewing, speaking, or opening the mouth difficult.',
    categorias: ['musculoesquelético', 'otorrinolaringología'],
    urgencia: 'baja',
    causasComunesEs: ['Trastorno de la articulación temporomandibular (ATM)', 'Bruxismo (rechinar los dientes)', 'Estrés y tensión muscular', 'Artritis de la mandíbula', 'Infección dental', 'Dolor referido cardíaco (en algunos casos)'],
    causasComunesEn: ['Temporomandibular joint disorder (TMJ)', 'Bruxism (teeth grinding)', 'Stress and muscle tension', 'Jaw arthritis', 'Dental infection', 'Cardiac referred pain (in some cases)'],
    cuandoVerMedicoEs: ['Dolor de mandíbula con dolor de pecho (posible cardíaco)', 'Incapacidad para abrir o cerrar la boca', 'Dolor intenso al masticar', 'Mandíbula que se traba frecuentemente'],
    cuandoVerMedicoEn: ['Jaw pain with chest pain (possible cardiac)', 'Inability to open or close the mouth', 'Severe pain when chewing', 'Jaw that frequently locks'],
    autoCuidadoEs: ['Comer alimentos blandos', 'Aplicar calor o frío en la mandíbula', 'Evitar mascar chicle', 'Practicar ejercicios de relajación mandibular', 'Usar una guarda dental nocturna si hay bruxismo'],
    autoCuidadoEn: ['Eat soft foods', 'Apply heat or cold to the jaw', 'Avoid chewing gum', 'Practice jaw relaxation exercises', 'Use a night dental guard if bruxism is present'],
    preguntasParaMedicoEs: ['¿Tengo trastorno de ATM?', '¿Necesito una guarda dental?', '¿Debería ver a un dentista o maxilofacial?'],
    preguntasParaMedicoEn: ['Do I have TMJ disorder?', 'Do I need a dental guard?', 'Should I see a dentist or oral surgeon?'],
    sintomasRelacionados: ['dolor-de-cabeza', 'dolor-de-oido', 'dolor-de-cuello', 'rigidez'],
    sistemasCorporales: ['musculoesquelético', 'otorrinolaringológico']
  }
];
