// =============================================================================
// Batch 1: General + Neurological Symptoms
// =============================================================================

import type { SintomaEntry } from './tipos';

export const SINTOMAS_GENERAL_NEURO: SintomaEntry[] = [
  {
    id: 'fiebre',
    nombreEs: 'Fiebre',
    nombreEn: 'Fever',
    descripcionEs: 'Elevación de la temperatura corporal por encima de 38°C (100.4°F). Es una respuesta natural del cuerpo ante infecciones u otras condiciones inflamatorias.',
    descripcionEn: 'Elevation of body temperature above 38°C (100.4°F). It is a natural response of the body to infections or other inflammatory conditions.',
    categorias: ['general', 'infeccioso'],
    urgencia: 'media',
    causasComunesEs: ['Infecciones virales como gripe o resfriado', 'Infecciones bacterianas', 'Reacciones a medicamentos', 'Enfermedades autoinmunes', 'Golpe de calor'],
    causasComunesEn: ['Viral infections such as flu or cold', 'Bacterial infections', 'Drug reactions', 'Autoimmune diseases', 'Heat stroke'],
    cuandoVerMedicoEs: ['Temperatura superior a 39.4°C (103°F) en adultos', 'Fiebre que dura más de 3 días', 'Fiebre acompañada de rigidez en el cuello o confusión', 'Cualquier fiebre en bebés menores de 3 meses'],
    cuandoVerMedicoEn: ['Temperature above 39.4°C (103°F) in adults', 'Fever lasting more than 3 days', 'Fever accompanied by neck stiffness or confusion', 'Any fever in infants under 3 months'],
    autoCuidadoEs: ['Mantenerse bien hidratado con agua y líquidos claros', 'Descansar lo suficiente', 'Usar ropa ligera', 'Tomar paracetamol o ibuprofeno según las indicaciones del envase'],
    autoCuidadoEn: ['Stay well hydrated with water and clear fluids', 'Get adequate rest', 'Wear lightweight clothing', 'Take acetaminophen or ibuprofen as directed on packaging'],
    preguntasParaMedicoEs: ['¿Cuál puede ser la causa de mi fiebre?', '¿Necesito algún análisis de sangre?', '¿Debo preocuparme si la fiebre vuelve después de bajar?'],
    preguntasParaMedicoEn: ['What could be causing my fever?', 'Do I need any blood tests?', 'Should I be concerned if the fever returns after going down?'],
    sintomasRelacionados: ['escalofrios', 'sudoracion-nocturna', 'fatiga', 'malestar-general'],
    sistemasCorporales: ['general', 'inmunológico']
  },
  {
    id: 'fatiga',
    nombreEs: 'Fatiga',
    nombreEn: 'Fatigue',
    descripcionEs: 'Sensación persistente de cansancio, agotamiento o falta de energía que no mejora con el descanso habitual. Puede afectar tanto al cuerpo como a la mente.',
    descripcionEn: 'Persistent feeling of tiredness, exhaustion, or lack of energy that does not improve with usual rest. It can affect both body and mind.',
    categorias: ['general'],
    urgencia: 'baja',
    causasComunesEs: ['Falta de sueño o sueño de mala calidad', 'Estrés emocional o físico', 'Anemia', 'Hipotiroidismo', 'Depresión', 'Diabetes no controlada'],
    causasComunesEn: ['Lack of sleep or poor sleep quality', 'Emotional or physical stress', 'Anemia', 'Hypothyroidism', 'Depression', 'Uncontrolled diabetes'],
    cuandoVerMedicoEs: ['Fatiga que dura más de 2 semanas sin mejoría', 'Fatiga acompañada de pérdida de peso inexplicable', 'Dificultad para realizar actividades cotidianas', 'Fatiga con fiebre persistente'],
    cuandoVerMedicoEn: ['Fatigue lasting more than 2 weeks without improvement', 'Fatigue accompanied by unexplained weight loss', 'Difficulty performing daily activities', 'Fatigue with persistent fever'],
    autoCuidadoEs: ['Establecer un horario regular de sueño', 'Hacer ejercicio moderado regularmente', 'Mantener una alimentación equilibrada', 'Reducir el consumo de cafeína y alcohol'],
    autoCuidadoEn: ['Establish a regular sleep schedule', 'Exercise moderately on a regular basis', 'Maintain a balanced diet', 'Reduce caffeine and alcohol intake'],
    preguntasParaMedicoEs: ['¿Podría haber una causa médica detrás de mi cansancio?', '¿Debería hacerme análisis de sangre para descartar anemia o problemas de tiroides?', '¿Mis medicamentos actuales podrían estar causando fatiga?'],
    preguntasParaMedicoEn: ['Could there be a medical cause behind my tiredness?', 'Should I get blood tests to rule out anemia or thyroid problems?', 'Could my current medications be causing fatigue?'],
    sintomasRelacionados: ['debilidad', 'perdida-de-peso', 'depresion', 'insomnio'],
    sistemasCorporales: ['general']
  },
  {
    id: 'perdida-de-peso',
    nombreEs: 'Pérdida de peso involuntaria',
    nombreEn: 'Unintentional weight loss',
    descripcionEs: 'Disminución del peso corporal sin intentarlo, generalmente definida como la pérdida de más del 5% del peso en un período de 6 a 12 meses.',
    descripcionEn: 'Decrease in body weight without trying, generally defined as losing more than 5% of body weight over a 6 to 12 month period.',
    categorias: ['general', 'metabólico'],
    urgencia: 'alta',
    causasComunesEs: ['Hipertiroidismo', 'Diabetes no controlada', 'Depresión o ansiedad', 'Enfermedades gastrointestinales', 'Cáncer', 'Infecciones crónicas'],
    causasComunesEn: ['Hyperthyroidism', 'Uncontrolled diabetes', 'Depression or anxiety', 'Gastrointestinal diseases', 'Cancer', 'Chronic infections'],
    cuandoVerMedicoEs: ['Pérdida de más del 5% de peso corporal en 6 meses sin dieta', 'Pérdida de peso acompañada de otros síntomas', 'Disminución progresiva del apetito'],
    cuandoVerMedicoEn: ['Loss of more than 5% of body weight in 6 months without dieting', 'Weight loss accompanied by other symptoms', 'Progressive decrease in appetite'],
    autoCuidadoEs: ['Llevar un registro del peso semanal', 'Comer comidas pequeñas y frecuentes', 'Enriquecer los alimentos con proteínas y calorías saludables', 'Consultar a un nutricionista'],
    autoCuidadoEn: ['Keep a weekly weight log', 'Eat small frequent meals', 'Enrich foods with protein and healthy calories', 'Consult a nutritionist'],
    preguntasParaMedicoEs: ['¿Qué estudios necesito para averiguar la causa?', '¿Debería ver a un especialista?', '¿Necesito suplementos nutricionales?'],
    preguntasParaMedicoEn: ['What tests do I need to find the cause?', 'Should I see a specialist?', 'Do I need nutritional supplements?'],
    sintomasRelacionados: ['fatiga', 'perdida-de-apetito', 'sudoracion-nocturna', 'fiebre'],
    sistemasCorporales: ['general', 'endocrino', 'gastrointestinal']
  },
  {
    id: 'sudoracion-nocturna',
    nombreEs: 'Sudoración nocturna',
    nombreEn: 'Night sweats',
    descripcionEs: 'Episodios de sudoración excesiva durante la noche que pueden empapar la ropa de dormir y las sábanas, sin relación con un ambiente caluroso.',
    descripcionEn: 'Episodes of excessive sweating during the night that can soak sleepwear and sheets, unrelated to a warm environment.',
    categorias: ['general'],
    urgencia: 'media',
    causasComunesEs: ['Infecciones como tuberculosis', 'Menopausia', 'Ciertos medicamentos como antidepresivos', 'Linfoma u otros cánceres', 'Trastornos hormonales', 'Apnea del sueño'],
    causasComunesEn: ['Infections such as tuberculosis', 'Menopause', 'Certain medications such as antidepressants', 'Lymphoma or other cancers', 'Hormonal disorders', 'Sleep apnea'],
    cuandoVerMedicoEs: ['Sudoración nocturna recurrente sin causa aparente', 'Acompañada de fiebre o pérdida de peso', 'Sudoración que interrumpe el sueño regularmente'],
    cuandoVerMedicoEn: ['Recurrent night sweats without apparent cause', 'Accompanied by fever or weight loss', 'Sweating that regularly disrupts sleep'],
    autoCuidadoEs: ['Usar ropa de cama de algodón transpirable', 'Mantener la habitación fresca', 'Evitar comidas picantes y alcohol antes de dormir', 'Usar ropa de dormir ligera'],
    autoCuidadoEn: ['Use breathable cotton bedding', 'Keep the bedroom cool', 'Avoid spicy foods and alcohol before bed', 'Wear lightweight sleepwear'],
    preguntasParaMedicoEs: ['¿Podrían mis medicamentos causar sudoración nocturna?', '¿Necesito pruebas para descartar infecciones o cáncer?', '¿Podría estar relacionado con cambios hormonales?'],
    preguntasParaMedicoEn: ['Could my medications be causing night sweats?', 'Do I need tests to rule out infections or cancer?', 'Could it be related to hormonal changes?'],
    sintomasRelacionados: ['fiebre', 'perdida-de-peso', 'fatiga', 'escalofrios'],
    sistemasCorporales: ['general', 'endocrino']
  },
  {
    id: 'escalofrios',
    nombreEs: 'Escalofríos',
    nombreEn: 'Chills',
    descripcionEs: 'Sensación de frío acompañada de temblores involuntarios del cuerpo. A menudo ocurren junto con fiebre como parte de la respuesta inmunológica.',
    descripcionEn: 'Feeling of coldness accompanied by involuntary shivering of the body. Often occurs alongside fever as part of the immune response.',
    categorias: ['general', 'infeccioso'],
    urgencia: 'media',
    causasComunesEs: ['Infecciones virales o bacterianas', 'Exposición al frío', 'Reacciones a medicamentos', 'Inicio de fiebre', 'Hipotiroidismo'],
    causasComunesEn: ['Viral or bacterial infections', 'Cold exposure', 'Drug reactions', 'Onset of fever', 'Hypothyroidism'],
    cuandoVerMedicoEs: ['Escalofríos con fiebre alta persistente', 'Escalofríos con confusión o rigidez de cuello', 'Escalofríos repetidos sin causa aparente'],
    cuandoVerMedicoEn: ['Chills with persistent high fever', 'Chills with confusion or neck stiffness', 'Repeated chills without apparent cause'],
    autoCuidadoEs: ['Abrigarse con mantas', 'Beber líquidos calientes', 'Descansar', 'Monitorear la temperatura corporal'],
    autoCuidadoEn: ['Wrap up with blankets', 'Drink warm fluids', 'Rest', 'Monitor body temperature'],
    preguntasParaMedicoEs: ['¿Los escalofríos indican una infección grave?', '¿Necesito antibióticos?', '¿Cuándo debo acudir a urgencias?'],
    preguntasParaMedicoEn: ['Do chills indicate a serious infection?', 'Do I need antibiotics?', 'When should I go to the emergency room?'],
    sintomasRelacionados: ['fiebre', 'sudoracion-nocturna', 'fatiga', 'malestar-general'],
    sistemasCorporales: ['general', 'inmunológico']
  },
  {
    id: 'malestar-general',
    nombreEs: 'Malestar general',
    nombreEn: 'General malaise',
    descripcionEs: 'Sensación vaga de incomodidad, enfermedad o falta de bienestar general. Es un síntoma inespecífico que puede acompañar a muchas enfermedades.',
    descripcionEn: 'Vague feeling of discomfort, illness, or lack of general well-being. It is a nonspecific symptom that can accompany many illnesses.',
    categorias: ['general'],
    urgencia: 'baja',
    causasComunesEs: ['Infecciones virales', 'Inicio de diversas enfermedades', 'Estrés crónico', 'Falta de sueño', 'Efectos secundarios de medicamentos'],
    causasComunesEn: ['Viral infections', 'Onset of various illnesses', 'Chronic stress', 'Lack of sleep', 'Medication side effects'],
    cuandoVerMedicoEs: ['Malestar que persiste más de una semana', 'Malestar acompañado de otros síntomas preocupantes', 'Interferencia significativa con las actividades diarias'],
    cuandoVerMedicoEn: ['Malaise persisting more than one week', 'Malaise accompanied by other concerning symptoms', 'Significant interference with daily activities'],
    autoCuidadoEs: ['Descansar adecuadamente', 'Hidratarse bien', 'Comer alimentos nutritivos', 'Evitar actividades extenuantes temporalmente'],
    autoCuidadoEn: ['Rest adequately', 'Stay well hydrated', 'Eat nutritious foods', 'Temporarily avoid strenuous activities'],
    preguntasParaMedicoEs: ['¿El malestar podría indicar algo serio?', '¿Debería hacerme un chequeo general?', '¿Hay algún análisis que pueda identificar la causa?'],
    preguntasParaMedicoEn: ['Could the malaise indicate something serious?', 'Should I get a general checkup?', 'Are there tests that can identify the cause?'],
    sintomasRelacionados: ['fatiga', 'fiebre', 'debilidad', 'perdida-de-apetito'],
    sistemasCorporales: ['general']
  },
  {
    id: 'debilidad',
    nombreEs: 'Debilidad generalizada',
    nombreEn: 'Generalized weakness',
    descripcionEs: 'Reducción de la fuerza muscular o sensación de falta de energía física para realizar movimientos o actividades habituales.',
    descripcionEn: 'Reduction in muscle strength or a feeling of lacking physical energy to perform usual movements or activities.',
    categorias: ['general', 'neurológico', 'musculoesquelético'],
    urgencia: 'media',
    causasComunesEs: ['Anemia', 'Deshidratación', 'Hipotiroidismo', 'Deficiencia de vitaminas', 'Enfermedades neuromusculares', 'Infecciones'],
    causasComunesEn: ['Anemia', 'Dehydration', 'Hypothyroidism', 'Vitamin deficiency', 'Neuromuscular diseases', 'Infections'],
    cuandoVerMedicoEs: ['Debilidad repentina en un lado del cuerpo', 'Debilidad progresiva que empeora', 'Debilidad acompañada de dificultad para respirar', 'Incapacidad para realizar actividades básicas'],
    cuandoVerMedicoEn: ['Sudden weakness on one side of the body', 'Progressive weakness that worsens', 'Weakness accompanied by difficulty breathing', 'Inability to perform basic activities'],
    autoCuidadoEs: ['Alimentarse de forma equilibrada', 'Mantenerse hidratado', 'Hacer ejercicio suave y progresivo', 'Dormir entre 7 y 9 horas por noche'],
    autoCuidadoEn: ['Eat a balanced diet', 'Stay hydrated', 'Do gentle progressive exercise', 'Sleep 7 to 9 hours per night'],
    preguntasParaMedicoEs: ['¿Podría ser anemia u otro problema sanguíneo?', '¿Necesito pruebas neurológicas?', '¿Mis niveles de vitaminas están bien?'],
    preguntasParaMedicoEn: ['Could it be anemia or another blood problem?', 'Do I need neurological tests?', 'Are my vitamin levels adequate?'],
    sintomasRelacionados: ['fatiga', 'mareos', 'entumecimiento', 'debilidad-muscular'],
    sistemasCorporales: ['general', 'neurológico', 'musculoesquelético']
  },
  {
    id: 'dolor-de-cabeza',
    nombreEs: 'Dolor de cabeza',
    nombreEn: 'Headache',
    descripcionEs: 'Dolor o molestia en cualquier zona de la cabeza. Puede ser punzante, opresivo, pulsátil o constante, y variar de leve a severo.',
    descripcionEn: 'Pain or discomfort in any area of the head. It can be sharp, pressing, throbbing, or constant, ranging from mild to severe.',
    categorias: ['neurológico', 'cabeza'],
    urgencia: 'baja',
    causasComunesEs: ['Cefalea tensional por estrés', 'Deshidratación', 'Falta de sueño', 'Tensión muscular cervical', 'Sinusitis', 'Problemas de visión'],
    causasComunesEn: ['Tension headache from stress', 'Dehydration', 'Lack of sleep', 'Cervical muscle tension', 'Sinusitis', 'Vision problems'],
    cuandoVerMedicoEs: ['Dolor de cabeza súbito e intenso (el peor de su vida)', 'Dolor acompañado de fiebre y rigidez de cuello', 'Dolor que empeora progresivamente', 'Dolor con cambios en la visión o confusión'],
    cuandoVerMedicoEn: ['Sudden severe headache (worst of your life)', 'Headache accompanied by fever and neck stiffness', 'Headache that progressively worsens', 'Headache with vision changes or confusion'],
    autoCuidadoEs: ['Descansar en un lugar oscuro y tranquilo', 'Aplicar compresas frías o calientes', 'Hidratarse adecuadamente', 'Tomar analgésicos de venta libre con moderación'],
    autoCuidadoEn: ['Rest in a dark quiet place', 'Apply cold or warm compresses', 'Stay adequately hydrated', 'Take over-the-counter pain relievers in moderation'],
    preguntasParaMedicoEs: ['¿Debería preocuparme por la frecuencia de mis dolores de cabeza?', '¿Necesito un estudio de imagen como tomografía?', '¿Hay tratamientos preventivos disponibles?'],
    preguntasParaMedicoEn: ['Should I be worried about the frequency of my headaches?', 'Do I need an imaging study like a CT scan?', 'Are there preventive treatments available?'],
    sintomasRelacionados: ['migrana', 'sensibilidad-a-la-luz', 'nauseas', 'vision-borrosa'],
    sistemasCorporales: ['neurológico']
  },
  {
    id: 'migrana',
    nombreEs: 'Migraña',
    nombreEn: 'Migraine',
    descripcionEs: 'Dolor de cabeza intenso y pulsátil, generalmente en un lado de la cabeza, que puede durar horas o días. Frecuentemente acompañado de náuseas, vómitos y sensibilidad a la luz y al sonido.',
    descripcionEn: 'Intense throbbing headache, usually on one side of the head, that can last hours or days. Frequently accompanied by nausea, vomiting, and sensitivity to light and sound.',
    categorias: ['neurológico', 'cabeza'],
    urgencia: 'media',
    causasComunesEs: ['Predisposición genética', 'Cambios hormonales', 'Estrés', 'Ciertos alimentos como queso añejo o vino tinto', 'Falta de sueño', 'Cambios climáticos'],
    causasComunesEn: ['Genetic predisposition', 'Hormonal changes', 'Stress', 'Certain foods such as aged cheese or red wine', 'Lack of sleep', 'Weather changes'],
    cuandoVerMedicoEs: ['Migrañas más de 4 veces al mes', 'Cambio en el patrón habitual de las migrañas', 'Migraña con síntomas neurológicos nuevos', 'Migraña que no responde a tratamiento habitual'],
    cuandoVerMedicoEn: ['Migraines more than 4 times a month', 'Change in the usual migraine pattern', 'Migraine with new neurological symptoms', 'Migraine not responding to usual treatment'],
    autoCuidadoEs: ['Identificar y evitar desencadenantes personales', 'Descansar en un cuarto oscuro y silencioso', 'Aplicar compresas frías en la frente', 'Mantener horarios regulares de sueño y comidas'],
    autoCuidadoEn: ['Identify and avoid personal triggers', 'Rest in a dark silent room', 'Apply cold compresses to the forehead', 'Maintain regular sleep and meal schedules'],
    preguntasParaMedicoEs: ['¿Necesito medicamento preventivo para las migrañas?', '¿Debería llevar un diario de migrañas?', '¿Existen tratamientos nuevos que pueda probar?'],
    preguntasParaMedicoEn: ['Do I need preventive medication for migraines?', 'Should I keep a migraine diary?', 'Are there new treatments I can try?'],
    sintomasRelacionados: ['dolor-de-cabeza', 'nauseas', 'sensibilidad-a-la-luz', 'vision-borrosa'],
    sistemasCorporales: ['neurológico']
  },
  {
    id: 'mareos',
    nombreEs: 'Mareos',
    nombreEn: 'Dizziness',
    descripcionEs: 'Sensación de inestabilidad, aturdimiento o como si uno fuera a desmayarse. Puede sentirse como si la habitación girara o como si se perdiera el equilibrio.',
    descripcionEn: 'Sensation of unsteadiness, lightheadedness, or feeling as if one might faint. It may feel like the room is spinning or like losing balance.',
    categorias: ['neurológico', 'cardiovascular'],
    urgencia: 'media',
    causasComunesEs: ['Hipotensión ortostática', 'Deshidratación', 'Anemia', 'Problemas del oído interno', 'Efectos de medicamentos', 'Ansiedad'],
    causasComunesEn: ['Orthostatic hypotension', 'Dehydration', 'Anemia', 'Inner ear problems', 'Medication effects', 'Anxiety'],
    cuandoVerMedicoEs: ['Mareos frecuentes o persistentes', 'Mareos con dolor de pecho o falta de aire', 'Mareos con pérdida de conciencia', 'Mareos acompañados de debilidad en un lado del cuerpo'],
    cuandoVerMedicoEn: ['Frequent or persistent dizziness', 'Dizziness with chest pain or shortness of breath', 'Dizziness with loss of consciousness', 'Dizziness accompanied by weakness on one side of the body'],
    autoCuidadoEs: ['Levantarse lentamente de la cama o de una silla', 'Mantenerse hidratado', 'Evitar cambios bruscos de posición', 'Sentarse o acostarse cuando sienta mareo'],
    autoCuidadoEn: ['Get up slowly from bed or a chair', 'Stay hydrated', 'Avoid sudden position changes', 'Sit or lie down when feeling dizzy'],
    preguntasParaMedicoEs: ['¿Mis mareos podrían estar relacionados con el oído?', '¿Debo ajustar alguno de mis medicamentos?', '¿Necesito pruebas de equilibrio?'],
    preguntasParaMedicoEn: ['Could my dizziness be related to my ear?', 'Should I adjust any of my medications?', 'Do I need balance tests?'],
    sintomasRelacionados: ['vertigo', 'desmayo', 'nauseas', 'debilidad'],
    sistemasCorporales: ['neurológico', 'cardiovascular', 'vestibular']
  },
  {
    id: 'vertigo',
    nombreEs: 'Vértigo',
    nombreEn: 'Vertigo',
    descripcionEs: 'Sensación falsa de que el entorno gira o se mueve a su alrededor, o de que usted mismo está girando. Diferente de los mareos comunes.',
    descripcionEn: 'False sensation that the surroundings are spinning or moving around you, or that you yourself are spinning. Different from common dizziness.',
    categorias: ['neurológico', 'oído'],
    urgencia: 'media',
    causasComunesEs: ['Vértigo posicional paroxístico benigno (VPPB)', 'Enfermedad de Ménière', 'Neuritis vestibular', 'Migraña vestibular', 'Infección del oído interno'],
    causasComunesEn: ['Benign paroxysmal positional vertigo (BPPV)', 'Meniere disease', 'Vestibular neuritis', 'Vestibular migraine', 'Inner ear infection'],
    cuandoVerMedicoEs: ['Vértigo acompañado de dificultad para hablar o caminar', 'Vértigo con pérdida de audición súbita', 'Episodios recurrentes de vértigo', 'Vértigo con dolor de cabeza intenso'],
    cuandoVerMedicoEn: ['Vertigo accompanied by difficulty speaking or walking', 'Vertigo with sudden hearing loss', 'Recurrent vertigo episodes', 'Vertigo with severe headache'],
    autoCuidadoEs: ['Evitar movimientos rápidos de cabeza', 'Sentarse o acostarse durante un episodio', 'Maniobras de Epley si es VPPB (con guía médica)', 'Evitar conducir durante episodios'],
    autoCuidadoEn: ['Avoid rapid head movements', 'Sit or lie down during an episode', 'Epley maneuver if BPPV (with medical guidance)', 'Avoid driving during episodes'],
    preguntasParaMedicoEs: ['¿Qué tipo de vértigo tengo?', '¿Necesito ver a un otorrinolaringólogo?', '¿Hay ejercicios de rehabilitación vestibular que pueda hacer?'],
    preguntasParaMedicoEn: ['What type of vertigo do I have?', 'Do I need to see an ENT specialist?', 'Are there vestibular rehabilitation exercises I can do?'],
    sintomasRelacionados: ['mareos', 'nauseas', 'perdida-de-audicion', 'zumbido'],
    sistemasCorporales: ['neurológico', 'vestibular']
  },
  {
    id: 'desmayo',
    nombreEs: 'Desmayo (síncope)',
    nombreEn: 'Fainting (syncope)',
    descripcionEs: 'Pérdida temporal de la conciencia causada por una disminución del flujo sanguíneo al cerebro. Generalmente es breve y la recuperación es completa.',
    descripcionEn: 'Temporary loss of consciousness caused by decreased blood flow to the brain. Usually brief with complete recovery.',
    categorias: ['neurológico', 'cardiovascular'],
    urgencia: 'alta',
    causasComunesEs: ['Deshidratación', 'Hipotensión ortostática', 'Arritmias cardíacas', 'Respuesta vasovagal (estrés, dolor, calor)', 'Hipoglucemia', 'Anemia severa'],
    causasComunesEn: ['Dehydration', 'Orthostatic hypotension', 'Cardiac arrhythmias', 'Vasovagal response (stress, pain, heat)', 'Hypoglycemia', 'Severe anemia'],
    cuandoVerMedicoEs: ['Cualquier desmayo debe ser evaluado por un médico', 'Desmayo durante ejercicio físico', 'Desmayo con palpitaciones o dolor de pecho', 'Desmayos recurrentes'],
    cuandoVerMedicoEn: ['Any fainting episode should be evaluated by a doctor', 'Fainting during physical exercise', 'Fainting with palpitations or chest pain', 'Recurrent fainting episodes'],
    autoCuidadoEs: ['Al sentir que va a desmayarse: sentarse o acostarse', 'Elevar las piernas si está acostado', 'Mantenerse hidratado', 'Evitar estar de pie por períodos prolongados'],
    autoCuidadoEn: ['When feeling faint: sit or lie down', 'Elevate legs if lying down', 'Stay hydrated', 'Avoid standing for prolonged periods'],
    preguntasParaMedicoEs: ['¿Necesito un electrocardiograma o monitoreo cardíaco?', '¿Mi desmayo podría ser de origen cardíaco?', '¿Hay medicamentos que podrían estar contribuyendo?'],
    preguntasParaMedicoEn: ['Do I need an electrocardiogram or cardiac monitoring?', 'Could my fainting be cardiac in origin?', 'Are there medications that could be contributing?'],
    sintomasRelacionados: ['mareos', 'debilidad', 'palpitaciones', 'vision-borrosa'],
    sistemasCorporales: ['neurológico', 'cardiovascular']
  },
  {
    id: 'confusion',
    nombreEs: 'Confusión',
    nombreEn: 'Confusion',
    descripcionEs: 'Dificultad para pensar con claridad, desorientación en tiempo, lugar o persona, o incapacidad para tomar decisiones o mantener la atención.',
    descripcionEn: 'Difficulty thinking clearly, disorientation in time, place, or person, or inability to make decisions or maintain attention.',
    categorias: ['neurológico'],
    urgencia: 'alta',
    causasComunesEs: ['Infecciones graves (especialmente en personas mayores)', 'Deshidratación severa', 'Efectos de medicamentos', 'Niveles anormales de azúcar en sangre', 'Accidente cerebrovascular', 'Traumatismo craneal'],
    causasComunesEn: ['Serious infections (especially in older adults)', 'Severe dehydration', 'Medication effects', 'Abnormal blood sugar levels', 'Stroke', 'Head trauma'],
    cuandoVerMedicoEs: ['Confusión de inicio súbito: acudir a urgencias inmediatamente', 'Confusión acompañada de fiebre alta', 'Confusión después de un golpe en la cabeza', 'Cualquier episodio de confusión nuevo'],
    cuandoVerMedicoEn: ['Sudden onset confusion: go to emergency immediately', 'Confusion accompanied by high fever', 'Confusion after a blow to the head', 'Any new episode of confusion'],
    autoCuidadoEs: ['Mantener al paciente seguro y acompañado', 'Hablarle con calma y frases sencillas', 'Mantener un ambiente tranquilo y bien iluminado', 'No dejar solo a alguien confundido'],
    autoCuidadoEn: ['Keep the patient safe and accompanied', 'Speak calmly using simple sentences', 'Maintain a quiet well-lit environment', 'Do not leave a confused person alone'],
    preguntasParaMedicoEs: ['¿Cuál es la causa más probable de la confusión?', '¿Se necesitan estudios de imagen del cerebro?', '¿Podría ser un efecto secundario de algún medicamento?'],
    preguntasParaMedicoEn: ['What is the most likely cause of the confusion?', 'Are brain imaging studies needed?', 'Could it be a side effect of a medication?'],
    sintomasRelacionados: ['perdida-de-memoria', 'fiebre', 'dolor-de-cabeza', 'desmayo'],
    sistemasCorporales: ['neurológico']
  },
  {
    id: 'perdida-de-memoria',
    nombreEs: 'Pérdida de memoria',
    nombreEn: 'Memory loss',
    descripcionEs: 'Dificultad para recordar información, eventos recientes o pasados. Puede ser temporal o progresiva y afectar la vida diaria.',
    descripcionEn: 'Difficulty remembering information, recent or past events. It can be temporary or progressive and affect daily life.',
    categorias: ['neurológico'],
    urgencia: 'media',
    causasComunesEs: ['Envejecimiento normal', 'Estrés y ansiedad', 'Falta de sueño', 'Depresión', 'Deficiencia de vitamina B12', 'Demencia o enfermedad de Alzheimer'],
    causasComunesEn: ['Normal aging', 'Stress and anxiety', 'Lack of sleep', 'Depression', 'Vitamin B12 deficiency', 'Dementia or Alzheimer disease'],
    cuandoVerMedicoEs: ['Olvidos que interfieren con las actividades diarias', 'Pérdida de memoria que empeora progresivamente', 'Dificultad para realizar tareas familiares', 'Confusión sobre fechas o lugares conocidos'],
    cuandoVerMedicoEn: ['Forgetfulness interfering with daily activities', 'Memory loss that progressively worsens', 'Difficulty performing familiar tasks', 'Confusion about dates or familiar places'],
    autoCuidadoEs: ['Mantener la mente activa con lectura y juegos', 'Hacer ejercicio regularmente', 'Dormir suficiente', 'Usar agendas y recordatorios', 'Mantener relaciones sociales activas'],
    autoCuidadoEn: ['Keep the mind active with reading and games', 'Exercise regularly', 'Get enough sleep', 'Use planners and reminders', 'Maintain active social relationships'],
    preguntasParaMedicoEs: ['¿Mi pérdida de memoria es parte del envejecimiento normal?', '¿Debería hacerme una evaluación neuropsicológica?', '¿Hay medicamentos que puedan ayudar?'],
    preguntasParaMedicoEn: ['Is my memory loss part of normal aging?', 'Should I get a neuropsychological evaluation?', 'Are there medications that can help?'],
    sintomasRelacionados: ['confusion', 'depresion', 'perdida-de-concentracion', 'dolor-de-cabeza'],
    sistemasCorporales: ['neurológico']
  },
  {
    id: 'temblores',
    nombreEs: 'Temblores',
    nombreEn: 'Tremors',
    descripcionEs: 'Movimientos rítmicos e involuntarios de una o varias partes del cuerpo. Pueden ser finos o gruesos y empeorar con el estrés o la fatiga.',
    descripcionEn: 'Rhythmic involuntary movements of one or more body parts. They can be fine or coarse and worsen with stress or fatigue.',
    categorias: ['neurológico'],
    urgencia: 'media',
    causasComunesEs: ['Temblor esencial (hereditario)', 'Enfermedad de Parkinson', 'Consumo excesivo de cafeína', 'Ansiedad', 'Hipertiroidismo', 'Efectos de medicamentos'],
    causasComunesEn: ['Essential tremor (hereditary)', 'Parkinson disease', 'Excessive caffeine intake', 'Anxiety', 'Hyperthyroidism', 'Medication effects'],
    cuandoVerMedicoEs: ['Temblor que empeora con el tiempo', 'Temblor que dificulta actividades diarias', 'Temblor acompañado de rigidez o lentitud de movimientos', 'Temblor de inicio repentino'],
    cuandoVerMedicoEn: ['Tremor that worsens over time', 'Tremor that hinders daily activities', 'Tremor accompanied by stiffness or slowness of movement', 'Sudden onset tremor'],
    autoCuidadoEs: ['Reducir el consumo de cafeína', 'Practicar técnicas de relajación', 'Dormir adecuadamente', 'Evitar sustancias que empeoren el temblor'],
    autoCuidadoEn: ['Reduce caffeine intake', 'Practice relaxation techniques', 'Get adequate sleep', 'Avoid substances that worsen the tremor'],
    preguntasParaMedicoEs: ['¿Qué tipo de temblor tengo?', '¿Necesito ver a un neurólogo?', '¿Podría ser enfermedad de Parkinson?'],
    preguntasParaMedicoEn: ['What type of tremor do I have?', 'Do I need to see a neurologist?', 'Could it be Parkinson disease?'],
    sintomasRelacionados: ['debilidad', 'rigidez', 'ansiedad', 'debilidad-muscular'],
    sistemasCorporales: ['neurológico']
  },
  {
    id: 'entumecimiento',
    nombreEs: 'Entumecimiento',
    nombreEn: 'Numbness',
    descripcionEs: 'Pérdida parcial o total de la sensibilidad en una zona del cuerpo. Puede sentirse como si la zona estuviera dormida.',
    descripcionEn: 'Partial or total loss of sensation in an area of the body. It may feel as if the area has fallen asleep.',
    categorias: ['neurológico'],
    urgencia: 'media',
    causasComunesEs: ['Compresión de nervios (como síndrome del túnel carpiano)', 'Postura inadecuada prolongada', 'Neuropatía diabética', 'Hernia de disco', 'Deficiencia de vitamina B12', 'Esclerosis múltiple'],
    causasComunesEn: ['Nerve compression (like carpal tunnel syndrome)', 'Prolonged poor posture', 'Diabetic neuropathy', 'Herniated disc', 'Vitamin B12 deficiency', 'Multiple sclerosis'],
    cuandoVerMedicoEs: ['Entumecimiento súbito en un lado del cuerpo', 'Entumecimiento progresivo', 'Entumecimiento acompañado de debilidad', 'Pérdida de control de esfínteres'],
    cuandoVerMedicoEn: ['Sudden numbness on one side of the body', 'Progressive numbness', 'Numbness accompanied by weakness', 'Loss of bladder or bowel control'],
    autoCuidadoEs: ['Cambiar de posición frecuentemente', 'Hacer ejercicios de estiramiento', 'Mantener un buen control de la diabetes si aplica', 'Usar muñequeras ergonómicas si es necesario'],
    autoCuidadoEn: ['Change positions frequently', 'Do stretching exercises', 'Maintain good diabetes control if applicable', 'Use ergonomic wrist supports if needed'],
    preguntasParaMedicoEs: ['¿Podría tener un nervio comprimido?', '¿Necesito estudios de conducción nerviosa?', '¿Está relacionado con mi diabetes?'],
    preguntasParaMedicoEn: ['Could I have a compressed nerve?', 'Do I need nerve conduction studies?', 'Is it related to my diabetes?'],
    sintomasRelacionados: ['hormigueo', 'debilidad', 'dolor-de-espalda', 'debilidad-muscular'],
    sistemasCorporales: ['neurológico', 'musculoesquelético']
  },
  {
    id: 'hormigueo',
    nombreEs: 'Hormigueo (parestesia)',
    nombreEn: 'Tingling (paresthesia)',
    descripcionEs: 'Sensación anormal de picor, punzadas o cosquilleo en la piel, generalmente en manos, pies, brazos o piernas.',
    descripcionEn: 'Abnormal sensation of prickling, stinging, or tickling in the skin, usually in hands, feet, arms, or legs.',
    categorias: ['neurológico'],
    urgencia: 'baja',
    causasComunesEs: ['Presión temporal sobre un nervio', 'Neuropatía periférica', 'Síndrome del túnel carpiano', 'Deficiencias vitamínicas', 'Mala circulación', 'Ansiedad'],
    causasComunesEn: ['Temporary pressure on a nerve', 'Peripheral neuropathy', 'Carpal tunnel syndrome', 'Vitamin deficiencies', 'Poor circulation', 'Anxiety'],
    cuandoVerMedicoEs: ['Hormigueo persistente o recurrente', 'Hormigueo que se extiende progresivamente', 'Hormigueo con debilidad asociada', 'Hormigueo en ambos lados del cuerpo'],
    cuandoVerMedicoEn: ['Persistent or recurrent tingling', 'Tingling that spreads progressively', 'Tingling with associated weakness', 'Tingling on both sides of the body'],
    autoCuidadoEs: ['Cambiar de posición para aliviar la presión', 'Hacer pausas activas durante el trabajo', 'Mantener una buena postura', 'Hacer ejercicios de estiramiento'],
    autoCuidadoEn: ['Change position to relieve pressure', 'Take active breaks during work', 'Maintain good posture', 'Do stretching exercises'],
    preguntasParaMedicoEs: ['¿Podría ser neuropatía?', '¿Necesito pruebas de nervios?', '¿Debería tomar suplementos vitamínicos?'],
    preguntasParaMedicoEn: ['Could it be neuropathy?', 'Do I need nerve tests?', 'Should I take vitamin supplements?'],
    sintomasRelacionados: ['entumecimiento', 'debilidad-muscular', 'dolor-de-espalda', 'calambres'],
    sistemasCorporales: ['neurológico']
  },
  {
    id: 'convulsiones',
    nombreEs: 'Convulsiones',
    nombreEn: 'Seizures',
    descripcionEs: 'Episodios de actividad eléctrica anormal en el cerebro que causan movimientos involuntarios, cambios en el comportamiento, sensaciones o estados de conciencia.',
    descripcionEn: 'Episodes of abnormal electrical activity in the brain causing involuntary movements, changes in behavior, sensations, or states of consciousness.',
    categorias: ['neurológico'],
    urgencia: 'emergencia',
    causasComunesEs: ['Epilepsia', 'Fiebre alta (convulsiones febriles en niños)', 'Traumatismo craneal', 'Niveles anormales de electrolitos', 'Infección cerebral', 'Abstinencia de alcohol o drogas'],
    causasComunesEn: ['Epilepsy', 'High fever (febrile seizures in children)', 'Head trauma', 'Abnormal electrolyte levels', 'Brain infection', 'Alcohol or drug withdrawal'],
    cuandoVerMedicoEs: ['Toda convulsión requiere evaluación médica', 'Convulsión que dura más de 5 minutos: llamar al 911', 'Primera convulsión en la vida', 'Convulsiones repetidas sin recuperación entre ellas'],
    cuandoVerMedicoEn: ['All seizures require medical evaluation', 'Seizure lasting more than 5 minutes: call 911', 'First seizure in life', 'Repeated seizures without recovery between them'],
    autoCuidadoEs: ['Durante una convulsión: proteger la cabeza, no introducir nada en la boca', 'Poner a la persona de lado después de la convulsión', 'Tomar la medicación antiepiléptica según indicaciones', 'Evitar desencadenantes conocidos'],
    autoCuidadoEn: ['During a seizure: protect the head, do not put anything in the mouth', 'Place the person on their side after the seizure', 'Take antiepileptic medication as directed', 'Avoid known triggers'],
    preguntasParaMedicoEs: ['¿Qué tipo de convulsiones tengo?', '¿Necesitaré medicación a largo plazo?', '¿Puedo conducir con este diagnóstico?'],
    preguntasParaMedicoEn: ['What type of seizures do I have?', 'Will I need long-term medication?', 'Can I drive with this diagnosis?'],
    sintomasRelacionados: ['confusion', 'perdida-de-memoria', 'dolor-de-cabeza', 'desmayo'],
    sistemasCorporales: ['neurológico']
  }
];
