import { EducationalContent } from '../types';

export const TELEMEDICINE_BASICS: EducationalContent = {
  id: 'digital-health-telemedicine-basics',
  type: 'concept',
  name: 'Telemedicine Basics',
  alternateNames: ['Telehealth Fundamentals', 'Virtual Healthcare', 'Remote Medicine', 'Digital Doctor Visits'],
  levels: {
    1: {
      level: 1,
      summary: 'Telemedicine is a way to see a doctor or nurse using a computer, phone, or tablet instead of going to a clinic in person.',
      explanation: 'Telemedicine lets you talk to healthcare providers without leaving your home. Instead of traveling to a doctor\'s office, you can use your computer, tablet, or smartphone to have a video visit, like a video call with a friend. You can see and hear the doctor, and they can see and hear you. Some telemedicine visits use just phone calls or text messages. Doctors can use telemedicine to check how you are feeling, answer your questions, look at minor problems like rashes or colds, and even prescribe medicine. Telemedicine is especially helpful when you live far from a doctor, have trouble traveling, or when it is not safe to go to a clinic. It has been around for a while but became much more popular when people needed to stay home during the COVID-19 pandemic.',
      keyTerms: [
        { term: 'video visit', definition: 'A medical appointment conducted through video call technology' },
        { term: 'doctor', definition: 'A healthcare provider who diagnoses and treats patients' },
        { term: 'remote', definition: 'From a distance; not in the same physical location' },
        { term: 'phone', definition: 'A device used to communicate with healthcare providers from home' },
        { term: 'computer', definition: 'A device that can be used for video visits with doctors' },
      ],
    },
    2: {
      level: 2,
      summary: 'Telemedicine enables healthcare delivery through electronic communications, allowing patients to receive medical consultations, diagnoses, and treatment recommendations remotely.',
      explanation: 'Telemedicine uses technology to connect patients with healthcare providers without requiring in-person visits. The main types include synchronous telemedicine, where patients and providers communicate in real-time through video or phone calls; asynchronous telemedicine (store-and-forward), where patients send information like photos or messages that providers review later; and remote patient monitoring, where devices send health data to providers automatically. Telemedicine can address many healthcare needs including primary care visits for minor illnesses, mental health counseling, chronic disease management follow-ups, specialist consultations, and medication management. Benefits include increased access to care (especially for rural or mobility-limited patients), convenience, reduced travel time and costs, and decreased exposure to contagious illnesses in waiting rooms. Limitations include inability to perform physical examinations, technology barriers for some patients, and the fact that some conditions require in-person evaluation. Telemedicine visits are covered by many insurance plans, including Medicare, though coverage rules vary.',
      keyTerms: [
        { term: 'synchronous', definition: 'Real-time communication where patient and provider interact simultaneously' },
        { term: 'asynchronous', definition: 'Communication where information is sent and reviewed at different times' },
        { term: 'store-and-forward', definition: 'Sending patient information for provider review at a later time' },
        { term: 'remote monitoring', definition: 'Tracking patient health data from a distance using devices' },
        { term: 'video visit', definition: 'A live video call between patient and healthcare provider' },
        { term: 'access to care', definition: 'The ability to obtain needed healthcare services' },
        { term: 'insurance coverage', definition: 'Financial protection that pays for healthcare services' },
      ],
    },
    3: {
      level: 3,
      summary: 'Telemedicine encompasses multiple delivery modalities, clinical applications across specialties, and regulatory frameworks governing licensure, reimbursement, and practice standards for remote healthcare delivery.',
      explanation: 'The telemedicine landscape includes distinct service delivery models with different clinical applications and technical requirements. Synchronous services (live video) enable real-time patient-provider interaction across most medical specialties, with particularly strong evidence and adoption in mental health, primary care, and urgent care. Asynchronous (store-and-forward) models are prevalent in specialties relying on image interpretation, including dermatology, radiology, pathology, and ophthalmology, allowing efficient specialist review without scheduling constraints. Remote patient monitoring provides continuous or periodic data collection for chronic disease management, post-acute care, and high-risk patient surveillance. Clinical appropriateness varies by condition: telemedicine works well for many cognitive-based services, medication management, and visual assessments, while conditions requiring physical examination, procedures, or laboratory testing typically need in-person care. The regulatory environment includes federal and state licensure requirements (providers generally must be licensed in the patient\'s state), prescribing regulations affecting controlled substances, and evolving reimbursement policies. Medicare and most commercial payers now cover many telemedicine services, though reimbursement parity with in-person visits varies. Quality standards address technology requirements, clinical protocols, privacy protections, and documentation practices for telemedicine encounters.',
      keyTerms: [
        { term: 'live video', definition: 'Real-time video connection enabling interactive patient-provider encounters' },
        { term: 'store-and-forward', definition: 'Asynchronous transmission of patient data for specialist review' },
        { term: 'clinical appropriateness', definition: 'Determination of whether a condition can be adequately managed via telemedicine' },
        { term: 'licensure requirements', definition: 'Legal obligations for providers to hold valid licenses in patient locations' },
        { term: 'reimbursement parity', definition: 'Equal payment for telehealth and in-person services' },
        { term: 'prescribing regulations', definition: 'Rules governing remote prescription of medications including controlled substances' },
        { term: 'quality standards', definition: 'Guidelines for technology, protocols, privacy, and documentation in telehealth' },
      ],
    },
    4: {
      level: 4,
      summary: 'Academic analysis of telemedicine addresses effectiveness evidence across clinical domains, implementation science considerations, policy and regulatory frameworks, and telemedicine\'s role in healthcare system transformation.',
      explanation: 'The telemedicine evidence base has expanded substantially, with systematic reviews and meta-analyses addressing efficacy across clinical domains. Strong evidence supports telepsychiatry effectiveness comparable to in-person care for depression, anxiety, and other mental health conditions. Telestroke programs demonstrate improved outcomes through rapid neurologist consultation for acute stroke patients in facilities without on-site specialists. Primary care telemedicine shows equivalent patient satisfaction and clinical outcomes for appropriate conditions, though questions persist about diagnostic accuracy and appropriate use boundaries. Implementation science frameworks help explain variation in telemedicine adoption and sustainability, identifying facilitators (organizational leadership, workflow integration, technical infrastructure) and barriers (clinician resistance, patient technology access, regulatory constraints). Policy analysis examines how regulatory structures shape telemedicine development, including interstate licensure compacts, Ryan Haight Act provisions for controlled substance prescribing, and the role of temporary pandemic flexibilities in accelerating adoption. Economic analyses address cost-effectiveness from multiple perspectives: patient savings from avoided travel, health system efficiency gains, and societal costs and benefits. Critical perspectives examine whether telemedicine expansion may exacerbate disparities if adoption varies by socioeconomic status, technology access, or digital literacy, and whether commercial telehealth platforms may fragment care delivery.',
      keyTerms: [
        { term: 'effectiveness evidence', definition: 'Research demonstrating clinical outcomes of telemedicine interventions' },
        { term: 'implementation science', definition: 'Study of methods to promote adoption of evidence-based practices' },
        { term: 'interstate licensure compacts', definition: 'Agreements allowing physicians to practice across state lines' },
        { term: 'Ryan Haight Act', definition: 'Federal law regulating online prescribing of controlled substances' },
        { term: 'pandemic flexibilities', definition: 'Temporary regulatory relaxations enabling expanded telehealth access' },
        { term: 'cost-effectiveness', definition: 'Economic analysis comparing costs and outcomes of different care approaches' },
        { term: 'health equity', definition: 'Fair and just opportunity for everyone to achieve optimal health' },
        { term: 'care fragmentation', definition: 'Disconnected healthcare delivery lacking coordination across providers' },
      ],
    },
    5: {
      level: 5,
      summary: 'Clinical leadership in telemedicine requires strategic development of service lines, quality assurance systems, workflow integration, and ongoing adaptation to evolving evidence, technology, and regulatory environments.',
      explanation: 'Building effective telemedicine programs demands systematic attention to clinical, operational, and strategic dimensions. Service line development should identify clinical areas where telemedicine offers clear value based on evidence, patient demand, and organizational capabilities, prioritizing high-impact applications with established effectiveness. Clinical protocol development must address appropriate use criteria, establishing which conditions and presentations are suitable for telemedicine versus requiring in-person evaluation, with clear pathways for escalation. Workflow integration requires embedding telemedicine into routine clinical operations rather than treating it as a separate service, including scheduling systems, documentation templates, and care coordination processes. Quality assurance systems should monitor clinical outcomes, patient experience, technical performance, and appropriate use, with continuous improvement processes addressing identified issues. Clinician training should address both technical competencies and adapted clinical skills for telemedicine encounters, including virtual physical examination techniques and building rapport through video. Patient experience optimization includes technology support, clear instructions, and accessibility accommodations for individuals with disabilities or limited technology access. Regulatory compliance requires ongoing attention to evolving licensure, prescribing, and billing requirements at federal and state levels. Strategic planning should anticipate continued evolution of telemedicine capabilities, considering hybrid care models, integration with remote monitoring, and specialty-specific applications.',
      keyTerms: [
        { term: 'service line development', definition: 'Strategic planning and implementation of specific telemedicine offerings' },
        { term: 'appropriate use criteria', definition: 'Guidelines defining which conditions are suitable for telemedicine' },
        { term: 'workflow integration', definition: 'Embedding telemedicine into routine clinical operations' },
        { term: 'quality assurance', definition: 'Systems monitoring clinical outcomes and performance standards' },
        { term: 'clinician training', definition: 'Education on technical and clinical skills for telemedicine delivery' },
        { term: 'patient experience', definition: 'Overall perception and satisfaction with telemedicine encounters' },
        { term: 'regulatory compliance', definition: 'Adherence to licensure, prescribing, and billing requirements' },
        { term: 'hybrid care models', definition: 'Combination of in-person and virtual care delivery approaches' },
      ],
      clinicalNotes: 'When conducting telemedicine visits, ensure appropriate patient selection based on clinical needs and technical capabilities. Optimize audio/video quality and minimize distractions. Adapt examination techniques for virtual environment, using patient self-examination guidance where appropriate. Document telemedicine visits thoroughly, including modality used and any limitations encountered. Know when to recommend in-person follow-up for conditions requiring physical examination or procedures. Verify patient location for licensure compliance and emergency protocols.',
    },
  },
  media: [],
  citations: [
    {
      id: 'tuckson-2017',
      type: 'article',
      title: 'Telehealth',
      authors: ['Tuckson RV', 'et al.'],
      source: 'N Engl J Med',
      page: '377(16):1585-1592',
    },
    {
      id: 'bashshur-2014',
      type: 'article',
      title: 'The Empirical Foundations of Telemedicine Interventions for Chronic Disease Management',
      authors: ['Bashshur RL', 'et al.'],
      source: 'Telemed J E Health',
      page: '20(9):769-800',
    },
    {
      id: 'cms-2023',
      type: 'website',
      title: 'Telehealth Services',
      authors: ['Centers for Medicare & Medicaid Services'],
      source: 'Medicare Learning Network',
    },
    {
      id: 'ama-2020',
      type: 'website',
      title: 'Telehealth Implementation Playbook',
      authors: ['American Medical Association'],
      source: 'AMA',
    },
  ],
  crossReferences: [
    { targetId: 'virtual-visits', targetType: 'concept', relationship: 'related', label: 'Virtual Visits' },
    { targetId: 'telehealth-regulations', targetType: 'concept', relationship: 'related', label: 'Telehealth Regulations' },
    { targetId: 'telehealth-technologies', targetType: 'concept', relationship: 'related', label: 'Telehealth Technologies' },
    { targetId: 'remote-patient-monitoring', targetType: 'concept', relationship: 'related', label: 'Remote Patient Monitoring' },
  ],
  tags: {
    systems: ['digital-health'],
    topics: ['telemedicine', 'telehealth', 'virtual-care', 'remote-healthcare', 'healthcare-access'],
    keywords: ['video visits', 'remote medicine', 'telehealth', 'virtual healthcare', 'patient access'],
  },
  createdAt: '2025-01-28T00:00:00.000Z',
  updatedAt: '2025-01-28T00:00:00.000Z',
  version: 1,
  status: 'published',
  contributors: ['Biological Self Content Team'],
};
